### ISSUE TITLE
Create preview url in PR's

### ISSUE THREAD

**Issue by MuhammadAHussain** [bbc/simorgh#10008]
**Is your feature request related to a problem? Please describe.**
We want to be able to view feature branches on test via a url link attached to the PR. This will make easier for reviewing and testing features.

**Describe the solution you'd like**
When a PR has been created, a link is generated and attached to the PR (similar to the GitHub actions we currently have). Anyone should be able to click the link which will take them to the test environment with the branch changes.

Possible approaches:
- AWS Lambda to build and deploy the branch via CodeBuild to a new instance of EC2?
- Use docker to build, deploy and run on EC2?

Previous issue: https://github.com/bbc/simorgh-infrastructure/issues/1464

Approach we are investigating:
- Running simorgh on docker container.

**Next steps**
- Create Docker container.
- Get Simorgh repo on container.
- Be able to build and run simorgh on the container.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by DarioR01** [comment]
Moving it somewhere
