### ISSUE TITLE
High Impact Promo - Adjust Layout for mid breakpoints

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#10014]
**Is your feature request related to a problem? Please describe.**
We want to update the mid breakpoints for the high impact promos to improve the visual appearance. 
A large proportion of our audience use larger device types that support these mid breakpoints. 

**Describe the solution you'd like**

Update to using the latest designs: https://zpl.io/p1mneJr

**Acceptance Criteria**:
Given I am viewing a CPS or Optimo article at 600px
When I view the features and analysis section
then the high impact promo designs meet the specifications [here](https://zpl.io/r17W6ZX)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by greenc05** [comment]
Have we specified what order will the promos should read by a screen reader?

**Comment by amoore108** [comment]
> Have we specified what order will the promos should read by a screen reader?

I don't think this was specified originally, however the promos will read out in the same order as they currently do in the list layout. Is this ok, or should they be read out differently when in 2 columns side by side on tablet?

**Comment by greenc05** [comment]
Thanks @amoore108 No it shoud be consisent, so it will read the first row then move onto the 2nd row?

**Comment by amoore108** [comment]
> Thanks @amoore108 No it shoud be consisent, so it will read the first row then move onto the 2nd row?

Yep thats right, it'll go:
1 2
3 4
5 6
etc
