### ISSUE TITLE
Update Optimo scenarios with additional features

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1005]
**Is your feature request related to a problem? Please describe.**
When creating the scenario articles in Optimo Test, several features were not yet available:
* Image captions containing urlLinks (Scenarios 8 and 20)
* Subscript and superscript
* Summaries

**Describe the solution you'd like**
Add them

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by jimjohnsonrollings** [comment]
Fixture Scenario | Test Optimo ID 
-- | --
c0000000001o | cnm5l5djlgxo
c0000000002o | c5mk3kl3w3ko
c0000000003o | c6eplpm44vlo
c0000000004o | c4vzwzjp2m6o
c0000000005o | cq80n03rj0qo
c0000000006o | c5m4y4y36kko
c0000000007o | c1d36dmmry5o
c0000000008o | cge525m34kzo
c0000000009o | cj3g8gymk66o
c0000000010o | c7zj2z16p7jo
c0000000011o | c457lnly75po
c0000000012o | cq3g5kd10v1o
c0000000013o | cr102p9d55eo
c0000000014o | c91n655l2r1o
c0000000015o | c0r60n52n51o
c0000000016o | ck6l5p9eg22o
c0000000017o | cq3gdp3zkm5o
c0000000018o | c91n6510z7wo
c0000000019o | c457ypqmmzeo
c0000000020o | cgq4r501egwo
c0000000021o | cjd8zd49d4qo
c0000000022o | cw2qrpznzqvo
c0000000023o | cpz770qwzypo
c0000000024o | c5nd2n466ppo
c0000000025o | c9rpqy7pmypo
c0000000026o | cd2dyze7347o
c0000000027o | c85pqyj5m2ko
c0000000028o | cwv2xv848j5o

**Comment by ChrisBAshton** [comment]
Assigning to Jim to see if still blocked.

**Comment by jimjohnsonrollings** [comment]
I think we can just close this.  We can do them individually if/when Optimo implements them.
