### ISSUE TITLE
Pagination unnecessary ellipsis

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#10053]
**Describe the bug**
For some combinations of page items & screen sizes, we are rendering an unnecessary ellipsis where we could just show a number in it's place. 

From this page - https://www.test.bbc.com/pidgin/new_topics/c1gdqg448w1t
<img width="498" alt="Screenshot 2022-04-20 at 09 27 11" src="https://user-images.githubusercontent.com/52488258/164185535-1acbc565-dba3-4e1a-b318-288f0b1a3c39.png">

From this page - https://www.test.bbc.com/pidgin/new_topics/c2dwqd1q11qt
<img width="283" alt="Screenshot 2022-04-20 at 09 27 46" src="https://user-images.githubusercontent.com/52488258/164185715-b9f3897c-6ea8-4ac5-a573-6ef85aff07bc.png">

We'd like to update the component so this doesn't happen. 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by RetiredBlob** [comment]
https://github.com/bbc/simorgh/blob/latest/src/app/pages/TopicPage/Pagination/buildBlocks.js#L70:L72

**Comment by pvaliani** [comment]
https://github.com/bbc/simorgh/pull/10055
