### ISSUE TITLE
Validator bug when handling properties that are arrays

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1006]
**Describe the bug**
While trying to implement https://github.com/BBC-News/simorgh/issues/404 it was realised that `properties` that are of type `array` currently cause a bug due to the way the props are passed onwards from the `validateProperties` function. 

**To Reproduce**

1. `git checkout c47a53cd9f0ff9b37b336518f332981727782580` 
2. locally change the following to be `type: array` 
https://github.com/BBC-News/simorgh/blob/c47a53cd9f0ff9b37b336518f332981727782580/data/schema.yaml#L232
3. `npm run dataValidate`
4. See following error:
```
./././data/prod/news/articles/c85pqyj5m2ko.json
Error: Type does not match for ':article:content:model:blocks' - expected 'array' got 'object'
```

**Expected behaviour**
This should not error following this work and #1008 which enabled array validation support. **Please note** testing this is very finicky as it is a bug around the validation of a properties that are handled in the validator as "blocks". I would highly suggest manual testing this to be performed within #1008 

**Additional context**
This can be manually tested be following the `Steps to reproduce` and ensuring no error, however the main thing this does is unblock https://github.com/BBC-News/simorgh/issues/404

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
So that I understand this correctly...

In c85pqyj5m2ko.json, `article.content.model.blocks` is an array:

![screen shot 2018-11-27 at 12 59 37](https://user-images.githubusercontent.com/5111927/49083384-55718100-f244-11e8-85fe-27e484d63992.png)

It is also an object, which is why [line 232](https://github.com/BBC-News/simorgh/blob/latest/data/schema.yaml#L232) is currently passing.
When we change it to `array` (a more specific type of object), it fails - but should pass, as it is indeed an array.

Is that right?

**Comment by pjlee11** [comment]
Not quite, following your question actually shows this is hard to test without being considered as part of https://github.com/BBC-News/simorgh/pull/1008 which adds the `Array.isArray` checks. Maybe this should be tested as part of 1008.

The bug is that it currently passes the `dataNode` where it should be passing `dataNode.property`. This means that when it is checking the `blocks` schema definition it actually calls `validateNode` (via `validateProperty`) with the value of `model` which is `{ blocks: [...] }`

## Detailed explanation 
```
const data = { 
    "node": {
        "property": [],
    },
};

const schema = {
    node: {
        type: 'object',
        properties: {
            property: {
                type: array,
            },
        },
    },
};
```

When validating `node` from the data, the function `validateNode` is passed `{ "property": [] }` and checks the type is `object`. Then due to the nesting, `validateProperty` invokes `validateNode` and incorrectly passes the data as in `{ "property": [] }` and checks it's type is `array`. Therefore, `validateProperty` should pass in the data as `node.property` which would mean it `validateNode` gets `[]` and checks it's type is `array`

**Comment by ChrisBAshton** [comment]
Ok I think I understand now. Thanks
