### ISSUE TITLE
Remove temporary `new_topics` route when all services are using Simorgh powered topics pages

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#10061]
**Is your feature request related to a problem? Please describe.**
When all services are using Simorgh topics pages, we need to remove the temporary topics (`/new_topics/`) route that was set up in [this PR](https://github.com/bbc/simorgh/pull/10060) 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by rebeccamcginn** [comment]
Done here - https://github.com/bbc/simorgh/pull/10411

@pvaliani ticket can be closed :)
