### ISSUE TITLE
Article & AMP styling clash on inline links on AMP articles

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1010]
**Describe the bug**
There is a dual highlight displayed if a user highlights an inline link on an article AMP page.

**To Reproduce**

1. Go to 'http://localhost:7080/news/articles/c85pqyj5m2ko.amp'
2. Highlight an inline link. (Press and hold on mobile devices)
3. Observe the highlight styles

**Expected behaviour**
There should be *one* visible style when the user highlights an inline link.
**Actual behaviour**
There are two highlights. One from AMP itself and the other from the Article styles.

![royal_wedding_flowers_given_to_hackney_hospice_ _bbc_news](https://user-images.githubusercontent.com/25743793/49090808-62976b80-f256-11e8-8cc2-10d3335fb1f6.jpg)

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by sareh** [comment]
Closed since issue is now in Psammead: https://github.com/BBC-News/psammead/issues/222
