### ISSUE TITLE
CORs error on simorgh TEST/LIVE on client request

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1012]
**Describe the bug**
Currently simorgh is hosted on `bbci.co.uk` and makes data requests over `.com` this causing CORs errors on the client side requests and causes our inline link tests to fail - #1011. We should fix this.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://simorgh.api.bbci.co.uk/news/articles/c85pqyj5m2ko
2. Open browser console
3. Click on the first link in the body

**Expected behaviour**
We should not get a CORs error and the page should render for client side requests. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/49096215-076b7600-f262-11e8-9a15-4c68ce9a4b05.png)

**Solution**
** Mozart are doing some work to allow cross origin requests for the JSON data from the simorgh application in https://jira.dev.bbc.co.uk/browse/RESFRAME-2513. Following this work being done we need to allow cors in the client side fetch. Change [this code](https://github.com/BBC-News/simorgh/blob/latest/src/app/routes/getInitialData/index.js#L11) to be: 
`fetch(url, { mode: "cors" })` as per the [fetch documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch). Once we've made this change we will need to take over test and build the feature branch to the Test endpoint and then run the E2E's with the inline link added back in (#1011), this will prove that the application can correctly request the data cross origin.

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
Done in https://github.com/bbc/mozart-routing/pull/713 and https://github.com/bbc/mozart-smoke-test/pull/74
