### ISSUE TITLE
Remove Markdown-to-JSX

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1016]
**Is your feature request related to a problem? Please describe.**
When solving text formatting, we initially went down the markdown route before realising it would not scale for i18n.

Optimo and Ares now return fragment blocks, i.e. text is associated with an `attributes` array which might contain `italic`, `bold`, etc. It no longer returns markdown such as `_italic_` or `*bold*`.

For legacy reasons, we still have markdown rendering in our Text component, which means we go from attributes -> markdown -> JSX. We should just go from attributes -> JSX directly.

**Describe the solution you'd like**

1. `npm uninstall markdown-to-jsx`
2. Update `components/Text` to not use Markdown anymore.
3. Update `containers/Text` to pull in `containers/InlineLink/index.new.jsx` (as opposed to `index.jsx`)
4. Update Text README.md.
5. Remove [reference to markdown in Caption comment](https://github.com/BBC-News/simorgh/blob/6de3063b80084f7017cea0554c86d8d01339bb9c/src/app/components/Figure/Caption/index.jsx#L40).

NB: we'll also want to make sure we have no markdown in any of our `data/`.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Regression tests only.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Blocked on the investigation https://github.com/BBC-News/simorgh/issues/1021

**Comment by ChrisBAshton** [comment]
Investigation happened in #1027 - now unblocked.
