### ISSUE TITLE
Investigate overriding component styles without Markdown-to-JSX 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1021]
**EDIT:** 🚨 Important context below 👇🏻

**Is your feature request related to a problem? Please describe.**
As a precursor to #1016 we should investigate how to pass components as an override so that the fragment rendering logic is reuse-able by all text component variations.

**Describe the solution you'd like**
We need to better understand our [current use of Markdown-to-JSX](https://github.com/BBC-News/simorgh/blob/afe1647eb73ad01c790ffc4181119122e544ee6d/src/app/components/Text/index.jsx#L13-L31) and find a way to reproduce this behaviour without the need of the `Markdown-to-JSX` library
As a result of this, add more information on how to do this to #1017 

**Describe alternatives you've considered**
We could keep the library but it feels like overkill and is just an artefact of when we had plans to receive markdown. However, we now receive fragments to render rich text so the library _should_ be obsolete 

**Testing notes**
[Tester to complete]

Dev insight: Testing is likely to happen in the implementation ticket #1016

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
@sareh & I have ended up looking at this quite a bit as part of #887. It seems to only be used by the Horizontal Rule story, & the figure container (for figure caption). As such, if the caption is changed to correctly parse blocks, there is no need to keep the Text component (& with it, Markdown-to-JSX) at all.

Scenario 8 using fragmented data 🥳:
<img width="753" alt="screenshot 2018-11-30 at 17 22 24" src="https://user-images.githubusercontent.com/11646957/49305470-3df5fa80-f4c7-11e8-8c06-6a22e670c9a3.png">

Current remaining challenge is working out whether the Figure component tests are attempting to do more than they should, as they reach out & pull in the Figure container.

We've been working this through on a branch, & I'll try to split it out into incremental PRs next week.

**Comment by ChrisBAshton** [comment]
Figure story which pulls in caption-with-inline-link has now been removed in #1017.

Team meeting this morning, we discussed and agreed that the Figure component tests should _not_ pull in the Figure container (and indeed, no presentational component's tests/stories should pull in containers).

So this issue will be closed by a PR which removed markdown-to-jsx sometime this week.

**Comment by ChrisBAshton** [comment]
Oh, that's covered by #1016. Closing.
