### ISSUE TITLE
CORS issue on latest with some tools

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1041]
**Describe the bug**
[James observed an issue on latest](https://github.com/BBC-News/simorgh/pull/1030#issuecomment-443758324), where a CORS error can prevent second-page loads through inline links to other article pages.

![dashboard](https://user-images.githubusercontent.com/25743793/49384553-2612b680-f713-11e8-8502-fe9094b25512.jpg)

Does CORS config need to be added around `localhost`?

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by PriyaKR** [comment]
@PriyaKR To verify whether this still an issue.

**Comment by PriyaKR** [comment]
Can't replicate this issue on latest branch.

**Comment by dr3** [comment]
Closing as fixed long ago
