### ISSUE TITLE
Local Test Data errors

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1043]
**Describe the bug**
When I run simorgh locally and visit any of these following test pages, I see console errors

http://localhost:7080/news/articles/c0000000002o
http://localhost:7080/news/articles/c0000000003o
http://localhost:7080/news/articles/c0000000004o
http://localhost:7080/news/articles/c0000000005o
http://localhost:7080/news/articles/c0000000006o
http://localhost:7080/news/articles/c0000000009o
http://localhost:7080/news/articles/c0000000012o
http://localhost:7080/news/articles/c0000000013o
http://localhost:7080/news/articles/c0000000015o
http://localhost:7080/news/articles/c0000000016o
http://localhost:7080/news/articles/c0000000017o
http://localhost:7080/news/articles/c0000000018o
http://localhost:7080/news/articles/c0000000019o
http://localhost:7080/news/articles/c0000000022o

**To Reproduce**

1. `git checkout latest && npm ci && npm run dev`
2. Open dev console in a browser & visit http://localhost:7080/news/articles/c0000000002o
3. See error

```
Warning: Failed prop type: Invalid prop `data.data.content.model.blocks[2]` supplied to `ArticleContainer`.
    in ArticleContainer (created by Route)
    in Route (created by a)
    in Switch (created by a)
    in a (created by Route)
    in Route (created by withRouter(a))
    in withRouter(a) (created by s)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by s)
    in s (at client.js:21) proxyConsole.js:54
Warning: Failed prop type: Invalid prop `blocks[0]` supplied to `TextContainer`.
    in TextContainer (at Blocks/index.jsx:20)
    in Blocks (at Article/index.jsx:95)
    in div (created by GridItemConstrained)
    in GridItemConstrained (at Article/index.jsx:94)
    in div (created by Wrapper)
    in Wrapper (created by OatWrapper)
    in OatWrapper (at Article/index.jsx:93)
    in main (at Article/index.jsx:83)
    in PlatformContextProvider (at Article/index.jsx:76)
    in ServiceContextProvider (at Article/index.jsx:75)
    in ArticleContainer (created by Route)
    in Route (created by a)
    in Switch (created by a)
    in a (created by Route)
    in Route (created by withRouter(a))
    in withRouter(a) (created by s)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by s)
    in s (at client.js:21) proxyConsole.js:54
Warning: Failed prop type: Invalid prop `blocks[1]` supplied to `ParagraphContainer`.
    in ParagraphContainer (at Blocks/index.jsx:20)
    in Blocks (at Text/index.jsx:19)
    in TextContainer (at Blocks/index.jsx:20)
    in Blocks (at Article/index.jsx:95)
    in div (created by GridItemConstrained)
    in GridItemConstrained (at Article/index.jsx:94)
    in div (created by Wrapper)
    in Wrapper (created by OatWrapper)
    in OatWrapper (at Article/index.jsx:93)
    in main (at Article/index.jsx:83)
    in PlatformContextProvider (at Article/index.jsx:76)
    in ServiceContextProvider (at Article/index.jsx:75)
    in ArticleContainer (created by Route)
    in Route (created by a)
    in Switch (created by a)
    in a (created by Route)
    in Route (created by withRouter(a))
    in withRouter(a) (created by s)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by s)
    in s (at client.js:21)
```

**Expected behavior**
No such errors. 

**Screenshots**
Screenshot of the error pasted above. 
<img width="597" alt="screen shot 2018-12-04 at 12 28 07" src="https://user-images.githubusercontent.com/3028997/49441947-eb1a8c80-f7bf-11e8-9fa7-daa27a70e662.png">

**Desktop (please complete the following information):**

- OS: Mac OS X 
- Browser:  Firefox Nightly v 65 

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
Can confirm, still an issue.

**Comment by jimjohnsonrollings** [comment]
The error is no longer present for c0000000002o but remains present once for each of the other listed scenarios.

**Comment by RayNjeri** [comment]
The error is no longer present in any of the test pages.
