### ISSUE TITLE
Use react-testing-library for unit tests

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1049]
**Is your feature request related to a problem? Please describe.**
We should use react-testing-library for our unit tests.  https://github.com/kentcdodds/react-testing-library

The immediate effects will be that our snapshots will contain actual DOM nodes (e.g. `<h1>`) instead of React components (e.g. `<StyledHeading>`) this will remove the issue of having `<ForwardRef>` listed in our snapshots.

Additionally, react-testing-library makes it very simple to set up unit tests that are not snapshot-based, but actually test the rendered DOM output.  This makes it much easier to test the actual user-facing functionality of the component, rather than the specific implementation details we have used. There are examples on the documentation page https://github.com/kentcdodds/react-testing-library#example

I found this video to be a great introduction to the benefits of moving away from using enzyme to react-testing-library. https://youtu.be/LHUdxkThTM0 "Migrating from shallow rendering react components to explicit component mocks"

**Describe the solution you'd like**
To update our existing `shouldMatchSnapshot` & `isNull` [testHelpers](https://github.com/BBC-News/simorgh/blob/latest/src/app/helpers/tests/testHelpers.js) to use `react-testing-library`. 

**Describe alternatives you've considered**
We could choose to use enzyme instead. Having looked at react-testing-library, I'd suggest we consider this instead. 

**Testing notes**
[Tester to complete]

Dev insight: Our Cypress tests shouldn't need to change. We will just be updating our unit test helpers and the snapshots. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Superseded by https://github.com/BBC-News/psammead/issues/219
