### ISSUE TITLE
Reith font not loaded on AMP article when not cached

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1053]
BLOCKED ON https://github.com/bbc/simorgh/issues/1178

**Describe the bug**
Possibly related to #1169 and #1009.

If a user visits the site for the first time to view an AMP article, the Reith font is not loaded once the article has finished loading.

**To Reproduce**

1. On an Incognito Window, go to 'http://localhost:7080/news/articles/c9rpqy7pmypo.amp'
2. Observe font

**Expected behavior**
The Reith font should load.

![meghan_s_bouquet_laid_on_tomb_of_unknown_warrior_ _bbc_news](https://user-images.githubusercontent.com/25743793/49511319-ba4f5b80-f882-11e8-8e9b-2f225572f589.jpg)

**Comment by sareh** [comment]
Closed since this is the expected behaviour https://github.com/bbc/simorgh/issues/1178#issuecomment-455150635
