### ISSUE TITLE
Remove top & bottom padding inline links

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1055]
**Describe the bug**
Following the investigate performed in https://github.com/BBC-News/simorgh/issues/616 UX have confirmed we should remove the top and bottom padding from the inline link component.

**To Reproduce**
See screenshots and bug description on https://github.com/BBC-News/simorgh/issues/616

**Expected behaviour**
See screenshots and bug description on https://github.com/BBC-News/simorgh/issues/616

**Additional context**
This is the issue is related to both the caption text but also body text when it comes to multi-line links. 

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by sareh** [comment]
Closed since issue is now in Psammead: https://github.com/BBC-News/psammead/issues/222

**Comment by dr3** [comment]
Reopened due to https://github.com/BBC-News/psammead/issues/222 not being possible without larger font changes. This work however is small enough to just do for its minor benifits
