### ISSUE TITLE
Test our move from @BBC-News to @bbc

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1063]
**Is your feature request related to a problem? Please describe.**
We should move Psammead and Simorgh to the @bbc org, from @BBC-News.

(Note that **we should be absolutely sure @bbc supports everything we need**, and we should **try as much as we can with a dummy repo first**.)

Advantages of moving to @bbc:

* We can have one project board (preliminary investigation shows that the private repo issues would appear as "You can't see this card" for public)
* More shareable in the world of OPR (we might _have_ to do it anyway)
* More cohesive for new joiners and anyone in the BBC searching for our repos / infrastructure

Disadvantages:

* Having to port across CodeClimate, Greenkeeper, Slack, CodeClimate velocity integrations. There's also a question of how much we're able to put onto @bbc
* Having to update Jenkins, Snyk, CodeClimate, Slack web hooks
* Up front effort of moving repos, recreating labels (perhaps this will be automated by GitHub? 🤔) and getting the team back up to speed
* The Psammead infrastructure repo is probably going away, so the only benefit of the joined up Project view would be the Simorgh infrastructure repo

Team discussion.

**Hypothetical acceptance criteria**

- [x] Pull request check from CodeClimate
- [x] Pull request check from Snyk
- [x] Pull request check from Jenkins CI
- [x] Pull request check from Travis
- [x] Slack notifications from GitHub on issue open/close and on PR merge
- [ ] Slack notifications on Storybook deployment
- [x] Slack notifications on Jenkins build fail
- [x] Slack notifications on Travis build fail
- [x] Infrastructure pipeline points to the correct place
- [ ] Greenkeeper continues to open PRs (how do we test this?)
- [x] Psammead storybook deployment still works https://github.com/BBC-News/psammead/pull/194#pullrequestreview-184579921
- [x] Psammead npm publish still works (generating otp, etc)

**Comment by pjlee11** [comment]
~Add to checklist: `Slack notification when Jenkins successfully deploys to live`~ 

Edit: That handled in the Jenkinsfile and if unrelated to the home of the repo 🤦‍♂️

**Comment by ChrisBAshton** [comment]
Blocked on https://github.com/bbc/psammead/pull/241

(That will tell us if Psammead storybook publishing & slack notification is still working)

**Comment by ChrisBAshton** [comment]
Have raised https://github.com/bbc/simorgh/issues/1149 to fix the CodeClimate diff/coverage checker.

**Comment by ChrisBAshton** [comment]
Storybook was updated 🎉 

But no announcement in Slack

**Comment by ChrisBAshton** [comment]
Believe we've now fixed the Storybook announcement on Slack, but haven't tested it yet. Happy to close.
