### ISSUE TITLE
Ensure AMP articles link to AMP articles

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1070]
**Is your feature request related to a problem? Please describe.**
AMP articles don't link to AMP articles. While this hasn't been a requirement previously, it is a behaviour that has been queried several times. We should first establish if this is a behaviour we want, & one that AMP recommends/doesn't discourage.

Different to #1199!

**Describe the solution you'd like**
The Inline Link container ensures AMP pages link to AMP pages.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
This is awaiting work on the CMS to inform us the origin of the link, since we don't want to manually inspect the url field and change the url ourselves.

**Comment by jamesbhobbs** [comment]
We might reevaluate this long term, but for now this is what we want.
