### ISSUE TITLE
Remove speculate from Simorgh

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1072]
**Is your feature request related to a problem? Please describe.**
Remove speculate as a dependency for Simorgh. It should only be in our infrastructure pipeline. 

**Describe the solution you'd like**
Remove Speculate as a dependency. 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: The application should still build. 

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Is currently blocked on adding spectacle (not speculate) in our infrastructure.

**Comment by ChrisBAshton** [comment]
I believe we decided this was no longer required.
