### ISSUE TITLE
Add Container Stories to Simorgh Storybook, with dial for context switching

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1078]
**Is your feature request related to a problem? Please describe.**
As we have moved components over to the [Psammead component library](https://github.com/BBC-News/psammead), we have few items in our Simorgh Storybook: https://bbc.github.io/simorgh

We should include our container components in the Simorgh storybook. 

**Describe the solution you'd like**
Add stories to these containers only:
- BrandContainer - showing different context values e.g. News/Persian examples
- CopyrightContainer
- HeaderContainer
- FooterContainer

What would be ideal, would be to add a drop-down that could switch between services and populate these with the correct view. e.g. selecting `Persian` from the drop-down when looking at the BrandContainer will show you the `News | Persian` brand.

We shouldn't need stories for all of our containers (e.g. Blocks, or Fragments) since these are for handling our Optimo data.  

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Viewing Storybook, you should be able to see the different variants of the 
**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
> What would be ideal, would be to add a drop-down that could switch between services and populate these with the correct view. e.g. selecting Persian from the drop-down when looking at the BrandContainer will show you the News | Persian brand.

The Figure story in Simorgh is already a container story. If we want the dials to be consistent, we should update it to match the changes in this PR.

**Comment by jamesbhobbs** [comment]
@sareh perhaps good to create an issue for each in psammead and link them to this issue?

**Comment by thekp** [comment]
I separated this into smaller issues for each component that requires a story. 
https://github.com/bbc/simorgh/issues/2194
https://github.com/bbc/simorgh/issues/2195
https://github.com/bbc/simorgh/issues/2196
https://github.com/bbc/simorgh/issues/2197
