### ISSUE TITLE
Travis CI builds are slow

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#109]
**Describe the bug**
Travis CI builds are slow ~8 minutes. 

Suggestions:

1. to cache `.npm` & `.cache` directories. 
2. to parallelise the tests a) npm test b) test:e2e:ci c) test:storybook:ci

**Comment by jamesbhobbs** [comment]
The parallelisation was ineffective because of how travis runs each set of tests on a new machine, it clearly favours the earlier machines, meaning a long delay can be experienced for each subsequent set of tests. I've therefore reduced it here: https://github.com/bbc/simorgh/pull/123

**Comment by jamesbhobbs** [comment]
Also want to add caching
