### ISSUE TITLE
Move storybook to github pages

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1098]
**Is your feature request related to a problem? Please describe.**
Psammead has moved its storybook to github pages and it works very well

**Describe the solution you'd like**
Copy the storybook publishing implementation in https://github.com/BBC-News/psammead and terminate the now.sh instance

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Replaced by #1252
