### ISSUE TITLE
Turn known components into siblings if they don't nest according to rules

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1100]
**Is your feature request related to a problem? Please describe.**
Similar - but different - to https://github.com/BBC-News/simorgh/issues/1099.

A product requirement from Jim:

```gherkin
When I try to render a block containing a block we don't expect
Then I should pull out the child block and render it adjacent to the parent block
```

Example:

```jsx
<Subheading>
  <Text>This is my headline</Text>
  <Video>This is a video - oo-er!</Video>
</Subheading>
```

Effectively becomes:

```jsx
<Subheading>
  <Text>This is my headline</Text>
</Subheading>
<Video>This is a video - oo-er!</Video>
```

This allows for changing product requirements, without breaking backwards compatibility (or waiting for platforms which haven't caught up yet). We may not currently know how to render a video within a headline, but we would gracefully fall back to a useable experience. Here's an example "new feature" vs "fallback scenario" below:

<img width="977" alt="screen shot 2018-12-17 at 11 47 54" src="https://user-images.githubusercontent.com/5111927/50085368-c2e45200-01f1-11e9-9ec5-9a82140677c6.png">

**Describe the solution you'd like**
A test suite which takes the 'nested' example above, and renders the 'sibling' example below it.

Naturally, the tests will fail at first because we haven't implemented this logic yet - so the PR would also need to implement that logic.

Before the test suite can be implemented we will need to create an article or two that reflects the behaviour that have been described within this ticket. This type of article doesn't exist within our current library of articles.

Known Block | Known Possible Children
------------ | -------------
altText | text
aresMedia | 
caption | text
fragment | 
headline | text
image | altText, caption, rawImage
paragraph | fragment, urlLink
rawImage | 
text | paragraph
urlLink | fragment
video | aresMedia, caption

**Describe alternatives you've considered**
Other alternatives would be to:

1. Show an error message along the lines of "We cannot render this block as it doesn't validate"
2. Render the bit we recognise, and ignore the "incorrect" bit (e.g. just render the `<Text>` in this case)
3. Blindly render all of the unexpected nesting as if the components were in isolation (likely to look broken).

**Testing notes**
Testing will involve checking that the logic around parent/child behaviour is as expected. For example, if there's some `text` that is the child of an `img` it should appear on the page as its own block. Cypress tests should be written to check that the "parent" element does _not_ contain any child elements.

Dev insight: See "Describe the solution you'd like".

**Additional context**
Our data schema validator is essential here, for describing what can and cannot appear inside a block. When something cannot appear inside a block, we should render it as a sibling.

Let's restrict this to just blocks inside the `<main>` at the moment - Headline is a bit of an edge case.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
To be able to decide what components don't nest in each other, we need rules. Optimo, in theory, allows anything inside of anything but that is logistically impossible at the rendering level.

An image inside caption recursion can't go on forever as you physically can't fit the pixels on the page. Because of this, we will need rules in simorgh to decide the limits. Maybe we allow images inside caption blocks, but only 2 levels deep? who's to say :L 

Talking to @pjlee11 @ChrisBAshton @bcmn It feels like those rules would come from @jimjohnsonrollings  or UX? We would then need to have a schema for these rules.

Would it be the same schema sa the attribute one we have? Would it be a new one? These are all questions

**Comment by dr3** [comment]
Regardless, this feels blocked

**Comment by bcmn** [comment]
We know the data input into Simorgh is extremely flexible, & we know that the HTML & UX that Simorgh outputs are not. Therefore, we need to establish how we go from one to the other, but I don't believe that means we have to be immediately clear on each set of rules.

To me, this ticket is about establishing a subset of the _technical capability_ for these rules, & is not about making UX/product establish what these rules are or will be. We as Simorgh should expect these rules to change over time -- for technical reasons (HTML is a changing standard), UX reasons (UX is a changing ) -- or by service (Newsround will likely have fundamentally different priorities to News).

I think the counterpoint being put forward before was that we should be less concerned with what these rules end up being, & more concerned with how we store them, apply them, & fallback from them.

My understanding:

1. There may/may not be a inter-team contract, which will grow out of dataValidator or contract tests. This is the investigation #920.
2. Simorgh will have product/UX rules that must be expressed & located somewhere. I don't believe we have a ticket for this yet.
3. Simorgh the application will read some collection of those rules as necessary when rendering a page, & will apply them.
4. One of the fallback methods render a recognised block that happens to exist inside of a completely unknown block that is encountered. Investigating how we would implement this data structure change, agnostic of any specific rule, is #1099.
5. One of the fallback methods if a may be to attempt to render unexpected child blocks as siblings. Investigating how we would implement this data structure change, agnostic of any specific rule, is this ticket.

For these investigations, the rule may as well be "When I encounter a block with the type `HiccupBlock`, I will attempt the fallback" -- they shouldn't be reliant on the other steps. Establishing whether the fallback behaviours are doable & acceptable are the desired outcomes, right?

(Obviously this is just my interpretation, I just wanted to try & express it as clearly as possible, as I felt we were clearly failing when discussing in the office.)

**Comment by ChrisBAshton** [comment]
Thanks @bcmn - that sounds right. I think we'll probably end up with two "schemas":

1) a shared one across platforms, that defines what blocks exist and what attributes they have
2) a Simorgh-specific one that captures _relationships between blocks_, i.e. what can exist inside/adjacent-to another.

This issue (#1100) is about exploring how we'll tackle number 2 and how we'll fall back to the 'sibling rule'. Perhaps it can be split into further issues.

**Comment by jimjohnsonrollings** [comment]
The rules that this refers to are the ones we've already established for the blocks we handle.

The rule for any block *that we recognise the type of* that we find *as a child of* a block that we don't expect it to be a child of, is to move it to be a sibling.

So for example, if we got:
Image > Caption > Image

We would change it to:
Image > Caption
           > Image

And then to:
Image > Caption
Image

We should not be prepared to render Images inside Captions until/unless we've agreed this into the Schema.

**Comment by ChrisBAshton** [comment]
I think we're saying that we don't have a parseable file that describes things "we've already established" - it's all captured in code. We have a Schema but all that does is [describe 1 as per this comment](https://github.com/BBC-News/simorgh/issues/1100#issuecomment-451869386), and to say that most blocks can have other unspecified blocks as children.

**Comment by jimjohnsonrollings** [comment]
OK.  Maybe a couple of us can sit down and put together that list of currently expected children this week?

**Comment by pjlee11** [comment]
We can handle expected children of a container using the [pre-existing `componentsToRender` logic](https://github.com/BBC-News/simorgh/blob/9fd288d221c59d6f8f1e306e666a18cf9306b784/src/app/containers/Paragraph/index.jsx#L8). However, this doesn't mean we have 2 schemas. What it actually means is that each of our containers define which components it can render, which could be seen as a "schema" of allowed components per container.

**Comment by jimjohnsonrollings** [comment]
Here's a first attempt at a list of what we 'expect'.

Known Block | Known Possible Children
------------ | -------------
altText | text
aresMedia | 
caption | text
fragment | 
headline | text
image | altText, caption, rawImage
paragraph | fragment, urlLink
rawImage | 
text | paragraph
urlLink | fragment
video | aresMedia, caption

**Comment by ChrisBAshton** [comment]
Thanks @jimjohnsonrollings - does that distinguish between a 'child' and an 'attribute'?

`altText` is an attribute, but `caption` is a child (as `caption` exists as a component) - I think 🤔 or rather, `caption` exists as an attribute and we decide to render that as a component.

**Comment by jimjohnsonrollings** [comment]
These refer to the block structure in the Optimo/Ares output, where altText is a child block.

**Comment by ChrisBAshton** [comment]
I've raised #1146 to document components & nested components.

I think #1100 should be more about looking at how this can be _implemented_ in a sensible way.

**Comment by sareh** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1309

**Comment by ChrisBAshton** [comment]
Should be helped by https://github.com/bbc/simorgh/pull/1493.
