### ISSUE TITLE
Use @bbc/gel-foundations in Simorgh

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1102]
**Is your feature request related to a problem? Please describe.**
Now that https://github.com/BBC-News/psammead/pull/221 `gel-constants` and `gel-foundations-styled-component` have been deprecated

**Describe the solution you'd like**
Replace references to `gel-constants` and `gel-foundations-styled-component` with `@bbc/gel-foundations`

**Describe alternatives you've considered**
Leaving as-is

**Testing notes**
[Tester to complete]

Dev insight: Regression test only

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
This is done already, I believe.
