### ISSUE TITLE
Add AMP Validation to Jenkins pipeline

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1122]
Blocked on #953.

**Describe the solution you'd like**
Currently, the `img`/`amp-img` errors are the only remaining warnings that are shown when running the AMP validation script. Once the ticket above is done, the validation should pass. Once here, we should add the AMP validation script to the Jenkins pipeline.

**Testing notes**
[Tester to complete]

Dev insight: When viewing Jenkins job output for the branch, I can see that the AMP validator is run & passing. Deliberately breaking an AMP behaviour would trigger the job to fail, etc.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Refined - we're just gonna run the validator against one URL, as we currently do, but in Jenkinsfile - as a failing step.

In #442 we'll look at expanding the list of URLs we test against.
