### ISSUE TITLE
Add Lighthouse benchmarks to Jenkins pipeline

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1123]
**Is your feature request related to a problem? Please describe.**
Once we fix the issues in #949, we should make Lighthouse a key failing step in the build pipeline.

Not doing so risks our application performance getting worse over time, unchecked.

**Describe the solution you'd like**
Jenkins should run the Lighthouse scripts and fail if the threshold is not reached.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: When viewing Jenkins job output for the branch, I can see that the Lighthouse performance benchmarker is run & passing. Deliberately making the performance worse - or raising the benchmark to an unachievable level - should trigger the job to fail.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Proposed approach: to add a script to the Simorgh package.json that runs `lighthouse-ci` (https://www.npmjs.com/package/lighthouse-ci), with the relevant thresholds. This should be added to the Jenkins & Travis pipelines within Simorgh. References:
https://github.com/BBC-News/simorgh/blob/latest/Makefile#L12
https://github.com/BBC-News/simorgh/blob/latest/.travis.yml#L20

**Comment by bcmn** [comment]
> add a script to the Simorgh package.json that runs lighthouse-ci (https://www.npmjs.com/package/lighthouse-ci), with the relevant thresholds. 

Note that we have decided to **lower the threshold** to get this added to Jenkins, & we will raise the threshold as we fix any remaining Lighthouse issues. 

We should also update documentation to appropriately point to the [lighthouse threshold configuration](https://github.com/BBC-News/simorgh/blob/d1a35b4073d8d3882f69c6692e6a662df98b1b68/lighthouse.js#L6-L12).

**Comment by sareh** [comment]
As a result of refinement session, we decided to only run this lighthouse test on Test and Live environments, not against localhost.

**Comment by ChrisBAshton** [comment]
^ reasons being, localhost has enough localhost-specific issues (not https, lack of HTTP2, canonical URL mismatch, etc) where we'd be _adding and modifying application code_ in order to feel better ourselves and get Lighthouse passing, when in reality none of the added/modified code would benefit the end user on Test/Live.
