### ISSUE TITLE
Add `npm audit` to Jenkins pipeline

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1126]
**Is your feature request related to a problem? Please describe.**
Blocked on removing Razzle (#715) (which has a high vulnerability).

Once that's done, we should hopefully be vulnerability-free. We should continue to do so! This issue helps ensure that.

**Describe the solution you'd like**
Make `npm audit` part of the Jenkins pipeline so that if known vulnerabilities are introduced or discovered, our build fails and we can prioritise an urgent fix.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Should see `npm audit` run in the Jenkins output with similar output to the following:

```
$ npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 43607 scanned packages
```

(And if we `npm install razzle` and `npm audit` again, we should see a failure)

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
Talking over with Sareh, we have concerns about failing all builds in the scenario in which an existing dependency is deemed vulnerable. We think reporting the result in Slack, with the full details of the `npm audit` output, might make for better behaviour.

**Comment by sareh** [comment]
As a result of refinement session, we discussed the option @bcmn mentioned. 
We agreed to still fail on any new vulnerability, whether it is major, minor or patch.

**Comment by sareh** [comment]
Unblocked since https://github.com/bbc/simorgh/issues/715 is completed.
