### ISSUE TITLE
Add `snyk test` as pre-push step

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1128]
**Is your feature request related to a problem? Please describe.**
Blocked on #715 (Razzle) and blocked on #1127 (`chownr` vulnerability).

`npm audit` only catches so much. We can use Snyk.io, which seems to have a more comprehensive list of known vulnerabilities.

We can run snyk against our repository by:

```
npm install snyk
snyk auth
snyk test
```

See https://snyk.io/docs/using-snyk/.

**Describe the solution you'd like**
A PR which adds Snyk as a devDependency, and adds `snyk test` as part of our package.json scripts somewhere.

Ideally it will be run on Jenkins - but this could be problematic given Snyk requires the `snyk auth` step (which opens a browser and checks for a signed in Snyk user).

As an MVP, we should add it to our `npm test` step so that it gets run locally prior to every `git push`.

**Describe alternatives you've considered**
We could _not_ do this, and rely instead on Snyk's checks against PRs. But using the CLI gives us more freedom (not everyone has Snyk admin GUI access) and makes the checks more transparent.

**Testing notes**
[Tester to complete]

Dev insight: See above.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Since we currently have a Github integration for Snyk, we are okay with not including snyk in the Jenkins pipeline. But we'd like it to be as a pre-push test step.
