### ISSUE TITLE
Create cypress test to test static files exist and are loaded successfully

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1131]
**Is your feature request related to a problem? Please describe.**
We run the unit tests, bundle, upload static assets, deploy cosmos and run the e2e's

It possible that the static assets upload fails - or explicitly points to local.bbc.co.uk (as happened recently), therefore 404's on Test, _but the e2es still pass_.

If the static files upload failed we have no way of knowing, as the cypress tests would continue to pass.

**Describe the solution you'd like**
A test that checks the JS (and other files like manifest.json) files load and initialise correctly. This test would fail if any of the static JS files 404 or are garbage that cant load.

**Env testing**
Ensure that files are loaded from the correct environment (e.g. live shouldn't use news.test.files, test shouldn't use localhost etc)

**Testing notes**
Cypress tests should be added capturing the Test and Live static assets. Pairing with a developer. 

Dev notes: This could be tested locally by deleting the files, and test on Test by changing simorgh-infrastructure `ENV` to point to local, which should we mean we see 404s on Test.

**Additional notes**
Here is a list of assets being uploaded to Test: 
https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/static-assets-deployer/detail/master/537/pipeline/40
and Live:
https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/static-assets-deployer/detail/master/538/pipeline/40/

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked on https://github.com/bbc/simorgh-infrastructure/issues/245

**Comment by rossgaskell** [comment]
As part of this we should confirm that the behaviour can still be replicated

**Comment by PriyaKR** [comment]
Some of the cypress tests are failing when manually deleting the build files(ie .,public folder) and then running the application locally using `npm run start` and then executing the cypress tests using the command `./node_modules/.bin/cypress run` as `npm run test:e2e` will create the build files again.

This would be something for discussion whether these failing tests are just enough to mention that there has been some failure in static files upload or need any specific test to mention it.
<img width="1099" alt="cypress_test_failure" src="https://user-images.githubusercontent.com/9802855/58949924-7e3f7980-8785-11e9-80c4-b8b24c96d1f7.png">

**Comment by DemonusPC** [comment]
After a conversation with @dr3 and @hindsc52 we have realised that we already have a Puppeteer test that checks for this behaviour as well as an internal BBC static asset verify script. This should cover testing for our static assets
