### ISSUE TITLE
Manifest.json is no longer built in the post razzle world

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1132]
**Describe the bug**
After moving away from razzle in https://github.com/BBC-News/simorgh/pull/1117 it appears the manifest.json file is no longer generated

**To Reproduce**

1. Run npm run build && npm run start
2. Go to http://localhost:7080/manifest.json
3. See the file doesnt exist

**Expected behavior**
The file is generated and served

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by sareh** [comment]
Everything in the `public` directory is not served. 
```
public
├── favicon.ico
├── images
│   └── icons
│       ├── icon-128x128.png
│       ├── icon-144x144.png
│       ├── icon-152x152.png
│       ├── icon-192x192.png
│       ├── icon-384x384.png
│       ├── icon-512x512.png
│       ├── icon-72x72.png
│       └── icon-96x96.png
└── manifest.json
```

**Comment by dr3** [comment]
This is the old build folder 
![image](https://user-images.githubusercontent.com/11341355/50904699-e5484480-1418-11e9-8c61-d87b6fcba872.png)
