### ISSUE TITLE
Namespace static assets

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1133]
**Is your feature request related to a problem? Please describe.**
Our static assets arn't name spaced. As we will soon have to support other products we should name space our assets to avoid issues down the road

**Describe the solution you'd like**
Namespace out assets under /news

Definition of done
https://news.test.files.bbci.co.uk/include/articles/public/news/sw.js
https://news.test.files.bbci.co.uk/include/articles/public/news/images/icons/icon-96x96.png
https://news.test.files.bbci.co.uk/include/articles/public/news/manifest.json

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Done in #1269
