### ISSUE TITLE
Update Robots meta tag - remove noindex/nofollow

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1139]
**Is your feature request related to a problem? Please describe.**
Currently, we block the page from indexing, with this meta tag: `<meta name="robots" content="noindex,nofollow" />` This is an active choice, since we're preventing indexing prior to going live. 

Just prior to launch, we should remove this.

**Describe the solution you'd like**
A PR to change the meta tag.

**Describe alternatives you've considered**
Update the robots meta content to be `<meta name="robots" content="noodp,noydir" />`

**Testing notes**
Tester insight: Cypress test will need updating for News and Persian metaspecs. Should write a test to check the meta tag continues to be `<meta name="robots" content="noindex,nofollow" />` for 404 pages (locally).

Dev insight: The Lighthouse test locally and on Test and Live environments should no longer give this error: `Page is blocked from indexing`. Snapshot tests should be updated.

**Additional context**
NB `<meta name="robots" content="noodp,noydir" />` is the value we're using on CPS pages at the moment.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
FYI: 

Noydir: In the case of automatically generated Meta Descriptions, the noydir attribute prevents search engines from using descriptions from the Yahoo! Directory, if it lists the website

Noodp: In the case of automatically generated Meta Descriptions, noodp prevents search engines from using descriptions from the Open Directory Project, if it lists the website

Source: http://www.springboardseo.com/resources/what-is/meta-robots.html

**Comment by pjlee11** [comment]
What are our thoughts for the `ErrorMain` which currently has `<meta name="robots" content="noindex,nofollow" />` should we...
1) Keep the `noidex nofollow`
2) Remove `robots` metatag from ErrorMain
