### ISSUE TITLE
Enable HTTP/2 locally

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1140]
**Is your feature request related to a problem? Please describe.**
Currently, running Lighthouse locally will result in a warning that we are not delivering pages over HTTP/2. For LIVE, this is not true. However, it'd be nice, albeit low priority, to remove this noise from local runs.

**Describe the solution you'd like**
Investigate and/or implement HTTP/2 delivery locally.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Worth noting we only want to do this if it makes a negligible difference to what the user sees on Live (in terms of bundle size, i.e. avoid installing libraries) and a negligible difference to the dev experience (e.g. just adds a `.apply('http2')` or something, and not a huge wodge of code).

**Comment by PriyaKR** [comment]
We no longer need this locally for lighthouse(as we are not going to run lighthouse locally).
