### ISSUE TITLE
Lighthouse warns on invalid canonical URLs on Non-LIVE environments

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1141]
When running Lighthouse on a non-LIVE environment, the following warning is shown:
```
Document does not have a valid rel=canonical
Points to a different domain (https://www.bbc.com/news/articles/c85pqyj5m2ko)
````

**Expected behavior**
It would be nice to reduce this noise when running Lighthouse against local or TEST.

**Additional context**
Sareh & I attempted this very briefly:

We have not found a way to ensure we update the base URL in a way that works across various environments.  

Option 1 
Use the enviroment variable SIMORGH_BASE_URL for the Canonical link in the Metadata https://github.com/BBC-News/simorgh/blob/e430f572903ada27e1d28c659de537a73848ad3a/src/app/containers/Metadata/index.test.jsx#L112

Option 2
Disable this Best Practice test only on Local and Test environments. Run it against the Live environment. 

Our preference is option 1. 
However, when branching off the 'remove razzle' branch (https://github.com/BBC-News/simorgh/pull/1117) and updating the `.env` file's `SIMORGH_BASE_URL` to be `https://www.test.bbc.com` we weren't able to make the Lighthouse test pass.

We prefer to *not* disable tests, to retain visibility of tests that are not passing.

- [x] Initially labelled with ["refinement needed"](https://github.com/BBC-News/simorgh/labels/refinement-needed)

**Comment by jamesbhobbs** [comment]
We removed such lighthouse testing.
