### ISSUE TITLE
Document components that can exist in combination with other components

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1146]
**Is your feature request related to a problem? Please describe.**
#1100 highlighted that we cannot implement the 'turn invalid nested components into siblings' rule unless we know what the _valid_ nested components are. [Jim has had an initial stab at listing these here](https://github.com/bbc/simorgh/issues/1100#issuecomment-451988026).

In other words, whereas we don't currently expect a Subheading to contain a Video:

```html
<Subheading>
  <Text>Foo</Text>
  <Video id='123' />
</Subheading>
```

...and would want to nest them as follows:

```
<Subheading>
  <Text>Foo</Text>
</Subheading>
<Video id='123' />
```

We don't currently document which components are 'allowed' to be nested within which.

**Describe the solution you'd like**
[We have listed what we believe our current view of the world is](https://github.com/bbc/simorgh/issues/1100#issuecomment-451988026).

This issue will document this view of the world in a version controlled way. It also gives us chance to verify & review the assumptions. This ticket will not block #1100, as that ticket is an investigation, & should be able to explore the implications of such a set of rules without having those rules set in stone.

**Describe alternatives you've considered**
Documenting the information as freetext under the `docs/` folder, or as code - the former is not parseable enough to be of automated use, and the latter is not visible enough to non-devs.

**Testing notes**
This is documentation and, as such, will not require testing.

Dev insight: This is a documentation issue, so no application code should be affected.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
I'm not certain I get this, but it seems to be an issue to write this https://github.com/bbc/simorgh/issues/1100 issue better, which is just refinement
