### ISSUE TITLE
Set up diff/total coverage checks using OS CodeClimate engines on Jenkins

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1149]
**Is your feature request related to a problem? Please describe.**
Re-set up CodeClimate diff-coverage and total-coverage checks:

<img width="252" alt="screen shot 2019-01-10 at 10 21 00" src="https://user-images.githubusercontent.com/5111927/50962154-825eb800-14c1-11e9-8f76-f759eef6d126.png">
<img width="654" alt="screen shot 2019-01-10 at 10 21 04" src="https://user-images.githubusercontent.com/5111927/50962155-825eb800-14c1-11e9-9374-702f94a26c96.png">

We lost these in the move from BBC-News to BBC.

**Additional context**
We're not able to use the CodeClimate service as it's not currently signed off by legal.

But we _can_ use their open source engines and run them on Jenkins.

**Comment by sareh** [comment]
Closed as fixed.
