### ISSUE TITLE
Update static assets serving

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1152]
**Is your feature request related to a problem? Please describe.**
Our static assets, when using webpack-dev-server, are served on port 1124 not 7080, unlike when you run npm start.

**Describe the solution you'd like**
Serve the assets on the correct port or point simorgh at the correctly.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
For the record, differing port numbers were chosen because we couldn't run the start-server-webpack-plugin on the same port as the webpack dev server.
