### ISSUE TITLE
Meta charset has medial cap

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1156]
**Describe the bug**
In the article, the character set meta data is currently rendered as `<meta charSet="utf-8"/>`.  The requirements specify `<meta charset="utf-8"/>`.

**To Reproduce**

1. Visit an article
2. View source
3. Search for `<meta char`

**Expected behavior**
Requirements and implementation to match

**Additional context**

- [ ] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by sareh** [comment]
React outputs certain DOM attributes as camel-cased. They will not fix it, since it is valid HTML.  https://github.com/facebook/react/issues/11160
