### ISSUE TITLE
Really long headlines overflow

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1162]
**Describe the bug**
If the headline contains a really long word, then it doesn't wrap but overflows into the area to the right of the headline block (out of the column).

**To Reproduce**

1. Create an article with a really long word in the title
2. Publish
3. View the article

**Expected behavior**
UX to define

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Firefox

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by sareh** [comment]
Closed since we do not want to break words in the middle, programmatically, since that could change the meaning of a headline.
