### ISSUE TITLE
Reith font not loading if not already cached (JS browser)

### ISSUE THREAD

**Issue by radiocontrolled** [bbc/simorgh#1169]
BLOCKED ON https://github.com/bbc/simorgh/issues/1178

**Describe the bug**
Possibly related to #1053 and #1009.

On a browser with JS enabled, the Reith font doesn't necessarily load the first time. 

**To Reproduce**
* `npm run dev`
* clear browser cache or open in a private browser
* visit http://localhost:7080/news/articles/c9rpqy7pmypo

**Expected behavior**

**Screenshots**
![screen shot 2019-01-14 at 14 12 32](https://user-images.githubusercontent.com/916416/51117810-b6f6aa80-1806-11e9-91a2-d77e1c5ccef5.png)

**Desktop (please complete the following information):**

FF (developer ed), Safari, Chrome
- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

Possibly related to: 
https://github.com/bbc/simorgh/issues/1053
https://github.com/bbc/simorgh/issues/1009

**Comment by radiocontrolled** [comment]
Not sure if this one needs refinement

**Comment by sareh** [comment]
Closed since this is the expected behaviour https://github.com/bbc/simorgh/issues/1178#issuecomment-455150635
