### ISSUE TITLE
Add automated lighthouse tests for AMP with own thresholds

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1174]
**Is your feature request related to a problem? Please describe.**
We should add amp pages to the lighthouse ci test, but have different thresholds to reduce dependancy on the other pages performance.

**Describe the solution you'd like**
Add the amp versions of the existing pages, but test with new thresholds

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by rossgaskell** [comment]
Closing as low priority, due to the limitations of AMP should prevent us creating performance issues.
