### ISSUE TITLE
Remove unneeded hash from bundle names.

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1175]
**Is your feature request related to a problem? Please describe.**
When we bundle our static assets we use the name recipe `static/js/[name].[hash:8].js` this means that all files outputted use a shared hash in their name.

This however means that when we do a release we rename the file, even if the contents of the bundle hasn't changed. This is especially important for the vendor bundles, as their content is unlikely to change on release, so we shouldn't require a user to redownload it.

**Describe the solution you'd like**
Change the filename recipe in from 'static/js/[name].[hash:8].js' to 'static/js/[name].js' to ensure that the file name doesn't change unnecessarily 

**Testing notes**
Regression of `SIMORGH` application, paying specific attention to the Network tab to check the static file loads as expected, given the implemented logic.

**Dev insight:**
DOD : There should only be a single hash in the file name that is solely dependant on the contents of the file, not the application build. E.g `static/js/main-d0ae3f07.js` not `static/js/main-d0ae3f07.67fd7b32.js`

**Additional context**
We may need to do some research into what the hash is based on to ensure it is always unique and has no clashes.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
The hash in filenames is important when we have clientside caching. The hash is generated from the contents of the file and so should only change whenever the file contents change. This means that when the file is updated, the cache is invalidated and a new file is loaded.

**Comment by dr3** [comment]
@sareh The current bundle names are in the format
```
static/js/main-d0ae3f07.67fd7b32.js
static/js/vendor-1f20a385.67fd7b32.js
static/js/vendor-253ae210.67fd7b32.js
static/js/vendor-678f84af.67fd7b32.js
```
This issue is to remove the `67fd7b32`bit. This hash is purely based on the release, not the contents of the bundle

**Comment by ChrisBAshton** [comment]
Work has been started by Benjamin, we can carry it on.
