### ISSUE TITLE
Update background colour of article

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1176]
**Is your feature request related to a problem? Please describe.**
UX have updated the design regarding the background colour of articles.

**Describe the solution you'd like**
The background colour should now be `#fdfdfd`, ("Ghost"), which should also be added to `psammead-styles`.

**This should affect the full extent of the article, from the top Brand component to the bottom Brand component. There is no longer a split following the headline.**

**Testing notes**
James' insight: Regression across devices, check AMP to ensure colours are reflected correctly.

Dev insight: If there are Cypress tests, they should be updated, but not to write new Cypress style tests.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
I think this can be done in 2 parts, firstly removing the oat wrapper, then secondly setting the correct background colour on the whole page.

**Comment by dr3** [comment]
Closing as done
