### ISSUE TITLE
Implement full-bleed images for mobile

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1177]
**Is your feature request related to a problem? Please describe.**
UX have updated the designs regarding images on mobile devices.

**Describe the solution you'd like**
For mobile size classes -- GEL Groups 1 & 2 -- large images should be displayed full-bleed -- no margin, & no padding.

If the image is so small it doesn't fill the mobile viewport, then the image should remain left-aligned, with padding of 8px (`GEL_SPACING` from `psammead-gel-foundations`).

On desktop, these small images should be left-aligned within the article text column, with no padding whatsoever.

For this ticket, the caption width should _always_ match the full width of the image. There are additional scenarios, such as for extremely small images with captions, but those will be handled in later tickets.

**Testing notes**
James' insight: 

- We'll need to be able to test with scenarios of all types of images -- 16:9, 9:6, 1:1, & an the smallest image that we will receive (100px by 100px).
- Testing on IE11 & iOS 7 especially important, due to the CSS Grid fallback.
- Ensure appearance is correct on AMP, & without JS.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Closed since this is part of this issue now: https://github.com/bbc/simorgh/issues/1751
