### ISSUE TITLE
Lighthouse randomly fails the build

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1183]
**Describe the bug**
Lighthouse tests run on Travis. Occasionally, Lighthouse returns `null` instead of a performance value (e.g. `82.4`). This fails the build. 

Example:
https://travis-ci.org/bbc/simorgh/jobs/480798628 - failing for `lighthouse null reason`

**To Reproduce**

1. Re-run Travis on `latest`
2. ...several times....
3. ...it will eventually fail because of Lighthouse

**Expected behavior**
The build should consistently pass.

**Additional context**
Suggestion: we could try re-running the Lighthouse tests continually until a non-null value is returned.

Or we could try replacing with [lighthouse-ci](https://www.npmjs.com/package/lighthouse-ci).

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by pjlee11** [comment]
Example failure

![image](https://user-images.githubusercontent.com/7791726/51381112-2ae8c980-1b0b-11e9-9cc6-cfa0aa31488c.png)
