### ISSUE TITLE
Add docs for using Snyk

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1184]
**Is your feature request related to a problem? Please describe.**
Add some text to the contributing on how to use synk, how to auth for the first time, how to update the whitelist etc

How to run
How to auth
How to update policy file (whitelist)

Refer to snyk docs in our docs https://snyk.io/docs/using-snyk/

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
We shouldn't be using snyk in this repo. It is managed centrally. Also see https://github.com/bbc/simorgh/issues/1607
