### ISSUE TITLE
Create cypress test for checking were using the correct data source.

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1186]
**Is your feature request related to a problem? Please describe.**
We have noticed that due to misconfiguration we wernt using aries data

**Describe the solution you'd like**
Create a test that checks we are using aries data. This could be done by loading an asset that isnt stored locally. If its avalible, were using the correct data source.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Think this issue has grown stale now.
