### ISSUE TITLE
`npm ci` on Travis intermittently fails with submodule errors

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1192]
**Describe the bug**
`npm ci` intermittently fails on Travis - random error in submodule npm uses.

**To Reproduce**
Run tests on Travis - it occasionally fails with this error.

**Expected behavior**
Travis should be consistent with what happens on local.

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
Too intermittent, can't find the jobs - closing for now.

**Comment by bcmn** [comment]
<img width="1176" alt="screenshot 2019-01-17 at 19 26 47" src="https://user-images.githubusercontent.com/11646957/51343264-eff48080-1a8d-11e9-97a0-ad60bcc96ef8.png">

Is this an example of the issue? From [this job](https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh/detail/lighthouseci-jenkins/1/pipeline/).
