### ISSUE TITLE
`xvfb-run` on Travis intermittently fails with 'unable to start' errpr

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1193]
**Describe the bug**
`xvfb-run` intermittently fails on Travis - 'unable to start'.

**To Reproduce**
Run tests on Travis - it occasionally fails with this error.

**Expected behavior**
Travis should be consistent with what happens on local.

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by bcmn** [comment]
What is this externally blocked on?

Here's an example:
<img width="548" alt="screenshot 2019-01-17 at 19 25 00" src="https://user-images.githubusercontent.com/11646957/51374267-6929bd00-1afa-11e9-9892-92a1dbf6e4d3.png">

[Here's an issue on the Travis repo which seems to offer a potential solution](https://github.com/travis-ci/travis-ci/issues/4387). (We don't use the `-a` flag anywhere that I could find.)

**Comment by ChrisBAshton** [comment]
Good point - not externally blocked, just an 'external' issue.

**Comment by jamesbhobbs** [comment]
No updates/reports of this in months, therefore closing
