### ISSUE TITLE
Create an error page in Simorgh

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1194]
**Is your feature request related to a problem? Please describe.**
Because Simorgh is a SPA it needs it an error page as the application can fail on the client side. The [error pages designs are on Zeplin](https://app.zeplin.io/project/5baa564c05c2eba0d2b89568?seid=5c5973040e57ce426c6f4331).

**Describe the solution you'd like**
We should have front-end components for the error pages. 
Our application should render 404 & 500 pages when these status codes are returned.

**Describe alternatives you've considered**
N/A

**Testing notes**
- Automation
Cypress tests to check the status code returns as `404`and the error printed within the "article" contains `404` & `Page cannot be found`.

- Manual
Manually test the article page to make sure there are no issues around overlapping and the colour displays as expected, especially across older devices/browsers.

- Accessibility
Test using AT to make sure the text on screen is being read out in the correct order. Before testing, confirm the correct order that the text should be read out in. We should also check the colour ratio levels are passing.

Dev insight: Unit tests would be needed, as should some simple integration test (just for the heading, not all the error page attributes). 

**Additional context**
On the server side, Mozart can handle some errors, see [issue](https://github.com/bbc/simorgh-infrastructure/issues/176)

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked on #1214.

**Comment by dr3** [comment]
Talking to @nataliesmart if its possible (and generally supported) it would be preferable if the footer of the error page stuck to the bottom of the screen. So like the right browser image below where theres no whitespace under the grey footer. This is only if its relatively simple in css :) 

![image](https://user-images.githubusercontent.com/11341355/52367695-91934000-2a44-11e9-8321-83b009a42f33.png)

**Comment by jamesdonoh** [comment]
Oops
