### ISSUE TITLE
Test AMP route renders Canonical page

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1199]
**Describe the bug**
Currently, the request to the Articles AMP URL https://www.test.bbc.com/news/articles/c85pqyj5m2ko.amp renders the non-AMP, canonical page.

**To Reproduce**

1. Visit https://www.test.bbc.com/news/articles/c85pqyj5m2ko.amp
2. Look at the source and note that it is rendering the Canonical page (e.g. `<img>` instead of <amp-img>`)

**Expected behavior**
It should render the AMP page.

**Additional context**
The reason for this is that we extract just the article id i.e.c85pqyj5m2ko and later on in the Assembler, use that in the url https://simorgh.test.api.bbci.co.uk/news/articles/{articles_id}

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by sareh** [comment]
The two Mozart PRs have been merged. They should be deployed up to Test in the next day or so, so we should keep this issue open until the work is on the Test environment and we've observed the fix.

**Comment by dr3** [comment]
https://www.test.bbc.com/news/articles/c85pqyj5m2ko.amp now renders the amp article correctly, great work, closing as done
