### ISSUE TITLE
Verify special characters appear as expected

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1202]
**Is your feature request related to a problem? Please describe.**
Special characters are available to journalists.

**Describe the solution you'd like**
We test that all special characters we claim to support actually are supported.  Here is a test article with all of them in: cev804m5n0vo

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
Closing in favour of #401.
