### ISSUE TITLE
Investigate remote un-registering/invalidation of service workers

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1208]
Identify if there is a feasible means of unregistering or invalidating a service worker remotely, in the scenario where we wish to rapidly disable a specific version of the -- possibly without a fixed subsequent version of the service worker yet available.

[This repo may prove interesting.](https://github.com/NekR/self-destroying-sw)

**Describe the solution you'd like**
Document & create tickets for an approach that will allow us to implement this behaviour.

### The outcome of this issue will be in the form of [a dropbox paper investigation](https://paper.dropbox.com/doc/Service-worker-usage-investigation--AWg4iO~bkILoRBAfKKJF2BZHAQ-2RmFsBBOBLjzQS9oRUhbo) that will be check by others to ensure it makes sense and is correct

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Re: invalidating the service worker
This is something @dgm34 is very passionate about and in RESFRAME-2571 he highlighted how we should have the header `Clear-Site-Data: storage cache` on a dial, so that if we break our service worker we can use this header to reset things.

**Comment by ChrisBAshton** [comment]
Replaced by https://github.com/bbc/simorgh-infrastructure/issues/315.
