### ISSUE TITLE
Add Content Security Policy (CSP) Headers

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1211]
**Is your feature request related to a problem? Please describe.**
We wish to add [Content Security Policy (CSP) headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to our served webpages, allowing us to constrain the domains from which assets are requested.

This would require Mozart to accept & forward CSP headers.

**Describe the solution you'd like**
We should be constraining the valid source domains by asset type. For this ticket, we will not prioritise establishing a reporting endpoint, as this work will be done in #....

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Done.
