### ISSUE TITLE
Add Production articles onto Optimo Live

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1213]
**Is your feature request related to a problem? Please describe.**
Currently, we have these articles on Optimo Test for News: `c85pqyj5m2ko` & `c9rpqy7pmypo` & this one for Persian: `cwv2xv848j5o`

We want to have these available on Optimo Live, so we can use it in our integration tests in our pipeline. 

**Describe the solution you'd like**
To create these three articles in Optimo. To ensure they're visible at the Ares broker endpoint. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: No tests needed, just ensuring that the output from Ares on Live is identical to that on Test (other than the article id). 

**Additional context**
As a result of finishing this ticket, we can start updating the Article 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Blocked on optimo live working

**Comment by dr3** [comment]
Reported by @jimjohnsonrollings >FYI: cxvxrj9yvppo is LIVE

**Comment by ChrisBAshton** [comment]
"To create these two articles in Optimo. To ensure they're visible at the Ares broker endpoint."

We only have 1. We need both (News and Persian)

**Comment by dr3** [comment]
These 3 articles are now available on live optimo :)
`'cpzk9lkk2p7o', 'cxvxrj9yvppo','c5ml5n7w4m3o'`
