### ISSUE TITLE
Update Cypress tests to use window Simorgh Data

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1226]
**Is your feature request related to a problem? Please describe.**
Currently, there are several Cypress tests that make use of assertions against the window SIMORGH_DATA (the JSON for the article) e.g. https://github.com/bbc/simorgh/blob/67decf15656f785ae20caf0cef7e9e5657920766/cypress/integration/newsBodySpec.js#L89

These tests are more resilient to changes in the Test data, since they check the value in the JSON data with the rendered output on the page. 
We should update the rest of our Cypress tests that have hard-coded values, to be checked against Simorgh Data. 

**Describe the solution you'd like**
To have the remaining Cypress tests updated to use SIMORGH_DATA for assertions, so they're resilient to changes made in the Test data. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Cypress tests should pass. Dev discussion should happen as to which fields from the SIMORGH_DATA should be used. 

Dev insight: Cypress tests should pass. 
e.g. the paragraph test should retrieve the first paragraph from the JSON data and assert that the first rendered paragraph matches. https://github.com/bbc/simorgh/blob/67decf15656f785ae20caf0cef7e9e5657920766/cypress/integration/newsBodySpec.js#L56

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Fixed by #1236.
