### ISSUE TITLE
Cypress Readme

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1228]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't an introduction to writing Cypress tests in our application. 
We should add a Readme to the Cypress directory - to explain the directory structure and best practice in adding integration tests and helper utilities. This should be accessible to developers and testers. 

**Describe the solution you'd like**
To write a `README.md` file in the [`cypress` directory](https://github.com/bbc/simorgh/tree/latest/cypress) giving a high-level overview, for any testers or developers to be able to understand how best to contribute to the integration tests. 

**Describe alternatives you've considered**
N/A

**Testing notes**
At the 'code review' stage, this should also be reviewed by a tester in a different team and feedback should be incorporated into the PR. 

Dev insight: Same as above. 

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by PriyaKR** [comment]
Requires discussion with other pod testers as well and then updating the `README.md`

**Comment by staylos92** [comment]
A README now exists here: https://github.com/bbc/simorgh/blob/latest/cypress/README.md I think things like directory structure and best practice info still needs adding to it though :)
