### ISSUE TITLE
Swarm `/news/article/xxxxxx` page on devices/browsers

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1229]
**Describe the investigation**
Swarm an `/news/article/xxxxxx` page on browsers/devices with a developer and another tester.

*When investigating look at the latest browser versions available to the public.*

**Desktop browsers**
Chrome (Windows)
Chrome (MacOS)
IE11 (Windows)
Firefox (Windows)
Firefox (MacOS)
Edge (Windows)
Safari (MacOS)
 
 
**Mobile Browsers**
Chrome (Android)
Samsung Internet Browser (Android/Samsung Devices)
Facebook for iPhone
Opera Mini (iOS)
Opera Mini (Android)
Chrome for iOS
Facebook for Android
Amazon Silk
Android Browser v4.x
Firefox (iOS)
Firefox (Android)

Once testing is completed, please add the device and browser version that was used.

**Comment by ChrisBAshton** [comment]
Blocked on #1234.

**Comment by jamesbhobbs** [comment]
@greenc05 please chase up to ensure this is given due priority.

**Comment by greenc05** [comment]
@jamesbrumpton can you confirm that this is referring to browser testing on devices, and not relevant to accessibility testing?

**Comment by jimjohnsonrollings** [comment]
This covers just browser testing, and is blocked until we've added video.
