### ISSUE TITLE
Split local data endpoint into separate local express server

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1235]
**Is your feature request related to a problem? Please describe.**
We currently have simorgh serving data in our production application which should be removed.

**Describe the solution you'd like**
Move the route https://github.com/bbc/simorgh/blob/latest/src/server/index.jsx#L43-L66 into a separate simple express server. This server would only serve fixture data for the purpose of integration tests. 

**Drew's opinion**
We should rename our fixture id values such that its obvious they are fixture files

**Testing notes**
This would be locally only so ensure the data endpoint stops working in the primary simorgh application and make sure nothing expects the route to exist. Check for any issues stemming from the data being on different origin/port

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Closing in favour of #1327.
