### ISSUE TITLE
Decouple the APP_ENV logic

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1239]
**Is your feature request related to a problem? Please describe.**
Currently `APP_ENV` is used by webpack at bundle time to decide both locally and on jenkins which `.env` file to use (EG: `.env.test`, `.env.live` or `.env.local`) AND also used at run time to decide which set of bundled assets to use (EG: `assets-test.json`). 

**Describe the solution you'd like**
We should `APP_ENV` responsibility into 2 separate variables. The first being pre-bundle for webpack to use and the second being at run time to decide on the assets to use. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Test that within the Network tab the `main-xxxxxxxx.js` & `vendor-xxxxxxx.js` returns as expected depending on where `local` is pointing to. 
- To point to Test - `npm run build && APP_ENV=test npm run start`
- To point to Live - `npm run build && APP_ENV=live npm run start`

Point of reference - `https://news.test.files.bbci.co.uk/include/articles/public`

Dev insight: Regression test that the application can still build. No functional changes as this is a refactor. 

**Additional context**
Following this PR we should be able to remove `.env.local`

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbrumpton** [comment]
👍 LGTM
