### ISSUE TITLE
Decide on polyfill strategy

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1241]
**Is your feature request related to a problem? Please describe.**
We currently `import 'babel-polyfill'` into `client.js`. This adds around 15KB of JavaScript to the final bundle (~15% of our bundle size):

| JS bundles with `babel-polyfill` | JS bundles without `babel-polyfill` |
|---------------------------------|------------------------------------|
|<img width="698" alt="screen shot 2019-02-05 at 12 13 07" src="https://user-images.githubusercontent.com/5111927/52272778-b81b8300-293f-11e9-8af1-6328261009a2.png">|<img width="713" alt="screen shot 2019-02-05 at 12 13 15" src="https://user-images.githubusercontent.com/5111927/52272791-bfdb2780-293f-11e9-9ca4-4c218dcf7d44.png">|

(to reproduce, run a production local build: `npm run build:local && npm run start`, with and without the `import 'babel-polyfill'` line on `client.js`).

**Describe the solution you'd like**
Group discussion.

We _could_ explore [only polyfilling the required modules by manually importing polyfills from core-js](https://github.com/zloirock/core-js#commonjs). We can [lazy-load these polyfills](https://itnext.io/lazy-loading-polyfills-4b85c4951e73) so that only the browsers that need them will get them.

This comes with quite a lot of dev & test overhead, but should mean a smaller bundle output.

**Describe alternatives you've considered**
Or, we could leave as-is. It's only 15KB, and it means a much simpler codebase and low-risk releases. We're not going to suddenly break old browsers because we forgot to manually polyfill something.

**Testing notes**
[Tester to complete]

Dev insight: TBC. We should discuss the merits of our polyfill strategy and any actions we may want to take later.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
Speed of iteration > tiny bundle. If there's a safe stable way to do this I'm all ears though.
