### ISSUE TITLE
Separate loading/error/data state logic from rendering page

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1247]
**Is your feature request related to a problem? Please describe.**
Currently, the Article container does two things: it handles the different `loading`/`error`/`data` states (currently returned from `react-universal-app`, but this may change) _and_ renders the page furniture. However, it would seem much of this outline of the page would be desired for the `loading` or `error` states.

**Describe the solution you'd like**
There is a clear separation between what handles the different states of react-universal-app (or it's replacement), & what renders the common parts of the page: `GlobalStyle`, the providers, `Header`, `Footer`, etc.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Would seem like a regression test -- internal refactor.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Closed as fixed.
