### ISSUE TITLE
Create loading page

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1248]
**Is your feature request related to a problem? Please describe.**
Our current loading state for second page load is a blank page with the text `Loading...`.  We should create a loading screen that maintains much of the page furniture (&, depending on UX requirements, may render a "skeleton screen" or similar preview.

Adding a smoother transition to this screen is covered in https://github.com/bbc/simorgh/issues/1302 which doesnt block this.

Blocked on UX's specifications for load page appearance.

**Describe the solution you'd like**
This should follow https://bbc.github.io/gel/foundations/routing/#awaiting-content

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Have edited this issue to be for the visual loading state only. Its bounce handling is covered by https://github.com/bbc/simorgh/issues/1302
