### ISSUE TITLE
Investigate screen capture Cypress plug-ins 

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1249]
**Is your feature request related to a problem? Please describe.**
Investigate possible screenshot capabilities of Cypress.

**Describe the solution you'd like**
Looking online, there are a few methods that could be used to allow screenshots to be captured via Cypress in a similar style to Wraith. It would be great to get it installed and see whether the team feels it's something worth integrating into the existing Cypress framework.

[Match-Screenshot _3rd Party_](https://github.com/julianburr/cypress-match-screenshot)
[Cypress.Screenshot _1st Party_](https://docs.cypress.io/api/cypress-api/screenshot-api)

Findings:
[TBD]

- [ ] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
We will soon use ChromaticQA for visual regression testing, inc cross-browser. I believe that will be sufficient for the foreseeable future.
