### ISSUE TITLE
Use CodeClimate CLI to run quality checks

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1250]
**Is your feature request related to a problem? Please describe.**
We're not going to get infosec sign-off for continued use of the CodeClimate service. But we ARE allowed to make use of the open-source tools they provide.

**Describe the solution you'd like**
A PR which adds [codeclimate CLI](https://github.com/codeclimate/codeclimate) (or equivalent) to our build process so that we can keep the same benefits of automated code quality checks.

NOTE: needs thinking about. Currently CodeClimate is a separate check, which we can ignore if we decide we prefer the code we have and don't want to abstract it just to appease the code checker. If we make it part of our one Jenkins build, how would we choose to ignore it?

Ideally we'd set up a separate Jenkins or a Lambda so that we can inspect and obey/ignore the check independently. 

**Describe alternatives you've considered**
Removing CodeClimate altogether and losing the automated code quality check.

**Testing notes**
[Tester to complete]

Dev insight: TBC - depends on the outcome of the investigation.

**Additional context**
We can't get CodeClimate signed off due to the risk of exposing all of our private repositories to a third party.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
CodeClimate is an approved supplier, closing.

**Comment by ChrisBAshton** [comment]
Congrats! 🙌
