### ISSUE TITLE
Amp pages serve a 304 response when requested again

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1251]
**Describe the bug**
Following https://github.com/bbc/simorgh/pull/1206 we are logging serving 304 responses from amp

**To Reproduce**
Steps to reproduce the behaviour:

1. Once https://github.com/bbc/simorgh/pull/1206
2. Build and start
3. Request amp page a few times
4. See 304's in log

**Investigation**
This behaviour is similar to .json responses, implying our amp pages are being cached as files, not pages. We should investigate if this is going to be an issue.

**Possible task**
Add 304s to the list of response codes we don't log. It will only be an issue if you hit simorgh directly, as Mozart wont do this, however best to do it anyway I think.

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by chris-hinds** [comment]
I can still reproduce this, even visiting an AMP page just the once. When you load a AMP page on localhost observe the console and see the 304 logs.

This could just be a bug with our logging.
