### ISSUE TITLE
Replace now.sh usage with GitHub pages

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1252]
**Is your feature request related to a problem? Please describe.**
We can't continue using now.sh: https://simorghstorybook.now.sh/

We should follow the [psammead approach](https://github.com/bbc/psammead) and make our Storybook available on GitHub Pages: https://bbc.github.io/psammead/

**Describe the solution you'd like**
A PR to Simorgh and Infrastructure to remove usage of now.sh and add GitHub Pages deployment to our pipeline. Then we should delete our now.sh account for housekeeping.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Once merged, we should be able to visit https://bbc.github.io/simorgh/ and see our Simorgh Storybook and https://simorghstorybook.now.sh should 404.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
@hindsc52 This issue incs removing now.sh, which is still in simorgh. Can you please make a PR to remove it?

**Comment by chris-hinds** [comment]
I will be yes, but there are still discussions around how we deploy to GH Pages now on the Infra PR

**Comment by dr3** [comment]
Reopening to remove now.sh :)

**Comment by chris-hinds** [comment]
Cheers Drew, will raise a PR for this shortly.
