### ISSUE TITLE
Eliminate need to set LOG_DIR when running production builds locally

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1255]
**Describe the bug**
When trying to run the test build locally it errors
![image](https://user-images.githubusercontent.com/11341355/52482047-1f3b7080-2ba8-11e9-9b1d-a3cd2cca186e.png)

**To Reproduce**

1. Run `npm run build:test && APP_ENV=test npm start`
2. See error

**Expected behavior**
It allows you to run it, defaulting to the `log` folder

**Screenshots**
See above

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by pjlee11** [comment]
It might be good to have an `npm run debug:testEnv` command which: 
- changed the `LOG_DIR` value
- removed the `build/`
- run the build with the `envConfig/test.env` values
- start the application 

This would allow for the current `npm run build:test` command is reusable for the debugging command and the `build:ci` command

**Comment by pjlee11** [comment]
Another solution could be that these are also set to `log` and then overridden in the bake scripts

**Comment by jamesdonoh** [comment]
Having discussed at refinement we believe following the existing instructions at https://github.com/bbc/simorgh#using-environment-builds-locally avoid this problem, meaning this issue is a DX nice-to-have rather than urgent, so de-prioritising accordingly.
