### ISSUE TITLE
Add Cypress tests for error pages

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1258]
Blocked by #935. Blocked by #1194.

**Is your feature request related to a problem? Please describe.**
Following the implementation of the error pages, we want our Cypress tests to test they are returned correctly.

**Describe the solution you'd like**
To check the correct error status code is returned. 

404 can be tested with an incorrect article id but matches the regex.
502 can be tested with blocking the request for the `.json` via Cypress. 

**Describe alternatives you've considered**
We do not want to check for specific strings such as 'Page Not Found', since it doesn't scale with different languages for various pages. 

We considered also testing the 500 error case in this ticket, but since this will be more complex, we will test it via unit tests. The 'internal server error' page should still be able to be shown via the 502 check above. 

**Testing notes**
Pair with developer to write/execute tests. Might be worth looking at current test logic around status codes/error pages that are existing in Cypress.

Dev insight: New Cypress tests should pass.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
This was done
