### ISSUE TITLE
Cypress tests: `focus` state only testable when window in view

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1261]
**Describe the bug**
When running Cypress in interactive mode, our test which checks the `:focus` state fails if we switch windows while the test is running. This is not a blocker but is mildly annoying. Headless Cypress passes fine, FYI.

**To Reproduce**
TBC

**Expected behavior**
Should always pass regardless of our multitasking.

**Screenshots**
TBC

**Additional context**
This issue came out of Test Workshop Feb 11th.

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by jamesbhobbs** [comment]
Cannot reproduce
