### ISSUE TITLE
Cypress test for a BBC copyrighted image

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1262]
**Is your feature request related to a problem? Please describe.**
We test for a non-BBC copyright image having an image 'source' in the markup.

We don't currently test for images that have BBC copyright (therefore no source in the markup).

**Describe the solution you'd like**
A PR which adds this test. We do already have a test article with an image with BBC copyright (the final image in TEST c9rpqy7pmypo)

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Tests should continue to pass.

**Additional context**
This issue came out of Test Workshop Feb 11th.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
This is done.
