### ISSUE TITLE
Make cypress tests run on multiple environments

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1263]
**Is your feature request related to a problem? Please describe.**
Now that we have a live environment we need our cypress tests to run on different environments with different assets 

**Describe the solution you'd like**
Following https://github.com/bbc/simorgh/pull/1236

A PR in Simorgh to split out our tests into local/test/live equivalents, either through folders or config file. The aim being to run Test cypress tests on Live, against Live URLs, without duplication of effort.

In tandem with a PR to Simorgh-Infrastructure to execute the right scripts defined by the above PR (issue: https://github.com/bbc/simorgh-infrastructure/issues/245).

**Testing notes**
Will sit down with a developer and run through the best approach to make the tests environment agnostic. We will sat down at a later date to discuss which tests should/should not be included for each environment.

**Dev insight:** 
Not writing any new tests - at the end of this work, our Test tests should be running on Live, but with live URLs.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
One option is to 
run cypress as `CYPRESS_APP_ENV=test npm run cypress`
and make a config file like `/support/config.js`
```
const config = {
  live: {
    baseUrl: 'https://simorgh.api.bbci.co.uk',
    dataUrl: 'https://www.bbc.com',
    assetUrl: 'https://news.files.bbci.co.uk/include/articles/public',
    assets: {
      news: 'cxvxrj9yvppo',
      newsThreeSubheadlines: 'cpzk9lkk2p7o',
      persian: 'c5ml5n7w4m3o',
    },
  },
  test: {
    baseUrl: 'https://simorgh.test.api.bbci.co.uk',
    dataUrl: 'https://www.test.bbc.com',
    assetUrl: 'https://news.test.files.bbci.co.uk/include/articles/public',
    assets: {
      news: 'c85pqyj5m2ko',
      newsThreeSubheadlines: 'c9rpqy7pmypo',
      persian: 'cwv2xv848j5o',
    },
  },
  local: {
    baseUrl: 'http://localhost:7080',
    dataUrl: 'http://localhost:7080',
    assetUrl: 'http://localhost:7080',
    assets: {
      news: 'c85pqyj5m2ko',
      newsThreeSubheadlines: 'c9rpqy7pmypo',
      persian: 'cwv2xv848j5o',
    },
  },
};

module.exports =
  typeof Cypress !== 'undefined'
    ? config[Cypress.env('APP_ENV')]
    : env => config[env];
```

We can set baseURL with a plugin `/plugins/index.js`
```
const envConfig = require('../support/config');

/* eslint-disable no-param-reassign */
module.exports = (on, config) => {
  config.baseUrl = envConfig(config.env.APP_ENV).baseUrl;

  return config;
};
```
And because were setting baseURL that way `cypress.json` can become
```
{
  "video": false,
  "env": {
    "APP_ENV": "local"
  }
}
```

Use it in files like `import config from '../support/config';` and ```cy.visit(`/news/articles/${config.assets.news}.amp`);```

**Comment by ChrisBAshton** [comment]
Reservations on that approach because not every page will have the things we want to test (e.g. video). Perhaps something more like:

```
  test: {
    baseUrl: 'https://simorgh.test.api.bbci.co.uk',
    dataUrl: 'https://www.test.bbc.com',
    assetUrl: 'https://news.test.files.bbci.co.uk/include/articles/public',
    assets: {
      newsPageWithVideo: 'ce3k983m4x8o',
      newsPageWithTwoHeadlines: 'crykxj1x2e7o', // etc
      persian: 'cwv2xv848j5o',
    },
  },
```
