### ISSUE TITLE
Add tests for footer links

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1264]
**Is your feature request related to a problem? Please describe.**
We currently have cypress tests that check the footer links contain hardcoded values.

We would like to test clicking on these links and ensuring that the final endpoint is the same as the original link, so that we're not linking to a redirect - and also to test that it doesn't 404.

That said, we have little control if these _do_ break externally, so we want the tests to only 'warn' rather than error, or to only run once a day ('daily sanity checks'?).

From the test workshop, it sounds like Cypress has some cross-origin errors when doing this, so will require a dev and test to sit together.

**Describe the solution you'd like**
A PR to write / add to our footer links test.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: TBC

**Additional context**
This issue came out of the Test Workshop on 11th Feb.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
One part of https://github.com/bbc/simorgh/issues/2228
