### ISSUE TITLE
Surface articles only on the correct Home

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1265]
**Is your feature request related to a problem? Please describe.**
If an article is homed in News, then it should be surfaced on a /news/ URL.  But if it is homed in Persian, then it should not be surfaced on a /news/ URL, but only on a /persian/ URL.

**URLs work**

Given an article has been published with a given id
And that article has Home set to Persian
When I visit https://www.bbc.com/persian/articles/:id
Then I see that article

**Right Home only**

Given an article has been published with a given id
And that article has Home set to a value other than Persian
When I visit https://www.bbc.com/persian/articles/:id
Then I see a 404 error page

**AMP works**

Given an article has been published with a given id
And that article has Home set to Persian
When I visit https://www.bbc.com/persian/articles/:id.amp
Then I see the AMP version of that article

**AMP only works for the right Home**

Given an article has been published with a given id
And that article has Home set to a value other than Persian
When I visit https://www.bbc.com/persian/articles/:id.amp
Then I see a 404 error page

**Describe the solution you'd like**
An article should only be available on the correct URL for its Home.
e.g. on Test, /persian/articles/c4vlle3q337o should work, but /news/articles/c4vlle3q337o should 404 (currently it 200s)

**Describe alternatives you've considered**
N/A

**Testing notes**
Besides Cypress, regressions testing that the above has been implemented as agreed.

Dev insight: Cypress test should be added to check that a persian id (for both canonical & AMP) with a news url gives a 404.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Updated Persian article URL in the ticket description (`c4vlle3q337o`).
