### ISSUE TITLE
Refactor nested data.model.blocks[0] calls

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1271]
**Is your feature request related to a problem? Please describe.**
Thought of a [nice way of refactoring our 'recursive' calls to `data.model.blocks[0].model.blocks[0]...`](https://github.com/bbc/simorgh/pull/1236#discussion_r256315802).

**Describe the solution you'd like**
A PR which implements the above suggestion and removes ugly chained code like that, across our application and our tests.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Regression test only.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked on #1352.

**Comment by jamesbhobbs** [comment]
No we shouldn't optimise recrusiveness, we should remove it
