### ISSUE TITLE
Timestamp: display time (when published > 10h && is today)

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1280]
**Is your feature request related to a problem? Please describe.**
We currently don't output the time in our timestamps - only the date. But under certain conditions, we do want to display the time (in BST, or in GMT, depending on when the article was published). NB, we're happy showing BST time to .com users (i.e. non-UK users).

Rule should be: 
- if it's yesterday or prior, given the timezone, we show the date
- if it's today, given the timezone, we show the date and time 
- if it's today, given the timezone, and less than 10 hours ago, we show the relative time.

Pseudocode for displaying absolute vs relative timestamps:

```
if ( (timestamp is lastPublished) || ( (timestamp is firstPublished) && (there is no lastPublished) ) )
    relativeTimeIsPossible

if (relativeTimeIsPossible && timestamp < 10 hrs ago) 
    displayRelativeTime() // e.g. "4 minutes ago"

else if (timestamp is from today)
    displayAbsoluteDateTime() // e.g. "4 March 2019, 15:14 BST"

else
    displayAbsoluteDate() // e.g. "4 March 2019"
```

Please note that this issue is NOT about the prefix text ("Updated") - this is simply to do with the datetime portion of the timestamp.

**Describe the solution you'd like**

The code for displaying absolute and relative time has been done, but the code for switching between the two has not - that's where this issue comes in. In addition, we'll need to add a formatting method to handle the time display, and import a timezone library to handle conversion to BST/GMT.

So we should be able to display all of these:

- `4 minutes ago`
- `13 February 2019`
- `13 February 2019, 14:36 GMT`
- `13 April 2019, 14:36 BST`

**Describe alternatives you've considered**
N/A

**Testing notes**
Cypress:
- We want to test content of the text, making sure that it is displaying correctly based on the information pulled in from Ares.

Manual:
- Test across devices/browsers to make sure it displays as expected and has no clipping issues, etc.

Accessibility:
- Use AT to make sure that the text is read out as expected.
- Test Colour Ratio.

We want to test content of the text, but will decide location between unit/cypress in issue refinement

James wants to test the behaviour with both a minor & major update, to make sure lastPublished only changes on major changes.

Potential edge case of GMT/BST change. If published in, hour is always the BST value. “X hours ago…” should always be the “real” value, not accounting for the +/- hour.

Dev insight: Will need lots of unit tests.

**Additional context**
[As described by Catharine](https://github.com/bbc/simorgh/issues/1282#issuecomment-463385663), we should ensure that "BST" & "GMT" are read out suitably on accessibility devices.

Probably worth branching off https://github.com/bbc/simorgh/pull/1519.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
[Catharine has also raised concerns about how a colon-separate time will be read out on accessibility devices](https://github.com/bbc/simorgh/issues/1282#issuecomment-463366590). Jim is aware of this, & we're awaiting a next step.

**Comment by sareh** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1279 & also on https://github.com/bbc/simorgh/issues/1322

**Comment by sareh** [comment]
Note: when choosing a timezone library, we should use the results from the investigation work here: https://github.com/bbc/simorgh/issues/637

**Comment by greenc05** [comment]
After some testing, note that the time format such as ‘09.36’ reads out well with our supported assistive technology (regardless of whether in a time HTML element or not).
The only exception seems to be with VoiceOver iPhone/Safari when the minutes start with a zero, such as ‘23:06’, in such cases it reads as ‘23:6’, while this isn’t ideal, I don’t think it’s worth the effort to resolve such a small use case. Awaiting results of Talkback from @jamesbrumpton

**Comment by dr3** [comment]
```
before moment stuff   390 KiB pre-gzip 105KiB gzip
without webpack magic 1.5 MiB pre-gzip 189KiB gzip
with    webpack magic 464 KiB pre-gzip 124KiB gzip
```

code used
```
moment(1554114593000).tz("Europe/London").format('MMMM Do YYYY, h:mm:ss a')
```
webpack magic used
```
new webpack.ContextReplacementPlugin(
  /moment[\/\\]locale$/,
  /en/
),
new MomentTimezoneDataPlugin({
  matchZones: 'Europe/London'
}),
```
19kb weight to add English London timestamps

**Comment by sareh** [comment]
@ChrisBAshton @eleanombre As a result of discussing requirements with @jimjohnsonrollings, I'm going to update the issue description - 

- If timestamp is yesterday (according to the timezone library), show absolute date `30 March 2019`
- If timestamp is today && is greater than 10 hours ago, show absolute date plus time `30 March 2019, 1:20pm BST`. 
- If timestamp is today && is less than 10 hours ago, show relative time `8 hours ago`.

**Comment by eleanombre** [comment]
@sareh @jimjohnsonrollings is this logic reproduced for both the published and updated timestamps? or just the updated one? eg is the expected behaviour:
(published) 2 hours ago
(updated) 1 minute ago
?
