### ISSUE TITLE
Update behaviour of Timestamp component

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1282]
**Is your feature request related to a problem? Please describe.**
UX have updated the designs for the Timestamp component.

It should now be able to display a phrase before the value, e.g. "Updated ___". However, this should not be included inside a `<time>` element, if we implement using one, & we should remember to favour `<span>` over `<div>`. [See this comment from Catharine regarding both of these aspects.](https://github.com/bbc/simorgh/issues/1279#issuecomment-463219731)

Also, we now wish to conditionally append hours to the timestamp (appearing following a comma), like so:
`13 February 2019`
`13 February 2019, 14:36 GMT`

Potential edge case of GMT/BST change.
The date will be based on BST if published under BST, GMT otherwise. This will always be true (will not change if viewing outside of BST, for example).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by greenc05** [comment]
I don't believe that the format '14:36' will read out well with a screen reader, is there a different time format that we could use here @jimjohnsonrollings @nataliesmart - that will work both visually and with a screen reader? Note, we want to avoid having one format displayed and another hidden for screen readers, as this will mean that some users get this content twice.

**Comment by greenc05** [comment]
Do we plan to display GMT/BST? If so, we should test that this reads out on our supported screen readers in the way that you would read this e.g. as letters and not a word

**Comment by bcmn** [comment]
Closing in favour of #1277, #1279, & #1280.

**Comment by greenc05** [comment]
After some testing, note that the time format such as ‘09.36’ reads out well with our supported assistive technology (regardless of whether in a time HTML element or not).
The only exception seems to be with VoiceOver iPhone/Safari when the minutes start with a zero, such as ‘23:06’, in such cases it reads as ‘23:6’, while this isn’t ideal, I don’t think it’s worth the effort to resolve such a small use case. Awaiting results of Talkback from @jamesbrumpton
