### ISSUE TITLE
Update ArticleMain to handle Timestamp position in blocks

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1288]
**Is your feature request related to a problem? Please describe.**
UX have updated the designs & behaviours for the timestamp component.

Currently, we use ArticleMain to always insert the Timestamp immediately after the headline. The desired UX is no longer this simple.

We should evaluate whether ArticleMain is a sustainable & scalable location to house this kind of  behaviour.

There are now several scenarios:

~~1) If the article data contains no headline, Simorgh should be able to render the page. In this scenario, the Timestamp Container is placed immediately after the Header.~~ Have raised #1483 to handle this scenario separately.

2) If the article data contains a headline, & it is immediately followed by a paragraph block, the Timestamp Container is placed between the Headline & Paragraph components.

3) If the article data contains a headline, & it is immediately followed by an image or video block, the Timestamp Container is placed after the Headline & Image/Video components. This is true regardless of the type of the third block.

**Describe the solution you'd like**

A spike PR which moves the Timestamp insertion logic into a separate pre-processing step (outside of ArticleMain). We are already doing scenario 2), so it's just a case of moving this to somewhere more sane. If good enough, we may merge.

Do something like wrap `getInitialData` in a `processForArticles` function, which changes the structure of the blocks / inserts the Timestamp block so that we can render really simply. This could be a precursor to implementing the algorithm defined at [articles-validator](https://github.com/bbc/articles-validator).

A second PR which augments this logic to accommodate scenario 3). We'll raise a new issue to accommodate scenario 1) if need.

**Describe alternatives you've considered**
Hard-coding the business rules in ArticleMain, but this doesn't scale to additional rules.

**Testing notes**
[Tester to complete]

Dev insight: This is mostly an investigation ticket. If anything is merged, we should have fixtures in Cypress tests to test this out, otherwise nothing to do.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by greenc05** [comment]
"If the article data contains no headline, Simorgh should be able to render the page. In this scenario, the Timestamp Container is placed immediately after the Header."

I thought it was decided that a page must have a headline (h1) in order for it to be rendered? Otherwise the page errors. This suggests otherwise? 

Are you aware of this @benjaminhobbs?

**Comment by jamesbhobbs** [comment]
@bcmn @ChrisBAshton It is critical that '* If the article data contains no headline, Simorgh should be able to render the page. In this scenario, the Timestamp Container is placed immediately after the Header. *' is not implemented. The hard rule is that if there is no headline the article does not render. We must have an h1 with the headline in it for all Articles. If there is no rule respecting this logic now a new issue needs to be created before v1 is released to prevent render in case of the absence of the headline.

**Comment by ChrisBAshton** [comment]
Agreed, let's remove that from our list of scenarios.

Hopefully we will have a contractual commitment to "an article must have a headline" in https://github.com/bbc/articles-validator.

**Comment by ChrisBAshton** [comment]
For the record, Optimo _will_ allow "no headline blocks" (or even "multiple headline blocks") in the CMS. The articles team is having a meeting on Monday to decide what to do in these scenarios.

**Comment by ChrisBAshton** [comment]
Raised #1483 to handle Timestamps where no Headline blocks exist.

**Comment by ChrisBAshton** [comment]
Also raised #1484 to handle Timestamps where Image/Video follows Headline block.

>If the article data contains a headline, & it is immediately followed by a paragraph block, the Timestamp Container is placed between the Headline & Paragraph components.

...is already happening.

Closing this issue in favour of the two new raised ones.

**Comment by ChrisBAshton** [comment]
Moved the crux of this issue to #1485.
