### ISSUE TITLE
Change position of Timestamp wrapper for GEL size classes

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1289]
**Is your feature request related to a problem? Please describe.**
Following #1280.

UX have updated the designs for the timestamp components.

**Describe the solution you'd like**
The element grouping both the "published" & "updated"  (likely the `div` in the Timestamp container) should become a Simorgh-only component in it's own right, containing CSS rules to handle positioning based on GEL viewport sizes.

There are two scenarios:
<img width="755" alt="1008px" src="https://user-images.githubusercontent.com/11646957/52742394-8ce40400-2fcf-11e9-9f26-0d4e8a5b4764.png">

- At 1008px (GEL Group 4) & below, the timestamps are positioned directly above the next element, left-aligned.

<img width="961" alt="1280px" src="https://user-images.githubusercontent.com/11646957/52742407-92414e80-2fcf-11e9-8724-0360b769a96d.png">

- At 1280px (GEL Group 5) & above, the timestamps are positioned _alongside_ the next component. 

Screenshot of layout with grid dev tools overlayed:
<img width="1092" alt="Screen Shot timestamp with grid overlay" src="https://user-images.githubusercontent.com/3028997/56202404-d89c4380-603a-11e9-8349-f3493fbc23e8.png">

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Snapshot tests sufficient until we have visual regression screenshot tests

**Additional context**
It's possible this kind of "drop into a specific left/right column, depending on LTR/RTL" behaviour, will be a common behaviour as we add onward journeys & similar. It might be worth exploring how we could abstract this in a generic & reusable way.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by oluoluoxenfree** [comment]
Where are the GEL groups defined?

**Comment by bcmn** [comment]
Hey @oluoluoxenfree, the GEL groups are defined in the [gel-foundations package](https://www.npmjs.com/package/@bbc/gel-foundations). You can see the exact file [here](https://github.com/bbc/psammead/blob/latest/packages/utilities/gel-foundations/src/breakpoints.js).
