### ISSUE TITLE
Add 'Abouts' to JSON-LD Schema block

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1290]
**Is your feature request related to a problem? Please describe.**
Tagging metadata is not exposed to Google.

**Describe the solution you'd like**
Add structured data to the schema.org JSON-LD block to reflect the tags an article has.

Example:
```
"about": [
	 {
		"@type": "Person",
		"name": "Duchess of Sussex",
		"alternateName": "Meghan Markle",
		 "sameAs": "http://dbpedia.org/resource/Meghan_Markle",
	}
]
```

 Notes:
- We should use all the tags that we receive from Ares for the 'about' predicate from
- Type values acceptable for JSON-LD are 'Person', 'Place', 'Event' and 'Organization' (note the Z, we spell it with an S internally) - these should map directly from the Ares response, however tags in Ares can have multiple types.  If a tag has exactly one of the above types in the thingType array, then we should use that, otherwise we should set the '@type' value as 'Thing'
- The 'name' field should use the 'thingLabel' field from Ares
- Use `thingSameAs` for the sameAs - but we should only use the value with a dbpedia.org URI (if one exists), otherwise skip this field
- Use the value of skos:altLabel (this is not yet in Ares) for 'alternateName', if there are any.  Multiple alternateNames can be added (how?)

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: We should add unit tests. We should validate it with https://search.google.com/structured-data/testing-tool/u/0/

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jimjohnsonrollings** [comment]
Need to do https://github.com/bbc/simorgh/issues/577 first

**Comment by pjlee11** [comment]
>**More specific Types**
>Action
>CreativeWork
>Event
>Intangible
>MedicalEntity
>Organization
>Person
>Place
>Product

_Source: https://schema.org/Thing_

We will need to take the `about` metadata object from the Ares payload and add a schema.org entry for the relevant `Thing` as the value of `@type`. [Example data](https://github.com/bbc/simorgh/blob/latest/data/prod/news/articles/cl55zn0w0l4o.json#L808-L876)
