### ISSUE TITLE
Investigate Echo integration for canonical pages

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1300]
**Is your feature request related to a problem? Please describe.**
We would like to investigate a possible implementation of analytics, using Reverb directly. Reverb does not currently support single page web applications. [Their current intended solution for this is a pageReset event in Orbit](https://jira.dev.bbc.co.uk/browse/ORBITEN-821), however, this investigation **will not use Orbit**. As such, a key part of this investigation will have to include a feasible way of sending further content to Reverb.

Update: We don't believe we could implement Reverb directly, but instead would have to go through a variant of Echo.

**Describe the solution you'd like**
Implement integration with Reverb such that the following details are correctly send to ATI on the initial and subsequent article visits.

Definition of done. To send these details to ATI:

See #1310.

**Describe alternatives you've considered**

**Testing notes**
Check that the beacons fire within the page. Similarly, test that the corresponding beacon matches that found within the ATI explorer. Double check these values with @jimjohnsonrollings and/or Shan Shan. The behaviour experienced from Reverb should be the same as ATI.

Dev insight: We should have unit tests. We should manually test this.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Closed in favour of #1310.
