### ISSUE TITLE
Analytics for client-side onward journeys

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1305]
**Is your feature request related to a problem? Please describe.**
Reverb is the JS library we could use for sending analytics data to ATI for canonical pages.
Currently, it does not send requests to handle client-side links to other articles. 
We should ensure that we send requests.

**Describe the solution you'd like**
We should note the work the Orbit team are making to Reverb: https://jira.dev.bbc.co.uk/browse/ORBITEN-821 

As a result, we should detail on this issue what needs to be changed to our application to send analytics for client-side interactions to ATI. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests to ensure we're sending the correct data. Manual tests for checking it's working end-to-end. 

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Blocked pending work on https://github.com/bbc/simorgh/issues/1300  & https://github.com/bbc/simorgh/issues/1310

**Comment by sareh** [comment]
Out of scope for V1.

**Comment by chris-hinds** [comment]
We already have a custom solution around sending analytics to ATI, this can be closed.
