### ISSUE TITLE
Implement ATI Analytics

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1310]
**Is your feature request related to a problem? Please describe.**
Blocked on #1216, #1300 & #1299.

**Describe the solution you'd like**
Once we've decided on an implementation, following the issues listed above, we need to implement the following analytics values, & ensure they're being sent:

Refinement note: How do we check if a user is in UK?

Field | Parameter | Condition | Value | Comments
-- | -- | -- | -- | --
Destination | s | User in UK | `NEWS_PS` (as id number) | NB. This will be different for WS when we get there
Destination | s | User not in UK | `NEWS_GNL` (as id number) | NB. This will be different for WS when we get there
Destination | s | On TEST environment | The same value, appended with `_TEST` (as id number) | NB. This will be different for WS when we get there
Producer | s2 |   | `NEWS` (as id number 64) | Hard-coded for now, until Optimo provide alternative
Page identifier | p |   | `news.articles.cl55zn0w0l4o.page` | Hard-coded for now, until Optimo provide alternative, use `news.articles.unknown.page` if id unknown
screen resolution & colour depth | r |   | `1920x1200x24x24` | Hard-coded for now, until Optimo provide alternative
browser/viewport resolution | re |   | `1146x1066` | Hard-coded for now, until Optimo provide alternative
time | hl |   | `13x11x31` | Hard-coded for now, until Optimo provide alternative
device language | en-US |   | `health` | Hard-coded for now, until Optimo provide alternative
Content ID | x1 |   | `urn:bbc:optimo:c??????????o` | Where the final part is the Optimo ID
Content Type | x7 |   | `article` | Hard-coded
App Type | x2 | Not AMP | `responsive` |  
App Type | x2 | AMP | `amp` |  
App Name | x3 |  | `news`  `news-persian` (this format for WS sites) |
Language | x4 |   | `aresResponse.metadata.passport.language` |  
URL | x5 |   | `window.location.href` (or equivalent) | Should be set by Library
Referrer URL | x6 |   | `document.referrer` (or equivalent) | Should be set by Library
Page title | x9 |   | `aresResponse.promo.headlines.promoHeadline`, spaces replaced by + |  
Publication date | x11 |  | `aresResponse.metadata.firstPublished` | YYYY-MM-DDTHH:MM:SSZ
Updated date | x12 |   | `aresResponse.metadata.lastPublished` | YYYY-MM-DDTHH:MM:SSZ
LDP Things | x13 | If set | `aresResponse.metadata.tags.about[i].thingLabel` separated by ~, spaces replaced by + | e.g. `Duchess+of+Sussex~Windsor~Hackney`
LDP Things IDs | x14 | If set | `aresResponse.metadata.tags.about[i].thingId` separated by ~  | e.g. `803eaeb9-c0c3-4f1b-9a66-90efac3df2dc~282061c0-3743-4eb0-9dde-6d710389630f~f2815ef8-ea42-414b-865c-d5e92b5207e7`
Location | x18 | loc_serve cookie is set | `true` |  
Location | x18 | loc_serve cookie is not set | `false` |  

**Describe alternatives you've considered**

**Testing notes**
Testing with ATI tool, both in browser and with the dashboard client. Jim to collaborate by looking ATI dashboard client.

Dev insight: Depends on implementation: Unit tests to ensure we're passing the values to Reverb correctly? Discussion at refinement about possibility of checking network calls as part of E2E tests, but wariness as this could be testing a dependency/other projects have found this flaky.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
James Donohue noted that the Mozart country is already utilised for ATI analytics news front page, weather pages, & existing news topic pages (in addition to additional logic recreating the same behaviour in the PAL) so using that would maintain consistency. 

See: https://github.com/bbc/mozart-controller/blob/ded5dbabefebb23ad3c7415bb3b1211cf577c79a/src/contexts/bbc/analytics/handler.rb#L9

https://github.com/BBC-News/core/blob/46d8dd749f95427c123fc95fabe9e258cc292a47/src/main/BBC/News/Core/Controller/BaseController.php#L291

**Comment by jimjohnsonrollings** [comment]
We should hold off implementing this until we know what Ares are doing - they may collate all of these fields into a nice simple group for us...

**Comment by jamesbrumpton** [comment]
![image](https://user-images.githubusercontent.com/25743793/59106738-0ca32f00-892f-11e9-9724-9f866cb8a53e.png)
![image](https://user-images.githubusercontent.com/25743793/59106771-204e9580-892f-11e9-82e4-bbc3fa3064d9.png)
There are currently errors with `x9` & `x13`. Please see the attached screenshots. These were found on the AMP & canonical article on both `news` (UK) & `persian`.

No ATI request is visible within the ATI console when JS is disabled.

On Persian, `Page - Level2` returns as `News (64)` instead of `Persian (69)`. Also, `Context Variables` returns `Site number` as `PS_NEWS_TEST`.

Thanks

**Comment by sareh** [comment]
After talking with Alex, there was a clarification in requirements - all spaces (e.g. for page title and ldp things) should be replaced by `+`s. I've updated the issue description to reflect this.
