### ISSUE TITLE
Handle edge case of very long image copyrights

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1317]
**Is your feature request related to a problem? Please describe.**
UX have updated the designs regarding images.

If an image is smaller than the copyright element associated with it, it should be presented in a box the height of the image & the width of the copyright element. The background of this box is `#F2F2F2`, or "Lunar".

![screenshot 2019-02-19 at 07 47 55](https://user-images.githubusercontent.com/11646957/52998518-641e9d00-341b-11e9-8fef-53e69833fbec.png)

**Describe the solution you'd like**
Consider using CSS only - can apply a background-color to `figure` which is only ever displayed when the image is smaller than the caption. When the image is bigger than the caption, the background color is 'behind' that and doesn't get seen. So is potentially doable in a line or two of CSS.

It may be that we need some extra CSS to make sure the figcaption doesn't wrap onto two lines.

We should add some fixture data to demonstrate our solutions works. So PR should be made up of CSS tweaks and new fixture data.

**Describe alternatives you've considered**
N/A

**Testing notes**
Another reason to invest time into the screenshot test functionality (3rd party based) within Cypress. Otherwise, regression testing across devices/browsers to make sure there's no overlapping or other UI issues.

Dev insight: Screenshot test (if/when we have them) perfect for this sort of thing. Otherwise manual testing with the fixture data.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Is there a reason why in this case the image is also centre-aligned? Surely it should be consistent with every other use-case, where our images are left-aligned for images when the text is left-to-right.

**Comment by ChrisBAshton** [comment]
The Figure is left-aligned, but the image within it is center-aligned. In every other case we see no alignment on the image itself as it's the same width as the Figure.

**Comment by sareh** [comment]
This is blocked on ensuring images aren't stretching to full width: https://github.com/bbc/simorgh/issues/1401

**Comment by jimjohnsonrollings** [comment]
Closing as we've changed the approach to small images in later discussions.
