### ISSUE TITLE
v1 Responsive Image Captions

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1323]
EDIT: do not attempt to refine until #1318 is complete - too difficult!

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
**GEL Group 1 (0-399px)**
**GEL Group 2 (400-599px)**

All:
Caption spans 6 columns, starting column 1.

**GEL Group 3 (600-1007px)**
Landscape:
If image 6 columns wide, caption spans 5 columns, starting column 1.
If image less than 6 columns wide & more than 4 columns wide, caption matches the width of the image, starting column 1, to a minimum width of 4 columns.

Portrait:
Caption spans 4 columns, starting column 1.

Square:
Caption matches the width of the image, starting column 1, to a minimum width of 4 columns.

**GEL Group 4 (1008-1279px)**
Landscape:
If image more than 4 columns wide, caption spans 5 columns, starting column 2.
If image less than 4 columns wide, caption matches width of image, starting column 2, to a minimum width of 3 columns.

Portrait:
Caption spans 3 columns, starting column 2.

Square:
Caption matches the width of the image, starting column 2, to a minimum width of 3 columns.

**GEL Group 5 (1280px+)**
Landscape:
If image more than 10 columns, caption spans 10 columns, starting column 5.
If image less than 10 columns wide, caption matches width of image, starting column 5, to a minimum width of 8 columns.

Portrait:
Caption spans 8 columns, starting column 5.

Square:
Caption matches width of image, starting column 5, to a minimum width of 8 columns.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked pending #1318.

**Comment by dr3** [comment]
We have decided to do an MVP version of this first https://github.com/bbc/simorgh/issues/1369

**Comment by sareh** [comment]
Closed since this is part of this issue now: https://github.com/bbc/simorgh/issues/1751
