### ISSUE TITLE
Cypress - Remove Reith Fonts From Tests

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1328]
**Describe the solution you'd like**
We need to remove any reference to the Reith font within the Cypress tests.

**Testing notes**
The tests should pass as expected once these font references have been removed.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
@jamesbrumpton please explain why in the desc?

**Comment by jamesbrumpton** [comment]
I'm unclear as to why this issue was raised. Will close and if this work *is* needed I'll open another issue.
