### ISSUE TITLE
Puppeteer - Test vendor bundle links

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1329]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
We would like to ensure that the links to client JS bundles on Simorgh pages point to the correct environment and return a valid 200 status code.

**Testing notes**
Make sure the Cypress tests pass when pointing to the correct environment but also test that they fail when pointing to the wrong environment.

- [ ] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
This is handled partially here: https://github.com/bbc/simorgh/blob/latest/puppeteer/bundleRequests.test.js I'm not sure it's practical to do more and have the test be stable.

**Comment by jamesbhobbs** [comment]
Done as much as it will be
