### ISSUE TITLE
Travis not running test steps

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1330]
**Describe the bug**
The following steps appear to never run inside Travis: https://github.com/bbc/simorgh/blob/latest/.travis.yml#L5-L14

Instead, only https://github.com/bbc/simorgh/blob/latest/.travis.yml#L15-L21 is run.

See https://api.travis-ci.org/v3/job/496108965/log.txt (built off https://github.com/bbc/simorgh/pull/1312)

**To Reproduce**

1. Open a PR
2. Wait for Travis check to pass/fail
3. View the Travis console output
4. See that `xvfb-run npm run test:e2e:storybook:ci` is never run (and no reference to `codeclimate`

**Expected behavior**
Both of the `stage: test` 'blocks' should be running, in order.

**Screenshots**
N/A

**Additional context**
#1312 is currently failing on Jenkins, so I wanted to see if it's failing on Travis too. But the cypress tests aren't even running on Travis.

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by sareh** [comment]
Travis splits this into two jobs that run in parallel:
e.g. parent job: https://travis-ci.org/bbc/simorgh/builds/496108962
that starts two child jobs: 
https://travis-ci.org/bbc/simorgh/jobs/496108964 
https://travis-ci.org/bbc/simorgh/jobs/496108965
The first of the two jobs runs lines L5-L14 that you referred to.

**Comment by ChrisBAshton** [comment]
Ah - my bad! Thanks for explaining.
