### ISSUE TITLE
Ensure canonical articles specify amp articles in metadata

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1337]
**Is your feature request related to a problem? Please describe.**
Canonical articles don't currently specify the location of the equivalent AMP article.

**Describe the solution you'd like**
```
<link rel="amphtml" href="https://www.bbc.com/news/articles/c0000000000o.amp">
```
The TLD should always respect the same TLD as the user is on.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will need unit tests. Cypress tests could be dificult due to restrictions on tld due to mozart redirect on test. Investigation needed.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
@ChrisBAshton What is this blocked on?

**Comment by ChrisBAshton** [comment]
I _think_ this was blocked on a decision from @jimjohnsonrollings around this question:

* If we're viewing a canonical article on .co.uk, should the AMP metadata point to .com?

Jim was going to check with an SEO expert.

**Comment by jimjohnsonrollings** [comment]
I have checked. We should point to the same domain. So .co.uk<http://co.uk> to .co.uk<http://co.uk>, .com to .com

**Comment by ChrisBAshton** [comment]
Therefore blocked on #1451.

**Comment by sareh** [comment]
No longer blocked since #1451 is complete
