### ISSUE TITLE
Add hreflang metadata

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1338]
**Is your feature request related to a problem? Please describe.**
We should specify that .co.uk is the alternate url for hreflang=en-gb

**Describe the solution you'd like**
Update the metadata container and component to add the additional information.

```
<link rel="alternate" href="https://www.bbc.co.uk/news/articles/c0000000000o" hreflang="en-gb" />
<link rel="alternate" href="https://www.bbc.com/news/articles/c0000000000o" hreflang="en" />
<link rel="alternate" href="https://www.bbc.com/news/articles/c0000000000o" hreflang="x-default" />
```

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Can add cypress tests, snapshot tests likely sufficient.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
I don't think that we should do this, since on `.com/news/articles/*` and `.co.uk/news/articles/*`, we'll be publishing pages with `lang` `en-GB`.

**Comment by jimjohnsonrollings** [comment]
I will enquire further...

**Comment by jimjohnsonrollings** [comment]
Updated description after follow-up chats with SEO gurus

**Comment by sareh** [comment]
@jimjohnsonrollings Should the alternate link tags for AMP pages also be the same as those above? Also for Persian, should there be no alternate links?

**Comment by jimjohnsonrollings** [comment]
@sareh For AMP pages they should have the equivalent AMP URLs.  For Persian there should current be no alternate links (though I'd like to have the meta-data some day to do them).
