### ISSUE TITLE
Evaluate whether cleartype metadata is required

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1339]
**Is your feature request related to a problem? Please describe.**
In the past, we have used:
```
<meta http-equiv="cleartype" content="on">
```
Which does something to fonts in some versions of IE.  Some advice suggests this should no longer be used.

**Describe the solution you'd like**
We should decide whether we want to use it.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
@jimjohnsonrollings testing on my desktop this does seem a significant improvement, but I'm not the best at seeing differences in fonts. Given the cost of doing this is nearly nothing, why don't we just do it? Maybe you found a source citing that it's bad practice?

**Comment by jimjohnsonrollings** [comment]
@benjaminhobbs A couple from a quick google
https://blog.giantgeek.com/?p=1250
https://www.drupal.org/project/drupal/issues/1717090

I'm happy either way - just didn't want to blindly say to implement it without someone more knowledgable making a judgement whether it was still relevant, as all these things on responsive were put in 4-7 years ago.

**Comment by jamesbhobbs** [comment]
@jimjohnsonrollings hadn't thought it needed the conditionality, we def shouldn't do it then
