### ISSUE TITLE
Dynamically load components

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#1342]
**Is your feature request related to a problem? Please describe.**
At the moment we load components by route. This is the normal but not optimised means of loading components in a React application. We should load React components only as they are needed this mean code splitting more incrementally and then only loading these smaller chunks as they're needed. The ideal way to do this in React is with React.lazy and Suspense but these are unavailable for Server Side Rendered (SSR) apps (citation: [React docs](https://reactjs.org/docs/code-splitting.html#reactlazy)

**Describe the solution you'd like**
As the same docs recommend for SSR apps we should use [Loadable components](https://github.com/smooth-code/loadable-components)

Questions I have for refinement: Do we need to have error boundaries for this to be used in production? I think not. When do we want to use: webpackPrefetch and webpackPreload with this? Should this be defined in our framework or each client app?

**Describe alternatives you've considered**
We could do this ourselves rather than use this library. I found what seems a reasonable approach [here](https://www.slightedgecoder.com/2017/12/03/loading-react-components-dynamically-demand/) but as the React docs say use the library I believe we absolutely should. If only because once/if React.lazy and Suspense do support SSR there should be an easier migration path.

**Testing notes**
[Tester to complete]

Dev insight: The potential regression of this is total failure to load a page. The existing e2es tests that cover SSR and I think Client Side Render (CSR) should be sufficient. However, testing the number and size of chunks in the network tab would be a non-regression testing means of manual testing. If we use Error boundaries we need to explain these thoroughly.

**Additional context**
Docs for the recommended library are here: [Loadable Components](https://www.smooth-code.com/open-source/loadable-components/docs/getting-started/)

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
@benjaminhobbs How granular would you recommend we make the chunks in terms of the number of components in them?

**Comment by sareh** [comment]
I'd imagine we'd want to group components that would appear together. E.g. the video container, plus caption, but not those that'd be unlikely to appear on a page together, to prevent unnecessary loading of JS. 

Since we'll almost always have a headline, text and (highly likely) an image, the outstanding components for loading dynamically can be the Video container, ErrorMain container, plus Image captions & copyright and Subheading.

**Comment by jamesbhobbs** [comment]
@sareh @dr3 I largely agree with Sareh's comments, though these components are so small it's highly questionable whether it's worth doing at all. Only video seems like something that could be large. This should be considered in two ways: 1. what is optimum performance data saving vs additional request 2. is this increase in performance worth the cognitive load of additional complexity in the codebase. With what we currently have in the repo I strongly believe it's not worth doing at all. As time goes on this needle will move, which is why I've left this issue for later consideration, I doubt it should be in v1 at all, and definitely shouldn't be considered before v1.1.

**Comment by sareh** [comment]
Blocked until we have an example of video, to dynamically load.

**Comment by jamesbhobbs** [comment]
Related to https://github.com/bbc/simorgh/pull/1872

**Comment by dr3** [comment]
This is now unblocked, and is possible in loadable components. What do we want to do this for? Why?

**Comment by dr3** [comment]
Going to leave this issue untill we have/ or will soon have, Adverts

**Comment by jamesbhobbs** [comment]
Closing as it's perpetually blocked, we know what we will do long term.
