### ISSUE TITLE
Preload woff2 font files?

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#1343]
**Is your feature request related to a problem? Please describe.**
In lighthouse tests, specifically measurements of 'First Meaningful Paint' (but also the warning re critical request depth) there is strange behaviour. All our font families are set to display optional. Yet the lighthouse tests show the late loading of the file as a major impediment to FMP, literally adding over a second to this measure. This seems really odd.

**Describe the solution you'd like**
I don't really mind. The quick solution would be to hardcode preload woff2 files in ResourceHints in addition to the preconnect to the domain. But it seems like some investigation of whether this is a bug to report to Lighthouse or there is a real render problem should be looked at as the reported time difference on the FMP is massive.

**Describe alternatives you've considered**
Ignore it as you cannot see a difference in the render snapshots. Seems lazy.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jakearchibald** [comment]
From the description it sounds like a bug in Lighthouse.

I tried to recreate it https://font-optional-lighthouse-test.glitch.me/ - this page has an optional font that takes 5 seconds to load, but it doesn't seem to impact FMP.

What do I need to do to recreate this issue locally?

**Comment by chris-hinds** [comment]
> From the description it sounds like a bug in Lighthouse.
> 
> I tried to recreate it https://font-optional-lighthouse-test.glitch.me/ - this page has an optional font that takes 5 seconds to load, but it doesn't seem to impact FMP.
> 
> What do I need to do to recreate this issue locally?

Hi @jakearchibald apologies we are only just getting around to this. I have been looking into this today and yes it does seem like a bug in lighthouse.

I have tested a few articles running against lighthouse 4.2 (current version in chrome stable) and also against LH 5.0, both version seem to show this same bug.

Looking at the source code of the rendered article there are 6 instances of `@font-face` each `@font-face` declaration has the font-display property set to optional.

Too replicate locally;

1. Clone https://github.com/bbc/simorgh
2. run `npm i && npm run build`
3. run `npm start`
4. Run lighthouse against `http://localhost:7080/news/articles/cn7769kpk9mo`

I have seen a number of bugs filed against LH already for this issue, each one seems to have been labeled as `fixed` however.

**Comment by chris-hinds** [comment]
Closing as we believe this be a bug in chrome/lighthouse
