### ISSUE TITLE
Implement "DIY" Compliance/GDPR on canonical pages

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1345]
**Is your feature request related to a problem? Please describe.**
After investigating our article pages could use orbit (The standard BBC page header, footer and page javascript), we have decided that at this time it is not performant enough and thus we need to create our own GDPR compliant cookie banner.

An investigation was done for this https://github.com/bbc/simorgh/issues/1298 and a PR created https://github.com/bbc/simorgh/pull/1336

**Describe the solution you'd like**
Implement a canonical cookie banner taking all the learnings from https://github.com/bbc/simorgh/pull/1336. We must ensure that our cookie banner meets all the needs to be GDPR compliant while also being compatible with the rest of the site. We dont need to worry about only showing the banner in the EU as per [Jims comment](https://github.com/bbc/simorgh/issues/1298#issuecomment-466345147)  

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: The cookie banners should look the same as the banners provided by orbit on other BBC pages. However, in this MVP version, we will not include the icons (e.g. cog icon and tick icon). 
This issue should add the cookie banners to Storybook. It should not integrate into the Article container. 

**Additional context**
I have written and commented the findings of the PR in this issue https://github.com/bbc/simorgh/issues/1298

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked pending us getting a signed-off feature file of legal requirements for the cookie banner.

(We can of course work on the front-end separately).

**Comment by ChrisBAshton** [comment]
Duplicated by #1398.
