### ISSUE TITLE
Make the Metadata component more reusable

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1350]
**Is your feature request related to a problem? Please describe.**
Currently our metadata component only supports articles that have rendered. With https://github.com/bbc/simorgh/pull/1295 we have to have metadata for an error page which means it doesnt have access to values that an article would, like last updated for example.

**Describe the solution you'd like**
Make the metadata component more dynamic, allowing you to optionally set certain values.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
This was done
