### ISSUE TITLE
Automate testing of special character rendering

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1370]
**Is your feature request related to a problem? Please describe.**
Following #401 we have a manual process to test a certain fixture data article that contains special characters. We should have an automated process that checks these special characters render.

**Describe the solution you'd like**
Using screenshot functionality (in cypress or similar) we could compare the visual render of the components that are required to correctly render special characters (EG: Headline, Subheading, Paragraph, etc). 

**Describe alternatives you've considered**
We could screenshot the entire article containing the special characters but this would likely mean that any visual change would flag up as a warning, which would be almost identical to manually checking the article. 

**Testing notes**
[Tester to complete]

Dev insight: We should pair with the Testers for this issue. 

**Additional context**
We will likely want to use the test asset `cev804m5n0vo` or a mock asset to ensure the content is consistent between screenshots. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
This would be completely covered by https://github.com/bbc/simorgh/pull/2530 which we will shortly enable on psammead and simorgh
