### ISSUE TITLE
De-dupe errorPage<service>.js files

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1371]
**Is your feature request related to a problem? Please describe.**
De-dupe errorPage<service>.js files so that the tests work across several services by using only one file, rather than the current "one per service" approach.

**Describe the solution you'd like**
We can take one of the current test files as a template and implement logic by where we pass through a service, rather than it be hard coded to a specific service in individual files.

**Testing notes**
Tester insight: Tests should pass in Cypress. This will not change any UI.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
[Example provided by Drew](https://gist.github.com/dr3/d10ad42e2ec0dfaff22b00363c014ceb#file-tests-js)

- [ ] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
No longer an issue
