### ISSUE TITLE
Dynamically integrate Headline to MainContent component

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#138]
**Is your feature request related to a problem? Please describe.**
Now we have a Headline component, we should dynamically integrate it to the MainContent component based on the `type`.

**Describe the solution you'd like**
There is already some [conditional integration](https://github.com/bbc/simorgh/blob/latest/src/app/components/MainContent/index.jsx#L17-L19) of a Headline component in the MainContent component. However, we should dynamically integrate a component (just `Headline` for now) based on the `type` of the block. This should be in the form of an object that contains the components, where we can fetch components from based on `type`. We should then pass the whole block to that component

It should fall back to rendering a stringified block to a paragraph.

Can use the similar example here https://github.com/bbc/simorgh/blob/recursive-model/src/app/optimo/renderBlocks.jsx (should not be recursive).

**Additional context**
Depends on https://github.com/bbc/simorgh/issues/116.

**Comment by pjlee11** [comment]
Text will also be integrated into MainContent at the same time as the Headline
