### ISSUE TITLE
Client-side render fallback: Refresh on failure

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1383]
**Is your feature request related to a problem? Please describe.**
On first page load, the Simorgh application is initialised such that if the user clicks on a link to a second Simorgh article, we request only the data (via the JSON endpoint) and render the article inline.

**Describe the solution you'd like**
If the JSON endpoint is down (5xx error), we want to force refresh the page, providing the user with the server render.

We need to make sure we cant cause a redirect loop. This cant happen now, but when we have dynamic error page we dont want someone to land on one, and ensure it doesnt force refresh on the server rendered error.

Once you have an initial solution, show it to Pod to discuss and consider.

**Testing notes**
On clicking an inline link on an article page for which the json endpoint is 5xx should refresh the page automatically once and the page should be re-rendered which would either load the page or 404.

Dev insight: Cypress tests required. How can re replicate 500 on cypress? Test to ensure doesnt retry on 404, only 5xx.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
@jamesdonoh I don't think we should error on the data endpoint failure in the case of 5xx, I think we should stop attempting CSR and make a real req for the same article SSR'd (it's possible that'd fail, but this gives 1 extra layer of fallback if CSR is broken on a release). PS as to whether we should ever do this, though that'd be extremely defensive.

**Comment by dr3** [comment]
After thinking about this more, I think we should hold off doing this until we have better user event tracking. Force refreshing the page could lead to unexpected behaviour which we should track. This behaviour should be required very infrequently, so tracking to ensure that is the case is important IMO

Thoughts?

**Comment by dr3** [comment]
Blocking untill we have Real user metrics to detect if this logic broke and caused refresh loops
