### ISSUE TITLE
Client-side render fallback: User loses network connection

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1384]
**Is your feature request related to a problem? Please describe.**
Simorgh should detect a loss of network availability and display a warning message to the user along the lines of "You don't appear to be connected to the internet. Try refreshing your browser".

**Describe the solution you'd like**
A PR which adds the described functionality, with tests.

Then update this section of the runbook: https://confluence.dev.bbc.co.uk/display/NEWSART/Articles+Architecture#ArticlesArchitecture-Userlosesnetworkconnection

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Cypress tests required.

**Additional context**
Blocked on designs & wording from product / UX.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
Some browsers already do this, and we shouldn't be going down this road we should be adding offline support.
