### ISSUE TITLE
We should set gzip as the fallback to brotli for compression

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1387]
**Is your feature request related to a problem? Please describe.**
As per [this blog](https://medium.com/groww-engineering/enable-brotli-compression-in-webpack-with-fallback-to-gzip-397a57cf9fc6) we should specify `orderPreference: ['br', 'gz'],` whereas we currently only specify `orderPreference: ['br'],`

**Describe the solution you'd like**
Enable gzip as a fallback to brotli, we should also test this fallback is working correctly.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
This may be happening by default but we should check that behaviour as part of this ticket.

**Comment by jamesbhobbs** [comment]
This is happening by default, NB we're passing preference not algorithm.
