### ISSUE TITLE
Document an overview our CD process

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1397]
**Is your feature request related to a problem? Please describe.**
We should document our CD process and that merges to live go straight to production. Also document the limitation of when we should/shouldn't merge. EG: Within work hours and not after 5pm on Fridays. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
This shouldn't be done in this repo. If done at all it should be in our private repo. We don't want to refer to any detail of our pipeline. Suffice to say we have CD, but we don't need to explain how it works and how it's secured publicly.
