### ISSUE TITLE
Pair with UX - Images - left-alignment & not stretching

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1401]
**Is your feature request related to a problem? Please describe.**
As part of the v1 image work https://github.com/bbc/simorgh/issues/1319, we need to ensure that we do not stretch the image wider than the width of the original. Also, we should left-align (for LTR services like News). 

**Describe the solution you'd like**
- Always left-align images, starting at the first 'content' column. 

- If the image width (_X px_) is smaller than the maximum value of a breakpoint
   - then there should be a margin `${GEL_MARGIN_BELOW_400PX}` `${GEL_MARGIN_ABOVE_400PX}`
   - and the image should have `max-width: _X px_` & `width: 100%`. 

- If the image width (_X px_) is greater than the maximum value of a breakpoint
   - then there should no margin 
   - and the image should have `max-width: _X px_` & `width: 100%`. 

Example: image at the bottom of this article: https://www.test.bbc.co.uk/news/articles/c5jje4ejkqvo 
Zeplin example: https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c596fa94e189735593e60e8 

Testing with 5 images - each having a width that is within each breakpoint
```
    Group 1 - 0 – 399px
    Group 2 - 400px – 599px
    Group 3 - 600px – 1007px
    Group 4 - 1008px+
    Group 5 - 1280px+
```
**Describe alternatives you've considered** 
N/A

**Testing notes**
Manual regression testing, which includes devices of different sizes and browsers of different operating systems. Make sure that there's no regression with the implementation of this logic.

Dev insight: Unit tests, small widths of images should not be stretched out to be wider than the original uploaded size. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Could we link to some visual assets that explain these requirements? EG: Zelpin or screenshots
Mainly asking because I'm unsure how we are expecting the image to look with an above and below margin?

**Comment by sareh** [comment]
There is a Psammead PR and a Simorgh PR. 
I have written the issues I'm having with linking up locally to view changes, since there's an issue with styled components (likely multiple instances of it on the page) https://github.com/bbc/simorgh/pull/1429#issuecomment-474219721

**Comment by ChrisBAshton** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1508.

**Comment by jimjohnsonrollings** [comment]
I will create an example asset with different sizes of image

**Comment by jimjohnsonrollings** [comment]
Test asset: c041xzjrn9ro

**Comment by jimjohnsonrollings** [comment]
The test asset now has a variety of sizes of landscape, portrait, and square images.

**Comment by sareh** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1508

**Comment by sareh** [comment]
Closed as being addressed via this issue https://github.com/bbc/simorgh/issues/1751
