### ISSUE TITLE
Cookie Banner International text

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1403]
**Is your feature request related to a problem? Please describe.**
The Cookie banner's text should differ if outside of the UK. 
We should receive a header and display appropriate text

In UK:
<img width="1285" alt="Screen Shot 2019-03-11 at 08 41 10" src="https://user-images.githubusercontent.com/3028997/54122481-116e4a80-43f5-11e9-8aee-f24b371095db.png">

Outside UK:

TBC. But needs to fit `First time users not in UK are shown the cookie banner with advertising information`. (https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/features/cookie-banner.feature#L16).

**Describe the solution you'd like**
Vary the text depending on the location. In https://github.com/bbc/simorgh/blob/latest/src/app/containers/ConsentBanner/Banner/Text.jsx listen to the context to vary the messaging.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Add a cypress tests, passing in the header from mozart and looking at the response on AMP. On canonical we might have difficulties changing the TLD, and on test and live there will be issues due to the mozart redirect. Investigation needed.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked on https://jira.dev.bbc.co.uk/browse/RESFRAME-2657

**Comment by ChrisBAshton** [comment]
Assigning to @jimjohnsonrollings - need an exact wording for UK and non-UK before we can consider this issue 'refined'.

**Comment by jimjohnsonrollings** [comment]
UK wording:
"Let us know you agree to cookies"
"We use cookies to give you the best online experience."
"Please let us know if you agree to all of these cookies."
"Yes, I agree"
"No, take me to settings"

Non-UK wording:
"Let us know you agree to cookies"
"We and our partners use technologies, such as cookies, and collect browsing data to give you the best online experience and to personalise the content and advertising shown to you."
"Please let us know if you agree."
"Yes, I agree"
"No, take me to settings"

**Comment by ChrisBAshton** [comment]
Blocked on #1451.
