### ISSUE TITLE
Grid fallback not working in IE8

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1404]
**Describe the bug**
The text for Article widths should be constrained at large breakpoints on IE 8.

**To Reproduce**

1. Go to browserstack, using IE 8 browser
2. Visit https://www.test.bbc.co.uk/news/articles/c85pqyj5m2ko
3. See Article text take full screen width:

<img width="1412" alt="Screen Shot 2019-03-11 at 14 19 48" src="https://user-images.githubusercontent.com/3028997/54130692-c2321500-4408-11e9-9492-554b489fa9d2.png">

**Expected behavior**
To have the correct fallback behaviour for IE 8. 
The correct behaviour _is_ working for iOS 7 with Safari, which doesn't support CSS Grid:

Browserstack screenshot with iOS 7 with Safari, with iPad Air 2 in landscape view:
<img width="745" alt="Screen Shot 2019-03-11 at 14 18 27" src="https://user-images.githubusercontent.com/3028997/54130595-91ea7680-4408-11e9-9931-83e52e8557df.png">

**Screenshots**

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by jamesbhobbs** [comment]
@sareh this is still very readable, what's the usage % on IE8 for /news? i.e. tempted by wontfix

**Comment by jamesbhobbs** [comment]
We don't support IE8, not even close, we support >11
