### ISSUE TITLE
Reith font-face loading intermittent 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1406]
**Describe the bug**
The Reith font-face loads intermittently, regardless of local storage/cache of the font-face.

**To Reproduce**

1. Visit a simorgh article
2. Disable javascript on the page (not sure why this causes the bug)
3. Reload the page several times (5+)
4. See the font-family change from Reith to Helvetica intermittently 

**Expected behavior**
I would expect the font-family to remain consistent if the `<style>` tag is consistent on the server render if JS turned off

**Screenshots**
## Correct 
![image](https://user-images.githubusercontent.com/7791726/54225748-41504780-44f4-11e9-8a47-3c4a4901a1bb.png)

## Incorrect
![image](https://user-images.githubusercontent.com/7791726/54225733-3990a300-44f4-11e9-8cf6-a01b6bfc95c3.png)

**Additional context**
The `<style>` tag seems to be consistent between each reload just the font-face that fails. This could be caused by the font-face being set to optional. 

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
To be clear - is "Disable Cache" checked in DevTools?

![Screen Shot 2019-03-13 at 08 51 47](https://user-images.githubusercontent.com/5111927/54265455-443b4e80-456d-11e9-92ad-c6e7b657fd42.png)

**Comment by pjlee11** [comment]
@dr3 made the above point yesterday, I didn't have it unticked ... DERP 

Closed, can't reproduce
