### ISSUE TITLE
Fresh package-lock gives brotli fallback warning

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1407]
**Describe the bug**
On a fresh install of the `package-lock.json` there is the following brotli warning `warning: couldn't find native brotli support in zlib library. trying to fall back to iltorb.` 

**To Reproduce**

1. In simorgh run: `rm -rf node_modules package-lock.json`
2. `npm install`
3. `npm run build`
4. See brotli warning

**Expected behavior**
Ideally, we should not fallback and should use brotli as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/54227020-eb30d380-44f6-11e9-8011-bbc1cc8c9f28.png)

**Additional context**
This has not yet been seen as we often `npm install` which will use the lock file and for deploymentwe use `npm ci` which explicitly uses `package-lock.json` 

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by sareh** [comment]
This warning appears specifically when updating from 
`    "brotli-webpack-plugin": "^1.0.0",`
to 
`    "brotli-webpack-plugin": "^1.1.0",`

**Comment by pjlee11** [comment]
As this is just a console warning we should double check if it happens on CI as well as latest. Also we should check if the bundles are still zipping the same as the warning isn't saying that brotli is broken just that there is not a native support

**Comment by g-wozniak** [comment]
Hello, any news on this? :)

**Comment by g-wozniak** [comment]
If you have `console.log` or something like this in your `webpack.js` file then this warning may pop.

**Comment by jamesbhobbs** [comment]
@g-wozniak thanks for the tip, we'll look into it.

**Comment by FK78** [comment]
![image](https://user-images.githubusercontent.com/34196381/69157355-b7259d80-0adc-11ea-8184-d129addeed6f.png)

Warning does not show up.
