### ISSUE TITLE
Refactor to eliminate duplication on code climate

### ISSUE THREAD

**Issue by PaulChinkwende** [bbc/simorgh#141]
**Is your feature request related to a problem? Please describe.**
We need to refactor some of the code for our components in order to fix code climate errors created by https://github.com/bbc/simorgh/pull/140
issues: 
https://codeclimate.com/github/bbc/simorgh/pull/140
**Describe the solution you'd like**
Code climate to run without finding issues.

**Additional context**

**Comment by jtart** [comment]
We can close this issue. The codebase will be undergoing fairly major changes over the coming weeks, which could implicitly address this.
