### ISSUE TITLE
Manifest.json 500 error in dev server mode

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1414]
**Describe the bug**
When we try to pull in http://localhost:7080/news/articles/manifest.json

...we get a 500 error (technically should be 404 as the file doesn't exist).

Best fix would be to make the manifest exist so the dev env doesn't have a worrying error!

**To Reproduce**

1. Go to `latest` branch
2. `npm run dev`
3. Visit http://localhost:7080/news/articles/c0g992jmmkko
4. See error in console

**Expected behavior**
No errors in console

**Screenshots**

![Screen Shot 2019-03-14 at 09 09 35](https://user-images.githubusercontent.com/5111927/54344700-55ea2800-4639-11e9-84c3-8ea58ecaff91.png)

**Additional context**
Problem goes away when running `npm run build`, so affects dev environment only.

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by jamesbhobbs** [comment]
The engineer should 1. be mildly alarmed 2. search github issues and see it's not really a problem by finding this.
