### ISSUE TITLE
Optimisation: stop minifying the `server.js`

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1415]
**Is your feature request related to a problem? Please describe.**
Running `npm run build` produces `build/server.js` and `build/server.js.map`.

Minifying the server and producing a map file for it slows down the build unnecessarily. We don't need to minify the server.js file as it's not being downloaded to peoples' browsers, and we certainly don't need a map file to debug it.

**Describe the solution you'd like**
A PR which tweaks the `webpack.server.config.js` to stop minifying its contents.

**Describe alternatives you've considered**
Leaving as-is. Not the end of the world.

**Testing notes**
Regression test.

Dev insight: Regression test only.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by thekp** [comment]
https://github.com/serverless-heaven/serverless-webpack/issues/345#issuecomment-372112607

seems like you can stop minifying server.js by adding to `webpack.server.config.js`:
```
    optimization: {
      // We no not want to minimize our code.
      minimize: false,
    },
```
