### ISSUE TITLE
Audit of npm scripts

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1418]
**Is your feature request related to a problem? Please describe.**
In simorgh there is currently 44 npm scripts, these can be used in one of multiple of the following:
- local dev
- makefile
- jenkins (simorgh)
- travis
- husky checks
- jenkins (infrastructure)
- spartacus (in the future)

**Describe the solution you'd like**
~We should document the purpose of each script for clarity.~ 
Simplify the scripts and naming them better so that they are self-explanatory so that we do not need to maintain documentation for scripts

**Describe alternatives you've considered**
~We could prioritise which scripts to document first rather than doing all 44 in one go.~

**Testing notes**
All the npm scripts available in `package.json` should run fine on CI and locally.

Dev insight: This will be documentation so no manual testing. However, a tester should be able to read through the documentation and understand each 

**Additional context**
I raised this after getting frustrated with `test:lighthouse` and `test:lighthouse:ci`
https://github.com/bbc/simorgh/blob/latest/package.json

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
The main thing we should do is vastly reduce the number of scripts, they shouldn't be so numerous that we have to document them.
