### ISSUE TITLE
Moving to lighthouse@4.2.1 breaks our lighthouse testing

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1419]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/bbc/simorgh/issues/1408. When moving to `lighthouse@4.2.1` (or `lighthouse-ci@1.4.1` which pulls in `lighthouse@4.2.1`) our lighthouse tests fail. 

**Describe the solution you'd like**
We should debug why our lighthouse scripts fail when using version `4.2.1` 

**Describe alternatives you've considered**
Rather than defining our own `scripts/` to run lighthouse could we use `lighthouse-cli`? 

**Testing notes**
[Tester to complete]

Dev insight: Lighthouse should work, `npm run test:lighthouse:ci`

**Additional context**
We currently pin `lighthouse-ci` to version `1.3.1`, which was done in https://github.com/bbc/simorgh/pull/1412

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by DemonusPC** [comment]
Irrelevant as of: #1691
