### ISSUE TITLE
Unlock Cypress Versioning (Locked to v3.1.5)

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1426]
**Is your feature request related to a problem? Please describe.**
Cypress `v3.2.0` has currently got several open issues that cause our tests to fail on `Test`.

**Describe the solution you'd like**
We have locked the current Cypress version to `v3.1.5` as `v3.2.0` currently doesn't work on Test. We should wait for the following issues to be fixed/closed and then unlock Cypress versioning.

- [Issue 1](https://github.com/cypress-io/cypress/issues/3728)
- [Issue 2](https://github.com/cypress-io/cypress/issues/3729)
- [Issue 3](https://github.com/cypress-io/cypress/issues/3717)

We need to revert https://github.com/bbc/simorgh/pull/1425 and https://github.com/bbc/simorgh-infrastructure/pull/338

**Comment by jamesbhobbs** [comment]
It's no longer locked to this version so there is no issue (it is up to date). But I think the reason we also don't want to unlock it in general is to keep it the same between here and jenkins version.
