### ISSUE TITLE
Fix Live cypress errors

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1433]
**Describe the bug**
There are live cypress test errors due to moving data to `bbc.com`

**To Reproduce**

1. Run the live cypress tests

**Expected behavior**
They run what they can, and pass

**Screenshots**
```
routingSpec.js

1) Routing tests accepts different service params:

     CypressError: cy.visit() failed trying to load:

https://simorgh.api.bbci.co.uk/news/articles/c85pqyj5m2ko

The response we received from your web server was:

  > 404: Not Found
```
```
Running: persianBodySpec.js... 

1) Article Body Tests "before all" hook for "should render an H1, which contains/displays a styled headline":

   CypressError: cy.visit() failed trying to load:

https://simorgh.api.bbci.co.uk/persian/articles/c5ml5n7w4m3o

The response we received from your web server was:

  > 502: Bad Gateway

```

**Additional context**
The first error is because the asset used in `routingSpec.js` wasnt made to be env dynamic and is trying to use test assets on live

The second error is because persian isnt routed for data via bbc.com/articles/*.json

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
So is the first error blocked on #1434?

And the second error we've decided IRL that we'll prevent running Persian tests on Live (as we won't have Persian for v1 - and having to enable Persian on Live requires STM changes etc).
