### ISSUE TITLE
Stop serving dev routes on production application.

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1435]
**Is your feature request related to a problem? Please describe.**
When we are running in production we should stop serving dev routes like `'/ckns_policy/*'`, static assets and fixture data

**Describe the solution you'd like**
Do a check, such as `process.env.NODE_ENV === 'development'` to prevent these express routes being used in production.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Untested potential solution: 

```
// production routes here
server
  .get(articleRegexPath, (req, res) => {
    ...
  });

// dev only routes here
if (process.env.NODE_ENV === 'development') {
  server
    .get('/ckns_policy/*', (req, res) => {
      res.sendStatus(200);
    });
}
```

**Comment by sareh** [comment]
Closed as fixed.
