### ISSUE TITLE
Get Persian translations for cookie banner

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1438]
**Is your feature request related to a problem? Please describe.**
We need translations for our cookie banner

**Describe the solution you'd like**
Update `src/app/lib/config/services/persian.js` with the correct translations

With the local application running, visiting localhost:7080/persian/articles/c0000000000o a non-existant Persian article, should show the 404 page with the right translations. 

To test the 500 use-case, you can load a valid Persian page first http://localhost:7080/persian/articles/cwv2xv848j5o & then in the network tab block the json request & refresh - that should force a 500 error, so you can see the correct translations. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Testing as mentioned above should be sufficient. 

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Closed as fixed in https://github.com/bbc/simorgh/pull/1888
