### ISSUE TITLE
iOS 7 text takes a long, long time to display

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1443]
**Describe the bug**
When visiting an article on an iOS7 device, the headline & body text does not render for a _long_ time (~30 seconds). I suspect this is something to do with our use of `display: optional`...?

**To Reproduce**
Steps to reproduce the behaviour:

1. On an iOS 7 device...
2. Visit https://bbc.com/news/articles/cxvxrj9yvppo
3. Observe that no text appears
4. Wait a while
5. Eventually the text loads (or is it a fallback font? TBC)

**Expected behaviour**
Text should render very quickly (Reith or non-Reith).

**Screenshots**
TBC

**Additional context**
Our aim is to render a page in under 2 seconds. This is a key part of that aim!

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
Cannot reproduce on Browserstack (iPhone 5S, iOS7, Safari browser).

Current usage of iOS7 is ~0.09%.

@jamesbrumpton would you mind checking this on an iOS7 device and seeing if it's still an issue?

**Comment by sareh** [comment]
Closed as cannot duplicate.
