### ISSUE TITLE
JS Bundle broken on IE 9-11

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1444]
**Describe the bug**
An error is logged, and the bundle doesnt run on IE

**To Reproduce**

1. Go to 'article in IE 9 - 11
2. See errors 

**Expected behavior**
It doesnt error

**Screenshots**
![image](https://user-images.githubusercontent.com/11341355/54682122-f8a51980-4b05-11e9-9751-c64188d9be4d.png)

![image](https://user-images.githubusercontent.com/11341355/54682200-28ecb800-4b06-11e9-85cf-816429a34cfe.png)

**Desktop (please complete the following information):**

- OS: windows 7 and 10, probably 8 too
- Browser IE
- Version 9-11

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by pjlee11** [comment]
Even if we set `"ie >= 9",` in `.babelrc` both `Set` and `Map` are not polyfilled out the box. 
Source: https://github.com/babel/babel/issues/7335

There are suggestions to use `core-js/es6/set` or `@babel/polyfill` or `@babel/plugin-transform-runtime` or `es6/set` ...

**Comment by pjlee11** [comment]
Trying `core-js`, just installing the package causes the build command to output `With `useBuiltIns` option, required direct setting of `corejs` option` then error with `Error: Can't resolve 'core-js/modules/es6.array.find'`
:x:

Trying `@babel/polyfill` with the knowledge that it's a largest package. Changes the application bundle sizes from 356KB to 438KB and doesn't fix the problem but open a second one where the server renders fine but the client fails on 
`SCRIPT5007: Unable to get property 'getRandomValues' of undefined or null reference`
:x: 

NB: We currently already install `@babel/polyfill` but don't seem to directly use it anywhere in the bundles, we should probably have an issue to review why we added it as a dependency in the first place.

**Comment by pjlee11** [comment]
Further material - https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by pjlee11** [comment]
I believe the Errors when installing `core-js` were due to installing version 3.0.0 when babel/polyfill was using version 2.6.5. I've now installed `core-js@2.6.5` successfully

**Comment by ChrisBAshton** [comment]
> NB: We currently already install @babel/polyfill but don't seem to directly use it anywhere in the bundles, we should probably have an issue to review why we added it as a dependency in the first place.

This is used in conjunction with `useBuiltIns: "usage"`. (Babel uses modules from`@babel/polyfill` to automatically polyfill only the code that is used).
