### ISSUE TITLE
Re-enable browser security in Cypress

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1452]
**Describe the bug**
In https://github.com/bbc/simorgh/pull/1439 we disabled the `chromeWebSecurity` feature in Cypress. This was needed because the tests simulate clicking on links in the consent banners, which cause the browser to navigate to a different superdomain.

Cypress docs recommend only doing this as a last resort. It means our e2e tests are no longer sensitive to legitimate security-related bugs that may get introduced later (e.g. CORS violations). It also means we can never run our tests on browsers that do not support disabling web security (see https://docs.cypress.io/guides/guides/web-security.html#Disabling-Web-Security).

For consideration:
- One option suggested by @dr3 was to make the links in the consent banners relative so that they don't require navigating to a different origin (and possibly then get Cypress to stub them)
- Other suggested Cypress workarounds are given here: https://docs.cypress.io/guides/guides/web-security.html#External-Navigation
- If all else fails we should only disable security for the tests that need it doing (see https://docs.cypress.io/guides/references/configuration.html#Cypress-config)

**To Reproduce**
N/A

**Expected behavior**
Browser security should be re-enabled in the Cypress tests for the reasons described above.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by jamesbhobbs** [comment]
Relates to https://github.com/bbc/simorgh/issues/2046
