### ISSUE TITLE
Footer should have 56px padding to distance itself from content

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1453]
**Is your feature request related to a problem? Please describe.**
Designs have a 56px gap between Footer and the last paragraph of the page.

**Describe the solution you'd like**
Update [the Footer container](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Footer/index.jsx) to have 56px of space between the footer and the content above it.

PR should have screenshots showing before & after.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshot tests need updating.

**Additional context**
N/a

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
This needs to be moved to psammead @ChrisBAshton
