### ISSUE TITLE
iPhone 6 Plus has "margin" to the right of article body text

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1454]
**Describe the bug**
Visiting an article on iPhone 6 Plus, it's at just the right size to get the "tablet" view and subsequently looks a bit weird. Have confirmed with Natalie from UX that we won't want a gutter of space here - so we should probably tweak the breakpoint at which that happens.

**To Reproduce**

1. On an iPhone 6 Plus
2. Visit any Simorgh article
3. See the space to the right of the body text.

**Expected behavior**
Body text should flow right to the edge of the screen (apart from 8-16px of 'true guttering').

**Screenshots**

<img width="433" alt="Screen Shot 2019-03-21 at 11 41 45" src="https://user-images.githubusercontent.com/5111927/54750040-569d3400-4bce-11e9-827e-41e8487ec805.png">

**Smartphone (please complete the following information):**

- Device: iPhone 6 Plus
- OS: 12
- Browser - Safari

**Additional context**
N/A

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by staylos92** [comment]
Also seeing this on:

Device : OnePlus 5
OS: Android 9
Browser: Chrome v72

**Comment by dr3** [comment]
This is not a bug, this is an unliked feature. If we want this to change we need to work with UX to redefine the width in which the grid changes (which I believe is gel)

**Comment by ChrisBAshton** [comment]
Blocked on getting a revised breakpoint from UX. Hoping to sit with them next week.

**Comment by ChrisBAshton** [comment]
Sounds like we want to apply the guttering feature to groups 3 and above, rather than groups 2 and above:

https://github.com/bbc/simorgh/issues/1369#issuecomment-476157389

Will check with UX.

**Comment by ChrisBAshton** [comment]
Confirmed - it _should_ start from group 3, not from group 2.

We're currently applying this margin to group 1 only, but should apply it to groups 1 and 2.

**Comment by ChrisBAshton** [comment]
Actually blocked on Natalie confirming on Wednesday - Ngan Thi not 100% sure and doesn't want us to do the work and then have to revert it.
