### ISSUE TITLE
Reith fonts do not load on Android 4.x or Opera Mini

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1456]
**Describe the bug**
The Reith font doesn't load on Opera mini, nor on Android 4.x (Galaxy Note 3, Nexus 4, Kindle Fire HDX 7 - tested via BrowserStack).

**To Reproduce**

1. Visit an article in any of the affected browsers
2. See that there is no Reith font

**Expected behavior**
The Reith font should appear, at the very least on a refresh of the page. (The `font-display: optional` suggests that the page should be allowed to render non-Reith font if it's quicker for performance, but the fonts should download in the background and subsequent page loads should display the font).

**Screenshots**
TBC

**Additional context**
Could be related to #1443.

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by jamesbhobbs** [comment]
Example resolution is here: https://css-tricks.com/font-display-masses/#article-header-id-3
