### ISSUE TITLE
Reevaluate AMP EU Countries

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1465]
**Is your feature request related to a problem? Please describe.**
We have a list of EU countries in `src/app/containers/ConsentBanner/index.amp.jsx`, can we extract these into a single "BBC list"? Are these even all of the countries?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
@jamesdonoh ^^ :)

**Comment by jamesdonoh** [comment]
Our current list (added in https://github.com/bbc/simorgh/pull/1442) deviates from the list used by Orbit to identify EU users (left is AlephAMP/Articles.AMP, right is Orbit):
```
at	at
be	be
bg	bg
cy	cy
cz	cz
de	de
dk	dk
ee	ee
es	es
      >	eu
fi	fi
fr	fr
gb	gb
gr	gr
hr	hr
hu	hu
ie	ie
is    <
it	it
li    <
lt	lt
lu	lu
lv	lv
mt	mt
nl	nl
no    <
pl	pl
pt	pt
ro	ro
se	se
si	si
sl    |	sk
```

**Comment by jamesdonoh** [comment]
Here is the list which I _think_ is used to generate the x-ip-is-eu-combined header: https://repo.dev.bbc.co.uk/uk/co/bbc/geoip/trunk/src/main/java/uk/co/bbc/geoip/transforms/IsEuCombinedTransformer.java

**Comment by dr3** [comment]
There is also the amp-geo preset https://github.com/ampproject/amphtml/blob/master/extensions/amp-geo/0.1/amp-geo-presets.js which can be used in AMP (whether we want to is a different question)

**Comment by dr3** [comment]
| BBC Orbit | Google AMP | Country | Comment |
|------|-------|-----------|-----------|
| at   |  at   |  Austria  |  |
| ❌   |  ax   |  Aland Islands  |  |
| be   |  be   |  Belgium  |  |
| bg   |  bg   |  Bulgaria   |  |
| ❌   |  bl   |  St Barthelemy  |  |
| ❌   |  ch   |  Switzerland  |  |
| cy   |  cy   |  Cyprus   |  |
| cz   |  cz   |  Czech Republic   |  |
| de   |  de   |  Germany  |  |
| dk   |  dk   |  Denmark  |  |
| ❌   |  ea   |  Ceuta & Melilla  |  |
| ee   |  ee   |  Estonia  |  |
| es   |  es   |  Spain  |  |
| ❌   |  ez   |  Eurozone   |  |
| fi   |  fi   |  Finland  |  |
| fr   |  fr   |  France   |  |
| gb   |  gb   |  United Kingdom   |  |
| ❌   |  gf   |  French Guiana  |  |
| gg   |  gg   |  Guernsey   |  |
| gi   |  gi   |  Gibraltar  |  |
| ❌   |  gp   |  Guadeloupe   |  |
| gr   |  gr   |  Greece   |  |
| hr   |  hr   |  Croatia  |  |
| hu   |  hu   |  Hungary  |  |
| ❌   |  ic   |  Canary Islands   |  |
| ie   |  ie   |  Ireland  |  |
| im   |  ❌   |  Isle of Man   | The Isle of Man holds neither membership nor associate membership of the European Union, and lies outside the European Economic Area (EEA) |
| ❌   |  is   |  Iceland  |  |
| it   |  it   |  Italy  |  |
| je   |  je   |  Jersy  |  |
| ❌   |  li   |  Liechtenstein  |  |
| lt   |  lt   |  Lithuania  |  |
| lu   |  lu   |  Luxembourg   |  |
| lv   |  lv   |  Latvia   |  |
| ❌   |  mf   |  St Martin  |  |
| ❌   |  mq   |  Martinique   |  |
| mt   |  mt   |  Malta  |  |
| ❌   |  nc   |  New Caledonia  |  |
| nl   |  nl   |  Netherlands  |  |
| ❌   |  no   |  Norway   |  |
| ❌   |  pf   |  French Polynesia   |  |
| pl   |  pl   |  Poland   |  |
| ❌   |  pm   |  St Pierre & Miquelon   |  |
| pt   |  pt   |  Portugal   |  |
| ❌   |  re   |  Reunion  |  |
| ro   |  ro   |  Romania  |  |
| se   |  se   |  Sweden   |  |
| si   |  si   |  Slovenia   |  |
| ❌   |  sj   |  Svalbard & Jan Mayen Islands   |  |
| sk   |  sk   |  Slovakia   |  |
| uk   |  ❌   |  United Kingdom   | Duplicate of `gb` |
| ❌   |  tf   |  French Southern Territories  |  |
| ❌   |  va   |  Vatican City   |  |
| ❌   |  wf   |  Wallis & Futuna Islands  |  |
| ❌   |  yt   |  Mayotte  |  |

**Comment by dr3** [comment]
@jimjohnsonrollings I have listed above the a comparison of BBC Orbits country code list for the EU and Googles list for the EEA. 

I propose we use the 'Google AMP' set above, leaving `uk` and `im` out.

Are there any countries above, which are in 'Google AMP', but not `BBC Orbit` which we should not show the cookie banner to?

It's likely some of those countries fell into other countries in our logic or we didnt show them due to being in the EEA but not the EU.

**Comment by dr3** [comment]
From Jim
>Countries:
UK banners should include Channel Islands and Isle of Man
Non-UK banner should include the rest of the EEA (30 states)

**Comment by sareh** [comment]
As part of this issue to move the amp-geo list to Psammead, https://github.com/bbc/psammead/pull/1367 we have added all the missing country codes in the list here: https://github.com/bbc/simorgh/issues/1465#issuecomment-476182335 apart from Switzerland and Eurozone.

**Comment by jamesbhobbs** [comment]
Done now that amp geo is merged
