### ISSUE TITLE
Write ADR for Polyfilling Policy

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1478]
**Is your feature request related to a problem? Please describe.**
In https://github.com/bbc/simorgh/pull/1468 we added polyfills for IE11,10&9. 

**Describe the solution you'd like**
Write an ADR explaining what they're for, what they allow and what restrictions we have now we used them. (e.g. crypto has been polyfilled so its now not secure)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
I believe our approach to polyfilling is clearly defined in the config file, writing an ADR seems superfluous except to relate this to our customer usage that invariably changes over time and therefore would need to be updated more often than an ADR should
