### ISSUE TITLE
Place `Timestamp` at top of doc if no `Headline` provided

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1483]
**Is your feature request related to a problem? Please describe.**
When no `Headline` is provided, we should put the `Timestamp` as the first thing in the body copy (after the off-screen `h1` in #1482).

**Describe the solution you'd like**
A PR that implements the expected logic

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Should have unit tests that cover this.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked on #1485.

**Comment by dr3** [comment]
I think this is covered by https://github.com/bbc/simorgh/issues/1485, is this issue needed?
