### ISSUE TITLE
Place `Timestamp` below `Image/Video` if these immediately follow `Headline`

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1484]
**Is your feature request related to a problem? Please describe.**
If the article data contains a headline, & it is immediately followed by an image or video block, the Timestamp Container should be placed after the Headline & Image/Video components.

What should happen if _two_ Image/Video blocks follow the Headline? TBC

**Describe the solution you'd like**
PR.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Cypress tests required.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked on #1485.

**Comment by jimjohnsonrollings** [comment]
Duplicate
