### ISSUE TITLE
Investigate using Browserstack API to automate tests in older browsers

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1486]
**Is your feature request related to a problem? Please describe.**
A bug (#1470) was only visible in older browsers and was caused by those browsers not supporting the 'options' parameter of `toLocaleDateString()`.

We could in theory write tests which reset `toLocaleDateString()` to a custom implementation to 'emulate' older browsers and test our fix, but our fix in #1481 removes that API call entirely and it doesn't feel write to mock methods we're not even using just for the sake of catching a regression should we re-introduce that code in future.

Ideally we would simply run our automated tests _inside an older browser_ e.g. by using the Browserstack API. 

**Describe the solution you'd like**
A spike PR which adds Browserstack API automated testing against at least one of our Cypress suites.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: N/A

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Closed since we're no longer using `toLocaleDateString`.
