### ISSUE TITLE
Use psammead-footer 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1492]
**Is your feature request related to a problem? Please describe.**
In the PR https://github.com/bbc/simorgh/pull/1491 we created a Footer component directly in the footer container due to time constraints for launch. Following the creation of the [psammead-footer](https://github.com/bbc/psammead/issues/395) we should start using it and remove the `styled.footer` from the footer container. 

**Describe the solution you'd like**
import and use `@bbc/psammead-footer` and remove the `styled.footer`.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshots should remain the same and visual regression will be needed. 

**Additional context**
n/a

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
blocked on https://github.com/bbc/psammead/issues/395

**Comment by sareh** [comment]
Closed since we're not creating a psammead-footer, since it now we are using the plain `footer` element with no associated styles.
