### ISSUE TITLE
Turn Persian E2Es back on

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1496]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/pull/1420 the Persian E2Es are skipped on test and live. Once we have a Persian error page in Mozart release to live we should turn the Persian E2Es back on. 

**Describe the solution you'd like**
Turn the Persian E2Es back on.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: E2Es should run on Test and Live for Persian after this change. 

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Blocked on having an error page in Mozart for Persian. https://github.com/bbc/simorgh-infrastructure/issues/347
