### ISSUE TITLE
Document how to run Env Cypress tests locally

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1500]
**Is your feature request related to a problem? Please describe.**
We have commands to run cypress tests against the TEST and LIVE env's (`npm run test:e2e:live_env` and `npm run test:e2e:test_env`). However, for these to pass we have to change the `baseUrl` in `cypress/support/config.js` to be `.co.uk` for TEST and LIVE because our machine's are in the UK and will get redirected to `.com` and throw a domain error.

**Describe the solution you'd like**
Document the above nicely in a read me.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
Related to and perhaps part of https://github.com/bbc/simorgh/issues/1418
