### ISSUE TITLE
Simorgh requires work to use 0.3.0 Gel Foundations

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1502]
**Describe the bug**
The 0.3.0 of [gel-foundations](https://github.com/bbc/psammead/tree/latest/packages/utilities/gel-foundations) (use of `rem` over `em` for breakpoints), if blindly pulled into Simorgh, breaks our endpoint of 1008px.

| < 1008px (as expected) | 1107px (still in the <1008px view, NOT expected) |
|-----|------|
|![1003px](https://user-images.githubusercontent.com/5111927/54920955-7ac58180-4efc-11e9-9558-8356c7176fc0.png)|![1107px](https://user-images.githubusercontent.com/5111927/54920969-82852600-4efc-11e9-8a44-69f4a8426923.png)|

| 1108px (completely broken) | 1109px (the view we expect at 1008px!) |
|-----|------|
|![1108px](https://user-images.githubusercontent.com/5111927/54920987-8c0e8e00-4efc-11e9-9ca6-98bf383ed76d.png)|![1109px](https://user-images.githubusercontent.com/5111927/54920999-916bd880-4efc-11e9-9f94-8f86bfd9c998.png)|

**To Reproduce**

1. Import latest gel-foundations into Simorgh
2. See article

**Expected behavior**
Breakpoints should work as before (i.e. at 1008px, new layout)

**Screenshots**
See above.

**Desktop (please complete the following information):**
Chrome, mac OS.

**Smartphone (please complete the following information):**
N/A

**Additional context**
We think we need to update `layoutGrid.js` to use gel-foundations in a new way. (In other words, this is a breaking change).

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by sareh** [comment]
Closed as fixed.
