### ISSUE TITLE
Create ContentWrapper grid inside GridWrapper

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1508]
**Is your feature request related to a problem? Please describe.**
Our image / caption / grid combination has to follow some complex rules, defined here: https://github.com/bbc/simorgh/issues/1369#issuecomment-477551812

This is impossible to do with just a top-level grid. Instead, we will need a ContentWrapper grid _inside_ this topmost grid (called GridWrapper for the purposes of this issue).

The GridWrapper is responsible for defining the "outer margins" and how wide a slot of content should accommodate inside that.

The ContentWrapper - inside GridWrapper - defines the grid inside the main content area, and allows us to do things such as taking up a proportion of columns inside the main content.

**Describe the solution you'd like**
A PR which adds a GridWrapper to handle the "internal" 6 columns, leaving ContentWrapper to handle just the outer margin columns from Group 4 and 5. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: The PR to add the new ContentWrapper should include Storybook examples for the GridLayout with a GridWrapper, Grid Item, ContentWrapper and example items inside.  Note: the actual items used can be simply a plain box with background colour. 

The exports from here should have Stories added to Storybook to show example usage https://github.com/bbc/simorgh/blob/latest/src/app/lib/styledGrid.js

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
https://codepen.io/phil-lee/pen/JzQgdx

**Comment by pjlee11** [comment]
Personally, I think the solution needs to be more flexible than the one proposed otherwise _every_ component will need to have nested grids. I think we need to maintain the current `layoutGridWrapper` and produce a new `contentGridWrapper` that is only used when a nested grid is required, EG: for the image component.

**Comment by ChrisBAshton** [comment]
Hmm shouldn't need to do that. See https://codepen.io/anon/pen/OGLLMj

**Comment by pjlee11** [comment]
Ahhh okay I see what you are suggesting. However, this would stop us from having full bleed components in the future which is a requirement we should keep in mind.

**Comment by ChrisBAshton** [comment]
Have updated the codepen :) you're right, that was tricky! Think I've found a way though... https://codepen.io/anon/pen/OGLLMj

**Comment by pjlee11** [comment]
Minus margin's are bad practice IMO. I've also just come to the conclusion that this could be solved by just nesting the exact same grid in a "full-bleed" item. 

See https://codepen.io/phil-lee/pen/yrBLYy

Therefore we have the following: 
```
<Grid>
  <GridItem />
  <GridItemFullBleed && Grid>
    <GridItem /> // this is nested but has the same grid knowledge as any other <GridItem>
  </GridItemFullBleed && Grid>
  <GridItem />
</Grid>
```

This works because `GridItemFullBleed && Grid` basically means treat this as an empty grid item and redefine the parent grid again for children of this element

**Comment by pjlee11** [comment]
Example of nesting the same grid inside a full bleed grid-item
https://codepen.io/phil-lee/pen/yrBLYy

**Comment by sareh** [comment]
This is an example of when we want the caption width and image width to differ. 

**A small image with a long caption**

<img width="378" alt="Screen Shot of small image and long caption" src="https://user-images.githubusercontent.com/3028997/56203211-b0addf80-603c-11e9-808f-a51c2d06442a.png"> 

https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c596fa88971d341fae3fd53

Here are examples of how it varies at a particular breakpoint. For the full breakdown of examples, please see requirements: https://github.com/bbc/simorgh/issues/1369#issuecomment-477551812

<img width="604" alt="Screen Shot 2019-04-16 at 11 46 22" src="https://user-images.githubusercontent.com/3028997/56203521-53665e00-603d-11e9-8f08-bad73ec23dbf.png">

<img width="604" alt="Screen Shot 2019-04-16 at 11 46 07" src="https://user-images.githubusercontent.com/3028997/56203522-53665e00-603d-11e9-91fb-c6f8a8b43aa9.png">
<img width="603" alt="Screen Shot 2019-04-16 at 11 45 52" src="https://user-images.githubusercontent.com/3028997/56203523-53fef480-603d-11e9-9ad4-280a2f5ad732.png">
