### ISSUE TITLE
Absolute datetime should show time

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1514]
**Describe the bug**
The absolute datetime does not show the time. 

**To Reproduce**

1. Go to https://www.test.bbc.co.uk/news/articles/c5jje4ejkqvo
2. View timestamps - note that the absolute dates should also show the time. They currently do not.
<img width="206" alt="Screen Shot 2019-03-29 at 14 41 18" src="https://user-images.githubusercontent.com/3028997/55240409-c051b980-5230-11e9-8ccf-4ea89f9fa5b0.png">

e.g. 27 March 2019, 12:34

**Expected behavior**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
The first or the second timestamp, @sareh ? They're both absolute.

**Comment by sareh** [comment]
@ChrisBAshton Both timestamps. Whenever they've changed to be updated more than 10 hours ago.

**Comment by ChrisBAshton** [comment]
Duplicate of #1280 and #1521
