### ISSUE TITLE
Updated timestamp doesnt show outside UTC when updated <1 min ago

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1515]
**Describe the bug**
When you look at an article published <1 min ago in the US it doesnt show how long ago it was updated

**To Reproduce**

1. Go to an article that was just updated outside UTC
2. See error

**Expected behavior**
It behaves as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/11341355/55241659-728a8080-5233-11e9-84a9-bd4110c9e395.png)

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
May be fixed by #1522...?

**Comment by jamesbhobbs** [comment]
@dr3 please recheck this

**Comment by dr3** [comment]
Can not replicate now, win
