### ISSUE TITLE
Timestamp: display 1 or 2 depending on lastPublish date

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1521]
**Is your feature request related to a problem? Please describe.**

Currently, we always display two timestamps if `lastPublished` is different to `firstPublished`.  But we want the behaviour to be more nuanced than that - otherwise the output can look a bit odd, e.g. `29 March 2019, Updated 29 March 2019`.

Pseudocode:

```
if (firstPublished === lastPublished)
  || ( (firstPublished and lastPublished are on same day) && (lastPublished > 24hrs ago) ):
    displayOnlyOneTimestamp() // with no "Updated" prefix...

else
    displayTwoTimestamps() // the latter with "Updated" prefix
```

**Describe the solution you'd like**
A PR, unit tests, probably Cypress integration tests too if we have time.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: See above.

**Additional context**
Probably worth branching off https://github.com/bbc/simorgh/pull/1519.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by twinlensreflex** [comment]
All the possible scenarios that need to be tested (for my own reference)

| lastPublished | firstPublished | published timestamp | updated timestamp | done? |
|---------------|----------------|---------------|----------------|----------------|
| === firstPublished | today < 10hrs | relative | none | ✅
| === firstPublished | today > 10hrs | date & time | none |✅
| === firstPublished | before today | date | none | ✅
| today < 10hrs | today < 10hrs | date | relative | ✅
| today > 10hrs | today > 10hrs | date & time | date & time |✅
| before today | same day as lastPublished | date | none |✅


| before today | before today  | date | date | ? ?  ? ? ?
