### ISSUE TITLE
If no Headline block, insert Headline as first block & use `seoHeadline` as value

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1524]
**Is your feature request related to a problem? Please describe.**
It is possible to publish an article without a Headline block, but it is unacceptable to render a page without a `<h1>`, and this must be visible.

Having consulted with Product, UX, A11y and Devs, we have agreed in this case to use the `seoHeadline` (which _will_ always exist) and render this as the `h1`. We discussed making this invisible for sighted users but decided the difference in UX isn't right, and that we should render the h1 visually as normal.

**Describe the solution you'd like**
A PR which builds upon #1485 to:

* check if a Headline block exists. If it _doesn't_:
  * insert a Headline block at the beginning of the blocks array
  * use the `seoHeadline` value as the Headline content

NB, in #1493 we fixed #1483 ("Place `Timestamp` at top of doc if no `Headline` provided") but this will now be superseded by "Insert Headline if no headline", so we should remove this rule.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will need unit tests, perhaps Cypress tests too.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Blocked until this is an actual problem - @jimjohnsonrollings

**Comment by jamesbhobbs** [comment]
@jimjohnsonrollings @sareh do you mean this is low priority according to product? Because I don't see how something that's easily mocked can be blocked.

**Comment by jimjohnsonrollings** [comment]
Fair enough - yes, low priority because it's not a problem as editorial are instructing their users to put headlines first at the moment.  I don't think we need to urgently cope with it until it starts to be something they do, and in that case I'd like to understand what they are trying to achieve so that we can find a solution that works for that use case rather than make assumptions.
