### ISSUE TITLE
SPIKE: Investigate adding an index route to render home pages

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#1526]
**Is your feature request related to a problem? Please describe.**
We should investigate adding an index route so we can render service home pages e.g. `/news` & `/mundo`

**Describe the solution you'd like**
We should look into generalising `getInitialData` and construct the data URL based on the page type to fetch data from a single `/data` endpoint.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [ ] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Closing issue as spike has been done and https://github.com/bbc/simorgh/pull/1589 should improve the implementation
