### ISSUE TITLE
Travis CI from forked repositories

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1531]
**Describe the bug**
When following guidelines set in [CONTRIBUTING.md](https://github.com/bbc/simorgh/blob/latest/CONTRIBUTING.md#contributing), I get the following error from Travis:
`The command "xvfb-run -a npm run test:prod:travis" exited with 1.`
_https://travis-ci.org/rhell/simorgh/jobs/514624945_

The build does also not report to the [original GitHub PR](https://github.com/bbc/simorgh/pull/1498).

By **not** changing the `README.md` as instructed to do so in the Contributing guidelines, that above error does not appear, and the [Travis CI builds pass](https://travis-ci.org/rhell/simorgh/builds/514627800). However, this is still not reported on the GitHub PR.

**To Reproduce**

1. Fork the Simorgh repository
2. Follow instructions set out in https://github.com/bbc/simorgh/blob/latest/CONTRIBUTING.md#contributing
3. Open a PR
4. Visit https://travis-ci.org and watch your build
4. See build fail, and not report into the Github PR

**Expected behaviour**
When committing to a PR on a forked repository, Travis should not error, and should also report the result back to the original GitHub PR.

https://github.com/bbc/simorgh/blob/latest/CONTRIBUTING.md#run-tests-on-your-fork should be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/7690572/55399442-082f5400-5543-11e9-86aa-46db7576f11d.png)

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by alex-magana** [comment]
The 
`The command "xvfb-run -a npm run test:prod:travis" exited with 1.`
error has been resolved by enabling `Build pushed PRs` in simorgh travis settings.
The build now reports
`The command "./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT" exited with 255.`.
This is a known issue and addition of `CC_TEST_REPORTER_ID ` to travis.yml to enable forks to report results to codeclimate, is pending confirmation.
Leaving this issue open to address the codeclimate issue.

Reference:
https://docs.travis-ci.com/user/environment-variables/
https://docs.codeclimate.com/docs/finding-your-test-coverage-token

Test PR: https://github.com/bbc/simorgh/pull/1562

**Comment by alex-magana** [comment]
Blocked. Requires resolution of Jira ticket RESFRAME-2625.
See https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/architecture-decision-records/2019-02-13-jenkins-github-forks.md for further details.

**Comment by alex-magana** [comment]
I added the `blocked` to allow us to run the Code Climate and Jenkins check, in tandem.

Following the conversation where we concluded that Jenkins may not be apt for running a build from a fork, I'm removing the `blocked` label to allow for this to be merged and so that it can aid exploring the alternative for running Jenkins builds.
