### ISSUE TITLE
302 redirect /news/articles to /news

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1540]
**Is your feature request related to a problem? Please describe.**
/news/articles currently gives a 404 - this is bad practice and unhelpful for SEO

**Describe the solution you'd like**
302 redirect /news/articles to /news

**Describe alternatives you've considered**
* 301 - ruled out as we may later want to:
* Create a page at this route - ruled out for now as we don't have anything to put there

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by chris-hinds** [comment]
This work is now on test.

https://www.test.bbc.co.uk/news/articles now issues a 302 redirect to https://www.test.bbc.co.uk/news

**Comment by jamesbrumpton** [comment]
LGTM

**Comment by jamesbhobbs** [comment]
This is live
