### ISSUE TITLE
Footer top padding doesnt account for ghost wrap

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1542]
**Describe the bug**
The footer has a top margin, which is pushing the ghost wrapper up, causing a white gap

**To Reproduce**

1. Go to any article
2. See error

**Expected behavior**
The padding incs ghost wrap

**Screenshots**
Screenshot replacing ghost with red

![image](https://user-images.githubusercontent.com/11341355/55717460-3d2f2100-59f1-11e9-8ac6-e8b51137f71b.png)

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by sareh** [comment]
Changed to be the core stream since all front-end components that are shared between Articles and Front Pages are to be addressed by Simorgh Core.
