### ISSUE TITLE
Allow simorgh to handle server route matches via react router

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1544]
**Is your feature request related to a problem? Please describe.**
We currently dont allow unknown routes past the express level. we should update [this logic](https://github.com/bbc/simorgh/blob/latest/src/server/index.jsx#L126) to be `/*` and allow all routes to be handled (and rejected) by react router.

We are currently unable to do this as if a user was able to hit an unknown route, [this logic](https://github.com/bbc/simorgh/blob/latest/src/app/routes/loadInitialData/index.js#L11) would throw a 500 as we cant distinquish between a borked routing or an actual application error

**Why do we need this?**
Without this work, every time we add a new route we need to add a new express route which is a copy of the existing one, or duplicate the logic via passing a function here https://github.com/bbc/simorgh/blob/latest/src/server/index.jsx#L126-L140

By doing this, all the logic is handled in react routing within the simorgh application, rather than its express app.

**Describe the solution you'd like**
if a route doesn't match, do your best to serve an error page.

Open up the express route to `/*`, falling back to the `matchRoutes` logic from react router

If user requests a url `/service/(!articles)*`
Serve a error page for that service using that services language

if user requests a url `/unknown*`
serve a news error page with english

**Describe alternatives you've considered**
Just returning a string of text, as really a user should never be able to hit these URLs as Mozart only lets through certain url routes

**Testing notes**
On localhost, when a user hits a route that doesn't exists depending on whether it ends with .amp or `/service/xxxx` error pages should be served accordingly.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Blocking https://github.com/bbc/simorgh/issues/1543

**Comment by chris-hinds** [comment]
@dr3 is this work actually blocking you from moving forward with the WS HomePages? Or can you get away with creating another route in express for the time being?

Going to investigate this more tomorrow but we might look to split the error handling with `matchRoutes` out first and prioritise that over the unified routing. keen to hear your thoughts when you have time.

**Comment by dr3** [comment]
It will be blocking us, perhaps not immediately, but soon.

We could just duplicate the route, but Im reeeeally not a fan of temporarily bodging code because were blocked by another stream. If that happens ide rather just do the work ourselves tbh.

**Comment by jamesbhobbs** [comment]
As part of this lets rename the routes, at the moment the naming is based on the origin of this as an articles application.

**Comment by jamesbhobbs** [comment]
Part of https://github.com/bbc/simorgh/issues/2230
