### ISSUE TITLE
Setup fixture data for the worldservice frontpages

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1545]
**Is your feature request related to a problem? Please describe.**
We need fixture data for the world service frontpages

**Describe the solution you'd like**
Add fixture data, from live CPS via ares to the repo.

We should add fixture for Yoruba, Igbo, Pidgin and Thai.

It should live under `/data/prod/service/frontpage/` however the name of the file/files is unknown. Part of this work is to propose a naming structure.

We should then route the the data so it can be hit on the client. It should expand/be similar to the [articles approach](https://github.com/bbc/simorgh/blob/latest/src/server/index.jsx#L71-L94). We need to decide how we will route the data. We will likely want multiple files, how will the application pick, when in production it wont need to?

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by chris-hinds** [comment]
Example request to Ares for front page data: https://ares-broker.api.bbci.co.uk/api/index/mundo/front_page/desktop/domestic

Should the directory structure for the fixture data follow this exactly? i.e. `/data/prod/mundo/front_page/desktop/domestic`

Is `/desktop/domestic` needed?

There talks about how/where we fetch this data from @pjlee11 might be able to give some more input on this area.

**Comment by dr3** [comment]
>Is /desktop/domestic needed? 

Not for WS afaik, if we use news, that will change

We need to decide what URL we want data to be called from in production, as that will likely influence how we want it locally

**Comment by dr3** [comment]
Closing in favour of https://github.com/bbc/simorgh/issues/1546
