### ISSUE TITLE
Add Article Main to Storybook

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1550]
**Is your feature request related to a problem? Please describe.**
We will have multiple services with multiple languages using ArticleMain. We should add this ArticleMainContainer to Storybook to give visibility of the various configuration in a structured format. 

**Describe the solution you'd like**
Ensure we're using the RTL and knobs for articles in different languages - see this example in Psammead's storybook - https://bbc.github.io/psammead/?path=/story/inlinelink--default

We can make use of Storybook knobs and create an input provider with fixture data, in a similar way to how it is used in Psammead:
```
import React from 'react';
import { storiesOf } from '@storybook/react';
import { withKnobs } from '@storybook/addon-knobs';
import { inputProvider } from '@bbc/psammead-storybook-helpers';
import notes from '../README.md';
import Paragraph from './index';

storiesOf('Paragraph', module)
  .addDecorator(withKnobs)
  .add(
    'default',
    inputProvider(['paragraph'], paragraph => (
      <Paragraph>{paragraph}</Paragraph>
    )),
    { notes },
  );

```

**Testing notes**
[Tester to complete]

Dev insight: Manually checking that Storybook is working as expected. 

**Additional context**
It would be good to discuss with Product and UX prior to starting work on this issue - add comments on this issue below. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
@sareh could you confirm what is meant by `to give visibility of the various configuration` please?

**Comment by sareh** [comment]
@pjlee11 To vary on `service` & `platform` & to show the correct output - e.g. the example of the Persian service should be right-to-left.

**Comment by pjlee11** [comment]
Refined by articles. Leaving label for core pod.
