### ISSUE TITLE
Google doesnt show updated/published time on article

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1554]
**Describe the bug**
When you see an article in google, it doesnt show the published/updated time

**To Reproduce**

1. Google `"Bowen thanked for bowel cancer 'bounce'"`
2. See error

**Expected behavior**
Google reports the time published/updated

**Screenshots**
PAL article with time value, followed by a Simorgh article without it
![image](https://user-images.githubusercontent.com/11341355/55804808-f31f6b80-5ad4-11e9-8b6a-fd402613e889.png)

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by jimjohnsonrollings** [comment]
Do you think this might just be because we haven't finished the timestamp work?

**Comment by dr3** [comment]
> Do you think this might just be because we haven't finished the timestamp work?

I dont think so, _i think_ we were just relying on a `time` tag in the page, but that doesn't appear to be working. AFAIK the pending timestamp work maintains this assumption of logic

**Comment by sareh** [comment]
@dr3 The article you highlighted in the screenshot was the PAL article - `https://www.bbc.com/news/health-47830406`

**Comment by dr3** [comment]
@sareh I was more trying to highlight the absence of a time indicator on the simorgh equivalent article below it

**Comment by jimjohnsonrollings** [comment]
Blocked until we've seen a few more examples once we've finished the timestamp work

**Comment by jimjohnsonrollings** [comment]
Looks good on later article :)
<img width="635" alt="Screen Shot 2019-05-31 at 10 56 49" src="https://user-images.githubusercontent.com/8124899/58698239-ddbb1500-8392-11e9-8087-c7ee783b2ce7.png">
<img width="644" alt="Screen Shot 2019-05-31 at 10 57 46" src="https://user-images.githubusercontent.com/8124899/58698333-f9beb680-8392-11e9-88bf-f4a23873e0f1.png">
