### ISSUE TITLE
Configuration workflow using iSite

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#1560]
**Is your feature request related to a problem? Please describe.**
It is generally agreed upon that we should factor out service level configuration from the application code. 

In the past when we have done this we have looked to use iSite as a `cms` for configuration and translations. However this comes with it's own problems when thinking about the current workflow.

Our iSite setup is a bit of mess right now with multiple projects, some duplicate file types, many empty projects/filetypes, currently a pain to setup new forms/filetypes as we then have to duplicate these on the live environment.

**Describe the solution you'd like**
I'd like a new unified project for configuration, translations and maybe feature toggles. (These could be separate projects).

New filetypes and updates should be created once, on the test environment. We should be able to point to test config in the application easily to enable testing of new changes/translations. Once we are happy with these we should be able to `promote` the new data to the live environment.

The Live environment should be `read only` this, way we can ensure the environments are always up-to date and are not out of sync. 

To enable this we should utilise the iSite CLI to create a promotion `job/process` to the data from test to live.

The data from iSite should be stored as easily readable JSON files in S3 similar to how the News Toggles system works.

The benefit of storing this data in S3 means we can swap out iSite in the future for something more suitable.

- [X] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
@hindsc52 Can you break this up into tasks please?
