### ISSUE TITLE
Update Travis & Code Climate slack channel

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1563]
**Is your feature request related to a problem? Please describe.**
Currently travis & Code Climate sends messages to #article-devs

**Describe the solution you'd like**
Update the [secure slack value](https://github.com/bbc/simorgh/blob/latest/.travis.yml#L26) for the new channel `#si_repo-simorgh`

Update Code Climate settings to alert in the same channel. 

**Testing notes**

Dev insight: Check it works on the branch. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh-infrastructure/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
Codeclimate done

**Comment by jamesbhobbs** [comment]
Travis now also done.

CodeClimate is done via the settings in their application
Travis is done via the settings in our slack integration
