### ISSUE TITLE
Reafactor Timestamp container logic

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1565]
**Is your feature request related to a problem? Please describe.**
The current timestamp container in simorgh is highly tied into the articles design. The container returns timestamps in an articles wrapper with the long form timestamp/relative timezone logic automatically configured and prefixes like `Updated` baked in.

**Describe the solution you'd like**
Before refactoring we should check that there is sufficient test coverage on this feature.

Extract reusable parts of the timestamp container such that it exports a single `time` dom element. It should allow for different formats of time as well as prefixes and suffixes such as 'Updated ' to be passed in as props. 

This can then be used by a much simpler ArticlesTimestamp which simply formats the data, constructs the wrapper and calls the new timestamp container to do the heavy lifting with time formats and moment etc

This work should be done with heavy influence from the other 2 streams to ensure we write a api that is liked by everyone :)

This should be done in a way that doesn't affect the output.

**Testing notes**
Verify accessibility issues
Re-run cypress

Dev insight: Unit testing, storybook and regression needed. 
Ensure cypress tests continue to pass

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by Bopchy** [comment]
My approach is to have the ArticlesTimestamp container 
- Check if a passed in date is valid
- Handle the logic of determining firstPublished and lastPublished times, 
- Pass the times to be rendered & any prefixes/suffixes to the Timestamp container
-  Perform the check for whether time should be relative or not and pass it as a prop to  Timestamp container

The Timestamp container on the other hand will
- Handle time formats, prefixes and suffixes through props

**Comment by dr3** [comment]
Chatted on slack, Imo we should split the logic more, so that you call
```
<TimestampContainer
  timestamp="112121212121"
  dateTimeFormat="YYYY-MM-DD"
  format="D MMMM YYYY, HH:mm z"
  isRelative={false}
  local="en-GB"
  timezone="Europe/London"
  prefix="Updated"
  suffix={null}
/>
``` 
and receive a styled 
```
<time datetime="2019-02-07">
Updated 7 February 2019 12:34 BST
</time>
```
