### ISSUE TITLE
Expand Timestamp container to support new locals for 4 services

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1566]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/pull/1522 we are using Moment with the default `en` local. This is backed with https://github.com/bbc/simorgh/blob/8c5f40e6f41fbfcb872363aff2dcd849197aafe8/webpack.config.client.js#L120 which ensures that we only bundle the `en` local into the simorgh application

**Describe the solution you'd like**
Extend the timestamp container to allow for multiple locals, likely passed as a prop.

Add config to webpack to ensure that we retain the desired locals in the bundle at build time. Work with the simorgh core team so they know what we are doing, as this will likely influence their approach to bundle splitting.

**Testing notes**
[Tester to complete]

Dev insight: Unit tests, passing in different locals and seeing them in storybook/snapshots

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by j-pendlebury** [comment]
Split this into two issues. Leave bundle splitting as blocked, but can add functionality to support prop passing.

**Comment by j-pendlebury** [comment]
New issues created. Closing this one.
