### ISSUE TITLE
Integrate section divider in simorgh

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1568]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/issues/1551, which creates the section devider we should integrate it into simorgh

Blocked on https://github.com/bbc/simorgh/issues/1551 and https://github.com/bbc/simorgh/issues/1547

**Describe the solution you'd like**
Add the section divider in between sections on the ws frontpage, passing the section title to each one.

**Testing notes**
New Cypress test

Dev insight: Snapshots using fixture data and storybook should be sufficient

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by andrew-nowak** [comment]
Closing as done as part of #1703
