### ISSUE TITLE
Use Hooks for Context - useContext instead of Context Consumer

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1569]
**Is your feature request related to a problem? Please describe.**
We're currently using the Context API in various places. We should move to using the Hooks implementation of it with `useContext`. Here is a description of the benefits of using the React Hooks implementation of Context https://frontarm.com/james-k-nelson/usecontext-react-hook/ 

https://github.com/bbc/simorgh/blob/ead571daf45100e1749fe3be96c2eef8deaec639/src/app/containers/ConsentBanner/Banner/index.amp.jsx#L35
https://github.com/bbc/simorgh/blob/4cbe0a30ff6b7976d415800138b3bdabb7fdb173/src/app/containers/Caption/index.jsx#L19
https://github.com/bbc/simorgh/blob/350761cbc024edd2ca206190b3b105827376aafc/src/app/containers/Brand/index.jsx#L6
https://github.com/bbc/simorgh/blob/34450a370a1c5df736622d7b0a470d996c6e8fc5/src/app/containers/Copyright/index.jsx#L9
https://github.com/bbc/simorgh/blob/ead571daf45100e1749fe3be96c2eef8deaec639/src/app/containers/ConsentBanner/Banner/index.canonical.jsx#L20
https://github.com/bbc/simorgh/blob/fdd997630c43819a36a1390d1666778be7d31929/src/app/containers/ErrorMain/index.jsx#L33
https://github.com/bbc/simorgh/blob/8cc14f8b7b138b6a7c9a841749828c8d028189c5/src/app/containers/Metadata/index.jsx#L30-L32

**Describe the solution you'd like**
To use `useContext(ServiceContext)`, `useContext(RequestContext)` instead of `<ServiceContext.Consumer>` `<RequestContext.Consumer>` in this codebase. 

**Describe alternatives you've considered**
We could leave the structure as it currently is, since it will continue to work in the same way. This work enhances readability for the usage of Contexts. 

**Testing notes**
[Tester to complete]

Dev insight: Snapshots would need to be updated. Other unit tests should continue to pass. Cypress tests should continue to pass. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
![](https://camo.githubusercontent.com/f0532a07281b7381bb8348e786e178b8d4ffc705/68747470733a2f2f696d332e657a6769662e636f6d2f746d702f657a6769662d332d3534386631343933656130322e676966)

**Comment by pjlee11** [comment]
Looks like `enzyme` testing doesn't yet support the `useContext` hook - https://github.com/airbnb/enzyme/issues/2011. Realistically instead of doing this work and changing some component unit tests to no longer be `enzyme` we should mark this issue as `externally blocked` and do the work after the next release to `enzyme`
