### ISSUE TITLE
Add console log to advertise open job roles

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1573]
**Is your feature request related to a problem? Please describe.**
We should add a console log message on simorgh pages advertising our Join us page https://bbc-news.github.io/join-us/

**Describe the solution you'd like**
Add a console message containing the link. The message should show in production, but not locally when running `npm run dev`

This will require some cross browser testing and accessibility testing.

**Testing notes**
Manual test of the console log to see whether the job roles ads are displayed.

Dev insight: Snapshot tests, perhaps storybook and manual testing

**Additional context**
This is our current console message on the news homepage
![image](https://user-images.githubusercontent.com/11341355/55894618-54693c80-5bb2-11e9-908e-bb0849094243.png)

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Please note - we have an outstanding accessibility issue with our current implementation. There is poor colour contrast in dark dev tools mode. So we should fix that as we add our console log statement to our new Simorgh pages.

**Comment by jimjohnsonrollings** [comment]
Is there any evidence this has worked?

**Comment by jamesbhobbs** [comment]
@jimjohnsonrollings been read and people have applied yes, people offered jobs not afaik, but it's not tracked very well and those people could have gotten jobs in other parts of the BBC

**Comment by EinsteinNjoroge** [comment]
@dr3 Should this be visible on every page or just the homepage?
