### ISSUE TITLE
Integrate Video promo icon into frontpage 'card'

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1574]
**Is your feature request related to a problem? Please describe.**
Following the creation of the video promo component in https://github.com/bbc/simorgh/issues/1553 we should integrate it into the card component/container

**Describe the solution you'd like**
Following the [UX Designs](https://app.zeplin.io/project/5c8a5e021d454124ef90669f?seid=5cac6de6bc9eec3920203b5c) add the video promo to the card such that it follows the designs for ALL breakpoints

Work with UX to confirm the designs before implementing the positioning

![image](https://user-images.githubusercontent.com/11341355/55896280-ddce3e00-5bb5-11e9-81dd-c479005b1db3.png)

![image](https://user-images.githubusercontent.com/11341355/55896290-e45cb580-5bb5-11e9-86cc-b208660d094c.png)

**Testing notes**
[Tester to complete]

Dev insight: Snapshot and storybook should be enough

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1553

**Comment by dr3** [comment]
~Blocked on investigating how we get the timestamp data~

![image](https://user-images.githubusercontent.com/11341355/55967513-5a265700-5c72-11e9-9e06-dd07656bf974.png)

The duration does come through inside a media version. ~Need to confirm with @neildoughty about the versions we get, and if logic is required to pick between them~

Chatted to Neil, for now we should just use the first version we get. In future this may change, but for now just use the first.

**Comment by j-pendlebury** [comment]
For now this work will be done in Storybook only, until we're ready to do work on containers.

![image](https://user-images.githubusercontent.com/13763899/57064582-a3405880-6cbe-11e9-95df-6ae079d126f8.png)

**Comment by dr3** [comment]
~Just thought ide mention, this piece of work will likely require the creation of a new component.~

The Image & will likely need to be in a `figure` element, with styling on that element to place the `media indictor` ontop, or below the image for different breakpoints

~I would say we should use `psammead-figure`, but its such a small component and we wont want [padding button](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-figure/src/index.jsx#L6) so we can likely create our own with specific `image` and `mediaIndicator` props that it uses~

It also needs to use `@bbc/psammead-image-placeholder` to hold the space

**Comment by dr3** [comment]
Looking at [the article figure implementation](https://github.com/bbc/simorgh/blob/StoryPromoContainer/src/app/containers/Figure/index.jsx) its probably best if we try to reuse as much as possible, it has the amp-image/image logic

Could you maybe propose a solution before implementing? Finding the right balance between reuse and duplication is gunna be tricky

**Comment by dr3** [comment]
Note: the current approach in https://github.com/bbc/simorgh/pull/1640 has the component not using a figure at all, but instead is just wrapped in a placeholder https://github.com/bbc/simorgh/pull/1640/files#diff-7c96cbfde451afa1b48a7b5f219d5ac7R22

**Comment by dr3** [comment]
Blocked on https://github.com/bbc/psammead/pull/522
