### ISSUE TITLE
Flash of invisible text (FOIT)

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#1575]
**Describe the bug**
When using the chrome perf analysis tools it is possible to see the page in a state where no text is visible yet the main image has rendered.

Should this happen when using `font-display: optional`?

According to MDN `font-display: optional` gives a really small `block` period and no `swap` period.

Font Block Period

> If the font face is not loaded, any element attempting to use it must render an invisible fallback font face. If the font face successfully loads during this period, it is used normally.

**To Reproduce**

1. Go to 'https://www.bbc.co.uk/news/articles/c744mjrym37o'
2. Open the chrome dev tool
3. Open the performance tab
4. Refresh the page

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14273378/55897631-d0ff1980-5bb8-11e9-94b8-33b48ee037f5.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: chrome
- Version: 73

**Additional context**

- [X] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by jamesbhobbs** [comment]
During the 'really short' block period yes (and what this means isn't well defined, often 50ms iirc). Subsequently no. Though I suspect it's a browser issue in lieu of any other evidence. optional is still rarely used.

**Comment by dr3** [comment]
@benjaminhobbs Do you feel this should be investigated or closed?

**Comment by jamesbhobbs** [comment]
IMO closed, but if UX wanted to note browsers this happens in we can talk to their maintainers to ensure their short swap period is implemented correctly.
