### ISSUE TITLE
Webpack performance budgets

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1586]
**Is your feature request related to a problem? Please describe.**
We do not currently have anything that tells us if our bundles significantly increase in size. Currently we could inadvertently make our bundles enormous without realising and hurt user experience.

**Describe the solution you'd like**
Set up appropriate `performance` options in Webpack to alert us to potential performance problems at build time. https://webpack.js.org/configuration/performance/

Thresholds should be set at a sensible initial limit and can be revised later.

**Describe alternatives you've considered**
RUM/synthetic performance testing would also alert us to unexpected increases in bundle size, but we would prefer to know before the change is released.

We should think about how and where we define our thresholds for bundle size and whether we can join these up with Lighthouse thresholds somehow.

**Testing notes**
- If you add an unexpectedly large amount to the bundle size then the PR build should fail on CI and merging should be impossible
- Ideally should also fail on developer's machine when building locally

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by rossgaskell** [comment]
I think we need to discuss the limits further, the size of the bundle is increasing by almost 10KB a week so this is going to be a cat and mouse game if we just set the limit to the existing bundle.

**Comment by jamesdonoh** [comment]
As discussed at refinement - while longer-term we want to monitor/graph bundle sizes properly we may as well finish this as it will still alert us to unexpected spikes - propose setting a threshold of current bundle + 25% and completing this.
