### ISSUE TITLE
Analyse second page load after an AMP render

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1591]
**Is your feature request related to a problem? Please describe.**
Currently, when hitting a [simorgh AMP render](https://www.bbc.co.uk/news/articles/c8xxl4l3dzeo.amp) the inline links route to the canonical version of the linked page. We should evaluate how best to serve secondary page loads when on an AMP render.

**Describe the solution you'd like**
Assess how we could:
- Link from AMP -> AMP
- Install service worker & the SPA for the second page render
- {Any other ideas}

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
While analysing how best to handle the second page render after an AMP load we should consider both an SPA and server-side render only scenario.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
If loaded via the amp cache, is it possible to link to another amp article in the amp cache? or do you have to go to bbc.com?

**Comment by chris-hinds** [comment]
> If loaded via the amp cache, is it possible to link to another amp article in the amp cache? or do you have to go to bbc.com?

You would need to get the cache url from the Goggle provided API, this is something I have raised before.

So thinking about it the onward Journey to an AMP page served by bbc.com and the google cache may end up being a perf hit as we will be loading all of the amp scripts.

This is the primary reason we should be rolling our own AMP cache.

However I am speaking to Google soon about serving AMP under our own domain so will raise this issue.

**Comment by neildoughty** [comment]
So, a reason to go AMP > AMP is that our story pages are slooooow. But they won't be in future. As we go more Optimo i think we're more interested in getting people to our amazing article than pushing people to AMP. AMP is still a massive hook to grab people, but as our own platform gets better/acceptable in terms of page speed we'd want to drive as many people as we can to it.

Equally, this feels like a prime candidate for an MVT test at some stage. See what it actually does to our user numbers, if we go AMP > AMP vs AMP > Simorgh

**Comment by rossgaskell** [comment]
**Investigation**

There are two potential implementations created off the back of this. Firstly we can do a simple AMP to AMP navigation: https://github.com/bbc/simorgh/pull/1845. As internal links use relative paths, this would support the AMP cache and onward journeys would be to the AMP cached version of the page.

Alternatively, the AMP project provides a `amp-install-serviceworker` component that can install and activate the service worker. This would mean that onward journeys would be to the canonical article, but would be able to register the SW on first page load: https://github.com/bbc/simorgh/pull/1846

**Comment by pjlee11** [comment]
There was recently a conversation between @benjaminhobbs, @hindsc52, @dr3 and myself regarding how we will eventually turn off the client-side rendering of Simorgh so that we can have an SSR-only render for certain services/users (couldn't find an issue to link 🤔). The main issue raised is that currently any JS executed on the client device actually relies on the client bundles being loaded and the user getting the full SPA. This makes the desired outcome of SSR-only pages difficult given that we will have "essential" JS that needs to execute on the user's device. 

An example of "essential" JS would be the privacy/cookie banner that uses JS to check the User's cookies for whether each banner should be shown. 

Rather than creating a solution which accommodates for SSR-only, EG: having a vanilla JS equivalent for all "essential" JS when we don't send the bundles and run as a SPA. It was suggested that Amp > Amp links could be a solution as we will already have spent time having an equivalent to any "essential" JS in our AMP pages.

This said, ideally we would want a very detailed outcome of the pros and cons from #1845 as it could be used as a long term solution for SSR-only.

**Comment by rossgaskell** [comment]
**Handover**
As mentioned by @pjlee11 above, further technical and product investigation of the impact of going AMP to AMP needs to be performed.

**Comment by jamesbhobbs** [comment]
Now having WS users in production we can see our pageload speed is good enough to not worry about this for the significant future.
