### ISSUE TITLE
Deploy storybook to static pages

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#160]
**Is your feature request related to a problem? Please describe.**
Storybook is not viewable outside of running it locally.

**Describe the solution you'd like**
Storybook deployed to GitHub pages, and updated whenever `latest` is updated with new/updated stories. See information here: https://storybook.js.org/basics/exporting-storybook/#deploying-to-github-pages

**Comment by jamesbhobbs** [comment]
Rejected the idea of deploying to github pages as it requires giving write access to github (to update the gh_pages branch). Working on other deploy options instead.
