### ISSUE TITLE
Migrate to using the `useContext` hook

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1600]
**Is your feature request related to a problem? Please describe.**
Now that there is the [`useContext` react hook](https://reactjs.org/docs/hooks-reference.html#usecontext), we should refactor existing hook consumers to use it.

We decided to refactor all uses out at once to be consistent across the codebase

<img src="https://user-images.githubusercontent.com/11341355/56208470-228c2600-6049-11e9-977c-e1a88a68001f.png" width="400px" />

**Describe the solution you'd like**
Replace all context consumers with `useContext`, maintaining functionality

**Testing notes**
[Tester to complete]

Dev insight: Regression only

**Additional context**
lol `context` pun

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
@dr3 FYI there is duplication with this ticket: https://github.com/bbc/simorgh/issues/1569

**Comment by dr3** [comment]
Ah snap, closing in favour of #1569
