### ISSUE TITLE
Refactor Moment locale bundle splitting

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1604]
**Is your feature request related to a problem? Please describe.**
Currently we use Regex for handling including only the required moment locales.

https://github.com/bbc/simorgh/pull/1522/files#r275449780 
The `MomentLocalesPlugin` module is recommended by the Moment.js team as an alternative, [as raised by @jamesdonoh here](https://github.com/bbc/simorgh/pull/1522/files#r275449780)

https://momentjs.com/docs/#/use-it/webpack/

**Describe the solution you'd like**
To use `MomentLocalesPlugin` as a safer way to handle importing locales. 

**Describe alternatives you've considered**
We could leave the regex solution as it is currently, since if we decide to move away from using Moment, we'll need to use the existing setup. 

**Testing notes**
[Tester to complete]

Dev insight: Regression testing of the pages is needed, ensuring datetime locales work. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
👋 This can be done, but bare in mind it likely wont be compatible with https://github.com/bbc/simorgh/issues/1602 which, rather than excluding the ones we dont want, will need to include the ones we do

**Comment by jamesdonoh** [comment]
We shouldn't pick this up till the outcome of #1602 is known as it may invalidate this issue completely.

**Comment by dr3** [comment]
This probably isnt needed anymore, we now use
```
new webpack.IgnorePlugin({
   resourceRegExp: /^\.\/locale$/,
   contextRegExp: /moment$/,
}),
```
We could move to `new MomentLocalesPlugin(),` which strips all locales except “en”, but I doubt thats going to be any better/worse. The IgnorePlugin works fine and isnt an extra dependancy
