### ISSUE TITLE
Mention at least once the location of the deployed Simorgh storybook

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#1609]
**Is your feature request related to a problem? Please describe.**
We never once mention in this repo the location of the [deployed Simorgh storybook](https://bbc.github.io/simorgh/).

**Describe the solution you'd like**
Add it to the documentation.

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: n/a

**Additional context**
n/a

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by chris-hinds** [comment]
Until we have the Article and Homepage containers in the Storybook is the any point mentioning this? There is nothing here to see really. i.e. should some of the components here actually be in Psammead.

**Comment by jamesbhobbs** [comment]
@hindsc52 I'd be happy with tidying which components are where. I do think if we have storybook, we should have a link to it somewhere, even if only an expression of intent.
