### ISSUE TITLE
Summarise types of configuration

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1614]
**Is your feature request related to a problem? Please describe.**
In order to begin to to plan configuration management for Simorgh it would be useful to have a summary of all the different types of 'configuration' that we may need to manage as the application grows

**Describe the solution you'd like**
A table summarising the different types of config we need with some examples of each. We should consider the level of volatility and sensitivity for each type of config:

https://paper.dropbox.com/doc/Simorgh-Core-Configuration-Investigation--AeWq0OlYhJ_ebhTYR14bKL9RAQ-ItLAkMtiLrBzqi8lOWfmS

We should note for each type of config whether it should be:

- Static
- Dynamic (set at build time)
- Dynamic (set at run time)

We should also note _who_ needs to be able to update it (e.g. developers, journalists, 24/7).

**Additional context**

- [ ] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by rossgaskell** [comment]
Investigation notes: https://paper.dropbox.com/doc/Simorgh-Core-Configuration-Investigation--AeWq0OlYhJ_ebhTYR14bKL9RAQ-ItLAkMtiLrBzqi8lOWfmS
