### ISSUE TITLE
Data endpoints for WS frontpages

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1621]
**Is your feature request related to a problem? Please describe.**
For the ws-frontpage we need a way of exposing backend API's to the client. The solution should be both resilient and scalable.

**Describe the solution you'd like**
Work with the Mozart team to define a solution for interfacing from the client with many backend API's. 

**Describe alternatives you've considered**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Following a workshop with the Mozart team we have decided to clearly define all required and to then flesh out a solution

**Comment by pjlee11** [comment]
Requirements have been provided, now awaiting a solution

**Comment by jamesbhobbs** [comment]
@dr3 isn't this now covered in a different issue?

**Comment by dr3** [comment]
@benjaminhobbs Im now working out of RESFRAME-2807, but that doesnt cover onward journeys

**Comment by pjlee11** [comment]
Removing onward journeys from the description because it will be covered in https://github.com/bbc/simorgh-infrastructure/issues/356
