### ISSUE TITLE
Add cookie check to mPulse beacon

### ISSUE THREAD

**Issue by rossgaskell** [bbc/simorgh#1630]
**Is your feature request related to a problem? Please describe.**
If a user has disabled performance cookies, the mPulse beacon will still be shown, therefore not respecting a user's privacy settings.

**Describe the solution you'd like**
Check that the user has enabled cookies (exact perferences/type of cookie to check TBD) before rendering the mPulse beacon.

Check the Dynatrace Beacon in RN to see which cookie was required to be set before loading the beacon.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by rossgaskell** [comment]
**Handover**
Currently the beacon is rendered server side so we don't have access to cookies to check that users have accepted performance based cookies. One potential solution suggested by mPulse but would need investigating to ensure it works would be to render the beacon disabled (ie running `window.BOOMR.disable()` after it's initialised. Then running `window.BOOMR.init()` once we have confirmed a users cookie policy.

**Comment by jroebu14** [comment]
I've investigated which cookie checks are made before loading the Dynatrace beacon in RN and it appears to be a cookie called `performance` as demonstrated [here](https://github.com/BBC-News/responsive-news/blob/b1f47ddb1b7db374cd6904f331565162690dea3e/tabloid/webapp/php/sharedmodules/tabloid-shared/views/component/dynatrace-beacon-news.mustache#L3)

**Comment by jroebu14** [comment]
Based on the previous comment which suggests an approach of rendering the beacon, then disabling it and checking a user's cookie preferences and then reinitialising the beacon again if the user allows it (which Ross hints may not actually work) I had a think about another approach.

I would like to know people's opinions on parsing cookies on the server side of the application and providing the result to any component that needs it. If we implement a solution for this we would have access to cookies on the first render of the app which we can use to decide whether to render parts of the application based on a user's cookie preferences.

My suggested approach for this would be to parse the cookies from the request made to the server, store the cookies using the React Context API and then have a custom hook for the universal getting and setting of cookies inside of components.

**Comment by neilstuartcraig** [comment]
Hi all.
Can I just check that you're discussing the potential for doing cookie decomposition on a BBC traffic manager?

**Comment by chris-hinds** [comment]
@neilstuartcraig apologies for the delayed reply. That was the suggestion. However we know this would come with many more implications.

I am also not sure that the cookie decomposition on the server is the best bet for us, especially as a user could change their cookie preferences whilst they are inside our SPA, so the client would need to know how to handle the cookie checks anyway.
