### ISSUE TITLE
Remove datavalidator logic

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1638]
**Is your feature request related to a problem? Please describe.**
The dataValidator currently validates against the article fixture `data/`, now that simorgh is being used for the articles and ws-frontpages we should remove this logic. In the future there should be a validation solution as an outcome of the schema workshop between Optimo, Ares and Articles. This would then be used in production and make the local validation logic obsolete. 

**Describe the solution you'd like**
After confirming we have an agreed approach to validator code elsewhere in the rendering chain we should remove the validator logic from simorgh. 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
I've moved the current logic to https://github.com/bbc/articles-validator so it is not lost.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1616 until the preprocessor logic finds a new home

**Comment by jamesdonoh** [comment]
@pjlee11 given #1616 is closed what's the status of this?

**Comment by jamesbhobbs** [comment]
Given this I've removed all other issues with the Data Validation label.

**Comment by pjlee11** [comment]
I think we need to discuss the purpose of the data validator. We currently validate the fixture data which doesn't have any impact on production. The outcome of the schema workshop should really replace the need for the data validator. https://github.com/bbc/articles-validator

**Comment by dr3** [comment]
@pjlee11 Any updates on this?

**Comment by pjlee11** [comment]
The schema validator is looking to become part of Ares workflow but after they've released their v2. This ticket is still relevant as it asks should we be validating our fixture data at all?

**Comment by dr3** [comment]
Sounds like we should extract it, but then import it back as a dep and run it like we currently do maybe?

**Comment by pjlee11** [comment]
I think if we are looking to extract it and use it as a dep, we would be better off pulling in https://github.com/bbc/articles-validator as a dep and running the validator using ajv

**Comment by jamesbhobbs** [comment]
Replaced by #3697
