### ISSUE TITLE
Move .storybook to its own separate artifact

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#1639]
**Is your feature request related to a problem? Please describe.**
As part of #398 I have created a script that packages up files and adds them to a shared simorgh zip file that is then passed to simorgh-infrastructure. Now for now this is alright. However this means that the storybook files are added to the RPM, which is something that we do not want. 

**Describe the solution you'd like**
- Create a script that creates a storybook deployment:
  - Copies over the storybook deployment
  - Copies over the src folder (for the storybook files)
  - Copies over the data folder
  - Zips the deployment and adds it to the stash
- In the deploy storybook, unstash the code and perform the deployment

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by alex-magana** [comment]
Blocked by https://github.com/bbc/simorgh-infrastructure/issues/398

**Comment by DemonusPC** [comment]
Unblocked, this has now become a prerequisite.
