### ISSUE TITLE
Adding support for Windows

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#165]
**Is your feature request related to a problem? Please describe.**
In one of the daily standups it was mentioned that as an Open Source project the team should support all major platforms: Linux, MacOS and Windows. This is currently not the case due to two major problems:

- The js "compiler" is crashing due to line feed problems (CRLF - LF) 
- NVM does not support Windows (And the few alternatives are either not maintained or have a very limited maintenance) 

**Describe the solution you'd like**
The team should agree to either support windows or not. Going forward with windows support, the biggest challenge will be the lack of nvm support for windows. We would either extend nvm or try to resurrect one of the nvm for windows projects.

**Comment by jamesbhobbs** [comment]
We will explicitly support only Linux, MacOS. Windows devices are unavailable to the core maintainers at the BBC (nearly every dev uses MacOS or Linux in the BBC), we will therefore not provide explicit support for it. However, if patches are provided by a wider community we will accept them as we do not wish to deliberately exclude Windows users.
