### ISSUE TITLE
MPulse beacon continues to fire when snippet is removed

### ISSUE THREAD

**Issue by rossgaskell** [bbc/simorgh#1659]
**Describe the bug**
We should be able to disable the beacon on the client side render based on a feature toggle. However during the investigations into implementing mPulse, once the beacon has been loaded during the first page render, the beacon iframe persists despite the snippet being removed from the page.

**Expected behavior**
When the beacon snippet is removed from the page, beacon should be removed from the page and stop firing.

**Additional context**

**Comment by simonhearne** [comment]
I assume this issue would only occur if the beacon is disabled mid-session?
The iframeless loader snippet would likely resolve this issue: https://developer.akamai.com/tools/boomerang/docs/tutorial-loader-snippet.html

**Comment by rossgaskell** [comment]
Thanks @simonhearne, will take a look.

**Comment by rossgaskell** [comment]
To resolve this, we will keep the beacon rendered purely in the server side document which will prevent the issues surrounding React Helmet.

In order to support client side toggling, a new client side component should be created which will trigger the disable method of the beacon: `window.BOOMR.disable()`, which should remove the event listeners and prevent the beacon from firing. As this doesn't construct extra tags inside the head, it should prevent the recursion error with Helmet when navigating between articles.
