### ISSUE TITLE
Pass moment locale prop to psammead timestamp

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#1663]
**Is your feature request related to a problem? Please describe.**
~~Blocked on https://github.com/bbc/psammead/issues/613 and https://github.com/bbc/psammead/issues/553 and https://github.com/bbc/psammead/issues/651,~~ we can pass the moment locale to psammead timestamp to set it for moment.

**Describe the solution you'd like**
1) Pass the locale to psammead timestamp in frontpages and articles.

2) Install the two locales created by https://github.com/bbc/psammead/issues/553 like
```
import '@bbc/psammead-locales/moment/ig'
```
In igbo and pidgins config files.

3) Open up the regex used to include locales [in webpack](https://github.com/bbc/simorgh/blob/latest/webpack.config.client.js#L120) to include the persian and yoruba locales

After this, you should see all timestamps translated to their own service in article and frontpages

**Testing notes**
Storybook regression

Dev insight: Unit tests, passing in different locals and seeing them in storybook/snapshots

**Additional context**

**Comment by EinsteinNjoroge** [comment]
@dr3 The description on this issue is not very clear, kindly expound on point 2 and 3 of the solution. cc @jblaut
