### ISSUE TITLE
Replace Timestamp container snapshot tests

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1666]
**Is your feature request related to a problem? Please describe.**
Replace snapshot tests for Timestamp Container with assertion-based tests. This is so we can safely test the Relative behaviour without the `dateTime` attribute in the snapshot needing to be updated every day, as the date increments. 

**Describe the solution you'd like**
Use tests similar to those in ArticleTimestamp https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleTimestamp/index.test.jsx#L94

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
@sareh this is no longer in this repo, perhaps move to psammead?
