### ISSUE TITLE
Vulnerability in execa dependency

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1667]
**Describe the bug**

```
✗ Medium severity vulnerability found in execa
  Description: Arbitrary Command Injection
  Info: https://snyk.io/vuln/SNYK-JS-EXECA-174564
  Introduced through: webpack-cli@3.3.0
  From: webpack-cli@3.3.0 > yargs@12.0.5 > os-locale@3.1.0 > execa@1.0.0


Organisation:      bbc
Package manager:   npm
Target file:       package-lock.json
Open source:       no
Project path:      simorgh

Tested 738 dependencies for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.

Run `snyk wizard` to address these issues.
```

**To Reproduce**

1. locally run `npm run snyk`
2. See error

**Expected behavior**
No error

**Screenshots**
<img width="728" alt="Screen Shot 2019-05-02 at 14 34 10" src="https://user-images.githubusercontent.com/3028997/57079009-5fae1480-6ce7-11e9-97dd-826a6453a2e8.png">

**Comment by rossgaskell** [comment]
Hi @sareh, have run this against latest but can't replicate. Can you try and reproduce for me?

![image](https://user-images.githubusercontent.com/21201639/57385634-b2397600-71aa-11e9-81d6-4d636fbbefcd.png)

**Comment by rossgaskell** [comment]
Closing as vulnerability no longer reported
