### ISSUE TITLE
Disable Code Climate GitHub quality checks for test code

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1674]
**Is your feature request related to a problem? Please describe.**
We have had several instances of Code Climate failing PRs due to duplication in test code, e.g. https://github.com/bbc/simorgh/issues/1612

In most cases the issues raised seem trivial and addressing them would make the tests harder to follow.
We need to configure the codeclimate check to only assess the application code result and exempt its check on the test code.

**Describe the solution you'd like**
Stop Code Climate quality check failures in test code from blocking PRs.

**Describe alternatives you've considered**
None known. From Code Climate docs:
> Exclusions can only be made at the global level (excluding code from all analysis) or at the plugin-level (excluding code only from specific third-party plugins). *Currently, exclusions cannot be made for individual maintainability checks.*

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
None.

**Comment by alex-magana** [comment]
Resolved by adding the required patterns to the exclude patterns in the repo settings on Code Climate.

See comment in https://github.com/bbc/simorgh/pull/1782
