### ISSUE TITLE
Refactor client.js to not require the SIMORGH_DATA.service property

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#1679]
**Is your feature request related to a problem? Please describe.**
At the moment client.js requires the service property to be set on the global SIMORGH_DATA object to pass the service name to the service worker url constructor.

client.js is now the only file that requires service to be set on this global data object.

**Describe the solution you'd like**
During [this](https://github.com/bbc/simorgh/pull/1673) PR a new `getRouteProps` helper was implemented that returns the service and isAmp props based on the current route. We should look to use this in client.js and leave the SIMORGH_DATA object to simply store page data and not application based data.

As a part of this we should refactor the tests around the service worker registration and installation as they manually set the service property on the SIMORGH_DATA object in order for the tests to pass.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Comment by rossgaskell** [comment]
**Handover**
PR https://github.com/bbc/simorgh/pull/1713 currently awaiting 2nd code review
