### ISSUE TITLE
Add uploadDate to video schema.org

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1685]
**Is your feature request related to a problem? Please describe.**
Video schema.org data should contain an uploadDate field.  This is currently not there.  This will be exposed in the Ares data as availableFrom.

**Describe the solution you'd like**
uploadDate field inserted into schema where the date is made available by Ares.

**Describe alternatives you've considered**
N/A

**Testing notes**
Inspecting Storybook to ensure schema metadata is added. 

Dev insight: Unit tests should be sufficient. Can view integration within Storybook's Video container. http://localhost:9001/?selectedKind=Video%20Container

**Additional context**

**Comment by jimjohnsonrollings** [comment]
Ares now updated to provide this.

**Comment by sareh** [comment]
@jimjohnsonrollings On existing articles on Test, e.g. `https://www.test.bbc.co.uk/news/articles/c2nn1prnl39o.json`, I cannot see the `uploadDate` field. 
I also just created a new article on Test with a video and it does not have the `uploadDate` field either. `https://www.test.bbc.co.uk/news/articles/c4d8dqrd5wyo.json`

**Comment by jimjohnsonrollings** [comment]
@sareh  Multiple possibilities:
- Assets probably need refetching and republishing to output the new field
- Not all videos will have the relevant data available to create this field
