### ISSUE TITLE
Add pageIdentifier & statsDestination to Request Context

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1693]
**Is your feature request related to a problem? Please describe.**

We need `pageIdentifier` and `statsDestination` values within the Video Container. https://github.com/bbc/simorgh/issues/1636

Currently `pageIdentifier` is determined via this helper function that requires all of `articleData` available. 
https://github.com/bbc/simorgh/blob/6d54b147cdb5a3e74fff9cfb3c70d0289a6fc690/src/app/containers/PageViewAnalytics/labelHelpers/article.js#L6-L12

`statsDestination` is defined here, requiring `env` and `isUK`

https://github.com/bbc/simorgh/blob/6d54b147cdb5a3e74fff9cfb3c70d0289a6fc690/src/app/containers/PageViewAnalytics/labelHelpers/index.js#L4

The values of `pageIdentifier` and `statsDestination` shouldn't need to be passed down via props, they should be available via the RequestContext. 

| statsDestination value | condition |
|------| ----------|
| 'NEWS_PS' | if service is 'news' & isUK is true & env is 'live' |
| 'NEWS_PS_TEST' | if service is 'news' & isUK is true & env is not 'live' |
| 'NEWS_GNL'| if service is 'news' & isUK is false & env is 'live' |
| 'NEWS_GNL_TEST'| if service is 'news' & isUK is false & env is not 'live' |
| 'WS_LANGUAGES' | if service is a WS service & isUK is true & env is 'live' |
| 'WS_LANGUAGES' | if service is a WS service site & isUK is false & env is 'live' |
| 'WS_LANGUAGES_TEST' | if service is a WS service & isUK is true & env is not 'live' |
| 'WS_LANGUAGES_TEST' | if service is a WS service site & isUK is false & env is not 'live' |

| statsPageIdentifier value | condition | 
|------| ----------|
| 'news.articles.c0000000000o.page' | if service is 'news' & id is 'c0000000000o' & pageType is 'article' |
| 'persian.articles.c0000000000o.page' | if service is 'persian' & id is 'c0000000000o' & pageType is 'article' |
| 'news.page' | if service is 'news' & id is 'c0000000000o' & pageType is 'frontpage' |
| 'persian.page' | if service is 'persian' & id is 'c0000000000o' & pageType is 'frontpage' |

**Describe the solution you'd like**
Add `pageIdentifier` & `statsDestination` values to the Request Context. 
This will enable us to pass these values to Video (and later, Audio) components in a simpler way.

However, `articleData` is not available at this level, so the helper method for defining `pageIdentifier` would need to be re-written to use the `id` from the url, not the id from `articleData`.

**Describe alternatives you've considered**
N/A

**Testing notes**
A developer should talk through the logic with the tester. Full integration testing will occur with this follow-on issue https://github.com/bbc/simorgh/issues/1636

Dev insight: Unit tests should be sufficient.

**Comment by chris-hinds** [comment]
This seems like a good and valid improvement to make. The new getRouteProps helper method may help with exposing the ID from the URL.

https://github.com/bbc/simorgh/blob/latest/src/app/routes/getInitialData/utils/getRouteProps.js

**Comment by sareh** [comment]
@hindsc52 Thanks for highlighting `getRouteProps` - however, at this RequestContext level, we'd need to pull in `routes` from https://github.com/bbc/simorgh/blob/latest/src/app/routes/index.js & then also provide the `url`. Are you suggesting we pull in the `url` from `window.location.href` here, or provided via another way? I'd rather use the existing values within the application than fetch them again. I'm not currently sure of the cleanest way to do that, though.

**Comment by chris-hinds** [comment]
@sareh thats a good point, constantly passing these values around can be a real pain. What if we were to update the request context within App.jsx or potentially higher? That way we can set those values in the request context once on first render and then the request context will get updated on client side re-renders too?

**Comment by pjlee11** [comment]
I've not looked into it in depth but is there a way to extend/add to a provider after the initial creation? I'm wondering this because unless I'm mistaken we don't actually need to consume the the url value before the pageData is available, we only need it before pageData because that is when the requestContext is initialised. 

If context provider can't be added to then maybe this highlights that the requestContext isn't suitable for this use case as well as the use cases it has for Error and Loading states

**Comment by chris-hinds** [comment]
@pjlee11 context can 100% be updated. however we don't currently do that within the application. We should look to implement a redux like pattern using actions which are there to set the context values.

To me this one one of the primary reasons for sing some sort of intern state management like context. we should be able to initialise the values and update them throughout the application as and when needed.

**Comment by pjlee11** [comment]
That feels like a longer term solution. In the meantime would it be a sensible solution to have a seperate context for the `url` value which is set inside of the article container after the error/loading has been handled. Therefore there could be a `RequestContext` and potentially a `PageContext` and after having successfully fetched the data we could populate the `PageContext`.

This way we seperate the responsibility of the contexts, then in the future we can implement a redux like pattern if required

**Comment by chris-hinds** [comment]
We could, I am wary about just adding more context providers as we need to ensure components that pull data from multiple context consumers are not unnecessarily re-rendering.

I am also not 100% sure if this would solve the issue that @sareh has raised.

**Comment by sareh** [comment]
Thanks for both of your comments on this. This has helped clarify the various options available.

I think adding `id` to the RequestContext could address this.
`getRouteProps` would need to return the id `cxxxxxxxxxxo` https://github.com/bbc/simorgh/blob/latest/src/app/routes/getInitialData/utils/getRouteProps.js#L14

`id` would need to be added to state in App.jsx  & returned https://github.com/bbc/simorgh/blob/latest/src/app/containers/App/App.jsx#L80 

So that it can be passed in as a prop to `ArticleContainer` & used in `RequestContext` here https://github.com/bbc/simorgh/blob/latest/src/app/containers/Article/index.jsx#L43

Then id is available throughout the application, and can be used to determine `pageIdentifier` easily.

What are your thoughts on this approach? @hindsc52 @pjlee11

**Comment by sareh** [comment]
Regarding `statsDestination`: this should be much simpler. 
This could have its own function within `RequestContext` called `getStatsDestination`, similar to [getOriginContext](https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/getOriginContext.js). 
What are your thoughts on this?

**Comment by chris-hinds** [comment]
> Thanks for both of your comments on this. This has helped clarify the various options available.
> 
> I think adding `id` to the RequestContext could address this.
> `getRouteProps` would need to return the id `cxxxxxxxxxxo` https://github.com/bbc/simorgh/blob/latest/src/app/routes/getInitialData/utils/getRouteProps.js#L14
> 
> `id` would need to be added to state in App.jsx & returned https://github.com/bbc/simorgh/blob/latest/src/app/containers/App/App.jsx#L80
> 
> So that it can be passed in as a prop to `ArticleContainer` & used in `RequestContext` here https://github.com/bbc/simorgh/blob/latest/src/app/containers/Article/index.jsx#L43
> 
> Then id is available throughout the application, and can be used to determine `pageIdentifier` easily.
> 
> What are your thoughts on this approach? @hindsc52 @pjlee11

@sareh I'm guessing ID is required on the server side render too? if so ID might also need to be added here so it gets passed to the document.

**Comment by chris-hinds** [comment]
> Regarding `statsDestination`: this should be much simpler.
> This could have its own function within `RequestContext` called `getStatsDestination`, similar to [getOriginContext](https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/getOriginContext.js).
> What are your thoughts on this?

Happy with this :)

**Comment by sareh** [comment]
>@sareh I'm guessing ID is required on the server side render too? if so ID might also need to be added here so it gets passed to the document.

Since `ArticleContainer` is rendered on both client and server, I assume having it there should be sufficient? I'm not sure where you mean by `added here`, if not in `ArticleContainer`.

**Comment by chris-hinds** [comment]
> > @sareh I'm guessing ID is required on the server side render too? if so ID might also need to be added here so it gets passed to the document.
> 
> Since `ArticleContainer` is rendered on both client and server, I assume having it there should be sufficient? I'm not sure where you mean by `added here`, if not in `ArticleContainer`.

Ahhh my bad I forgot to add the link. I was thinking it might be worth adding the ID [here](https://github.com/bbc/simorgh/blob/latest/src/server/index.jsx#L148) in the server, this way it gets passed a prop to the document, but I don't actually think that it is required.

**Comment by sareh** [comment]
Okay, thanks. That makes sense. Although it is possible to be passed in there, to then be passed to the Document component https://github.com/bbc/simorgh/blob/latest/src/server/Document/index.jsx#L32, it shouldn't be necessary at all.
