### ISSUE TITLE
DOMException in AMP VideoContainer story

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1698]
**Describe the bug**
Storybook is throwing a `DOMException` error when navigating through `Video Container - AMP` stories.

**To Reproduce**

1. Go to https://bbc.github.io/simorgh
2. Open developer console
3. Click through the `Video Container - AMP` stories

**Expected behavior**
No console errors should be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/7690572/57612384-a95ef080-756c-11e9-9f30-05eaf3407f0a.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 74.0.3729.131

**Comment by thekp** [comment]
i've been trying to fix a similar bug on my [PR](https://github.com/bbc/simorgh/pull/2105) and ended up fixing this bug instead with this...

 ```
const isRegistered = element => !!customElements.get(element);

 {isRegistered('amp-default') ? null : (
        <script
          async
          custom-element="amp-default"
          src="https://cdn.ampproject.org/v0.js"
        />
      )}
```
