### ISSUE TITLE
Update ATI (analytics) for WS Articles

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1699]
**Is your feature request related to a problem? Please describe.**
We should ensure that the WS Languages stats destination values are used for World Service sites. 

We should also ensure we pass in all of these fields: 

| Field | Value |
| -- | -- |
| Destination (s) | WS_NEWS_LANGUAGES: 598342 (live), 598343 (test) |
| Producer | `69` (for Persian) |
|Chapter | Null (should not be passed as a query param |
| Page (p) | `'persian.articles.c0000000000o.page'` |

**Describe the solution you'd like**
Update the `getDestination` logic to use the WS News Languages buckets for Test/Live. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Tester to pair with dev, and also Jim or Alex, to ensure correct values are being passed. 

Dev insight: Unit tests & manual tests.

**Comment by 12** [comment]
According to https://bbc.github.io/echo-docs/documentation/reporting-ati/#producer, the values for World Service sites should be as follows:

```
WS_NEWS_LANGUAGES: 598342
WS_NEWS_LANGUAGES_TEST: 598343
```

**Comment by sareh** [comment]
Closed as fixed.
