### ISSUE TITLE
Use new reith fonts

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1710]
**Is your feature request related to a problem? Please describe.**
Following #1649, we are awaiting our third party to produce the full set of source font files for the GEL team to host. After these files have been hosted, we should update the font source files to use the new version. This version of Reith should have reduced whitespace around the rendered glyphs which will allow our UX team to have design freedom going forward. 

This issue should bump our Reith version to 2.5+ which will then include the changes for 2.4 and 2.5+ 

**Describe the solution you'd like**
Update ‘globalStyles’ to use the new version of the reith source font files. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Regression across fonts including visual regression. Check across older OS's to ensure the fonts don't regress.

Dev insight: Update all relevant tests. Manually check that the 2.500 font files are being pulled in, in the network tab. 

**Additional context**
There should be no visual change in the rendered page.

**Comment by pjlee11** [comment]
This ticket also incorporates the testing and bumping for https://github.com/bbc/simorgh/issues/1724.

**Comment by jimjohnsonrollings** [comment]
Updated special characters test asset: c45kr234w4wo

**Comment by pjlee11** [comment]
The new font version was put live through dependabot so this work is complete
