### ISSUE TITLE
Investigate optimisation of Dials data fetching

### ISSUE THREAD

**Issue by rossgaskell** [bbc/simorgh#1712]
**Is your feature request related to a problem? Please describe.**
In the current proposed implementation of fetching Cosmos dials values (https://github.com/bbc/simorgh/pull/1628), the dials file is read on each request. At the moment this isn't an issue with the current application load in which Mozart caches requests for 30s, but as the number of articles increases and we starting serving WS articles we may soon therefore be receiving 1000rps which as the dial value will not change as frequently, is inefficient.

**Describe the solution you'd like**

- Investigate and document potential optimisations.
- Raise issues to implement proposals

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by chris-hinds** [comment]
Closing as Dials are soon to be removed from simorgh.
