### ISSUE TITLE
Persian footer links

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1716]
**Is your feature request related to a problem? Please describe.**
Currently the Persian footer container includes the links that are suitable for News. These should be updated for Persian

Details to be confirmed by @jimjohnsonrollings & WS Product, since the Zeplin designs (see screenshot) differ in number and order from the links on the live Persian site (listed in the tables below)
<img width="640" alt="Screen Shot of footer design from Zeplin" src="https://user-images.githubusercontent.com/3028997/57781484-2c757780-7722-11e9-8448-4f71965f28ca.png">

**Describe the solution you'd like**
- Update the Footer Container to take in an array of links from the service config files.  
- Keep the current News links for the News Service.
- Add the Persian links for the Persian Service. 

**Links**

|Link href | Link text |
|-----|-----|
|'https://www.bbc.com/persian/institutional-37474133' |'شرایط استفاده' |
|'https://www.bbc.com/persian/institutional-37474136' |'درباره بی بی سی' |
|'https://www.bbc.com/persian/institutional-37540067' |'سیاست حفظ حریم خصوصی' |
|'https://www.bbc.co.uk/privacy/cookies/managing/cookie-settings.html' |'Cookies' |
|'https://www.bbc.co.uk/accessibility/' |'Accessibility Help' |
|'https://www.bbc.co.uk/guidance' |'Parental Guidance' |
|'https://www.bbc.com/persian/institutional-37542244' |'تماس با بی بی سی' |
|'https://www.bbc.co.uk/bbcnewsletter' |'Get Personalised Newsletters' |

**Copyright Text**
`\u00A9 ${currentYear()} BBC.  بی بی سی. بی بی سی مسئول محتوای سایت های دیگر نیست. سیاست ما درباره لینک دادن به سایت های دیگر.`

**External link**

|Link href | Link text |
|-----|-----|
| 'https://www.bbc.com/persian/institutional/2011/04/000001_links'| 'سیاست ما درباره لینک دادن به سایت های دیگر.' |

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests & Cypress tests.

**Comment by dr3** [comment]
Added `ws-frontpage-stream` label as we also need this work :)

**Comment by dr3** [comment]
done by https://github.com/bbc/simorgh/pull/1852
