### ISSUE TITLE
Metadata: SEO Sit down with Tom ☕️🍪

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#1717]
~Blocked on #1906~
WSFRONTPGS-22

Go through metadata we receive to make sure all the values we receive are correct, and create further issues if needed.

**Comment by dr3** [comment]
Sit with tom once we have this on a URL to check for SEO

**Comment by j-pendlebury** [comment]
To check:
- Twitter:
```
twitterCreator: '@BBCNews',
twitterSite: '@BBCNews',
```

- Facebook:
```
facebookAdmin
facebookAppID
```

**Comment by j-pendlebury** [comment]
Arranged time with Tom for Thursday @ 2pm

**Comment by j-pendlebury** [comment]
Changed to Thursday @ 3:30pm

**Comment by j-pendlebury** [comment]
Talked to Tom, there were some questions raised and he will get back to me. But there aren't any major issues that could stop us from going live

**Comment by dr3** [comment]
Removing v1 label as "there aren't any major issues that could stop us from going live"
