### ISSUE TITLE
Bump Reith fonts to >= 2.400

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1724]
**Is your feature request related to a problem? Please describe.**
Superscript and subscript numbers contain a bug in Reith font versions below 2.400.  This bug causes superscript 1, 2 and 3 to appear differently to all the other superscript and subscript numbers.  Examples of this can be seen in test asset cev804m5n0vo.

**Describe the solution you'd like**
Use a Reith font version greater than or equal to 2.400
When this ticket is picked up, we should check that this is the latest version.  

**Describe alternatives you've considered**
N/A

**Testing notes**
Regression across fonts. Check across older OS's to ensure the fonts don't regress. 

Dev insight: Update all relevant tests. Manually check that the 2.400 font files are being pulled in, in the network tab. 

**Additional context**

**Comment by sareh** [comment]
The version of the font files used is currently defined here, in Psammead `@bbc/psammead-styles` https://github.com/bbc/psammead/blob/4cef741ea946a697801069b78ad345b53e1d7ea9/packages/utilities/psammead-styles/src/fonts.js#L1

**Comment by pjlee11** [comment]
Superseded by https://github.com/bbc/simorgh/issues/1710 which will pull in the newer version for 2.5+
