### ISSUE TITLE
No italics for Arabic-script language blocks

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1731]
**Is your feature request related to a problem? Please describe.**
As a reader of an Arabic-script site (Persian, Arabic, Urdu, Pashto)
I never want to see italics
So that I can read the text

Given I am on an article that uses an Arabic script
And one of the fragment blocks contains the italic attribute
Then I see that fragment as if it did not have an italic attribute

Given I am on an Arabic-script article
Then I see no italic text

Note:
- Exclusion for nested blocks: e.g. `fa` article with  `en-gb` block - italic should work in the `en-gb` block but not for the `fa` blocks. 

**Describe the solution you'd like**

- [ ] Pull in [work in psammead which disabled italics in persian](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap#L59-L65)
* this means:
  * Updating `psammead-styles` to version `1.1.0` if/where needed ([see work in psammead to de-italicise caption](https://github.com/bbc/psammead/pull/939))
  * [using functions like `getSansItalic` where we currently use `font-style: italic`](https://github.com/bbc/psammead/blob/799c4c667098094e1acd801ee2b51f4edf5433bb/packages/components/psammead-caption/src/index.jsx#L22)
 * Rethinking our approach to `<i>` and `<b>` tags in [`Fragment`](https://github.com/bbc/simorgh/blob/2b72dbef65d90018dcdde9f04e3058a404510422/src/app/containers/Fragment/index.jsx)

**Describe alternatives you've considered**
Fixing these issues by using
```
 [lang=fa] & {
    font-style: normal;
  }
```
but the approach in this ticket removes duplication and will handle this for more languages than just farsi.

**Testing notes**
-  [Farsi article c19v65z3lg5o](http://localhost.bbc.co.uk:7080/persian/articles/c19v65z3lg5o) has italics in the headline in the data (on  `فوتبال` )

Regression is sufficient & manual testing. 

Dev insight: Unit tests should be sufficient.

**Additional context**

**Comment by sareh** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1730 & https://github.com/bbc/simorgh/issues/1732

**Comment by jamesdonoh** [comment]
As far as I can see, once https://github.com/bbc/psammead/issues/543 is done captions should already lose their italic formatting for Persian (this needs verifying).

Or we could disable italics in paragraph text on a per-service basis by modifying `Fragment` to check `ServiceContext` and the language attribute passed from Optimo when deciding whether to wrap in `<i></i>` or not?

**Comment by jamesdonoh** [comment]
#1730 and #1732 are both closed and this is no longer blocked.

**Comment by pjlee11** [comment]
We should aim to complete https://github.com/bbc/psammead/issues/376 before/or parallel to this work.

**Comment by twinlensreflex** [comment]
https://github.com/bbc/simorgh/issues/2623 is linked
