### ISSUE TITLE
Integrate Video into Article

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1733]
**Is your feature request related to a problem? Please describe.**
Integrate VideoContainer into the ArticleMain container. This will make the Videos render on Article pages. 

**Describe the solution you'd like**
Add the VideoContainer in the [ArticleMain Blocks list](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleMain/index.jsx#L12).

Ensure the same layout as for the Images are implemented for the Video block. 
So including the Nested Grid Parent/Child items for the Video Container: https://github.com/bbc/simorgh/pull/1900/files

Splitting out the implementation into these files:
`containers/AudioVideo/index.jsx`
`containers/AudioVideo/amp.jsx`
`containers/AudioVideo/canonical.jsx`

Rename component `components/AudioVideo`.

Since we do not have a fully-functioning AMP video implementation yet, we will want to just return `null` in the index file if the amp video is requested. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Full regression test across multiple devices, for Canonical pages & ensuring no video-related content is on the AMP pages. 
Regression testing for this will also require looking at fallback images, non-JS and relevant response when viewing from non-UK/UK locations.

Refer to UK/non-UK acceptance criteria listed in this issue: https://github.com/bbc/simorgh/issues/868 

Test asset: https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo

Accessibility testing notes for video: https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers  

Dev insight: Cypress tests will need to be added for canonical news article - this asset `c3wmq4d1y3wo` can be used for local and test. There is no live asset currently, so should use the `describeForLocalAndTest` block for the Cypress tests

Ensure the video being selected has global access e.g. video about ants `p01k6msm`. Test should check the video is on the page and can be interacted with (clicked on).

**Comment by sareh** [comment]
Blocked on all other Video issues: https://github.com/bbc/simorgh/issues/134 https://github.com/bbc/simorgh/issues/868

**Comment by 12** [comment]
An article with a working video asset on test can be found here: https://www.test.bbc.co.uk/news/articles/c92y12zwyz8o

**Comment by oluoluoxenfree** [comment]
Whoever picks this up should make sure to also experiment with the `GridItem` sizes, as that was also not picked with UX.
