### ISSUE TITLE
Localhost to show International version

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1736]
**Is your feature request related to a problem? Please describe.**
When on localhost, you can only see the UK variant of the page.

Due to the way the [`getOriginContext`](https://github.com/bbc/simorgh/blob/af741b24b53c3a9e40385bc50509424437fd3ee0/src/app/contexts/RequestContext/getOriginContext.js#L15-L17) logic is defined, when on localhost, `isUK` is always `true`, even if you're viewing the page outside of the UK (or via VPN). 

This makes it difficult for testers to test PRs for the international variants locally, on their machines. 

We should enable our application to show the International variant.

**For testing**
UK version of cookie banner:
<img width="350" alt="Screen Shot 2019-05-17 at 15 56 34" src="https://user-images.githubusercontent.com/3028997/57937534-05ec4380-78be-11e9-92b2-e1be8a858bb5.png">

International version of cookie banner:
<img width="350" alt="Screen Shot 2019-05-17 at 16 15 22" src="https://user-images.githubusercontent.com/3028997/57937968-03d6b480-78bf-11e9-86b0-fa20ef4f2ab6.png">

**Describe the solution you'd like**
We could update `getOriginContext.js` to show the international variant locally. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests and testing locally should be sufficient. 

**Additional context**

**Comment by PriyaKR** [comment]
Needs an investigation to find an simple way of doing this may be something like a query string override or environment variable override.

**Comment by rossgaskell** [comment]
Hi @sareh, what are your thoughts about using localhost.bbc.co.uk/.com to trigger this behaviour?

**UK**
<img width="1039" alt="Screenshot 2019-05-24 at 13 43 56" src="https://user-images.githubusercontent.com/21201639/58329108-a77a1480-7e2b-11e9-8642-37c5578f1b84.png">

**International**
<img width="1039" alt="Screenshot 2019-05-24 at 13 44 29" src="https://user-images.githubusercontent.com/21201639/58329109-a77a1480-7e2b-11e9-84c8-00002cff9aae.png">

**Comment by sareh** [comment]
@rossgaskell I think it would be good. I like that it mimicks the `www.test.bbc.co.uk` `www.test.bbc.com` variants. 
So long as it is documented as a recommended way of using the application - we should have notes in the readme about running `http://localhost.bbc.co.uk/:7080` & `http://localhost.bbc.com/:7080`.
