### ISSUE TITLE
Security: Do not dump the error message back to the user on a 500 error

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#1740]
**Is your feature request related to a problem? Please describe.**
When a server is working (aka it has started) the code currently dumps the resulting error message in plaintext back to the user.
```
  .get(articleRegexPath, async ({ url, headers }, res) => {
    try {
      const data = await loadInitialData(url, routes);
      const { status } = data;
      const { service, isAmp } = getRouteProps(routes, url);
      const bbcOrigin = headers['bbc-origin'];

      res
        .status(status)
        .send(
          await renderDocument(url, data, routes, bbcOrigin, service, isAmp),
        );
    } catch ({ message, status }) {
      // Return an internal server error for any uncaught errors
      logger.error(`status: ${status || 500} - ${message}`);
      res.status(500).send(message);
    }
  });
```

Thanks to our internal BBC middleware we are protected from showing this for some time. However this is still a big information vulnerability. It is good that we are indeed logging the error message but we should never pass back this message back to the user.

**Describe the solution you'd like**
- In an event of a failure the server should render and return the failure page
- **Never** return any internal exceptions to the user
- The error message should still be logged

**Testing notes**
[Tester to complete]

Dev insight: Unless we induce the server to gracefully fail there is no way to create an automated tests for this edge case. We might have to inject invalid code onto the test environment and see how the application will handle it. However the investment necessary to test this might be too great for the return. As long as a generic error page gets returned we should be fine. 

**Additional context**

**Comment by PriyaKR** [comment]
Might need a little bit of investigation that how mozart handles this scenario ie)will there be any fallback handled by mozart.

**Comment by ryanmccombe** [comment]
Had a look at this and was able to reproduce just by doing `throw new Error()` in any component, but fixing it probably needs input

Errors that happen in React-land could be handled just with a high level wrapper that implements componentDidCatch, and falls back to the existing `ErrorMain` page

However, ErrorMain has context dependencies (eg, `service`, `translations`) that might not be populated if the error occurs quite early in the request handling process

For those errors, eg an error that happens in the `try catch` pasted above, we might need a simpler error page, or heavily modify ErrorMain to make it fall back if the config isn't available, eg, to still work even if something like `getRouteProps` throws

**Comment by chris-hinds** [comment]
> Had a look at this and was able to reproduce just by doing `throw new Error()` in any component, but fixing it probably needs input
> 
> Errors that happen in React-land could be handled just with a high level wrapper that implements componentDidCatch, and falls back to the existing `ErrorMain` page
> 
> However, ErrorMain has context dependencies (eg, `service`, `translations`) that might not be populated if the error occurs quite early in the request handling process
> 
> For those errors, eg an error that happens in the `try catch` pasted above, we might need a simpler error page, or heavily modify ErrorMain to make it fall back if the config isn't available, eg, to still work even if something like `getRouteProps` throws

@ryanmccombe componentDidCatch is a good idea i.e. React error boundaries however at present these lifecycle methods do not work when server side rendering.

A quick solution here be to simply redirect to the static error pages served by Mozart?

**Comment by dr3** [comment]
@hindsc52  I dont we should rely on the mozart error page redirect, simorgh should handle this itself. IMO we should serve a static string or static html file and log all the error stuff
