### ISSUE TITLE
Refactor Figure Container

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1742]
~~Blocked on https://github.com/bbc/simorgh/pull/1734~~

**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/pull/1734, the articles figure now has lazy loading

**Describe the solution you'd like**
Refactor figure, so there is little to no code duplication between https://github.com/bbc/simorgh/blob/31d42b176e4f7e6d66d18beaa44f1d3ec78435c1/src/app/containers/Figure/index.jsx and https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/Figure.jsx

Obs frontpage doesnt need figure element wrapper, caption or copywriter elements, but they can be turned off via props which should be fine. Most likely outcome is https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/Figure.jsx gets removed, and Story Promo uses `src/app/containers/Figure/index.jsx` as well

**Testing notes**
[Tester to complete]

Dev insight: Manual regression, storybook and snaps

**Additional context**

**Comment by greenc05** [comment]
@dr3 "Obs frontpage doesnt need a **figure**, caption or copywrite, but they can be turned off via props which should be fine. Most likely outcome is... " Are we using the correct terminology here? Story promo wouldn't use a figure html element...

**Comment by dr3** [comment]
Good spot @greenc05, updated

**Comment by greenc05** [comment]
Also why do we reference a file called 'figure.jsx' for storyPromo if it doesn't use a figure? Should 'figure.jsx' be more appropriately named?
