### ISSUE TITLE
WS Preprocessor - Filter out empty sections (groups)

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1753]
To avoid any issues with CPS feeds, to disable a section on the page, we have decided the journalist can just remove all stories from its section.

**Describe the solution you'd like**
Taking in CPS homepage index data, create a preprocessor rule that deletes groups from the data if they contain 0 items

An example of a preprocessor rule can be found [here](https://github.com/bbc/simorgh/blob/9fa9eb596a3eae1d6d6d1e87eab344e9ee9db472/src/app/lib/utilities/preprocessor/rules/topstories.js). TL;DR, take in json, split out json 

**Testing notes**
[Tester to complete]

Dev insight: Unit tests

**Comment by ghost** [comment]
I need more clarity on this. I am a little bit confused. We have the index data as 
```
{
  content: {
    groups: [
      {
         type: 'the type',
         items: [{ name: 'item name' }]
      }
    ]
  }
}
``` 
Do we delete the `groups` prop when it has no objects in it or do we delete an `item` from the group if it has no objects in it.

**Comment by dr3** [comment]
@sadick254 if a 'group' (object in the groups array), contains 0 things in its `item` array, remove the group from the `groups` array
