### ISSUE TITLE
Video - iframe for AMP variant

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1757]
**Is your feature request related to a problem? Please describe.**
For Video for AMP pages, we need to use an iframe and load in the SMP media player (via an 'embed' endpoint). 
 
There is separate work that is being carried out to update our embed endpoints to work with our data.  This issue is to just get an iframe working for the Video container, with a single example URL.

**Describe the solution you'd like**
- Investigate usage of `react-iframe`: https://www.npmjs.com/package/react-iframe#usage
- Pair with UX to determine width/height values. 
- Use an example video such as `https://www.bbc.co.uk/news/uk-politics-46827301/embed/p06w3lfm?amp=1` for testing purposes.

**Describe alternatives you've considered**
N/A

**Testing notes**
Cross-browser testing for the iframe, across devices.

Dev insight: Unit tests should be sufficient.  This work should just check that the iframe exists on the page. 

**Additional context**
N/A

**Comment by oluoluoxenfree** [comment]
As @rossgaskell pointed out, we should be using the amp-iframe or amp-video-iframe components. From the description it sound like we should be using the latter. 

https://github.com/bbc/simorgh/pull/1774#discussion_r291913191
