### ISSUE TITLE
Investigate Image Fade In

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1762]
**Is your feature request related to a problem? Please describe.**
Following on from #1734, UX have suggested investigating adding a fade to ease an image into its container when the image is lazyloaded. An example can be found [here](https://www.bbc.co.uk/news/uk-48368346) by scrolling down the page and observing the fading in of images as they are lazyloaded.

UX context - during user research it was found that often users scroll quickly through the page. We'd like to improve this experience.

**Describe the solution you'd like**
When the image component is lazyloaded, we should ease it into the page with a fade. UX should be involved with the timings of this. 

Investigate several options and present with gifs/videos showing the alternatives & review with UX.

**Testing notes**
Regression testing, checking performance isn't negatively impacted. 
Browser testing to ensure the fade in is working in multiple browsers. 

Dev insight: Visual regression cross device / browser.

**Comment by sareh** [comment]
Current implementation in #1734 loads in like this:
![lazyloaded image at top of page](https://user-images.githubusercontent.com/3028997/58320250-29117880-7e13-11e9-97b0-8e19ff1f360b.gif)

**Comment by rhenshaw56** [comment]
### Findings for Image fade in

[`react-lazyload`](https://www.npmjs.com/package/react-lazyload) offers better performance for lazyloading images but images pops into view so fast abruptly which doesn't seem so good from a UX point of view. 

**Possible Solutions**
1. We could add a CSS fade-in transition naturally, but it would overridden by the lazy loading and images would still pop in just the same.
2. Write a wrapper using any of the many npm packages used to apply a fade-in effect (there's really loads of them)

The approach which I think would best suit our use case would be to make use of the [`react-transition-group`](https://www.npmjs.com/package/react-addons-transition-group) library.
checkout [this link](https://bundlephobia.com/result?p=react-transition-group@4.1.0) for size info.

Testing this out using the [`react-transition-group`]()  library, I was able to get a smooth fade-in effect, by setting the fade in duration

```
const FADE_IN_DURATION = 700; // number in ms to apply the fade-in effect
```

```
const transitionStyles = {
  entering: { opacity: 0.2 },
  entered: { opacity: 1 },
  exiting: { opacity: 0.2 },
  exited: { opacity: 0 },
};
```
[`react-transition-group`](https://www.npmjs.com/package/react-addons-transition-group) offers transition states which is toggled via the inProp passed to the Transition component [see more](http://reactcommunity.org/react-transition-group/transition).


We would need to wrap the [`imageTorender`](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Figure/index.jsx#L13) prop in an image wrapper so we would be able to apply overlaying styles and track it's `onLoad` state using an image wrapper like (ideally, this could also be done in the image component in [psammead-image](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-image/src/index.jsx))

```
const ImageWrapper = styled.div`
  transition: ${() => `opacity ${FADE_IN_DURATION}ms ease-in-out`};
  opacity: ${props => props.opacity || 0};
`;
```

```
const renderImage = (imageToRender, lazyLoad, fadeIn, setFadeIn) =>
  lazyLoad ? (
    <Fragment>
      <LazyLoad offset={LAZYLOAD_OFFSET} once scroll>
        <Transition in={fadeIn} timeout={FADE_IN_DURATION}>
          {state => (
            <ImageWrapper
              {...transitionStyles[state]}
              onLoad={() => setFadeIn(true)}
            >
              {imageToRender}
            </ImageWrapper>
          )}
        </Transition>
      </LazyLoad>
      <noscript>{imageToRender}</noscript>
    </Fragment>
  ) : (
    imageToRender
  );
```

Rest of the code...

```
const [fadeIn, setFadeIn] = useState(false);
```

```
...renderImage(imageToRender, lazyLoad, fadeIn, setFadeIn)
```

**Preview**


*for a fade-in duration of 500ms and opacities of 0 and 1*
![500ms](https://user-images.githubusercontent.com/25608386/59088987-f41c2000-8900-11e9-983b-1c6d42cf81f3.gif)

*- for a fade-in duration of 700ms and opacities of 0.2 and 1*
![700ms](https://user-images.githubusercontent.com/25608386/59089461-0f3b5f80-8902-11e9-9521-f542167e1dc2.gif)

**Comment by nataliesmart** [comment]
Have just reviewed this with Sareh. My preference would be a fade 0-1, and think it could be a faster fade, perhaps 200ms. Thanks.

**Comment by 12** [comment]
Hey @rhenshaw56, thanks for this awesome write up. Do you have a branch where we can check this out locally?

**Comment by rhenshaw56** [comment]
Hi @rhell, thanks. I just committed and pushed up a branch [here](https://github.com/rhenshaw56/simorgh/tree/investigate-image-fade-in)
