### ISSUE TITLE
Video - AMP - Add embed endpoint

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1764]
**Is your feature request related to a problem? Please describe.**
Following the work to add the iframe to video for AMP variants: https://github.com/bbc/simorgh/issues/1757, and the work required to generate the embed endpoints (being carried out by the off-Forge team), we should use the correct embed endpoint in the url. 

**Describe the solution you'd like**
- We should use a url of the form:
`https://www.bbc.co.uk/news/av/embed/:pid/:articleId?statsAppName=news&statsAppType=amp&statsCountername=news.articles.c0000000000o.page&statsDestination=NEWS_PS_TEST&uiLocale=en-GB`

*Query parameter names to be confirmed with the team generating the embed endpoint URL*

Prior to this work being carried out, we'll need an example URL made available by the off-Forge team.

- Definition of done: 
  - have a video loading and working in the iframe with the embed endpoint
  - the video should have all of the correct attributes relating to the video asset. 
  - it should pass correct stats attributes to the SMP media player and stats should be logged in ATI on Test. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Both unit tests and Cypress tests should be added. 

**Additional context**

**Comment by 12** [comment]
This has been completed, therefore this issue is no longer needed.

https://www.test.bbc.co.uk/ws/av-embeds/c3wmq4d1y3wo/p01k6msp/amp?morph_env=test
