### ISSUE TITLE
Import and pass locale for new moment locales

### ISSUE THREAD

**Issue by amywalkerdev** [bbc/simorgh#1772]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by j-pendlebury** [comment]
Duplicate of https://github.com/bbc/simorgh/issues/1663?

**Comment by amywalkerdev** [comment]
Seems so, I'll close this one
