### ISSUE TITLE
PropType errors in Front Page components

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1776]
**Describe the bug**
Required props are missing in some front page components. This includes the `id` prop for `PageWrapper` and `RequestContextProvider`, and `frontPageData.metadata.locators.optimoUrn` for `FrontPageMain`.

There is another invalid prop type in the Story Promo `canonical` story, with a string being passed through to `ratio` where a number is currently expected. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Launch Storybook
2. Click on Front Page `default`
3. Open developer tools
4. See console error for prop types.

**To do**
Investigate why this is happening, and decide to either do it, or make issues to resolve the issue

**Expected behavior**
There should be no prop type errors in the console when running storybook, or the main application.

**Screenshots**
![image](https://user-images.githubusercontent.com/7690572/58255997-1725cc00-7d66-11e9-93a4-2ccd6aa4be0f.png)

![image](https://user-images.githubusercontent.com/7690572/58256118-4f2d0f00-7d66-11e9-9e07-84f799c0aa4a.png)

**Comment by DenisHdz** [comment]
We are wrongly using the [`articleDataPropTypes`](https://github.com/bbc/simorgh/blob/latest/src/app/containers/FrontPageMain/index.jsx#L25
) which requires the [`optimoUrn`](https://github.com/bbc/simorgh/blob/latest/src/app/models/propTypes/metadata/index.js#L12) and it is not in the FrontPage fixtureData.

**Comment by andrew-nowak** [comment]
> 'Warning: Failed prop type: Invalid prop `ratio` of type `string` supplied to `ImagePlaceholder`, expected `number`.'

https://github.com/bbc/simorgh/blob/85c8989f2370144b35e8a26ec73807e1d065d658/src/app/containers/StoryPromo/Figure.jsx#L19

`Number.toFixed()` returns a string, not a number -- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

**Comment by andrew-nowak** [comment]
> Warning: Failed prop type: The prop `id` is marked as required in `PageWrapper`, but its value is `undefined`.

https://github.com/bbc/simorgh/blob/85c8989f2370144b35e8a26ec73807e1d065d658/src/app/Layouts/defaultPageWrapper.jsx#L54

https://github.com/bbc/simorgh/blob/85c8989f2370144b35e8a26ec73807e1d065d658/src/app/routes/regex/index.js#L9

https://github.com/bbc/simorgh/blob/85c8989f2370144b35e8a26ec73807e1d065d658/src/app/routes/getInitialData/utils/getRouteProps.js#L11

For articles, the `id` prop is passed in from the matches in the route regex. But the frontpage doesn't have an id, so can't pass one to the PageWrapper

**Comment by andrew-nowak** [comment]
I believe the errors listed in this ticket will be resolved in #1783, or have a more specific issue raised in #1785 and #1786, and that this investigation ticket can now be closed.
