### ISSUE TITLE
Image copyright e2e test failing on live

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1777]
**Describe the bug**
One e2e test in `newsBodySpec.js` is failing on live but not on test, e.g.:
```
  1) Article Body Tests should have an image copyright label with styling:
     CypressError: Timed out retrying: expected '<p.Copyright-sc-11lgtw-0.eqxQmp>' to contain undefined
```
see https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh-infrastructure/detail/latest/32/pipeline/

**To Reproduce**
Build and release latest on Jenkins.

**Screenshots**

![Screenshot 2019-05-23 at 14 56 06](https://user-images.githubusercontent.com/11161809/58258588-ebf1ab80-7d6a-11e9-8787-11add3f5d5b5.png)

**Additional context**

**Comment by pjlee11** [comment]
Fixed as part of https://github.com/bbc/simorgh/pull/1780
