### ISSUE TITLE
Add Security Policy to Simorgh

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1778]
**Is your feature request related to a problem? Please describe.**
Github have released an enhancement to some security features. A new addition is the 'Security Policy'. This involves adding a new `.github/SECURITY.md` file that documents how contributors and the open source community can report security advisories in a discreet manner to the Simorgh code owners. More information regarding this new feature can be found [here](https://help.github.com/en/articles/adding-a-security-policy-to-your-repository).

Once merged, the security policy would be visible [here](https://github.com/bbc/simorgh/security/policy).

To be decided: contact e-mail address to use and any further details to include.

**Describe the solution you'd like**
A security policy written to `.github/SECURITY.md` to indicate to users how to report security advisories to repository maintainers.

**Testing notes**
[Tester to complete]

Dev insight: No testing required as this is not a code change. Maybe a sanity check that the policy makes sense once created.

Whoever is picking this up would need to do a investigation on what should go inside the `security.md` file.

**Comment by 12** [comment]
Github provide this as an example template:
```
# Security Policy

## Supported Versions

Use this section to tell people about which versions of your project are
currently being supported with security updates.

| Version | Supported          |
| ------- | ------------------ |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | :x:                |
| 4.0.x   | :white_check_mark: |
| < 4.0   | :x:                |

## Reporting a Vulnerability

Use this section to tell people how to report a vulnerability.

Tell them where to go, how often they can expect to get an update on a
reported vulnerability, what to expect if the vulnerability is accepted or
declined, etc.

```

**Comment by sareh** [comment]
- We should link to this file, which has the BBC-wide responsible disclosures procedure: https://www.bbc.co.uk/.well-known/security.txt 
- We should discuss what our processes are for responsible disclosures of Security issues regarding our Simorgh application
Here are best practices for what to include in our policy, by the Snyk team: https://snyk.io/blog/ten-git-hub-security-best-practices/
- We should document it in a SECURITY.md file, for example: `https://github.com/alphagov/.github/blob/master/SECURITY.md`
