### ISSUE TITLE
Cypress tests shouldn't access array data using index numbers

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1784]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/issues/1777 we should change all cypress tests to access array's using the new `getBlockByType` function. This means that any use case of `array[0]` should be changed to access the item by it's `type` using the aforementioned function.

**Describe the solution you'd like**
Changes all occurrences in the cypress tests that access array's using index values.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: the cypress tests should pass regardless of the array items order in the data payload. Could be checked by changing the local fixture data

**Additional context**
This is high-priority to stop a situation like https://github.com/bbc/simorgh/issues/1777

**Comment by jamesbhobbs** [comment]
Can find no such examples
