### ISSUE TITLE
Pull in new version of psammead-copyright

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1788]
**Is your feature request related to a problem? Please describe.**
Pending completion and merge of https://github.com/bbc/psammead/issues/552, we should update Simorgh to pull in these changes, so that we can ensure the copyright component can be positioned correctly depending on service.

**Describe the solution you'd like**
Pull in the latest version of `psammead-copyright`, and write some logic to tell the component where it should be positioned within the `Figure` container.

1) add `dir` field to the Service Configs for News/Persian, etc. They should have values `ltr` / `rtl`.
2) use the value in the Copyright Container. 
3) pass in prop 'right' to Copyright component if text direction `rtl`, and 'left' if text direction is `ltr`. 

Note: that if the image copyright is owned by the BBC, we have logic to not include the copyright component at all.  

We should have Storybook examples for all variants. 

**Testing notes**
Checking Storybook examples as well as full pages: 
http://localhost:7080/news/articles/cn7769kpk9mo
http://localhost:7080/persian/articles/cwv2xv848j5o

Dev insight: Unit tests, (snapshot tests) and storybook.

**Comment by jamesbhobbs** [comment]
@rhell there's no reason listed as to why this is blocked.

**Comment by 12** [comment]
It's blocked because this is the issue created to pull changes made in bbc/psammead#552 into Simorgh, as mentioned a the start of this issue:

>Pending completion and merge of bbc/psammead#552

I thought it'd be better to create the issue to pull it into Simorgh now, than to forget about it in the future.
