### ISSUE TITLE
Insert Simorgh translations & config for Igbo, Yoruba & Pidgin

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1789]
We have the translations - link on Jira ticket. 

Error pages work - Core Pod
Cookie Banner work - Articles pod
Footer work - Front pages pod covered by Footer Milestone
Navigation - Front pages pod covered by Navigation Milestone

**Is your feature request related to a problem? Please describe.**
To make use of all the nice error pages etc in simorgh, we need translations!

**Describe the solution you'd like**
Add translations for the 3 services in simorgh, following the values in https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/news.js#L25-L106

We also need the localised values for https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/news.js#L11-L23

**Testing notes**
[Tester to complete]

Dev insight: Storybook, showing things like the error pages.

**Comment by j-pendlebury** [comment]
Work to be done in individual issues for each piece of work
