### ISSUE TITLE
Link within Text block

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#179]
**Is your feature request related to a problem? Please describe.**
Render a link within a text block. This should include default styles as well as correct hover-focus styles. 

**Describe the solution you'd like**
There should be an anchor link with hover and focus styles, using styled-components. 

**Additional context**
- Will need to have all accessibility requirements addressed, working closely with a UX designer.
- Will likely need to add e2e tests, working closely with a QA tester.

<img width="493" alt="screen shot 2018-08-10 at 10 47 15" src="https://user-images.githubusercontent.com/3028997/43951347-d276ee02-9c8a-11e8-9445-db3d59f0de6b.png">

link colour: `#0F556C`, `Bluejay`

visited link colour: `#5C5752` `Pebble`

hover link colour: `#0F556C`, `Bluejay`
hover link text background: `#C3DEE7`, `Bluejay-Light`

focus link colour: `#C3DEE7`, `Bluejay-Light`
focus link text background: `#0F556C`, `Bluejay`

**Comment by greenc05** [comment]
@sareh should this cover external links as well?

**Comment by jamesbhobbs** [comment]
@greenc05 they're being handled separately (there is another jira ticket for them), this issue will treat all links the same.

**Comment by jtart** [comment]
This is now duplicated.
