### ISSUE TITLE
Add Manifest.json and Images for WS sites

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1790]
Images found in WSFRONTPGS-66

**Is your feature request related to a problem? Please describe.**
We need to generate and create manifest.json files for our 3 new services `Igbo, pidgin & Yoruba`

**Describe the solution you'd like**
1) Create a manifest.json file for each service in the style of [existing ones](https://github.com/bbc/simorgh/blob/latest/public/persian/manifest.json)
2) Ensure the manifest.json can be accessed via `/{service}/articles/manifest.json`
3) Add required images [to match existing ones](https://github.com/bbc/simorgh/tree/latest/public/persian/images/icons)

NB: the manifest uses live URLs like `https://news.files.bbci.co.uk/include/articles/public/persian/images/icons/icon-72x72.png`, untill we upload them, they wont exist on this domain. Its fine to merge this in 1 go, with the expectation they will work after merge.

NB: The manifest url of `/{service}/articles/manifest.json` isnt suitable for us, This will however be fixed in a later issue :)

**Testing notes**
[Tester to complete]

Dev insight: Manual testing, maybe a cypress test?

**Comment by david-boydell** [comment]
Hi @dr3, I checked this out and the files look fine. The only question I have is something to do with routing, with this checked out when I hit http://localhost:7080/igbo I get a 301 redirect to `/igbo/`, this then gets a 404.

I saw in the manifest `"Scope": "/igbo/",` and didn't know whether this was a factor. There was a question about the routing with trailing slashed in https://github.com/bbc/simorgh/pull/1810, not sure if this is something we need to address.
