### ISSUE TITLE
Insert default brand image for WS services

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1791]
**Is your feature request related to a problem? Please describe.**
We need a default image for our 3 new WS simorgh services

**Describe the solution you'd like**
Into config, like [existing services](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/persian.js#L8) add the following images under the key `defaultImage`

https://news.files.bbci.co.uk/ws/img/logos/og/igbo.png
https://news.files.bbci.co.uk/ws/img/logos/og/yoruba.png
https://news.files.bbci.co.uk/ws/img/logos/og/pidgin.png

**Testing notes**
[Tester to complete]

Dev insight: None, this wont work yet due to its use in metadata

**Comment by david-boydell** [comment]
Nothing to verify here as this cannot be tested, see dev insight. Once we have a fuller page this will be verified.
