### ISSUE TITLE
Discuss the scope/introduction of Enzyme testing for Styled Components

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#180]
**Is your feature request related to a problem? Please describe.**
Currently there is a set of end-to-end tests that checks for the validity of the CSS that is outputted by the React Components. Issue #132 introduces a styled component into the core component, which raises a posibility of testing the CSS at the unit test level. By using Enzyme and Jest-Styled-Components there is a way of snapshot unit testing the component. This could be very useful for quickly testing that components that are being modified are correctly styled. The team should therefore decide on the direction (if any) of testing styled components.

**Describe the solution you'd like**
This is up for team discussion. However some preliminary points have been raised:
Advantages:

- Core component features can be tested quickly and efficiently
- Early detection of possible styling errors
- Testing different theming options would be easier

Disadvantages: 

- Testing everything can cause huge snapshot balooning, making the tests useless becuase noone will bother to check 500 snapshots for errors
- Test duplication: css unit tests could be testing the same css rules tested in e2e

**Comment by jamesbhobbs** [comment]
There being duplication between unit tests and e2es is of no concern to me (efficiency of e2e tests is a long-term concern), they serve different purposes and different masters. But yet again, good issue, I look forward to discussing it soon @DemonusPC

**Comment by jamesbhobbs** [comment]
^^^ seems that's all that's required

**Comment by DemonusPC** [comment]
So we are doing it then?

**Comment by jamesbhobbs** [comment]
@DemonusPC yeh I've moved it to CR
