### ISSUE TITLE
Add unit tests to Front Page Main

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#1800]
**Is your feature request related to a problem? Please describe.**
The `FrontPageMain` doesn't have 100% test coverage.

**Describe the solution you'd like**
We should add unit tests with assertions (rather than snapshots) to the `FrontPageMain`.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests

**Additional context**

**Comment by j-pendlebury** [comment]
Are unit tests a requirement for v1? 
Can we go live with no unit tests for v1?
What is the priority for this work?
@jamesdonoh @benjaminhobbs

**Comment by jamesbhobbs** [comment]
@jblaut Yes, no, extremely high (respectively). NB you don't need 100% coverage, you need good tests and coverage around 80% (as a guideline).

**Comment by dr3** [comment]
This will be in simorgh, but similar in implementation to https://github.com/bbc/psammead/pull/663
