### ISSUE TITLE
Create new Persian Article on TEST

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1802]
**Is your feature request related to a problem? Please describe.**
Create a new Persian article on TEST, which will enable us to implement an inline link on the Persian articles.

**Describe the solution you'd like**
A new Persian article will be created on TEST, which will allow us to include an inline link within Persian articles. This will allow us to see the impact of RTL would have on the styling of inline links. This article should also include the following...

Video example
Audio example
Sub-headline
Internal link
External link
English/Latin text
Italic fragments in text, caption, headline, subheadline blocks
Image

**Testing notes**
Article renders with a 200 response.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Comment by jimjohnsonrollings** [comment]
ID on test: c19v65z3lg5o
