### ISSUE TITLE
Accessibility swarm on the Front Page

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#1808]
**Is your feature request related to a problem? Please describe.**
Carry out a team accessibility swarm for the `Front Page` with all the disciplines once the `StoryPromo`, `StoryPromoList`, `SectionLabel`, `Navigation`, `Brand` and `Footer` are completed.

**Describe the solution you'd like**
Go through the [accessibility checklist](https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers) and fix any issue we might face.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by DenisHdz** [comment]
Blocked on ~~[#560](https://github.com/bbc/psammead/issues/560), [#558](https://github.com/bbc/psammead/issues/558), [#559](https://github.com/bbc/psammead/issues/559), [#558](https://github.com/bbc/psammead/issues/558) and [#614](https://github.com/bbc/psammead/issues/614)~~

**Comment by dr3** [comment]
This was done today and all issues stemming from it have now been raised :) No P1's were found, and the P2's are very minor.

Closing as done.
