### ISSUE TITLE
Add npm install before test suite runs

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#181]
**Is your feature request related to a problem? Please describe.**
When merging in latest to a feature branch any changes to the package.json do not affect my local env until I run an npm install. This can cause situations were tests/linting seem to be passing but the local setup is out of date. 

This is a particular pain when precommit and prepush and run against your local setup and pass then on Travis the commit fails the tests.

**Describe the solution you'd like**
run npm ci as a prerequisite to npm test.

**Describe alternatives you've considered**
npm install instead of npm ci but this would also update the package-lock.json whereas npm ci will use the package-lock.json from latest.

**Additional context**

**Comment by jamesbhobbs** [comment]
I suppose the downside is that if package-lock.json on latest falls out of sync, it'll be harder to notice. I would suggest the npm install is used and then the user will see the lock change if there's any issue.

**Comment by pjlee11** [comment]
This could actually be solved using the githook `post-merge` to npm install any time that a git pull is run. Further details at https://git-scm.com/docs/githooks#_post_merge
