### ISSUE TITLE
Set up test profiles for ATI

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#1818]
**Is your feature request related to a problem? Please describe.**
Setting up test profiles/necessary steps for ATI tracking of testing and next steps for live page changes.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
WSFRONTPGS-22

**Comment by andrew-nowak** [comment]
We don't believe these are needed any more.
