### ISSUE TITLE
Canonicalise absolute URL

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#1819]
**Is your feature request related to a problem? Please describe.**
Ensure each relevant page is canonicalised to the absolute URL on new domain (canonicals to remain in Header)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
WSFRONTPGS-22

**Comment by dr3** [comment]
What new domain?
