### ISSUE TITLE
E2E tests for non JS output

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#182]
**Is your feature request related to a problem? Please describe.**
We should have E2E tests that run the headless browser within Cypress to ensure the server side rendered output is what we expect when the client device doesn't have JS.

**Describe the solution you'd like**
Check that all features which don't require JS render on a client device without JS.

**Comment by jamesbhobbs** [comment]
This isn't possible with cypress https://github.com/cypress-io/cypress/issues/1611
