### ISSUE TITLE
Investigate Sign In

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1821]
**Is your feature request related to a problem? Please describe.**
We need to investigate how we can bring sign in to Simorgh; supporting both canonical and AMP. 

Sign in is required due to future work relating to serving end-users with recommendations based on varying factors. However, questions have been raised with how this can work with our current AMP-first approach. It would be good early on to try and capture the complexities with sign in and the current application state.

**Describe the solution you'd like**
Ideally a rough solution demonstrating how we can bring BBC Sign In to the Simorgh application. We do not want this to be brought in via orbit, nor do we want to use `RequireJS`. 

The investigation should highlight problems and situations that remain unsolved.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Comment by pjlee11** [comment]
My main concern with this work is that we are aiming from a product perspective to "drive sign-in" but with development we follow an "AMP-first" approach. In the case of sign-in and how we rely on using `idcta` these feel like contradictory statements. 

We should also be speaking to other teams/departments about how the see `idcta` being implemented in the future. Will `idcta` be pulled out of Orbit as part of the  headless orbit work? Will it be recreated in react and loadable as a standalone bundle? Can we build the UI and just pull in the back-end of `idcta` as a set of helper functions for sign-in? 

This issue will require a lot of investigation and communication with teams within and outside of our department.
