### ISSUE TITLE
RTL text block

### ISSUE THREAD

**Issue by twinlensreflex** [bbc/simorgh#1822]
**Is your feature request related to a problem? Please describe.**
We want our text block to work for RTL articles (Persian, Arabic, Urdu, Pashto).

**Describe the solution you'd like**
As a result of https://github.com/bbc/simorgh/issues/2713, the NassimPersian font should be loaded for all 4 services and we should already have the text direction being right-to-left. This ticket is to ensure that the implementation matches the designs (except for it not using the correct service-specific font).

If the font sizes and line heights need updating, they should be discussed with UX design before implementing any changes `gel-foundations`

For each service we should import the Arabic typography settings from here: `import { arabic } from '@bbc/gel-foundations/scripts'` (this should already be done)

- [x] text block is RTL and matches UX designs (except for service-specific font)
- [x] Font size is 22px with line height 32px on all breakpoints

**Testing notes**
Will need to investigate if we can add tests to check RTL within Cypress. Otherwise it'll be a regression across browsers & devices.

- Check that regular and bold fonts are applied to the relevant text attributes & inline links within paragraphs. 

Dev insight: Snapshot unit tests should be sufficient

**Testing URL's**
https://www.test.bbc.com/arabic/articles/c69dvq19k63o
https://www.test.bbc.com/persian/articles/c4vlle3q337o
https://www.test.bbc.com/urdu/articles/cx621klkm1ro
https://www.test.bbc.com/pashto/articles/cng0e8v85eko

**Additional context**

**Comment by 12** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1910

**Comment by jamesdonoh** [comment]
No longer blocked on #1910; now blocked on https://github.com/bbc/psammead/issues/543

**Comment by jamesdonoh** [comment]
The above issue was closed, assuming this is now unblocked so we should try to pick up.

**Comment by jamesdonoh** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1822

**Comment by jimjohnsonrollings** [comment]
Blocked pending #2732

**Comment by nataliesmart** [comment]
Text-block type sizes:
Group A (0-319px): font size is 18px with line height 28px
Group B and D (320px +): font size is 22px with line height 32px

**Comment by jamesdonoh** [comment]
Unblocked following that bbc/psammead#1516

**Comment by RayNjeri** [comment]
Blocked pending #2713

**Comment by RayNjeri** [comment]
> Text-block type sizes:
> Group A (0-319px): font size is 18px with line-height 28px
> Group B and D (320px +): font size is 22px with line-height 32px

Checked as per the description and per the values specified here by @nataliesmart and everything seems to check off, both on Chrome and Firefox. Further UX review is welcomed.
cc: @jamesdonoh 
![Screen Shot 2019-08-13 at 11 34 40 AM](https://user-images.githubusercontent.com/27012452/62927077-7a038e00-bdbe-11e9-899a-be85c289e434.png)

**Comment by RayNjeri** [comment]
Same applies on live 
<img width="1440" alt="Screen Shot 2019-08-13 at 11 41 24 AM" src="https://user-images.githubusercontent.com/27012452/62927526-61e03e80-bdbf-11e9-841c-b8720dc25ea6.png">

**Comment by stevencava** [comment]
Current RTL text blocks look ok on desktop/mobile

**Comment by jamesdonoh** [comment]
Closing this issue as we believe the treatment on live is as expected, please reopen if not.

**Comment by nataliesmart** [comment]
Type specs on the links match those listed above. Thanks everyone.
