### ISSUE TITLE
ATI click tracking on simorgh

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1823]
**Is your feature request related to a problem? Please describe.**
For components going forward the explore pod (and likely the articles pod) want click tracking on front end components. I believe this may be something the core team will look into. To be extended...

**Describe the solution you'd like**
There should be a solution for ATI click tracking that allows components to implement click tracking. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
@pjlee11 Do we know what tags will be needed for this?

**Comment by pjlee11** [comment]
@jimjohnsonrollings will likely have more details on click tracking with ATI

**Comment by jimjohnsonrollings** [comment]
Not me.  @lizcameron is looking at it :)

**Comment by dr3** [comment]
Cooli, popped blocked on this for now, pending product info about click tracking requirements :)

**Comment by dr3** [comment]
This is being done by https://github.com/bbc/simorgh/issues/2788

**Comment by mykeels** [comment]
Should I close this issue, since it's been done in https://github.com/bbc/simorgh/pull/3559 ?
