### ISSUE TITLE
Canonicals are wrong

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1836]
**Describe the bug**
On the current live article on .co.uk, the canonical URL is .co.uk.  This is wrong.  The canonical should always be .com.

**To Reproduce**

1. Go to https://www.bbc.co.uk/news/articles/c744mjrym37o
2. View source
3. Search for "canonical"
4. Observe that it says .co.uk

**Expected behavior**
Canonical URL should always be .com

**Comment by sareh** [comment]
Logic in the Metadata Container should be updated & relevant unit tests updated/added https://github.com/bbc/simorgh/blob/latest/src/app/containers/Metadata/index.jsx#L48

We should update the amp canonical url to also be using `.com`. 
Cypress tests should be updated too. https://github.com/bbc/simorgh/blob/latest/cypress/integration/metaNewsSpec.js#L102 
https://github.com/bbc/simorgh/blob/latest/cypress/integration/metaPersianSpec.js#L61
https://github.com/bbc/simorgh/blob/latest/cypress/integration/ampSpec.js#L74
