### ISSUE TITLE
Typography for text components 

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#184]
**Is your feature request related to a problem? Please describe.**
We should have our typography sizes available in our application, to be used by the Headline, Subheading, and Text blocks, as well as any future blocks that render text. 

**Describe the solution you'd like**
To use the values set out in GEL Typography, for consistency with other BBC products. 
See these pages for details on the Typography settings (type name, font-size and line-height at different breakpoints):
https://github.com/bbc/gel-typography/blob/master/lib/_settings.scss#L76-L285
http://www.bbc.co.uk/gel/guidelines/typography#type-sizes

Initially only include types that are required (`canon` for h1, `double-pica` for h2, `great-primer` for h3, `pica` for h4 and body text, `brevier` for timestamps, category identifier, caption text). 

**Describe alternatives you've considered**
An alternative could be to not use the GEL typography types with sizes at different breakpoints, but this will likely not be approved by UX.

**Comment by greenc05** [comment]
@sareh have we considered if we are going to specify font-sizes in pixels or relative units? For accessibility we should probably be using relative units rather than pixels... https://medium.com/@vamptvo/pixels-vs-ems-users-do-change-font-size-5cfb20831773

**Comment by jamesbhobbs** [comment]
@greenc05 I'd assumed relative, @sareh agree?

**Comment by greenc05** [comment]
Just checking as the above file references px values... https://github.com/bbc/gel-typography/blob/master/lib/_settings.scss#L76-L285 Our current use of gel typography via the Morph components outputs px and rem, I assume we do that incase the browser doesn't support rem and if the browser does, it will ignore the px value? .gel-canon{font-size:28px;font-size:1.75rem;
