### ISSUE TITLE
Add simorgh to BBC Open Source pages

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1849]
**Is your feature request related to a problem? Please describe.**
The new BBC Open Source page will launch soon (see http://www.test.bbc.co.uk/opensource). We should add some information to it about Simorgh in order to promote the project and seek greater community involvement.

**Describe the solution you'd like**
Open PR against https://github.com/bbc/opensource-2018 to add info about simorgh to `content/projects`.

Info to add: TBC

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
Chatted to the opensource people about this, they said we can put simorgh on it (and on the frontpage of it) but we need an Image. @benjaminhobbs any ideas?

**Comment by jamesbhobbs** [comment]
@dr3 well obviously this for simorgh and psammead: https://www.dvdizzy.com/images/m-p/phoenix05.jpg if we need one each then psammead: https://www.clubdesmonstres.com/best/img/5enfantsetmoii.jpg and simorgh can use the image of both: https://www.dvdizzy.com/images/m-p/phoenix05.jpg I believe these images are copyright of BBC, can't see any other mentions, anyhow it's clear tribute/parody so probably not claimable as breach of copyright.

**Comment by thekp** [comment]
on the front page use this image: https://www.dvdizzy.com/images/m-p/phoenix05.jpg

link psammead with this image: https://www.clubdesmonstres.com/best/img/5enfantsetmoii.jpg

we can replace WRAITH on the homepage with Simorgh
and add psammead as an entry on a different page.

**Comment by oluoluoxenfree** [comment]
Closing as my PR has been merged!

**Comment by oluoluoxenfree** [comment]
This ticket requires some design work - aka a new set of images to represent simorgh and psammead - and for those to be put into the site in a new PR. We are unable to use the current pictures due to copyright concerns.

**Comment by amywalkerdev** [comment]
Found proof that we do have the copyright for these images, Chris to update the Open Source team

**Comment by chris-hinds** [comment]
Simorgh is now live on the BC OpenSource page https://www.bbc.co.uk/opensource/
