### ISSUE TITLE
Whitespace added beneath each Story Promo on Feature phone FF48

### ISSUE THREAD

**Issue by david-boydell** [bbc/simorgh#1856]
Using Firefox 48 on feature phones adds a large amount of whitespace between each story promo. This has been observed on the Jio Phone the Nokia 8110, both of which use this browser.

**To Reproduce**

1. Navigate to a front page, currently options are http://localhost:7080/igbo, /yoruba or /pidgin
2. Scroll down to and past the first story promo

**Expected behavior**
There is 16px of padding between the first story promo and the second.

**Screenshots**
![20190530_124001](https://user-images.githubusercontent.com/36667923/58951446-1428d380-8789-11e9-93e4-d75f62d9d092.jpg)

**Featurephone (please complete the following information):**

- Device: Nokia 8110
- OS: Nokia_8110_4G
- Browser: Firefox
- Version: 48

**Additional context**
It's worth mentioning that I have checked this on Firefox 48 in browserstack and I have not been able to recreate.

**Comment by andrew-nowak** [comment]
Should be fixed by #1862 :)
