### ISSUE TITLE
Content Security Policy blocking mPulse beacon

### ISSUE THREAD

**Issue by rossgaskell** [bbc/simorgh#1857]
**Describe the bug**
The Content Security Policy is blocking the source of the mPulse beacon script.

**To Reproduce**
1. Ensure dial for mpulse is turned on
2. Wait 1 min for dial to propagate
3. Visit article on test (e.g https://www.test.bbc.co.uk/news/articles/c5v767l2l0zo)
4. Open DevTools console
5. See script loading error

**Expected behavior**
The script should be loaded and the beacon activated

**Screenshots**
![image](https://user-images.githubusercontent.com/21201639/58951701-b47ef800-8789-11e9-804a-20c1ca875033.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Firefox
- Version 67.0

**Testing**
- Check that error is no longer being generated
- Regression check the mpulse beacon is working as expected

**Additional context**

**Comment by jroebu14** [comment]
I believe we just have to merge the following CSP rules to our existing set of rules `script-src https://*.go-mpulse.net; img-src https://*.akstat.io; connect-src https://*.akstat.io https://c.go-mpulse.net;` as outlined here https://developer.akamai.com/tools/boomerang/#content-security-policy-(csp)

**Comment by dr3** [comment]
https://github.com/bbc/mozart-routing/blob/master/src/lib/mozart_routing/headers/simorgh_header.rb is where our current CSP lives :)

**Comment by PriyaKR** [comment]
Testing: @jroebu14 Seeing error message in the dev console related to content security policy when the mpulse dials are enabled.
![mpulse_beaco_enabled_error](https://user-images.githubusercontent.com/9802855/59684940-f6b92800-91d2-11e9-8463-c0b33d2a8f3c.png)

**Comment by dr3** [comment]
We have added all the CSP stuff listed here  https://developer.akamai.com/tools/boomerang/#content-security-policy-(csp)

Closing as done, will reopen if its broken on test, if it is, it will be a similar issue, but not the same
