### ISSUE TITLE
Analysis of bundle size optimisations

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1874]
**Is your feature request related to a problem? Please describe.**
We have open issues like https://github.com/bbc/simorgh/issues/1857 that were created to reduce our bundle size but carry their own risk.

We want to reduce bundle size and constrain growth but we need to know the most efficient way of expending this effort in terms of complexity, benefit and risk.

**Describe the solution you'd like**
- Analyse current bundle sizes and identify several possible optimisations (max. 5)
- Assess potential benefit (in KB) of each candidate along with complexity and risk (high/medium/low)
- Select candidate(s) to be worked on and create issue(s) for them, close anything else

**Describe alternatives you've considered**
We could just pick up https://github.com/bbc/simorgh/issues/1241 but we do not know if it's an optimal use of time and effort.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
The generic aim is good but there are issues to actively monitor it and since this was written we've made very good progress
