### ISSUE TITLE
Running e2e tests against TEST from developer machines gives false negatives

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#1875]
**Describe the bug**
```
     CypressError: cy.visit() failed because you are attempting to visit a second unique domain.

You may only visit a single unique domain per test.

Different subdomains are okay, but unique domains are not.

The previous domain you visited was: 'https://www.test.bbc.co.uk'

You're attempting to visit this new domain: 'https://www.test.bbc.com'

You may need to restructure some of your code to prevent this from happening.

https://on.cypress.io/cannot-visit-second-unique-domain
```

**To Reproduce**
Run `CYPRESS_APP_ENV=test npm run cypress` on a developer machine

**Expected behavior**
Not this.

**Comment by jamesdonoh** [comment]
Note from the error output this _may_ be related to TLD redirection - whoever picks it up should determine whether the problem exists both for UK- and non-UK based devs, and if it can be resolved for both.

**Comment by DemonusPC** [comment]
Yes it is definitely related to redirects and geo location. Will need to add some branching to the tests in order to change the behaviour of these tests if they are ran from dev machines in the uk
