### ISSUE TITLE
Relative timestamp unit test fails during the first 3 hours of every day

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#1885]
**Describe the bug**
The unit test 'ArticleTimestamp › should render two timestamps - published: date & time, updated: relative when both are today and < 10 hours ago' fails during the first 3 hours of the day locally and remotely due to the line in the test that sets the time back by 3 hours, invalidating the test as it ceases being the same day.

I don't think this is quite the same but is similar to tests it being dependent on timezone https://github.com/bbc/simorgh/issues/1855.

**To Reproduce**
Run tests between midnight and 3am (or change your system time).

**Expected behavior**
Test passes

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Suggest the person working on this fixes other tests and perhaps looks at the bug linked to above at the same time.

**Comment by billy-reilly** [comment]
@benjaminhobbs I think #1884 resolved this

**Comment by thekp** [comment]
I've reproduced the error on an old HEAD of latest and verified that it passes on current latest. 

@billy-reilly thank you for your contribution to the repository, I will close this issue now.

![image](https://user-images.githubusercontent.com/30599794/60164148-5fcf0b80-9790-11e9-8979-cdd525827b6f.png)
![image](https://user-images.githubusercontent.com/30599794/60165158-2b5c4f00-9792-11e9-9d62-cc5bc8a5db94.png)

**Comment by jamesbhobbs** [comment]
Nice, thanks @billy-reilly !
