### ISSUE TITLE
ESLint - Importing Dev Dependencies

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#1886]
Our ESLint config throws errors when dev dependencies are imported into code

As importing dev dependencies is legitimate in certain scenarios (eg, see referenced comment) we should update the rules to allow it in those scenarios

One possible solution: ESLint does support passing a glob of paths where importing dev dependencies is permitted

_Originally posted by @benjaminhobbs in https://github.com/bbc/simorgh/pull/1883_

**Comment by jamesbhobbs** [comment]
Accidentally pushed to latest here https://github.com/bbc/simorgh/commit/3fffc701c3d692571ee06a02d78fa532ecc9b889 have updated repo rules to prevent admins pushing to latest, can you check this PR and close this or revert if necessary please @ryanmccombe @jroebu14 @jamesdonoh Sorry :(

**Comment by jamesdonoh** [comment]
No obvious problems on `latest` so closing this.
