### ISSUE TITLE
Images don't work on IE11

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1895]
**Describe the bug**
Images do not load in IE11.

**To Reproduce**

1. Open IE11
2. Go to an article with an image
3. See images not load

**Expected behavior**
Images should load

**Screenshots**

**Desktop (please complete the following information):**
IE11

**Additional context**
Looks like it might be all the JS failing

**Comment by 12** [comment]
The cookie banner also is not displaying.

**Comment by jamesbhobbs** [comment]
I believe the issue is this https://stackoverflow.com/questions/52821427/javascript-babel-preset-env-not-transpiling-arrow-functions-for-ie11

**Comment by jimjohnsonrollings** [comment]
Replaced by https://github.com/bbc/simorgh/issues/1896 which the Core pod will pick up
