### ISSUE TITLE
Pull in the new arabic script for Persian article image caption

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#1904]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/psammead/issues/608 we need to pull in the new version of the gel-foundations to get the updated script values. 

**Describe the solution you'd like**
Bump the `gel-foundations` version to get the new typography values 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests and visual regression the page looking at closely at the caption typography.

**Additional context**
N/A

**Comment by jamesdonoh** [comment]
Unblocked, but is this still a valid issue @pjlee11 ?

**Comment by pjlee11** [comment]
Checking the article the typography is now correct, it is likely dependabot pulled through the changes
