### ISSUE TITLE
Use Nassim fonts for Persian

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1910]
**Is your feature request related to a problem? Please describe.**

As a user of BBC News Persian
I want to be able to read the text on the page
So that I can consume the content

As a user of BBC News Persian
I don't want to load font files for small amounts of text in other scripts
So that I don't use bandwidth unecessarily

Given I am on a Persian article
When I see text in Farsi
Then it is displayed in the BBC Nassim Persian font

Given I am on a Persian article
And there is a fragment in Farsi with a bold attribute
Then I see that fragment in BBC Nassim Persian bold

Given I am on a Persian article
And there is a fragment or other text in a Latin script
Then that text is displayed in the system sans font
And not in BBC Reith Latin

**Describe the solution you'd like**
- Use the font-faces for Nassim Persian introduced in https://github.com/bbc/psammead/issues/675 https://ws-downloads.files.bbci.co.uk/fonts/index.html#NassimPersian

- Persian articles should download Nassim Persian font files
- The correct font weight should be used on normal text / bold text
- There should be no Reith fonts loaded on Persian articles
- There should be no Nassim Persian fonts loaded on News articles 
- You can import the Nassim font faces from the latest version of the `psammead-styles` package: https://github.com/bbc/psammead/pull/676/files 

Test article: `http://localhost.bbc.com:7080/persian/articles/c4vlle3q337o`

**Describe alternatives you've considered**
N/A

**Testing notes**
Requires manual testing across page types and browsers - specifically older supported browsers.
Fonts should be loaded on both canonical and amp pages, with no errors in the console. 

Dev insight: Cypress integration tests & snapshot tests should be added/updated.

**Comment by sareh** [comment]
Blocked on this issue to add the font-faces to `@bbc/psammead-styles` https://github.com/bbc/psammead/issues/675

**Comment by sareh** [comment]
Blocked on this work to add this font domain to the CSP header list https://github.com/bbc/simorgh-infrastructure/issues/513

**Comment by sareh** [comment]
Note: the Mozart Headers have been deployed up to test (Mozart Routing Release 1240) but not yet to live. So any PR relating to this issue should not be merged until that has been deployed first - otherwise we'll have console errors on the Live environment.

**Comment by ryanmccombe** [comment]
@sadickisaac is already working on this as part of this issue: https://github.com/bbc/psammead/issues/543

Closing this

**Comment by dr3** [comment]
This issue was closed prematurely, however ive made https://github.com/bbc/simorgh/issues/2503 to do the bit that was missing :)
