### ISSUE TITLE
Browser tests for analytics behaviour

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1926]
**Is your feature request related to a problem? Please describe.**
As part of the work that we are currently doing to implement analytics (https://github.com/bbc/simorgh/issues/1310) we will have unit test coverage for things such as the `amp-analytics` configuration and `noscript` image tag for canonical.

However we need to ensure that we also have sufficient coverage for scenarios such as:

- Is one (and only one) page view event sent for initial page load?
- Is one (and only one) page view event sent for client-side navigation?

These cannot be tested using unit tests but are likely to require a browser environment to test with any confidence.

Such coverage will also help us ensure that our fix for https://github.com/bbc/simorgh/issues/1919 behaves as intended.

**Describe the solution you'd like**
Find a way of implementing appropriate test coverage for the above, for example by stubbing the network requests in Cypress or similar.

Note that we should not write Cypress tests covering every aspect of the analytics, only the things that cannot be covered effectively by faster/simpler tests (e.g. unit tests)

**Describe alternatives you've considered**
We could ignore this requirement but we would not know if we started double-reporting page views or not reporting them at all.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
This should be tested upon every page's implementation. I doubt this could possibly be missed by other streams of work if it were wrong.
