### ISSUE TITLE
Localhost urls not testable on browserstack(ios)

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#1929]
**Is your feature request related to a problem? Please describe.**
Noticed the javascript files are not being requested on localhost urls(on devices) while using  browserstack especially ios and also browserstack always redirects localhost on ios to  http://bs-local.com

Because of this issue the images on the articles page are never been displayed on ios devices which would mean we may sometime overlook the issue and merge PRs when there is an actual issue with the PR.

Related information [https://www.browserstack.com/question/758](https://www.browserstack.com/question/758)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
<img width="313" alt="localhost_urls_BS" src="https://user-images.githubusercontent.com/9802855/59501288-1bd82e80-8e93-11e9-9643-7fa09350b46e.png">

**Comment by jamesbhobbs** [comment]
Cannot fix would be more accurate. We need to add ad hoc envs for this. You could alternatively ask engineers to release things behind a feature toggle and then you could test on test.bbc.com.
