### ISSUE TITLE
Github Slack notifications update

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#193]
**Is your feature request related to a problem? Please describe.**
Update the Github Slack notifications for Simorgh, to be less verbose. This is because the alerts currently post the title, description text and status of tests (for a PR).

**Describe the solution you'd like**
Ensure that for new PR and new Issue notifications, only the headline is posted, with none of the description text.

**Comment by jamesbhobbs** [comment]
Discussed offline. Summary: The default solution is verbose but it works and we shouldn't spend time rewriting what works, even when it's annoying.
