### ISSUE TITLE
AMP Images dont render in Story Promo without Grid 

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1931]
**Describe the bug**
When on devices without grid, like IE11, AMP images dont render. This is likely because the psammead placeholder div doesn't hold its own shape, meaning AMP doesnt think its visible, so doesnt render the image.

This doesnt happen on canonical because the image takes its own space. It does however mean image placeholders never show without grid.

**Describe the solution you'd like**
Fix it

**Testing notes**
[Tester to complete]

![image](https://user-images.githubusercontent.com/11341355/59453271-74fa8080-8e07-11e9-82a8-7faa58019a49.png)

Dev insight: Snaps and manual

**Additional context**

**Comment by dr3** [comment]
@EinsteinCarrey Hey, I can replicate this by visiting `http://localhost:7080/igbo.amp` in browserstack on IE11. You may need to install a browser extension to let browserstack hit your localhost

**Comment by EinsteinCarrey** [comment]
@dr3 I have investigated this issue. Apparently `<amp-img>` is not supported in IE an that's the reason why the images are not showing. My solution is to render images using `<img>`.
