### ISSUE TITLE
Move Video component from simorgh to psammead

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#1933]
**Is your feature request related to a problem? Please describe.**
The Video component should not be in this repo, it should be in bbc/psammead

https://github.com/bbc/psammead/blob/latest/CONTRIBUTING.md

**Describe the solution you'd like**
https://www.youtube.com/watch?v=hdcTmpvDO0I

**Describe alternatives you've considered**
None

**Testing notes**
[Tester to complete]

Dev insight: It's not currently used, so minimal.

**Additional context**
n/a

**Comment by sareh** [comment]
Blocked on https://github.com/bbc/simorgh/pull/1798

**Comment by jamesdonoh** [comment]
#1798 was merged so this can be picked up

**Comment by 12** [comment]
~Blocked on #2545~

**Comment by jamesdonoh** [comment]
Will be resolved by https://github.com/bbc/simorgh/issues/2614 since there will no longer be any AV components in Simorgh (some AV code will remain in Simorgh such as the `AudioVideo` container).
