### ISSUE TITLE
Move ConsentBanner component from simorgh to psammead

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#1934]
**Is your feature request related to a problem? Please describe.**
The ConsentBanner component should not be in this repo, it should be in bbc/psammead

**Describe the solution you'd like**
https://www.youtube.com/watch?v=hdcTmpvDO0I

**Describe alternatives you've considered**
None

**Testing notes**
[Tester to complete]

Dev insight: It's not currently used, so minimal.

**Additional context**
n/a

**Comment by thekp** [comment]
@benjaminhobbs do we have a roadmap for this component ?
(would be nice for the package readme)

**Comment by dr3** [comment]
@thekp can you make an issue to pull it back into simorgh and remove the old code please?

**Comment by thekp** [comment]
👍 I was gonna create a PR to link to this issue, but it closed automatically 👀
