### ISSUE TITLE
Use srcSet in WS Frontpages

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1935]
~~Blocked on https://github.com/bbc/simorgh/pull/1831~~

**Is your feature request related to a problem? Please describe.**
We currently load a 660px image for every WS frontpage image, this is not ideally as our images never even reach that size.

**Describe the solution you'd like**
Using/Adapting the `createSrcset` function found [here](https://github.com/bbc/simorgh/blob/87670059908e03184dc6765bcded678152deb012/src/app/containers/Image/helpers/srcSet.js) and used [here](https://github.com/bbc/simorgh/blob/f1afcb471ec55d095a29c21a24ee8c14c5fd189a/src/app/containers/Image/index.jsx#L54), add src set to ws frontpage images.

The image sizes used in srcset may not be perfect, if this is the case this can be optimised in a future issue.

**Testing notes**
[Tester to complete]

Dev insight: Unit tests

**Comment by ghost** [comment]
@dr3 This would need to be done in the `StoryPromo` container. But the `item` prop passed to `StoryPromo` does not include `originCode`. How do I go about it.

**Comment by dr3** [comment]
@sadick254 We get path `/cpsprodpb/3120/production/_107367521_177a9008.jpg` where I think `cpsprodpb` is the `originCode`, so maybe we can adapt it to work?

**Comment by ghost** [comment]
@dr3 What about the `locator`? is it `locators.assetUri`

**Comment by dr3** [comment]
@sadick254 I dont think so `path="/cpsprodpb/FFC1/production/_107437456_177a9008.jpg"` becomes
```
{
	originCode: "cpsprodpb"
	locator: "FFC1/production/_107437456_177a9008.jpg"
}
```
Just based the above off [this test](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Image/helpers/srcSet.test.js#L5-L13) (i think locator and location are the same thing)

The end result is a bunch of image URLS with different width values in the format of `https://ichef.bbci.co.uk/news/${width}/cpsprodpb/3120/production/_107367521_177a9008.jpg` using the `srcSet` function

**Comment by david-boydell** [comment]
This is ready to merge.
