### ISSUE TITLE
Re-enable WS cookie banner integration tests

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1937]
Blocking on routing to STMs

**Is your feature request related to a problem? Please describe.**
In https://github.com/bbc/simorgh/pull/1938, the World Service cookie banner integration tests were restricted to run on local env only, as the routing was not in place on our test environment. When the routing is in place, we should allow these tests to be ran on local **and** test environments.
 
**Describe the solution you'd like**
Allow these tests to be ran on local and test env's:
https://github.com/bbc/simorgh/blob/61d29a2729e372c7d8c75b4f24d93691451d5539/cypress/integration/cookieBannerWS.js#L13-L21

https://github.com/bbc/simorgh/blob/61d29a2729e372c7d8c75b4f24d93691451d5539/cypress/integration/cookieBannerWS.js#L27-L35
**Testing notes**
[Tester to complete]

Dev insight: Enabled cypress tests should pass

Make sure @david-boydell sees this before merge as he'll be iterating the tests in future

**Comment by EinsteinNjoroge** [comment]
@rhell Is this still blocked?

**Comment by jamesdonoh** [comment]
Assume this is now unblocked.

**Comment by 12** [comment]
Just be aware that there are still issues on some devices, so this could potentially still fail. As @jamesdonoh has said though, assume unblocked.

**Comment by david-boydell** [comment]
Hi @rhell, @jamesdonoh,

Could you clarify what I should see as a result of the routing ticket (mentioned in the description)? I'm looking at https://www.test.bbc.com/mundo but this is the old style frontpage.

~@rhell Can you also let me know what you mean when you say _issues on devices_? What devices do we mean, also what issues might I expect to see?~

~At the moment all cookieBannerWS tests are failing on https://github.com/bbc/simorgh/pull/2547 when run against test.~ I can see why some if the tests are failing so will look at amending those.

**Comment by jamesbhobbs** [comment]
Have updated the PR with a response on what's needed
