### ISSUE TITLE
Layout fix for vertical video

### ISSUE THREAD

**Issue by oluoluoxenfree** [bbc/simorgh#1939]
**Is your feature request related to a problem? Please describe.**

Vertical video is being rendered, but the SMP player is the wrong size and shape. 

**Describe the solution you'd like**
To have the correctly sized and shaped video player for vertical video, we need to add relevant CSS classes to constrain its contaning div.

We should re-use the styles being introduced in this PR: https://github.com/bbc/simorgh/pull/1900/files#diff-acb5631872636e1f2d49f017bbf81646R57 

Vertical image iChef recipes are of the form `640xn` - where you specify just the width e.g. 640px. 
e.g. `http://ichef.test.bbci.co.uk/images/ic/640xn/p01mxrbn.jpg`

For this reason, we are blocking this ticket on completion of the image layout work. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Vertical video layout should be identical to portrait image in UX spec.

Dev insight: Should work in storybook with fixture data. Unit tests. It will not work on the Test/Live environments until this work by Ares is complete: #2198

**Additional context**

**Comment by sareh** [comment]
Blocked on this integration ticket: https://github.com/bbc/simorgh/issues/1733

**Comment by twinlensreflex** [comment]
I think this can be closed? pretty sure the work has been completed in #1733
