### ISSUE TITLE
Pidgin/Yoruba/Igbo error pages

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1948]
**Is your feature request related to a problem? Please describe.**
We need to implement error pages (404,5xx) for Pidgin, Yoruba and Igbo front pages. The designs should be the same as for the English ones.

Fonts required for each service are listed in the fonts spreadsheet.

Depends on https://github.com/bbc/simorgh/issues/1947

**Describe the solution you'd like**
Ensure that localised error pages are returned for the services listed above when needed.

**Describe alternatives you've considered**
Not localising error pages but this is a poor user experience.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by sareh** [comment]
Discussing with Natalie, we should have the same Reith font for these three services as is used for News. We should just check all relevant translations are being used.

**Comment by dr3** [comment]
>we should have the same Reith font for these three services as is used for News

@sareh is this right? We dont use reith for their homepages, they use Helmet https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap#L77

**Comment by sareh** [comment]
You're right - the relevant font-families should be included for each service (not Reith). Just the line-height and font sizes will be the same (latin script with `@bbc/gel-foundations/typography` typography groups) for these three services.

**Comment by joshcoventry** [comment]
Replaced by new parent issue, will require refinement: https://github.com/bbc/simorgh/issues/7815
