### ISSUE TITLE
Persian error pages

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1952]
**Is your feature request related to a problem? Please describe.**
We already have some error page components for the Persian service (e.g. see https://bbc.github.io/simorgh/?path=/story/error-page--404-persian) but we need to make sure they are ready for use in production, such as by:

- checking them against the latest UX designs provided for Persian error pages
- ensuring they include the latest text according to the translations spreadsheet
- making them render text right-to-left.
- etc.

**Describe the solution you'd like**
As above.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by sareh** [comment]
Closed as fixed.
