### ISSUE TITLE
Console error received on latest branch for frontpages

### ISSUE THREAD

**Issue by david-boydell** [bbc/simorgh#1961]
**Describe the bug**
I am finding that we are getting console errors when looking at the `latest` branch (with `RouteSimorgh` merged in). The errors is `Warning: Failed prop type: Invalid prop `ratio` of type `string` supplied to `ImagePlaceholder`, expected `number`.`

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to /pidgin, /yoruba or /igbo
2. Open the Console in dev tools

**Expected behavior**
We should not receive any console errors on `latest`

**Screenshots**
![console-error](https://user-images.githubusercontent.com/36667923/59597463-d1a0b880-90f1-11e9-862d-adf234162490.jpg)

**Desktop (please complete the following information):**

- OS: OS X
- Browser Chrome, Safari, FF

**Comment by ghost** [comment]
Related to [1786](https://github.com/bbc/simorgh/issues/1786)

**Comment by ghost** [comment]
@david-boydell Could you please confirm if you are still getting the same error in your latest branch

**Comment by EinsteinNjoroge** [comment]
@david-boydell this issue has been resolved, I'm gonna go ahead and close this issue now.
