### ISSUE TITLE
Use new service worker route

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1966]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/pull/1965, we should use the new service worker route for the ws frontpages

| service | path |
|:--------|:-----|
| news | /service/articles/sw.js |
| persian | /service/sw.js |
| igbo | /service/sw.js |
| yoruba | /service/sw.js |
| pidgin | /service/sw.js |

https://github.com/bbc/simorgh/blob/latest/src/client.js#L21-L23

When doing this PLEASE do not import the service config into the client.js file, this will cause big problems that will immediately need to be refactored for bundle splitting

**Describe the solution option 1**
Do a `if (service === 'news') {} else {}` to decide which service worker URL to use 

**Describe the solution option 2**
Move the service worker install into the react application and pass `serviceWorkerPath` from the service context

**Testing notes**
Regression tests routes still work.

Dev insight: Unit tests

**Comment by sareh** [comment]
Of the two options, I personally prefer option 2 - using `serviceWorkerPath` from the Service config.

Also I'd like to suggest having the news ServiceWorker path also being on 	`service/sw.js`. Even though the News front page is unlikely to be moved over to simorgh, we could still have the news serviceworker available here. It would be good for consistency with the other world service news sites.

**Comment by dr3** [comment]
@sareh I agree with option 2

As for news using `service/sw.js`, I agree, depending on when this work is done (before/after we make an stm change through to live) we can include news :)

As it stands its unlikely this will happen after that, so for now I say keep news on /news/articles/sw.js :)

**Comment by EinsteinNjoroge** [comment]
@sareh @dr3 The challenge with **option 2** is that `navigator` is part of the `window` object which is only accessible on the browser. Given that we're using SSR, if we move service worker installation into the react application, we won't have access to the `window` object.
