### ISSUE TITLE
Vary `pageType` passed to RequestContext Provider

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1975]
**Is your feature request related to a problem? Please describe.**
Following the ATI work, we now have an idea of 'page type' in simorgh, however this is currently hardcoded to be `articles` [here](https://github.com/bbc/simorgh/blob/latest/src/app/Layouts/defaultPageWrapper.jsx#L18)

**Describe the solution you'd like**
Vary this, so It can be `articles`, `frontPage` or anything else we have in future.

End goal is the following code works, returning the correct page type.
```
const { pageType } = getContext(RequestContext);
```

Likely best to pair up with someone and discuss options before sinking time into this, as its likely going to be a opinionated decision :) Make sure to include the teams in the decision :)

**Testing notes**
Regression test ATI

Dev insight: Unit tests

**Comment by jamesbhobbs** [comment]
As discussed with Drew, I'd do handle this as we handle isUK here https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/getOriginContext.js but have a regex check on the route to get pageType value, which would need to be mapped somewhere.
