### ISSUE TITLE
Change localhost references in docs and code

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1976]
**Is your feature request related to a problem? Please describe.**

For our SMP implementation of Video to work locally, it needs to be on a page with URL `*bbc.co.uk*` or `*bbc.com*`.

We already have instructions for how to make `http://localhost.bbc.com:7080` & `http://localhost.bbc.co.uk:7080` work https://github.com/bbc/simorgh/blob/latest/README.md#changing-request-location

However, our docs all refer to http://localhost:7080 & our application is using this as well. 

**Describe the solution you'd like**
- Update docs to use `http://localhost.bbc.com:7080` or `http://localhost.bbc.co.uk:7080` according to whether they're World Service or a Public Service site (e.g. News)
- Update our scripts in package.json to use `http://localhost.bbc.com:7080`. 
- Update Cypress to use `http://localhost.bbc.com:7080`. 

**Describe alternatives you've considered**
If we don't make this change, we will not be able to have video working locally / on CI. 

**Testing notes**
Manually check README and that scripts still work.

**Additional context**

**Comment by chris-hinds** [comment]
With this in mind are we asking any open source contributors to also access the localhost environment via `http://localhost.bbc.com:7080`?

I get that we need this internally for video, but seems a little odd to ask everyone to set this up.
