### ISSUE TITLE
Fix tests - checking number of fonts on page

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1979]
**Is your feature request related to a problem? Please describe.**
Currently we have a Cypress test that checks for the number of fonts per page is under a threshold. 

This test is giving a false positive. 

We also pull in specific fonts into Global Styles: https://github.com/bbc/simorgh/blob/latest/src/app/lib/globalStyles.jsx#L27 We should add unit tests to ensure we're only pulling in fonts listed in the Service Config.

**Describe the solution you'd like**
- Update the Cypress tests. 
We should have a maximum of 6 font files downloaded for News and 2 for Persian. https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/news.js#L150-L157

- Update unit tests for Global Styles

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
https://github.com/bbc/simorgh/blob/latest/cypress/integration/metaNewsSpec.js#L28-L45
Yeah this test is odd, it doesn't check the number of fonts loaded, it checks the number of types of reith used in font families, which is `ReithSerif` or `ReithSans`

**Comment by jamesbhobbs** [comment]
This doesn't matter without /news
