### ISSUE TITLE
Add Simorgh signing 

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#1980]
**Is your feature request related to a problem? Please describe.**
Right now a build going our way does not contain any form of signature. This makes it harder for us to track down builds as they go through the pipeline. Creating a very simple script that notes the build numbers of the pipeline and the git commit would make the process of tracking builds much simpler. 

**Describe the solution you'd like**

Create a bash/python script that generates a text/json file containing the following information:
- CI build tag -> $BUILD_TAG
- Simorgh Git hash -> $GIT_COMMIT

A list of all Jenkins ENV variables can be found [here](https://wiki.jenkins.io/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables)

Also remember to include the resulting file in the artefact bundling script so that it can get passed down later on. 

**Describe alternatives you've considered**
Democracy is non negotiable

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by alex-magana** [comment]
Closing this as resolved via https://github.com/bbc/simorgh-infrastructure/issues/449
using PRs https://github.com/bbc/simorgh-infrastructure/pull/497 and https://github.com/bbc/simorgh/pull/1990

cc @DemonusPC
