### ISSUE TITLE
Should an ares 404 cause a simorgh 404? (ws fp)

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#1984]
**Is your feature request related to a problem? Please describe.**
A discussion around errors for the front page occurred earlier. When discussing with @dr3, current Simorgh logic would cause a 404 page to be shown if ares returns a 404. I suggest that this doesn't seem to be correct - if we `GET /pidgin` we should not return a 404, no matter what - that page should exist, and ares returning a 404 *is an ares error*.

Imagine the user flow - a user is on a pidgin article, clicks the 'BBC News | Pidgin' header, and sees a 'page not found' error page. 😱 

This is also probably an edge case that will never happen, so this is probably a `low-priority` ticket (if it should even remain open).

**Describe the solution you'd like**
If a request matches the frontpage regex, never 404.

**Describe alternatives you've considered**
Not bothering, because ares 404ing for a frontpage is a pretty :scream: scenario as it is

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
I think this could actually be really simple to implement, In [here](https://github.com/bbc/simorgh/blob/latest/src/app/routes/getInitialData/frontpage.js) we pass our version of the [upstreamStatusCodesToPropagate](https://github.com/bbc/simorgh/blob/latest/src/app/routes/getInitialData/utils/fetchData.js#L6) array to [fetchData](https://github.com/bbc/simorgh/blob/latest/src/app/routes/getInitialData/utils/fetchData.js). In FPs case it would just be `[200]`, anything else becomes a 502 to simorgh :)

**Comment by jamesbhobbs** [comment]
> If a request matches the frontpage regex, never 404

We can abstract this to "If a request matches any page regex where that regex has no :id/asset variable never 404 - this would cover all cases, e.g. subindexes too when they exist.

**Comment by thekp** [comment]
closing.

if this ever happens we will reopen this issue.
