### ISSUE TITLE
Integrate Chartbeat

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1987]
**Is your feature request related to a problem? Please describe.**
Following on from the completion of #1986, we should now integrate Chartbeat analytics into Simorgh. The table provided in the above issue contains the relevant information that we need to pass to Chartbeat.

**Describe the solution you'd like**
Chartbeat should work with both AMP and canonical articles. Using the utilities created in #1986, we should now be able to send a beacon to Chartbeat with the relevant data.

You can check that requests are being sent to Chartbeat by observing your network requests panel and looking for the domain `ping.chartbeat.com`.

As a result of this network request being made, you should then see real-time stats in your Chartbeat dashboard.

For any environment other than live, we should report to the domain `test.bbc.co.uk`.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Unit + Cypress tests

**Additional context**
Chartbeat docs: http://support.chartbeat.com/docs/
Chartbeat for AMP: http://support.chartbeat.com/docs/integrations.html#amp

Regarding single page applications, [Chartbeat docs](https://chartbeat.zendesk.com/hc/en-us/articles/360017557814-Integrate-Chartbeat-on-your-website) say:

> If your website makes use of dynamic page change, infinite scroll, or Single Page App architecture, you will need to implement our virtualPage function for Chartbeat to properly track these pageviews.

However, the [virtualPage documentation](http://support.chartbeat.com/docs/#ajax) states that it _should_ only be needed if the DOM does not update and/or the URL does not change. Therefore, I think we should be okay, but might need a little bit of investigation.
 
Chartbeat recommend placing the code to fire the beacon within the `head` of the page, and after the `rel="canonical"`.

I'd also recommend installing the [Chartbeat Heads-Up Display](https://chartbeat.zendesk.com/hc/en-us/articles/115001293233-Install-the-Heads-Up-Display-HUD-)

If you need Chartbeat access, speak to @jimjohnsonrollings

**Comment by jamesdonoh** [comment]
Now unblocked.
