### ISSUE TITLE
Investigate need for Apple IOS metadata tags

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2027]
**Is your feature request related to a problem? Please describe.**
We currently have ios images in the manifest.json, is that enough? We have a manifest json which should cover it, but is that used by everyone?

**Describe the solution you'd like**
Investigate support, and if needed, add the metadata tags required (use existing site and product guidance)

**Testing notes**
[Tester to complete]

Dev insight: If change needed, expand existing metadata tests

**Additional context**

**Comment by JonBeeb** [comment]
Some information on this is on iSite/News and Sport syndication configs/Service Meta Data

**Comment by dr3** [comment]
Based on https://github.com/bbc/simorgh/issues/734 we do need these, they will be added by https://github.com/bbc/simorgh/issues/2026
