### ISSUE TITLE
Reduce bundle size limit after bundle splitting

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#2029]
**Is your feature request related to a problem? Please describe.**
As a part of https://github.com/bbc/simorgh/pull/2028 we increased the bundle size entry point limit to 730kb.

**Describe the solution you'd like**
Once the bundle splitting work is completed and merged, we should be able to lower the bundle size entry point again.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
This is in effect mandated now as there's a lower and upper limit.
