### ISSUE TITLE
Snyk high vulnerability in webpack@4.34.0 & webpack-cli@4.34.0

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#2032]
**Describe the bug**
Snyk has identified a new high vulnerabilities in webpack@4.34.0 and webpack-cli@4.34.0

https://app.snyk.io/org/news-articles/project/35916eba-8cf2-4204-89f8-45455a5b9d95/

Note this vuln is not fixed in the latest version of webpack@4.35.0 or webpack-cli @4.35.0

**Comment by jamesbhobbs** [comment]
Fixed
