### ISSUE TITLE
Use plugin stylis-rtl to flip RTL layout of styles

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#2035]
**Is your feature request related to a problem? Please describe.**
Styled Components v5 beta has been announced https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987
It has support for including a plugin that will flip styles to work correctly for right-to-left. For example, it changes `margin-right: 0;` to `margin-left: 0;` and `float: left;` to `float: right;`. 
This is particularly useful for flipping styles for components. 

From the docs:
```jsx
import { StyleSheetManager } from 'styled-components';
import stylisRTLPlugin from 'stylis-rtl';

<StyleSheetManager stylisPlugins={[stylisRTLPlugin]}>
  <App />
</StyleSheetManager>
```

**Describe the solution you'd like**
- Use `styled-components5.0.0-beta.3` (or later beta, if available)
- Check how comprehensive the plugin is regarding CSS properties (does it flip: margin, adding, border, float etc.) 
- If service is RTL, use `stylisRTLPlugin`. 
- If service is LTR do not use this plugin.
- To test this: look at the consent banner, since this has right/left CSS logic. 

**Describe alternatives you've considered**
N/A

**Testing notes**
- Manual QA with Sareh to check the Persian RTL styling looks correct
- Check other RTL sites for correctness at the same time (Arabic, Pashto, Urdu)

Dev insight: Unit tests should be sufficient - we can separately look at cypress screenshots for page layout regression testing.

**Additional context**
N/A

**Comment by chris-hinds** [comment]
Blocked pending the release of styled-components v5 (non beta) https://github.com/styled-components/styled-components/releases

**Comment by sareh** [comment]
Closed since we're not going to be using stylis-rtl.
