### ISSUE TITLE
Update rawVideo data to include necessary properties

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#204]
**Describe the bug**
Currently, the `rawVideo` block in the data does not have the properties necessary to pass to the SMP media player, to load a video. 

**To Reproduce**
Look at example data for a rawVideo block and see that it doesn't have properties `versionId` & `kind` https://github.com/bbc/simorgh/blob/latest/data/test/scenario-09.json#L35-L39

**Expected behavior**
The RawVideo block to have these properties:
`versionId` for the video e.g. `p049sq7k`
`kind` of the video, e.g. `clip` or `programme`
`duration` should be of this format: a number, in seconds. e.g. `1009`.

We should update all the sample scenario data to include these properties.

**Comment by jimjohnsonrollings** [comment]
Proposed example block:
`{
  "type": "video",
  "model": {
    "locator": "urn:bbc:pips:pid:p01jvmg5",
    "blocks": [
      {
        "type": "aresMedia",
        "model": {
          "id":"p01jvmg5",
          "subType": "clip",
          "format": "audio_video",
          "versions": [
            {
              "versionId": "p01jvmg7",
              "versionType": "Original",
              "warnings": {},
              "duration": 43
            }
          ],
          "title": "Dramatic capsize in America's Cup yacht",
          "embedding": true,
          "advertising": false,
          "imageUrl": "ichef.test.bbci.co.uk/images/ic/$recipe/p01jvmms.jpg"
        }
      },
      {
        "type": "image",
        "model": {
          "blocks": [
            {
              "type": "rawImage",
              "model": {
                "width": 1280,
                "height": 760,
                "locator": "ichef.test.bbci.co.uk/images/ic/$recipe/p01jvmms.jpg",
                "originCode": "pips",
                "copyrightHolder": "Reuters"
              }
            }
          ]
        }
      },
      {
        "type": "caption",
        "model": {
          "blocks": [
            {
              "type": "text",
              "model": {
                "blocks": [
                  {
                    "type": "paragraph",
                    "model": {
                      "text": "Duis vitae ipsum hendrerit, commodo metus vel, mattis sapien. Proin eleifend vulputate porta. Curabitur mollis nunc nec felis ultricies, vitae tempor metus imperdiet."
                      "blocks": [
                        {
                          "type": "fragment",
                          "model": {
                            "text": "Duis vitae ipsum hendrerit, commodo metus vel, mattis sapien. Proin eleifend vulputate porta. Curabitur mollis nunc nec felis ultricies, vitae tempor metus imperdiet.",
                            "attributes": []
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  }
}`

**Comment by sareh** [comment]
Blocked pending updated `rawVideo` block implementation in Ares API response.

**Comment by jimjohnsonrollings** [comment]
Updated example:
`{
  "blockId" : "urn:bbc:ares::clip:p067gq6h",
  "type" : "aresMedia",
  "model" : {
    "id" : "p067gq6h",
    "subType" : "clip",
    "format" : "audio_video",
    "title" : "Mark and Isla Royal Wedding",
    "synopses" : {
      "short" : "Stop the press! It’s a Mark and Isla Royal Wedding special…",
      "medium" : null,
      "long" : null
    },
    "imageUrl" : "ichef.bbci.co.uk/images/ic/$recipe/p067grwg.jpg",
    "embedding" : true,
    "warnings" : { },
    "advertising" : false,
    "versions" : [
      {
        "versionId" : "p067gq6k",
        "types" : [ "Original" ],
        "duration" : 94,
        "availableTerritories" : {
          "uk" : true,
          "nonUk" : false
        }
      }
    ]
  }
}`
