### ISSUE TITLE
Duplicate keys for components

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#2061]
**Is your feature request related to a problem? Please describe.**
Currently we're using the text for fields for generating the keys for React components. If the text in two components of the page are identical, we get this error in the console:

<img width="930" alt="Screen Shot console error" src="https://user-images.githubusercontent.com/3028997/60000501-4b89f200-965c-11e9-9342-86292e5ddcb5.png">

You can see this when running `npm run storybook` and looking at examples with captions: http://localhost.bbc.com:9001/?path=/story/figure--with-a-caption

**Describe the solution you'd like**
- We should use UUID in addition to text for unique keys, to ensure that all components have unique keys

**Describe alternatives you've considered**
N/A - we're already using the `uuid` package as a dependency, so this usage would be more suitable. 

**Testing notes**
- Go to the storybook page (http://localhost.bbc.com:9001/?path=/story/figure--with-a-caption) and there should not be an error about duplicate keys.
- Update an article that has multiple paragraphs in a caption: make them have the same text in the multiple paragraphs - see no error about duplicate keys.

Dev insight: Existing unit tests should be updated. No integration tests required.

**Additional context**

**Comment by ryanmccombe** [comment]
We were previously generating keys as suggested using nanoid, but removed it as a performance optimisation

@sareh is there a real world use case for two items in the same list having the same text?  We assumed not, so implemented it like this, but we'd need to change it if that assumption is wrong

**Comment by sareh** [comment]
@ryanmccombe Good to know about the change of nanoid to uuid. I checked with Jim regarding likelihood of text being used in a caption, for example. He stated that it is possible and has happened in the past, so this change is needed.
