### ISSUE TITLE
Not setting a title

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#2064]
**Describe the bug**

![image](https://user-images.githubusercontent.com/10963046/60008244-a545e880-966b-11e9-8770-5b37992de8a0.png)

:scream:

**To Reproduce**

1. Open a page on test environment
2. There's no title

**Expected behavior**
There's a title.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox 67, Chrome 75

**Additional context**

**Comment by j-pendlebury** [comment]
None of the metadata is actually coming through. Could be an issue with the simorgh-infra build?

**Comment by j-pendlebury** [comment]
Title is now coming through as expected
![image](https://user-images.githubusercontent.com/13763899/60009559-01aa0780-966e-11e9-83b8-975b49df6384.png)
![image](https://user-images.githubusercontent.com/13763899/60009594-0ec6f680-966e-11e9-892d-3104d0b5e823.png)
