### ISSUE TITLE
lang = en-GB

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#2065]
**Describe the bug**
On all pages, the page lang is en-GB

**To Reproduce**
1. Open a non en-GB frontpage on the test environment
2. Open browser inspector
3. ![image](https://user-images.githubusercontent.com/10963046/60008774-90b62000-966c-11e9-80b6-b7fe927d7712.png)

**Expected behavior**
The page language is set to the appropriate language for the page

**Comment by j-pendlebury** [comment]
See https://github.com/bbc/simorgh/issues/2064#issuecomment-504937339

**Comment by sareh** [comment]
@aacn500 Value should be set to `lang` rather than `locale` - in many cases this is the same, but for News for example it's `en-GB` vs `en_GB`.

**Comment by j-pendlebury** [comment]
![image](https://user-images.githubusercontent.com/13763899/60009629-1c7c7c00-966e-11e9-9aec-c579bb9ccea2.png)
`lang` now comes through as expected
