### ISSUE TITLE
Story promo overlays the page

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#2071]
**Describe the bug**
On mobile devices such as iPhoneX, the viewport is overlayed by a link.
This behaviour is caused by the `::before` tag that set overlay over the single story promo, however that seems to leak out over the entire page.

**To Reproduce**

1. Go to https://www.stage.bbc.co.uk/yoruba on a mobile device
2. Click anywhere on the page without scrolling
3. You will be taken to an article (the article is the last article shown on the page)

**Expected behavior**
Click on a story, you will be taken to the story.

**Screenshots**
<img width="338" alt="image" src="https://user-images.githubusercontent.com/13763899/60019325-82283280-9685-11e9-9fdc-f66ccbe50f4c.png">
<img width="472" alt="image" src="https://user-images.githubusercontent.com/13763899/60019373-9ec46a80-9685-11e9-8048-66ae63d4dd3d.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/13763899/60019388-a4ba4b80-9685-11e9-901f-3ced562e4ccc.png">

**Smartphone:**

- Device: iPhoneX, iPhone5S, Samsung Galaxy S5
- Browser: Firefox, Chrome

**Additional context**
Checked with some other devices, like OnePlus6 and Pixel2, and the page works as expected.

Bug spotted on iPhoneX (real device). This was also checked in Chrome dev tools simulator with iPhone5S and Samsung Galaxy S5 settings. 
Checked with Pixel2 settings in Chrome dev tools as well.

**Comment by dr3** [comment]
Played with this locally using browser stack. Adding `position: relative` to StoryPromoWrapper will fix this :)
