### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#210]
**Is your feature request related to a problem? Please describe.**
Our test coverage is increasing due to saturation of components, the underlying core code (the app that isn't components) still has very poor coverage.

**Describe the solution you'd like**
Add tests.

**Describe alternatives you've considered**
Also add tests to our core deps such as razzle and after.js

**Additional context**
This can and probably should be done in many PRs.

**Comment by radiocontrolled** [comment]
@benjaminhobbs re: adding tests to core dependencies, would this mean for example, checking to see that ensureReady has been called with routes, by mocking this dependency and seeing if it is called?

e.g. in https://github.com/bbc/simorgh/blob/latest/src/client.js#L10
