### ISSUE TITLE
Fix psammead component linking issue

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2112]
**Is your feature request related to a problem? Please describe.**
Currently if you npm link psammead components to simorgh the styles for that component dont render on the server. This causes issues when we go to test our components.

**Describe the solution you'd like**
Fix the issue so `npm link ../psammead/packages/components/psammead-story-promo` works, and styles for the promo render on the server render.

**Testing notes**
Pair with dev to verify

Dev insight: Manual

**Additional context**

**Comment by jamesbhobbs** [comment]
Believed to be due to multiple versions of styled components being used concurrently.

**Comment by DenisHdz** [comment]
A hack to fix this is to
`cp -r ../psammead/packages/components/psammead-story-promo/dist ./node_modules/@bbc/psammead-story-promo/dist`

**Comment by andrew-nowak** [comment]
Refined by ws-fp pod, but we don't believe this is a high priority for our goal of getting front pages live.

**Comment by jamesbhobbs** [comment]
This should now be fixed as it's impossible to have duplicate packages on build.
