### ISSUE TITLE
Polyfills missing from dev server config

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#2117]
**Describe the bug**
The polyfills script that includes polyfills for IE10/11 for `map`, `set` and `symbol` is not included in the dev server config.

**To Reproduce**
1. Run the webpack dev server
2. On IE10, navigate to http://localhost:7080/news/articles/c6v11qzyv8po and run the debugger
3. Observe the `Set is undefined error` and things like lazy loaded images do not work.

**Expected behaviour**
No errors during debugging and things like lazy loaded images work.

**Comment by oluoluoxenfree** [comment]
@jroebu14 After adding the polyfill I still get `Unable to get property 'includes' of undefined or null reference`. Should I raise a new issue or try to fix it with this?
