### ISSUE TITLE
Create hydration cypress test

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2142]
**Is your feature request related to a problem? Please describe.**
Initial caused (and fixed) in https://github.com/bbc/simorgh/pull/1872, it is possible for the DOM to be wiped in the hydration process and immediately replaced with near identical elements.

While this generally cant be seen visually, it is bad for performance and should be avoided at all costs.

This was first spotted by @aacn500 by using the following code to spot the issue
```js
const serializer = new XMLSerializer();
const ser = serializer.serializeToString(root);
console.log(ser);
```

This was then confirmed by @dr3 using the following code to watch for removed dom nodes
```js
const rootChildren = Array.from(document.getElementById('root').children);

const callback = (mutationsList, observer) => {
  for (const mutation of mutationsList) {
    if (mutation.removedNodes.length > 0) {
      mutation.removedNodes.forEach(node => {
        if (rootChildren.includes(node)) {

        // ONE OF THE ROOTS CHILDREN HAS BEEN REMOVED!

        }
      });
    }
  }
};

const observer = new MutationObserver(callback);
observer.observe(root, { childList: true });
```

**Also:**
Can we test https://github.com/bbc/simorgh/blob/3be336fa5c2f794cbce31c74997674d581dd99a9/src/app/lib/config/services/index.js#L1-L6? It feels like its tested implicitly via the bundle splitting working, but could it be better?

**Describe the solution you'd like**
Write an automated test, most likely in cypress, to assert that during the hydration process dom nodes arn't removed.

To force the page to break (and start removing the elements) you can change the code in `simorgh/src/client.js` by commenting out the `Loadable.preloadReady` wrap.
```jsx
// Loadable.preloadReady().then(() => {
  hydrate(<ClientApp data={data} routes={routes} />, root);
// });
```

**Testing notes**
[Tester to complete]

Dev insight: N/A

**Additional context**

**Comment by jamesbhobbs** [comment]
Doing so in Puppeteer is also fine.

**Comment by amywalkerdev** [comment]
Can't reliably replicate the break so closing this for now
