### ISSUE TITLE
Get `Current page` translations

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#2153]
**Is your feature request related to a problem? Please describe.**
We need the `Current page` visually hidden text used in the Navigation translated for `igbo`, `pidgin` and `yoruba`.

**Describe the solution you'd like**
Update config files with the right translations (atm are in English):

Igbo:
```
    currentPage: 'Peegi ị nọ ugbua',
```

Pidgin:
```
    currentPage: 'Page where you dey',
```

Yoruba:
```
    currentPage: 'Ojú ewé to wà yìí',
```

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
Externally blocked on translation
