### ISSUE TITLE
Lighthouse and a11y and AMP validate tests not running against WS FPs

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2155]
**Is your feature request related to a problem? Please describe.**
These types of tests aren't running in CI or CD for WS FPs.

**Describe the solution you'd like**
At very least 1 of the WS FPs needs to be tested, ideally all three.

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
This is a blocker to release.

**Comment by jamesbhobbs** [comment]
NB we need to do this for release, we don't necessarily need a scalable way to handle this for release, but we should have this for when we have many more page types and services.

**Comment by dr3** [comment]
@benjaminhobbs Should this also include amp?

**Comment by dr3** [comment]
Lighthouse sollution? Add `test:lighthouse:frontpages` which is copy of `test:lighthouse` with a single frontpage url in it (gross i know)

Add `&& amphtml-validator http://localhost:7080/igbo.amp` to the end of `amp:validate`

**Comment by dr3** [comment]
Reopening to add test lighthouse runs

**Comment by jamesbhobbs** [comment]
..in CD

**Comment by dr3** [comment]
Need to update https://github.com/bbc/simorgh-infrastructure/blob/latest/scripts/run_lighthouse.sh

and /Users/mcmild07/dev/simorgh-infrastructure/scripts/evaluate_lighthouse.py

**Comment by chris-hinds** [comment]
We should look to using something like `https://github.com/mikestead/lighthouse-batch` this would allow to to pass a .txt file with a list of sites (page urls in our case) we can also then evaluate against the score for each individual page or against the summary report that it provides for each tested URL.

**Comment by dr3** [comment]
Agreed, this is purely a rush job issue though to get live, I think if we can adapt our current scripts easily we should for now
