### ISSUE TITLE
Improve script tag source for amp analytics

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#2156]
**Is your feature request related to a problem? Please describe.**
Raised this issue to address this comment: https://github.com/bbc/simorgh/pull/2105/files#r298190205

We currently define 4 script tags for AMP analytics: 
```
<script key="amp" async src="https://cdn.ampproject.org/v0.js" />
<script
   async
   custom-element="amp-geo"
   src="https://cdn.ampproject.org/v0/amp-geo-0.1.js"
   />
<script
   async
    custom-element="amp-consent"
    src="https://cdn.ampproject.org/v0/amp-consent-0.1.js"
/>
<script
   async
    custom-element="amp-analytics"
    src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"
/>
```

**Describe the solution you'd like**
These scripts are currently used in the following locations:
https://github.com/bbc/simorgh/blob/latest/src/server/Document/component.jsx#L52-L66
https://github.com/bbc/simorgh/blob/latest/.storybook/helpers/ampDecorator/index.jsx

A possible solution is to export the scripts independently in `packages/utilities/psammead-assets/src/amp-boilerplate.js` and then importing where required (see links above).

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
This may be an invalid issue, as we may require separate scripts, for this issue: https://github.com/bbc/simorgh/issues/1698

**Comment by dr3** [comment]
> This could be optimised by defining a single script that asnyc pulls all the required scripts from a single source.

I’m not sure I follow? Is this saying the client will download a single script, which then downloads the amp scripts?

**Comment by thekp** [comment]
> I’m not sure I follow? Is this saying the client will download a single script, which then downloads the amp scripts?

@dr3 
I created this issue a while back, I think this was just waffle I added. I've removed it for less confusion

**Comment by samora** [comment]
Added an `AMP_JS` constant to _amp-boilerplate_ in _psammead_assets_. PR is [here](https://github.com/bbc/psammead/pull/2433). 

Once published to NPM we can replace
```
`<script key="amp" async src="https://cdn.ampproject.org/v0.js" />
<script
   async
   custom-element="amp-geo"
   src="https://cdn.ampproject.org/v0/amp-geo-0.1.js"
   />
<script
   async
    custom-element="amp-consent"
    src="https://cdn.ampproject.org/v0/amp-consent-0.1.js"
/>
<script
   async
    custom-element="amp-analytics"
    src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"
/>
```
with
```
{ AMP_JS }
```
