### ISSUE TITLE
Lazyload images are not displayed in Opera Mini

### ISSUE THREAD

**Issue by david-boydell** [bbc/simorgh#2160]
**Describe the bug**
Lazyloaded images are not displayed on the Opera Mini browser. For the frontpage and article page we get the first image and then just placeholders.

**To Reproduce**

1. Open opera Mini on a mobile phone, change the Data Savings setting to be off
2. Navigate to either a front-page or articles page
3. Observe that only the first (non-lazyloaded) image is displayed, all other images display only the placeholder image.

**Expected behavior**
Images are displayed in Opera Mini, unless the Data Savings setting sets images to "Off"

**Screenshots**
![image](https://user-images.githubusercontent.com/36667923/60277031-aa699880-98f4-11e9-997d-b7b436ea8a59.png)

**Desktop (please complete the following information):**

- OS: Windows 7 & 8
- Browser: Internet Explorer
- Version: 10 & 11

**Smartphone (please complete the following information):**

- Device: Galaxy S8
- OS: Android 9
- Browser Opera Mini
- Version 43

**Comment by EinsteinNjoroge** [comment]
@david-boydell this seems to be working fine, I've tried it on multiple devices and it sems to work fine after reloading the page twice.
![Screenshot_20190718-153526_Opera Mini](https://user-images.githubusercontent.com/21374761/61461500-7aecff80-a979-11e9-9ea5-207ce7ad195d.jpg)
![Screenshot_2019-07-18-15-36-28](https://user-images.githubusercontent.com/21374761/61461517-817b7700-a979-11e9-9a9e-494f60475365.png)

**Comment by david-boydell** [comment]
Hi @EinsteinCarrey , sorry about that - I'm not sure went wrong. I can confirm it's also working for me now as well.
