### ISSUE TITLE
When a Heading block is immediately followed by a Subheading block, the space between them is a bit big

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#2162]
**Describe the bug**
When a Headline block (H1) is immediately followed by a Subheadline block (H2) there is 72px of vertical whitespace between them.  This feels a bit excessive, and looks odd as the timestamp isn't aligned with the H2 at wide.

**To Reproduce**

1. Go to https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo
2. Look at H1 and H2

**Expected behavior**
Less space - say 40px - so that it looks less weird.  We'll ask UX.

**Screenshots**
<img width="978" alt="Screen Shot 2019-06-27 at 17 21 31" src="https://user-images.githubusercontent.com/8124899/60282975-0dacf800-9900-11e9-9acb-3fdb40122439.png">

**Testing Notes**
- Accessibility testing required
- Regression tests across browsers

**Notes:**
If this is a psammead issue then we should probably move this to the psammead board.
Consult with other pods about vertical strategy.

This issue may be related: https://github.com/bbc/psammead/issues/408

**Comment by nataliesmart** [comment]
In this scenario, the space between the H1 and the H2 should be 56px. All subheads should have 56px above them. See screenshots.

**Comment by nataliesmart** [comment]
![Screen Shot 2019-06-28 at 09 49 27](https://user-images.githubusercontent.com/30656637/60330592-b1db8100-998a-11e9-87ed-0ee2cc197ceb.png)
![Screen Shot 2019-06-28 at 09 49 40](https://user-images.githubusercontent.com/30656637/60330593-b1db8100-998a-11e9-817d-51592f0b6f43.png)

**Comment by sareh** [comment]
This ticket is now blocked on https://github.com/bbc/psammead/issues/1431/

**Comment by RayNjeri** [comment]
Moving this back to externally blocked till the work on bbc/psammead#1431 is complete
