### ISSUE TITLE
Update Ares ichef locators for portrait ratios for video

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#2171]
**Is your feature request related to a problem? Please describe.**
Currently, Ares is populating the `locator` field for image placeholder assets from `mpv`.

For Landscape-oriented images, this is of the following format: 
`"ichef.test.bbci.co.uk/images/ic/$recipe/p01k6mtv.jpg",`
For portrait images it is currently the same. 

In this ticket we should update to use the format `$widthxn`
`"ichef.test.bbci.co.uk/images/ic/$widthxn/p01mxrbn.jpg",`

**Describe the solution you'd like**
We have requested Ares to update the locators that they provide us on the Test & Live environments. 

**Tasks:**
- We should ensure that our fixture data reflects this `$widthxn` for Portrait placeholders only. Add fixture data in the `data/test/news/articles/`
- Ensure that fixture data within the AudioVideo container includes the correct portrait locator. 
- We should ensure our Image placeholder for video reflects the designs in our Zeplin documentation.

**Describe alternatives you've considered**
We explored this option but discussed against it:
- We update the value ourselves in a preprocessor step - when type of media `portrait`.

Ticket blocked on https://github.com/bbc/simorgh/pull/2151

**Testing notes**
[Tester to complete]

Dev insight: Updating fixture data. Unit tests should be sufficient. Manually viewing a portrait video example in the browser.
Only testing localhost. It will be broken on Test and Live environments until this is complete: https://github.com/bbc/simorgh/issues/2198 

**Additional context**

**Comment by sareh** [comment]
Update from @jimjohnsonrollings: we're going down route 2: `We request Ares to update the locators that they provide us.`. 
- We should carry out the work, assuming the change has been made in Ares. 
- We should ensure that our fixture data reflects this
- We should ensure our Image placeholder for video reflects the designs in our Zeplin documentation.

**Comment by sareh** [comment]
Ticket blocked on https://github.com/bbc/simorgh/pull/2151

**Comment by jamesdonoh** [comment]
#2151 has been merged so this can be picked up

**Comment by jimjohnsonrollings** [comment]
NB We've asked Ares to do this at their end - so there shouldn't be anything for us to do except check it's worked.  I believe it's in their current sprint.

**Comment by jimjohnsonrollings** [comment]
Ok I've just read this properly.  What's said in the description is mostly valid.

The difference is that we've asked for all the video/audio placeholder URLs to have this change - not just portrait.

**Comment by RayNjeri** [comment]
Blocked pending work from Ares https://jira.dev.bbc.co.uk/browse/ARES-774

**Comment by jimjohnsonrollings** [comment]
Ares has now released this to test.

**Comment by jimjohnsonrollings** [comment]
We can see this on c3wmq4d1y3wo on test - so I think this issue just is for ensuring the fixture data matches and that we haven't broken anythin.
