### ISSUE TITLE
IE11 JS Failing - Vendor bundle has arrow function

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2178]
**Describe the bug**
A simorgh vendor bundle has an arrow function causing most older browsers (IE11 down) to throw error and not run JS

**To Reproduce**

1. Go to IE11
2. See console error

**Expected behavior**
Bundles are ES5 with IE10 supports

![image](https://user-images.githubusercontent.com/11341355/60353401-e1f24680-99c1-11e9-8bb7-3ae49f6b968c.png)

**Additional context**

**Comment by amywalkerdev** [comment]
Does #1897 resolve this?

**Comment by dr3** [comment]
Caused by https://github.com/bbc/simorgh/pull/2084

Which bumps `react-amphtml` (again)

**Comment by dr3** [comment]
>Does #1897 resolve this?

Not sure, but if it does I think we should do it differently, running babel on all node modules is generally not advised.
