### ISSUE TITLE
Create a welcome/starter guide for Simorgh

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#2182]
**Is your feature request related to a problem? Please describe.**
At the moment our documentation is spread out in many different sources. We need a single document that we can show to new recruits so that they can easily understand the purpose of Simorgh and how to work on it.

![](https://media.giphy.com/media/citBl9yPwnUOs/giphy.gif)

**Describe the solution you'd like**
Create a friendly starter guide that includes:
- our high level aims  
- any essential setup (installing node, etc)
- Links to other docs for further information or take information from that doc and place it here (i.e the project-board doc - `docs/Project-Board-Guide.md`)
- A list of people who are the code owners

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
If you have any more information to add, please do.

**Comment by jamesbhobbs** [comment]
What more do we want in this than what we have?

**Comment by thekp** [comment]
nothing, I believe we have an on-boarding doc (off github) now.
