### ISSUE TITLE
Add container story for BrandContainer

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#2194]
**Is your feature request related to a problem? Please describe.**
As we have moved components over to the Psammead component library, we have few items in our Simorgh Storybook: https://bbc.github.io/simorgh/

We should include our container components in the Simorgh storybook

**Describe the solution you'd like**
Update story to BrandContainer (on storybook) - showing different context values e.g. News/Persian examples

- [x] What would be ideal, would be to add a drop-down that could switch between services and populate these with the correct view. e.g. selecting Persian from the drop-down when looking at the BrandContainer will show you the News | Persian brand.
- [x] The containers relating to RTL services, (e.g. Persian and in future, other RTL services) should have the `dir="rtl"` attribute passed through to Storybook. Could be added via a Decorator, that gets the value of `dir` from the Service Context. 

See the implementation of this for the Psammead sitewide links component - https://bbc.github.io/psammead/?path=/story/components-sitewidelinks--default When you select `Persian` from the `language` dropdown, it loads links in the right language and adds the correct `dir` value too.

Brand story Container: https://github.com/bbc/simorgh/blob/latest/src/app/containers/Brand/index.stories.jsx

**Describe alternatives you've considered**
N/A

**Testing notes**
Regression of the BrandContainer

Dev insight: Cypress tests may need to be updated, if so pair with test

**Additional context**
We shouldn't need stories for all of our containers (e.g. Blocks, or Fragments) since these are for handling our Optimo data.

**Comment by pjlee11** [comment]
Refined by articles
