### ISSUE TITLE
Add container story for FooterContainer

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#2197]
~blocked: https://github.com/bbc/psammead/issues/757 and https://github.com/bbc/psammead/issues/770~

**Is your feature request related to a problem? Please describe.**
As we have moved components over to the Psammead component library, we have few items in our Simorgh Storybook: https://bbc.github.io/simorgh/

We should include our container components in the Simorgh storybook.

**Describe the solution you'd like**
Add story to Footer Container (on storybook)

- [x] What would be ideal, would be to add a drop-down that could switch between services and populate these with the correct view. e.g. selecting Persian from the drop-down when looking at the BrandContainer will show you the News | Persian brand.
- [x] The containers relating to RTL services, (e.g. Persian and in future, other RTL services) should have the `dir="rtl"` attribute passed through to Storybook. Could be added via a Decorator, that gets the value of `dir` from the Service Context. 

See the implementation of this for the Psammead sitewide links component - https://bbc.github.io/psammead/?path=/story/components-sitewidelinks--default When you select `Persian` from the `language` dropdown, it loads links in the right language and adds the correct `dir` value too.

Footer storybook container: https://github.com/bbc/simorgh/blob/latest/src/app/containers/Footer/index.stories.jsx

**Describe alternatives you've considered**

**Testing notes**
Regression of the FooterContainer

Dev insight: Cypress tests for Storybook may need to be updated, if so pair with test. 

**Additional context**
We shouldn't need stories for all of our containers (e.g. Blocks, or Fragments) since these are for handling our Optimo data.

**Comment by pjlee11** [comment]
Refined by articles.
