### ISSUE TITLE
Test Portrait video on the Test environment

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#2198]
**Is your feature request related to a problem? Please describe.**
Currently, portrait images in Ares data have locators of this format:
`"ichef.test.bbci.co.uk/images/ic/$recipe/p01mxrbn.jpg",`

Once the Ares team have updated the locators for image placeholders for video *portrait* images to this format:
`$widthxn` e.g.
`"ichef.test.bbci.co.uk/images/ic/$widthxn/p01mxrbn.jpg",`

We should check that it works on our Test & Live articles. 

**Describe the solution you'd like**
Testing ticket only

**Describe alternatives you've considered**
N/A

**Testing notes**
Regression of articles with portrait examples / storybook with portrait examples.
Can manually check this article that has a portrait video: `localhost.bbc.com:7080/news/articles/c0000000031o` Will be merged in as part of https://github.com/bbc/simorgh/pull/2151

Dev insight: Unit tests should be added/updated for portrait examples.

**Additional context**
Blocked on Ares work on Test/Live.

**Comment by lizcameron** [comment]
ARES team has now implemented this; placeholder images have $widthxn as the ichef recipe variable instead of $recipe.

**Comment by jamesdonoh** [comment]
Can't see any obvious issues with portrait video on test so closing this as not clear if any further work is needed at this stage.
