### ISSUE TITLE
Add a Jenkins pipeline copy file validator

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#2201]
**Is your feature request related to a problem? Please describe.**
In a recent webpack bundle splitting work we have ran into an issue of file differences in the jenkins file copying script. This caused a major failure on latest. This should not happen again.

**Describe the solution you'd like**
Create a script that compares the current file system with the list of files to copy. The script should:
- List the file differences between the current file system and the `agreed` file structure
- The script should output error code 1 if the files do not match (failing the pipeline)
- The script should provide a utility that can automatically update the `agreed` file

**Describe alternatives you've considered**
Democracy is non negotiable

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by chris-hinds** [comment]
no longer required
