### ISSUE TITLE
Consolidate FP tests all into one file (ati, body, meta and amp)

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2217]
**Is your feature request related to a problem? Please describe.**
Consolidate front pages tests in one spec file for all services

**Describe the solution you'd like**
Factor out test helpers into commands and use these in the single spec file

**Describe alternatives you've considered**
None, but I wouldn't try to do this in one PR

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
Part of https://github.com/bbc/simorgh/issues/2046

**Comment by dr3** [comment]
closing, done in https://github.com/bbc/simorgh/pull/3053
