### ISSUE TITLE
Make lighthouse tests more scaleable

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2219]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/issues/2155 we only run lighthouse tests on 1 article and frontpage, we should expand the logic to run them on multiple pages across services.

**Describe the solution you'd like**
Create a scaleable script to run lighthouse tests and assert the results for all canonical page types & services.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
This is to be done in our private infra repo
