### ISSUE TITLE
Make AMP Validate tests more scaleable 

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2220]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/issues/2155 we only run amp validate tests on 1 article and frontpage, we should expand the logic to run them on multiple pages across services.

**Describe the solution you'd like**
Create a scaleable script to run amp validate tests and assert the results for all canonical page types & services.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
@benjaminhobbs How many pages should we validate?

**Comment by jamesbhobbs** [comment]
@dr3 at least one of each page type, probably worth doing across a few services but probably not all, maybe 1 PS, 1 WS and the Japanese for GNL.

**Comment by chris-hinds** [comment]
This has been completed now.
