### ISSUE TITLE
Make A11y tests more dynamic

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2221]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/issues/2155 we run the a11y tests on a hardcoded array of urls, we should make this dynamic to run automatically on all available services and page types

**Describe the solution you'd like**
Make the a11y tests dynamic to run automatically on all available services and page types

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
NB add a test against a worst-case scenario example

**Comment by j-pendlebury** [comment]
Refined by WSFPs
