### ISSUE TITLE
Ensure e2es would catch broken local links

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2228]
**Is your feature request related to a problem? Please describe.**
E2e tests should check every link in every environment, and ensure we never get a 404 NB only check they're not 404, as we don't want to test if the pages we're pointing at are erroring (5xx) or not (2xx).

**Describe the solution you'd like**
Actually, test this, because we broke them all in https://github.com/bbc/simorgh/pull/2187 and tests still passed

Maybe iterate over all links and do a cy.request (quicker than clicking on them and coming back)

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
Related to https://github.com/bbc/simorgh/issues/2046 but this is more about missed coverage in tests

**Comment by PriyaKR** [comment]
As per discussion with @benjaminhobbs - the e2e tests should assert for every link on a page to ensure the link destination either gets a 2xx or a 3xx response.
