### ISSUE TITLE
Revise the intro in the primary readme so it's less article focussed

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2229]
**Is your feature request related to a problem? Please describe.**
We mention articles a lot and also put the mythology before the application explanation

**Describe the solution you'd like**
Revise the intro in the primary readme so it's less article focussed

**Describe alternatives you've considered**
n/a
**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by sareh** [comment]
Please also replace any acronyms we use (OSS, SPA, etc.) with the full text. 
The explanation of mythology / origins of the naming of this repo as Simorgh can be moved to the bottom of the readme.

**Comment by jamesbhobbs** [comment]
Done
