### ISSUE TITLE
Add all service configs

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2231]
**Is your feature request related to a problem? Please describe.**
We currently only have immediately needed configs

**Describe the solution you'd like**
Add all configs here https://github.com/bbc/simorgh/tree/latest/src/app/lib/config/services

**World Services:**
www.bbc.com/afrique
www.bbc.com/afaanoromoo
www.bbc.com/amharic
www.bbc.com/arabic
www.bbc.com/azeri
www.bbc.com/bengali
www.bbc.com/burmese
www.bbc.com/gahuza
www.bbc.com/gujarati
www.bbc.com/hausa
www.bbc.com/hindi
www.bbc.com/igbo
www.bbc.com/indonesia
www.bbc.com/korean
www.bbc.com/kyrgyz
www.bbc.com/marathi
www.bbc.com/mundo
www.bbc.com/nepali
www.bbc.com/pashto
www.bbc.com/persian
www.bbc.com/pidgin
www.bbc.com/portuguese
www.bbc.com/punjabi
www.bbc.com/russian
www.bbc.com/serbian
www.bbc.com/sinhala
www.bbc.com/somali
www.bbc.com/swahili
www.bbc.com/tamil
www.bbc.com/telugu
www.bbc.com/thai
www.bbc.com/tigrinya
www.bbc.com/turkce
www.bbc.com/ukchina
www.bbc.com/ukrainian
www.bbc.com/urdu
www.bbc.com/uzbek
www.bbc.com/vietnamese
www.bbc.com/yoruba
www.bbc.com/zhongwen

**UK News:**
https://www.bbc.co.uk/cymrufyw
https://www.bbc.co.uk/naidheachdan
https://www.bbc.co.uk/news

**Describe alternatives you've considered**
We could wait until we put config in a 3rd party service but I think we need to test the scalability of the app urgently.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
Part of https://github.com/bbc/simorgh/issues/2230

**Comment by gavinspence** [comment]
We're missing Japanese from the list of services @benjaminhobbs
