### ISSUE TITLE
Remove prop-types from production build

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2232]
**Is your feature request related to a problem? Please describe.**
Remove prop-types from production build.

**Describe the solution you'd like**
Use transform-react-remove-prop-types to remove prop-types from production build.
- remove the imports too, which is a conditional option

**Describe alternatives you've considered**
Maybe we should do this on psammead too?

**Testing notes**
Complete testing of front pages and articles pages required.

Dev insight: Could break everything if done wrong.

**Additional context**

**Comment by dr3** [comment]
>Maybe we should do this on psammead too?

I dont think so, as when running dev in simorgh its good to see prop warnings from components, we can ensure we strip them from psammead components in simorgh babel though

**Comment by dr3** [comment]
Weird it still pulls in some prop types stuff, tiny though
![image](https://user-images.githubusercontent.com/11341355/60881467-b41cc580-a23d-11e9-845a-f32a53730674.png)
