### ISSUE TITLE
Remove all AMP logic from bundle

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2233]
**Is your feature request related to a problem? Please describe.**
All our AMP logic is included in the bundle and therefore clientside render. This is completely wasteful in bundle size and JS execution time.

**Describe the solution you'd like**
Cut the AMP logic from the bundle on build

**Describe alternatives you've considered**
Perhaps a similar approach to the one taken by this library could be used: transform-react-remove-prop-types

**Testing notes**
Regression testing of amp pages.

Dev insight: no unit test changes required

**Additional context**
n/a

**Comment by ryanmccombe** [comment]
https://github.com/bbc/simorgh/blob/9f80f52ed8a683b931dbe5485db673b41816c0af/src/app/containers/ConsentBanner/index.jsx#L4

**Comment by FK78** [comment]
Closing issue as the added complexity of the solutions do not justify the actual savings.
