### ISSUE TITLE
Tree shake psammead packages

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2235]
Related psammead PR https://github.com/bbc/simorgh/pull/2062

**Is your feature request related to a problem? Please describe.**
Import psammead packages as ESM and treeshake them to remove unused variables, e.g. unused scripts from `gel-foundations`

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
<img src="https://camo.githubusercontent.com/d16c5bc4692bc2de7c2366b09751f739a5106a73/68747470733a2f2f696d352e657a6769662e636f6d2f746d702f657a6769662d352d3234363038316161653562642e676966" />

**Comment by thekp** [comment]
_Google'd tree shaking..._

> Tree shaking is a term commonly used within a JavaScript context to describe the removal of dead code. It relies on the import and export statements in ES2015 to detect if code modules are exported and imported for use between JavaScript files.

**Comment by dr3** [comment]
Closing as done
