### ISSUE TITLE
Brand Banner to be imported within Footer

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#226]
**Is your feature request related to a problem? Please describe.**
To duplicate the Brand Banner (currently the Header component and is the red BBC News banner). It should be at the bottom of articles, inside the footer. 

**Describe the solution you'd like**
- Banner should have similar link and touch-area behaviour. 
- It should use a `div` instead of a `header`
- It should be within the `footer` element. (`footer` should surround both this and the component below it)
- Should not have role="banner"
- The alignment of the logo should be different. See screenshots for banner at bottom:

![375_footer](https://user-images.githubusercontent.com/3028997/42102090-d994de40-7bbc-11e8-9976-9f334d9e267e.png)
![1280_footer](https://user-images.githubusercontent.com/3028997/42102098-dbaffc8c-7bbc-11e8-80a7-e0280669cf2b.png)

vs those of the header:
![375_header](https://user-images.githubusercontent.com/3028997/42102142-fb707588-7bbc-11e8-840d-d85bd0205c5e.png)
![1280_header](https://user-images.githubusercontent.com/3028997/42102144-fd39af9c-7bbc-11e8-9890-b8eb086ddccb.png)

**Acceptance Criteria**
> Given I view the footer
> When I hover on the brand logo
> Then brand logo must have a visible state change
> And it must not be identified by colour alone

> Given I view the footer
> When I navigate by keyboard
> And I focus on the brand logo
> Then brand logo must have a visible state change
> And it must not be identified by colour alone
> And in addition it must have browser default styling (i.e. outline around brand logo)

> Given I view the footer
> When I navigate by keyboard
> And I focus on the text links
> Then text links must have a visible state change
> And they must not be identified by colour alone
> And in addition they must have browser default styling (i.e. outline around link text)

This ticket is blocked until issue https://github.com/bbc/simorgh/issues/186 has been completed, since we should use the existing component. 

We need to style the logo in the Footer component to match the UX&D designs referenced in https://jira.dev.bbc.co.uk/browse/NEWSART-595

**Comment by greenc05** [comment]
@sareh will this still be part of the footer? i.e. it should be inside the footer html tag

**Comment by jamesbhobbs** [comment]
@greenc05 I think it should be inside the <footer></footer>

**Comment by jamesbhobbs** [comment]
@greenc05 I think it should be inside the `<footer></footer>`

**Comment by sareh** [comment]
@greenc05 Yes, I've updated the description to capture this - that this component and the one below should both be within the `footer` element.

**Comment by greenc05** [comment]
Fab @sareh
