### ISSUE TITLE
Allow for components to be rendered in isolation 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#227]
**Is your feature request related to a problem? Please describe.**
Currently the Document.jsx adds the DOM elements for an entire html page. We require the ability to render just a component on the client such as onwards journeys. Because of this we should move the DOM elements out of the Document.jsx. 

**Describe the solution you'd like**
Move all DOM elements that are required only for a full html page out of Document.jsx therefore making Document.jsx a shell that just proxies to other components. We can then move the DOM element into Article.jsx so it renders a full html page.

**Describe alternatives you've considered**
Change the internal logic of razzle/after to pick between multiple Document.jsx's

**Additional context**

**Comment by jamesbhobbs** [comment]
We will never SSR components other than full html documents. The client can fetch data and render itself there. I think the way we'd do this would be to simply not provide the data on the server to the specific component within the page and this it'd render some fallback as part of the full html document, on the client it'd then fetch the data and render the component using only CSR.
