### ISSUE TITLE
Add audio player to AV page

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#2286]
We need the ability to play live and on demand radio.

Support standard controls for play
- Play
- Pause
- Skip forward
- Skip back

Support standard controls for audio
- Increase volume
- Decrease volume
- Mute
- Unmute

**Solution**
Load SMP into the page.

**Testing notes**
Requires testing these services:
- Amharic - https://www.bbc.com/amharic/bbc_amharic_radio/liveradio
- Afaan Oromoo - https://www.bbc.com/afaanoromoo/bbc_oromo_radio/liveradio
- Indonesian - https://www.bbc.com/indonesia/bbc_indonesian_radio/liveradio
- Korean - https://www.bbc.com/korean/bbc_korean_radio/liveradio
- Tigrinya - https://www.bbc.com/tigrinya/bbc_tigrinya_radio/liveradio

Manual test checklist for player functionality in the top section of this document:
https://paper.dropbox.com/doc/Live-Radio-Audio-Player--AjrVYxEQnAYDSvt7PhnltAf3Ag-efPjQlnSYn9vLHY72mZmu

Dev insight: Need to source a test PID. Unit testing will be required. Doesn't initially require Cypress tests as is not production ready. May require storybook story. 

Blocked on the investigation of the SMP audio player and route setup.
Also blocked by the embed endpoiint

**Comment by graeme-lindsay** [comment]
If this is a placeholder to examine the embedded media, we can now investigate:

* Will the lazy-loading of the media player create unacceptable latency on starting content?
* Will the double i-frames cause a problem?
* Understand whether the controls identified in WSMEDIA-40 work with the appropriate service.

Check with @gavinspence

**Comment by pjlee11** [comment]
Removing block label now that the embed endpoint works on test env
