### ISSUE TITLE
Pass `topStory` prop to Media Indicator

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#2290]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/psammead/issues/768, we will need to pass a `topStory` prop to the Media Indicator to tweak the padding under 400px.

**Describe the solution you'd like**
Pass `topStory` prop to `MediaIndicator`.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by DenisBBC** [comment]
Closed as duplication of https://github.com/bbc/simorgh/issues/2272

**Comment by DenisHdz** [comment]
Closed as duplication of #2272
