### ISSUE TITLE
Create WS media page routing including amp

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#2294]
**Is your feature request related to a problem? Please describe.**
We need to route through simorgh to a new placeholder route for the AV media pages. It should be in this pattern: 
- bbc.com/$service/$sid/$pid
- bbc.com/$service/$sid/$pid.amp

Examples:
- bbc.com/amharic/bbc_amharic_radio/liveradio
- bbc.com/amharic/bbc_amharic_radio/$pid 

**Describe the solution you'd like**
Add a route [here](https://github.com/bbc/simorgh/blob/latest/src/app/routes/index.js#L15-L21) and a regex [here](https://github.com/bbc/simorgh/blob/latest/src/app/routes/regex/index.js) including amp support. We should do this for all world service sites. 

**Describe alternatives you've considered**
We could do this only for the 4 services we plan to release in MVP - it's only slightly more work to open this route for all WS sites. 

**Testing notes**
[Tester to complete]

Dev insight: This could have Cypress for local, however for test or live we would require Mozart and STM changes as well.

**Additional context**

**Comment by pjlee11** [comment]
blocked on https://github.com/bbc/simorgh/pull/2375

**Comment by ryanmccombe** [comment]
https://github.com/bbc/simorgh/issues/1544

**Comment by ryanmccombe** [comment]
Requires routing for: Amharic, Korean, Indonesia, Afaan Oromoo and Tigrinya
