### ISSUE TITLE
Pull in new version of psammead-brand

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#2314]
**Is your feature request related to a problem? Please describe.**
`psammead-brand` currently does not work as expected in high contrast mode in Firefox. Work done in bbc/psammead#787 fixes this bug, and therefore following the merge of that, we should pull the new version of the component into Simorgh.

**Describe the solution you'd like**
- Pull `@bbc/psammead-brand@latest` into Simorgh
- Update snapshots

**Describe alternatives you've considered**

**Testing notes**
- Visual regression including test of high contrast modes
- Test both articles (canonical & AMP), front pages and simorgh storybook

**Additional context**
You can test this by opening Firefox > Settings > Colours > Change dropdown to 'Always'

**Comment by jamesdonoh** [comment]
Blocked until https://github.com/bbc/psammead/pull/787 is merged.
