### ISSUE TITLE
Fix the cypress test interactive mode issue

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#2315]
**Is your feature request related to a problem? Please describe.**
Running all tests at once in interactive mode fails (running them individually is fine) - it seems to get itself into a redirect loop.

**Steps to reproduce**
1.Checkout latest branch
2.Run all the cypress tests in interactive mode `CYPRESS_APP_ENV=test npm run cypress:interactive
`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
Running all the tests once in interactive mode should run fine.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
<img width="1416" alt="cypress_interactivemode_issue" src="https://user-images.githubusercontent.com/9802855/60726447-76fdbe00-9f33-11e9-928a-8864b6f4f4fe.png">

**Comment by jamesbhobbs** [comment]
@PriyaKR is this issue still present?

**Comment by PriyaKR** [comment]
Not an issue any more hence closing.
