### ISSUE TITLE
WS media service config first 5 services

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#2316]
**Is your feature request related to a problem? Please describe.**
We need to create service config in simorgh for the first 5 services getting the WS media pages. Amharic, Korean, Indonesia, Afaan Oromoo and Tigrinya.

**Describe the solution you'd like**
Add configuration for the 5 service listed above to https://github.com/bbc/simorgh/tree/latest/src/app/lib/config/services. Any unknown values or translations should be confirmed with product/editorial, they likely already exist in Responsive News. 

Default values can be used (english placeholders) as these pages are not yet in production.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Manual regression of the brandName in the header to check the new service config is being used

**Additional context**

**Comment by jamesbhobbs** [comment]
This is a subset of https://github.com/bbc/simorgh/issues/2231 and this alternate issue should be done instead.
