### ISSUE TITLE
Investigate Code Climate Issue Reporting

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#2326]
**Describe the bug**
A weird behavior was noticed in the process of moving the Code Climate config over to a YAML file: https://github.com/bbc/simorgh/pull/2318

Code Climate was intermittently switching between reporting over 200 issues, and no issues at all

This seemed sensitive to the `"src/**/*.test.{jsx,js}"` exclusion - once that was added, CC reported there were no longer any issues, even though many of the issues were not in files that should have matched that pattern.  eg, there were a lot of issues reported in `.stories.` files.

**Comment by jamesbhobbs** [comment]
NB example that should show as error: src/app/containers/ImageWithPlaceholder/index.jsx

**Comment by jamesbhobbs** [comment]
Having attempted to fix this I'm quite confident it's an error in codeclimate exclude pattern recognition. I will merge the branch above as we're currently ignoring too many files. The remainder of this issue which is non urgent is for the person who picks this up to take this up with code climate - or to prove me wrong with a pattern that strictly excludes the test and story files
