### ISSUE TITLE
front page: offscreen h1 is placed too low when the skip to content link is activated

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#2330]
**Describe the bug**
The h1 is affected by browser default styling, and therefore placed too low; using the skip to content link places the browser viewport a little too low. (The top of the viewport is where the blue line in the screenshot below).

This issue is present on all browsers but is particularly obvious on IE11.

**Desired solution**

Set `margin: 0;` on the visually hidden h1 to reset any browser default margins.

**Screenshots**
![IMG_1236](https://user-images.githubusercontent.com/10963046/60808304-d6e8a480-a17f-11e9-842c-258257016164.JPG)

**Additional context**

**Comment by ghost** [comment]
`psammead-visually-hidden-text` has already been update to version 1.0.7.
