### ISSUE TITLE
Add live Persian asset to articleSpec e2e's

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#2335]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/bbc/simorgh/pull/2332 we skipped the Persian articleSpec as the asset used was no longer available on live.

**Describe the solution you'd like**
When we have Persian articles available on live we should update the config with the correct live and test assets.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Cypress tests passing are valid regression

**Additional context**
N/A

**Comment by jimjohnsonrollings** [comment]
c7eel0lmr4do exists on Live

**Comment by jimjohnsonrollings** [comment]
ah but there's no routing on live, so I think this is still blocked.

**Comment by jimjohnsonrollings** [comment]
This should also cover live SW and Manifest e2es

**Comment by jamesdonoh** [comment]
Moving to externally blocked while we await live route
