### ISSUE TITLE
Read&Write reads out URL on brand

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2338]
**Describe the bug**
Reads out url in addition to the text when hovering over the brand element - does not seem to do this for other urls on the page

**To Reproduce**

**Expected behavior**
It doesnt read the url out.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 7 Service pack 1
- Browser: Internet Explorer 11
- Tool: Read&Write

**Additional context**

**Comment by greenc05** [comment]
Should this not be a psammead issue?

**Comment by DenisHdz** [comment]
I am testing the Pidgin site using Read and Write and I can't reproduce this behavior. It just reads out the visually hidden text: `BBC News, Pidgin`. @dr3 @greenc05
