### ISSUE TITLE
Re-org app files

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#236]
**Is your feature request related to a problem? Please describe.**
App files are a bit all over the place and need a minor re-org to a `lib` directory.

**Describe the solution you'd like**
Move all app specific lib files to to `src/app/lib`:
- https://github.com/bbc/simorgh/blob/latest/src/lib/constants/styles.js
- https://github.com/bbc/simorgh/blob/latest/src/app/models/blocks.js
- https://github.com/bbc/simorgh/blob/latest/src/app/helpers/blocks.js
- https://github.com/bbc/simorgh/blob/latest/src/app/helpers/proptypes.js

**Comment by jamesbhobbs** [comment]
@jtart let's discuss tomorrow f2f

**Comment by jamesbhobbs** [comment]
After conversation the exact things in the issue aren't being done, @jtart and I must approve to merge and we defined the new structure^^^
