### ISSUE TITLE
Make simorgh E2E's run on live env for WS frontpages

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2377]
~~Blocked on LIVE STM routing of pages~~

**Is your feature request related to a problem? Please describe.**
Make simorgh E2E's run on live env for WS frontpages

**Describe the solution you'd like**
Search for `describeForLocalOnly` and `describeForLocalAndTest` blocks in our cypress tests. Change **only those relevant to the front pages which recently went live** to be `describe` blocks.

**Describe alternatives you've considered**
None, because not testing our live environment is not an alternative that should be considered.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
Make sure @david-boydell sees this before merge as he'll be iterating the tests in future

**Comment by jamesbhobbs** [comment]
Effectively done we just need to change the config as things go live
