### ISSUE TITLE
Remove blocking JavaScript from AudioVideo integration

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2389]
**Describe the bug**
The initial implementation for integrating audio and video in https://github.com/bbc/simorgh/pull/2151 loads [RequireJS](https://requirejs.org/) via a blocking external `script` tag added to the `head`.

This is very bad for performance because as soon as the browser encounters this tag it will block all further parsing of the page till the RequireJS library has been loaded over the network and evaluated.

This issue should take the existing implementation as it stands, to make it load lazily. This shouldn't be a massive issue that refactors a lot of code, and doesn't need to be best technical implementation, that will come in a future issue. This is just to stop blocking JS. 

There should be a future ticket to carry out a more in-depth investigation on the best technical solution to lazy load entire react components.

**Testing Notes**
- Test that `requirejs` is loaded asynchronously

**To Reproduce**

Either examine page source or to observe performance effect:

1. Go to any Simorgh page
2. Open DevTools and look at Network tab
3. Notice blocking request for RequireJS in waterfall

**Expected behavior**
All external scripts should be loaded asynchronously.

**Screenshots**
<img width="996" alt="Screenshot 2019-07-10 at 08 03 36" src="https://user-images.githubusercontent.com/11161809/60947738-41692400-a2e9-11e9-8aa0-1df3834ff20d.png">

**Additional context**
Good overview from [Ilya Grigorik at Google](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/)

**Comment by 12** [comment]
@jamesdonoh is this going to be blocking us from releasing video?

**Comment by jamesdonoh** [comment]
Closing per https://github.com/bbc/simorgh/pull/2456#issuecomment-512182925
