### ISSUE TITLE
Improve the data validator log format

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#239]
**Is your feature request related to a problem? Please describe.**
Change the logging on the data validator to better represent the nested nature of the data feed. 

**Describe the solution you'd like**
Logging similar to `npm ls` to show how the blocks in the data feed are nested:

EG:

```
simorgh@0.0.1 /Users/phillee/Code/BBC/simorgh
├─┬ @jaredpalmer/after@1.3.1
│ ├── react-helmet@5.2.0 deduped
│ └── serialize-javascript@1.5.0
├─┬ @storybook/react@4.0.0-alpha.8
│ ├─┬ @storybook/core@4.0.0-alpha.8
│ │ ├─┬ @storybook/addons@4.0.0-alpha.8
│ │ │ ├── @storybook/channels@4.0.0-alpha.8
│ │ │ ├── global@4.3.2 deduped
│ │ │ └── util-deprecate@1.0.2
```

**Describe alternatives you've considered**
None

**Additional context**
The data feed is highly complex due to the infinite nesting of the data blocks.

**Comment by jamesbhobbs** [comment]
https://github.com/bbc/simorgh/issues/1638
