### ISSUE TITLE
Team a11y swarm for for articles AV

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2408]
**Is your feature request related to a problem? Please describe.**
Before the media player can be enabled on articles we need to complete a full team a11y swarm on it (see https://bbc.github.io/accessibility-news-and-you/accessibility-swarms)

As well as a the general testing described at the link above, in particular we should check that the screenreader UX as implemented matches the agreed designs (https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c596fa88971d341fae3fd53)

**Describe the solution you'd like**
- Arrange and carry out team swarm as described above
- Create and prioritise GitHub bug issue for any problems that are found, seeking guidance from a11y Champion as necessary
  - Compare with results of previous Media pod swarm(s)

**Describe alternatives you've considered**
NA

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by rhell** [comment]
Adding the blocked label as this is not testable on some devices and browsers yet due to #2498.

**Comment by lizcameron** [comment]
Swarm complete and resultant P1 issues investigated/closed. P2 or lower issues created and in To Do.
