### ISSUE TITLE
Tidy up AudioVideo work

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2412]
**Is your feature request related to a problem? Please describe.**
While reviewing https://github.com/bbc/simorgh/pull/2151 some ideas were raised for refactoring/tidying up which we will do separately to avoid blocking the main PR:

- DRY up use of `isKind` helper, see https://github.com/bbc/simorgh/pull/2151/files#r301522592
- `portrait` default, see https://github.com/bbc/simorgh/pull/2151/files#r301490794
- document/clarify use of 9:16 ratio, see https://github.com/bbc/simorgh/pull/2151/files#r301495371

**Describe the solution you'd like**
Action the suggestions made during review (or evaluate and reject them).

**Describe alternatives you've considered**
NA

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by RayNjeri** [comment]
This is no longer required since we are currently removing most of the canonical implementation.
https://github.com/bbc/simorgh/issues/2614
