### ISSUE TITLE
Image metadata for AudioVideo content

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2413]
**Is your feature request related to a problem? Please describe.**
Update: image metadata appears to have been disabled. The first step is to ensure it is reenabled.

Right now the image given in page-level metadata for audio/video content includes `$recipe` which is invalid, this should be a valid image URL of suitable dimensions that can be consumed by aggregators/search engines. Additionally, the `uploadDate` appears to be null.

Originally raised by @rhell, see:
- https://github.com/bbc/simorgh/pull/2151#discussion_r301493377
- https://github.com/bbc/simorgh/pull/2151#discussion_r301494278

For schema.org metadata format reference see for example: https://schema.org/AudioObject

**Describe the solution you'd like**
- Make the thumbnail image URL valid
- Revisit https://github.com/bbc/simorgh/pull/2151/files#r301494278
- Validate page-level metadata using 3rd-party tools and check that everything is picked up correctly

**Describe alternatives you've considered**
NA

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
Not only should the video block be valid in itself, but each should also point to the associatedArticle they're in or another canonical article they're in. This can be confusing for search engines though (as across different articles the same video would relate to many articles) and also this link expects NewsArticle which we don't seem to use, so it'd be better to list the videos directly under the article https://schema.org/Article
