### ISSUE TITLE
Refactor AudioVideo and ArticleFigure containers for maintainability

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2415]
**Is your feature request related to a problem? Please describe.**
There seems to be quite a lot of overlap/duplication between the `ArticleFigure` and `AudioVideo` containers (e.g. see https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleFigure/index.jsx#L77-L84). This means that if the treatment for both article figures and audio/video content needs to change we will have to update it in multiple places.

**Describe the solution you'd like**
We should look for ways of reducing the duplication between these containers and making them easier to maintain. We should also search for any other good candidates for inclusion in this task.

**Describe alternatives you've considered**
We could leave the containers as they are if we think their requirements are going to diverge significantly, but there is still probably opportunity for simplification.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
Possibly relevant issues:
- https://github.com/bbc/simorgh/issues/2313
- https://github.com/bbc/simorgh/issues/2149

**Comment by jamesbrumpton** [comment]
We have removed refinement needed as we were happy regarding the refactoring of AudioVideo & ArticleFigure logic to reduce duplication. The only outstanding question was for @jamesdonoh in terms of what was "any other good candidates" referring to? Something else to be refactored along with the AV & ArticleFigure logic or something completely separate?
