### ISSUE TITLE
Make logger files modules, not scripts

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2419]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/pull/2378 an exception in the babel was made to treat logger js files as scripts not modules. It is unknow why these cant be modules, however it causes weird errors, like how theyre not functions, despite logging as functions, then theyre called.

**Describe the solution you'd like**
Resolve this problem if possible, turning them into modules and removing the babel exception.

**Describe alternatives you've considered**

**Testing notes**
No longer should be seeing those weird errors on logger files.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by PriyaKR** [comment]
Whoever is picking this up are you able to log those weird errors seen in logger file for testing purpose?

**Comment by mykeels** [comment]
What logger file(s) do we want to turn from scripts into modules?

**Comment by dr3** [comment]
> What logger file(s) do we want to turn from scripts into modules?

@mykeels anything under `/.*logger.*/` which I think namely is files under `https://github.com/bbc/simorgh/tree/latest/src/app/lib`

**Comment by mykeels** [comment]
Investigating this, I've learnt that:

- The build `server.js` output has:
```js
var nodeLogger = __webpack_require__(/*! #lib/logger.node */ "./src/app/lib/logger.node.js");
```
and if this is changed to:
```js
var nodeLogger = __webpack_require__(/*! #lib/logger.node */ "./src/app/lib/logger.node.js").default;
```

Then the `nodeLogger is not a function` error, goes away.

I've been unable to effect this change in the build process.
