### ISSUE TITLE
Frontpages structured data error

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2426]
**Describe the bug**
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.stage.bbc.co.uk%2Figbo

**Expected behavior**
Value `@type` should be a known type, (to be confirmed)

**Additional context**

**Comment by amywalkerdev** [comment]
og:type should be `website` http://ogp.me/#type_website and not `IDX`

**Comment by amywalkerdev** [comment]
schema.org type is also wrong, should be `WebPage` https://schema.org/WebPage instead of `IDX`
