### ISSUE TITLE
Properly define MainContent props

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#244]
**Is your feature request related to a problem? Please describe.**
The defined MainContent props takes an array that can contain anything: https://github.com/bbc/simorgh/blob/b0f698590a6b66e28798201a146dc15778a0e8bf/src/app/components/MainContent/index.jsx#L34

**Describe the solution you'd like**
The MainContent props to be properly defined as to the blocks it can and will [render](https://github.com/bbc/simorgh/blob/latest/src/app/components/MainContent/index.jsx#L12-L15). These props should be made up of `block` prop types that are defined [here](https://github.com/bbc/simorgh/tree/latest/src/app/models/propTypes) - [this](https://github.com/bbc/simorgh/blob/latest/src/app/models/propTypes/headline/index.js#L8) is an example.

**Comment by jamesbhobbs** [comment]
No longer true

**Comment by jamesbhobbs** [comment]
Reopened and corrected/updated issue description.
