### ISSUE TITLE
Handle media player loading timeout gracefully

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2451]
**Is your feature request related to a problem? Please describe.**
If loading/rendering the player (SMP) for audio/video content times out or fails (e.g. due to loss of network) the user may see nothing and be left waiting indefinitely, or (once we have done https://github.com/bbc/simorgh/issues/2422) keep clicking the placeholder without realising that it has failed.

**Describe the solution you'd like**
We should detect this situation and handle it gracefully, showing a suitable text message and/or image to the user so that they are not left waiting indefinitely.

- Timeout: suggested initial default value of 15 seconds. Later we want this to be configurable per-service
- UX: there is currently no UX for this but we can implement the technical solution and associated tests and refine the appearance/text later.

One option for implementing this at the code level: https://www.npmjs.com/package/promise-timeout

**Describe alternatives you've considered**
Ignoring this problem is likely to cause user frustration/disappointment.

**Testing notes**
Dev Insight covers what testing is necessary. However, perhaps using speed tethering may be a good alternative.

Dev insight: Testing this will required using the dev tools to click requests to the AV or bump and check the timeout takes place. 

**Additional context**

**Comment by pjlee11** [comment]
Bump currently has a timeout of 30 seconds so it's likely we should be consistent with the timeout values.

**Comment by jamesbhobbs** [comment]
I'd like timeout values to be a value in the app config for each service and read from there. This would then be applicable to all 3rdparty content loaded in e.g. social embeds and ads as well.

PS for simplicity I agree for now setting them all in the config to 30s. So long as it's possible to vary them by service.

**Comment by jamesdonoh** [comment]
I don't think this issue is possible with the new implementation so I move we close it.
