### ISSUE TITLE
Run Lighthouse tests against worst-case article

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2455]
**Is your feature request related to a problem? Please describe.**
Currently we run Lighthouse tests for articles against `c6v11qzyv8po`, however as we continue to evolve the product more features will be added (e.g. audio/video) that may affect our Lighthouse scores. We should be targeting worst-case performance, i.e. the Lighthouse scores we would get for articles that have all features enabled.

**Describe the solution you'd like**
- ~Create new asset or adapt existing asset~ New asset created: `cq0erv3pqpro`
- Communicate with Optimo that we are using the asset(s) for testing so they need preserving
- Update Lighthouse tests and create separate issues for any problems found

**Describe alternatives you've considered**
No alternatives.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by pjlee11** [comment]
Assuming we have features behind toggles are we expecting to run light house against the our ENV's using the toggle values or would we override the toggles to ensure consistency lighthouse scores across different environments

**Comment by jamesdonoh** [comment]
As discussed we currently only run Lighthouse against test. If we did run it against both test and live, in practice toggle values for test should either match live or represent "worse" than live, rather than "better" than live.

**Comment by jamesbhobbs** [comment]
This is sort of assumed in the issue for scaling lighthouse tests, all tests should run against worst cases
