### ISSUE TITLE
ATI container to check propTypes for front pages

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#2459]
**Is your feature request related to a problem? Please describe.**
Currently the ATI container uses propTypes to validate data for articles:
https://github.com/bbc/simorgh/blob/f8ecdce2ebcc2a5f24ef3315a5217035a5b5e096/src/app/containers/ATIAnalytics/index.jsx#L34

We should update it to use front page propTypes (https://github.com/bbc/simorgh/blob/fix-metadata-proptypes/src/app/models/propTypes/frontPage/index.js)

**Describe the solution you'd like**
PropTypes to validate against either articlePropTypes or frontPagePropTypes using `oneOfType`.

**Describe alternatives you've considered**
We leave it as it is and we get console errors 🚫. 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by EinsteinNjoroge** [comment]
This issue has been resolved in [bb480b1](https://github.com/bbc/simorgh/commit/bb480b1447dec76034b70186aa5021ec5f3d0d2f)
