### ISSUE TITLE
Add some details to Github release

### ISSUE THREAD

**Issue by mbzain76** [bbc/simorgh#2501]
**Is your feature request related to a problem? Please describe.**
We have Github release created automatic but without details just the name.

**Describe the solution you'd like**
We need as the beginning to add some details like:
- The latest commit message.
- Jenkins build number
- Cosmos release version

**Describe alternatives you've considered**
N/A
**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by DemonusPC** [comment]
Done as part of an internal tooling stream
