### ISSUE TITLE
Use NassimPersian font face in simorgh

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2503]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/psammead/pull/676 the NassimPersian font face is now available in psammead

**Describe the solution you'd like**
- Similar to how `news` [does it](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/news.js#L161-L168) add the nassim persian fontface to [the persian config](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/persian.js#L170)
- Add screenshots for before and after and get UX to review
- Answer question: should Nassim load on first page view or only on subsequent ones like Reith? (check with Jim or Natalie)
- Check if any changes are required to Storybook in SImorgh

**Testing notes**
- Check using DevTools that the correct version of the Nassim font is used on Persian articles
- Check that no other styling is adversely impacted (e.g. inline link changes)
- Test how it looks on older/smaller devices
- Dev and test to decide on best way of providing test coverage for correct font being used on Persian

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jimjohnsonrollings** [comment]
Closing as PR has merged
