### ISSUE TITLE
Toggle for Chartbeat

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2552]
**Is your feature request related to a problem? Please describe.**
Once we have added Chartbeat in https://github.com/bbc/simorgh/issues/1987 we should ensure that we have a way of turning it off at runtime in the event of any problems.

**Describe the solution you'd like**
- Implement feature toggle for Chartbeat
- Document process for disabling it

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbrumpton** [comment]
Previous implementation of Flag logic - https://github.com/bbc/simorgh/pull/2283

**Comment by oluoluoxenfree** [comment]
Blocked on #2341

**Comment by oluoluoxenfree** [comment]
Dials are being removed from simorgh and #2341 adds their replacement, toggles. It's still in test so we're waiting for it be merged.

**Comment by 12** [comment]
@oluoluoxenfree This has now been merged.
