### ISSUE TITLE
Add PGL to CPS type whitelist

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#2559]
~~Blocked on https://github.com/bbc/psammead/issues/1232~~
~~Blocked on https://github.com/bbc/simorgh/issues/2561 (transitively externally blocked)~~
Blocked waiting for UX review

**Is your feature request related to a problem? Please describe.**
Since we're adding support for photo galleries on our front pages, we now need to stop filtering out PGLs.

**Describe the solution you'd like**
Add `PGL` to the whitelist array in [cpstypes.js](https://github.com/bbc/simorgh/blob/latest/src/app/lib/utilities/preprocessor/rules/cpstypes.js) and enable the use of photo gallery media indicator on in story promo

**Describe alternatives you've considered**
📷🚫 = 👎 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
WSFRONTPGS-83

**Comment by j-pendlebury** [comment]
Check that fixture data contains PGL

**Comment by j-pendlebury** [comment]
Make sure that one of the service's top story is a PGL asset

**Comment by j-pendlebury** [comment]
Blocked by media indicator needing a UX review

**Comment by laurapsn** [comment]
PGL indicator reviewed by UX and good to go.
