### ISSUE TITLE
AMP assets should have a BBC.com url - not a google.com url

### ISSUE THREAD

**Issue by neildoughty** [bbc/simorgh#2560]
**Is your feature request related to a problem? Please describe.**
Since the first proper WS pages went live in Simorgh the AMP versions of them have appeared at the top of Google search results pages, but the URLs show as they from Google. We have a brand attribution problem within the WS where many users don't know where our content is from. As such it's important a BBC url is shown on these pages.

**Describe the solution you'd like**
When a user views an AMP asset served from Simorgh that AMP asset ought to appear with a BBC url. Martyn and Chris have referred to a thing called WebPackage - https://blog.amp.dev/2018/05/08/a-first-look-at-using-web-packaging-to-improve-amp-urls/ - which may help with this problem, and doing the work now may be a sensible time to do it before we launch more pages.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
https://www.dropbox.com/s/j5l5w852y1sun3k/RPReplay_Final1563267863.MP4?dl=0

**Comment by chris-hinds** [comment]
Signed exchanges and web packaging is the solution to this. More info here: https://venturebeat.com/2019/04/16/google-amp-signed-exchanges/

**Comment by dr3** [comment]
@hindsc52 How was this done for alephamp? Can we replicate that sollution?

**Comment by neildoughty** [comment]
We haven't done this for Alephamp.
You can hit pages on the bbc url with AMP in it and they'll work, but if you find that page via search, then you get a google url. So we don't have a current solution.

**Comment by chris-hinds** [comment]
This isn't really viable until our CDN supports web packaging and signed exchanges for AMP. A support ticket with our CDN was opened to ensure they know that the BBC is seeking this functionality.
