### ISSUE TITLE
Add translations for 'photogallery'

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#2561]
**Is your feature request related to a problem? Please describe.**
We need to add translations for the word photogallery.

**Describe the solution you'd like**
Add translation for the word photogallery to our config files:

* [Igbo](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/igbo.js)
* [Pidgin](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/pidgin.js)
* [Yoruba](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/yoruba.js)

Translations https://github.com/bbc/simorgh/issues/2561#issuecomment-512743348

**Describe alternatives you've considered**
Hardcode to English.. which isn't ideal.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
WSFRONTPGS-83

**Comment by andrew-nowak** [comment]
ig - `Image gallery`
pcm - `Image gallery`
~~yo - `Láti abala náà`~~
yo - `Àtẹ Àwòrán`

These are the translations used on the current (now old 😮 ) site. They may not be correct (igbo is especially 🤔 ) but we can easily update the config when updated translations come through
