### ISSUE TITLE
Refactor Grid implementation

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2563]
**Is your feature request related to a problem? Please describe.**
The current grid implementation is quite large, it can be found [here](https://github.com/bbc/simorgh/blob/latest/src/app/lib/layoutGrid/index.js) and [here](https://github.com/bbc/simorgh/blob/latest/src/app/lib/styledGrid/index.jsx).

IMO it has a number of possible improvements that can be made. It is very restrictive, you cant use it outside of `small`, `medium` and `large`. It also adds many uneeded dom elements. E.g. a figure element requires `GridItemConstrainedLargeNoMargin Figure NestedGridParentLarge NestedGridItemChildLarge`. 

**Describe the solution you'd like**
Discuss, Expand and implement [this proposed refactor](https://codepen.io/drewmcmillan/pen/MMMZwB?editors=0010). Every grid item has its own grid that matches the column numbers of its parent.

It supports not having Grid (IE11) and doesn't require any hardcoded percentages etc.

We can remove all hardcoded `Large` elements etc and replace them with config like
```
const large = {
 group0: 6,
 group1: 6,
 group2: 6,
 group3: 6,
 group4: 6,
 group5: 12
}
```

Need a margin? Expand the css
Need it to be a figure? use `as="figure"`

The general idea is an item knows "I am 4 columns wide, my parent is 6 columns wide"

- It sets itself spanning 4 columns
- It makes a new grid inside itself, 4 columns wide
- Sets itself as 4 of 6 = 66% width (for non grid)

The code pens above will need to be expanded to scale for multiple breakpoints, however this can be done programmatically 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
Closing in favour of this issue https://github.com/bbc/simorgh/issues/2313 (not implying it won't be done, just that one issue is clearer to track)
