### ISSUE TITLE
[Core] Brasil articles don't work because their Home don't match their service name

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#2574]
**Is your feature request related to a problem? Please describe.**

We currently validate that the Passport Home of an asset matches the service name from the URL.  This is not expected to be the case in Brasil, where the Passport Home will be Brasil, but the URL will contain the word 'portuguese' instead.

**Describe the solution you'd like**
Our validation of articles should handle cases where the service and Passport Home values are not identical

**Describe alternatives you've considered**
* Change the Passport - rejected as this would be inconsistent with the audience-facing branding
* Change the URL - rejected as this would be bad for SEO

**Testing notes**
https://www.test.bbc.com/portuguese/articles/cerj3rk9mmyo - should load the article page instead of 404 ing

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
The easiest way to do this would be add a key of `passportHome` to the service config (or all of them) and check if it matches in `withData.jsx`. If we dont put it in all of them, use `passportHome` if set, else use `service`.

**Comment by dr3** [comment]
https://www.test.bbc.com/portuguese/articles/cerj3rk9mmyo.json

**Comment by jimjohnsonrollings** [comment]
This is also true of /scotland articles where the home is 'BBCScotland'

**Comment by mykeels** [comment]
I'd like to take this up.

What config files should I look at for Brasil and Scotland?

**Comment by jimjohnsonrollings** [comment]
The Brasil config is called 'protuguese.js'.  The Scotland config is on a branch called 'scotland' at the moment.

**Comment by dr3** [comment]
the service files dont need to change, its the 'Home' logic that does :)

**Comment by mykeels** [comment]
Why wouldn't the service files have to change, if we have to add a key `passportHome` to the service config? @dr3

**Comment by dr3** [comment]
@mykeels Ah yes sorry, i meant renaming them soz 🙈Adding new keys is fine :)

**Comment by mykeels** [comment]
Of the three folders in `data/portuguese`, does only the json file in the `articles` folder need this change, or all three?

**Comment by dr3** [comment]
Sorry @mykeels We cant change anything in the data folder, thats just fixture and we cant make the change in ares either.
