### ISSUE TITLE
Mock console log object in Article spec and add a test for it being called

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#259]
**Describe the bug**
[This article spec](https://github.com/bbc/simorgh/blob/latest/src/app/components/Article/index.test.jsx#L61-L66) is outputting a console log.

**To Reproduce**
Run unit tests: `npm run test:unit`

**Expected behavior**
Console log should not output to the stdout - We should mock the console object, then can add a test to ensure that is it calling console.log.

**Screenshots**
![image](https://user-images.githubusercontent.com/16549467/42325630-ac5f284e-805e-11e8-90d2-ae0a4dabb8d4.png)

**Comment by pjlee11** [comment]
Rather than mocking the console.log in each set of Jest tests we should create a log() method as a utility helper. This way we can suppress the actual `console.log` while mocking the `log` method allowing us to capture and test that thing log as expected.
