### ISSUE TITLE
Add LIV to CPS type whitelist 

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#2600]
~~Blocked on https://github.com/bbc/psammead/issues/1356~~

**Is your feature request related to a problem? Please describe.**
Similarly to #2559, we need to add 'LIV' to the whitelist array to stop filtering out the live promo assets and integrate the LIV label functionality in Simorgh

**Describe the solution you'd like**
Add LIV to the whitelist array in [cpstypes.js](https://github.com/bbc/simorgh/blob/latest/src/app/lib/utilities/preprocessor/rules/cpstypes.js)

Update story promo container with logic for LIVE label

**Describe alternatives you've considered**
No live promos 😢 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
WSFRONTPGS-81

**Comment by j-pendlebury** [comment]
Blocked by https://github.com/bbc/psammead/pull/1359 needing an accessibility swarm

**Comment by Bopchy** [comment]
Waiting on https://github.com/bbc/psammead/pull/1359 to be merged
