### ISSUE TITLE
Add support for inline block to support multiple languages

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#2601]
**Is your feature request related to a problem? Please describe.**
We currently do not support the block with `type=inline`. The article https://www.test.bbc.co.uk/news/articles/cv7yn5n25rno is an English article containing a Farsi block.

**Describe the solution you'd like**
Give the payload https://www.test.bbc.co.uk/news/articles/cv7yn5n25rno we should render the inline block. 

We can also look to add the `dir` and `lang` attribute to the HTML elements that map to the given `language` of the block.

The following requirements must be satisfied (originally from https://github.com/bbc/simorgh/issues/1912)

As a screen-reader user
I want text to be read out in the appropriate voice for its language
So that I can understand it

Given I am on an article
When I reach a fragment with a language attribute that is different from the language attribute of the article
Then I hear it read in the appropriate screen-reader voice

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshot tests are required and manual regression of the article. 

**Additional context**
We should add fixture data matching the example - https://www.test.bbc.co.uk/news/articles/cv7yn5n25rno

**Comment by pjlee11** [comment]
Quickly reviewing the [example payload](https://www.test.bbc.co.uk/news/articles/cv7yn5n25rno.json) and the inline block marked as `language=fa` contains latin left-to-right text. We should update this to be actual Farsi content (rtl)

**Comment by greenc05** [comment]
Has this had a developer accessibility swarm? Including text, a link and an external link with the lang attribute?
