### ISSUE TITLE
FrontPages should not show images for non-js users

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#2605]
**Is your feature request related to a problem? Please describe.**
For non-js users the front loads with about 2.4MB image of images this is unacceptably large and will be a huge performance issue for non-js users.

**Describe the solution you'd like**
To not load images on the non-js experience. Whether or the not the top image should load needs to be decided.

**Describe alternatives you've considered**
leaving it as is and asking users to download a near 3MB page

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
Make sure articles not broken.

**Comment by jamesbhobbs** [comment]
Is this not also equally true for articles and therefore we should be removing no-js support entirely. Repeating (again): we do not need to support no-JS experiences so any bug shouldn't be fixed we should remove the functionality.

**Comment by j-pendlebury** [comment]
all images to be removed on non-js

**Comment by ghost** [comment]
use placeholders for the images.
