### ISSUE TITLE
Add cypress tests for new WS routes

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#2615]
**Is your feature request related to a problem? Please describe.**
We have now added routes for all of the world service sites for front pages and articles. These will soon be available on the test environment.

We should add cyrpress test to ensure the main routes as well as the service worker, manifest and data routes are working.

**Describe the solution you'd like**
Add new cypress tests to ensure all world service routes are working as expected on the test environment.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by PriyaKR** [comment]
This would mainly need extending the config file adding new services which would make some of the test files extend to new services.

Also do we need to run the cypress tests for all the services which would consume more time?

**Comment by jamesbhobbs** [comment]
>Also do we need to run the cypress tests for all the services which would consume more time?

yes, for now. We can be more selective in future, at the moment I'm very concerned by the lack of coverage

**Comment by jamesbhobbs** [comment]
done
