### ISSUE TITLE
Enable Chartbeat for indexes

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#2625]
~~Blocked on https://github.com/bbc/simorgh/pull/2837~~

**Is your feature request related to a problem? Please describe.**
We need to add Chartbeat to the front page routes. This involves generating a dynamic object  that we can then send to Chartbeat. The key/values for this object can be found by looking at the table in #1986.

**Describe the solution you'd like**
This should work for both AMP and canonical platforms. Using the utilities created in #1986, this shouldn't be too taxing, however some modification of those utils _might_ be required. They were built as close to the spec of that table as possible.

You can observe requests being made to Chartbeat by inspecting your network tab and looking for requests to `ping.chartbeat.com`.

For any environment that is not live, we should report to the `test.bbc.co.uk` domain.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
Chartbeat Docs: http://support.chartbeat.com
Chartbeat for AMP: http://support.chartbeat.com/docs/integrations.html#amp

It is useful to be aware of the following (although not 100% certain if it will apply to us):

> If your website makes use of dynamic page change, infinite scroll, or Single Page App architecture, you will need to implement our virtualPage function for Chartbeat to properly track these pageviews.

However, the [virtualPage documentation](http://support.chartbeat.com/docs/#ajax) states that it should only be needed if the DOM does not update and/or the URL does not change. Therefore, I think we should be okay, but might need a little bit of investigation.

Chartbeat recommend placing the code to fire the beacon within the `head` of the page, and after the `rel="canonical"`.

I'd also recommend installing the [Chartbeat Heads-Up Display](https://chartbeat.zendesk.com/hc/en-us/articles/115001293233-Install-the-Heads-Up-Display-HUD-)

If you need Chartbeat access, speak to @jimjohnsonrollings

**Comment by rhenshaw56** [comment]
@rhell I think most of the work for this has been done here [PR in progress](https://github.com/bbc/simorgh/pull/2580) because it has the same logic, just a matter of adding the ChartbeatAnalytics container to the front page index and updating snapshots

**Comment by 12** [comment]
This is blocked on bbc/simorgh-infrastructure#622

**Comment by rhenshaw56** [comment]
this should be unblocked now as https://github.com/bbc/simorgh/pull/2740 has been merged

**Comment by sadickisaac** [comment]
Blocked on https://github.com/bbc/simorgh/issues/2811

**Comment by andrew-nowak** [comment]
@rhell do you know if this issue is ready for the frontpages pod to  pick up or are there still issues with the chartbeat implementation?

**Comment by 12** [comment]
I think this is blocked until #2837 is merged, as this resolves numerous issues that would affect frontpage tracking too, as highlighted in the original issue #2811. Happy to update when this work is merged 🙂

**Comment by andrew-nowak** [comment]
Thanks @rhell

**Comment by ghost** [comment]
What milestone is this?

**Comment by andrew-nowak** [comment]
No longer blocked, but we should be aware of a couple of remaining bugs in the chartbeat implementation 
https://github.com/bbc/simorgh/issues/3040
