### ISSUE TITLE
Add new block definitions to schema

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#263]
**Is your feature request related to a problem? Please describe.**
There have been new blocks defined within the CMS we need to update the schema to incorporate these new blocks.

**Describe the solution you'd like**
Add any new block definitions that we don't already have. 

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by jamesbhobbs** [comment]
@pjlee11 there's no content in this issue to do, can you define what precisely is needed, please. Then add the suitable milestone.

**Comment by pjlee11** [comment]
I created this as a future placeholder for when the next batch of blocks are agreed upon as and when Optimo create them, happy for this to be closed as the new blocks are yet to be confirmed.
