### ISSUE TITLE
Cookie Banner reappears on refresh

### ISSUE THREAD

**Issue by david-boydell** [bbc/simorgh#2646]
**Describe the bug**
It doesn't seem possible to permanently dismiss the cookie banner, when the page is reloaded the banner reappears.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/igbo
2. Dismiss the cookie banner
3. Reload
4. Banner appears again

**Expected behavior**
The banner is dismissed permanently and does not reappear.

**Screenshots**
Looking at a instance of Chrome that is exhibiting this behaviour, the cookies stored were:

![image](https://user-images.githubusercontent.com/36667923/61539453-771db380-aa33-11e9-95f1-c76a72fa6d8b.png)

**Desktop (please complete the following information):**

- OS: OS X
- Browser Chrome
- Version 75

**Comment by david-boydell** [comment]
Adding screenshot provided by Clare showing the domains:

![image](https://user-images.githubusercontent.com/36667923/61626391-1c739a00-ac75-11e9-8ec8-f8bf6e2cd959.png)

**Comment by EinsteinNjoroge** [comment]
@david-boydell @clareevansbbc Kindly confirm this issue still persists, I can't seem to reproduce it on any of my devices. I've tried using  **Chrome _v75_** and **Firefox _v68_** on OS X and **Chrome** on Android

**Comment by EinsteinNjoroge** [comment]
It turns out that this is a browser caching issue, the banner behaves as expected.
