### ISSUE TITLE
Investigate how to ensure the use of immutable data structures

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#2649]
**Is your feature request related to a problem? Please describe.**
Mutating data can be bad for performance and cause hard to track down bugs. See [The Power Of Not Mutating Data](https://reactjs.org/docs/optimizing-performance.html#the-power-of-not-mutating-data).

**Describe the solution you'd like**
Use of immutable data structures and a guard against data mutation. A possible solution could be [Immer](https://github.com/immerjs/immer).

[More on Immer](https://www.netlify.com/blog/2018/09/12/the-rise-of-immer-in-react/).

**Task:** Investigate and propose sollutions, Once done, discuss with pod on an agreed sollution to implement and raise a new issue 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by thekp** [comment]
testing: make sure bundle size isn't increased.
