### ISSUE TITLE
Use new psammead-amp-geo component

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#2652]
**Is your feature request related to a problem? Please describe.**
After the creation of `psammead-amp-geo` https://github.com/bbc/psammead/issues/298, we should use it in Simorgh. 

**Describe the solution you'd like**
Import `@bbc/psammead-amp-geo` as a dependency and use it for the Consent Banner. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests, plus when on Test checking that the Consent Banner logic is working for AMP pages in the EEA countries and overseas territories

**Comment by sareh** [comment]
Blocked on completion of https://github.com/bbc/psammead/issues/298

**Comment by jamesbhobbs** [comment]
This is done

**Comment by jamesbhobbs** [comment]
https://github.com/bbc/simorgh/blob/7df05c0d340447c44b8554c5cc170c47cd78f320/src/app/containers/ConsentBanner/index.amp.jsx

https://github.com/bbc/simorgh/blob/25e9501e8d9b077144bbdba8f0d9ca7ffbd52e64/package.json
