### ISSUE TITLE
Investigate invalidating application caches

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#2661]
**Is your feature request related to a problem? Please describe.**
We need a method to invalidate local caches as way to force reload the JS bundles, as when on a users devices in the SPA world given that onward journeys are rendered client side a user may never get the latest bundles.

Along with the bundles we'd need a way to invalidate the service worker, as a bad SW release could be damaging to the application.

**Describe the solution you'd like**
An investigation into the different solutions available to aid in invalidation of JS bundle and service worker caches, essentially forcing a reload of Simorgh's core assets.

Questions to answer:
1) Upon finding a bad release how do we invalidate the caches
2) How long until we are sure that everyone has the "fix"

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by joshcoventry** [comment]
bundles are invalidated each time we release as the hash changes and our pages have a very short ttl
