### ISSUE TITLE
Add `BBC` to copyright text for all services

### ISSUE THREAD

**Issue by EinsteinNjoroge** [bbc/simorgh#2667]
**Is your feature request related to a problem? Please describe.**
The word `BBC` doesn't appear in the copyright text for some services.
consider these two screenshots from `igbo` and `russian` service respectively. Note that one has the word `BBC` in the copyright text and the disclaimer while the other only has `BBC` in the disclaimer.
(_NB: I used google translate to display them in English_)

![Screen Shot 2019-07-23 at 11 16 28 AM](https://user-images.githubusercontent.com/21374761/61695279-e51bf080-ad3b-11e9-8261-fc91c3aba1cb.png)
![Screen Shot 2019-07-23 at 11 16 19 AM](https://user-images.githubusercontent.com/21374761/61695280-e51bf080-ad3b-11e9-8ab6-8781e70a2c74.png)

**Describe the solution you'd like**
There needs to be the `BBC` mentioned twice. The first mention is for the `BBC.` in `© 2019 BBC. ` and the second mention for the disclaimer sentence. e.g. for Russian it should be `'Би-би-си. Би-би-си не несет ответственности за содержание других сайтов.',`
This then shows up online as `© 2019 Би-би-си. Би-би-си не несет ответственности за содержание других сайтов.',` 

**Describe alternatives you've considered**

**Testing notes**
Since this is a translation fix, just a visual regression should be sufficient. We should separately have an issue to add automated visual regression checks, but that shouldn't be in this ticket.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
Raised from https://github.com/bbc/psammead/issues/934

**Comment by paruchurisilpa** [comment]
Regression looks good to me..
