### ISSUE TITLE
Create a Simorgh NPM

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#269]
**Is your feature request related to a problem? Please describe.**
One of the goals of Simorgh is cross team usability. We at R&L would like to start using Simorgh as part of our projects, since we don't want to repeat the work done by Articles. We want to make use of the UX styling that is already in place as part of development.

**Describe the solution you'd like**
Add a build step to create an npm package and publish it to a repository that the entire business can pull from. Since this project is open source you could just make it publicly visible on npm, but a private repo will do the trick as well.

**Comment by dr3** [comment]
This will be done as a separate, extracted library https://github.com/bbc/SPArtacus, closing as not needed
