### ISSUE TITLE
Add duration translations to service configs

### ISSUE THREAD

**Issue by ghost** [bbc/simorgh#2695]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/pull/2640 we will have duration descriptions. Currently it defaults to english duration descriptions. We need to have translations for other services.

**Describe the solution you'd like**
Add `durations` translations in service configs and use them in offscreen text
```js
const translations = {
  s: '{x} second',
  ss: '{x} seconds',
  m: '{x} minute',
  mm: '{x} minutes',
  h: '{x} hour',
  hh: '{x} hours',
};
```

Note: The placement of duration may vary from service to service. i.e in swahili duration is in the format.
```js
const translations = {
  h: 'Saa {x}',
  hh: 'Masaa {x}',
  m: 'Dakika {x}',
  mm: 'Dakika {x}',
  s: 'Sekunde {x}',
  ss: 'Sekunde {x}',
};
```

**Testing notes**
[Tester to complete]

Dev insight: Ensure translations are correct.

**Comment by ghost** [comment]
What milestone is this?

**Comment by ghost** [comment]
We could use `moment` translations available on `relativeTime`, but we would end up with 

<img width="556" alt="Screenshot 2019-07-30 at 13 12 49" src="https://user-images.githubusercontent.com/48688870/62121421-3a23ad80-b2cc-11e9-8d56-10bbfcba910c.png">

**Comment by ghost** [comment]
It gets worse when we have `1.01`. That would be `a minute just some seconds`.It looks like we need the translations for `second` only.

**Comment by ghost** [comment]
If `moment` would fix https://github.com/moment/moment/issues/5170 we will be in luck and use the translations added for `second`

**Comment by j-pendlebury** [comment]
Waiting for translations from editorial

**Comment by DenisHdz** [comment]
Closed in favour of https://github.com/bbc/simorgh/issues/2996
