### ISSUE TITLE
Use duration translations

### ISSUE THREAD

**Issue by ghost** [bbc/simorgh#2698]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/issues/2695 we will have duration translation. We need to use those translations in components that require descriptive durations. Like `LinkContents`

**Describe the solution you'd like**
Pass translations to components that require descriptive durations. Such that we have the durations localised per `service` 

**Testing notes**
[Tester to complete]

Dev insight: Assertion test

**Comment by j-pendlebury** [comment]
Work will be done in https://github.com/bbc/simorgh/issues/2695
