### ISSUE TITLE
Social Headline needs to be added to all data scenarios 

### ISSUE THREAD

**Issue by PaulChinkwende** [bbc/simorgh#270]
**Is your feature request related to a problem? Please describe.**
socialHeadline is defined a required field however it is missing from the data scenarios homed in https://github.com/bbc/simorgh/tree/latest/data .This is causing our scenarios to fail against our validator.

**Describe the solution you'd like**
As this is defined as a required property within our schema I would expect this to be a value at all times.

**Describe alternatives you've considered**
If social headline is not required the schema needs to be changed.

**Comment by jimjohnsonrollings** [comment]
Social Headline is an optional field.  Would you like it with null values in the scenarios for now?

**Comment by PaulChinkwende** [comment]
I think we can close this issue actually because if a field is optional, but does not contain any data we would prefer it to simply not exist for the scenario rather than being null.
