### ISSUE TITLE
Handle the fact that ares timestamps might be seconds OR millis

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#2710]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/10963046/61790407-ff72ce80-ae0e-11e9-9764-8503bf7b0d4c.png)
(Context: Ares timestamps should be in milliseconds. Due to a bug, they released with most being in seconds. At some point in the future, they will transition to all being in millis)

**Describe the solution you'd like**
Tolerate either timestamp. This way we won't block their fix going live, which will hopefully allow it to happen sooner.
This sort of hackery already exists in simorgh - see https://github.com/bbc/simorgh/blob/88c47b1c35d9ca6921eacca6e76a91aa488428d5/src/app/lib/analyticsUtils/index.js#L143-L150

Consider extracting this or similar functionality into a common library so that it can be easily identified once ares has removed all seconds timestamps

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Comment by EinsteinNjoroge** [comment]
There's [a hack](https://github.com/bbc/simorgh/pull/2780) to fix this bug, I think the permanent solution should be implemented in Psammead
