### ISSUE TITLE
Multiple console errors when viewing components in Storybook

### ISSUE THREAD

**Issue by david-boydell** [bbc/simorgh#2711]
**Describe the bug**
There are multiple console errors when viewing components in Storybook, found when testing the `latest` branch.

**To Reproduce**

1. Go to http://localhost:9001/?path=/story/articlefigure-amp--with-a-caption
2. View the console errors

**Expected behavior**
No console errors received

**Screenshots**
![image](https://user-images.githubusercontent.com/36667923/61792236-2f70a080-ae14-11e9-8485-0f0330dfd991.png)

**Desktop (please complete the following information):**

- OS: OS SX
- Browser Multiple

**Comment by andrew-nowak** [comment]
Note that the first error "The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type"." is probably not us; it is a known longstanding storybook bug: https://github.com/storybookjs/storybook/issues/6998

**Comment by ghost** [comment]
@david-boydell is the scope of this issue all components in storybook or just `ArticleFigure`? Simorgh has lots of console warnings.

**Comment by david-boydell** [comment]
@sadickisaac, pretty much every one I checked, I used this as an example as it had the most errors.
