### ISSUE TITLE
Use correct Nassim fonts for Arabic, Urdu, Pashto

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2713]
**Testing notes**
**[Tester to complete with developer when issue is picked up]**

**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/issues/2732 we are temporarily going to use NassimPersian for all of APUP.

Once https://github.com/bbc/psammead/issues/735 is done all of the correct Nassim fonts will be available in Psammead, meaning that we can use the correct version of each font for the three remaining Arabic-script services (Arabic, Urdu, Pashto).

respective fonts for each of the services:
```
  F_NASSIM_ARABIC_REGULAR
  F_NASSIM_ARABIC_BOLD
  F_NASSIM_PASHTO_REGULAR
  F_NASSIM_PASHTO_BOLD
  F_NASSIM_URDU_REGULAR
  F_NASSIM_URDU_BOLD
```

**Describe the solution you'd like**
- Similar to how `persian` [does it](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/persian.js) add the correct nassim fontfaces to each of the service configs for Arabic, Urdu and Pashto
- Add screenshots for before and after and get UX to review
- Check if any changes are required to Storybook in SImorgh

**Testing notes**
- Check using DevTools that the correct version of the Nassim font is used on each service's articles
- Check that no other styling is adversely impacted (e.g. inline link changes)
- Test how it looks on older/smaller devices
- Dev and test to decide on best way of providing test coverage for correct font being used

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesdonoh** [comment]
Blocked on https://github.com/bbc/psammead/issues/735 which the Shared Components pod will be picking up following clarification from UX.

**Comment by jamesdonoh** [comment]
Unblocked following that https://github.com/bbc/psammead/pull/1516

**Comment by RayNjeri** [comment]
Awaiting https://github.com/bbc/psammead/pull/1592 && https://github.com/bbc/psammead/pull/1595

**Comment by jimjohnsonrollings** [comment]
Blocking PRs are both merged
