### ISSUE TITLE
Add navigation for all WS sites in Simorgh

### ISSUE THREAD

**Issue by neildoughty** [bbc/simorgh#2729]
**Is your feature request related to a problem? Please describe.**
As a product owner who is thrilled that all the WS home pages are available on TEST, I think it might be beneficial to have the navigation in place on all of them, so the sites are more representative of production.

**Describe the solution you'd like**
I would like the navigation styling which features on the Igbo, Yoruba and Pidgin sites to be available on all the others sites, and I'd like it to be powered by iSite.

**Describe alternatives you've considered**
We could hardcode the nav nodes, but i think that's a bad place to get to. We have navigation config in place in iSite for all WS sites, which is being used by AMP. We should use this information in Simorgh too, making maintenance simpler.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by amywalkerdev** [comment]
All nav has been added to our config files, there is an issue open to look into isite and the best way to retrieve the config details from there https://github.com/bbc/simorgh/issues/1560
