### ISSUE TITLE
Review e2e coverage for APUP

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2731]
**Is your feature request related to a problem? Please describe.**
As we are working on getting article pages for the four Arabic-script services (Arabic, Persian, Urdu, Pashto) finished together we need to ensure that we have core features and behaviour covered by e2e tests.

**Describe the solution you'd like**
- Test engineer to:
  - review existing e2e test coverage for Persian articles
  - identify gaps and areas we want to improve coverage
  - plan how this can be extended to APUP
- Developer and test engineer to:
  - work together to identify what can be/is covered by unit tests and what should be in e2es
- Test engineer to implement e2es with support from developer(s)

**Additional context**
None at present.

Test assets
http://localhost.bbc.com:7080/arabic/articles/c69dvq19k63o
http://localhost.bbc.com:7080/pashto/articles/cng0e8v85eko
http://localhost.bbc.com:7080/urdu/articles/cx621klkm1ro

**Comment by jimjohnsonrollings** [comment]
New Test env assets:
Arabic: clr0em3yzkmo
Pashto: cm53wmz0x39o
Urdu: c2n75x5wrlzo

**Comment by jimjohnsonrollings** [comment]
New Live env assets:
Arabic: c8j91j2ljppo
Pashto: c70970g2251o
Urdu: c4qg7qq63y6o

**Comment by jamesbhobbs** [comment]
NB this should be pretty easy, you should just need to remove hacks currently in place to limit some tests to each service in the /cypress/integrations/pages/articles.js file

**Comment by RayNjeri** [comment]
is this related to #3706 @jamesdonoh ?

**Comment by jamesbrumpton** [comment]
After having investigated with @RayNjeri , we both believe that the current e2es are fine with what components are currently on the APUP sites. The only major difference is that there are instances of a dual timestamp, however this has been taken care of under unit tests, which can be found here https://github.com/bbc/simorgh/pull/3894 .

This ticket will now be closed.
