### ISSUE TITLE
Temporarily use NassimPersian font for Arabic, Pashto, Urdu

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2732]
**Is your feature request related to a problem? Please describe.**
Based on #2503 which was done just for Persian.

Until https://github.com/bbc/psammead/issues/735 is done only the NassimPersian fonts are available in Psammead. As the other Arabic-script sites have the same typography settings as Persian, we should use this font temporarily.

**Describe the solution you'd like**
- Similar to how `persian` [does it](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/persian.js) add the Nassim Persian fontfaces to each of the service configs for Arabic, Urdu and Pashto
- Check if any changes are required to Storybook in SImorgh

**Testing notes**
 - unit tests to show that nassim works for those services
 - update snapshots
 - manual regression

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesdonoh** [comment]
Blocked on https://github.com/bbc/simorgh/issues/2503

**Comment by RayNjeri** [comment]
@jamesdonoh following work from this PR https://github.com/bbc/psammead/pull/1516, if merged should we revert to using the respective fonts availed for each of the services?? ie 
```
  F_NASSIM_ARABIC_REGULAR
  F_NASSIM_ARABIC_BOLD
  F_NASSIM_PASHTO_REGULAR
  F_NASSIM_PASHTO_BOLD
  F_NASSIM_URDU_REGULAR
  F_NASSIM_URDU_BOLD
```

**Comment by RayNjeri** [comment]
Following works on this PR https://github.com/bbc/psammead/pull/1516 there is no need on temporarily using the NassimPersian fonts.
