### ISSUE TITLE
Redirected too many times on /uzbek.amp

### ISSUE THREAD

**Issue by david-boydell** [bbc/simorgh#2743]
**Describe the bug**
/uzbek.amp is not loading, Chrome reports that there are too many redirects. It seems to be directing us between https://www.test.bbc.co.uk/uzbek.amp and https://www.test.bbc.com/uzbek.amp and then back again.

Identified whilst running a cypress test - so steps to recreate are in cookieBannerWS.js.

**To Reproduce**

1. Go to https://www.test.bbc.co.uk/uzbek.amp
2. Browser reports that there are too may redirects

**Expected behavior**
Page loads, redirects are sane.

**Screenshots**
![image](https://user-images.githubusercontent.com/36667923/61950961-69be7700-afa7-11e9-9c0c-881ce98014e5.png)

**Desktop (please complete the following information):**

- OS: OS X
- Browser Any
- Version na

**Comment by jamesbhobbs** [comment]
Fixed
