### ISSUE TITLE
Integrate index alsos

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#2752]
Blocked on https://github.com/bbc/psammead/issues/1512
WSFRONTPGS-84

Add Index Alsos.
Pull in package created in https://github.com/bbc/psammead/issues/1512
The data for each Index Also is found in the `relatedItems` field of the item in the data.
You should cap the number of Index Alsos at 3.

If the related article is of type "cpsType": "MAP",  with no `mediaType` field
then show a video icon

If the related article is of type `cpsType: "MAP"`, 
and `mediaType: "Video"` then show the video icon

If the related article is of type `cpsType: "MAP"`, 
and `mediaType: "Audio"` then show the audio icon

You will need to add translations for 'Related Content' to the service config - these may be available in the config for the old site (ongoing question)
If there are more than one items of related content, they should be contained within an html list.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ghost** [comment]
What milestone is this?
