### ISSUE TITLE
Integrate section labels with links

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#2753]
WSFRONTPGS-80
~~Blocked on https://github.com/bbc/psammead/issues/1513~~

**Is your feature request related to a problem? Please describe.**
Pull in the updated psammead-section-label from https://github.com/bbc/psammead/issues/1513.

Render a section label with a link when the strapline contains `"type": "LINK"`.
The data for the link is contained in the `links.mobile` key of the strapline. Do not use any other of the links contained in the `links` object.

**Accessibility acceptance criteria**

Given I use a screen reader
When I navigate to a section heading level 2 (on an index page)
And this is a link
Then this includes visual CTA text ‘See all’
And the announced text does not include CTA text ‘See all’

Given I use a screen reader
When I navigate to a section with promos and the section has CTA text ‘see all’ (on an index page)
Then a region landmark must be announced e.g. Region
And this must be announced with a label e.g. Top stories
And the label must be unique to the page
And this must not include the CTA text ‘see all’

Given I use a keyboard only
When I navigate to a section heading level 2 link by pressing the TAB key (on an index page)
And this includes visual CTA text ‘see more’
Then there must be one focusable element
And this must have visible state change on focus
And this must not be identified by colour alone
And this must be in addition to the browser default focus outline styling

Given I use a mouse
When I hover over a section heading level 2 link (on an index page)
And the mouse cursor changes from a pointer to a hand
Then this includes the section heading and visual CTA text ‘See all’
And the link must have a visible state change
And this must not be identified by colour alone

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ghost** [comment]
What is this blocked by?
