### ISSUE TITLE
Add fixture data for liveradio pages

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#2754]
**Is your feature request related to a problem? Please describe.**
We have requested that for consistency Ares should return static data for the live radio pages. This data should mimic the necessary values we need in the data response to build the full page. This will be some but not all of the fields specified in:
- [metadata](https://github.com/bbc/simorgh/blob/latest/data/afrique/frontpage/index.json#L2-L41)
- [promo](https://github.com/bbc/simorgh/blob/latest/data/afrique/frontpage/index.json#L4215-L4221)
- [relatedContent](https://github.com/bbc/simorgh/blob/latest/data/afrique/frontpage/index.json#L4222-L4236)
- content - see a data payload

**Describe the solution you'd like**
Add a fixture data asset for each service_id under the matching service, for liveradio.

**Describe alternatives you've considered**
N/a

**Testing notes**
[Tester to complete]

Dev insight: No testing required 

**Additional context**

**Comment by ryanmccombe** [comment]
This does seem mostly blocked by the lack of fixture data

**Comment by ryanmccombe** [comment]
Blocked until we confirm our data requirements
