### ISSUE TITLE
Preconnect for ati domain

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#2759]
**Is your feature request related to a problem? Please describe.**
Lighthouse screenshot of an article page - we should add a preconnect link for the ATI domain. <img width="825" alt="Screen Shot of lighthouse - preconnect" src="https://user-images.githubusercontent.com/3028997/62033231-6c0d1500-b1e3-11e9-9f6f-e8dd5c900be6.png">

**Describe the solution you'd like**
- Add the ATI domain to the list of asset domains (which should change depending on 
- When running lighthouse, we should no longer get the warning in the screenshot above. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests updating should be sufficient. 

**Additional context**

**Comment by dr3** [comment]
The message in the screenshot above says
>to establish early connections to important third-party origins

Is this what ATI is to us? Do we care that the beacon is sent ASAP? The words "early" and "important" arnt something I would describe our ATI beacon as needing to be. Preconnecting has a weight, we shouldnt do it for everything IMO.

Would be more fruitful IMO to workout why lighthouse thinks we would 'save' 300ms by doing this. Save what? is it blocking something else?

**Comment by pjlee11** [comment]
I think it depends on how product expect ATI’s behaviour to work. Should it instantly track the page view or can it be after initial page load. What about bounce rate tracking, how quickly do we need tracking beacons to fire?

I agree we should look into why lighthouse thinks this would save 300ms, this concerns me that ATI could currently be blocking other resources. Unless lighthouse is saying 300ms on the total load time, which then again should be evaluated against the TTFB and TTFP metrics when the preconnect is added

**Comment by sareh** [comment]
@dr3 The estimated time saved is an approximation. Adding a Preconnect link can in certain browsers remove the costly round-trips for DNS, TCP, and TLS https://www.igvita.com/2015/08/17/eliminating-roundtrips-with-preconnect/
