### ISSUE TITLE
Automate minor version number bumps 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#276]
**Is your feature request related to a problem? Please describe.**
Following the SemVer syntax we will soon be bumping the package version number per PR. As we are aiming to have small incremental PRs we will frequently conflict on minor version bumps as we merge in PRs

**Describe the solution you'd like**
Automate version bumping so that any minor bump is done outside of the code change and therefore removes any conflicts on version numbers.

**Describe alternatives you've considered**
N/A

**Additional context**
There seems to be open source libraries that do this that we could utilise

**Comment by dr3** [comment]
Closing as not needed, can reopen if we decide it to be useful
