### ISSUE TITLE
Simorgh server issues 200 response for URLs that don't exist

### ISSUE THREAD

**Issue by radiocontrolled** [bbc/simorgh#277]
**Describe the bug**
When the simorgh server is started and hit with a request for a resource that shouldn't exist, it will issue a 200 response code and html payload

**To Reproduce**
1. Do `npm run dev`
2. curl a url that shouldn't exist, e.g. `curl http://localhost:7080/icecream -I`

for example: 

```curl http://localhost:7080/icecream -I
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 3188
ETag: W/"c74-2fQtTo3bieUDuHkpvKvVZtUF61w"
Date: Wed, 11 Jul 2018 13:23:58 GMT
Connection: keep-alive
```

**Expected behavior**
I imagine it should return a 404.

**Comment by jtart** [comment]
Fixed in https://github.com/jaredpalmer/after.js/pull/160
