### ISSUE TITLE
Use latest version of dependency-check package

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#2779]
**Is your feature request related to a problem? Please describe.**
as a part of #2778 we locked the dependency-check package to an older known working version.

**Describe the solution you'd like**
To be able to use the latest version of the dependency-check package https://github.com/dependency-check-team/dependency-check/releases

**Describe alternatives you've considered**

**Testing notes**
Doesn't require testing effort from tester.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by thekp** [comment]
![image](https://user-images.githubusercontent.com/30599794/62768824-a0a88880-ba8f-11e9-8440-63d5b249b2a0.png)

**Comment by thekp** [comment]
dependency-check is being used here: https://github.com/bbc/simorgh/blob/latest/package.json#L23

you can run independently from that script by running: `npx dependency-check ./package.json`

this issue should be to find out what changes they've made in their API and update our implementation of the script to work with their new changes.

**Comment by samora** [comment]
It seems `dependency-check`isn't working as expected. I found another lib, [depcheck](https://www.npmjs.com/package/depcheck), which seems to do the same thing with better results. See output when I run it against the simorgh source.

<img width="388" alt="Screen Shot 2019-10-17 at 7 19 47 AM" src="https://user-images.githubusercontent.com/2126634/66986491-8f42b480-f0ae-11e9-9778-d6cb1e4c0f95.png">

**Comment by samora** [comment]
<img width="864" alt="Screen Shot 2019-10-22 at 4 17 59 AM" src="https://user-images.githubusercontent.com/2126634/67259007-03040900-f483-11e9-80df-74054f7391f7.png">
Not even merged in, and it's catching stuff from changes in latest.
