### ISSUE TITLE
env for Amp showing as "test" locally

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#2787]
**Describe the bug**
`env` in the request context for amp pages always shows as `test` locally, this should be fixed to show the correct env enabling us target the right environment in code.

**To Reproduce**

1. run `npm run dev` locally
2. log the value of `env` in the request context
3. view amp page article on your browser eg. http://localhost.bbc.com:7080/news/articles/c0g992jmmkko.amp
4. see that the value of `env` is test (which shouldn't be the case)

**Expected behavior**
`env` should show as `local` locally, `test` on test.bbc.com and `live` on bbc.co.uk

**Additional context**
n/a

**Comment by dr3** [comment]
This is due to https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/getOriginContext/index.js#L10, I believe @hindsc52 is looking at changing this back to localhost?

**Comment by chris-hinds** [comment]
After speaking with Rowland he has tested this is change is going to work on a fix to remove the hardcoding of the BBC origin and ensure this change does not affect the current analytics functionality
