### ISSUE TITLE
SPIKE: Event tracking for front pages

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#2788]
WSFRONTPGS-175

**Is your feature request related to a problem? Please describe.**
SPIKE into event tracking for WSFPs

**Describe the solution you'd like**
We track events

**Describe alternatives you've considered**
No tracking

**Testing notes**
[Tester to complete]

Dev insight: Unit tests

**Additional context**

**Comment by sareh** [comment]
In file [atiUrl/index](https://github.com/bbc/simorgh/blob/636080eb4aa1a2417ece9995dc4eb5348d6cdb25/src/app/containers/ATIAnalytics/atiUrl/index.js#L20) you can export a `atiLinkTrackingParams` in the same way we have a `atiPageViewParams`, re-using the methods that are shared between them. 

For the AMP implementation, you can extend [`ampAnalyticsJson`](https://github.com/bbc/simorgh/blob/5cb6f65f988c0f04dd888bfdadf9c3eb7f65d2d5/src/app/containers/ATIAnalytics/amp/ampAnalyticsJson.js#L13) to include a new key/value pair
With an `on` `click` trigger. Documentation is here: https://amp.dev/documentation/components/amp-analytics/?referrer=ampproject.org#triggers

**Comment by j-pendlebury** [comment]
it's a spike, so I'm removing the refinement needed label.

**Comment by jamesbhobbs** [comment]
https://github.com/bbc/simorgh/issues/3365 and https://github.com/bbc/simorgh/issues/3366 questions created from this spike
