### ISSUE TITLE
Refactor Default PropTypes

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#279]
**Is your feature request related to a problem? Please describe.**
Currently Default PropTypes are defined in `./src/app/models/proptypes.js`, whereas PropTypes are defined in component directories `./src/app/models/propTypes/headline/index.js` (as a result of PR https://github.com/bbc/simorgh/pull/264)

I would expect the solution to define default PropTypes in these same directories, so that the `/models/proptypes.js` file can be removed.

**Comment by sareh** [comment]
Blocked pending https://github.com/bbc/simorgh/pull/264/files being merged.

**Comment by ChrisBAshton** [comment]
+1. Would love to see our use of `propTypes` simplified. NB: #264 is merged now, so no longer blocked.

**Comment by sareh** [comment]
Closed as fixed.
