### ISSUE TITLE
Enable Chartbeat toggle on live

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#2806]
**Is your feature request related to a problem? Please describe.**
Once Chartbeat is working properly on test, we should flip the Chartbeat toggle to enable it on live.

**Describe the solution you'd like**
Change this boolean to `true` to enable Chartbeat analytics on live.
https://github.com/bbc/simorgh/blob/fce62cd9cc63cbe5af0147d258f30e9073acaa08/src/app/lib/config/toggles/index.js#L20-L22

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**DEPENDS ON** 
Chartbeat testing https://github.com/bbc/simorgh/issues/2808 

**Additional context**

**Comment by jamesdonoh** [comment]
Blocked on https://github.com/bbc/simorgh/issues/2808 but PR can be opened as it's straightforward
