### ISSUE TITLE
Move the translations for ContentTitle and SubTitle from the service config to the AReS payload

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#2810]
Phil has added the translations to the service config 

We need to move to the fixtures and AReS payload eventually 

Ensure translations appear on the page after the changes are made 

WSMEDIA-21

**More specifics:**

We currently have the translations used in the Live radio pages stored in the service config, eg, here for Indonesian Radio:

https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/indonesia.js#L117-L121

This ticket is to move these into the fixtures / ARES payload, eg, here:

https://github.com/bbc/simorgh/blob/latest/data/indonesia/bbc_indonesian_radio/liveradio.json

Then update the component here to reflect that the translations are now coming from `pageData` instead of `serviceContext`:

https://github.com/bbc/simorgh/blob/latest/src/app/containers/MediaPageMain/index.jsx

**Comment by ryanmccombe** [comment]
@graemelindsayBBC @jroebu14 updated description with more details
