### ISSUE TITLE
Get inspectpack dep patched as it has a medium priority vulnerability

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2812]
**Is your feature request related to a problem? Please describe.**
Our dep Inspectpack has a dep (yargs) that has a vuln and needs updating.

**Describe the solution you'd like**
https://github.com/FormidableLabs/inspectpack/issues/118

**Describe alternatives you've considered**
n/a, should be fixed or we should stop using inspectpack

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by hotinglok** [comment]
Currently using the latest version with the patch, closing as this is now resolved.
