### ISSUE TITLE
Update ATI (analytics) for Arabic, Urdu, Pashto articles (and producers for all WS services)

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#2839]
**Is your feature request related to a problem? Please describe.**
We should ensure that the WS Languages stats destination values are used for World Service sites.

We already did this for Persian in https://github.com/bbc/simorgh/issues/1699 and so the requirement may already be covered by that work - this issue is to test this and do any further dev work that may be required (which may be none).

There is a Chrome plugin called ATI Tag Inspector that can be used to verify the values we are sending. An ATI login is also required - please speak to @jimjohnsonrollings or @lizcameron for more information.

We should also ensure we pass in all of these fields for Arabic:

Field | Value
-- | --
Destination (s) | WS_NEWS_LANGUAGES: 598342 (live), 598343 (test)
Producer | 5
Chapter | Null
Page (p) | arabic.articles.c0000000000o.page
appName (x3) | news-arabic

These for Urdu:

Field | Value
-- | --
Destination (s) | WS_NEWS_LANGUAGES: 598342 (live), 598343 (test)
Producer | 95
Chapter | Null
Page (p) | urdu.articles.c0000000000o.page
appName (x3) | news-urdu

These for Pashto:

Field | Value
-- | --
Destination (s) | WS_NEWS_LANGUAGES: 598342 (live), 598343 (test)
Producer | 68
Chapter | Null
Page (p) | pashto.articles.c0000000000o.page
appName (x3) | news-pashto

**Describe the solution you'd like**

**Describe alternatives you've considered**
N/A

**Testing notes**
Testing required here will be making sure that the responses found within the ATI terminal (Chrome Plugin) are as expected for both AMP & Canonical.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by 12** [comment]
I created a series of test assets in each of these services
**Arabic:** https://www.test.bbc.com/arabic/articles/cde17exw0xko
**Pashto:** https://www.test.bbc.com/pashto/articles/ckrw3rkwxnko
**Urdu:** https://www.test.bbc.com/urdu/articles/cmw3zwxven5o
**Persian:** https://www.test.bbc.com/persian/articles/cx8398z5nk4o

On **`TEST`**, all of these services are reporting to the site `598343` which maps to `WS_NEWS_LANGUAGES_TEST` (which is correct as above).

![image](https://user-images.githubusercontent.com/7690572/62204735-b4fccf00-b385-11e9-998b-5d9f183554d0.png)

**Comment by 12** [comment]
Testing this for live is blocked on routing and STM changes.

bbc/simorgh-infrastructure#434

**Comment by HarveyPeachey** [comment]
Currently the logic for ATI analytics isn't sending producer ID's, I've opened a pull request to fix this  and I'm going to add the relevant ID's for all the planned WS sites for future proofing as described in the pull request.

**Comment by HarveyPeachey** [comment]
Blocked until #2995 is resolved

**Comment by jamesbhobbs** [comment]
reopened due to https://github.com/bbc/simorgh/pull/3336

**Comment by jimjohnsonrollings** [comment]
@benjaminhobbs could you elaborate on why this one needed to be reverted as well? This one (I thought) only dealt with producers whereas the error you mention on the other issue is with destinations. Ta

**Comment by jamesbhobbs** [comment]
@jimjohnsonrollings apologies reopened in error
