### ISSUE TITLE
Question: how can we determine the performance effect of loading the Reith font on our sites?

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#2848]
The BBC Reith font is now available to be used for Latin and Cyrillic languages. 

We need to decide which services to use the font on, ensuring that we do not significantly effect the performance of the sites in places where the connection is bad.  We are assuming there are places in the world we should not increase the page weight at any cost, for example our services in Africa. 

We need to decide whether to use the font in places where connection is patchy, for example Indonesia, and to do this it would be useful to understand the impact of loading the font. 

**For discussion:** 
- can we compare the performance of a page on Simorgh that loads the Reith font vs not loading the font?
- can we do this without putting the Reith font live? 
- do we need RUM to do this effectively?

**But Clare, why do we need the font at all?** 
The font has been specifically designed to be very readable and accessible online. It will help with BBC brand attribution and therefore is part of the brand strategy.

**Comment by ghost** [comment]
The performance of loading the `Reith` font can be tested locally with `slow 3G` connection simulation in chrome. `http://localhost.bbc.com:7080/news` 

There are two key metrics that should not be overlooked
- How long does it take for text to be visible
- How many reflows happen after the font has been loaded and how that affects the user.
