### ISSUE TITLE
Create examples in comments for prop types

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#285]
**Is your feature request related to a problem? Please describe.**
It is not clear what structure the prop types generate.

**Describe the solution you'd like**
We should add comments that give a definition of what prop types look like. This is for [specifically defined prop types](https://github.com/bbc/simorgh/blob/latest/src/app/models/propTypes/headline/index.js#L8-L11), and also the [general utility prop types](https://github.com/bbc/simorgh/blob/latest/src/app/models/propTypes/general/index.js)

**Comment by ChrisBAshton** [comment]
Would this be superseded by #279?

**Comment by jamesbhobbs** [comment]
Most prop types are moved to psammead
