### ISSUE TITLE
ArticleMain story fails to render

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#2853]
**Describe the bug**
The ArticleMain story is failing to render due to not being able to access toggleState. Parts of the article now rely on having access to feature toggles, these are provided by the ToggleContext provider.

**To Reproduce**

1. Go to 'https://bbc.github.io/simorgh/?path=/story/containers-article-article-main--default'
2. See error

**Expected behavior**
The ArticleMain story should render

**Screenshots**
https://bbc.github.io/simorgh/?path=/story/containers-article-article-main--default

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bopchy** [comment]
This has been fixed here - https://github.com/bbc/simorgh/pull/2800
