### ISSUE TITLE
Cypress tests - Error pages on Test

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#2862]
**Is your feature request related to a problem? Please describe.**
After these tickets have been completed: https://github.com/bbc/simorgh/issues/2639 https://github.com/bbc/simorgh-infrastructure/issues/598 https://github.com/bbc/simorgh-infrastructure/issues/599 we should have error pages available on the Test environment for a small set of services - ideally one RTL (arabic) one LTR (mundo) one with with variants (zhongwen)

Then we should add Cypress tests to check that the 404 pages are working for these services. 

**Describe the solution you'd like**
Add example assets for Arabic, Mundo, Zhongwen to the Cypress config for `errorPage404` on TEST. https://github.com/bbc/simorgh/blob/48ad08c8d9170f017bbdaea1c562e7da8c72c210/cypress/support/config/services.js#L30

**Describe alternatives you've considered**
N/A

**Testing notes**
- Make sure that tests run against the error pages as expected
- Make sure that the current `errorPage.js` tests don't fail
- Add any e2es that are missing

Dev insight: Cypress tests for the Test environment only. We do not yet have STMs set up on LIVE. 

**Additional context**
N/A

**Comment by 12** [comment]
This will be resolved be #2911

**Comment by jimjohnsonrollings** [comment]
Given @12's comment, can this be closed now? (@jamesdonoh )

**Comment by jamesdonoh** [comment]
@jimjohnsonrollings this still needs doing but is blocked on the issues mentioned in the description.

**Comment by joshcoventry** [comment]
Replaced by new parent issue, will require refinement: https://github.com/bbc/simorgh/issues/7815
