### ISSUE TITLE
No static assets on local production builds

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#2864]
**Describe the bug**
Following the instructions on the Simorgh [README](https://github.com/bbc/simorgh/blob/latest/README.md#using-environment-builds-locally) to get a production build running locally, I've noticed that the client-side JS bundles are 404'ing. This means that when we run the production build locally, we are not getting any JS.

This means we cannot test production builds 

**To Reproduce**

1. Follow steps in [the README](https://github.com/bbc/simorgh/blob/latest/README.md#using-environment-builds-locally)
2. View an article
3. Open console
4. See error in console

**Expected behavior**
All JS bundles should load with no error.

**Additional context**

**Comment by dr3** [comment]
Issue - APP_ENV is used here https://github.com/bbc/simorgh/blob/latest/src/server/index.jsx#L82 to serve static assets

BUT ALSO

APP_ENV=local is used to decide the assets-live.json

SO 
APP_ENV=local -> Serves assets but theyre local
APP_ENV=live -> Doesnt serve assets, but tries to use live ones

**Comment by chris-hinds** [comment]
Blocked on finding out the desired use-case for this functionality.

**Comment by jamesbhobbs** [comment]
I don't understand this, local production builds should surely use local static files, no? Else how would we make changes to them before deploying them?

**Comment by 12** [comment]
Checked this again locally, and appears to be working again. Therefore closing this issue.
