### ISSUE TITLE
Parallelize running the chromatica tests

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#2866]
**Is your feature request related to a problem? Please describe.**
We should parallelize as much of the simorgh pipeline as possible

**Describe the solution you'd like**
Move running of chromatica to a separate build step that runs in parallel with everything else.

**Describe alternatives you've considered**
Democracy is non negotiable

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by chinds185a** [comment]
This should be good to do as long as we not need to build storybook within the simorgh pipeline for anything else as chromatic uses our exiting script to build storybook

**Comment by chris-hinds** [comment]
This is done in Psammead and will be completed in simorgh once we have B/G deployments
