### ISSUE TITLE
Add lightweight readmes to the base of all major directories

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#2873]
**Is your feature request related to a problem? Please describe.**
In https://github.com/bbc/simorgh/pull/2870 we removed the components and containers readmes. They were verbose and inconsistent in that they were the only ones which existed.

This leaves us with no readmes at the bases of important directories

**Describe the solution you'd like**
Supplement the primary documentation with a sentence of two in a readme at the base of every major directory. Emphasis should be on brevity and maintainability of these files.

**Describe alternatives you've considered**
Leave with no readmes, which is adequate but perhaps not ideal - it would be better than out of date documentation though

**Testing notes**
No testing needed this is just markdown files

**Additional context**
We should probably refer to how we work between psammead and simorgh more.

**Comment by jamesbhobbs** [comment]
I'd like to review this, someone please contact me IRL once this is drafted.

**Comment by benjaminhobbs** [comment]
The readme https://github.com/bbc/simorgh/tree/latest/cypress/integration should be used as a model for such readme (as I am not a humble man). Thanks for @oluoluoxenfree for suggested improvements to it though.
