### ISSUE TITLE
Chartbeat script tag rendered twice

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#2878]
**Describe the bug**
When Chartbeat is enabled, after client render there are two `script` tags that load Chartbeat in the DOM instead of one.

**To Reproduce**

1. Go to a page where Chartbeat is enabled, e.g. https://www.test.bbc.co.uk/news/articles/c0g992jmmkko
2. Look in dev tools at elements
3. See that Chartbeat script tag exists twice

**Expected behavior**
The Chartbeat script tag should not be in the DOM twice.

**Screenshots**
![Screenshot 2019-08-02 at 15 12 34](https://user-images.githubusercontent.com/11161809/62376197-02b93900-b538-11e9-8f59-067ef3fad17a.png)

**Additional context**

**Comment by 12** [comment]
This was resolved in #2837.
