### ISSUE TITLE
Capitalise initial character of relative timestamp

### ISSUE THREAD

**Issue by david-boydell** [bbc/simorgh#2890]
**Is your feature request related to a problem? Please describe.**
Currently the first character of the relative timestamps is not capitalised. We should be capitalising the first character I think.

**Describe the solution you'd like**
Timestamps for articles that have been published less than 10 hours ago should have a capitalised initial character 

**Describe alternatives you've considered**
None

**Testing notes**
You can test this by going to https://www.epochconverter.com/ and creating a new timestamp to put into the fixture data.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
Currently this is what is displayed for e.g. igbo

![image](https://user-images.githubusercontent.com/36667923/62470389-40190300-b792-11e9-928d-2c72ad7fceb3.png)

**Comment by jamesbhobbs** [comment]
Before anyone works of this please make certain for which services this is true as part of refinement.
