### ISSUE TITLE
Fix chromaticqa false negative tests for FF

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#2891]
**Is your feature request related to a problem? Please describe.**
We have chromaticqa tests running on our CI pipeline.Its a visual regression tool compares snapshots of components on a branch against the baseline images and throws an issue if there is a difference.It's being enabled for all three browsers(Chrome,FF and IE11).Chrome and IE11 are very stable but not the case for firefox(there are differences in snapshots because the snapshots are taken before the images were loaded)

**Describe the solution you'd like**
Adding a delay is the only solution i can think of which is not ideal.Biut we could add delays to specific components containing images using the example mentioned here.http://docs.chromaticqa.com/delay

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by hotinglok** [comment]
Externally blocked on ChromaticQA, @PriyaKR will attach extra issues to mitigate this on the simorgh end.

**Comment by PriyaKR** [comment]
Need to look into this issue once this [https://github.com/bbc/simorgh/issues/3002](url) and the same for image assets has been done.

**Comment by hotinglok** [comment]
Closing as we're not currently running against FF
