### ISSUE TITLE
Replacing Moment.js and Moment Timezone

### ISSUE THREAD

**Issue by gabriellorin** [bbc/simorgh#2898]
**Is your feature request related to a problem? Please describe.**
To render timestamps and convert to various time zones, we're currently using `Moment.js` and `Moment Timezone`.

On the client, these libraries weight around 59KB (minified, no gzip). We're only using a fraction of the features, and because of the way the libraries are organised and how tightly coupled they are, it would seem like we can't easily tree shake them.

**Describe the solution you'd like**
After taking a small look at which features we're using, and re-creating these features in vanilla js, it would seem like we could create a tiny library, tree shakable, and to save dev time, re-using as much from `Moment.js` and `Moment Timezone` as possible. We could re-use: the locales (although just keeping the actual locale data, not the helper functions, etc), and the timezones data (exporting each timezone separately; did a small test exporting all timezones to single file with ES modules named exports: https://gist.github.com/gabriellorin/5f1c827151f203eb48522e7116019182).

Because the data would then be decoupled from `Moment.js` / `Moment Timezone`, we could import the correct locale data as well as timezone data and set it as new properties on each service config object. This data could then be accessed more easily from the rest of the code.

(For example in the `news` service config, we currently import the locale as `import 'moment/locale/en-gb';`. After extracting the data from the Moment locales, we could import it as `import localeData from 'x/en-gb';` and set it as a new property `localeData: localeData` on the service config object.)

**Describe alternatives you've considered**
Keeping `Moment.js` and `Moment Timezone` 😁

**Testing notes**

Investigation doesn't require testing.

**Comment by amywalkerdev** [comment]
Not worth doing this atm
