### ISSUE TITLE
Fix prop type warnings in src/app/containers/Headings/index.test.jsx 

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#2906]
**Describe the bug**
There are prop type warnings in unit test caused by having no data in function ```HeadingsContainerWithContext()```.
https://github.com/bbc/simorgh/blob/247d0f5be2916f0d145f18dc8e1c93fcc8cec61a/src/app/containers/Headings/index.test.jsx#L72

**To Reproduce**

1. Go to simorgh in terminal
2. Run npm run test:unit
3. Observe prop type warnings:

```js
    console.log src/testHelpers/setupTests.js:26
      IMPORTANT! Soon this test will not pass because React warnings were detected. Please don't add any more tests containing React warnings
      Warning: Failed prop type: The prop `item.summary` is marked as required in `MediaIndicator`, but its value is `undefined`.
          in MediaIndicator
    console.error src/testHelpers/setupTests.js:37
      Warning: Failed prop type: The prop `item.summary` is marked as required in `MediaIndicator`, but its value is `undefined`.
          in MediaIndicator
    console.error src/testHelpers/setupTests.js:37
      Warning: Failed prop type: The prop `item.locators` is marked as required in `MediaIndicator`, but its value is `undefined`.
          in MediaIndicator
```

**Expected behavior**
No prop warnings.

**Testing notes**
No testing required.

**Comment by dr3** [comment]
This is a tricky fix, the test inherently needs to fail prop type checks to work. Could we find a way of selectively disabling prop type warnings when they're expected?

**Comment by thekp** [comment]
https://github.com/bbc/simorgh/pull/2961
suppress warning with this ^

**Comment by thekp** [comment]
https://github.com/bbc/simorgh/issues/3001
duplicate
