### ISSUE TITLE
Investigate how we capture ATI tracking through SMP

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#2910]
We expect this investigation to be carried out once we have the audio player on the page, and is probably more of a testing & analysis task rather than a build task

**Is your feature request related to a problem? Please describe.**
We need to understand how we pass values to SMP to track rich media in ATI 

**Describe the solution you'd like**
A clear understanding of what we need to capture and how we pass properties to SMP for rich media tracking 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
WSMEDIA-26 & WSMEDIA-86 for link to confluence and properties we need to capture 
We will likely pass any values via Morph

**Comment by ryanmccombe** [comment]
SMP settings object is here: https://github.com/bbc/morph-modules/blob/504c116d2d6b257aa7ba447752ae15a6585cd92a/news-av-player/src/smp.js#L30

The values that seem relevant to analytics are: `destination`, `counterName` and `clipPID` - are you familiar with those or know what they should be @aeroplanejane ?

**Comment by aeroplanejane** [comment]
Destination is the Level 1 site e.g. WS_LANGUAGES. `counterName` I don't know what this is and I don't see it as a value we track in ATI - we need to follow up with Articles. `clipPID` in this case I suspect we want to pass the content id - which for live radio will be our service id e.g. bbc_afaanoromoo_radio Values we also want to ensure are passed are `level 2 site` e.g. Afaan Oromoo, Media Type `Audio` Please refer to WSMEDIA-86 @ryanmccombe

**Comment by ryanmccombe** [comment]
Continued convo on WSMEDIA-86 due to reliance on a lot of internal docs

**Comment by aeroplanejane** [comment]
We know what we can pass to SMP through the settings object. What we don't understand is whether SMP will look after the rest, or whether we need to capture this additional data ourselves. Awaiting feedback from SMP, but we may have to pass what we can to SMP when the player is on the pages to prototype. More info on what we pass to settings on WSMEDIA-86
