### ISSUE TITLE
Change date format of timestamp in /StoryPromo/index.jsx

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#2913]
**Is your feature request related to a problem? Please describe.**
Currently, timeFormats.js uses hardcoded formats which only cover mainly latin based languages rendering dates in asian languages for example read incorrectly. 
Eg. 7 七月 2018 in zhongwen from storybook usually reads as 2018年7月7日. 

**Describe the solution you'd like**
Use locale format for multiple locale support (Eg. LLLL found here: https://momentjs.com) instead of hard-coding one single format.

**Additional context**
Files affected:
https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx#L99

**Comment by andrew-nowak** [comment]
We set up the default for hte timestamp container to be 'LL, LT z' (see https://github.com/bbc/psammead/blob/c383b2c5374b6ce7e40fe37472a9b9df1d6695e5/packages/containers/psammead-timestamp-container/src/timestampUtilities.js#L22). One resolution for this ticket could be removing the `format` prop from the StoryPromo container and instead relying upon the default in the timestamp container

**Comment by j-pendlebury** [comment]
More info here https://www.dropbox.com/s/st883m5a8u9hi3a/WS%20Home%20Pages%20%28Live%29.xlsx?dl=0
