### ISSUE TITLE
Add PGL and LIV stories to fixture data

### ISSUE THREAD

**Issue by david-boydell** [bbc/simorgh#2918]
**Is your feature request related to a problem? Please describe.**
We need to add the `cpsType` of PGL and LIV assets to fixture data for testing. Currently the fixture data does not include all of these. One is needed per service to be able to check the translations.

Currently Pidgin alone has LIV:

Igbo: ~PGL~, ~LIV~
Pidgin: ~PGL~, LIV
Yoruba: ~PGL~, ~LIV~

**Describe the solution you'd like**
Have a PGL and a LIV asset type added to each of the services. One services should include a PGL as it's top story, another should have a LIV page as it's top story.

**Describe alternatives you've considered**
None

**Testing notes**
Visual check on localhost on the three services /igbo, /yoruba & /pidgin.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc: Nope

**Additional context**

**Comment by ghost** [comment]
What milestone is this?

**Comment by david-boydell** [comment]
@sallymorales I've added to LIV promos, could be either that or PGL. Apologies.
