### ISSUE TITLE
Header component - mobile layout

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#292]
We should update the Header component to have the markup and CSS required for the mobile layout. 

(Note, no breakpoint-dependent behaviour should be addressed here. Neither should the typography be addressed here. It will be in a future issue.)

The brand SVG should be used. It should work in high contrast mode on a PC and the no-CSS mode should be addressed. 

Here is a description written by @greenc05 on a related issue: (https://github.com/bbc/simorgh/issues/186)
Some points to consider...

**Inline SVG brand logo - Recommended approach**
- Add an attribute of focusable="false" to the svg - Without this, when using Jaws with IE and navigating via the ‘tab’ key, the SVG content is read out twice to screen reader users. This is due to a bug with IE in which it makes all SVGs within links/buttons focusable, resulting in you being able to tab to the link and also to the SVG inside the link, this is also an issue for sighted users using the keyboard to navigate with the tab key who will have to tab twice when encountering a link with an svg inside.
- Add an attribute of aria-hidden="true" to the SVG (title is not reliably supported)
- Use a ‘visually hidden’ (also known as off-screen text) span for the textual equivalent of the SVG
- Even if you are following these recommendations, always thoroughly test your exact implementation

```
<a href="https://www.bbc.co.uk/news">
    <svg focusable="false" aria-hidden="true” …>...</svg>
    <span class="gs-u-vh">BBC News</span>
</a>
```

**High contrast mode on PC**
It's important that the brand logo SVG works with default and custom colour themes, ensure you test this in development.

**No CSS**
If the user doesn’t have CSS (it either hasn't loaded or they have chosen to disable it), it would be awesome if the user can still see the brand logo SVG i.e. a white SVG cannot be seen on a white background. 

The following example code demonstrates how you can display an SVG in black for users without CSS, by specifying an inline fill colour (black) for the SVG which is available if the user doesn’t have CSS (which works on a white background), the colour of the SVG is then changed to white with CSS which can then be seen on the CSS coloured background. An example of how to implement this can be seen here http://2bitstudio.co.uk/code-tests/article/svg-brand.html

![Header at mobile breakpoint 375px](https://user-images.githubusercontent.com/3028997/42679856-36df75a6-867b-11e8-8711-1026e4de7af1.png)

The hover/focus style is defined as a white bar below the BBC News logo.
Please see an example on the navigation items on BBC News home page: https://www.bbc.co.uk/news
Link:
<img width="119" alt="screen shot 2018-07-13 at 09 01 57" src="https://user-images.githubusercontent.com/3028997/42680441-f8c846b0-867c-11e8-9e6d-beb5ec0fa106.png">
Link hover/focus style
<img width="123" alt="screen shot 2018-07-13 at 09 01 45" src="https://user-images.githubusercontent.com/3028997/42680442-f8efba74-867c-11e8-91d5-a368de560ba2.png">

**Note for development**
```
npm install
npm run storybook
```
Then visit http://localhost:9001/?selectedKind=Header to view the Header

**Comment by greenc05** [comment]
@sareh should we look at core first rather than mobile? If you aren't aware the hover/focus styling for the brand logo is defined in the UX documentation

**Comment by jtart** [comment]
Closing for more granular issues.
