### ISSUE TITLE
Footer component - mobile layout

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#293]
We should update the Footer component to have the markup and CSS required for the mobile layout. 

(Note, no breakpoint-dependent behaviour should be addressed here. Neither should the typography be addressed here. It will be in a future issue.)
The work in this ticket should be carried out on the component in Storybook and not incorporated within the article. 

The no-CSS mode should be addressed. 

These links should be in an unordered list, styled with hover and focus colours. 

Label | Link
-- | --
BBC News | https://www.bbc.com/news
Why you can trust the BBC | https://www.bbc.com/news/help-41670342
Terms of Use | http://www.bbc.com/terms/
About the BBC | http://www.bbc.com/terms/
Privacy Policy | http://www.bbc.com/privacy/
Cookies | http://www.bbc.com/privacy/cookies/about
Accessibility Help | http://www.bbc.com/accessibility/
Contact the BBC | http://www.bbc.com/contact/
Copyright © 2018 BBC. The BBC is not responsible for the content of external sites. | not clickable
Read about our approach to external linking | http://www.bbc.com/help/web/links/

Here is a description written by @greenc05 on a related issue: (https://github.com/bbc/simorgh/issues/139)

**List semantics**
Note that VoiceOver strips out the list semantics when using list style none, we should reinstate the semantics by adding role list and role listitem to the mark up:
```
<ul role="list">
    <li role="listitem">Item 1</li>
    <li role="listitem">Item 2</li>
    <li role="listitem">Item 3</li>
</ul>
```

Design for mobile view:
![footer at mobile breakpoint - 375px](https://user-images.githubusercontent.com/3028997/42679674-b2b4f36e-867a-11e8-8fc4-afe3262a1648.png)

**Note for development**
```
npm install
npm run storybook
```
Then visit http://localhost:9001/?selectedKind=Footer to view the Footer

**Comment by greenc05** [comment]
Does mobile cover core @sareh?
