### ISSUE TITLE
Decide if audit-ci license is allowed

### ISSUE THREAD

**Issue by oluoluoxenfree** [bbc/simorgh#2955]
**Is your feature request related to a problem? Please describe.**
Newer versions of audit-ci than 2.1.0 require JSONStream, a package that's archived and has a non standard license.

**Describe the solution you'd like**
Decide if we'll add the new license to our exceptions.

**Describe alternatives you've considered**
- Finding an alternative to audit-ci
- Staying at 2.1.0
- Contacting the audit-ci team

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
I think until we come across a problem with pinning to this version we can consider this won't fix
