### ISSUE TITLE
Update article fixture data to include images, captions and copyright

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2959]
**Is your feature request related to a problem? Please describe.**
Unlike `news` and the APUP services, a lot of the other services' article fixture data currently don't have images (aka 'figures') and image captions, which we test in cypress.

**Describe the solution you'd like**
- Modify all article fixtures that currently do not contain images to include images and captions
- Use an image or images from existing articles for services where the tests currently do run and pass
- Include some images with BBC copyright and some without to allow us to test that copyright is only displayed for non-BBC images
- Ensure articles for all services satisfy the cypress tests for images/captions
- Remove service exclusions from https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/article/canonical.js#L6-L9

**Describe alternatives you've considered**

**Testing notes**
This will not require manual testing.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jimjohnsonrollings** [comment]
As discussed, going to close this and create some new test assets which are designed specifically for Cypress testing, beginning with #3146
