### ISSUE TITLE
Sinhala not rendering article correctly

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2962]
**Describe the bug**
The sinhala article, found here https://www.test.bbc.com/sinhala/articles/c45w255zlexo.json contains the text `ලොව ප්‍රමුඛ පෙළේ විද්‍යාඥයින්ගෙන් සැදුම් ලත් එක්සත් රාජධානියේ රාජකීය සමාජයේ (The Royal Society) සාමාජිකත්වය සඳහා පසුගිය` however this isnt rendered in the article here https://www.test.bbc.com/sinhala/articles/c45w255zlexo

**Expected behavior**
Should render correctly. Will need to dix article data (in ares/optimo?) or fix simorgh?

**Additional context**

**Comment by sareh** [comment]
Should be fixed by this PR: https://github.com/bbc/simorgh/pull/2791

**Comment by jamesbhobbs** [comment]
@sareh @dr3 as that PR is now merged can you pls recheck this issue.

**Comment by RayNjeri** [comment]
Checked on this, the said issue seems to be rendered alright.
This can be closed if there isn't any other objection. cc: @benjaminhobbs @dr3  @sareh 
![Screenshot 2019-09-02 at 1 38 25 PM](https://user-images.githubusercontent.com/27012452/64108961-f7e80300-cd86-11e9-9ab4-74f2b3eec497.png)
