### ISSUE TITLE
Add Thai Navigation

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#2967]
Labels and links for Thai Navigation: 

หน้าแรก https://www.bbc.com/thai
ประเทศไทย https://www.bbc.com/thai/topics/1ed75fd4-f992-46db-9859-fb5a7c95da91
ต่างประเทศ https://www.bbc.com/thai/international
วิทยาศาสตร์ https://www.bbc.com/thai/topics/0f469e6a-d4a6-46f2-b727-2bd039cb6b53
สุขภาพ https://www.bbc.com/thai/topics/c4794229-7f87-43ce-ac0a-6cfcd6d3cef2
วิดีโอ https://www.bbc.com/thai/media/video
ยอดนิยม https://www.bbc.com/thai/popular/read

Please use the existing site for reference if required. 

**Testing notes**
Quick visual check across browsers/screen widths. Cypress tests already exist for nav - ensure that Thai is not excluded.

**Comment by EinsteinNjoroge** [comment]
Will require a tester input.
