### ISSUE TITLE
Confirm the manifest.json is correct for Thai

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#2973]
The links to link to the assets should work (~this is blocked by adding those assets~)
Not sure what else - we should compare to the live ones. 

**Testing notes**
Cypress test exist for manfest.json in `cypress/integration/application(Not Pages)/index.js`. Running these should suffice. Check that the services are not excluded from the Cypress tests.

**Comment by EinsteinNjoroge** [comment]
~~Blocked by https://github.com/bbc/simorgh/issues/2974~~

**Comment by EinsteinNjoroge** [comment]
@clareevansbbc  Confirmed, Thai service loads the correct manifest file and all asset files are available. Cypress test exists and thai service is not excluded from the tests.
![Screen Shot 2019-08-14 at 12 10 16 PM](https://user-images.githubusercontent.com/21374761/63009123-8f46ee00-be8c-11e9-8fd2-1ff7d8bbb273.png)
