### ISSUE TITLE
Add the add to homescreen assets for Thai

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#2974]
Assets provided by UX - currently blocked by this
Should live in the same place (relatively) as the live sites

From Tom:  tiled logo svg's for Phase 1 & 2 are in here, let me know if there's any issues with them https://www.dropbox.com/sh/3jjvvzna4hr8giv/AABs5sRM3APX-ZFPdRe9PScEa/Thai

**Testing notes**
No testing needed, this is just adding assets not changing end user behaviour/features

**Comment by EinsteinNjoroge** [comment]
Blocked awaiting asset files from UX
