### ISSUE TITLE
Naidheachdan doesnt redirect to .com outside the UK

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#2985]
**Describe the bug**
https://www.test.bbc.co.uk/naidheachdan/articles/c18q7nedn2ko doesnt redirect to .com outside the UK

**To Reproduce**

1. Visit https://www.test.bbc.co.uk/naidheachdan/articles/c18q7nedn2ko outside the UK

**Expected behavior**
It redirects to .com

**Additional context**

**Comment by jamesbhobbs** [comment]
Blocked by another BBC team (Belfrage), I am working on removing this blocker.

**Comment by chris-hinds** [comment]
Closing as Simorgh will not be rendering new public service content
