### ISSUE TITLE
Missing icon errors on Arabic/Urdu/Pashto

### ISSUE THREAD

**Issue by RayNjeri** [bbc/simorgh#2987]
**Describe the bug**
There are multiple console errors when viewing articles for arabic, pashto and urdu services and images seem not to be loading on chrome

**To Reproduce**

1. Go to either of these articles:
 http://localhost:7080/arabic/articles/c69dvq19k63o
  http://localhost:7080/urdu/articles/cx621klkm1ro 
 http://localhost:7080/pashto/articles/cng0e8v85eko
2. View the console errors

**Expected behavior**
No console errors received

**Screenshots**
![Screen Shot 2019-08-08 at 11 46 03 AM](https://user-images.githubusercontent.com/27012452/62689100-d471a880-b9d2-11e9-81f4-e3e9ef53ca34.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by rhenshaw56** [comment]
I picked this up and checked! I think these fonts haven't been deployed yet, not sure who to reach out to on these cc @jimjohnsonrollings @jamesdonoh
