### ISSUE TITLE
Basic e2e tests for Live Radio Page 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#2989]
**Is your feature request related to a problem? Please describe.**
The live radio page requires Cypress tests added to CD pipeline to avoid regressions.

**Describe the solution you'd like**
Having a look at our current Cypress tests for front page and article we currently require the following tests:

### Canonical

**Header tests**
- should have a visible banner
- should not have an AMP attribute
- should have one visible navigation
- should have a visually hidden top-level header

**Footer Tests**
- should render the BBC News branding
- should have working links
- should contain copyright text
- should contain a link in the copyright text

**Scripts**
- should only have expected bundle script tags
- should have 1 bundle for its service

**Analytics**
_placeholder for ATI tests_

**Metadata**
- should have the correct lang & dir attributes
- should not have an AMP attribute on the main article
- should have a correct robot meta tag
- should have resource hints
- should have the correct facebook metadata
- should have the correct open graph metadata
- should have the correct twitter metadata
- should include metadata that matches the JSON data
- should include the canonical URL & ampHTML
- should include mainEntityOfPage in the LinkedData

**Live radio specific**
- should render the page title
- should render the page subtitle

### AMP
- should return a 200 response
- should have the metadata
- should have AMP attribute
- should have lang and dir attributes
- should load the AMP framework
- should load the AMP body scripts
- should have any correct amp scripts in the body and the head
- should contain an amp-img
- should include the canonical URL

**Testing notes**
No testing required

**Additional context**

**Comment by aeroplanejane** [comment]
Look at this: https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/frontPage/canonical.js

**Comment by jamesbhobbs** [comment]
This isn't quite done yet, one more PR

**Comment by jroebu14** [comment]
Closed via https://github.com/bbc/simorgh/pull/3401
