### ISSUE TITLE
Support Link Promo type in 'standard' format. 

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#2990]
A link promo is a different type of promo that can have various formats. At first we only want to support the 'standard' format, and it should use the existing Story Promo, as it is. 

See details in WSFRONTPGS-182

**Describe the solution you'd like**
These promos should be displayed using the existing story promo component.
Link Promos have cps type of `PRO`, however the data we receive has a different format than the normal STY.

```
{
  "name": "Ina mọnamọna: Ijọba rawọ bẹ araalu fun ina ọba to lọ lọjọ isẹgun",
  "summary": "Idakureku ina ọba kii se ajeji s'awọn ọmọ orilẹ-ede Naijiria, sugbọn nigba ti gbogbo ina orilẹ-ede yii ba dede ku lọwọkannaa, ko le sai fa awuyewuye laarin awọ ọmọ orilẹ-ede Naijiria",
  "indexImage": {
    "id": "63640284",
    "subType": "index",
    "href": "http://b.files.bbci.co.uk/BC4C/test/_63640284_babatunde-rajifasholaministafunrinamnamna.jpg",
    "path": "/cpsdevpb/BC4C/test/_63640284_babatunde-rajifasholaministafunrinamnamna.jpg",
    "height": 549,
    "width": 976,
    "altText": "Babatunde Fashola",
    "caption": "Babatunde Fashola",
    "copyrightHolder": "Babatunde Fashola/Facebook"
  },
  "uri": "https://www.test.bbc.com/yoruba/afrika-23176202",
  "contentType": "Text",
  "assetTypeCode": "PRO",
  "timestamp": 1561381319000,
  "type": "link"
}
```

The story promo container will have to be updated so it can use information provided by CPS. There will be some mapping required between `headline` => `name`, etc.

[The CPS whitelist filter](https://github.com/bbc/simorgh/blob/spike-event-tracking/src/app/lib/utilities/preprocessor/rules/cpstypes.js) will also have to be updated since Link Promos use `assetTypeCode` instead of the usual `cpsType`.

**Describe alternatives you've considered**
-

**Testing notes**
- Cypress tests will be needed
- Ensure fixture data has the data necessary
- Exploratory and Compatibility testing required

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ghost** [comment]
Add story in storybook as well.
