### ISSUE TITLE
Add footer links and labels for Thai

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#2993]
We need to add the footer links and labels to Thai. 
These links are included in the current Thai footer which you can use for reference if you need to. 

Why you can trust BBC News | ทำไมคุณจึงไว้วางใจ บีบีซี นิวส์ ได้  | https://www.bbc.com/thai/institutional-49281839
Terms of use | เงื่อนไขการใช้เว็บไซต์ | https://www.bbc.com/thai/institutional-38403477
Privacy policy | นโยบายความเป็นส่วนตัว | https://www.bbc.com/thai/institutional-38497681
Cookies | คุกกี้ี้ | https://www.bbc.co.uk/usingthebbc/cookies/
Contact us | ติดต่อบีบีซีี | https://www.bbc.com/thai/institutional-37981748
Copyright | Copyright © 2019 บีบีซี. บีบีซีไม่มีส่วนรับผิดชอบต่อเนื้อหาของเว็บไซต์ภายนอก. |  
External links | นโยบายของเราเรื่องการเชื่อมต่อไปยังลิงก์ภายนอก. | https://www.bbc.co.uk/help/web/links/

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by paruchurisilpa** [comment]
Looks good to me..
