### ISSUE TITLE
Enable consent/cookie banner for Thai

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#2994]
We need to enable the consent banner for Thai. 
All required translations can be found in the translation spreadsheet, link in Jira ticket WSFRONTPGS-133

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ghost** [comment]
Check the cypress test covers the thai service. Check cross browsers and widths . Check chromatic test
