### ISSUE TITLE
Add remaining producer destinations to ATI logic

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#2995]
**Is your feature request related to a problem? Please describe.**
Currently there is only logic for the WS News Languages, News PS and News GNL but not for News Languages PS and News Languages GNL sites as destinations in the logic for ATI analytics as pointed out by @jimjohnsonrollings in this [comment](https://github.com/bbc/simorgh/pull/2991#issuecomment-519479492) on #2991 .

**Describe the solution you'd like**
- We need to add support for news sites under public service and global news through this [file](https://github.com/bbc/simorgh/blob/latest/src/app/lib/analyticsUtils/index.js)
- We need to add logic to support this which can be found in this [file](https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/getStatsDestination/index.js)
- To understand the logic that is needed I've created a table below to show this:

Site | isUk | DestLive | Dest Test
-- | -- | -- | --
Cymru Fyw | False | NEWS_LANGUAGES_GNL = 598289 | NEWS_LANGUAGES_GNL_TEST = 598290
Cymru Fyw | True | NEWS_LANGUAGES_PS: 598291 | NEWS_LANGUAGES_PS_TEST: 598292
Naidheachdan | False | NEWS_LANGUAGES_GNL = 598289 | NEWS_LANGUAGES_GNL_TEST = 598290
Naidheachdan | True | NEWS_LANGUAGES_PS: 598291 | NEWS_LANGUAGES_PS_TEST: 598292
Japanese | False | NEWS_LANGUAGES_GNL= 598289 | NEWS_LANGUAGES_GNL_TEST = 598290
Japanese | True | NEWS_LANGUAGES_GNL = 598289 | NEWS_LANGUAGES_GNL_TEST = 598290

**Describe alternatives you've considered**

**Testing notes**
This issue needs Unit Tests.

**Additional context**

**Comment by jamesbhobbs** [comment]
reopened due to https://github.com/bbc/simorgh/pull/3336
