### ISSUE TITLE
Descriptive durations should just have raw numbers with a space

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#2996]
**Is your feature request related to a problem? Please describe.**
The problem with adding translations for minutes and seconds is that it is difficult to do for all languages, especially for some Slavic languages that have multiple versions of plurals. 

**Describe the solution you'd like**
Instead of the minutes/seconds in story promo headline, we should just have numbers with a space

1. Use formatDuration instead of describeDuration in LinkContents. 
2. Replace the colons between the hours/minutes/seconds with spaces in the formatDuration function. For example "1:00" -> "1 00". This will avoid screen reader interpreting the numbers as a time, eg 'one o'clock'. 

We can't think of a downside of having a space instead of a colon as the screenreader reads it in the same way when the numbers are not '1:00'. 

**Describe alternatives you've considered**
Loads - but this is the most straightforward thing to do. 

**Testing notes**
To be tested with all supported assistive technology. 

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by DenisBBC** [comment]
This work should fix [this](https://github.com/bbc/simorgh/issues/2309) bug.
