### ISSUE TITLE
Serving fonts from local, static folder in storybook

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3002]
**Is your feature request related to a problem? Please describe.**
Chromatic have advised that we try to host the assets close to storybook and embed where possible.

This should help avoid issues like this

![image](https://user-images.githubusercontent.com/11341355/62711781-8cae4980-b9f1-11e9-843e-f8a5f1757a5c.png)

**Describe the solution you'd like**
Example PR from webcore, do this :) https://github.com/bbc/web/pull/1184/files

**Testing notes**
Should fix the font issues on moment locales on chromaticqa builds.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by chris-hinds** [comment]
@dr3 Raising an issue to allow us to change the base path of out font urls to enabled serving the files from the storybook static server.

**Comment by dr3** [comment]
Blocked on https://github.com/bbc/psammead/issues/1729

**Comment by oluoluoxenfree** [comment]
Blocked on https://github.com/bbc/psammead/pull/2273 and https://github.com/bbc/simorgh/pull/4053
