### ISSUE TITLE
Enable Navigation for Amharic 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#3037]
**Is your feature request related to a problem? Please describe.**
We require the navigation to be enabled for the live radio page for Amharic
We need to enable the navigation to be used by other teams for those sites

Full spec in WSMEDIA-31

**Describe the solution you'd like**

If in doubt please refer to the website

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by aeroplanejane** [comment]
@ryanmccombe do you wish to continue tracking this or will I close it as it is now covered in https://github.com/bbc/simorgh/issues/3031 ?

**Comment by ryanmccombe** [comment]
This should be closed as part of https://github.com/bbc/simorgh/pull/3055 - github automation maybe a bit bugged
