### ISSUE TITLE
Chartbeat blocked in Firefox private browsing

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#3041]
3) When looking at a page in Firefox Private Browsing, I get `The resource at “https://static.chartbeat.com/js/chartbeat.js” was blocked because content blocking is enabled.` in the console and nothing is sent to Chartbeat. (Chrome Incognito isn't working for me so can't check there)

_Originally posted by @jimjohnsonrollings in https://github.com/bbc/simorgh/issues/2808#issuecomment-519854791_

**Comment by jamesdonoh** [comment]
Rhys reports this also affects other (non-Simorgh pages).

**Comment by rhenshaw56** [comment]
@jamesdonoh , @jimjohnsonrollings I think this is a firefox  tracking protection thing which is on by default on their private winndow, [see here for more](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default), if you turn off firefox tracking protection you don't get that content blocking message and chartbeat works fine.

Chrome incognito is fine as well!

**Comment by jimjohnsonrollings** [comment]
Okay. Thanks for looking into it :) This can be closed then.
