### ISSUE TITLE
Moment deprecation warning

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3043]
**Describe the bug**

```
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
```

**To Reproduce**

1. run `npm i && npm run dev`

**Expected behavior**
Doesnt throw this warning

**Screenshots**

**Additional context**

**Comment by ghost** [comment]
I can't seem to figure out where the warning is originating from.

**Comment by oluoluoxenfree** [comment]
Tried replacing all the instances of `moment.defineLocale()` in psammead but doesn't fix the issue; from googling a different moment method might be causing it, but not sure how to narrow it down.

**Comment by EinsteinNjoroge** [comment]
Looks like news service config has something to do with this issue https://github.com/bbc/simorgh/blob/9cba2a9234e8e9f107d9bc9ff640a710391d7fa3/src/app/lib/config/services/news.js#L12
When I comment out his line the error disappears.

**Comment by EinsteinNjoroge** [comment]
@sadickisaac I'm wondering why we set locale to default to `en-GB` if it's not provided. 
 https://github.com/bbc/psammead/blob/cbeee287c132dccbb7b676d630a163703de2c9e6/packages/containers/psammead-timestamp-container/src/timestampUtilities.js#L38

**Comment by ghost** [comment]
@EinsteinCarrey Because moment defaults to `en` if locale is not provided. Since we are not using `en` as a locale to any service, we decided to default to `en-GB` used by `news`.

**Comment by EinsteinNjoroge** [comment]
Commenting out https://github.com/bbc/psammead/blob/ce9f0ae47747d8adcb399227d8c4cfa69816e854/packages/containers/psammead-timestamp-container/src/timestampUtilities.js#L41 also clears the issue. I can't seem to put my finger on what's causing this issue.
