### ISSUE TITLE
Optimize all services images

### ISSUE THREAD

**Issue by ghost** [bbc/simorgh#3049]
**Is your feature request related to a problem? Please describe.**
Service images in `/public/{service}/images` are not optimised  

**Describe the solution you'd like**
Optimise all the services images. You can use a tool like https://tinypng.com/

**Describe alternatives you've considered**
Leave the images as they are.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by DenisHdz** [comment]
Double-check with other PODs and UX, if they have optimized images in the past and what tool have been used.
