### ISSUE TITLE
Dark mode and `prefers-color-scheme`

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#3056]
**Is your feature request related to a problem? Please describe.**
Perhaps two of the most popular operating systems Simorgh pages will be viewed from, iOS & Android, are in the process of releasing dark modes. Currently, opening a webpage to a "Ghost" `#fdfdfd` background from a dark mode-enabled device or app could prove to be quite a jarring & unpleasant experience, especially if that app was showing content from the same site. 😉  Addressing this would be a great way for Simorgh to continue being "awesome on mobile" (© MMXVII) 😉👴

**~Describe the solution you'd like~ A possible solution?**
Android doesn't seem to currently have any concessions that would allow websites to specify their own dark themes. Currently Chrome Android seems to instead have a "dark mode" flag that you can enable, following which the browser will attempt to choose suitable dark mode equivalents for the various colours on your webpages.

However, Firefox, Chrome & Safari now support the [`prefers-color-scheme`](https://caniuse.com/#feat=prefers-color-scheme) media query. It's in the "drafts" stage of the standard, but it feels like there's a reasonable amount of energy behind it. I'm not sure if Chrome's desktop adoption of this is a promising signal for Chrome Android support, and the forced dark mode described above might just be a fallback?

I suppose one way of utilising this would be for each display component to separately check for this media query, but it seems rather repetitive.

```
const Paragraph = styled.p`
    ...
    color: C_SHADOW;
    @media (prefers-color-scheme: dark) {
        color: C_LUNAR;
    }
`;
```

I also wondered if supporting dark mode could ease any use of the Simorgh/Psammead combo for services with different theming requirements. 🤔

---

I had a go at a rather hacky spike keeping those two things in mind. 

Note: The colours for this spike were guessed from some very early UX designs for Android, definitely don't assume they're indicative
<img width="1257" alt="A screenshot of the same Simorgh webpage, one in a browser with a spike of dark mode enabled, the other in it's current light mode appearance" src="https://user-images.githubusercontent.com/11646957/62788073-14fa2080-babe-11e9-99cb-268365eb0661.png">

I felt a little rusty with JS, so wasn't going to PR, but the spike generally followed the pattern:
• Simorgh and Psammead components utilise CSS variables for semantic colours, with hard-coded fallbacks.

```
const Paragraph = styled.p`
    ...
    color: C_SHADOW; // Fallback for browsers which don't support CSS variables
    color: var(--textPrimary, C_SHADOW); // You can specify a fallback if the CSS variable isn't set. I didn't realise this was a thing before 😅 
`;
```

• Each `service` config object in Simorgh gained a `theme` child, following [the existing pattern for services to define their own `fonts`](https://github.com/bbc/simorgh/blob/45b735831b5b0dd449c036da44741103560910f3/src/app/lib/config/services/news.js#L162-L169).

This `theme` defines a `light` and `dark` value for each semantic colour which it wishes to override.
I also removed the existing `themeColour` property within services, in favour of a new `brand` semantic colour defined within `theme`. 

```
{
    ...
    theme: {
        light: {
            brand: C_POSTBOX,
            ...
        },
        dark: {
            brand: "#EB0000",
            ...
        }
    }
}
```

• Finally, `globalStyles` defines the supported themes, and sets the semantic colour variables for each theme.

```
:root {
    color-scheme: light dark;

    ${({ theme }) => `
        @media (prefers-color-scheme: dark) {
            --brand: ${theme.dark.brand};
            // I manually set each semantic colour variable here, but wondered if there'd be a way to use Object.keys or similar to only set those which have been explicitly overridden by the service config, to avoid repetition in the config
        }
    `}
}
```

The obvious downside of this pattern would be the thought and updating that would need to go into establishing and using semantic colours for the various display components. I had fun trying to work it out though, and would be curious what everyone who has more knowledge of the current project direction would think.

**Testing notes**
[Tester to complete]

Dev insight: This would seem to be well-fitted to Cypress tests, though I don't know if it's possible to set media query properties such as `prefers-color-scheme`?

**Additional context**
[Media Queries Level 5: Detecting the desire for light or dark color schemes](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme)
[WWDC 2019#214: Implementing Dark Mode on iOS](https://developer.apple.com/wwdc19/214)
[WWDC 2019#511: Supporting Dark Mode in Your Web Content](https://developer.apple.com/wwdc19/511)

**Comment by jamesbhobbs** [comment]
@bcmn nice, PRs still welcome even from the rusty, especially on no urgent things like this :)
