### ISSUE TITLE
Add cypress tests for live radio nav bar

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3078]
**Is your feature request related to a problem? Please describe.**
Extend the live radio cypress tests (once available) to include testing of the nav bar

**Describe the solution you'd like**
From discussion at refinement, it should include also testing the links, not just the presence of the nav bar. Ensure tests do not run on the test environment

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jamesbhobbs** [comment]
I don't think this is needed, Sareh will be adding this and the same work would include the tests. NB there should not be separate issues for testing, testing whether unit or e2e should be done with each PR.
