### ISSUE TITLE
Suppress React warnings in src/app/containers/Text/index.test.jsx

### ISSUE THREAD

**Issue by FK78** [bbc/simorgh#3080]
**Describe the bug**
There are React warnings in unit tests.
~Blocked by: https://github.com/bbc/simorgh/pull/2961~
**To Reproduce**

1. Go to simorgh in terminal
2. Run npm run test:unit
3. Observe React warnings:

```
    console.log src/testHelpers/setupTests.js:19
      Test failed because too many React warnings were detected. Please fix the following:
      Warning: Failed prop type: The prop `blocks` is marked as required in `TextContainer`, but its value is `undefined`.
          in TextContainer
```

**Expected behaviour**

No React warning for test suite.

**Testing notes**

No testing required.

**Comment by thekp** [comment]
https://github.com/bbc/simorgh/blob/latest/src/app/containers/Text/index.test.jsx#L6-L8

similarly to this issue: https://github.com/bbc/simorgh/issues/3001

we are testing for `Null` by not passing in props when props are required.
