### ISSUE TITLE
Add unit tests for the new media pod Simorgh routes

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3093]
**Is your feature request related to a problem? Please describe.**
We need to add unit tests for the routes we added to Simorgh

**Describe the solution you'd like**
Add tests here: https://github.com/bbc/simorgh/blob/latest/src/server/index.test.jsx

**Testing notes**
[Tester to complete]

Dev insight: Adding unit tests should not need manual testing

**Additional context**

**Comment by jamesbhobbs** [comment]
The route should not have been merged without this testing in that file, there is partial coverage here  https://github.com/bbc/simorgh/pull/2708/files but it isn't sufficient.

**Comment by pjlee11** [comment]
@benjaminhobbs given this route isn't shown in production at all and for quite a long time was not included on any environment I'm not convinced it "should not of been merged without testing". Will pick this up today.

**Comment by graeme-lindsay** [comment]
@benjaminhobbs I agree we shouldn't be merging code without associated unit tests. That's a discipline I expect us to hold going forward. 

In this instance, we missed the unit tests and created this issue to track. As @pjlee11 has mentioned we did have a rationale for not prioritising this, but I'm not sure it justifies the time between code and associated unit test coverage.

We'll pick it up as a priority.
