### ISSUE TITLE
Catch up w/ James re Lighthouse Strategy

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3108]
**Is your feature request related to a problem? Please describe.**
Catch up with James and establish a plan on how we can implement LH tests for our live radio pages

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: No tests - just an analysis task

**Additional context**

**Comment by LilyL0u** [comment]
Going to ask if the current automated Lighthouse tests can also be run on a live radio page. Apparently they are a bit intensive, so I doubt we will put them on every service.

**Comment by LilyL0u** [comment]
'If you want it on the pipeline that will require a ticket. Should be easy enough. But will force us to do a deployment since the tests are tied to our test deployment pipeline'
Otherwise I can do it manually and collate a report of the results comparing new and old radio services.

**Comment by ryanmccombe** [comment]
@jamesdonoh  offered to have a sync up meeting around this - articles have also been doing work around lighthouse tests for media embeds

**Comment by ryanmccombe** [comment]
Follow up with james

**Comment by aeroplanejane** [comment]
This has been done
