### ISSUE TITLE
Add live radio schema.org metadata

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#3117]
Similar to this https://github.com/bbc/simorgh/issues/577

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by aeroplanejane** [comment]
See: https://schema.org/docs/gs.html for reference and also https://schema.org/RadioChannel for suggested schema object. 
Not for V1 - would require a refactor of the schema.org config to support the radio channel object. 
See WS2020-1538 for reference.

**Comment by aeroplanejane** [comment]
This has been done, this issue is a duplicate. Closing.
