### ISSUE TITLE
Update SMP object for Arabic, Urdu, Pashto

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#3119]
**Is your feature request related to a problem? Please describe.**
We need to update the object we send to SMP when on the Arabic, Urdu and Pashto services to provide the following:

Language translations for Arabic, Urdu and Pashto
Stats tracking for Arabic, Urdu and Pashto
RTL support for SMP CTA

**Describe the solution you'd like**
When viewing video and audio on Arabic, we should amend the SMP object to include the following to support the three points above:

```
{
  ...
  "appName": "news-arabic",
  "ui": {
    "cta": {
      "direction": "rtl"
    },
    "locale": {
      "lang": "ar"
    }
  },
  "statsObject": {
    "destination": "WS_NEWS_LANGUAGES",
    "producer": "ARABIC"
  },
}
```

When viewing video and audio on Urdu, we should amend the SMP object to include the following to support the three points above:

```
{
  ...
  "appName": "news-urdu",
  "ui": {
    "cta": {
      "direction": "rtl"
    },
    "locale": {
      "lang": "ur"
    }
  },
  "statsObject": {
    "destination": "WS_NEWS_LANGUAGES",
    "producer": "URDU"
  },
}
```

When viewing video and audio on Pashto, we should amend the SMP object to include the following to support the three points above:

```
{
  ...
  "appName": "news-pashto",
  "ui": {
    "cta": {
      "direction": "rtl"
    },
    "locale": {
      "lang": "ps"
    }
  },
  "statsObject": {
    "destination": "WS_NEWS_LANGUAGES",
    "producer": "PASHTO"
  },
}

```

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by 12** [comment]
This will likely need an investigation into whether the current media embed endpoint already contains logic to switch these params. If not, this will require additional work on that endpoint.

May I suggest moving this to bbc/simorgh-infrastructure?

**Comment by lizcameron** [comment]
Combined with https://github.com/bbc/simorgh/issues/1959 which handles all four RTL languages
