### ISSUE TITLE
AV: Some browsers require two clicks to play video

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#3134]
**Describe the bug**
When a user clicks the placeholder image of a media asset, when the media player loads, it should start to play the content. However in some browsers this is not the case, due to the way we are configuring autoplay, which causes the user to have to interact twice in order to get a media asset playing back, instead of the single click on the placeholder.

**Outcome of this issue**
We should investigate the different autoplay policies for the browsers and devices listed below, that may be able to help us understand why autoplay is not working as expected. From that writeup, we should then be able to take further steps to correcting this behaviour.

**Table of browsers that do not work**

_**PLEASE UPDATE THIS TABLE AS YOU FIND NEW BROWSERS THAT DO NOT WORK**_

_in descending order of priority_

| Device  | Operating System | Browser |
| --- | --- | --- |
| Nexus 5X  | Android 8  | Chrome |
| Samsung Galaxy Note 8  | Android 8  | Samsung Browser, Chrome |
| MacBook | MacOS 10.14.5 | Safari |
| iPhone 5s  | iOS 7  | Safari, Chrome |
| iPhone 8 Plus  | iOS 12  | Safari, Chrome |
| iPad Pro  | iOS 11  | Safari, Chrome |

**To Reproduce**

1. Using a browser listed above as being reported to not have working autoplay
2. Go to https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo
3. Click on a placeholder image
4. See media player load, but not autoplay

**Expected behavior**
When I click a media player placeholder image, the media player should load and play automatically.

**Additional context**
We should investigate what autoplay policies each browser (that has been reported as not working) has, and work out how we can follow that policy.

**Comment by 12** [comment]
Different browsers have different (but configurable) autoplay policies. For instance, Firefox defaults to permit autoplay when there is no audio.

**Comment by 12** [comment]
`twitch.tv` behaves the following way (in Safari):
- `Allow All Auto-Play`: Plays as normal with sound
- `Stop Media With Sound`: Twitch detects this option and video playback is muted
- `Never Auto-Play`: User interaction required to initiate video playback

These settings can be configured for entire browser / per site in Safari Preferences > Websites > Auto-Play.

**Comment by HarveyPeachey** [comment]
MDN has a brief outline of the general rules of thumb that different browsers follow in regards to [auto-play policies](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#Autoplay_availability)

I'll look into more browser specific stuff that we need to support:

- [Chrome (Mobile)](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) - On mobile this in theory should work, as it follows the same policy as it's desktop counterpart which works. ~One thing that could be causing it not to autoplay, would be the attribute used to trigger autoplay could be different for the mobile build. What could be done is `autoplay` being added to the top level iframe to see if that rectifies the issue, as at the moment it only has `allow="autoplay"` these can be found in the psammead media-player component for [amp](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-media-player/src/Amp/index.jsx) and [canonical](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-media-player/src/Canonical/index.jsx).~ Videos won't autoplay unless they're inline which isn't what we want as we need to let users enter fullscreen.
- [Firefox](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#Firefox)
- [Safari (Mac)](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/) - Safari uses a differential privacy algorithm to determine what websites are allowed to have autoplay enabled by default. So sites like twitch and netflix will autoplay but videos on the BBC won't. Here's a thread where an Apple employee addresses this: https://forums.developer.apple.com/thread/90784
- [Safari (iOS)](https://webkit.org/blog/6784/new-video-policies-for-ios/) - From this description it looks like videos will only autoplay if the video is muted.
- [Edge](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/browser-features/autoplay-policies#best-practices-for-web-developers)
- Samsung Internet Browser - There is currently no documentation on specific autoplay policies for this browser. However it is built on chromium, so it can be assumed it follows what chrome uses. There is also an xda developer article about autoplay being disabled by [default](https://www.xda-developers.com/samsung-internet-beta-9-4-autoplay-video-blocker/) with version 9.4 which was released on July 22, 2019.

**Comment by HarveyPeachey** [comment]
~~Blocked until #3507 is done as testing can't be performed because test videos currently don't load.~~

**Comment by HarveyPeachey** [comment]
~~Blocked on #3608~~

**Comment by HarveyPeachey** [comment]
Summary: Until the X-Frame-Options issue which is currently blocked is done, then we can't fully test these scenarios locally. One method we can try is once the video iFrame is loaded we can use onLoad to trigger the play() function for the video. And because the user has already interacted with the page, it doesn't violate Chrome's autoplay policy however, this will need testing on other browsers.

Edit: Although I have now discovered that if battery saver mode is enabled on iOS then autoplay is disabled on Chrome and Safari. This is the same case if data saver mode is enabled on android for chrome.

**Comment by HarveyPeachey** [comment]
Blocked until X-Frame-Options header for mp embeds is completed, which is currently blocked due to work outside of pod.

**Comment by jamesdonoh** [comment]
Closing this as investigation is completed.
