### ISSUE TITLE
Use updated psammead-media-player

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#3135]
**Is your feature request related to a problem? Please describe.**
The latest Media Player https://github.com/bbc/psammead/issues/2248 includes psammead-play-button and updates its API to accept timestamp and duration data. 

**Describe the solution you'd like**
Introduce the updated psammead-media-player (with play button) to Simorgh and make the necessary changes to containing components and test files.

**Describe alternatives you've considered**
n/a

**Testing notes**
- Investigate whether we can do Cypress tests when we interact with the button.
- Cross browser testing.
- Developer a11y swarm.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
n/a

**Comment by lizcameron** [comment]
Designs, including screenreader UX: 
Default state for play button, (with duration displayed): https://zpl.io/aMK7WBd 
Hover/focus state for play button (with duration displayed): https://zpl.io/VOKM56l

**Comment by simonsinclair** [comment]
I've created the companion Psammead ticket here https://github.com/bbc/psammead/issues/2248 and moved this one to Blocked, while it's worked on.
