### ISSUE TITLE
Set AppType ATI label to amp for live radio amp pages 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#3136]
**Is your feature request related to a problem? Please describe.**
Where a liveradio page is an amp page we want to set the appType Label to "amp" 
Currently appType is set to "responsive" for all page types 

**Describe the solution you'd like**
Given a user visits an amp page and the page loads
then the value passed to ATI for appType will be "amp" 
![Screenshot 2019-08-14 at 11 26 46](https://user-images.githubusercontent.com/22519682/63014457-7a675c00-be86-11e9-95d0-2000e56540c0.png)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by aeroplanejane** [comment]
@ryanmccombe let me know if more info is needed

**Comment by gavinspence** [comment]
Done
