### ISSUE TITLE
Validate that the new standardised Cypress testing article works for us

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#3146]
**Is your feature request related to a problem? Please describe.**
In order to make cross-service testing easier, we are planning to create a standardised test article.

**Describe the solution you'd like**
An asset has been created on the test environment.  This task is to evaluate whether it contains all of the features necessary for our tests.

The asset is cn7k01xp8kxo

Dev to pair with tester (James B) to complete issue.

**Testing notes**

- [x] - We need to check that the article doesn't 404
- [x] - It has all the agreed components
- [x] - Existing Cypress tests pass
- [x] - Any components (excluding video and audio) that do not have Cypress tests will require new e2es
- [ ] 

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by jimjohnsonrollings** [comment]
Blocked until I create the test asset

**Comment by jimjohnsonrollings** [comment]
Test asset now created: cn7k01xp8kxo

**Comment by jamesbhobbs** [comment]
I'd like to look at this, let me know if you're waiting for me and I'll bump it up my to do list

**Comment by jamesbhobbs** [comment]
LGTM

**Comment by HarveyPeachey** [comment]
Is this done? And how do I access the asset `cn7k01xp8kxo`?

**Comment by jimjohnsonrollings** [comment]
@HarveyPeachey /news/articles/cn7k01xp8kxo on www.test

**Comment by jamesdonoh** [comment]
Next steps are to update the Cypress config to use the new asset and verify that everything passes (and fix/report anything that doesn't).
