### ISSUE TITLE
Timestamps for Pashto locale

### ISSUE THREAD

**Issue by RayNjeri** [bbc/simorgh#3147]
**Is your feature request related to a problem? Please describe.**
We need to ensure timestamps support Pashto, this includes correct translations and numerals.

When viewing an article in Pashto, the timestamp should:
- Use [Eastern Arabic numerals](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals)
- Display both relative and absolute timestamps in Pashto
- Display updated timestamps correctly in Pashto
- Include both Gregorian and Jalaali calendar dates (already enabled in https://github.com/bbc/simorgh/pull/3552)
- Be rendered right-to-left
- Have onscreen and offscreen translations in Pashto

**Other links**
Storybook for examples of relative timestamps, e.g. https://bbc.github.io/simorgh/?path=/story/containers-article-article-timestamp--lastpublished-firstpublished-and-firstpublished-10-hours-ago

Pashto article fixture data: https://github.com/bbc/simorgh/tree/latest/data/pashto/articles

**Describe the solution you'd like**
Update the [`ps` locale in psammead-locales](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-locales/moment/ps.js) to support the above requirements.

**Note** the locale does not need to include all Moment locale features, only enough to support our timestamp formats. 

**Describe alternatives you've considered**
None.

**Testing notes**
- Requires unit test coverage for Pashto locale

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by rhenshaw56** [comment]
should be unblocked once https://github.com/bbc/psammead/issues/1732 is completed

**Comment by rhenshaw56** [comment]
still blocked pending merge of https://github.com/bbc/psammead/pull/1844

**Comment by jamesdonoh** [comment]
Reopening this as only dual calendar support was covered by https://github.com/bbc/simorgh/pull/3552 and we still have to implement the remainder.

**Comment by jamesdonoh** [comment]
Reopening this till the code has been integrated into Simorgh
