### ISSUE TITLE
Swagger-cli validator doesn't seem to lint correctly

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#315]
**Describe the bug**
As per the comment on https://github.com/bbc/simorgh/pull/273#pullrequestreview-137121079 it seems that the swagger-cli lint doesn't pick up single space errors. 

**To Reproduce**
See comment and screenshot of PR link in description 

**Expected behavior**
The linter should error on single space errors

**Screenshots**
![](https://user-images.githubusercontent.com/7791726/42808187-991dbd18-89aa-11e8-9546-5ee893f568d5.png)

**Additional context**
This may need to be fixed within swagger-cli itself

**Comment by jamesbhobbs** [comment]
@pjlee11 rather than have the issue handled only here, can you open it on the source repo, which I think this https://github.com/BigstickCarpet/swagger-cli Also if you comment mentioning our issue link it will link that issue to this one.

**Comment by ChrisBAshton** [comment]
This is now fixed in a recent version of swagger-cli.

https://github.com/APIDevTools/swagger-cli/commit/b132158575541ee02a55207b024f7573d22378dc
