### ISSUE TITLE
Snapshot for MediaPage returns a 500

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3152]
**Describe the bug**
The snapshots for the `MediaPage` container are currently returning a 500. This is likely due to missing mocks and/or fixture data. Without accurate page snapshots it's not possible to see the impact our code changes have on the page metadata.

**To Reproduce**

This [snapshot](https://github.com/bbc/simorgh/blob/59754221862cd60696266d51944b2cc720f34430/src/app/containers/MediaPage/__snapshots__/index.test.jsx.snap#L337) is showing a 500 page return. 

**Expected behavior**
Our snapshots should render a 200 page with the whole page rendered. 

**Additional context**
Without this piece of work it is hard to see how new code changes impact the media page's HTML output.

**Comment by ryanmccombe** [comment]
How did it pass CI if a snapshot test is rendering a 500 page?

**Comment by pjlee11** [comment]
Because Simorgh has the ability to handle 500 pages because it is a SPA. Our ErrorPage logic captures 500 status codes and creates a page with header, footer and the main being 500, similar to how the 404 page renders - run simorgh locally and visit http://localhost.bbc.com:7080/news/articles/c0g992jmmkdo to see the 404
