### ISSUE TITLE
AV: investigate screenreader reading controls twice

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#3176]
**Is your feature request related to a problem? Please describe.**
Currently when using a screen reader, the SMP video automatically reads and repeats every control twice when play button is pressed (does not happen on audio skin).

**Describe the solution you'd like**
Each control should be read once.
Check if iPlayer does something different in their SMP config, for a solution.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by FK78** [comment]
The screen reader now reads out the controls three to four times on MacOS using VoiceOver, but only when navigating the page using the tab key.

**Comment by FK78** [comment]
Issue can not be replicated on Android or iOS.

**Comment by 12** [comment]
Might be worth looking at `MP-3378` in JIRA. This was raised for an issue with video on the News Front Page, and the outcome of the investigation was that this is typically an issue with screenreaders (namely NVDA).

Whoever picks this up should test with various voiceover utilities.
