### ISSUE TITLE
AV: investigate screen reader behaviour for second iframe

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#3180]
**Is your feature request related to a problem? Please describe.**
Currently, the screenreader is acknowledging the second iframe leading to a poor experience for screenreader users.

**Describe the solution you'd like**
Investigation to see if there's a way if prevent both iframes being acknowledged by the screenreader. E.g. See if removing `title` (https://github.com/bbc/morph-modules/blob/master/news-av-player/src/smp.js#L64​​) from the SMP object means that the screenreader doesn't acknowledge the iframe. Different screen readers might have different outcomes based on this.

Could also try adding role="presentation" to the iframe element along with an attribute of tabindex -1. If this stops the iframe from being announced, we need to check that you can still reach the content of the iframe with the keyboard (eg all focusable items are still focusable) and that we haven’t lost the semantic meaning of child elements when using a screen reader. https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/#presentation_role_ignored
 
**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by aeroplanejane** [comment]
@lizcameron UX and @greenc05 investigated this and we have implemented the following solution on our pages:
**Scenario: Video Outer iFrame**
- Given I use a screen reader 
- and the I am on a MAP page with a **video** clip
- when I navigate to the outer iframe of the SMP on the MAP page
- then “Video Player” is announced

**Scenario: Audio Outer iFrame**
- Given I use a screen reader 
- and the I am on a MAP page with an audio clip
- when I navigate to the outer iframe of the SMP on the MAP page
- then “Audio Player” is announced

**Scenario: Inner iFrame**
- Given I use a screen reader
- when I navigate to the second iFrame on a MAP page
- then the title of clip is announced 
- e.g. “The Pidgin Minute” 

If we cannot detect the whether a clip is audio or video we should use "media player" I've asked editorial for translations for video player, audio player and media player in the translations spreadsheet but I'm told this will take quite some time to attain

**Comment by aeroplanejane** [comment]
See: https://github.com/bbc/simorgh/issues/3961

**Comment by lizcameron** [comment]
May be resolved by https://github.com/bbc/simorgh/pull/4404

**Comment by rhenshaw56** [comment]
Closing as this is no longer happening.
