### ISSUE TITLE
Pass locale correctly to Gregorian timestamps in Arabic.

### ISSUE THREAD

**Issue by RayNjeri** [bbc/simorgh#3183]
**Is your feature request related to a problem? Please describe.**
We need to update our Gregorian timestamps to support Arabic, this includes using its translations, **different numerals for Arabic**, and right-to-left support.

We already completed this work for Persian in https://github.com/bbc/simorgh/issues/1969 and  Urdu in https://github.com/bbc/simorgh/pull/3131 so this issue should be extending that further to encompass the requirements for the Arabic service in this group.

**Describe the solution you'd like**
When viewing an article in Arabic, the timestamp should:
Use Western Arabic numerals (i.e. 12345678...) (possibly returned when using moment's ur locale)
Be right-to-left
Have onscreen and offscreen translations in Arabic for Updated text
When time is updated, the updated timestamps should all read in Arabic

**Describe alternatives you've considered**

**Testing notes**
We will want to test that the timestamp returns as expected depending on the locale that's being passed through. We may also want to investigate if there are any changes we want to make to the Cypress tests given we're introducing extra logic to the timestamp.
This needs to have e2e coverage.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by rhenshaw56** [comment]
should be picked unblockedd once https://github.com/bbc/psammead/issues/1778
