### ISSUE TITLE
Add Producer ID to AReS payload for ATI Analytics

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#3196]
We need to ensure that the level 2 site producers are returned from the ARES payload

**PRODUCER | SITE ID**
AFAAN_OROMOO | 2
AMHARIC | 4
INDONESIAN | 54
KOREAN | 57
TIGRINYA | 91

SMP accepts the enum value for ID as a string

**Comment by ryanmccombe** [comment]
We should maybe get them to add both the string and the numeric representation of producer - just in case we end up needing them both?

**Comment by ryanmccombe** [comment]
Sent this request to ARES

**Comment by aeroplanejane** [comment]
Verified as present on the test payload: 
https://ares-broker.test.api.bbci.co.uk/api/ws-media/bbc_afaanoromoo_radio/liveradio
https://ares-broker.test.api.bbci.co.uk/api/ws-media/bbc_amharic_radio/liveradio
https://ares-broker.test.api.bbci.co.uk/api/ws-media/bbc_indonesian_radio/liveradio
https://ares-broker.test.api.bbci.co.uk/api/ws-media/bbc_korean_radio/liveradio
https://ares-broker.test.api.bbci.co.uk/api/ws-media/bbc_tigrinya_radio/liveradio
