### ISSUE TITLE
Live Radio pages reporting wrong producer to ATI

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3206]
**Describe the bug**
Live radio pages are reporting the custom ATI field `producer` as 0

**Expected behavior**
Use the correct producer depending on the service:
http://bbc.github.io/echo-docs/documentation/reporting-ati/#producer

**Comment by HarveyPeachey** [comment]
My PR has just merged to latest, can you check if this is fixed or give me a link so I can check? I'm not sure where the 5 Live Radio v1 services are.

**Comment by ryanmccombe** [comment]
Thanks @HarveyPeachey :)

- https://www.test.bbc.com/indonesia/bbc_indonesian_radio/liveradio
- https://www.test.bbc.com/korean/bbc_korean_radio/liveradio
- https://www.test.bbc.com/tigrinya/bbc_tigrinya_radio/liveradio
- https://www.test.bbc.com/amharic/bbc_amharic_radio/liveradio
- https://www.test.bbc.com/afaanoromoo/bbc_afaanoromoo_radio/liveradio

**Comment by HarveyPeachey** [comment]
Cool thanks @ryanmccombe looks like it done the job :)
