### ISSUE TITLE
Cypress e2e tests in /cypress/integration/pages repeatedly request data rather than sharing context

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#3263]
**Describe the bug**
Inside each page we repeatedly do cy.request to get data endpoint. Instead we should use just cy.request('url).as('data') approach as written up https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context 

**To Reproduce**
Read the files

**Expected behavior**
Doesn't keep requesting the same data, instead requests it once for canonical and amp page

**Testing notes**
Just that tests pass

**Additional context**
n/a

**Comment by PriyaKR** [comment]
@benjaminhobbs Looking into the cypress tests only inside `../cypress/integration/application/index.js ` `cy.request` is being called in two places for same page.In all other places it varies with service and pagetype.

Refactoring cy.request to use shareContext would be applicable only in this file `../cypress/integration/application/index.js`

**Comment by PriyaKR** [comment]
Closing this issue as cypress doesn't allow defined aliases being used on different tests across which means there is no point in using them.
