### ISSUE TITLE
Remove test helpers from simorgh

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3264]
**Is your feature request related to a problem? Please describe.**
We moved our test helpers to psammead monttttths ago, but we still use them in simorgh via `simorgh/src/testHelpers/index.js`

**Describe the solution you'd like**
Delete `simorgh/src/testHelpers/index.js`, first ensuring that all the commands we use are available in `@bbc/psammead-test-helpers`. If we have commands in simorgh test helpers that arnt in psammead test helpers, move them first

Everywhere simorgh test helpers are used, use `@bbc/psammead-test-helpers` instead

- ~[ ] This feature is expected to need manual testing.~

**Additional context**

**Comment by FK78** [comment]
Blocked by #[1917](https://github.com/bbc/psammead/pull/1917/files)

**Comment by ghost** [comment]
This is now unblocked https://github.com/bbc/psammead/pull/1917 has been merged

**Comment by ghost** [comment]
But might be blocked on https://github.com/bbc/psammead/issues/774 since we don't have shallow rendering and shallow match snapshots. Some test needs to be refactored
