### ISSUE TITLE
Add footer translations for Indonesian & Korean

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3285]
**Is your feature request related to a problem? Please describe.**
We need to add the footer translations for the 2/4live radio v1 services (afaan oromoo is already done)

**Describe the solution you'd like**
Add the translations to the service configs.  Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-29)

**Testing notes**
[Tester to complete]

Dev insight: Unlikely to need a tester due to simplicity

- [ ] This feature is expected to need manual testing.

**Additional context**
WSMEDIA-29

**Comment by aeroplanejane** [comment]
@ryanmccombe This appears to be done? Can you make sure you move these tickets across?

**Comment by ryanmccombe** [comment]
@aeroplanejane aaah this issue was copy-pasted to over here: https://github.com/bbc/simorgh/issues/3297 and then I did that one 🤣 

Either way, I think this issue can be closed as a duplicate now
