### ISSUE TITLE
Update Thai metadata

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#3288]
**Is your feature request related to a problem? Please describe.**
Update Thai metadata to include

```
Title Tag update:

ข่าว ข่าวสด วัน นี้ ข่าว ล่าสุด วีดีโอ | BBC บีบีซีไทย - BBC News

Hreflang:
<link rel="alternate" href="https://www.bbc.com/thai" hreflang="th" />
```

**Describe the solution you'd like**
Add `isoLang` in Thai config and set it to `th` - similar to [Yoruba](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/yoruba.js#L16)

Currently we use `promo.name` from Ares as a value for the `title` tag. This will need to be updated so we can pass in our own custom value. This value could be stored in the config for example.

**Describe alternatives you've considered**
...

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by andrew-nowak** [comment]
speak to SEO expert tom about whether the title should really be moving out of editorial control

**Comment by ghost** [comment]
Best to keep this within development for now, we take editorial stakeholders through title tag changes and happy to be the go-between during off-forge and other related tasks where title changes necessary. Would be keen to work out smoother processes if possible though (e.g. title tag changes could be made manually by SEOs with editorial input, similar to CPS sitebuilder, could take a task away from development backlogs?)

**Comment by andrew-nowak** [comment]
@chandlertp sounds good, I take it the title tags for the other live services are good and should be kept as they are?

> Would be keen to work out smoother processes if possible though (e.g. title tag changes could be made manually by SEOs with editorial input, similar to CPS sitebuilder, could take a task away from development backlogs?)

Agreed this is a good goal to have - unfortunately it is probably a goal for the non-immediate future

**Comment by ghost** [comment]
@aacn500 all good for Pidgin, Igbo and Yoruba. Hopefully space to build further optimisation (in future as mentioned above). Will feed in Title tags for next services in pipeline soon 😀
