### ISSUE TITLE
Add Footer Translations for Amharic

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#3296]
We need to add footer translations for Amharic

Add the translations to the service configs. Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-29)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
The "why you can trust the bbc" translation isn't on the spreadsheet or the jira ticket - moving to blocked
