### ISSUE TITLE
Fix Medium Severity 'Regular Expression Denial of Service' vulnerability

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#33]
Snyk is reporting a vulnerability with a medium severity in the 'content-type-parser' package of 'razzle@2.0.3': https://snyk.io/test/github/bbc/simorgh#npm:content-type-parser:20170905

We should fix this.

**Comment by sareh** [comment]
According to the Snyk site: `There is no fix for content-type-parser. The package was renamed from content-type-parser to whatwg-mimetype, which fixes the issue in version 2.0.0.`. 

Here are the dependencies:
`razzle@2.0.3 › jest@20.0.4 › jest-cli@20.0.4 › jest-environment-jsdom@20.0.3 › jsdom@9.12.0 › content-type-parser@1.0.2 ` 

It appears to be the case that by updating to use `jest@23.1.0`, this security vulnerability is addressed. New dependency tree would be this:
`jest@23.1.0` > `jest-cli@23.1.0`> `jest-environment-jsdom@23.1.0` > `jsdom@^11.5.1` which installs `jsdom@11.11.0` > `whatwg-mimetype@2.1.0`.

We can open a PR against Razzle to update the version of Jest being used from `"20.0.4"` to `"^23.1.0"` https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/package.json

**Comment by jamesbhobbs** [comment]
@sareh Sounds good, when you do please add the issue and PR here

**Comment by jamesbhobbs** [comment]
See https://github.com/jaredpalmer/razzle/issues/438
