### ISSUE TITLE
Run lighthouse tests in CI

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#331]
**Is your feature request related to a problem? Please describe.**
Subsequent to https://github.com/bbc/simorgh/issues/305 we have bbc-a11y running in CI. We should also run performance tests.

**Describe the solution you'd like**
Run lighthouse tests against our production scenarios and enforce minimum standards. Namely:
Must meet:
- Performance >= 90
- PWA - warning not error on all points missing, except those currently met which should be set to error in case we degrade the features.
- Best practices = 100
- Accessibility = 100
- SEO = 100

**Describe alternatives you've considered**
We can use https://github.com/bbc/a11y-tests-web and extend it itself to allow other lighthouse tests to be run (it's currently hardcoded to only run accessibility). Note: this was the solution chosen, as an effort to make a11y-tests-web extensible for Simorgh.

**Comment by BogdanDogaru** [comment]
Closing this as we've implemented Lighthouse but we will enforce the minimum scores in #949
