### ISSUE TITLE
Single service bundle for service variants

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#3323]
**Is your feature request related to a problem? Please describe.**
As of right n ow services variant supports has gone with the idea of creating new bundle for each service variant i.e.

Serbian will have two variant bundles

`serbian_lat.js` & `serbian_cyr.js`

**Describe the solution you'd like**
Can we have a single service bundle for services with variants e.g. `serbian.js` instead of `serbian_lat.js` & `serbian_cyr.js`

The service config could be in one file and have two named exports for each of the variants.

The serviceContext provider could then take a serviceVariant prop to ensure the correct configuration is loaded.

Benefits of this approach being that switching between variants would not need to have a new service bundle downloaded and would actually reduce the complexity of the current service variant work in simorgh.

**Describe alternatives you've considered**
Sticking with the current approach of have a bundle per service or per variant.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
>would actually reduce the complexity of the current service variant work in simorgh.

I think thats debatable, I still like the idea of treating varients as their own service with `name_var` If anything thats simpler. 

As for putting the varient into in 1 file, I dont really see the value and will mean that for these sites with with 2 variants, the bundles will be much bigger

**Comment by dr3** [comment]
Closing, being done in 3509
