### ISSUE TITLE
Add cypress test for live radio analytics

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3324]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by jroebu14** [comment]
Waiting on this https://github.com/bbc/simorgh/pull/3364 to be merged before addressing the conflicts in https://github.com/bbc/simorgh/pull/3341.

**Comment by jroebu14** [comment]
Will be completed by https://github.com/bbc/simorgh/pull/3339

**Comment by jroebu14** [comment]
Closed via #3339. I have pulled latest and can confirm that ATI tests are running against live radio pages.
