### ISSUE TITLE
Get Live Radio data from ARES

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3330]
**Is your feature request related to a problem? Please describe.**
We have code in both Simorgh and Mozart that causes Simorgh to retrieve JSON from itself, rather than reaching out to ARES

This was an interim solution as the ARES data wasn't available

ARES data is now available, so this can be stripped out

**Describe the solution you'd like**
In the test environment, the live radio pages get their data from ARES, rather than Simorgh

**Testing notes**
[Tester to complete]

Dev insight: Needs updates to the unit tests

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
Completed as by mozart-assembler#292, mozart-routing#916 and #3379
