### ISSUE TITLE
Lang attribute on AV embed endpoint 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3342]
**Is your feature request related to a problem? Please describe.**
In the Mozart page templates for the `/ws/*` media embed endpoints we currently have `<html lang="en">` hardcoded. We need to be able to set the lang attribute on the embed endpoint based on parameters in the request URL. This is needed so we can set the lang based on the current language of the service, page or block.

Any changes made to the `/ws/av_embeds_media` template should also be made to `/ws/av_embeds_articles` template. ~It is also worth evaluating if the 2 different payload could share a unified template~ < not possible. 

**Describe the solution you'd like**
Edit the lang attribute in the Mozart page [template](https://github.com/bbc/mozart-page-configs/blob/master/templates/ws/av_embeds.mustache#L2) so that it can be defined in the request URL. 

**Describe alternatives you've considered**
If it is not possible to use the request URL to vary the lang then we will need to create a template for each service. 

**Testing notes**
We will want to make sure that the relevant `lang` code is returned as expected when visiting `ws` sites. 

**Media liveradio AV embed URLs**
https://www.test.bbc.com/ws/av-embeds/media/bbc_korean_radio/liveradio should have `lang="ko"`
https://www.test.bbc.com/ws/av-embeds/media/bbc_indonesia_radio/liveradio should have  `lang="id"`
https://www.test.bbc.com/ws/av-embeds/media/bbc_tigrinya_radio/liveradio should have  `lang="ti"`
https://www.test.bbc.com/ws/av-embeds/media/bbc_amharic_radio/liveradio should have  `lang="am"`
https://www.test.bbc.com/ws/av-embeds/media/bbc_afaanoromoo_radio/liveradio should have  `lang="om"`

**Articles AV embed URLs**
https://www.test.bbc.com/ws/av-embeds/articles/c3wmq4d1y3wo/p01kdbnv should have `lang="en-gb"`
https://www.test.bbc.com/ws/av-embeds/articles/c3wmq4d1y3wo/p01k6msp should have `lang="en-gb"`

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
It looks like we can use the [`request.language`](https://github.com/bbc/mozart-routing/blob/master/src/lib/mozart_routing/payloads/weather_error_page.rb#L15) as [`{{language}}`](https://github.com/bbc/mozart-page-configs/blob/master/templates/weather/article_page.mustache#L2)

We should check that these values are the write `lang` values we would expect.

**Comment by LilyL0u** [comment]
Just to check I will be testing this correctly, do I just need to check that the 'html lang="en"' changes to the appropriate language e.g lang="ko" @pjlee11 

![UNADJUSTEDNONRAW_mini_8](https://user-images.githubusercontent.com/54575620/64109857-75f0dd80-cd78-11e9-8fd2-0ac6c9ed0616.jpg)

**Comment by pjlee11** [comment]
@LilyL0u correct, just checking they match the correct lang for the service

**Comment by LilyL0u** [comment]
Sorry I accidentally closed and reopened the issue, because I thought the button just closed the window with the issue open in 🙈

**Comment by ryanmccombe** [comment]
We can't use `request.language`, as that comes from the following steps in mozart:

- Get the product from the first part of the URL
- Map the product to a language

This does not work for our embed URLs, as they do not contain the product.  Mozart believes the product is "ws" because that is the first part of the URL

We can implement an alternative method for the live radio URLs, as they have the service ID, and the product can be mapped from that, eg, `bbc_indonesian_radio` => `indonesia`

However, the articles URLs, and our proposed URLs for future page types, do not have enough information to determine the language / product.

Article URLs are in the format:  `/ws/av-embeds/articles/:ares_id/:vpid/?:amp?`

Possibly need a discussion on how to move forward with this

**Comment by ryanmccombe** [comment]
Blocked based on discussion with article pod - it's possible we don't do this ticket at all - waiting for confirmation

**Comment by ryanmccombe** [comment]
Unassigning from me as it is mostly down to articles if they want to change their URLs

Note Mozart does seem to accept query strings - to get lang from the request query string in Mozart routing:

```
Rack::Utils.parse_nested_query(@request.query_string)['lang'] || 'en'
```

If this value is added to the payload, eg, under the `language` key, it can then be used in mozart page config:

```
<html lang="{{language}}">
```

**Comment by pjlee11** [comment]
SMP itself produces an iframe which currently doesn't provide a `lang` attribute. We could potentially move forward without a `lang` attribute in the Mozart template

**Comment by jamesdonoh** [comment]
Next steps are to a11y test this to assess the actual impact on AT.

**Comment by pjlee11** [comment]
Update: as per https://github.com/bbc/simorgh/issues/3877 we have removed the hardcoded `lang` attribute from the `<html>` element of the embed page. This was decided as we effectively have the following in Simorgh:

```
<html lang='{{service_lang}}'>
  ...
  <iframe>
    <html> // AV embed created by Mozart
      <div>
        <iframe /> // SMP instance
      </div>
    </html>
  </iframe>
</html>
```

AFAICT  from Googling `iframes` are considered entirely seperate documents and therefore would need to specify the `lang` themselves. Therefore having `lang` in the embed only sets it for the single `<div>` before the next `<iframe>` (SMP) which currently doesn't support passing a `lang`. 

If we find that the a11y test for this doesn't have any errors I propose closing this Issue as won't fix.
