### ISSUE TITLE
Integrate Video into MainContent

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#335]
**Is your feature request related to a problem? Please describe.**
Video is not integrated into MainContent component.

**Describe the solution you'd like**
Whitelist the Video in the [MainContent Blocks whitelist](https://github.com/bbc/simorgh/blob/latest/src/app/components/MainContent/index.jsx#L13-L16).

**Comment by jtart** [comment]
I don't think it is valuable to do this ticket until we render a video: https://github.com/bbc/simorgh/issues/134.

**Comment by sareh** [comment]
This ticket is blocked since it should only be started on after the Video block is complete.
