### ISSUE TITLE
PRO assets missing `id` value to use as key in `FrontPageSection`

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#3354]
**Describe the bug**
```filterUnknownContentTypes``` has replaced ```filterUnknownCpsTypes``` and now allows PRO assets through, which is an issue for us as they dont have `id` values which we use as keys in mapping over items.

**To Reproduce**
If you have the React Developer Tools Chrome Extension:
1. Run ```npm run dev```
2. Go to the /pidgin page
3. Inspect page.
4. See errors below:
![image](https://user-images.githubusercontent.com/53564281/63526839-f2bdc500-c4f7-11e9-8bff-f499a92f14ad.png)

Or see locally on terminal here:
1. Go to src/app/container/FrontPageMain/index.test.jsx
2. Run ```npm run test:unit```
3. See errors below:
```
  console.error src/testHelpers/setupTests.js:53
    Warning: Each child in a list should have a unique "key" prop.

    Check the render method of `FrontPageSection`. See https://fb.me/react-warning-keys for more information.
        in StoryPromoLi (created by FrontPageSection)
        in FrontPageSection (created by FrontPageMain)
        in div (created by Context.Consumer)
        in StyledComponent (created by GridItemConstrainedLargeWithTopMargin)
        in GridItemConstrainedLargeWithTopMargin (created by FrontPageMain)
        in div (created by Context.Consumer)
        in StyledComponent (created by Grid)
        in Grid (created by FrontPageMain)
        in main (created by FrontPageMain)
        in FrontPageMain (created by FrontPageMainWithContext)
        in FrontPageMainWithContext
```
**Expected behavior**
PRO assets have an ID value (or similar) to use when looping over them

**Additional context**
This breaks the fix made here: https://github.com/bbc/simorgh/pull/3088

**Comment by andrew-nowak** [comment]
> Expected behavior
> filterUnknownContentTypes should filter out the articles tagged with "PRO" to avoid key prop warnings.

Please don't do this, we want to render PROs :(

We need to find a good alternative to `id`, and unfortunately PRO doesn't offer much:
![image](https://user-images.githubusercontent.com/10963046/63530277-0704c080-c4fe-11e9-8b02-d4877e9b3aa6.png)

Our best bet is perhaps something like `'$title-$timestamp'`

**Comment by DenisHdz** [comment]
For more context https://github.com/bbc/simorgh/pull/3132

**Comment by dr3** [comment]
Will likely need to make a preprocessor that adds Ids to the items, just like articles :)
