### ISSUE TITLE
Question: How should we track components

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#3366]
**Is your feature request related to a problem? Please describe.**
Based on the event tracking spike https://github.com/bbc/simorgh/pull/2957, we should decide whether we want to track components by class names (as per spike implementation), use data attributes, or maybe IDs.

This question issue is dependent on the result of https://github.com/bbc/simorgh/issues/3365, because we will only have to discuss this if we decide to keep logic out of Psammead.

**Describe the solution you'd like**
Discuss and decide on the best approach.
Document pros and cons of the methods mentioned above to decide on the way forward.

**Describe alternatives you've considered**
Use `onClick`s in Psammead.

**Comment by jamesbhobbs** [comment]
My view on this is less clear cut than on https://github.com/bbc/simorgh/issues/3365 but it is clear to me that we shouldn't use classes (they're for CSS).

re data attributes vs ids. I believe we should use data attributes, I don't think this will also require the use of ids. The use of ids wouldn't scale as well as data attributes and would add a new layer of complexity by not allowing duplicated ids.

**Comment by dr3** [comment]
I think this should work as a context around the application. You add a click listener to the document, and use `const { addListener } = useContext(EventContext)` then call `addListener('click', 'navigation', frontpageNavClickHandler)`. This `addListener` function will add the click event type onto an object.

When a click happens on the page, it checks the `data-type` attribute, if it equals ('navigation') it calls the `frontpageNavClickHandler` function. This function does all the ATI stuff for you.

The advantage of this is its scaleable to any type of event listener and any number of them. This also has the advantage of only creating 1 event listener on the whole page, not 1 per type or 1 per item, which is better for performance

(this is a rough idea, so may need cleaning up)
