### ISSUE TITLE
Chartbeat referrer 'v' value is wrong when clicking the 'back' button in browser

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#3368]
**Describe the bug**
When using the back button in Simorgh, the referrer in Chartbeat is wrong. Possibly related to #3369

**To Reproduce**

1. Go to https://www.test.bbc.co.uk/news/articles/cn7769kpk9mo
2. View the chartbeat beacon - the 'v' value will be this github issue
3. Click on the inline link to https://www.test.bbc.co.uk/news/articles/cl55zn0w0l4o
4. View the chartbeat beacon - the 'v' value will be the first article
5. Click back
6. View the chartbeat beacon - the 'v' value will be the second article

**Expected behavior**
6. View the chartbeat beacon - the 'v' value is correctly this github issue

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome & Firefox

**Testing notes**

- [x] This bug fix is expected to need manual testing.
- Create or edit e2e coverage for chartbeat referrers.
- Investigate what tests can be done for this issue based on new cypress test system.

**Additional context**

**Comment by rhenshaw56** [comment]
blocked pending a response from chartbeat support.

**Comment by rhenshaw56** [comment]
blocked till we can fix the multiple rendering issue on #1919

**Comment by rhenshaw56** [comment]
Unblocked. Moving this to ready for test as the referrer issue with back clicks have been fixed by charrbeat

**Comment by PriyaKR** [comment]
What is the value of expected when it says

`6. View the chartbeat beacon - the 'v' value is correctly this github issue`

so v value is expected to be `https://www.test.bbc.co.uk/referrer`?

**Comment by rhenshaw56** [comment]
> What is the value of expected when it says
> 
> `6. View the chartbeat beacon - the 'v' value is correctly this github issue`
> 
> so v value is expected to be `https://www.test.bbc.co.uk/referrer`?

@PriyaKR for now yes, created [this other issue](https://github.com/bbc/simorgh/issues/4573) to address that

**Comment by PriyaKR** [comment]
Looks good to me.
