### ISSUE TITLE
The first chartbeat request after a referral is wrong

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#3369]
**Describe the bug**
When clicking an inline link from one canonical page to another, the first chartbeat ping after clicking has matching p and v values

**To Reproduce**

1. Go to https://www.test.bbc.co.uk/news/articles/cl55zn0w0l4o
2. See that the chartbeat beacon has the correct p value and a v value of this github ticket
3. Click the inline link to https://www.test.bbc.co.uk/news/articles/cn7769kpk9mo
4. See that the first chartbeat beacon sent has updated the v value to be /news/articles/cl55zn0w0l4o but not updated the p value - so that both are the same - _This should not happen_
5. See that the second chartbeat beacon sent has updated the p value to be the second article, but also updated the v value to now include the domain in the url of the first article - _This is correct behaviour_

**Expected behavior**
The p and v values are always correct and consistent

**Comment by rhenshaw56** [comment]
blocked pending a response from chartbeat support

**Comment by rhenshaw56** [comment]
blocked till we can fix the multiple rendering issue on #1919

**Comment by rhenshaw56** [comment]
fixed via https://github.com/bbc/simorgh/pull/3622
