### ISSUE TITLE
Fix Low Severity 'Regular Expression Denial of Service' vulnerability

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#34]
Snyk is reporting a vulnerability with a low severity in the 'braces' package of 'razzle@2.0.3': https://snyk.io/test/github/bbc/simorgh#npm:braces:20180219

We should fix this.

**Comment by jamesbhobbs** [comment]
https://github.com/jaredpalmer/razzle/issues/438

**Comment by jamesbhobbs** [comment]
Should be fixed by https://github.com/jaredpalmer/razzle/pull/701 NB it is an experimental PR not an update.

**Comment by ChrisBAshton** [comment]
Will be fixed by whatever replaces #871.
