### ISSUE TITLE
Index Alsos - Related content translations

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#3403]
Blocked pending translations of "Related content"

**Is your feature request related to a problem? Please describe.**
A heading level 4 must be announced before the related items (index alsos).
And the h4’s announced text should be ‘Related content’.

This text is hardcoded in English at the moment.

**Describe the solution you'd like**
Add translations for `Related content` to the services config files.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by Bopchy** [comment]
We need to investigate how it works currently and the get translations

**Comment by DenisHdz** [comment]
Checked a couple of services and the offscreen text is empty 🤷🏻‍♂️

![mundo-related-content](https://user-images.githubusercontent.com/46446236/63932362-f4830d80-ca4e-11e9-8b91-c5d4d6786578.png)

**Comment by DenisHdz** [comment]
Closed as this will be added in addition with other translations.
