### ISSUE TITLE
Add all the front page titles to service config

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#3406]
**Is your feature request related to a problem? Please describe.**
After https://github.com/bbc/simorgh/pull/3376 we have a new service config key `frontPageTitle` which is used to override the title found in the data feed. In discussion, it would be best if this was used for each service.

**Describe the solution you'd like**
Add the `frontPageTitle` config key to each service, so that the title is no longer obtained from the data feed.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by andrew-nowak** [comment]
I would suggest that we use the values that can be found in the data feed in the `metadata.title` key for all services EXCEPT THAI

**Comment by sareh** [comment]
We already have `translations.home` that is this exact field - why can this not be used instead?
