### ISSUE TITLE
Add translations for error pages for Tigrinya 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#3409]
**Is your feature request related to a problem? Please describe.**
We need to add the cookie / privacy banner translations for the following live radio service

-Tigrinya 

**Describe the solution you'd like**
Add the translations to the service configs. Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-87)

**Testing notes**
[Tester to complete]

Dev insight: Unlikely to need a tester due to simplicity

**Additional context**
WSMEDIA-87

**Comment by LilyL0u** [comment]
In the line, ከም ኣማራጺ ከኣ [BBC News ረኣይ።], brackets being removed, ረኣይ። being taken out of brackets

**Comment by LilyL0u** [comment]
Fixes made. Tigrinya now reads ከም ኣማራጺ ከኣ BBC News ትግርኛ ረኣይ። (with the service name included).
