### ISSUE TITLE
Add Footer Translations for Tigrinya

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#3410]
We need to add footer translations for Tigrinya 

Add the translations to the service configs. Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-29)

**Testing notes**
[Tester to complete]

**Dev insight**: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

This feature is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
In the footer translation for the field 'Copyright message in footer'
the translation sheet says:
© 2019 BBC. ቢቢሲ ንናይ ደገ መርበብ ሓበሬታታት ሓላፍነት ኣይወስድን.      
  
The page currently says '© 2019 © 2019 BBC. ቢቢሲ ንናይ ደገ መርበብ ሓበሬታታት ሓላፍነት ኣይወስድን'
Where © 2019 is written twice. Needs to be written once, matching the sheet translation.

@ibMadbouly

**Comment by LilyL0u** [comment]
@ibMadbouly  I still see the double © 2019 even though I got the latest code. Did you make the change?
