### ISSUE TITLE
Bundle size script complains about Sport

### ISSUE THREAD

**Issue by andrew-nowak** [bbc/simorgh#3414]
**Is your feature request related to a problem? Please describe.**
When running `npm run build`, the build size script will complain that the bundle for Sport is too small:

`Bundle size for Sport is too small at 515 kB. Please update thresholds in './scripts/bundleSize.js'`

This is unsurprising, because we don't have a bundle for Sport, so the total bundle size is about 10k less than all of our actual services.

It seems that 'sport' was added to the cypress service config - https://github.com/bbc/simorgh/blob/e40490c33916c9ee176f31cfa2621bbd7a96c420/cypress/support/config/services.js#L876 - but nothing is running on the sport service on cypress (again, unsurprising, as we don't have a sport service)

**Describe the solution you'd like**
Remove `sport` from the Cypress service config.

**Describe alternatives you've considered**
Keep our lower bundle size limit artificially low

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by oluoluoxenfree** [comment]
This no longer seems to be true; sport is the smallest bundle but there is no error. Do we still need to remove sport from cypress? @aacn500

**Comment by andrew-nowak** [comment]
Sorry, I wouldn't know as I don't work on simorgh any more. Possibly someone else in the core pod may have a better idea?

**Comment by chris-hinds** [comment]
We will have a sport service pretty soon as we will be rendering the AMP articles for `/sport`, so we should keep sport here.
