### ISSUE TITLE
On the latest branch deploy run CI in tandem with deploy not before

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#3421]
**Is your feature request related to a problem? Please describe.**
On the latest branch deploys we run CI before we deploy to test, slowing deploy. And it means if there are CI flakes it blocks deploy. It's useful to run CI just in case of merge to latest from a branch that wasn't updated.

**Describe the solution you'd like**
For latest branch
Build steps -. Deploy and run tests in parallel

**Describe alternatives you've considered**
Leave as it

**Testing notes**
[Tester to complete]

Dev insight: No testing needed

- [ ] This feature is expected to need manual testing.

**Additional context**
While here we don't need propagate true the infra jobs fail and report by themselves, why fail the CI build if it passes but CD fails?

**Comment by chris-hinds** [comment]
@benjaminhobbs I don't see the need to do this with BG on the horizon. We will accomplish with BG in a slightly different way.

Closing but feel free to re-open
