### ISSUE TITLE
Header - Add logo hover state

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#343]
**Is your feature request related to a problem? Please describe.**
Header logo does not have a hover state.

**Describe the solution you'd like**
The logo should have a hover state of 4px underline in #FFFFFF.

![image](https://user-images.githubusercontent.com/16549467/43261881-20ca468c-90d6-11e8-9626-f2333e79ebbb.png)

**Additional Context**
Write tests for AC.

**Comment by jtart** [comment]
![image](https://user-images.githubusercontent.com/16549467/43261881-20ca468c-90d6-11e8-9626-f2333e79ebbb.png)
