### ISSUE TITLE
Cookie banner setting cookies to the wrong place

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3440]
**Describe the bug**
The simorgh consent banner sets cookies to `www.bbc.com` whereas the pal sets them to `.bbc.com`. This causes weird behaviour where we read from 1 domain, but write to another. This means the cookie banner cant be dismissed in some cases

**Unconfirmed:**
It appears that our cookie banner will read cookies set on `.bbc.com` and set cookies on `www.bbc.com`, which means you cant correct the values, and it will show the banners on every refresh

**To Reproduce**

On Chrome and Firefox 
1. Go to bbc.com/pidgin
2. Click on "Yes I agree" to the cookie settings
3. Refresh the page
4. See the cookie banner is displayed again 

**Expected behavior**
When you "Yes click I agree" then you don't see the cookie banner again when the page is refreshed

Simorgh sets cookies the same place that the pal does

**Screenshots**
![image](https://user-images.githubusercontent.com/11341355/63882037-0de17680-c9c9-11e9-8be8-4873379334d8.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
I started this in https://github.com/bbc/simorgh/compare/CorrectCookieDomain but I was unable to get the cypress tests to work, as they seemly cant delete cookies on `.bbc.com`. Not sure how to get around this

Any ideas @benjaminhobbs @hindsc52

**Comment by jamesbhobbs** [comment]
@dr3 this should be able to be done in vanilla JS. I don't think the security constraints of deleting cookies would apply in this case - so I think we can bypass the Cypress limitation

**Comment by ryanmccombe** [comment]
**Additional context (internal links)**
- https://bbcnews.slack.com/archives/CK85Q5SL9/p1579175002125200
- https://bbcnews.slack.com/archives/CJT0284G2/p1579174550037900

**Comment by aeroplanejane** [comment]
@LilyL0u Can you check that that the bug details and steps to reproduce are ok?

**Comment by karinathomasbbc** [comment]
Worth having a look at: https://github.com/js-cookie/js-cookie#domain

**Comment by LilyL0u** [comment]
> @LilyL0u Can you check that that the bug details and steps to reproduce are ok?

@aeroplanejane  Looks good but doesn't mention the privacy policy banner as well

**Comment by LilyL0u** [comment]
> @LilyL0u Can you check that that the bug details and steps to reproduce are ok?

@aeroplanejane looks good but I'd also mention it happens with the privacy policy banner too

**Comment by RichardPK** [comment]
Hey to reproduce you need to cross-pollenate your cookies a bit.

1. Clear your cookies
2. Visit https://www.bbc.com/pidgin
3. Visit a PAL page without accepting the cookies policy (i.e. https://www.bbc.com/pidgin/tori-51194083).
4. Still don't accept the cookies policy. Visit https://www.bbc.com/pidgin again.
5. You will now see the cookies banner repeatedly, even after accepting, while navigating through Simorgh pages.
6. If interested, you will now see the duplication of the cookies with different domains within your dev tools. One accepted, and one not.
![duplicate cookies](https://i.imgur.com/L8gvLrI.png)

**Comment by jroebu14** [comment]
@LilyL0u will be ready to test once deployed to test.bbc.com

**Comment by paruchurisilpa** [comment]
Looks good to me..

**Comment by LilyL0u** [comment]
Looks good to me too. Cookie banner does not appear again on Simorgh or PAL once it has been accepted. If the cookies are not accepted, the banner continues to show.

The cookie banner does appear again if you have accepted it on bbc.com, but then go to bbc.co.uk.

Accepting cookie banner on .co.uk stops it showing on .com.

**Comment by LilyL0u** [comment]
@jroebu14 The issue this ticket fixes works now - ready to merge?
