### ISSUE TITLE
We're not reporting test coverage on the latest branch

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#3441]
**Describe the bug**
We're not reporting test coverage on the latest branch

**To Reproduce**
See jenkins file, it's not run on latest branch

**Expected behavior**
It is

**Testing notes**
n/a
- [ ] This bug fix is expected to need manual testing.

**Additional context**
n/a

**Comment by hindsc52** [comment]
PR https://github.com/bbc/simorgh/pull/3862/files
