### ISSUE TITLE
Add ATI component to the MAP page

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#3454]
**Is your feature request related to a problem? Please describe.**

As a WS product manager I'd like the ability to track media asset page metrics with ATI Analytics on page load.

**Describe the solution you'd like**

Metrics will be captured on WS_NEWS_LANGUAGES_TEST 598343 until we release to production at which point we will capture analytics through WS_NEWS_LANGUAGES 598342

Example Media Asset Page: https://www.test.bbc.com/pidgin/media-49529724

AReS Payload: https://ares-broker.api.bbci.co.uk/api/asset/pidgin/media-49529724

| ID | ATI Site ID | Value | Source | mandatory |
|-|-|-|-|-|
| Destination (L1) | 598342 | WS_NEWS_LANGUAGES (*on live)*|Simorgh| Yes 
| | 598343|WS_NEWS_LANGUAGES_TEST (*on test)*|Simorgh| Yes |
|Producer  Level 2 |70|Pidgin |Simorgh| Yes |
|Chapter1|- |embedded_media (but can be world, news, embedded media - will generally be the second part of the page countername e.g. pidgin.embedded_media.media_asset.49529724.page ) |AReS| Yes |
|Page| -|pidgin.embedded_media.media_asset.49529724.page ("counterName" in payload) |AReS | Yes |
|*Custom Site Variables*| | | |
|Content ID (x1) |-|[urn:bbc:cps:c6f77da9-be7c-fb40-9a26-08fadbaede29] (this is in AReS payload in see "curie":"http://www.bbc.co.uk/asset/*c6f77da9-be7c-fb40-9a26-08fadbaede29*"|AReS| Yes |
|App Type (x2) |-|responsive OR amp |Simorgh| Yes |
|App name |-|news-pidgin|Simorgh | Yes | 
|Language|-|pcm |AReS| Yes | 
|URL|-|https://www.test.bbc.com/pidgin/media-49529724|Simorgh| Yes | 
|Content Type |-|article-media-asset|Simorgh| Yes | 
|Page Title (x9) |-|[BBC Pidgin Minute - BBC News Pidgin] (Defined as \{title} - BBC News Pidgin where content title is title from AReS payload)  | AReS for title / Simorgh for Brand | Yes | 
|Publication Date (x11) | -|[2018-05-23T05:54:44+00:00](firstPublished but needs to be converted from unix time)| AReS| Yes | 
|Update Date (x12) | -|[2018-05-23T05:54:44+00:00](lastUpdated but needs to be converted from unix time)|AReS | Yes | 
|Campaign (x16) | -|[WS - Inspire me] (Can be multiple values see: Campaigns / campaignName in payload) |AReS| No (can be blank) | 
| Category (x17) | -|[Feature] (defined as categoryName in the payload e.g. [news] [feature]) | AReS | No (can be blank) | 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

**Test against these URLs:** 
      '/japanese/video-23248670',
         '/korean/media-23248686',
         '/pidgin/23248703',
         '/punjabi/media-23248705',
         '/sinhala/23248970',
         '/uzbek/sport-23248721',
         '/thai/thailand-23248713',
         '/news/av/business-23249447'

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
Jira story - WSMEDIA-59

**Comment by aeroplanejane** [comment]
In order to fulfil the existing ATI e2e tests for the page we require just the following params 
 return atiPageViewParams({
    appName: atiAnalyticsAppName,
    contentId: metadata.id,
    contentType: 'player-live',
    language: metadata.language,
    pageIdentifier: path(['analyticsLabels', 'pageIdentifier'], metadata),
    pageTitle: path(['analyticsLabels', 'pageTitle'], metadata),
    producerId: atiAnalyticsProducerId,
    statsDestination,
    platform,
    service,
  });

**Comment by ryanmccombe** [comment]
Done most of the plumbing for this - just need to verify the values

Also, do we have an example of where Chapter 1, Campaign and Category are used on some other page?

These are all new custom variables for Simorgh, and not sure what type of data we need to pass to them

**Comment by ryanmccombe** [comment]
Campaign is custom variable "x16" - category is custom variable "x17", based on this URL used in an existing MAP:

```
https://a1.api.bbc.co.uk/hit.xiti?s=598342&idclient=04d23d65-b398-43ea-a667-c7482142d78a&ts=1571063545598&vtag=5.17.1&ptag=js&r=1920x1080x24x24&re=1250x665&hl=15x32x25&lng=en-US&idp=1532252417106&jv=0&p=embedded_media::pidgin.embedded_media.media_asset.49529724.page&s2=70&x1=[urn%3Abbc%3Acps%3Ac6f77da9-be7c-fb40-9a26-08fadbaede29]&x2=[responsive]&x3=[news-pidgin]&x4=[pcm]&x5=[https%3A%2F%2Fwww.bbc.com%2Fpidgin%2Fmedia-49529724]&x7=[article-media-asset]&x8=[reverb-1.0.1]&x9=[Inside%20Vintage%20Exotics%20Ghana%2C%20one%20of%20di%20biggest%20collection%20of%20old%20cars%20for%20West%20Africa%20-%20BBC%20News%20Pidgin]&x11=[2019-08-30T17%3A26%3A12%2B00%3A00]&x12=[2019-08-30T17%3A26%3A12%2B00%3A00]&x16=[WS%20-%20Inspire%20me]&x17=[Feature]&ref=
```

Chapter1 seems to be a built-in ATI feature - it's not a custom variable.  It seems to be invoked by prefixing it to the page identifier, seperated by `::` based on the above example

`p=embedded_media::pidgin.embedded_media.media_asset.49529724.page`

**Comment by LilyL0u** [comment]
Pidgin page https://www.test.bbc.com/pidgin/media-49529724 showing all values as expected in tag inspector:

![Image 21-10-2019 at 15 27](https://user-images.githubusercontent.com/54575620/67214323-7a03b800-f417-11e9-87d1-c3d45c923c87.jpg)
![UNADJUSTEDNONRAW_mini_61](https://user-images.githubusercontent.com/54575620/67214332-7c661200-f417-11e9-927d-3462583900a3.jpg)

And the above sample URLs in the table also have the corresponding values in tag inspector.

**Comment by aeroplanejane** [comment]
@LilyL0u added urls above - you were away last week when this was refined but we'll make sure the testing notes are complete when refining in the future - this is the JIRA issue: https://jira.dev.bbc.co.uk/browse/WSMEDIA-59

**Comment by LilyL0u** [comment]
Bug raised related to this: https://github.com/bbc/simorgh/issues/4374 - page title not including 'BBC News [service]' when it should.

**Comment by LilyL0u** [comment]
https://www.test.bbc.com/japanese/video-23248670 - Cannot see page visits captured in ATI on WS_NEWS_LANGUAGES_TEST Japanese as Japan is sent to NEWS_LANGUAGES_GNL. Do not have access to this at the moment so cannot test if it is working.

https://www.test.bbc.com/korean/media-23248686 - Page visits captured

https://www.test.bbc.com/pidgin/23248703 - Page visits captured

https://www.test.bbc.com/punjabi/media-23248705 - Page visits captured

https://www.test.bbc.com/sinhala/23248970 - Page visits captured

https://www.test.bbc.com/uzbek/sport-23248721 - Page visits captured

https://www.test.bbc.com/thai/thailand-23248713 - Page visits captured

**Comment by LilyL0u** [comment]
The following variables are being captured in ATI for each site:

- [x] Content ID (e.g urn:bbc:ares::asset:korean/media-23248686)
- [x] App type (e.g responsive)
- [x] App name (e.g news-korean)
- [x] Language (e.g ko)
- [x] URL (e.g https://www.test.bbc.com/korean/media-23248686)
- [x] Content type (e.g article-media-asset)
- [x] Page title (e.g 협상이 진행 중"이라며 "이것이 입법 절차이고, 이것은 가는 바늘에 실을 꿰는 것"이라고 덧붙였다) BUG linked https://github.com/bbc/simorgh/issues/4374
- [x] Publication date (e.g 2019-09-13T15:11:13.000Z)
- [x] Update Date (e.g 2019-09-13T15:11:14.000Z)
- [x] Campaign (e.g Amuse Me)
- [x] Category (e.g News)

![Image 28-10-2019 at 17 10](https://user-images.githubusercontent.com/54575620/67700477-e9445380-f9a5-11e9-87d8-9f81b3c45b18.jpg)

I can see these in
Korean
Pidgin
Punjabi (could not check Campaign or Category because could not connect to CPS to add them)
Sinhala (could not check Campaign or Category because could not connect to CPS to add them)
Uzbek (could not check Campaign or Category because could not connect to CPS to add them)
Thai (could not check Campaign or Category because could not connect to CPS to add them)
