### ISSUE TITLE
Cookie banner - Banner disappears after viewing settings in same tab

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#3460]
**Describe the bug**
On the cookie banner, if the user clicks the settings link, they are navigated to the cookies settings page. If they then click back, they go back to the previous page and the cookies banner has gone. This means that the user did not have a chance to agree to the non-essential cookies if they did not turn them on on the settings page.

**To Reproduce**

1. Go to the settings link on the cookies banner.
2. Click on the settings link (not the agree link!)
3. You are taken to the cookies settings page. Click back to return to the previous page
4. Observe that the cookies banner is gone.

**Expected behavior**
When the user returns to the page that showed the cookies banner, if they have not yet clicked agree, they are shown the banner so that they can choose to agree to the cookies.

**Screenshots**

After clicking OK on the privacy banner, and being shown the cookies banner:

<img width="1390" alt="Screenshot 2019-08-29 at 14 57 50" src="https://user-images.githubusercontent.com/54575620/63946760-97e31b00-ca6d-11e9-831f-4e8a5088eb7b.png">

After clicking settings and then back to return to the page:

<img width="1386" alt="Screenshot 2019-08-29 at 15 01 19" src="https://user-images.githubusercontent.com/54575620/63946920-e7294b80-ca6d-11e9-9a58-77cc04296373.png">

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Firefox
- Version: 68.0.2

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
The user can agree to the cookies on the settings page, but many users may not look down the page that far, or really read or interact with it. Then they will not get a chance to agree to the cookies.

**Comment by sareh** [comment]
Hi @LilyL0u Thanks for raising this issue. This is in fact expected behaviour. The first is a `Yes, I agree` and the second is `No, take me to settings`. So by selecting `No`, you have dismissed the cookie banner and so do not see the cookie banner again on future page visits.

**Comment by sareh** [comment]
Closing as this is expected behaviour.

**Comment by sareh** [comment]
To see this working on a Simorgh News article, visit https://www.bbc.co.uk/news/articles/cd4vr7lvrvmo <img width="1427" alt="Screenshot news article with cookie banner" src="https://user-images.githubusercontent.com/3028997/63949178-e4c8f080-ca71-11e9-8d8b-676dd444333c.png">
