### ISSUE TITLE
Add footer links

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#347]
**Acceptance Criteria**
> Given I view an article page
> And it is homed in News
> When I scroll to the bottom
> Then I see a footer
> And footer contains below links

|Label|Link|
|-------|-------|
|BBC News|https://www.bbc.com/news|
|Why you can trust the BBC|https://www.bbc.com/news/help-41670342|
|Terms of Use|https://www.bbc.com/terms/|
|About the BBC|https://www.bbc.com/aboutthebbc/|
|Privacy Policy|https://www.bbc.com/privacy/|
|Cookies|https://www.bbc.com/privacy/cookies/about|
|Accessibility Help|https://www.bbc.com/accessibility/|
|Contact the BBC|https://www.bbc.com/contact/|
|Copyright © 2018 BBC. The BBC is not responsible for the content of external sites.|not clickable|
|Read about our approach to external linking|https://www.bbc.com/help/web/links/|

**Describe the solution you'd like**
We need to style the text in the Footer component to match the UX&D designs referenced in https://jira.dev.bbc.co.uk/browse/NEWSART-595

**Comment by sareh** [comment]
Closed as fixed. See Footer Container on Storybook: https://simorghstorybook.now.sh
