### ISSUE TITLE
Separate the test env tests from simorgh-e2e Jenkins job

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#3473]
**Is your feature request related to a problem? Please describe.**
The test env failures are not critical, whereas the live tests are critical and the local tests tell us whether the default branch is safe.

**Describe the solution you'd like**
Separate the test env tests from simorgh-e2e Jenkins job this way the test env failures are totally isolated from the live and local test failures

**Describe alternatives you've considered**
Wait until we have B/G deployment when this makes more sense, but I don't see any point in waiting.

**Testing notes**
[Tester to complete]

Dev insight: n/a

- [ ] This feature is expected to need manual testing.

**Additional context**
n/a

**Comment by jamesbhobbs** [comment]
NB https://github.com/bbc/simorgh-infrastructure/issues/667

**Comment by thekp** [comment]
have one pipeline with 2 stages and have another with one (https://github.com/bbc/simorgh/blob/latest/Jenkinsfile-e2e#L85-L105)

**Comment by dr3** [comment]
Done in https://github.com/bbc/simorgh/pull/3606
