### ISSUE TITLE
Why all the ChromaticQA tests in this repo?!!!

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#3474]
**Is your feature request related to a problem? Please describe.**
We pay per snapshot. We have a lot of snapshot tests in ChromaticQA, every single story!

**Describe the solution you'd like**
Why don't we just test the full pages in this repo and the components separately in https://github.com/bbc/psammead/ ?

We can use this https://docs.chromaticqa.com/ignoring-elements

**Describe alternatives you've considered**
Nothing this seem pretty obvious, it also should discourage people creating components in Simorgh

**Testing notes**
Make sure everything in simorgh unchromaticqa is covered in psammead chromaticqa.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
This would save circa 5 mins of Jenkins runtime per push to the repo!!!!

There's also absolutely no need to run these tests on the latest branch, so we should just turn this off right away.

**Comment by PriyaKR** [comment]
Make sure everything in simorgh unchromaticqa is covered in psammead chromaticqa.

**Comment by jamesbhobbs** [comment]
Ignore all stories but a few pages without banners https://docs.chromaticqa.com/ignoring-elements
