### ISSUE TITLE
Update cookie banner logic to accept ckns_explicit = 2

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#3477]
**Is your feature request related to a problem? Please describe.**
GNL are making changes to how the Cookie Banner works in the EU/EEA (but not UK) - we need to make some changes as well.

**Describe the solution you'd like**
Currently, we display the cookie banner if the ckns_explicit cookie's value is not `1` (ie it is `0` or not set)

We now need to consider a value of 2 as also reflecting acceptance of the cookie banner.

**Describe alternatives you've considered**
N/A

**Implementation detail:**
We currently have [this function](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ConsentBanner/CanonicalLogic/index.js#L30)
```js
const showCookieBanner = () =>
  Cookie.get(EXPLICIT_COOKIE) !== COOKIE_BANNER_APPROVED;
```

This may need to change to
```js
const EXPLICIT_COOKIE_ACCEPTED_VALUES = ['1', '2'];

const showCookieBanner = () =>
  !EXPLICIT_COOKIE_ACCEPTED_VALUES.includes(Cookie.get(EXPLICIT_COOKIE));
```

i.e. if `EXPLICIT_COOKIE` (ckns_explicit) isnt `1` or `2`, show the banner

**Testing notes**
[Tester to complete]

Dev insight: Alllllllllll the unit tests

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
@jimjohnsonrollings We currently set `ckns_explicit` to `1` when you accept it, can we continue to do that?

**Comment by jimjohnsonrollings** [comment]
For the purposes of this issue, yes
