### ISSUE TITLE
Use new cookie banner for EU/EEA (non UK) users

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#3478]
**Is your feature request related to a problem? Please describe.**
GNL are making changes to how the cookie banner works in the EU/EEA (but not the UK).

**Describe the solution you'd like**
If the user is in the UK, then everything continues as at present.
If the user is elsewhere in the EU/EEA and their ckns_policy cookie is not set to `2`, then we display the new cookie banner (https://github.com/bbc/psammead/issues/1957), which:
* is an overlay for the whole page
* contains new wording
* sets the ckns_explicit cookie to `2` and the ckns_policy cookie to `111` when the user clicks/taps the 'accept' button

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by neildoughty** [comment]
What happens if a user is in neither the UK nor the EU/EEA?

**Comment by jamesbhobbs** [comment]
>What happens if a user is in neither the UK nor the EU/EEA?

They don't get a cookie banner at all (this isn't what Simorgh does, it's what the new logic above would be if using our ORBIT system). In simorgh we show the cookie banner to all canonical users and only EU/EEA on AMP (because it was an articles shortcut to live).

**Comment by dr3** [comment]
Blocked on https://github.com/bbc/simorgh/issues/3494
