### ISSUE TITLE
Footer landmark

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#348]
**Acceptance Criteria**
> Given I use a screen reader
> When I navigate to the content info landmark
> Then BBC News brand logo is the first thing to be announced
> And brand logo will be announced as 'BBC News'

**Describe the solution you'd like**
We need to ensure our mark-up is labelled appropriately to have screen readers work as expected.

**Additional context**
Example of `aria-label` usage: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

**Comment by sareh** [comment]
Closed as fixed. See Footer component on Storybook: https://simorghstorybook.now.sh
