### ISSUE TITLE
Footer links hover state

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#350]
**Acceptance Criteria**
> Given I view the footer
> When I hover on the text links
> Then text links must have a visible state change
> And they must not be identified by colour alone

**Describe the solution you'd like**
We need to style the logo in the Footer component to match the UX&D designs referenced in https://jira.dev.bbc.co.uk/browse/NEWSART-595

**Comment by sareh** [comment]
Closed since it is captured in this issue: https://github.com/bbc/simorgh/issues/226 AC is listed there, too.
