### ISSUE TITLE
Footer links focus state

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#351]
**Acceptance Criteria**
> Given I view the footer
> When I navigate by keyboard
> And I focus on the text links
> Then text links must have a visible state change
> And they must not be identified by colour alone
> And in addition they must have browser default styling (i.e. outline around link text)

**Comment by sareh** [comment]
Closed since this work is captured in this issue: https://github.com/bbc/simorgh/issues/226 Acceptance Criteria is listed there, too.
