### ISSUE TITLE
Confirm that the manifest.json is correct for Punjabi

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#3517]
Blocked on https://github.com/bbc/simorgh/issues/3516

**Is your feature request related to a problem? Please describe.**
Confirm that the links in the manifest.json are correct for the assets added in https://github.com/bbc/simorgh/issues/3516
Confirm that the link to the manifest.json is correct - it should not live in /article it should live in the root eg bbc.com/punjabi/manifest.json

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
LGTM

**Comment by hotinglok** [comment]
LGTM, closing after two 'approvals'
