### ISSUE TITLE
Footer text styling

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#352]
**Acceptance Criteria**
> Given I am viewing the footer
> When I view non linking text 
> Then it must be visually distinct from linking text

**Describe the solution you'd like**
We need to style the text in the Footer component to match the UX&D designs referenced in https://jira.dev.bbc.co.uk/browse/NEWSART-595

**Comment by sareh** [comment]
Closed as fixed. See Footer Component on Storybook: https://simorghstorybook.now.sh/
