### ISSUE TITLE
Suppress Audio player controls

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#3524]
**Is your feature request related to a problem? Please describe.**
The SMP player we are using the audio player on the Live Radio page presents controls that are not appropriate for Live Radio and should be suppressed. We may need to request that these controls are made toggle-able as the appear to be always on for the Sounds style player. 

**Describe the solution you'd like**
In the morph module news-av-player we sound suppress 'back to start' and 'jump to live' controls when `skin` is set to `audio`. This may be possible via the `ui.controls` setting ([details](http://cookbook.tools.bbc.co.uk/audiouilive/customise)).

**Describe alternatives you've considered**
None

**Testing notes**
* Manual inspection to verify that the controls are as-expected

Are we able to use Cypress to inspect the controls on the page?

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
Currently the controls we would like to suppress are not suppress-able, this is therefore blocked awaiting liaising with the SMP team. 

https://jira.dev.bbc.co.uk/browse/WSMEDIA-40?focusedCommentId=4460463&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4460463

**Comment by gavinspence** [comment]
Commented on the jira ticket above with editorial feedback - this can be dropped as a requirement for now. @pjlee11

**Comment by pjlee11** [comment]
Closing no longer required
