### ISSUE TITLE
Dependancy statuses are broken in the Simorgh readme.md

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#3526]
**Describe the bug**
Dependancy status and dev dependancy status image and links are broken in the Simorgh readme.md

**To Reproduce**

1. Click https://github.com/bbc/simorgh#simorgh
2. See that the images and links are broken for dependancies.

**Expected behavior**
They should show the correct image and link to the correct place

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Comment by FK78** [comment]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/34196381/69147432-d23ae200-0ac9-11ea-8643-880bcf919795.png">
Everything looks good on my end.

**Comment by HarveyPeachey** [comment]
> <img alt="image" width="934" src="https://user-images.githubusercontent.com/34196381/69147432-d23ae200-0ac9-11ea-8643-880bcf919795.png">
> 
> Everything looks good on my end.

Yeah I think Benjamin fixed it, he just didn't close it.
