### ISSUE TITLE
Footer links tab order

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#353]
**Acceptance Criteria**
> Given I view the footer
> When I navigate by keyboard
> Then the focus order is as per screenshot attached

**Describe the solution you'd like**
We need to ensure our mark-up is labelled appropriately to have screen readers work as expected.

**Comment by radiocontrolled** [comment]
![_thumb_639457](https://user-images.githubusercontent.com/916416/43066302-32f409f0-8e5c-11e8-922c-9c58b9e6b530.png)

I looked at this manually and the tab order is correct per the instructions in the image above

**Comment by sareh** [comment]
Closed as fixed. See Footer Container on https://simorghstorybook.now.sh/
