### ISSUE TITLE
Move/Rename MediaPlayer component because it's specific to optimo/articles and not reusable

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#3536]
The `MediaPlayer` component is specific to Optimo articles. It has articles specific data transformations and metadata concerns and is designed to only really be consumed by the [`Blocks` component](https://github.com/bbc/simorgh/tree/latest/src/app/containers/Blocks). It currently sits in the top level of the components directory which is misleading because that would suggest it is a reusable component outside of the context of articles.

**Proposed solution**
Rename [`MediaPlayer`](https://github.com/bbc/simorgh/blob/latest/src/app/containers/MediaPlayer/index.jsx) to `MediaPlayerBlock` and move it into the Blocks directory (and maybe consider any other components specific to `Blocks` to follow suit).

**Other solutions**
Move all of the `MediaPlayer` blocks data transformations into the `Blocks` component which will make the `MediaPlayer` component generic and reusable and only concerned with rendering amp or canonical media players and props drilling. 

After discussion what might be best is to separate out the logic from the block structure.

**Testing notes**
- Updating snapshots

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Comment by dr3** [comment]
>move it into the Blocks directory

Not sure it should be moved here, Simply naming it `ArticlesMediaPlayer` IMO

**Comment by jroebu14** [comment]
> Not sure it should be moved here, Simply naming it ArticlesMediaPlayer IMO

Also sounds good. Makes it pretty clear it only works in articles.
