### ISSUE TITLE
Review the fields required by WSMEDIA-86 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3551]
**Is your feature request related to a problem? Please describe.**
We have been given requirements for the Rich Media Tracking values that we need to provide on the live radio page. 

Metrics will be captured on `WS_NEWS_LANGUAGES_TEST`  until we release to production at which point we will capture analytics through `WS_NEWS_LANGUAGES`.

Values required:

| ID | Value |
|--- | ----- |
| Destination (L1) | WS_NEWS_LANGUAGES | 
| Producer (L2) | Afaan Oromoo |
| Content ID | urn:bbc:pips:bbc_oromo_radio |
| App Type | responsive |
| App name | news-afaanoromoo |
| Language | om-ET |
| Content Type | player-live |
| Page Title | Dhaggeeffadhaa - BBC News Afaan Oromoo |
| Chapter | - |
| Page | afaanoromoo.bbc_afaanoromoo_radio.liveradio.page |

**Describe the solution you'd like**
We should review these values, checking which ones we are missing from Ares response and which ones we can get from inside other values. 

EG: `Content Type` is a value we are missing, and `Content ID` we can create using the string `urn:bbc:pips:` with the `externalId` appended on the end. 

**Describe alternatives you've considered**
N/a

**Testing notes**
[Tester to complete]

Dev insight: No testing required

- ~[ ] This feature is expected to need manual testing.~

**Additional context**
Definition of done for this is to create an issue to supply the missing values we require from Ares in the payload, and also any other issues required for us to be able to provide all values in the table.

**Comment by ryanmccombe** [comment]
This was done here: https://github.com/bbc/simorgh/pull/2971

I don't think there's any more work needed here

Was some question at refinement over the hardcoding of `contentType` as `'player-live'` on the belief that this was hardcoded in both Simorgh and Morph

This does not seem to be the case - the value is used in simorgh only.

This could be moved to ARES if considered worthwhile

**Comment by staylos92** [comment]
The linked PR has been tested and merged. Is there any additional testing required for this ticket?

**Comment by LilyL0u** [comment]
Content ID is being updated to match what is expected. This can be seen in https://gist.github.com/ryanmccombe/06b1e7da8e95a481bf5396aa5b1ff63f

For example, the content id [urn:bbc:pips:bbc_oromo_radio] is currently captured as [urn:bbc:ares::ws_live:bbc_afaanoromoo_radio]

We are waiting for Mozart fixes for this, so I am moving this to Blocked.

**Comment by aeroplanejane** [comment]
These values should be here with the exception of **content id** of urn:bbc:pips:bbc_oromo_radio which will be urn:bbc:ares:bbc_oromo_radio until ARES updates the changes - this will be captured in another ticket https://github.com/bbc/simorgh/issues/3554. This should be covered when we test: https://github.com/bbc/simorgh/issues/3556
