### ISSUE TITLE
Ensure data validator runs when testing

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3553]
**Is your feature request related to a problem? Please describe.**
We recently removed the data validate command which stopped it running automatically

**Describe the solution you'd like**
Re-add data validator in our test scripts

**Describe alternatives you've considered**

**Testing notes**
Doesn't require testing by a tester.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
add `node dataValidator/index.js` back into one of our test scripts either `npm run test`

removed here: https://github.com/bbc/simorgh/pull/3374/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L32

**Comment by jamesbhobbs** [comment]
Replaced by https://github.com/bbc/simorgh/issues/3697
