### ISSUE TITLE
Create static live radio payloads for all services 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3554]
**Is your feature request related to a problem? Please describe.**
Create JSON payloads for all services that have liveradio. These payloads then need to be added as fixtures to the `data/` directory and given to Ares to host in an S3 bucket. 

Similar to https://github.com/bbc/simorgh/issues/2809

**Describe the solution you'd like**
Dynamically create the JSON payload for the service IDs listed in the table above using this script: 
https://gist.github.com/ryanmccombe/06b1e7da8e95a481bf5396aa5b1ff63f

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Ensure there is a payload available for all service IDs listed above in the URL format `ARES/api/ws-media/{{SERVICE_ID}}/liveradio`

- [x] This feature is expected to need manual testing.

**Additional context**
Definition of done is to have these payloads available via Ares.

**Comment by pjlee11** [comment]
Move information needed before this can be worked on, for each service we require [these values](https://gist.github.com/ryanmccombe/06b1e7da8e95a481bf5396aa5b1ff63f#file-payloadvariants-js-L12-L22)

**Comment by pjlee11** [comment]
Blocked awaiting the information specified in the comment above

**Comment by ryanmccombe** [comment]
https://gist.github.com/ryanmccombe/06b1e7da8e95a481bf5396aa5b1ff63f

**Comment by ryanmccombe** [comment]
Opened request with ARES on slack

**Comment by LilyL0u** [comment]
@pjlee11 @ryanmccombe Do we have the table of service IDs mentioned in this issue? It references a 'table above' but I do not see one. 
Want to make sure I check all the correct services.

**Comment by ryanmccombe** [comment]
Oops, this one isn't actually ready for test.  ARES have created the API response for all the services - this ticket is to copy them into Simorgh

We haven't done that yet
