### ISSUE TITLE
Live radio to Test for all services

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3555]
Requires #3554 to be completed first. 

Still to do, Cypress tests and Manual QA of the pages.

**Is your feature request related to a problem? Please describe.**
We should route all the services that have live radio on the test STMs to Mozart. Similar to this ticket https://jira.dev.bbc.co.uk/browse/OPS-222032. 

**Describe the solution you'd like**
```
afaanoromoo/bbc_afaanoromoo_radio/liveradio
afrique/bbc_afrique_radio/liveradio
amharic/bbc_amharic_radio/liveradio
arabic/bbc_arabic_radio/liveradio
bengali/bbc_bangla_radio/liveradio
burmese/bbc_burmese_radio/liveradio
gahuza/bbc_gahuza_radio/liveradio
hausa/bbc_hausa_radio/liveradio
hindi/bbc_hindi_radio/liveradio
indonesia/bbc_indonesian_radio/liveradio
korean/bbc_korean_radio/liveradio
kyrgyz/bbc_kyrgyz_radio/liveradio
nepali/bbc_nepali_radio/liveradio
pashto/bbc_pashto_radio/liveradio
persian/bbc_persian_radio/liveradio
persian/bbc_dari_radio/liveradio
russian/bbc_russian_radio/liveradio
sinhala/bbc_sinhala_radio/liveradio
somali/bbc_somali_radio/liveradio
swahili/bbc_swahili_radio/liveradio
tamil/bbc_tamil_radio/liveradio
tigrinya/bbc_tigrinya_radio/liveradio
urdu/bbc_urdu_radio/liveradio
uzbek/bbc_uzbek_radio/liveradio

```

All of these should be available over `www.test.bbc.com/`. 

The following services are on Test prior to this issue: 
- tigrinya
- indonesia
- korean
- amharic
- afaanoromoo

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Manual test is required, all URL's listed should server a 200 and a page similar to the screenshot below. 

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
| Site | Service ID | language | pageIdentifier | pageTitle | title | description | uri | producerId | producer | contentID | appName | appType | Destination (production) | Destination ID (production) | contentType |
| ---- | ---------- | -------- | -------------- | --------- | ----- | ----------- | --- | ---------- | -------- | --------- | ------- | ------- | ------------------------ | --------------------------- | ----------- |
| afrique | bbc_afrique_radio | fr | afrique.bbc_afrique_radio.liveradio.page | BBC Afrique Radio - BBC News Afrique | BBC Afrique Radio | Infos, musique et sports | /afrique/bbc_afrique_radio/liveradio | 3 | AFRIQUE | urn:bbc:pips:bbc_afrique_radio | news-afrique | responsive | WS_LANGUAGES | 598342 | player-live |
| arabic | bbc_arabic_radio | ar | arabic.bbc_arabic_radio.liveradio.page | إذاعة بي بي سي العربية - BBC News Arabic | إذاعة بي بي سي العربية | خدمة إخبارية على مدار الساعة و برامج حوارية وتفاعلية تناقش قضايا المنطقة والعالم وباقة من البرامج المنوعة من إذاعة بي بي سي | /arabic/bbc_arabic_radio/liveradio | 5 | ARABIC | urn:bbc:pips:bbc_arabic_radio | news-arabic | responsive | WS_LANGUAGES | 598342 | player-live |
| bengali | bbc_bangla_radio | bn | bengali.bbc_bangla_radio.liveradio.page | বিবিসি বাংলা - BBC News বাংলা | বিবিসি বাংলা | বাংলাদেশ, তার প্রতিবেশী এবং গোটা বিশ্বের সংবাদ পরিবেশন করে। সংবাদদাতার প্রতিবেদন ছাড়াও আছে সাক্ষাৎকার, সংবাদপত্র পর্যালোচনা এবং সরাসরি ফোন-ইন। | /bengali/bbc_bangla_radio/liveradio | 31 | BENGALI | urn:bbc:pips:bbc_bengali_radio | news-bengali | responsive | WS_LANGUAGES | 598342 | player-live |
| burmese | bbc_burmese_radio | my | burmese.bbc_burmese_radio.liveradio.page | ဘီဘီစီ မြန်မာပိုင်း ရေဒီယို - BBC News မြန်မာ | ဘီဘီစီ မြန်မာပိုင်း ရေဒီယို | နေ့စဉ် ပြည်တွင်း ပြည်ပ သတင်းနဲ့ သုံးသပ်ချက်များ၊ ပညာရေး၊ ကျန်းမာရေး၊ အားကစား၊ နည်းပညာ အစီအစဉ်များ နဲ့ မျက်မှောက်ရေးရာ ဆွေးနွေးခန်းများ | /burmese/bbc_burmese_radio/liveradio | 35 | BURMESE | urn:bbc:pips:bbc_burmese_radio | news-burmese  | responsive | WS_LANGUAGES | 598342 | player-live |
| gahuza | bbc_gahuza_radio | rw | gahuza.bbc_gahuza_radio.liveradio.page | Radio BBC Gahuza - BBC News Gahuza | Radio BBC Gahuza | Amakuru y’amahanga, ubusesenguzi, amakuru y’akarere k’ibiyaga bigari, ikinamico, ubuzima, imibereho y’abagore. Kuri FM no kuri internet. | /gahuza/bbc_gahuza_radio/liveradio | 40 | GAHUZA | urn:bbc:pips:bbc_gahuza_radio | news-gahuza | responsive | WS_LANGUAGES | 598342 | player-live |
| hausa | bbc_hausa_radio | ha | hausa.bbc_hausa_radio.liveradio.page | BBC Hausa Rediyo - BBC News Hausa | BBC Hausa Rediyo | Labaran duniya da sharhi da kuma bayanai kan al'amuran yau da kullum daga sashin Hausa na BBC. | /hausa/bbc_hausa_radio/liveradio | 51 | HAUSA  | urn:bbc:pips:bbc_hausa_radio | news-hausa | responsive | WS_LANGUAGES | 598342 | player-live |
| hindi | bbc_hindi_radio | hi | hindi.bbc_hindi_radio.liveradio.page | बीबीसी हिंदी - BBC News हिंदी | बीबीसी हिंदी | दुनिया और भारत की ख़बरें, विश्लेषण और फ़ीचर. हिंदी में संवाद के सूत्रधार | /hindi/bbc_hindi_radio/liveradio | 52 | HINDI | urn:bbc:pips:bbc_hindi_radio | news-hindi | responsive | WS_LANGUAGES | 598342 | player-live |
| kyrgyz | bbc_kyrgyz_radio | ky | kyrgyz.bbc_kyrgyz_radio.liveradio.page | Би-Би-Си Кыргыз кызматынын радиосу - BBC News Кыргыз КызMATы | Би-Би-Си Кыргыз кызматынын радиосу | Эл аралык жана жергиликтүү жаңылыктар, аналитика, кызыктуу материалдар кыргыз тилинде | /kyrgyz/bbc_kyrgyz_radio/liveradio | 58 | KYRGYZ | urn:bbc:pips:bbc_krygyz_radio | news-krygyz | responsive | WS_LANGUAGES | 598342 | player-live |
| nepali | bbc_nepali_radio | ne | nepali.bbc_nepali_radio.liveradio.page | बीबीसी नेपाली रेडियो - BBC News नेपाली | बीबीसी नेपाली रेडियो | नेपाली भाषामा बीबीसी विश्व सेवाको राष्ट्रिय तथा अन्तर्राष्ट्रिय समाचार तथा समसामयिक चर्चा, राष्ट्रिय तथा अन्तर्राष्ट्रिय समाचार विश्लेषण, समाचारमा रहेका व्यक्तित्वहरुसंगको अन्तर्वार्ता, साप्ताहिक बहस तथा छलफल, विज्ञान, स्वास्थ्य. | /nepali/bbc_nepali_radio/liveradio | 63 | NEPALI | urn:bbc:pips:bbc_nepali_radio | news-nepali | responsive | WS_LANGUAGES | 598342 | player-live |
| pashto | bbc_pashto_radio | ps | pashto.bbc_pashto_radio.liveradio.page | بي بي سي افغانستان (پښتو خپرونه) - BBC News پښتو | بي بي سي افغانستان (پښتو خپرونه) | بي بي سي د افغانستان لپاره کورني، سیمه ییز او نړیوال وروستي او کره خبرونه د هر اړخېزو څېړونو او شننو سره تاسې ته وړاندې کوي. په پښتو او دري ژبو بېلا بېلې سیاسي، اقتصادي، ټولنېزې او روزنیزې خپرونې هر ورځ د سهار له ۵ بجو نه د شپې تر ۱۲ بجو پورې خپروي | /pashto/bbc_pashto_radio/liveradio | 68 | PASHTO | urn:bbc:pips:bbc_pashto_radio | news-pashto | responsive | WS_LANGUAGES | 598342 | player-live |
| persian | bbc_persian_radio | fa | persian.bbc_persian_radio.liveradio.page | رادیو فارسی بی‌بی‌سی - BBC News فارسی | رادیو فارسی بی‌بی‌سی | مجله خبری بخش فارسی رادیو بی‌بی‌سی را هر روز از ساعت ۶ تا ۸ صبح به وقت تهران (۲:۳۰ تا ۴:۳۰ به وقت گرینیچ) بشنوید. این برنامه شامل تازه‌ترین خبرهای روز ایران و جهان، به همراه گزارش، گفت وگو و تحلیل و تفسیر درباره رویدادهای ایران، منطقه و جهان است. | /pashto/bbc_pashto_radio/liveradio | 69 | PERSIAN  | urn:bbc:pips:bbc_persian_radio | news-persian | responsive | WS_LANGUAGES | 598342 | player-live |
| persian | bbc_dari_radio | fa | persian.bbc_dari_radio.liveradio.page | بی بی سی افغانستان (برنامه های دری) - BBC News فارسی | بی بی سی افغانستان (برنامه های دری) | بی بی سی برای افغانستان تازه ترین و دقیق ترین خبرهای افغانستان ، منطقه و جهان را با تحلیل های همه جانبه ارایه می کند. برنامه های مختلف سیاسی، اجتماعی، فرهنگی و آموزشی از ساعت پنج صبح تا دوازده شب به زبان های دری و پشتو از بی بی سی برای افغانستان. | /persian/bbc_dari_radio/liveradio | 69 | PERSIAN  | urn:bbc:pips:bbc_dari_radio | news-persian | responsive | WS_LANGUAGES | 598342 | player-live |
| russian | bbc_russian_radio | ru | russian.bbc_russian_radio.liveradio.page | Русская служба Би-би-си - BBC News Русская служба | Русская служба Би-би-си | мировые новости с местным колоритом. Как видятся события в России и регионе из-за рубежа. | /russian/bbc_russian_radio/liveradio | 75 | RUSSIAN | urn:bbc:pips:bbc_russian_radio | news-russian | responsive | WS_LANGUAGES | 598342 | player-live |
| sinhala | bbc_sinhala_radio | si | sinhala.bbc_sinhala_radio.liveradio.page | බීබීසී සිංහල සංදේශය - BBC News සිංහල | බීබීසී සිංහල සංදේශය | බීබීසී සිංහල ඔස්සේ ශ්‍රී ලාංකීය, දකුණු ආසියාතික සහ ජාත්‍යන්තර පුවත්, විශ්ලේෂණ සහ ක්‍රීඩා පුවත් | /sinhala/bbc_sinhala_radio/liveradio | 82 | SINHALA | urn:bbc:pips:bbc_sinhala_radio | news-sinhala | responsive | WS_LANGUAGES | 598342 | player-live |
| somali | bbc_somali_radio | so | somali.bbc_somali_radio.liveradio.page | Raadiyaha BBC Soomaali - BBC News Somali | Raadiyaha BBC Soomaali | Wararka iyo xaaladda taagan ee dunida oo dhan, faallo, muusig, madadaallo iyo cayaaro. | /somali/bbc_somali_radio/liveradio | 83 | SOMALI | urn:bbc:pips:bbc_somali_radio | news-somali | responsive | WS_LANGUAGES | 598342 | player-live |
| swahili | bbc_swahili_radio | sw | swahili.bbc_swahili_radio.liveradio.page | BBC Swahili Radio - BBC News Swahili | BBC Swahili Radio | Habari za kimataifa, michezo na uchambuzi kutoka kwa idhaa ya dunia. | /swahili/bbc_swahili_radio/liveradio | 86 | SWAHILI | urn:bbc:pips:bbc_swahili_radio | news-swahili | responsive | WS_LANGUAGES | 598342 | player-live |
| tamil | bbc_tamil_radio | ta | tamil.bbc_tamil_radio.liveradio.page | பிபிசி தமிழோசை - BBC News தமிழ் | பிபிசி தமிழோசை | சர்வதேச, இந்திய, இலங்கை செய்திகள் மற்றும் நடப்புத் தகவல்களை வழங்கும் ஓர் நிகழ்ச்சி. அறிவியல், விளையாட்டு, கலை, கலாச்சாரம் மற்றும் பொழுதுபோக்கு தொடர்பான செய்திகளும் இதில் இடம்பெறும். சிற்றலை வானொலியிலும் பிபிசிதமிழ்.காம் இணையதளத்திலும் இதைக் கேட்கலாம். | /tamil/bbc_tamil_radio/liveradio | 87 | TAMIL | urn:bbc:pips:bbc_tamil_radio | news-tamil | responsive | WS_LANGUAGES | 598342 | player-live |
| urdu | bbc_urdu_radio | ur | urdu.bbc_urdu_radio.liveradio.page | بی بی سی اردو ریڈیو - BBC News اردو | بی بی سی اردو ریڈیو | اردو زبان کے معتبر ترین خبررساں اداروں میں ایک، بی بی سی اردو کی جانب سے مصدقہ خبریں اور جامع تجزیے | /urdu/bbc_urdu_radio/liveradio | 95 | URDU | urn:bbc:pips:bbc_urdu_radio | news-urdu | responsive | WS_LANGUAGES | 598342 | player-live |
| uzbek | bbc_uzbek_radio | uz | uzbek.bbc_uzbek_radio.liveradio.page | BBC Uzbek Radio - BBC News O'zbek | /uzbek/bbc_uzbek_radio/liveradio | 96 | UZBEK | urn:bbc:pips:bbc_uzbek_radio | news-uzbek | responsive | WS_LANGUAGES | 598342 | player-live |
| afaanoromoo | bbc_oromo_radio | om | afaanoromoo.bbc_afaanoromoo_radio.liveradio.page | Dhaggeeffadhaa - BBC News Afaan Oromoo | Dhaggeeffadhaa | Sagantaawwan keenya | /afaanoromoo/bbc_afaanoromoo_radio/liveradio | 2 | AFAAN_OROMOO | urn:bbc:pips:bbc_oromo_radio | news-afaanoromoo | responsive | WS_LANGUAGES | 598342 | player-live |
| amharic | bbc_amharic_radio | am | amharic.bbc_amharic_radio.liveradio.page | ያድምጡ - BBC News አማርኛ | ያድምጡ | ዝግጅቶቻችንን’ | /amharic/bbc_amharic_radio/liveradio | 4 | AMHARIC | urn:bbc:pips:bbc_amharic_radio | news-amharic | responsive | WS_LANGUAGES | 598342 | player-live |
| indonesian | bbc_indonesian_radio | id | indonesia.bbc_indonesian_radio.liveradio.page | BBC Indonesia Radio - BBC News Indonesia | BBC Indonesia Radio | BBC Indonesia Radio: Berita dunia, ulasan, berita olahraga dan majalah mingguan dari BBC Indonesia Radio. | /indonesia/bbc_indonesian_radio/liveradio | 54 | INDONESIAN | urn:bbc:pips:bbc_indonesian_radio | news-indonesian | responsive | WS_LANGUAGES | 598342 | player-live |
| korean | bbc_korean_radio | ko | korean.bbc_korean_radio.liveradio.page | BBC 코리아 라디오 - BBC News 코리아 | BBC 코리아 라디오 | 세계와 한반도 뉴스를 공정하고 객관적으로 전달해 드립니다 | /korean/bbc_korean_radio/liveradio | 57 | KOREAN | urn:bbc:pips:bbc_korean_radio | news-korean | responsive | WS_LANGUAGES | 598342 | player-live |
| tigrinya | bbc_tigriny_radio | ti | tigrinya.bbc_tigrinya_radio.liveradio.page | ስምዑ - BBC News ትግርኛ | ስምዑ | መደባትና | /tigrinya/bbc_tigrinya_radio/liveradio | 91 | TIGRINYA | urn:bbc:pips:bbc_tigrinya_radio | news-tigrinya | responsive | WS_LANGUAGES | 598342 | player-live |

**Comment by gavinspence** [comment]
Is this not done already @pjlee11 ?

**Comment by pjlee11** [comment]
@gavinspence I think we probably need some QA to check each service and then some Cypress Tests added for each service against `www.test`
