### ISSUE TITLE
Pass ATI values to SMP for live radio

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3556]
**Is your feature request related to a problem? Please describe.**
After #3551 is completed we will need to pass the necessary ATI values to SMP with the playlist object. 

**Describe the solution you'd like**
Ensure the following ATI tracking values are passed to SMP in the `news-av-player` morph module for live radio.

Values for every service detailed in https://jira.dev.bbc.co.uk/browse/WSMEDIA-40. 

SMP SETTINGS OBJECT 

| Setting name | Value source | Value example | If no value? |
| ------------- | ------------- | -------------- | ------------ |
| counterName |  AReS | afaanoromoo.bbc_afaanoromoo_radio.liveradio.page | Mandatory |
| statsObject.destination | ? | "WS_LANGUAGES_TEST”  or on test “WS_LANGUAGES” on live  | Mandatory |
| statsObject.producer | ? | “AFAAN_OROMOO” | Mandatory |
| appType | ? | responsive OR amp | Mandatory |
| appName | ? | news-afaanoromoo | Mandatory |
| product |	? | News | Mandatory |
 	 	 	 	 	 
SMP PLAYLIST OBJECT 

| Field name | Value source | Value example | If no value? |
| ----------- | ------------- | -------------- | ------------ |
| title | model.versions[0].title | "Dhaggeeffadhaa - BBC News Afaan Oromoo" | Mandatory |
| autoplay | - | False | - |
| liveRewind | - | True | - |
| Simulcast | - | True | - |
| items | Ares |	[] | Mandatory |
| items[i].serviceID | Ares | bbc_oromo_radio | Mandatory |
| items[i].live	| Ares | True | Mandatory |
| items[i].kind	| Ares | radioProgramme | Mandatory |

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Using the ATI tracking add on check the values pass match as per the table above. Unit tests also required.

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
Add on is "ATI tag Inspector" - https://chrome.google.com/webstore/detail/at-internet-tag-inspector/epdfbeoiphkaeapcohmilhmpdeilgnok?hl=en

**Comment by ryanmccombe** [comment]
This should already be done - there's a unit test that confirms the SMP settings match this mock: https://github.com/bbc/morph-modules/blob/master/news-av-player/test/fixtures/liveradio-smp-settings.js

This ticket can be used to verify

**Comment by LilyL0u** [comment]
Linked to bug https://github.com/bbc/simorgh/issues/3668, the Rich Media is not being Captured in WS_LANGUAGES_TEST, instead is being captured in WS_LANGUAGES (live). This is something we can fix, then can be tested.

**Comment by LilyL0u** [comment]
Not sure what to do with this issue. I think it needs a discussion on what we are really expecting, or where to find these values, as many in the above SMP Playlist Object table I cannot see captured anywhere when looking in Tag Inspector or ATI Explorer.

@aeroplanejane any ideas?

**Comment by LilyL0u** [comment]
Looking over the values in the table above to see what we should be capturing and what we are:

items[i].serviceID: bbc_korean_radio is being captured with the name Media name: bbc_korean_radio
items[i].live: true, seems to be instead Media broadcast mode: live
items[i].kind: radioProgramme seems to be instead Media type: audio

And the following

title | model.versions[0].title | "Dhaggeeffadhaa - BBC News Afaan Oromoo" 
autoplay | - | False 
liveRewind | - | True 
Simulcast | - | True 
items | Ares | []

Cannot be seen in tag inspector or Explorer

@pjlee11 is this acceptable? We think maybe this is just requirements not being clear for everyone as to what we should see in ATI.

**Comment by ryanmccombe** [comment]
@LilyL0u this ticket is quite confusing - it's conflating the values we need to pass to SMP with the ones we need to pass to ATI

The tables above are the expected SMP values.

The expected ATI values are here: https://jira.dev.bbc.co.uk/browse/WSMEDIA-86

**Comment by ryanmccombe** [comment]
The original implementation is here, for reference: https://github.com/bbc/simorgh/pull/2971

Screenshots of what the ATI tag inspector looked like are in the comments of that PR

**Comment by aeroplanejane** [comment]
@LilyL0u @pjlee11 @ryanmccombe 
Values we expect to be passed to SMP and captured through ATI (other values are set by SMP we do not have control over them) 

level 2 site as media level 2: e.g. 4 (amharic) 
media name (service id) e.g. bbc_korean_radio 
media broadcast mode: live 
media type: audio 
Duration: 0 

Site number (destination) e.g. WS_LANGUAGES_TEST

**Comment by ryanmccombe** [comment]
All the values are set by SMP - our IFrame has no ATI code at all.  SMP tries to figure out what to pass to ATI based on the settings object we give it.

From the above list:

**Destination:**
This is stored as a site ID rather than the name "WS_LANGUAGES_TEST"
The site ID is 598343
See the "Producer" table here: http://bbc.github.io/echo-docs/documentation/reporting-ati/

This appears to be on the tag inspector correctly (on the left table)

**Level 2 Site:**
This is also referred to producer
I believe ATI shows the numeric representation (eg 57) instead of eg "Korean"
See the second table under "Producer" here: http://bbc.github.io/echo-docs/documentation/reporting-ati/

This appears to be on the tag inspector correctly (on the left table)

**Media Name
Media Broadcast Mode
Media Type
Duration**
All appearing on ATI inspector, and appear to be correct

![Screen Shot 2019-09-16 at 16 00 15](https://user-images.githubusercontent.com/8601460/64969178-550da980-d89b-11e9-86e8-e6b11f30e0b2.png)

**Comment by ryanmccombe** [comment]
**Cookbook:** http://cookbook.tools.bbc.co.uk/audiouilive/customise
**Our SMP settings:** https://github.com/bbc/morph-modules/blob/master/news-av-player/test/fixtures/liveradio-smp-settings.js

**Comment by LilyL0u** [comment]
Values are matching the corrected requirements by @ryanmccombe for Korea, Indonesia, Amharic and Tigrinya.

As the Afaan Oromoo player isn't working, I cannot check the richMedia tags for it. Are we going to fix this soon?

The richMedia rows in the tag inspector do not show the Level 2 producer. Is this OK?

**Comment by ryanmccombe** [comment]
Don't think we were aware Afaan Oromoo wasn't working - seems to be broken on staging and test.  Will investigate as a seperate issue to this ticket!

**Comment by LilyL0u** [comment]
Values are matching for Afaan Oromoo, tested now the player is fixed. 

Do we mind that the Level 2 producer is not showing in tag inspector for the richMedia rows? @aeroplanejane 

![Image 18-09-2019 at 16 46](https://user-images.githubusercontent.com/54575620/65163980-e6b01f00-da33-11e9-94de-db081af50010.jpg)

**Comment by aeroplanejane** [comment]
Hey Lily - yes that's fine! That value is captured as media level 2 when we
expect the hit and we see level 2 in ATI explorer
[image: Screenshot 2019-09-19 at 09.03.58.png]

**Comment by aeroplanejane** [comment]
@LilyL0u closing this as done
