### ISSUE TITLE
Add all 'add to homescreen' assets to the project

### ISSUE THREAD

**Issue by Bopchy** [bbc/simorgh#3588]
**Is your feature request related to a problem? Please describe.**
All the `add to homescreen` assets for all services need to be added to the project.

**Describe the solution you'd like**
Add the assets for the different services at once, in one PR. Also confirm links to these assets are correct in the manifest.json and that the link to the manifest is correct - not in the articles directory. 

**Describe alternatives you've considered**
N/A.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
The assets can be found here -- https://www.dropbox.com/sh/4eljarf21j4p2hl/AADOfRYB4byBdzB4PpoMvSXza?dl=0

**Comment by j-pendlebury** [comment]
Example PR: https://github.com/bbc/simorgh/pull/3544
