### ISSUE TITLE
Refactor Metadata container/component

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#3598]
I'm working on adding metadata to media asset pages and after having a dig around the Metadata container component I was thinking of doing some refactoring to it but wanted to check with you all first. I think with the addition of more page types it's starting to get complex.

The Metadata container component currently take 2 props - `metadata` and `promo` which are both objects that can have varying data structures depending on the page type. The Metadata container gets what it needs from `metadata` and `promo` by checking for the existence of object paths and properties or by doing different things based on page type and then uses that along with context data and other bits and pieces to build props to pass down to the Metadata and LinkedData component.

In summary the Metadata container looks like it was made specifically for articles, then roughly adapted for both front page and media. It's become designed to have any data thrown at it and then be responsible for getting what it needs by any means necessary. This also makes the prop type definitions complex.

I was thinking it would be better to pass the Metadata container primitive values instead of objects that can vary in structure. This would prevent things like this in the Metadata container:

```js
const getTitle = promo =>
  pathOr(null, ['headlines', 'seoHeadline'], promo)
    ? pathOr(null, ['headlines', 'seoHeadline'], promo)
    : pathOr(null, ['name'], promo);

const getDescription = (metadata, promo) =>
  pathOr(null, ['summary'], promo) ||
  pathOr(null, ['headlines', 'seoHeadline'], promo) ||
  pathOr(null, ['summary'], metadata);
```
and

```js
  if (pageType === 'article') {
    const id = metadata.id.split(':').pop();
    link = `${linkOrigin}/${service}/articles/${id}`;
  } else if (pageType === 'frontPage') {
    link = `${linkOrigin}/${service}`;
  } else {
    // different payload formats have the uri in various places
    link = `${linkOrigin}${promo.uri || metadata.locators.assetUri}`;
  }
```

instead you could construct and pass these in at the page component level e.g. `<MetadataContainer title={title} description={description} link={link} />`

Thoughts?

**Alternative solutions**
We could have separate metadata component specific to the page type e.g. MetadataContainer and ArticleMetadataContainer where ArticleMetadataContainer contains stuff only used in articles.

**Other notes**
The analytics container has very similar requirements but had a really nice design to deal with the fact the payloads were different - it had like a "mapper" function to standardise them.

With regards to the rendering of meta tags - every meta tag can just be in this format so everything's optional and you just have to pass in what you want
`{pageTitle && <meta name="og:title" content={pageTitle} />}`

**Comment by jroebu14** [comment]
I'm happy to undertake this work as part of resolving this issue https://github.com/bbc/simorgh/issues/3454

**Comment by dr3** [comment]
SGTM, might be easier to refactor, then add media page stuff, but idm :)

**Comment by jroebu14** [comment]
My approach to this is going to be:

1. Make metadata tests easier to understand, maintain and have more confidence in.
2. Separate out article specific metadata into a separate component called ArticleMetadata
3. Separate out front page specific metadata into a separate component called FrontPageMetadata
4. Move any page type splitting logic from MetadataContainer up to the page components.
5. Move the Metadata component into the MetadataContainer and then delete the Metadata component.

I'll create separate PRs for each stage.

**Comment by jroebu14** [comment]
Blocked by https://github.com/bbc/psammead/pull/2125
