### ISSUE TITLE
Live radio player has extra spacing

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#3607]
**Describe the bug**
The live radio player is contained within a 16:9 iframe which creates extra spacing around the player because it is not 16:9 media.

**To Reproduce**
Go to https://www.test.bbc.com/korean/bbc_korean_radio/liveradio and observe the extra space above the player.

<img width="1203" alt="Screenshot 2019-09-06 at 09 15 01" src="https://user-images.githubusercontent.com/4798332/64412238-e18fbf00-d086-11e9-9194-9c0a23311fb7.png">

**Expected behavior**
The live radio player should not have extra space above or below. The SMP player should allow no fixed aspect ratio so that the audio player can fill only the space needed.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
It seems this extra height is coming from a `<div>` before the SMP ,<iframe>` which has `padding-bottom: 56.25%` that is used to save the correct space for the classic SMP skin player. 

![image](https://user-images.githubusercontent.com/7791726/64420144-7ea62400-d096-11e9-9097-434e973373ca.png)
