### ISSUE TITLE
Conform Live Radio Lang Codes

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3609]
**Is your feature request related to a problem? Please describe.**
We've been using 2-charcter lang codes (eg, `om`) and 4-character lang codes (eg, `om-ET`) somewhat arbitrarily.

We've got the go-ahead from Benjamin and the the audience team to just convert everything to the 2-character code

The 4 character codes are still being used in these places:
 - ARES payloads
 - Morph SMP settings

**Describe the solution you'd like**
Use ISO 639-3 char codes for language - same as what are used in the service configs

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Should be able to see only the language in the ATI Tag Inspector

- [ ] This feature is expected to need manual testing.

**Additional context**
- https://bbcnews.slack.com/archives/CJT0284G2/p1567702242050300
- https://bbcnews.slack.com/archives/CJT0284G2/p1567703042056500
- https://bbcnews.slack.com/archives/CJT0284G2/p1567758051069200

**Comment by ryanmccombe** [comment]
Opened request with ARES on Slack

**Comment by LilyL0u** [comment]
The following lang codes are showing in ATI Tag Inspector and ARES payloads correctly for the five services going live:
Korean - ko
Indonesian - id
Tigrinya - ti
Amharic - am

The lang code for Afaan Oromoo is still showing as om-ET

![Image 25-09-2019 at 12 20](https://user-images.githubusercontent.com/54575620/65596479-da294a80-df8e-11e9-9a6f-61a886842ac9.jpg)

**Comment by ryanmccombe** [comment]
Asked ARES to resolve: https://bbcnews.slack.com/archives/C70C1RPGE/p1569409946008900?thread_ts=1569324209.007200&cid=C70C1RPGE

**Comment by LilyL0u** [comment]
Checked again now frame is fixed. 'Om' is now the lang code, which is correct. I also checked it in live. All good.
