### ISSUE TITLE
Test the Media block contains a play button and duration

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#3616]
**Cypress Testing Scenario**
This is testing the presence of the play button and duration on a media block.

**Testing steps to follow**
1. Given there is a media block on the page.
2. When the user hasn't interacted with it.
3. Then over the top of the placeholder image, it should include a play button for both video and audio.
4. And the duration should match the ARES data that has been received.

**Expected Outcome**
When a media block is loaded it should display a play button and duration information over the top of the placeholder image.

**Comment by jamesbrumpton** [comment]
This is now blocked pending the implementation of the Play/Duration button
