### ISSUE TITLE
ATI in-page analytics plugin is not detecting ATI tag information

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#3662]
**Describe the bug**
When you visit any Simorgh rendered page and use the ATI in-page analytics chrome [plugin](https://chrome.google.com/webstore/detail/at-internet-in-page-analy/hdnngccjdidjdfkdliiebkfocphicfkm), the plugin will produce an error stating that the ATI tag cannot be found. However ATI is receiving a hit as shown by their tag inspector [plugin](https://chrome.google.com/webstore/detail/at-internet-tag-inspector/epdfbeoiphkaeapcohmilhmpdeilgnok?hl=en).

**To Reproduce**

1. Install [ATI in-page analytics](https://chrome.google.com/webstore/detail/at-internet-in-page-analy/hdnngccjdidjdfkdliiebkfocphicfkm)
2. Go to this [article](https://www.bbc.co.uk/news/articles/ce9v85jlrzzo) or any other simorgh rendered page
3. Click on the ATI in-page analytics plugin in the top right

**Expected behavior**
The ATI in-page analytics plugin should display analytical information for the current simorgh rendered page.

**Screenshots**
<img width="604" alt="Screenshot 2019-09-06 at 16 59 07" src="https://user-images.githubusercontent.com/4706195/64525316-751bf680-d2f8-11e9-973d-50e8b3f3cd23.png">

**Comment by LilyL0u** [comment]
I also experienced this.
