### ISSUE TITLE
UX - Tab highlighting on the live radio player

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#3666]
**Is your feature request related to a problem? Please describe.**
Currently, when tabbing through the controls on the live radio player, only the play button and timeline mover are highlighted when they are in the current tab focus. The other controls do not show that they have been tabbed onto, which makes it unclear for the user where they currently are on the page when tabbing.

In this screenshot, the skip backward button is on tab focus but there is no visual indication of this:
![Image 09-09-2019 at 12 40](https://user-images.githubusercontent.com/54575620/64527928-1efe8180-d2ff-11e9-87df-6ee18171d2d7.jpg)

In this screenshot, the play button is on tab focus, and the user can see visually that this is the case:
![Image 09-09-2019 at 12 40](https://user-images.githubusercontent.com/54575620/64527921-1d34be00-d2ff-11e9-890a-9bed8473410a.jpg)

**Describe the solution you'd like**
We need a design for the highlighting of the player controls when they are on tab focus.

**Testing notes**
Given that the user tabs through the live radio player controls
Then they are able to tell what element they have on tab focus by the design of the highlight.

This should be tested for every player control.

- [x] This feature is expected to need manual testing.

**Comment by pjlee11** [comment]
This may have been fixed by https://github.com/bbc/morph-modules/pull/31998 TBC

**Comment by pjlee11** [comment]
URL for testing https://www.test.bbc.com/korean/bbc_korean_radio/liveradio

**Comment by pjlee11** [comment]
We need to confirm what styling should be on the elements when tabbing through

**Comment by pjlee11** [comment]
This is being explicitly turned off in the CSS of the player by `outline: 0`

![image](https://user-images.githubusercontent.com/7791726/65324628-afad4b00-dba4-11e9-9bd3-39d6478aa710.png)

**Comment by graeme-lindsay** [comment]
Awaiting a fix for SMP button state change on focus/,hover.

**Comment by aeroplanejane** [comment]
@gavinspence Do we know if SMP are going to implement a fix for this? e.g. button state change and do we have related JIRAs for the issues you raised with them? Thanks!

**Comment by gavinspence** [comment]
Old issue - closing
