### ISSUE TITLE
Review changes to the Simorgh runbook required for Live Radio Pages

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#3667]
**Is your feature request related to a problem? Please describe.**
Before we can go into production with the Live Radio Pages, we will need to update the runbook for 247. There are already pages for Simorgh, and we are expecting to just add and update the existing pages.

**Describe the solution you'd like**
This issue is an investigation task to identify the changes we are likely to need to make. We need to think about the touchpoints we have introduced during the development of the pages and if they impact the runbook.

e.g.
 * We have introduced the Live Ratio page type
 * We have introduced SMP for audio playback which relies on Mozart -> Morph -> Ares
 * We have introduced new AReS payloads for the static live radio assets

**Describe alternatives you've considered**
This is mandatory

**Testing notes**
[Tester to complete]

Dev insight: This is a manual technical documentation task, so will need to be reviewed - but there's unlikely to be any testing required.

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by Martin-Duffy** [comment]
**Simorgh run book** - CONFLUENCE/NEWSART/Simorgh+Run+Book

**WS front pages run book** - CONFLUENCE/WSFrontPGS/World+Service+front+pages+run+book

**AV embed URLs with diagram** - https://paper.dropbox.com/doc/AV-embed-URLs--AkgCfoPvpnbxnkaSW3~Bt9MOAg-4zRvKIjhS2VuwDxgn7f8o

**Comment by ryanmccombe** [comment]
https://paper.dropbox.com/doc/AV-Embed-Runbook-Proposal--AkvP2wZpBW6Si7fDBrpd~KW~Ag-b8G9WooWP1mP7Oocpvyyj

**Comment by Martin-Duffy** [comment]
We updated the following sections of the Simorgh Run book:

- Scope - https://confluence.dev.bbc.co.uk/display/NEWSART/Simorgh+Run+Book#SimorghRunBook-Scope
- Media embed architecture - https://confluence.dev.bbc.co.uk/display/NEWSART/Simorgh+Architecture 
- Volumetrics - https://confluence.dev.bbc.co.uk/display/NEWSART/Simorgh+Run+Book#SimorghRunBook-Volumetrics
- Corrective action - https://confluence.dev.bbc.co.uk/display/NEWSART/Simorgh+Run+Book#SimorghRunBook-CorrectiveAction

This was reviewed and no changes were required to our updates - https://jira.dev.bbc.co.uk/browse/RBREVIEW-2145

@ibMadbouly / @ryanmccombe - anything else to add here or are you happy to close this off now?

**Comment by ibMadbouly** [comment]
Happy to close off now , waiting @ryanmccombe to confirm

**Comment by ryanmccombe** [comment]
Thanks all - looks good to me 👍
