### ISSUE TITLE
UX - Add volume control to Live Radio Player

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#3672]
**Is your feature request related to a problem? Please describe.**
When the live radio player is viewed on desktop, the user should be able to control the volume with on screen controls. Our designs for the desktop page have a volume control:

![Image 09-09-2019 at 16 13](https://user-images.githubusercontent.com/54575620/64543614-6eec4100-d31d-11e9-9ea7-9106c7d9792c.jpg)

Currently the desktop page is missing the volume control:

![Image 09-09-2019 at 16 07](https://user-images.githubusercontent.com/54575620/64543582-6267e880-d31d-11e9-846a-6980cb3b529e.jpg)

**Describe the solution you'd like**
Add the volume control to the desktop page of the live radio player, as shown in designs.

**Testing notes**
Given the user is on the desktop page for the live radio player
And they have clicked the play button
Then the user can see and interact with the volume control

Could include a Cypress test for this?

On smaller devices (under 800px) the volumes automatically hide. 

- [x] This feature is expected to need manual testing.

**Additional context**
Ade has included the volume control in his adapted designs for the player on Zeplin

**Comment by jroebu14** [comment]
Changing this media query from

```css
@media (max-width: 799px)
.audioUI .p_volumeControls {
    display: none;
}
```

to

```css
@media only screen and (max-device-width: 799px)
.audioUI .p_volumeControls {
    display: none;
}
```

will show the volume slider on desktop (i.e. screens wider than 800px)

However this will happen

<img width="611" alt="Screenshot 2019-09-12 at 09 10 26" src="https://user-images.githubusercontent.com/4798332/64845012-0ba22d80-d601-11e9-9c04-85eb3f937525.png">

So looks like the fix should be to make the container width wider. A fix that can be done in Simorgh.

The way we can achieve this is by putting the player in a separate container to the heading and paragraph and setting a max-width of 800px. The drawback of this is that the player becomes wider than and unaligned with the heading and paragraph on desktop as shown below.

<img width="652" alt="Screenshot 2019-09-13 at 08 36 10" src="https://user-images.githubusercontent.com/4798332/64845394-f8439200-d601-11e9-89db-5dc19fbb6a8b.png">

A better solution would be to make the heading and paragraph have the same max-width as the player as shown below

<img width="622" alt="Screenshot 2019-09-13 at 08 37 25" src="https://user-images.githubusercontent.com/4798332/64845439-1a3d1480-d602-11e9-9d1c-a4cb1c5ce7ce.png">

**Comment by gavinspence** [comment]
@AdeAkintola @jmckee87 to advise

**Comment by jmckee87** [comment]
So, I would say we have to feature a volume button on desktop for accessibility reasons. It would def be worth feeding back to the SMP team about this situation but IMO we shouldn’t go live without the desktop volume, And to keep the page in line with the articles conventions, then we should keep the header/para and SMP in separate containers if that’s what needs to happen - this might mean things aren’t aligned but we’ll be consistent. (It’s also worth flagging that the articles designs are using 6 columns for headers and 5 for body copy / paras)
