### ISSUE TITLE
Investigate SMP audio player padding

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#3689]
**Is your feature request related to a problem? Please describe.**
Currently the live radio player on the page has a starting edge where the timeline is not aligned with the starting edge of the text:

![Image 10-09-2019 at 11 30](https://user-images.githubusercontent.com/54575620/64606605-7fa0c380-d3be-11e9-88ab-2ec2f0dbeec8.jpg)

The designs, however, show the beginning of the player timeline and the beginning of the text as aligned, which is more aesthetically pleasing.

![Image 10-09-2019 at 11 34](https://user-images.githubusercontent.com/54575620/64606777-f473fd80-d3be-11e9-8e3c-59864a64bdfe.jpg)

**Describe the solution you'd like**
Investigate with the SMP player has padding on its right and left sides, as this will have an effect on whether we can align the player with the text.

**Testing notes**
Visually check the alignment.
Given that the user is on the live radio player page
Then the beginning of the player timeline is aligned with the beginning of the text (title, description)

Could be a Cypress test also?

- [x] This feature is expected to need manual testing.

**Comment by pjlee11** [comment]
Looking at the embedded SMP instance might be easier to debug the padding on the player - https://www.test.bbc.com/ws/av-embeds/media/bbc_korean_radio/liveradio

**Comment by pjlee11** [comment]
UX to check on whether this padding is necessary and therefore this issue moot.
