### ISSUE TITLE
UX - Make the live radio player bigger to align with text on page (title, description)

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#3691]
**Is your feature request related to a problem? Please describe.**
After conducting the investigation in issue https://github.com/bbc/simorgh/issues/3689

Currently the live radio player on the page has a starting edge where the timeline is not aligned with the starting edge of the text (title, description):

![Image 10-09-2019 at 11 30](https://user-images.githubusercontent.com/54575620/64606605-7fa0c380-d3be-11e9-88ab-2ec2f0dbeec8.jpg)

The designs, however, show the beginning of the player timeline and the beginning of the text as aligned, which is more aesthetically pleasing.

![Image 10-09-2019 at 11 34](https://user-images.githubusercontent.com/54575620/64606777-f473fd80-d3be-11e9-8e3c-59864a64bdfe.jpg)

**Describe the solution you'd like**
If investigations lead to the answer that it is possible for us to change the alignment (there is no padding we cannot control) make the player bigger so it spans six columns and aligns with the text.

**Testing notes**
Visually check the alignment across different breakpoints.
Given that the user is on the live radio player page
Then the beginning of the player timeline is aligned with the beginning of the text (title, description)

Could be a Cypress test also?

- [x] This feature is expected to need manual testing.

**Comment by ryanmccombe** [comment]
I think we need to do this either way - even if we can't control the internal padding of SMP, we can make the whole thing wider so that it spans 6 columns

**Comment by jroebu14** [comment]
Did we not come to the conclusion that this one shouldn't be fixed because we think the padding is there to allow the scrubber and duration space when positioned at each end? Example shown below.

<img width="2032" alt="Screenshot 2019-09-12 at 08 44 48" src="https://user-images.githubusercontent.com/4798332/64764262-9cadd180-d539-11e9-9bf8-57aef857e0fa.png">

**Comment by pjlee11** [comment]
closing as we have agreed the additional padding is necessary on the player
