### ISSUE TITLE
Add cypress test for offscreen brand text

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#3705]
**Is your feature request related to a problem? Please describe.**
We currently don't have cypress tests for checking the brand has offscreen text. We should.
<img width="604" alt="Screenshot of Thai brand with offscreen text" src="https://user-images.githubusercontent.com/3028997/64691408-7e3ccd00-d48a-11e9-9407-e768199ecdce.png">

**Describe the solution you'd like**
- We should have a test for all page types. (So in `⁨cypress/integration/pages⁩/testsForAllPages.js`)
- The check should be:
if `serviceLocalizedName` exists in config, it should have 
```
<span class="VisuallyHiddenText-sc"><span lang="en-GB">{product}</span>{serviceLocalizedName}</span>
```
Otherwise:
```
<span class="VisuallyHiddenText-sc">{product}</span>
```

**Describe alternatives you've considered**
We could not add this cypress test, but it'd need to be always checked manually.

**Testing notes**
[Tester to complete]

Dev insight: This work should only add Cypress tests. 

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by j-pendlebury** [comment]
Closing in favour of https://github.com/bbc/simorgh/issues/3943
