### ISSUE TITLE
Make the CPS index optional in the MAP routing Regex

### ISSUE THREAD

**Issue by ibMadbouly** [bbc/simorgh#3712]
**Describe the bug**

The Media-Asset-Page routing is relying on a regex to match the MAP pages URLs, whats is implemented on Simorgh routing is to match this pattern EG:

`http://localhost:7080/{service}/{CPSIndex}{CPSId}.amp` and 
`assetUril` = `{CPSIndex}{CPSId}` , the current routing logic is matching the `assetUri` as the `CPSIndex` is required as the regex implies here: 

 [https://github.com/bbc/simorgh/blob/61a20af5b9522fc217213a30d40220c4e8b23595/src/app/routes/regex/index.js#L8](url)

**To Reproduce**
after getting Simorgh running locallly `npm run dev` 
1. Go to 'http://localhost:7080/{service}/49567825` | `.json` | `.amp`, you will get a `404` cause it is not a valid `assetUri` as the above regex implies.

**Expected behavior**
  -  the expected behavior to get the MAP page rendered in in the browser for all the cases

-  `http://localhost:7080/{service}/49567825`
-  `http://localhost:7080/{service}/49567825.amp`
-  `http://localhost:7080/{service}/49567825.json`

**Notes:**
 - unit tests should be added for this particular case  - as a valid route 

**Testing notes**
-  After the fix should be manually tested on like the examples here
` http://localhost:7080/{service}/49567825` -> canonical
`http://localhost:7080/{service}/49567825.amp` -> amp
`http://localhost:7080/{service}/49567825.json` -> json data 

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
3 links tested:
http://localhost:7080/ukchina/49375846.amp
http://localhost:7080/ukchina/49375846
http://localhost:7080/ukchina/49375846.json

All display.

![UNADJUSTEDNONRAW_thumb_23](https://user-images.githubusercontent.com/54575620/64866913-440f2f00-d634-11e9-9f21-698fd548a720.jpg)
![Image 13-09-2019 at 14 38](https://user-images.githubusercontent.com/54575620/64866925-47a2b600-d634-11e9-9954-13cc83e073dc.jpg)
![Image 13-09-2019 at 14 38](https://user-images.githubusercontent.com/54575620/64866931-4bced380-d634-11e9-83d7-9026b2224d2e.jpg)
