### ISSUE TITLE
Switch to using `data-e2e` attributes in cypress tests

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3714]
**Is your feature request related to a problem? Please describe.**
Were starting to use styled component class names in cypress like `StyledIndexAlsos`. IMO this is bad as someone could simply rename the component, without realising it breaks e2es and cause a lot of problems down the road. 

**Describe the solution you'd like**
Switch to using a data attribute `data-e2e` to serve the same purpose. This attribute is clear in purpose, and anyone changing it will have a clear understanding of what other changes will be needed.

This will need to be done in psammead and simorgh.

**Describe alternatives you've considered**
Leaving as it is, and continuing to use styled component classes

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
Interesting discussion [here](https://github.com/cypress-io/cypress/issues/1212) about this.

**Comment by j-pendlebury** [comment]
From Slack:

Since we destructure props in the Psammead component, we can’t pass in an attribute.

## Option 1)

Psammead component:
```
export const IndexAlsos = ({ children, dataE2e }) => (
    <div data-e2e={dataE2e}>
      {children}
    </div>
  );
```

Simorgh:
```
  return (
    <IndexAlsos dataE2e="index-alsos">{...}</IndexAlsos>
```

## Option 2)

Psammead component:
```
export const IndexAlsos = props => (
    <div {...props}>
      {props.children}
    </div>
  );
```

Simorgh:
```
  return (
    <IndexAlsos data-e2e="index-alsos">{...}</IndexAlsos>
```

## Option 3)

Psammead component:
```
export const IndexAlsos = props => (
    <div data-e2e="index-alsos">
      {children}
    </div>
  );
```

**Comment by DenisHdz** [comment]
## Option 4)

In Simorgh `IndexAlsosContainer`:

```
<div data-e2e="index-alsos">
    <IndexAlsos offScreenText={relatedContent}>
    ...
```
