### ISSUE TITLE
Cookie/Privacy banner translations for services

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#3722]
**Is your feature request related to a problem? Please describe.**
We have updated translations for these services:

Afaan Oromoo
Afrique
Amharic
Arabic
Azeri
Gahuza
Hausa
Igbo
Indonesian
Japanese
Korean
Pashto
Persian
Pidgin
Punjabi
Somali
Swahili
Thai
Tigrinya
Urdu
Vietnamese
Yoruba

We should update Simorgh so that it has all of the Cookie and Privacy banner translations. Note, these translations will be added together with those in https://github.com/bbc/simorgh/issues/3721, in the issues referenced below

**Describe the solution you'd like**
- Update the service configs at `src/app/lib/config/services/:service.js`
- Check the Simorgh pages load correctly: localhost urls are here: https://github.com/bbc/simorgh/wiki/Simorgh-Pages 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Before putting the PR through code review, the full cypress test suite should be run (all page types for all services) with `CYPRESS_SMOKE=false npm run test:e2e`

- [ ] This feature is expected to need manual testing.

**Additional context**
N/A

**Comment by ghost** [comment]
@sareh On the spreadsheet we have the `privacy` key and the translated content. We don't have it grouped like the `cookies` key where we have `uk` and `non-uk` which I guess maps to `international` and `uk` in our configs. How should I go about updating the privacy in our config? Should i just use the same content for `uk` and `international`
