### ISSUE TITLE
Provide an override for fetching data when service name does not match CPS site name

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#3740]
**Is your feature request related to a problem? Please describe.**
The `Cymrufyw` service used to be named `Newyddion`. When it changed to `Cymrufyw` the CPS site name was never updated. So our frontends have since had to provide a "friendly" name since.

When fetching data from https://www.test.bbc.com/cymrufyw.json for the `Cymrufyw` service we need to ensure we are requesting the `newyddion` from ares

**Describe the solution you'd like**
Provide an override option in Mozart, when we request data for `cymrufyw.` Mozart should hit ares with the old service name `newyddion`

**Describe alternatives you've considered**
Include the the above override option in Simorgh instead of mozart. Doing this adds extra complications to Simorgh. Our frontend should only know the service as `cymrufyw`

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
Refined, talk to mozart team prior to doing it

**Comment by hotinglok** [comment]
Merged a while ago, https://github.com/bbc/mozart-routing/pull/975
Closing now since this didn't automatically close
