### ISSUE TITLE
Application not hydrating correclty

### ISSUE THREAD

**Issue by ghost** [bbc/simorgh#3743]
**Describe the bug**
[Hindi](http://localhost.bbc.com:7080/hindi)  service does not show localised timestamp.

**To Reproduce**

1. Go to [Hindi](http://localhost.bbc.com:7080/hindi)
2. Look at the timestamps of the story promos - (Not Localised)
3. Open devtools

**Expected behavior**
Application should hydrate correctly to allow [Hindi](http://localhost.bbc.com:7080/hindi) to show localised timestamps.

**Screenshots**
<img width="1260" alt="Screenshot 2019-09-16 at 10 58 24" src="https://user-images.githubusercontent.com/48688870/64942137-f7646780-d870-11e9-8382-410085818544.png">

![Screenshot 2019-09-16 at 10 48 57](https://user-images.githubusercontent.com/48688870/64942072-d13ec780-d870-11e9-92b9-9d31a81df524.png)

**Desktop :**

- OS: MacOs Mojave: 10.14.6
- Browser : Chrome
- Version 76

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
This happens for most services atm. Its caused because https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/hindi.js doesn't include `import 'moment/locale/hi';` The hydration is fine 🎉

**Comment by ghost** [comment]
Yap. You are right. I didn't see that. Closing this.
