### ISSUE TITLE
[Mozart Routing] liveradio 404s have /news fallbacks in Mozart 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3811]
**Describe the bug**
The live radio pages do not have 404s matching the service (EG: /korean) in Mozart. 

**To Reproduce**

1. Go to https://www.test.bbc.com/korean/bbc_korean_radio/blah
2. See error - the page furniture is for `/news` rather than for `/korean`

**Expected behavior**
The 404 pages should be specific to Korean

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/65030104-de25ee80-d936-11e9-8515-cf9358008b4a.png)

**Testing notes**
Ensure that when visiting https://www.test.bbc.com/korean/bbc_korean_radio/blah the page furniture is correct for the service. 

- [x] This bug fix is expected to need manual testing.

**Additional context**
This will need to be addressed for all services offering live radio: korean, indonesia, tigrinya, amharic, afaanoromoo

**Comment by ryanmccombe** [comment]
Did some investigation on this - I'm not sure this is in scope for media pod, or Simorgh in general

We aren't routing `bbc_korean_radio/blah` - that is just falling through to Mozart's catch all:

https://github.com/bbc/mozart-routing/blob/62d53b986cf25d02fce14f2afb19efab810bfed2/src/lib/mozart_routing/routes/live_routes.rb#L581

`serve_error` uses the base payload by default: https://github.com/bbc/mozart-routing/blob/8ebe3a3e4cfefe83ae75f81480d48576ccc09c66/src/lib/mozart_routing/routes/base.rb#L68

Which hardcodes the error URL:
https://github.com/bbc/mozart-routing/blob/b5bcb6040b3bc6a59966b645e8fd86f8601d2939/src/lib/mozart_routing/payloads/simorgh.rb#L7

We could fix this, but seems out of scope for our team?  Sounds like core Mozart work

Interestingly, this bug doesn't happen in prod: https://www.bbc.com/korean/bbc_korean_radio/blah - not hitting Mozart I guess?

**Comment by karinathomasbbc** [comment]
Not going to fix
