### ISSUE TITLE
Error HOC doesnt ever catch handle errors

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3815]
**Is your feature request related to a problem? Please describe.**

We have a [`WithError` HOC](https://github.com/bbc/simorgh/blob/MpulsePageTypeService/src/app/containers/PageHandlers/withError/index.jsx) which shows an error page if `error` is truthy. Our issue is, thats basically never the case.

Error is set [here](https://github.com/bbc/simorgh/blob/MpulsePageTypeService/src/app/containers/App/App.jsx#L55-L69). If `route.getInitialData` throws an error, we catch it and set `error`. This is great, except our data fetching [already has a try catch inside it](https://github.com/bbc/simorgh/blob/MpulsePageTypeService/src/app/routes/getInitialData/utils/fetchData/index.js#L12-L29) meaning the error pretty much never propagates out.

This means all error pages caused by bad data get caught by the [withData](https://github.com/bbc/simorgh/blob/MpulsePageTypeService/src/app/containers/PageHandlers/withData/index.jsx#L51) HOC instead.

**Describe the solution you'd like**
Simply our error handling, and ideally expand it. We should only have 1 error page visual route.

**Describe alternatives you've considered**

**Testing notes**
This is mainly an investigation issue for now.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
We should investigate a prototype a solution to this. The ideal solution would be to use Reacts error boundaries which uses the `componentDidCatch` lifecycle method however this still does not work for SSR yet :(

An alternative might be to remove the try catch logic around the data fetching and allow the withError HOC to catch any errors.

Ideal for paring on.

**Comment by mykeels** [comment]
We could leave `fetchData` to handle its own error, and return the `error` object with `pageData` and `status`. 

```js
const fetchData = async ({ url, preprocessorRules }) => {
  try {
    ...
    return { pageData, status };
  } catch (error) {
   ...
    status = 502;
    return { pageData, status, error };
  }
};
```

That would give the context in `App.jsx`, access to the error thrown, allowing it to be re-thrown.

```js
const fetchData = async () => {
try {
  const {  status,  error, } = await route.getInitialData(...);

  if (error) {
    error.status = _status;
    throw error;
  }
} catch (error) {
      setState(prevState => ({
        ...prevState,
        error,
        status: error.status,
        loading: false,
      }));
   }
};
```

**Comment by mykeels** [comment]
I find that removing the try-catch logic in fetchData, makes the app fail on the server render.

**Comment by jroebu14** [comment]
I think this could work https://github.com/bbc/simorgh/pull/4161

`fetchData` has been made easier to reason about https://github.com/bbc/simorgh/pull/4161/files#diff-023e950aad140d55ee062f681d534050

and the catch has been removed from `App` https://github.com/bbc/simorgh/pull/4161/files#diff-075d3e454c8d5028eecfaf8c11b80de1

**Comment by mykeels** [comment]
Looks good @jroebu14 ... I noticed we lose our error at line 30 in `fetchData`. We could return it with:

```js
return { status: STATUS_CODE_BAD_GATEWAY, error };
```

So that it can be passed down to `withError`.

**Comment by jroebu14** [comment]
@mykeels good spot. We'd need to introduce state to return that error so maybe a mix of a promise and async could work well:

```js
const handleSuccess = (url, preprocessorRules) => async response => {
  const { status } = response;

  if (upstreamStatusCodesToPropagate.includes(status)) {
    return {
      status,
      ...(status === STATUS_CODE_OK && {
        pageData: preprocess(await response.json(), preprocessorRules),
      }),
    };
  }

  logger.warn(
    `Unexpected upstream response (HTTP status code ${status}) when requesting ${url}`,
  );

  return { status };
};

const handleError = error => {
  logger.error(error);

  return { error, status: STATUS_CODE_BAD_GATEWAY };
};

const fetchData = ({ url, preprocessorRules }) =>
  fetch(url)
    .then(handleSuccess(url, preprocessorRules))
    .catch(handleError);
```

**Comment by mykeels** [comment]
I'm not sure what you mean by "introduce state". I'd assumed:
```js
try {
  if (success) {
    return { ... }
  }
  return { status: STATUS_CODE_BAD_GATEWAY };
}
catch (error) {
   ...
    return { status: STATUS_CODE_BAD_GATEWAY, error };
}
```
would be enough
