### ISSUE TITLE
Update service configs to include locales.

### ISSUE THREAD

**Issue by ghost** [bbc/simorgh#3819]
**Is your feature request related to a problem? Please describe.**
We are not including the relevant `locales` in our config, this leads to some services displaying timestamps in english.

**Describe the solution you'd like**
Include relevant locales to their respective services. For some services we are overriding the default moment locales. For those services include locale from `psammead-locales`.
More details [here](https://bbc.github.io/psammead/?path=/info/utilities-psammead-locales--moment-arabic-ar)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by jamesbrumpton** [comment]
There are some discrepancies on the datestamps in comparison to what documentation has been made available.

*Mundo*
![image](https://user-images.githubusercontent.com/25743793/65682208-65b7df80-e052-11e9-8277-d71e1b0644a8.png)

The date shouldn’t include `de` In either instance.

*Brasil/Portuguese*
![image](https://user-images.githubusercontent.com/25743793/65682275-8a13bc00-e052-11e9-8262-af3b6321b75f.png)

The date on Brasil/Portuguese is capitalised on the page but on the spreadsheet it’s completely lowercase.

*Serbian*
There is no Cyrillic reference on the documentation and it's unclear whether the latin date should include a completely lowercase month or one that includes a capitalised beginner letter.

**Comment by jblaut** [comment]
@jamesbrumpton as far as I can tell these are correct
![image](https://user-images.githubusercontent.com/13763899/65683245-b3354c00-e054-11e9-8fb4-7008641fafe0.png)

Brasil timestamps are supposed to have the 'de' removed, Mundo doesn't mention it.

**Comment by j-pendlebury** [comment]
@jamesbrumpton are these the only timestamps that aren't correct?
