### ISSUE TITLE
Add Fixture Data for MAP v1

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3826]
**Is your feature request related to a problem? Please describe.**
Add local fixture data for all the payloads we have chosen for our v1 test implementation

**Describe the solution you'd like**
See payloads here: 
https://ares-broker.test.api.bbci.co.uk/api/asset/japanese/video-23248670
https://ares-broker.test.api.bbci.co.uk/api/asset/korean/media-23248686
https://ares-broker.test.api.bbci.co.uk/api/asset/pidgin/23248703
https://ares-broker.test.api.bbci.co.uk/api/asset/punjabi/media-23248705
https://ares-broker.test.api.bbci.co.uk/api/asset/sinhala/23248970
https://ares-broker.test.api.bbci.co.uk/api/asset/thai/thailand-23248713
https://ares-broker.test.api.bbci.co.uk/api/asset/uzbek/sport-23248721

Copy these into JSON files within Simorgh's data directory, so they are available for local development / storybook / testing

- Get ARES response from links above 
- Add to JSON files within the simorgh /data directory following the existing naming pattern

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: No tests needed - this is just JSON dev data

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
@ibMadbouly test map asset links from ARES added above from spreadsheet
