### ISSUE TITLE
STM->Mozart Routing for MAP v1

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3828]
**Is your feature request related to a problem? Please describe.**
We need to create a CHANGE ticket to implement STM routing for our media asset pages on **TEST**

Note, Mozart is currently not able to infer whether a resource is a MAP page, and, therefore, can't route MAP pages to Simorgh.

Mozart are investigating a solution for this

In the mean time, we've agreed to create some temporary routes with hardcoded, known IDs.

These routes are temporary, but will allow us to test our pages.

**Describe the solution you'd like**
Complete list of routes to send to Mozart:

```
https://test.bbc.com/japanese/video-23248670
https://test.bbc.com/korean/media-23248686
https://test.bbc.com/pidgin/23248703
https://test.bbc.com/punjabi/media-23248705
https://test.bbc.com/sinhala/23248970
https://test.bbc.com/uzbek/sport-23248721
https://test.bbc.com/thai/thailand-23248713
[All of the above, but with .amp at the end]
[All of the above, but with .json at the end]
https://test.bbc.com/(japanese|korean|pidgin|punjabi|sinhala|uzbek|thai)/manifest.json
https://test.bbc.com/(japanese|korean|pidgin|punjabi|sinhala|uzbek|thai)/sw.js
```

Note, for services that already are on test, the sw.js and manifest.json routes may already exist, and will not need modified.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: N/A

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
@pjlee11 to get advice as we might be trying to add too many specific routes here

**Comment by pjlee11** [comment]
Manifest and Service Worker is available on TEST for all 7 of our first services...

www.test.bbc.com/{{service}}/manifest.json and www.test.bbc.com/{{service}}/sw.js for each service:
  - korean :ok:
  - igbo :ok:
  - japanese :ok: 
  - pidgin :ok: 
  - pubjabi :ok:
  - sinhala :ok:
  - thai :ok:
  - uzbek :ok:

**Comment by pjlee11** [comment]
Confirmed with the livesite team on Slack that the first 7 services can be exactly routed for `page`, `amp` and `json` on the TEST TMs.

**Comment by pjlee11** [comment]
EG:
https://test.bbc.com/japanese/video-23248670
https://test.bbc.com/japanese/video-23248670.amp
https://test.bbc.com/japanese/video-23248670.json

**Comment by pjlee11** [comment]
OPS-224962
