### ISSUE TITLE
Spike - Investigate AV player against MAP requirements

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3829]
**Is your feature request related to a problem? Please describe.**
We need a developer to investigate the current implementation of the AV architecture against our requirements for media asset pages.

**Describe the solution you'd like**
Investigate the current AV solution, and document any problems / limitations that will impair our requirements.  This ticket should facilitate us identifying any updates required to any AV component.

**AV Components:**
- ARES Payloads
- Morph Module
- Mozart (Routing / Page Config)
- Psammead
- Simorgh

**MAP Basic Requirements:**
https://jira.dev.bbc.co.uk/secure/RapidBoard.jspa?rapidView=10930&quickFilter=53570

**MAP Improved Requirements:**
https://jira.dev.bbc.co.uk/secure/RapidBoard.jspa?rapidView=10930&quickFilter=53572

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Ticket is investigation only - no ticket required

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by graeme-lindsay** [comment]
@ibMadbouly when this was picked up, I asked you to provide an update to the rest of the pod on what your understanding of this investigation is. I am aware that this issue is not well-defined so I wanted to make sure you checked your understanding before proceeding. Have you done this?

**Comment by ibMadbouly** [comment]
@graemelindsayBBC this was picked up late last Thursday, I had a call with @ryanmccombe to uderstand more about listed AV components, and I got to the details of the shared links, and shared on the channel the findings with the pod here https://gist.github.com/ibMadbouly/1f9b73db142a319e324eb9eb9d16d3a2
