### ISSUE TITLE
Provide Simorgh version to mPulse

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#3843]
**Is your feature request related to a problem? Please describe.**
If we notice a problem in the mPulse data we want to be able to identify which Simorgh release introduced it.

In order to do this, we should make some identifier accessible to mPulse that would allow us to track down the offending PR.

**Describe the solution you'd like**
- Add a version identifier to the `window` (e.g. the version number set here https://github.com/bbc/simorgh-infrastructure/blob/73edeccb6f44febab7505e7120ca2a3bdf28d4de/scripts/release_github.sh#L22)

This can be done via the existing `window.SIMORGH_MPULSE_INFO` object set [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/MPulseBeacon/index.jsx#L32)
By adding a key of `simorghVersion: process.env.SIMORGH_VERSION` which is provided at build time

- Configure mPulse to use the version identifier as a custom dimension

**Describe alternatives you've considered**
None.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by samora** [comment]
Blocked pending changes to CI pipeline.

**Comment by amywalkerdev** [comment]
Closing mpulse issues as we are stopping our trial
