### ISSUE TITLE
application.js Cypress test failing on local

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3846]
**Describe the bug**
When running the Cypress tests on the local dev environment there are failing tests. 

**To Reproduce**

1. Go to `latest`
2. Run command `CYPRESS_APP_ENV=local CYPRESS_UK=true CYPRESS_SMOKE=false npm run build && npm run test:e2e`
3. See error

**Expected behavior**
No tests should fail when run locally running the Cypress tests with `CYPRESS_APP_ENV=local`

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/65140899-755a7700-da07-11e9-9896-aa816e572a64.png)

**Testing notes**

- ~[ ] This bug fix is expected to need manual testing.~

**Additional context**
Latest is on the commit `a0a520a552f55e41988bd5e0e43fb0462ba1aa67`

**Comment by oluoluoxenfree** [comment]
@pjlee11 Are you still able to replicate this? They pass for me running that command

**Comment by pjlee11** [comment]
Yep, when running `CYPRESS_APP_ENV=local CYPRESS_UK=true CYPRESS_SMOKE=false npm run build && npm run test:e2e` still failing 

![image](https://user-images.githubusercontent.com/7791726/65607978-5d559b00-dfa5-11e9-9386-705e2d42069f.png)

**Comment by oluoluoxenfree** [comment]
@pjlee11 Tried again today and @dr3 also ran it, both passing.
