### ISSUE TITLE
Use fonts on ws-downloads for all sites

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#3850]
**Is your feature request related to a problem? Please describe.**
Currently we're using Reith fonts hosted on `https://gel.files.bbci.co.uk`. We should use the fonts hosted on `https://ws-downloads.files.bbci.co.uk` instead. This is where all the other WS fonts in Simorgh are currently being served from.

This is a requirement from Engineering, but has been checked with the relevant Product Owner as well. 

**Describe the solution you'd like**
Update fonts in Psammead: Base URL: https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/fonts.js#L1 as well as the font file names: https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/fonts.js#L36 

They should follow the naming convention here:
https://ws-downloads.files.bbci.co.uk/fonts/index.html#ReithSansLatin
https://ws-downloads.files.bbci.co.uk/fonts/index.html#ReithSerifLatin

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
IMO we shouldnt do this, we should move all to `news.files.bbci.co.uk`. I dont see any advantage to moving them to ws-downloads as it still means we need to connect to 2 files domains (js and fonts) when we can just connect to one.

**Comment by sareh** [comment]
That's a fair point.  
That'd require moving all the fonts from https://github.com/bbc/news-fonts which is built on https://github.com/BBC-News/ws-downloads/ to be deployed up using Sling to a bucket behind `news.files.bbci.co.uk`. If we can use mPulse data to see it'd make a demonstrable impact in performance, we could make the change. It isn't a quick change, so would be good to check it'd make a difference.

The other impact of moving all fonts to `news.files.bbci.co.uk` would be the change in CDN provider. `ws-downloads` is currently using CloudFront. `news.files.bbci.co.uk` is using Akamai. I have messaged people to find out why CloudFront was explicitly used for the ws-downloads service. Will update this ticket when I have that info.

**Comment by joshcoventry** [comment]
We will move to the static.files domain soon so we will revisit then.
