### ISSUE TITLE
Cookie banner content UK version has missing translations 

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#3856]
**Describe the bug**
In the translations sheet there are two versions of the 'cookie banner content', one version is UK, one version is non-UK. When I set isUK to true to view the content locally, many of the UK version translations are missing:

Korean - missing translation for cookies description (it is in English)
Tigrinya - correct
Afaan Oromoo - missing translation for cookies description (it is in English)
Indonesian - missing translation for cookies description (it is in English)
Amharic - missing translation for cookies description (it is in English)

**To Reproduce**

1. Go to src/app/contexts/RequestContext/getOriginContext/index.js and in the code make sure isUK is == true.
2. Go to one of the URLs, e.g http://localhost:7080/indonesia/bbc_indonesian_radio/liveradio
3. Check the cookie banner content against the translations sheet

**Expected behavior**

**Screenshots**
![Image 18-09-2019 at 15 52](https://user-images.githubusercontent.com/54575620/65159708-69cd7700-da2c-11e9-9d41-c6036571acfd.jpg)

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome
- Version: 77.0.3865.75

**Testing notes**
Check the UK version is showing on the page and match to the translations in the translation sheet.
- [x] This bug fix is expected to need manual testing.

**Additional context**
It is possible it was assumed all services would just need the non-uk version as they are outside the uk. But it is actually about viewing them FROM the uk.

**Comment by ryanmccombe** [comment]
Translations available here: https://docs.google.com/spreadsheets/d/1IE6dvHfOJhYTIhC0kg8aRGnaj3fEg1NH9jQwo5NuUDQ/edit#gid=757630729

**Comment by aeroplanejane** [comment]
@ryanmccombe @LilyL0u is this related to https://github.com/bbc/simorgh/issues/3859 ?

**Comment by LilyL0u** [comment]
> @ryanmccombe @LilyL0u is this related to #3859 ?
@aeroplanejane 
#3859 stops us seeing the UK cookie banner, so we didn't notice the translations were missing at first! You can test it by changing isUK to true in the code. When the UK banners show in the UK it will be easier to test, but in the meantime it would be good to have the UK banner translations in.

**Comment by joshcoventry** [comment]
@LilyL0u Was this issue superseded by another issue? Is this issue still relevant?

**Comment by aeroplanejane** [comment]
I'm closing this as we have all of the translations in place for the services we require
