### ISSUE TITLE
Non-UK cookie banner translations are showing in the UK (here!)

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#3859]
**Describe the bug**
In the translations sheet there are two versions of the 'cookie banner content', one version is UK, one version is non-UK. We would expect to see the UK version here in the UK, however the non-uk versions are showing instead.

**To Reproduce**

1. Go to a service on test e.g https://www.test.bbc.com/korean/bbc_korean_radio/liveradio in the UK
2. Check the cookie banner content against the UK and non-UK translations
3. See error

**Expected behavior**
UK version should show in the UK. Non-uk version should not should in the UK, but should show outside the UK.

**Screenshots**
![Image 18-09-2019 at 16 01](https://user-images.githubusercontent.com/54575620/65160487-b6658200-da2d-11e9-8809-fae55e73e4a8.jpg)

**Additional context**
Afaan Oromoo will appear to be correct because it has the uk version translation in the non-uk version!

**Comment by ryanmccombe** [comment]
This is a simorgh-wide bug - we're currently inferring whether someone is in the UK based on whether they're using .co.uk or .com

This is implemented here: https://github.com/bbc/simorgh/blob/a8e15351cff5589c8e1af1b2533a66b78d190544/src/app/contexts/RequestContext/getOriginContext/index.js#L17

Test / Stage redirects to .com so we never see the UK version
In Live, all WS services are on .com, so they will never see the UK version either

Need better implementation of this

Added core pod label - cc @hindsc52

**Comment by dr3** [comment]
Related to https://github.com/bbc/simorgh/issues/3494

**Comment by hotinglok** [comment]
Blocked on #3494

**Comment by LilyL0u** [comment]
Apparently this is now fixed in the related issue: https://github.com/bbc/simorgh-infrastructure/issues/726

'Closing as done, countries are now coming through as expected'

Will check if it works

**Comment by LilyL0u** [comment]
The fix is done in the Mozart size, not the simorgh side and there’s a simorgh issue to integrate it somewhere. Will move back to blocked.

**Comment by LilyL0u** [comment]
Still being worked on in the issue https://github.com/bbc/simorgh/issues/4060, so still blocked.
