### ISSUE TITLE
Enable react router links in the header, nav, storypromo & footer

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3869]
Blocked on https://github.com/bbc/simorgh/issues/3868

**Is your feature request related to a problem? Please describe.**
Currently all non-article links are standard, non react router link.

**Describe the solution you'd like**
Extract the logic in https://github.com/bbc/simorgh/blob/latest/src/app/containers/InlineLink/index.jsx into a reusable helper, that can be used in other places.

This means, when the helper allows it, a link will "become" a react router link.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
For this I would expect we'd need to add a list of supported routes that can use the react router link and this would need to be per environment i.e. we may support internal linking to CPS assets but only on test.

We are also going to need to know the asset type, as we might support internal linking to STY's but not to MAP's
