### ISSUE TITLE
[Mozart Routing] Handle variants when requesting `.json` payload in Mozart

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3876]
**Is your feature request related to a problem? Please describe.**
We currently get our `.json` data from Ares via Mozart. 

https://www.bbc.com/igbo.json -> ARES/api/index/igbo/front_page

To enable variant `.json` data we need to remap the variant in our request URL to create the correct URL for ARES. 

Example: 
www.bbc.com/zhongwen/chinese-news-49631219/simp.json -> ARES/api/asset/zhongwen/simp/chinese-news-49631219

**Describe the solution you'd like**
Take the variant from the end of the `.json` route and place it in the correct part of the Ares request. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
`MOZART/{{service}}/{{assetURI}}/{{variant}}.json -> ARES/{{service}}/{{variant}}/{{assetURI}`

**Comment by chris-hinds** [comment]
Is this referring to CPS assets? If so simorgh only renders with the variant after the service and that is the URL passed to ARES for for fetching the asset data e.g. `/zhongwen/simp/chinese-news-49631219`

`www.bbc.com/zhongwen/chinese-news-49631219/simp` This isn't a valid URL

**Comment by chris-hinds** [comment]
This has been completed as a part of the Mozart routing refactor
