### ISSUE TITLE
componentWillMount warning from SideEffect(NullComponent)

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3893]
**Describe the bug**
in `npm run test:unit` we get the following warning. I belive this is similar BUT UNRELATED to `react-loadable`, which is covered by https://github.com/bbc/simorgh/issues/3087

**To Reproduce**

``` 
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

      * Move code with side effects to componentDidMount, and set initial state in the constructor.
      * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

      Please update the following components: SideEffect(NullComponent)
```

**Fix:**
If issue is in our code, fix it. If its in a dependancy, log the issue in their github and link to it here

**Expected behavior**
Warning doesnt happen

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
I believe this is from helmet

Related issues:
https://github.com/nfl/react-helmet/issues/465
https://github.com/nfl/react-helmet/issues/413

**Comment by FK78** [comment]
Blocked until [react-helmet](https://github.com/nfl/react-helmet) bumps `react-side-effect` to 2.0.0.

**Comment by j-pendlebury** [comment]
> Blocked until [react-helmet](https://github.com/nfl/react-helmet) bumps `react-side-effect` to 2.0.0.

Looks like that's been done https://github.com/nfl/react-helmet/blob/master/package.json#L38

**Comment by FK78** [comment]
> > Blocked until [react-helmet](https://github.com/nfl/react-helmet) bumps `react-side-effect` to 2.0.0.
> 
> Looks like that's been done https://github.com/nfl/react-helmet/blob/master/package.json#L38

Oh great, but currently seems to be in beta so we won't be able to unblock this issue for now.

**Comment by Roeefl** [comment]
++ Waiting for this patch to be available as well

**Comment by FK78** [comment]
> > > Blocked until [react-helmet](https://github.com/nfl/react-helmet) bumps `react-side-effect` to 2.0.0.
> > 
> > 
> > Looks like that's been done https://github.com/nfl/react-helmet/blob/master/package.json#L38
> 
> Oh great, but currently seems to be in beta so we won't be able to unblock this issue for now.

6.0.0 has been released.

**Comment by darrenkeen** [comment]
Anyone else still getting this issue with 6.0.0-beta?

**Comment by FK78** [comment]
> Anyone else still getting this issue with 6.0.0-beta?

We've manged to fix the warnings by using version 6.0.0, we did not test 6.0.0-beta.

**Comment by rinturj84** [comment]
Still getting the Warning in 6.0.0.

**Comment by darrenkeen** [comment]
Yes me too, still in `6.0.0`

**Comment by MickaelNeves** [comment]
fixed in ^6.1.0

**Comment by RyanRutkin** [comment]
I'm still getting this error in ^6.1.0

**Comment by zachintosh** [comment]
Also seeing this error in 6.1.0

**Comment by bobziroll** [comment]
Same here. Just updated from 5.2.1 to 6.1.0 and getting the same warning.

**Comment by miquelvir** [comment]
Same here. Seeing the warning in "react-helmet": "^6.1.0".

```
Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: SideEffect(NullComponent)
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
push../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11506
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23822
commitRootImpl @ react-dom.development.js:23005
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ index.js:9
./src/index.js @ index.js:35
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ theme.js:31
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1

```

**Comment by satyamskillz** [comment]
I am still getting the same error, so I am uninstalling this useless package. Total waste of time!!

**Comment by ananddoesembed** [comment]
Issue persists. is this problem going to get fixed?

**Comment by samuelbukoye** [comment]
im still getting this issue in version ^6.1.0"

**Comment by Darkthunder119** [comment]
Still have the issues. I have decided to use `react-helmet-async` instead. Does a much better job and does not use SideEffect

**Comment by hector97i** [comment]
@Darkthunder119 
> Still have the issues. I have decided to use `react-helmet-async` instead. Does a much better job and does not use SideEffect

How did that go for you?

**Comment by Pilzington** [comment]
> @Darkthunder119
> 
> > Still have the issues. I have decided to use `react-helmet-async` instead. Does a much better job and does not use SideEffect
> 
> How did that go for you?

Switching to `react-helmet-async` worked for us.
