### ISSUE TITLE
Update the title tags for Azeri, Kyrgyz and Japanese

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#3925]
**Is your feature request related to a problem? Please describe.**
Please update the title tags for the following services:
Azeri: "Xəbərlər, Qaynar Xəbərlər, Analiz, Video | BBC Azərbaycanca - BBC News"
Japanese: "最新ニュース | BBCニュース"
Kyrgyz: "Кабарлар, акыркы мүнөттөгү кабарлар, талдоо, видео | Би-Би-Си Кыргыз Кызматы - BBC News"

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ghost** [comment]
The title includes the `brandName` of the service. For `Kyrgyz` the `brandName` is `BBC News Кыргыз КызMATы` and with the update given it will result in 
`Кабарлар, акыркы мүнөттөгү кабарлар, талдоо, видео - BBC News Кыргыз КызMATы` 
not 
`Кабарлар, акыркы мүнөттөгү кабарлар, талдоо, видео | Би-Би-Си Кыргыз Кызматы - BBC News` as shown in the issue description.

Does that mean we have to update the service `brandName` from  `BBC News Кыргыз КызMATы` to `Би-Би-Си Кыргыз Кызматы - BBC News`
