### ISSUE TITLE
Use `useful links` link promo in Simorgh

### ISSUE THREAD

**Issue by Bopchy** [bbc/simorgh#3927]
**Is your feature request related to a problem? Please describe.**
Use `useful link` link promo created in https://github.com/bbc/psammead/issues/2222 in Simorgh, and add it to the whitelist.

```
{
"name": "Guide promo",
"indexImage": {
"id": "63692548",
"subType": "index",
"href": "http://b.files.bbci.co.uk/14A31/test/_63692548_000327537-1.jpg",
"path": "/cpsdevpb/14A31/test/_63692548_000327537-1.jpg",
"height": 549,
"width": 976,
"altText": "A lone Koala perches in a eucalyptus tree",
"caption": "Koalas are from Australia",
"copyrightHolder": "BBC"
},
"uri": "http://www.bbc.com/azeri",
"contentType": "Guide",
"assetTypeCode": "PRO",
"timestamp": 1569321103000,
"type": "link"
},
```

**Describe the solution you'd like**
Using the useful links promo in Simorgh. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: This will require unit and Cypress tests

- [ ] This feature is expected to need manual testing.

**Additional context**
See WSFRONTPGS-226 for details on the expected contentType.

**Comment by j-pendlebury** [comment]
Blocked on work pending in https://github.com/bbc/psammead/issues/2222, which will need acceptance criteria for a11y testing

**Comment by OlgaLyubin** [comment]
Unblocked on https://github.com/bbc/psammead/pull/2236 being merged
