### ISSUE TITLE
MAP - Headline Transformer

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3930]
**Is your feature request related to a problem? Please describe.**
The response we get from ARES needs to be transformed into something we can render.  This ticket is for the headlines

**Describe the solution you'd like**
Collect scenarios of what is possible within the CPS headlines.  Write a function that standardises them to an output that we can render

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Test automation is sufficient - this ticket will have no user-facing effect

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by graeme-lindsay** [comment]
Replaced with #4088
