### ISSUE TITLE
Create MAP Skeleton Page

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3940]
**Is your feature request related to a problem? Please describe.**
We need a skeleton page to place our MAP content

**Describe the solution you'd like**
We are currently re-using the "MediaPage" for our MAP routes.  We need this to be a different page such that, when we create new components for it, we can add those components to this page, and build it out over time.

The skeleton page can just have some placeholder content for now

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Automated tests were already created as part of the initial routing work - update them if required.

- [ ] This feature is expected to need manual testing.

**Additional context**
N/A

**Comment by pjlee11** [comment]
It's probably worth waiting till after https://github.com/bbc/simorgh/pull/3982 is merged before this issue is picked up for dev

**Comment by pjlee11** [comment]
I would also suggest we name the new component as `CpsAssetPage` rather than `MediaAssetPage` as it is likely we can make use of the page container in other asset types in the future
