### ISSUE TITLE
Write tests for `shouldRender/index.js`

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#3942]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/simorgh/pull/3773 `shouldRender` is now its own file, however it pretty much didnt have any tests originally.

**Describe the solution you'd like**
Write full unit tests for this function, on top of the passport tests that exist following #3773

**Describe alternatives you've considered**
Not doing this, retiring to a beach in the south of france selling sea shells by the sea shore

**Testing notes**
Doesn't require any testing effort.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by mykeels** [comment]
See [commit](https://github.com/bbc/simorgh/commit/7dcbc9b9de0f22f1d799a28a3462e01dd2632d53) above, that references this issue, and [existing tests](https://github.com/bbc/simorgh/blob/latest/src/app/containers/PageHandlers/withData/shouldRender/index.test.js) for `shouldRender`. 

Are we sure this hasn't been resolved?

**Comment by samora** [comment]
Closing this issue since it's no longer valid.
