### ISSUE TITLE
Fix BBC-a11y issue with iframes

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3946]
This issue is blocking us going live:

https://github.com/bbc/bbc-a11y/issues/298

**Comment by ryanmccombe** [comment]
Jonathan said he's not working on this, so we need to pick it up ourselves

**Comment by ryanmccombe** [comment]
This is not blocking us, as bbc-a11y only runs against an article page

**Comment by gavinspence** [comment]
Closing issue as it's out of date.
