### ISSUE TITLE
Improve Tabbing Behavior in Firefox

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3948]
**Describe the bug**
The tabbing behavior around the embedded media player doesn't provide a great UX in Firefox

**To Reproduce**
In Chrome, the existance of the iframes is pretty much invisible.

In Firefox, when a user tabs into the Iframe, they focus on the iframe itself.  The next tab focuses on the inner iframe.

**Expected behavior**
Investigate if the FF user experience can be improved to something like Chrome's

**Screenshots**

**Comment by ibMadbouly** [comment]
Chrome tabbing order: 
it focuses on the player play button ( turns red )  
![chrome_tab_order](https://user-images.githubusercontent.com/47124571/66193071-1a28b580-e692-11e9-8749-6268bce73b6b.gif)

**Comment by ibMadbouly** [comment]
on FF (nightly build to test key board access)
focuses on: 
 

- iframe 
-  playbutton
-  live_Icon

![22](https://user-images.githubusercontent.com/47124571/66194976-f4051480-e695-11e9-8611-9ee98028a0d3.gif)

**Comment by ibMadbouly** [comment]
Closing this, cause Jim Lee, Fixed the video Elements and investigating the Iframes
