### ISSUE TITLE
Audio player has 16x9 placeholder on amp for liveradio page 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#3969]
**Describe the bug**
The liveradio page uses the audio SMP skin but it seem the mediaPlayer placeholder that is being used on amp is 16x9 and therefore a different ratio to the audio skin player. 

**To Reproduce**

1. Go to https://www.test.bbc.com/korean/bbc_korean_radio/liveradio.amp
2. See error as placeholder loads and then disappears 

**Expected behavior**
The audio player should not load in with a 16x9 placeholder (grey square in screenshot/GIF).

**Screenshots**
![AV AMP placeholder 16x9](https://user-images.githubusercontent.com/7791726/65609309-78c1a580-dfa7-11e9-91c2-ab4a88b290b3.gif)

![image](https://user-images.githubusercontent.com/7791726/65609501-c8a06c80-dfa7-11e9-8519-5ade6f6a73e7.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by pharingee** [comment]
Closing as fixed.
