### ISSUE TITLE
Add Local Lighthouse Tests for Live Radio and MAP

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#3971]
**Is your feature request related to a problem? Please describe.**
Update the simorgh `lighthouse` script to also run against Live Radio and MAP pages
**Note:** this should probably wait until Mozart deploy the x-frame header options, so LH can include the embed endpoint

**Describe the solution you'd like**
Update the Simorgh repo's lighthouse infrastructure to run tests against local live radio pages. EG: add another line per page type to [this script](https://github.com/bbc/simorgh/blob/latest/scripts/lighthouseRun.sh#L4).

We may need to change the [budget](https://github.com/bbc/simorgh/blob/latest/scripts/lighthouseBudget.js#L71-L75) so that it is different per page type.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: No testing needed

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by graeme-lindsay** [comment]
@ryanmccombe Can you post the link to the Lighthouse page. Maybe this issue gets replaced with a performance review/swarm

**Comment by ryanmccombe** [comment]
Following discussion in senior conf, we're probably going to remove all the local lighthouse stuff for the other pages.  Live radio and MAPs are already there!
