### ISSUE TITLE
chartbeat virtual update happens twice when using back button

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#3977]
**Describe the bug**
Our current implementation for getting the previous path works fine when navigating between pages, however when using the back button, chartbeat virtual update happens twice for canonical pages which results in discrepancies between pings. We recently isolated this behavior on latest by removing the `previousPath` value from the canonical config and setting a constant value [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js#L98). 

We need to fix this to get chartbeat working properly.

**To Reproduce**

1. Change the value of the `virtulReferrer` in the [config](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js#L98) to make use of `previousPath`
2. go to http://localhost:7080/news/articles/c0g992jmmkko
3. click the inline link to go to http://localhost:7080/news/articles/c6v11qzyv8po (this works fine)
4. click the back button to go to http://localhost:7080/news/articles/c0g992jmmkko, see that the virtual update function [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/canonical/index.jsx#L13) is called twice

**Expected behavior**
virtual updates should happen just once on each page load

**Comment by jroebu14** [comment]
Blocked by https://github.com/bbc/simorgh/issues/4573

**Comment by PriyaKR** [comment]
@rhenshaw56 can i have some clarification on this issue please?What do you mean by virtual update happens twice?Are you referring to the ping response seen in the network tab happening twice when clicked on an inline link?

**Comment by rhenshaw56** [comment]
>Are you referring to the ping response seen in the network tab happening twice when clicked on an inline link?

@PriyaKR not really, seeing multiple pings is fine as long as the`t` param is consistent in alll pings for each page. the virtual update happening twice just means that [this function](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/canonical/index.jsx#L13) doesn't run twice when clicking the inline link

**Comment by PriyaKR** [comment]
This is now unblocked and looks good tested as a part of this PR https://github.com/bbc/simorgh/pull/4793
