### ISSUE TITLE
Layout bug on Edge v44

### ISSUE THREAD

**Issue by clareevansbbc** [bbc/simorgh#3988]
**Describe the bug**
Layout bug on Microsoft Edge 44.17763.1.0

![image (13)](https://user-images.githubusercontent.com/45389716/65706362-3c16ac80-e082-11e9-8b69-856c9f71d9f3.png)

Raised by Vlad and Jordi - seen on a Windows laptop. 
It was Kyrgyz on stage. 

Please see if you can reproduce and if so resolve. If you can't reproduce, please contact Vlad and Jordi for more information. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by Bopchy** [comment]
I could not replicate this issue, and it appears to have disappeared for now. An issue will be raised if this reoccurs.
