### ISSUE TITLE
Heading - anchoring of SubHeading

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#399]
**Is your feature request related to a problem? Please describe.**
We should anchor to the Subheading.

**Describe the solution you'd like**
We should use the following markup

```
<h2 id="[TEXT]" tabindex="-1">[TEXT]</h2>
```

**Comment by greenc05** [comment]
Just adding a blocked label until I've finished investigating this with regards to accessibility

**Comment by jtart** [comment]
@greenc05 is there an update on the a11y investigation?

**Comment by greenc05** [comment]
There sure is @jtart 

Subheadings need to have:

- An id

- Tabindex value of -1

For example:

```
<a href=”https://www.bbc.co.uk/news/article/my-article#example-6”>My anchor link</a>
<h2 id="example-6" tabindex="-1">
```

**Comment by greenc05** [comment]
@jtart can you please explain what 'We should wrap apply a subheading in a hyperlink that has a name of the subheading text.' means please?

**Comment by jtart** [comment]
@greenc05 have removed that comment in favour of the approached described.
