### ISSUE TITLE
Validator should check for type array

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#404]
**Is your feature request related to a problem? Please describe.**
Currently the validator uses the `typeof` operator to check a node's type. This is problematic for array's as their type is actually an `object` (https://stackoverflow.com/questions/12996871/why-does-typeof-array-with-objects-return-object-and-not-array)

**Describe the solution you'd like**
Implement logic that uses `isArray` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) if the schema specifies a type of `array`

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by pjlee11** [comment]
Adding `alpha-2` label and picking up this work as the Apps team are looking to use the validator in production ready code and this is a quick win to improve the `schema.yaml`

**Comment by bcmn** [comment]
No longer blocked as #1006 has been resolved.
