### ISSUE TITLE
Live radio page fails AMP validation

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4044]
**Describe the bug**
AMP validation is failing meaning the AMP pages will not be indexed by Google. 

**To Reproduce**

1. Go to https://www.bbc.com/korean/bbc_korean_radio/liveradio.amp
2. Validate using the [AMP validator extension](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc)
3. See error (as in screenshot)

**Expected behavior**
Fix the errors described in the screenshot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/65891404-5a3f1e00-e39c-11e9-9299-f14b5df90f56.png)

**Testing notes**
Using the extension detailed above ensure no errors are present on the PR. 

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
![audio-player-placeholder](https://user-images.githubusercontent.com/7791726/65897696-c4a98b80-e3a7-11e9-9b71-358e6a2fc5dc.png)

**Comment by pjlee11** [comment]
`allowFullScreen` in `amp-iframe` set to true is due to React making HTML attributes a boolean explicitly when passed in. https://github.com/bbc/psammead/blob/051d2e1213436683a13acbb05235bbbfa66300c8/packages/components/psammead-media-player/src/Amp/index.jsx#L24

**Comment by pjlee11** [comment]
https://github.com/bbc/simorgh/pull/4048 is a temporary placeholder image that I created. We should request an image from UX that is 800px x 165px and similar to https://github.com/bbc/simorgh/issues/4044#issuecomment-536640187. If we remove `live` from the right hand side we should also be able to reuse this placeholder for on-demand content in the future.

**Comment by ibMadbouly** [comment]
@pjlee11 thinking to pass the value of the `allowfullscreen` attribute as a prop to `AmpMediaPlayer` component to set it the same way the `src`  and `placeholderSrc` were set to be in psammead like 
```jsx
const AmpMediaPlayer = ({ src, placeholderSrc , allowfullscreen }) => {
  return (
    <>
      <AmpHead />
      <amp-iframe
        sandbox="allow-scripts allow-same-origin"
        layout="fill"
        frameborder="0"
        src={src}
        allowfullscreen = {allowfullscreen}
      >
        <amp-img layout="fill" src={placeholderSrc} placeholder />
      </amp-iframe>
    </>
  );
};
```
and in simorgh should be passed along with the two other props like : 
```jsx
<AmpMediaPlayer src={embedSource} placeholderSrc={placeholderSrc} allowfullscreen= {value} />
```
