### ISSUE TITLE
Write Cypress tests for the updated Front Page Top Story component

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4056]
**Is your feature request related to a problem? Please describe.**
Once the updated Front Page Top Story component design has been merged, we must write Cypress tests for the Desktop variant. An annotated image of the redesign has been added below. 

We should check that the following is tested...

**Section No.1**
- Headline
- Summary
- Image
- Time/Datestamp

**Section No.2**
- Headline
- No Summary
- Image
- Time/Datestamp

**Section No.3**
- Headline
- No Summary
- No Image
- Time/Datestamp

**Describe the solution you'd like**
We need to implement Cypress tests that test for the presence of the components on the screen. Any granular testing such as styling, etc. should be done within the unit tests.

**Testing notes**
Making sure that the e2es pass on local, test & live.

![image](https://user-images.githubusercontent.com/25743793/65967766-13176280-e45a-11e9-8056-1f6e984ce68c.png)

This is currently blocked on this milestone - https://github.com/bbc/psammead/milestone/5
Once this has been finished the designs will then need to be implemented into Simorgh, which is when we can begin to write the Cypress tests.

**Comment by sareh** [comment]
As a result of discussion with @PriyaKR 
 - we will have storybook examples for slice with 1, 5, 9, 13 for the first slice and 2, 6, 10 for other slices. (https://github.com/bbc/simorgh/pull/5139)
- There will be unit tests covering all possible input values and layouts, so this does not need to be replicated at the cypress integration level. (https://github.com/bbc/simorgh/pull/5139)
- Then Cypress tests can just cover the existance of at least one promo within a slice, with the image/headline/timestamp.
