### ISSUE TITLE
Afrique timestamp bug

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4069]
**Describe the bug**
The timestamp on Afrique changes to english when the client app renders.

**To Reproduce**

1. Go to www.test.bbc.com/afrique
2. See error

**Expected behavior**
The timestamp should be in french and not change to english when the client app renders.

**Screenshots**
![afrique-timestamp-bug](https://user-images.githubusercontent.com/7791726/66033955-38f74280-e500-11e9-8864-5fa0bbe560ff.gif)
**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by j-pendlebury** [comment]
the moment locale is not being imported. `import 'moment/locale/fr';` needs to be added to Afrique config
