### ISSUE TITLE
Use relative instead of absolute units

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#407]
**Is your feature request related to a problem? Please describe.**
Currently we are using pixels for spacing, rather than using `em`s, which scale relative to the page's base font-size. 

**Describe the solution you'd like**
To update the spacing units in the file `src/app/lib/constants/styles.js` to use `em` (or `rem`s).
```
export const GEL_SPACING = 0.5em; // 8px
export const GEL_SPACING_DBL = 1em; // 16px
```

# Spike: REMs vs EMs for spacing
EMs and REMs is are both flexible / rezisable. This spike compares their use as units for spacing. 

Visual comparison: 
https://www.dropbox.com/sh/piitkh24wimzjkk/AACFxrbSno8sLMykPZaabx-Ua?dl=0

## REMs
The REM unit represents a size relative to the root element (e.g., the `font-size` of `<html>`). Combined with the root element's font-size, a REM represents the root element's initial value. 

### Advantages
Spacing will be global across Simorgh

Ease of understanding: When we create a constant expressed in REMs (e.g. `export const GEL_SPACING = '0.5rem'`) that value, or values based of of that value, stay constant, which adds simplicity from a developer perspective.

```
// assumes the root font size is 16px, which is a common browser default

export const GEL_SPACING = '0.5rem'; // 8px
export const GEL_SPACING_DBL = GEL_SPACING * 2; // 16px 
export const GEL_SPACING_QUAD = GEL_SPACING * 4; // 32px
```

REMs offer the (seeming) easiest transition from our current code base's use of pixels for padding.

### Disadvantages
REMs are not supported in IE8: https://caniuse.com/#search=REMs, but they are used on our production sites. IE8 is not a supported browser.Spacing doesn't appear to break in IE8 when REMs are used: 

Pixels for padding:
![latest-px-win7-ie8](https://user-images.githubusercontent.com/916416/43953551-46638fea-9c91-11e8-851a-ef74c2cee458.PNG)

REMs for padding
![rems-win7-ie8](https://user-images.githubusercontent.com/916416/43953553-46899366-9c91-11e8-8335-a0c833a4c5c9.PNG)

<hr/>

## EMs
"Represents the calculated font-size of the element. If used on the font-size property itself, it represents the inherited font-size of the element."(MDN)

### Advantages
Allows for more modularity of components, because spacing will be relative to local font size. 

### Disadvantages
Potential complexity of understanding due to nesting components, depending on how font size is implemented. It's harder to immediately understand what the current font size is that the EM is relative to: 
```
    <style>
        .parent {
            font-size: 16px;
        }

        h1 {
            font-size: 2em;
        }

        .child {
            font-size: 0.75em; /* 12px */
            padding-bottom: 1em; /* 12px - confusing! because it's relative to the current font-size, 
            0.5em, which is 12px. */
        }

    </style>

    <div class="parent">
        <h1>I am a heading and I should be 32px</h1>
        <div class="child">
            I am the child and I should be 12px
        </div>
    </div>

```

## a11y
* REMs and EMs are resisable. Both are established for use in production.
* Regardless of the unit chosen, we must set a default font-size in a resisable unit, i.e., `font-size: 100%` on the `html` element; supported user agents will allow text resizing (which will have a knock-on effect for padding/margin resizing). Setting a default font size in a resisable unit partially satisfies http://www.bbc.co.uk/guidelines/futuremedia/accessibility/html/resize-zoom.shtml; there isn't a standard per se for padding and margins.

## Further reading: 
<ul>
    <li>https://developer.mozilla.org/en-US/docs/Web/CSS/length</li>
    <li>https://engageinteractive.co.uk/blog/em-vs-rem-vs-px</li>
    <li>https://zellwk.com/blog/rem-vs-em/</li>
</ul>

**Comment by greenc05** [comment]
Can we please check, if we haven't, that there is no difference between using em or rem, if you page zoom in our supported browsers and that it works ok? And maybe also increasing the default font size in the browser - not sure if that setting also increases spacing or just the font… May also be worth a quick look at with ZoomText/IE?

**Comment by radiocontrolled** [comment]
Yes. Increasing default font size and/or zooming in will alter spacing in supported browsers because spacing becomes a function of the font size, whatever that font size is. The difference between the two is what the unit is relative to: the document as a whole (REMs) or the component/local font size (EMs). UX and AT testing for this should happen at the swarm level when the application matches the visual design enough to see how the flow of content behaves in context with other styled elements such as text.
