### ISSUE TITLE
Moment locale import missing from several service configs

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#4075]
Extends https://github.com/bbc/simorgh/issues/4069

**Is your feature request related to a problem? Please describe.**
Add moment import, i.e. `import 'moment/locale/[LOCALE]';` to any config files that do not have it set.

**Describe the solution you'd like**
Have moment import for each service.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Comment by 12** [comment]
This will clash with #4004.
