### ISSUE TITLE
Add Headline to MAPs

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4088]
**Is your feature request related to a problem? Please describe.**
MAP pages should have a headline using the psammead-headings component. 

**Describe the solution you'd like**
Use the headline value from the `promo.headlines.headline` in the data feed to create an Optimo format headline and render using the Blocks container logic. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshot testing and E2Es are required to ensure a headline is rendered on the page.

- ~[ ] This feature is expected to need manual testing.~

**Additional context**

**Comment by aeroplanejane** [comment]
Links to WSMEDIA-54 #2 https://confluence.dev.bbc.co.uk/display/WSMEDIA/MAP+%7C+Page
