### ISSUE TITLE
Enable ARES timestamp value on MAP pages

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4092]
**Is your feature request related to a problem? Please describe.**
We need to ensure that timestamps on CPS MAP pages are configured to use the new timestamp value where it exists on newly published CPS MAP pages. 

This will follow the same logic as existing CPS MAP and STY assets whereby we display the last published time from CPS. This time will change when there is a news update or major rewrite in CPS, but not when minor changes are made. 

Only newly published MAPs after ares v1.1.4 will have the timestamp value, so we need to factor in older assets that won't have this value because Ares has already cached these endpoints. 
We also need to factor in older TC2 MAP pages that won't have this value either. 

In order to enable the timestamp value we need to republish the MAP or update it with the admin tool: the Ares admin tool https://ares-admin-tool.api.bbci.co.uk/

**Describe the solution you'd like**
Where the timestamp value exists on a MAP page use that as the last updated value. 
Where the value 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshot testing and E2Es are required to ensure a headline is rendered on the page.

- [x] This feature is expected to need manual testing.

**Additional context**

CPS allows you to publish changes as minor changes, news updates or major rewrite. 
- Minor changes will not change the timestamp.
- News updates will change the update time on the timestamp 
- Major rewrites will create a new asset within CPS. When the new asset is published the published date will be displayed from the time that asset was published. 

This is the timestamp on a MAP we are referring to: 
![Screenshot 2019-11-26 at 11 39 30](https://user-images.githubusercontent.com/22519682/69642023-0d548c80-1059-11ea-854b-e69c9f1d2feb.png)

**Scenario 1: MAP has been published for the first time**
MAP with no changes: https://www.test.bbc.com/pidgin/media-23256554 

How long ago was it published | Example of what we display
-- | --
< 2 mins ago | 1 minute ago
2 mins ago - 1 hour ago | 42 minutes ago
1 hour ago - 2 hours ago | 1 hour ago
2 hours ago - 10 hours ago | 4 hours ago
More than 10 hours ago, but still today | 9 April 2018, 11:59 BST(or relevant timezone to service)
2 hours ago - 24 hours ago | N/A
More than 10 hours ago, and not today | 9 April 2018(using, but not displaying, relevant timezone)
More than 24 hours ago | N/A

**Scenario 2: MAP has been published with minor changes**
MAP updated with minor changes: https://www.test.bbc.com/pidgin/media-23256554

How long ago was it published | Example of what we display
-- | --
< 2 mins ago | 1 minute ago
2 mins ago - 1 hour ago | 42 minutes ago
1 hour ago - 2 hours ago | 1 hour ago
2 hours ago - 10 hours ago | 4 hours ago
More than 10 hours ago, but still today | 9 April 2018, 11:59 BST(or relevant timezone to service)
2 hours ago - 24 hours ago | N/A
More than 10 hours ago, and not today | 9 April 2018(using, but not displaying, relevant timezone)
More than 24 hours ago | N/A

**Scenario 3: MAP has been published and has had 'News Updates' or major changes**
MAP with news update: https://www.test.bbc.com/pidgin/media-23256550

< 2 mins ago | 9 April 2018, 11:59 BST*Updated 1 minute ago
-- | --
2 mins ago - 1 hour ago | 9 April 2018, 11:59 BST - Updated M minutes ago
1 hour ago - 2 hours ago | 9 April 2018, 11:59 BST - Updated 1 hour ago
2 hours ago - 10 hours ago | 9 April 2018, 11:59 BST - Updated H hours ago
More than 10 hours ago | 9 April 2018, 11:59 BST - Updated HH:MM XXT

**Scenario 4: MAP published yesterday or earlier and has had news updates**
MAP with news update: https://www.test.bbc.com/pidgin/media-23256550

How long ago was the most recent ‘News Update’ | Example of what we display
-- | --
< 2 mins ago | 9 April 2018Updated 1 minute ago
2 mins ago - 1 hour ago | 9 April 2018 - Updated M minutes ago
1 hour ago - 2 hours ago | 9 April 2018 - Updated 1 hour ago
2 hours ago - 10 hours ago | 9 April 2018 - Updated H hours ago
2 hours ago - 24 hours ago | N/A
More than 10 hours ago | 9 April 2018 - Updated D Mmm YYYY

****

**Comment by aeroplanejane** [comment]
Related to: 
https://github.com/bbc/simorgh/issues/3838
https://github.com/bbc/simorgh/issues/3838

**Comment by aeroplanejane** [comment]
Currently blocked by ARES-863

**Comment by aeroplanejane** [comment]
@karinathomas spoke with ares and we're hoping we can map ares.timestamp to ares.lastPublished  When this happens this issue should be resolved automatically. Closing this and have captured in JIRA WSMEDIA-138
