### ISSUE TITLE
Bumping react-router-dom causes property errors

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#4098]
**Describe the bug**
When bumping `react-router-dom` from 5.0.1 to 5.1.1 causes the following errors:
![image](https://user-images.githubusercontent.com/53564281/66138316-527ab600-e5f6-11e9-96de-2289a2ca0a0f.png)
![image](https://user-images.githubusercontent.com/53564281/66138317-5575a680-e5f6-11e9-96aa-d1a060a256d0.png)

**To Reproduce**

1. Go to `package.json` and bump `react-router-dom` version
2. Run `npm install`
3. Run `npm run test:unit`
4. See errors

**Expected behavior**
No errors.

**Additional context**
Think it is something to do with the test helpers work recently: https://github.com/bbc/simorgh/pull/3945

**Comment by mykeels** [comment]
I'm looking at this issue.

**Comment by mykeels** [comment]
I noticed the following:

- _`withRouter` was moved from `react-router-dom` to `react-router`._
- _`StaticRouter` in `react-router-dom` only has a `get` accessor, because that's what [babel gives to re-exported objects](https://stackoverflow.com/a/53307822/7396801)._
