### ISSUE TITLE
radioPage/addIdToBlocks should be homed asa preprocessor rule 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4108]
**Is your feature request related to a problem? Please describe.**
The file `/routes/getInitialData/cpsAsset/addIdsToBlocks.js` should be handled as a preprocessor rule. 

**Describe the solution you'd like**
Move the logic out of `getInitialData` and into the `preprocessor/` format. Also ensure it is consistent with out preprocessor rules. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests will cover the regression of this refactor. 

- ~[ ] This feature is expected to need manual testing.~

**Additional context**

**Comment by graeme-lindsay** [comment]
@pjlee11 @ryanmccombe Can we check if the title is correct on this, doesn't seem like a liveradio page issue

**Comment by pjlee11** [comment]
We currently `map` over the blocks array to build the live radio page, and the `map` function needs unique IDs for each block. However, assuming we are only having the blocks that are statically defined (Headline, summary and AV player) we could statically render the exact components we need and remove the `map`, therefore remove the need for the block IDs. 

If we keep the `map` logic the `addIdsToBlocks.js` logic should be homed in the preprocessor rules as it currently is in an inconsistent place compared to the rest of the application.
