### ISSUE TITLE
Add a placeholder to the Audio SMP instance on live radio pages 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4115]
**Is your feature request related to a problem? Please describe.**
For both AMP and Canonical we should have a grey image placeholder load before the SMP instance as per the updated designs. The image colour should be [C_LUNAR](https://github.com/bbc/psammead/blob/28d6ddc48138129bf90ae6b2702d312931eadc69/packages/utilities/psammead-styles/src/colours.js#L16) which means this is different to the [ImagePlaceholder](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-image-placeholder) which uses `C_CHALK`. We should confirm with UX this inconsistency of placeholder colours is correct. 

Ideally we want the same [BBC_BLOCKS](https://github.com/bbc/psammead/blob/28d6ddc48138129bf90ae6b2702d312931eadc69/packages/components/psammead-image-placeholder/src/index.jsx#L4) used on the ImagePlaceholder, however this may be more complicated on AMP than on Canonical. This is due to AMP explicitly wanting to be supplied an image via `src` and the AudioPlayer has a static height and dynamic width meaning can content on the image will distort at certain widths. Because of this UX are happy to just have a `C_LUNAR` image and we can try to overlay the BBC blocks, if possible, similar to https://github.com/bbc/psammead/blob/latest/packages/components/psammead-image-placeholder/src/index.jsx#L17 but it is likely this isn't feasible on AMP. 

**Describe the solution you'd like**
For Canonical we should load a placeholder that is grey and contains the BBC blocks in the centre of the placeholder, this could be achieved using a `<div>` with `background-color` and `background-mage` similar to the ImagePlacholder. 

For AMP we **have** to supply an `<amp-img>` and therefore need to use an image asset. Due to the static height of the component this should be a plain grey image to avoid image distortion. We can then experiment with adding the BBC blocks in a wrapping `<div>` or similar, however this is an enhanced requirement as UX are happy to just have a grey image as the placeholder. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: This will require snapshot and Cypress testing. 

Manual testing the behaviour of the placeholder image is made easier by opening the network tab and throttling the connection to either "slow 3G" or "fast 3G" to ensure the placeholder is seen before the SMP instance loads in.
- [x] This feature is expected to need manual testing.

**Additional context**
The SMP player does not load in on `test` or `live` on `.amp` pages, this is known issue - https://github.com/bbc/simorgh/issues/3970

### UX Designs

![image](https://user-images.githubusercontent.com/7791726/66224821-c1c3d900-e6ce-11e9-928e-298772818d35.png)

![image](https://user-images.githubusercontent.com/7791726/66224846-d56f3f80-e6ce-11e9-8f18-f3ff7129dd53.png)

https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5d95f9f4198cbf179991ce88

**Comment by pjlee11** [comment]
AMP PR - https://github.com/bbc/simorgh/pull/4117 -> https://github.com/bbc/simorgh/pull/4175

The canonical PR is blocked on - https://github.com/bbc/psammead/issues/2381

**Comment by karinathomasbbc** [comment]
I believe this has been done.
