### ISSUE TITLE
Embed Endpoint Hardcoded to use Live SMP

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4120]
**Describe the bug**
The embed endpoint always uses live SMP, even on TEST:

https://github.com/bbc/morph-modules/blob/master/news-av-player/templates/bodyLast.mustache#L7

**To Reproduce**
Visit https://www.test.bbc.com/korean/bbc_korean_radio/liveradio and note the SMP source

**Expected behavior**
Live SMP on live; Test SMP on test

Ensure no regression around mediator - live radio should continue to work in both test and live

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
Live radio pages on the TEST server should now load in the TEST version of SMP (aka BUMP)

![Screen Shot 2019-10-14 at 16 08 02](https://user-images.githubusercontent.com/8601460/66761999-056fcd00-ee9d-11e9-99cd-ba4d6ec19cec.png)

Live should still load in live SMP, ie, https://emp.bbci.co.uk/emp/bump-4/bump-4.js

**Comment by jamesbrumpton** [comment]
lgtm
