### ISSUE TITLE
UX request: compare Reith fonts with different formatting

### ISSUE THREAD

**Issue by katikaa** [bbc/simorgh#414]
**Is your feature request related to a problem? Please describe.**
We need to keep the number of Reith variations to a maximum of 3 (at the moment we have 6 variations in order to cover bold and italics in headlines and text). Because of that we have suggested that we only use Reith Serif Medium and Reith Sans Regular and we add weight to create Bold and we italicise to assimilate the italics family. UX would like to see the different variations on a page so that they can compare the visual output

**Describe the solution you'd like**
Please use this phrase (thanks @sareh!) and output it on a page with all below combinations:
"The quick brown fox jumps over the lazy dog"
- Compare Reith Serif Medium Italics to Reith Serif Medium with italic formatting
- Compare Reith Sans Regular Italics to Reith Sans Regular with italic formatting
- Compare Reith Sans Bold Italics to Reith Sans Bold with italic formatting
- Show Reith Serif Medium, Reith Sans Regular and Reith Sans Bold next to each other
**Additional context**
Please work with UX (Natalie or Ngan Thi)

**Comment by jamesbhobbs** [comment]
This is not longer desired, by order of Head of UX
