### ISSUE TITLE
Add support for paragraph blocks on MAPs 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4143]
**Is your feature request related to a problem? Please describe.**
MAP pages should have paragraphs rendered using the psammead-paragraph component. Paragraphs should support markdown for bold and italic. Any other markdown/HTML should be ignored and the text inside the candy_xml* should be rendered in plain text. 

**Describe the solution you'd like**
Paragraphs is a type of MAP block, these should be converted into Optimo format and rendered using the Blocks container logic. 

Both plain text paragraphs and candy_xml paragraphs should appear the same

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshot testing and E2Es are required to ensure a headline is rendered on the page.

- [x] This feature is expected to need manual testing.~

**Additional context**
***candy_xml string  example**
```
'Some text, then some <bold>bold text</bold>. Some <italic>italic text</italic>, then some unsupported markdown <strike-through>strike-through</strike-through> <span>span</span> <div>div</div>'
```

**Comment by aeroplanejane** [comment]
I think this may be duplicated by #3454
