### ISSUE TITLE
MAP Blocks - Handle Special Characters: & < >

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4153]
**Is your feature request related to a problem? Please describe.**
All text blocks for media asset pages should be able to handle special characters

**Describe the solution you'd like**
The text blocks we have added to Simorgh for MAPs should handle special characters.  This is likely to happen by default, so this issue may just be for QA

This issue can't be done until the blocks are created

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
We anticipate this to already be supported - just needs testing

**Comment by LilyL0u** [comment]
To test this, I input all special characters available in CPS into the paragraph test. Screenshots below:

![Image 05-11-2019 at 10 01](https://user-images.githubusercontent.com/54575620/68198367-c91f2080-ffb3-11e9-8f0a-6f2b6b0ed422.jpg)

![Image 05-11-2019 at 10 05](https://user-images.githubusercontent.com/54575620/68198405-db995a00-ffb3-11e9-8960-c6930493086b.jpg)

As can be seen, all special characters worked apart from & which displays as 

![UNADJUSTEDNONRAW_mini_76](https://user-images.githubusercontent.com/54575620/68198880-cd980900-ffb4-11e9-951c-73c3fce4075b.jpg)

and < and > which display together as 

![UNADJUSTEDNONRAW_mini_77](https://user-images.githubusercontent.com/54575620/68198895-d688da80-ffb4-11e9-97aa-4e55af2bc399.jpg)


Do we need these characters (&, <, >) to show in MAPs? @ryanmccombe

**Comment by LilyL0u** [comment]
To be fixed

**Comment by ryanmccombe** [comment]
These encodings need explicitly handled

This is already done for `&quot;` here: https://github.com/bbc/simorgh/blob/a7d5b1b3fb38da6d9b9db5539e3960f75a6af547/src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/paragraph/helpers.js#L6

`&amp;`, `&lt;` and `&gt;` need similar treatment

**Comment by ryanmccombe** [comment]
@LilyL0u this issue was only for text blocks, but I imagine CPS allow these characters to be added to any block type?

Fixed it for paragraphs, but headings, captions, bulleted lists - basically every block that we support where text can be added - probably has the same issue

**Comment by LilyL0u** [comment]
Inserted &, < and > into text for headline, heading, subheading, introduction, crosshead and caption and they all display properly.

Bulleted list not yet showing so will need to test that later.

I don't see the fix yet for paragraph text on test.

![Image 20-11-2019 at 12 26](https://user-images.githubusercontent.com/54575620/69239062-4b513c80-0b91-11ea-9e5e-ef5dc130c89a.jpg)

![Image 20-11-2019 at 12 26 (1)](https://user-images.githubusercontent.com/54575620/69239075-50ae8700-0b91-11ea-8710-78dd4c3f7327.jpg)

![UNADJUSTEDNONRAW_mini_7c](https://user-images.githubusercontent.com/54575620/69239139-7a67ae00-0b91-11ea-865e-1f2d89bc1388.jpg)

**Comment by ryanmccombe** [comment]
Thanks!  Surprised those work

I haven't merged the paragraph fix yet as I thought it would need applied to all the blocks - looks like we're good though

**Comment by ryanmccombe** [comment]
Paragraph fixes should be on test soon, or in latest branch for local testing

![Screen Shot 2019-11-21 at 12 48 57](https://user-images.githubusercontent.com/8601460/69339541-77d28a80-0c5d-11ea-9355-efd7270df3e2.png)

**Comment by LilyL0u** [comment]
Fixed and in test
<img width="750" alt="Screenshot 2019-11-22 at 18 01 40" src="https://user-images.githubusercontent.com/54575620/69449193-3ec81200-0d52-11ea-9ca0-39119e640133.png">
