### ISSUE TITLE
MAP Blocks - Transmission Info

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4156]
**Is your feature request related to a problem? Please describe.**
We need to handle the Transmission Info block type of a CPS asset

**Describe the solution you'd like**
Render the heading using a psammead paragraph component

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
![Screenshot 2019-10-24 at 18 03 03](https://user-images.githubusercontent.com/22519682/67508262-92c6d480-f688-11e9-8ecd-3814510739a6.png)
This is done
