### ISSUE TITLE
MAP Blocks - Footer

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4157]
**Is your feature request related to a problem? Please describe.**
We need to handle the "Footer" block type of a CPS asset

**Describe the solution you'd like**
Render the footer using a psammead paragraph component

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
![image](https://user-images.githubusercontent.com/11341355/67468918-42795380-f643-11e9-9b0c-e0d87a890916.png)

Looks like were rendering it fine :)
