### ISSUE TITLE
[Test Only] MAP Blocks - Unsupported Types are not rendered

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4160]
**Is your feature request related to a problem? Please describe.**
Any block we don't explicitly support should not be included in the simorgh output.

This includes:

- Tables
- Quote Boxes
- Fact Boxes
- Social Media Embeds

**Describe the solution you'd like**
Any unrecognised block should be removed from the rendered output.  This will likely be a default behaviour of how we implement the block renderer, so this ticket can just be used to test

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
We expect this is already the behavior we have - just needs testing (eg, add some unsupported blocks to one of our test maps, and make sure they don't show up in Simorgh)

**Comment by LilyL0u** [comment]
Tested Table, Quote Box, Correspondent Quote Box, Fact Box and Social Media Embed. In the screenshot below I have put text to show where each of these would appear if they were rendered. As you can see, under each piece of text is a blank space, so the unsupported types were not rendered.
![Image 05-11-2019 at 15 32](https://user-images.githubusercontent.com/54575620/68221540-7c523e80-ffe1-11e9-9625-fa0dc4e79175.jpg)
