### ISSUE TITLE
Ensure correct story promo is being used for FIX assets

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4163]
**Is your feature request related to a problem? Please describe.**
feature index's can include a variety of story promos's these promos should use the correct media icon to represent their type

**Describe the solution you'd like**
Ensure that different promo types on a FIX asset show the correct media icon. This logic may be identical to that used on the current front pages

**Describe alternatives you've considered**

**Testing notes**
This does not require testing.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by AlistairGempf** [comment]
Blocked on #4164.

**Comment by AlistairGempf** [comment]
Check that fixture data contains all different types of promos.

**Comment by sareh** [comment]
Closed as outdated.
