### ISSUE TITLE
Create feature Index PageType container

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4164]
**Is your feature request related to a problem? Please describe.**
Each PageType in Simorgh should have its own top level page container.

Currently feature index's uses the same FrontPage container.

**Describe the solution you'd like**
Create a new top level FeatureIndex page container which can include any logic specific to only feature indexes and then pull in the shared logic between a FIX asset and a front page i.e. the iteration and rendering of story promos is currently identical between these two assets. Identify what can be shared not be shared and split this out.

THIS will make it easier to include specific logic that is only relevant to a particular page type

**Describe alternatives you've considered**

**Testing notes**
- Similar testing for Front Page Container
- Components in Feature Index fixtures are correctly displayed

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Closed as outdated.
