### ISSUE TITLE
Set background colour of the article body content

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#417]
**Is your feature request related to a problem? Please describe.**
The background colour of the BodyContent is white

**Describe the solution you'd like**
The background colour should be `#F2EFEC` aka $OAT

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="569" alt="main content background colour" src="https://user-images.githubusercontent.com/7791726/43532891-6f682834-95ab-11e8-9ac4-eea73f203877.png">

**Testing notes**
- Snapshot tests would cover this. Cypress tests are not necessary.

**Comment by sareh** [comment]
@pjlee11 Not all of MainContent will have that background - only the part below share tools will.

**Comment by jtart** [comment]
This issue is blocked until analysis has been done, and a decision has been made, on how we will support varying UX treatments for blocks, and groups of blocks, from Optimo.

**Comment by BogdanDogaru** [comment]
~This issue is not blocked on analysis anymore, but pending an investigation into the most suitable technical solution for this (see #802).~

**Comment by BogdanDogaru** [comment]
Blocked on #841 and #839
