### ISSUE TITLE
Cypress fail faster(er)

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4193]
**Is your feature request related to a problem? Please describe.**
Sometimes our cypress tests fail, we should ensure that we stop the running cypress instance as soon as a possible in a bit to fail as fast as possible.

**Describe the solution you'd like**
Implement an afterEach step that will check the status of the previous test and exit cypress if the previous test failed.

Example here: https://github.com/cypress-io/cypress/issues/518#issuecomment-373369129
**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
I tried implemented the suggestion from the cypress issue:
```
afterEach(function() {
  if (this.currentTest.state === 'failed') {
    Cypress.runner.stop()
  }
});
``` 

However, we are not using `mocha` we are unable to access `this.currentTest.state`

![image](https://user-images.githubusercontent.com/30599794/66926508-16981580-f026-11e9-8db3-e14800ac98c5.png)

I also tried this suggestion in the issue: 
```
Cypress.on('fail', () => {
    Cypress.stop();
    throw new error;
});
```
This worked on `npm run cypress:interactive` however it did not work on CI and skipped the failing tests instead flagging it. 

I will be closing this issue until there is an official cypress functionality to do this.
