### ISSUE TITLE
More console errors when navigating between articles

### ISSUE THREAD

**Issue by mykeels** [bbc/simorgh#4206]
**Describe the bug**
When clicking an internal link to a new article, these errors are thrown and appear in console:
- Warning: Failed prop type: The prop `status` is marked as required in `WithContextsContainer`, but its value is `null`.
- Warning: Failed prop type: The prop `status` is marked as required in `PageWrapperContainer`, but its value is `null`.
- Warning: Failed prop type: The prop `statusCode` is marked as required in `RequestContextProvider`, but its value is `null`.

**To Reproduce**

1. Run npm run dev
1. Go to http://localhost.bbc.com:7080/news/articles/c0g992jmmkko
1. Click on the link to another article placed on the tomb of the unknown warrior
1. Open console
1. See error

**Expected behavior**
When navigating through articles, I should not see any console errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/11996508/66751070-119c6000-ee86-11e9-89f8-d1a4ca056c4f.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Comment by itimirichard** [comment]
This issue can no longer be reproduced
