### ISSUE TITLE
Validate value of minimum items in schema

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#422]
**Is your feature request related to a problem? Please describe.**
Currently the validator does not check against the `minItems` value in the schema

**Describe the solution you'd like**
The validator should check arrays meet the minimum value set in the schema

**Describe alternatives you've considered**
N/A

**Additional context**
This should be done following https://github.com/bbc/simorgh/issues/404

**Comment by jamesbhobbs** [comment]
Should be handled where it causes problems not by the pure number, e.g. where we lack a headline it breaks a11y
