### ISSUE TITLE
Inline links - styling

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#424]
**Is your feature request related to a problem? Please describe.**
Styles of inline links do not meet UX requirements.

**Describe the solution you'd like**
Inline links should have the following styles:
- color:  `#0F556C` bluejay
- border-bottom: 1px solid `#0F556C` bluejay
- font-family: same as text

background-color: not applicable

**Additional Context**
  - All links open in current tab
  - No bold or italic (i.e. the formatting is removed) - does not block this ticket, done in #481
  - This issue may be worked on at the same time as any PR in the following group: #424, #425, #426, #427

**Testing**
- Cypress test
- Tab through to link
- Open via keyboard should open in current tab
- Check superscript/subscript characters in links (dependent on #454)

**Screenshot of designs**
<img width="277" alt="inline link" src="https://user-images.githubusercontent.com/7791726/43958961-084d9444-9ca5-11e8-82af-a214c2b13af5.png">

**Comment by nataliesmart** [comment]
Should be as follows:
color: #0F556C bluejay
border-bottom-color: 1px solid #0F556C bluejay
background colour: none
border: none

**Comment by jtart** [comment]
The font-family will be applied in #451, as the link will just inherit the text font family value.

Furthermore, it was decided by UX (@nataliesmart) that we will apply a 2px transparent border to the default styles so there is not a jump.
