### ISSUE TITLE
(AV Testing) Check for no subtitle button when a subtitle file isn't present

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4244]
**Cypress Testing Scenario**
This test is to check that when a user plays a video that doesn't include a subtitle file there is no subtitle button present within the media player.

**Testing steps to follow**

1. Given that the page contains a media block (Video/Audio)
2. When the user plays a video
3. And there is no subtitle file present
3. Then there will be no visible subtitle button within the media player

**Expected Outcome**
When a user plays a video that doesn't contain a subtitle file there will be no subtitle button visible on the player

**Comment by HarveyPeachey** [comment]
We will not be writing tests for this because it's based on SMP behaviour
