### ISSUE TITLE
(AV Testing) Check a UK based user can play UK ONLY content

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4245]
**Cypress Testing Scenario**
This test is to check that a user based within the UK can play UK only content.

**Testing steps to follow**

1. Given that the user is based in the UK
2. When media block contains content that is UK ONLY
3. And the user clicks the play button
3. Then the video play without error

**Expected Outcome**
When a user is based within the UK and clicks play on a video that is marked as UK ONLY they should be able to play it without error.

**Comment by HarveyPeachey** [comment]
We can't write tests for this as we need to bypass SMP's geolocation.
