### ISSUE TITLE
(AV Testing) Check a non-UK based user cannot play UK ONLY content

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4246]
**Cypress Testing Scenario**
This test is to check that a user based outside of the UK cannot play UK only content.

**Testing steps to follow**

1. Given that the user is *not* based in the UK
2. When media block contains content that is UK ONLY
3. And the user clicks the play button
4. And the video *should not* play
5. Then the user will receive a location based error message

**Expected Outcome**
When a user is *not* based within the UK and clicks play on a video that is marked as UK ONLY they should not be able to play it. They should also receive a relevant error message.

**Comment by HarveyPeachey** [comment]
We will not be writing tests for this because it's already enforced by SMP player.
