### ISSUE TITLE
(AV Testing) Check a UK based user cannot play international ONLY content

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4247]
**Cypress Testing Scenario**
This test is to check that a user based within the UK cannot play international only content.

**Testing steps to follow**

1. Given that the user is based in the UK
2. When media block contains content that is international ONLY
3. And the user clicks the play button
4. And the video *should not* play
5. Then the user will receive a location based error message

**Expected Outcome**
When a user *is* based within the UK and clicks play on a video that is marked as international ONLY they should not be able to play it. They should also receive a relevant error message.

**Comment by HarveyPeachey** [comment]
We can't write tests for this as we need to bypass SMP's geolocation.
