### ISSUE TITLE
(AV Testing) Check a non-UK based user can play international ONLY content

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4248]
**Cypress Testing Scenario**
This test is to check that a user based outside the UK can play international only content.

**Testing steps to follow**

1. Given that the user is based outside the UK
2. When media block contains content that is international ONLY
3. And the user clicks the play button
4. Then the video *should* play

**Expected Outcome**
When a user *is* based outside the UK and clicks play on a video that is marked as international ONLY they should be able to play it.

**Comment by HarveyPeachey** [comment]
We can't write tests for this as SMP enforces this.
