### ISSUE TITLE
(AV Testing) Check user based anywhere can play UK+International videos

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4249]
**Cypress Testing Scenario**
This test is to check that a user based on earth can play content marked as UK+international.

**Testing steps to follow**

1. Given that the user is based on earth
2. When media block contains content that is UK+international
3. And the user clicks the play button
4. Then the video *should* play

**Expected Outcome**
When a user *is* based on earth and clicks play on a video that is marked as UK+international they should be able to play it.

**Comment by HarveyPeachey** [comment]
We can't write tests for this as SMP enforces this.
