### ISSUE TITLE
(AV Testing) Check that a user can play a video with an expiry date set in the future

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4250]
**Cypress Testing Scenario**
This test is to check that a user can play a video with an expiry date set in the future.

**Testing steps to follow**

1. Given that a video has an expiry date set in the future
2. When the user clicks the play button
3. Then the video *should* play

**Expected Outcome**
When a video has an expiry date set in the future, the user should be able to click play/watch the content without error.

**Comment by HarveyPeachey** [comment]
We can't write tests for this as SMP enforces this.
