### ISSUE TITLE
(AV Testing) check that a user cannot play a video that has expired

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#4251]
**Cypress Testing Scenario**
This test is to check that a user cannot play a video that has expired.

**Testing steps to follow**

1. Given that a video has expired
2. When the user clicks the play button
3. And the video *should not* play
4. Then the user should receive a relevant error message

**Expected Outcome**
When a video has expired then the user should not be able to play the content and they should also receive a relevant error message.

**Aditional Context**
Investigation will be needed to check how the expiry logic works and whether we need to write code to prevent this from happening. A tester and developer should work together to investigate this. https://github.com/bbc/simorgh/issues/4252 Might be related

**Comment by HarveyPeachey** [comment]
Investigation will be needed to check how the expiry logic works and whether we need to write code to prevent this from happening. A tester and developer should work together to investigate this.
