### ISSUE TITLE
Inline links from WS to News 500 in the UK

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#4255]
**Describe the bug**
Inline links from a WS article to a .com/news article 500 in the UK.

**To Reproduce**

1. Go to https://www.test.bbc.com/afaanoromoo/articles/ck6nrm5l8yzo
2. Click on the link
3. See 500 error
4. Click refresh
5. See page correctly

**Expected behavior**
1. Go to https://www.test.bbc.com/afaanoromoo/articles/ck6nrm5l8yzo
2. Click on the link
3. See page correctly

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Closing, won't fix.

**Comment by aeroplanejane** [comment]
This also affects links from one service to another with client side rendering.  Currently edge case. If / when this becomes an issue we might look to tackle it again.
