### ISSUE TITLE
Simorgh online storybook not serving fonts properly

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#4259]
Related to https://github.com/bbc/simorgh/pull/4189

**Describe the bug**
The `static` folder where storybook gets fonts from now doesn't seem to be a valid path on the online storybook.

**To Reproduce**
1. Go to https://bbc.github.io/simorgh/?path=/story/containers-heading--default-heading
2. Open console and see 404s on font files

**Expected behavior**
Fonts to be served properly from the `static` folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/53564281/66916526-4ab60b00-f013-11e9-8aa4-d720cd8f4fc6.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Comment by amywalkerdev** [comment]
Guessing this is related to this? https://github.com/bbc/simorgh/pull/4181

**Comment by hotinglok** [comment]
Think it was broken before that got merged @amywalker1987
