### ISSUE TITLE
Remove use of localhost.bbc.com

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#4265]
**Is your feature request related to a problem? Please describe.**
When we did https://github.com/bbc/simorgh/issues/1976 and https://github.com/bbc/simorgh/issues/1992 we moved to using `localhost.bbc.com`/`localhost.bbc.co.uk` for 
various aspects of local development and when running automated tests.

This DNS record will shortly cease to exist which will have a major impact on our ability to develop locally and run tests on CI. We should therefore change it back to `localhost`.

Note: as a result of this we _may_ lose the ability to see and test SMP on localhost but if so we will need to explore alternative solutions to this as part of a separate issue.

**Describe the solution you'd like**
- Replace references to `localhost.bbc.com` or `localhost.bbc.co.uk` with `localhost`

**Describe alternatives you've considered**
We could modify the hosts file on Jenkins and on every developer's machine but this is probably not sustainable.

**Testing notes**
- [x] This feature is expected to need manual testing.
- Test all aspects of dev workflow
- Test AV content playing locally on articles/media pages
- Test on CI/CD

**Additional context**

**Comment by dr3** [comment]
Things to check:
Does the video iframe require its loaded on `*.bbc.com`?
Will ads require theyres on `*.bbc.com`?
Are there any other requirements that require the domain to be `*.bbc.com`?

**Comment by jamesdonoh** [comment]
I did a quick check running a production build locally with `SIMORGH_BASE_URL` and `SIMORGH_PUBLIC_STATIC_ASSETS_ORIGIN` set to `http://localhost:7080` and AV content still plays. I suspect the SMP restriction described in https://github.com/bbc/simorgh/issues/1976 does not apply to us any longer because we aren't using BUMP. However this needs testing carefully across a range of different situations to be sure.

Re. ads we should be able avoid any such restriction by discussing it with the team responsible for implementing them. My other concern worry is whether it impacts any of our AMP use cases, @pjlee11 might be best placed to advise here.

**Comment by pjlee11** [comment]
I'm not aware of this explicitly affecting AMP in anyway, the AV playback concerns should be the same for canonical and AMP AFAIK

**Comment by jamesdonoh** [comment]
Confirmed with Benjamin there's no upcoming expectation for ads or anything else to need us to be on `.com` locally or on CI. If it happens let's (re-)cross that bridge then.
