### ISSUE TITLE
Console warning on latest: <html> cannot appear as a child of <div>

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#4284]
**Describe the bug**
A console warning originating from `./server/Document/component.test.jsx` is currently on latest. 

**To Reproduce**

1. Run `npm run test:unit` on latest.
2. See console warning

**Expected behavior**
No console warnings

**Screenshots**
If applicable, add screensh.ots to help explain your problem.
![image](https://user-images.githubusercontent.com/53564281/67024338-24b86580-f0fc-11e9-86df-931df56059dc.png)

**Comment by oluoluoxenfree** [comment]
@thekp has narrowed it down a bit; it seems to be an issue with the way `shouldMatchSnapshot` works, and that we may just have to suppress the warning here. I'll investigate that option and also discuss further tomorrow if there is a possible fix.
