### ISSUE TITLE
propTypes warnings on client side render

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4285]
**Describe the bug**
`npm run dev`, visit http://localhost.bbc.com:7080/news/articles/c0g992jmmkko and click the inline link (any link inside the article main paragraphs), see errors in console.

**Expected behavior**
There should not be propTypes errors in the console when performing an onward journey using the client app.

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/67028624-934cf180-f103-11e9-8cc7-c31e55fe7327.png)

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by stevenwally** [comment]
Hey! Can I take this bug? I attempted assigning it to myself, but wasn't able to 🤔

**Comment by dr3** [comment]
Sure @stevenwally :)
