### ISSUE TITLE
Analyse performance of psammead-rich-text-transforms in simorgh

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#4286]
While it's good we're working to limit content sizes, have we also investigated the browser memory/CPU usage of `psammead-rich-text-transforms` on anything other than a fast laptop yet? A pure JS XML parser sounds like it has the potential to make the browsing experience on low-end phones sluggish. Could we measure the impact?

_Originally posted by @jamesdonoh in https://github.com/bbc/simorgh/pull/4240#issuecomment-543245620_

**Describe the solution you'd like**
Following https://github.com/bbc/simorgh/pull/4240 we should analyse the performance of `psammead-rich-text-transforms` and how it will affect low end devices. This should be backed with data collected and a dropbox paper written describing this data.

We can then analyse this and debate if we should move to a serverside sollution as a priority before release or not.

**Additional context**

**Comment by pjlee11** [comment]
Copying over comment from #4240 

Totally agree, this is a concern we need to take seriously. When we are running this properly on www.test we will need to evaluate the affect on low end devices. We also should check this against the stats of how many onward journeys our users actually perform as it will only affect the client side render as on the first page load the server handles the parsing.

Furthermore it might be CPU heavy to parse the data but the benefits of a SPA might mean that even on a low-end device the second page load is quicker then the current full server render the PAL currently performs in production.

Also the library and modelling of Optimo blocks (work that will follow this PR) will both be entirely re-usable if we moved to a server-side approach in the future
