### ISSUE TITLE
Update news-av-player to support CPS payloads

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4287]
**Is your feature request related to a problem? Please describe.**
We need to update our morph module to support our MAP use case

The module can already support CPS payloads - we just need to handle the integration to make it work based on our props, without any regressions to the existing behaviour

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
Currently the `news-av-player` only supports video playback in the classic skin, we need to also support audio media in MAPs.

**Comment by pjlee11** [comment]
`format === video` - https://github.com/bbc/morph-modules/blob/master/news-av-player/src/cps.js#L14

**Comment by ryanmccombe** [comment]
Note the CPS audio example we use no longer seems valid: https://www.test.bbc.com/ws/av-embeds/cps/igbo/afirika-23252735/p01mr6r9/ig

This asset does not have a media block with that vpid

This one seems to work:
https://www.test.bbc.com/ws/av-embeds/cps/thai/international-23252825/p01mr6r9/th
