### ISSUE TITLE
AV player indented at smaller screen sizes

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#4311]
**Describe the bug**
The media player is currently indented on 375px, 600px, and 768px layouts.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.test.bbc.com/igbo/articles/cr1lw620ygjo
2. Toggle to the widths listed above.
3. Scroll down to the media player block. 
4. See that the media player block is indented.

**Expected behavior**
The media player needs to be flush on all layouts. See designs here: https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c596fa88971d341fae3fd53

**Screenshots**
Screenshot of the bug:
![image](https://user-images.githubusercontent.com/52247014/67188713-d5688280-f3e4-11e9-823e-c96cc019d40f.png)

Screenshot of correct placement:
![image](https://user-images.githubusercontent.com/52247014/67188660-bb2ea480-f3e4-11e9-8dbc-fbf46fd275e2.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
While testing this issue, we should ensure that it also fixes https://github.com/bbc/simorgh/issues/4735

**Comment by 12** [comment]
I suspect this is because we are using the wrong grid definition. I imagine this will be fixed when we move to the new grid system.
