### ISSUE TITLE
Split out the dataValidator logic into it's own application

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#432]
**Is your feature request related to a problem? Please describe.**
Currently the data validation logic is i embedded within this application and we should split it out.

**Describe the solution you'd like**
Create a seperate application for the data validation logic. 

**Describe alternatives you've considered**
N/A

**Comment by ChrisBAshton** [comment]
Related to #920.

**Comment by ChrisBAshton** [comment]
In fact, superseded by it.
