### ISSUE TITLE
Images at 100x100px are getting scaled up

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#4341]
**Describe the bug**
100x100px images are getting scaled up on the article page. 

**To Reproduce**
1. Go to https://www.test.bbc.com/igbo/articles/cx6yzp3lgz3o
2. Scroll down to the image captioned 'Image size 100x100'
3. See that the image is being scaled up

**Expected behavior**
100x100px is the smallest image size possible. Images at this size should be displayed at this size and should not be scaled up.

**Screenshots**
As is screenshot:
![image](https://user-images.githubusercontent.com/52247014/67190981-cdaadd00-f3e8-11e9-91ba-2f70f0485ca1.png)
To be screenshot from designs:
![image](https://user-images.githubusercontent.com/52247014/67221599-9efe2800-f423-11e9-9253-71d91a73f74b.png)

**Desired solution:**

Psammead components to investigate:

https://github.com/bbc/psammead/blob/latest/packages/components/psammead-image-placeholder/src/index.jsx#L15

 https://github.com/bbc/psammead/blob/latest/packages/components/psammead-image/src/index.jsx#L24

**Testing notes**

- [ ] Raise a draft PR to run the Jenkins job which will run a Chromatic test.

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Not going to fix. Closing.
