### ISSUE TITLE
[Service Variant] SERVER - Allow Simorgh to default to a variant

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4346]
**Is your feature request related to a problem? Please describe.**
Simorgh must default to a service variant for services that have variants;

- ukchina
- zhongwen
- serbian

ukchina and zhongwen should default to /trad
serbian should default to /lat

**Describe the solution you'd like**

If no variant is specified in the url path then default to a specified variant ensuring to use the correct service config and make the correct data fetches.

The following should happen: 
http://localhost:7080/ukchina > http://localhost:7080/ukchina/trad
http://localhost:7080/zhongwen > http://localhost:7080/zhongwen/trad

http://localhost:7080/ukchina/articles/c0e8weny66ko > http://localhost:7080/ukchina/articles/c0e8weny66ko/trad
http://localhost:7080/zhongwen/articles/c3xd4x9prgyo > http://localhost:7080/zhongwen/articles/c3xd4x9prgyo/trad

**Describe alternatives you've considered**
N/A

**Testing notes**
The above urls for the three service should default to default variant if the variant isn't provided in the url.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
NB: In the future Simorgh will need to respect a cookie that may have already been set and either default/redirect to a variant based on the value of this cookie.

Cookie set: 

```
zhongwen: 'ckps_chinese',
ukchina: 'ckps_chinese',
serbian: 'ckps_serbian'
```

**Comment by dr3** [comment]
IMO this issue should begin with drawing out all the user journeys and get that signed off by @dgm34 before implementing :)

**Comment by dgm34** [comment]
As a brief update I've been part of conversations led by @hindsc52 and I consider the work he's done and the proposals that he sketched out sufficient for me to back away from this now 👍

**Comment by chris-hinds** [comment]
[Simorgh variant User Journeys (1).pdf](https://github.com/bbc/simorgh/files/3792991/Simorgh.variant.User.Journeys.1.pdf)

**Comment by mykeels** [comment]
Is there already a cookie name for preferred variants?

**Comment by chris-hinds** [comment]
> Is there already a cookie name for preferred variants?

Sure is, they are at the bottom of the issue description

**Comment by samora** [comment]
@mykeels already integrated my PR in this PR https://github.com/bbc/simorgh/pull/4567.
