### ISSUE TITLE
[Service Variant] CLIENT - Respect the cookie value if set and render the correct variant

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4348]
**Is your feature request related to a problem? Please describe.**
With service variants we have a script switch, this switch allows the users to specify their preferred variant and it saves that value in a cookie i.e. `ckps_chinese` with a value of either `simp` or `trad`

Simorgh should respect the value of this cookie if it is set and render the correct variant for a given request.

**Describe the solution you'd like**
If the cookie is set and the value is different to the original request i.e. the initial render was for /trad but the users preference is /simp can we programmatically route the user to their preferred variant and re-render the page

**Describe alternatives you've considered**
issue a 302 redirect to the users preferred variant

**Testing notes**
Depending on the cookie value set for `ckps_chinese`,`ckps_serbian` the variant of the page should be displayed.If no cookie value is set then the default variant page should be loaded.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
This will likely use `import { Redirect } from 'react-router-dom'`

**Comment by dr3** [comment]
This will highly tie in with https://github.com/bbc/simorgh/issues/4346 and IMO they should both begin with user journeys being spec'd out before implementing anything

Ive started https://paper.dropbox.com/doc/Service-Variant-redirects--AnHx0LNyhYJo9oXfHxlEFSvlAg-vlUWYhEGTuRTev1HFMP4m to map various journeys out and discuss technical limitations

This will likely use import { Redirect } from 'react-router-dom'

**Comment by chris-hinds** [comment]
[Simorgh variant User Journeys (1).pdf](https://github.com/bbc/simorgh/files/3792991/Simorgh.variant.User.Journeys.1.pdf)

**Comment by mykeels** [comment]
How do we determine a service's default variant?

**Comment by mykeels** [comment]
What part of the simorgh code can we perform this intercept in?

**Comment by chris-hinds** [comment]
The default variant is probably going to have to be stored in the service config.

**Comment by mykeels** [comment]
See `src/app/lib/utilities/variantHandler/index.js` for information on default variants
