### ISSUE TITLE
[Service Variant] Allow Simorgh users to set a cookie for their preferred variant

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4350]
**Is your feature request related to a problem? Please describe.**
A script switch component is being built that is designed to allow a user to specify their preferred variant for a service.

[Psammead Script Switch](https://bbc.github.io/psammead/?path=/story/components-scriptlink--default)

A user clicking on this switch should set the variant cookie or updates its value if it already exists and direct the user to that variant buy pushing a new route onto the history API allowing react router to render the new variant.

Cookies to set
```
zhongwen: 'ckps_chinese',
ukchina: 'ckps_chinese',
serbian: 'ckps_serbian'
```

**Describe the solution you'd like**
Provide a way to update or set the variant cookie from a click event, that can be passed to the psammead component.

This would involve creating a new container in Simorgh, that should import an action from a reducer with a function to set or update the cookie and then re-route the user to the updated variant.

The action/reducer pattern should be followed here, like the toggles reducer https://github.com/bbc/simorgh/blob/latest/src/app/reducers/ToggleReducer/index.jsx

This would lead to a context that contains the values of all user cookies making it easier to update and and read the values of cookies throughout the app

**Describe alternatives you've considered**

**Testing notes**
The script switch `lat/cyr` available on the side of the nav on article and frontpage for services with variants should switch the page when the switch is clicked and also set the cookie value accordingly, if the user has accepted personalisation cookies.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
[Simorgh variant User Journeys (1).pdf](https://github.com/bbc/simorgh/files/3792991/Simorgh.variant.User.Journeys.1.pdf)

**Comment by jroebu14** [comment]
This might be a nice approach - instead of updating cookies and then react context on a click event, we could set up a [cookie change event listener](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged) where the callback updates the react context in the event that cookies are updated in the click event. The benefit of this is that the react context update is bound to the changing of cookie values rather than having to explicitly update both cookies and context.

I'm sure there's a good discussion to be had about either approach though.

**Comment by jroebu14** [comment]
Another idea I had for a snappier variant transition might be to prefetch the variant content on hover/focus of the toggle.

**Comment by samora** [comment]
`js-cookie` doesn't support the cookie listening api. However, I found  [universal-cookie](https://www.npmjs.com/package/universal-cookie) that is almost a drop-in replacement for `js-cookie` with the listening api. 

There is also a React Hooks lib, [react-cookie](https://www.npmjs.com/package/react-cookie), that takes care of state, change listeners and all.

**Comment by samora** [comment]
@jroebu14 What do you think about this?

> `js-cookie` doesn't support the cookie listening api. However, I found [universal-cookie](https://www.npmjs.com/package/universal-cookie) that is almost a drop-in replacement for `js-cookie` with the listening api.
> 
> There is also a React Hooks lib, [react-cookie](https://www.npmjs.com/package/react-cookie), that takes care of state, change listeners and all.

**Comment by jroebu14** [comment]
Work is completed and in the latest Simorgh to redirect to the correct service variant when:

1. when the variant is not specified in the URL -> redirects to the default variant
2. when a preferred service variant cookie exists -> redirects to the variant from the cookie value

All that is left to do is to implement the psammead script switch and set the cookie when it is clicked. This means that psammead script switch will need an on click event that we can hook into to set the cookie from within Simorgh.

**Comment by tochwill** [comment]
I've raised a PR to include this based on some work that was done a while ago, that I've just added a check to make sure that we're respecting personalisation cookies. There are some differences in that implementation than what is described on this ticket, I just want to check if there's any new context/conversations that I missed. https://github.com/bbc/simorgh/pull/5676

**Comment by tochwill** [comment]
Keeping this open until we've done a round of testing on the test environment.
