### ISSUE TITLE
Standardise SMP Settings

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4361]
**Is your feature request related to a problem? Please describe.**
We currently have 4 different scenarios that implement SMP:

- Off-Forge team
- Articles Pod - Optimo Articles
- Media Pod - Live Radio
- Media Pod - Media Asset Pages

This is going to be extended to STY pages in the future

These scenarios implement slightly different SMP settings - from some initial exploration, the differences fall into 3 categories:

1. Differences that have no effect - one team explicitely set a value that would be defaulted to that value anyway (eg, ui controls)
2. Differences that aren't needed, but are just a side effect of issues being created by different teams (eg, responsive vs super-responsive)
3. Differences that reflect legitimate product requirements (eg, analytics producer)

**Describe the solution you'd like**
We should analyse and agree a cross-team standard set of SMP settings, and only implement changes where there's a legitimate product need (3rd category)

Once this is done, we should also update the `news-av-player` morph module to implement these requirements in a robust way - the current code here is largely just me hacking in media pod requirements in a way that avoids changing the settings for other teams

**Agreed Approach:**

**Step 1:** Generate fixtures for articles and off-forge scenarios, and write integration tests that verify against them

See examples for live radio and MAP here: https://github.com/bbc/morph-modules/tree/master/news-av-player/test/fixtures

For each sub-scenario - where the expected output is going to be different based on the ARES response or props, it might necessitate creating another fixture - similar to how "Live Stream" and "MAP" are two different fixtures

Where the variation is smaller, it can perhaps be handled by just modifying the expected output within the test, eg: https://github.com/bbc/morph-modules/blob/master/news-av-player/test/unit/map.spec.js#L47-L50

**Step 2:** Having generated fixtures - create a standard SMP settings fixture that has the common components of all the scenarios.  Any business logic that is specific to a certain scenario should not be included in this.

**Step 3:** Create the base `getSMPSettings` function and integration test that test against the fixture created in step 2

**Step 4:** Create `getSMPSettings` variants for each of the scenarios we care about.  These can be integration tested and verified against the fixtures created in step 1 (which may need updated)

The individual variations look like the extension functions in this proposal: https://gist.github.com/ryanmccombe/83e76e32cbfa8577be3705e27c31ba26

**Context:**
Based on original proposal agreed here: https://gist.github.com/ryanmccombe/83e76e32cbfa8577be3705e27c31ba26

**Related links:**
- https://en.wikipedia.org/wiki/Strategy_pattern
- https://blog.bitsrc.io/keep-it-simple-with-the-strategy-design-pattern-c36a14c985e9

This is based on the strategy pattern, but on the call, we acknowledged "scenario" was probably a more appropriate name for our use case - eg, the "live radio scenario", "articles scenario"

Note this pattern can be implemented using any syntax desired - functional or classes

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Internal links:
Slack conversation (includes many links): https://bbcnews.slack.com/archives/CJT0284G2/p1571670079043900
Morph Module: https://github.com/bbc/morph-modules/tree/master/news-av-player

**Comment by aeroplanejane** [comment]
Google doc with settings across the players: https://docs.google.com/spreadsheets/d/1j7HlOZvEbg94de4sDr5mMx0hD0NJqvbVMNM5ELi4CXs/edit?usp=sharing

**Comment by ryanmccombe** [comment]
@simonsinclair @jamesdonoh @alex-magana Updated this with agreed approach after the call

I'm available any time tomorrow after 11:30ish to assist with this if needed

There can be quite a lot of work in all these steps, but as long as at least step 1 is done (creating the expected output for articles & off-forge) I can finish any remaining steps off next week :)

**Comment by jamesdonoh** [comment]
Good stuff - thanks for this @ryanmccombe @simonsinclair 👌
