### ISSUE TITLE
Type error in AV page metadata

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#4375]
**Is your feature request related to a problem? Please describe.**

Currently when validating page level schema.org metadata the AV part shows as an `Unspecified Type`, as seen on the screenshot below

![Screen Shot 2019-10-22 at 15 26 50](https://user-images.githubusercontent.com/25608386/67384204-a1c65d80-f588-11e9-8bcc-cd01a7a5a9ae.png)

This needs to be corrected to show a valid type.

**Describe the solution you'd like**
- Explore alternatives to the solutions considered below
- Validate page-level metadata using [this tool](https://search.google.com/structured-data/testing-tool/u/0/)

**Describe alternatives you've considered**
- Adding type of `MediaObject` to the av metadata - https://schema.org/MediaObject
- Incorporating the [AV metadata](https://github.com/bbc/simorgh/blob/latest/src/app/containers/MediaPlayer/Metadata.jsx) into the [LinkedData component](https://github.com/bbc/simorgh/blob/latest/src/app/containers/LinkedData/index.jsx#L58). 
Doing this also addresses the issue of linking an AV content to it's associated article, listing the video/audio directly under the [Article type](https://schema.org/Article).

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
An example of the expected validation for an article page with multiple videos
![Screen Shot 2019-10-23 at 09 38 01](https://user-images.githubusercontent.com/25608386/67380847-d9caa200-f582-11e9-8aa1-e6efafaf759b.png)

**Comment by lizcameron** [comment]
Closed via #4664
