### ISSUE TITLE
Remove unused ATI Producers logic

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#4392]
**Is your feature request related to a problem? Please describe.**
~Currently we don't have all of the Producer values for all the services: https://github.com/bbc/simorgh/blob/latest/src/app/lib/analyticsUtils/index.js#L155~

The ATI producers are now being passed in via the Service config. So we should remove the getProducers function from the file.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
The ATI producers are now being passed in via the Service config. So we should remove the `getProducers` function from the file.

**Comment by amywalkerdev** [comment]
Covered in #4738
