### ISSUE TITLE
Investigate whether older CPS MAP pages can play video in Simorgh 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4393]
**Is your feature request related to a problem? Please describe.**
Once Mozart has enabled the routing of all MAP assets from Ares we need to ensure that older MAP assets can still play video. 

These are assets that have been published from CPS over 3 years ago. 

**Describe the solution you'd like**
We need to collate a list of older CPS assets to test against: 
https://api.live.bbc.co.uk/content/asset/japanese/video-34654975
https://api.live.bbc.co.uk/content/asset/news/business-30926413
https://api.live.bbc.co.uk/content/asset/news/uk-wales-30796321
https://api.live.bbc.co.uk/content/asset/news/uk-northern-ireland-30890027
https://api.live.bbc.co.uk/content/asset/news/uk-politics-30835220
https://api.live.bbc.co.uk/content/asset/news/world-middle-east-30934373
https://api.live.bbc.co.uk/content/asset/news/magazine-30551860
https://api.live.bbc.co.uk/content/asset/news/uk-politics-30900584

We need to ensure that we support video playback against older video assets. 
We need to perform a regression test against the pages. 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Added links above.

**Comment by gavinspence** [comment]
@aeroplanejane to test separately when we have the first batch of services with older content on Test.

**Comment by karinathomasbbc** [comment]
I don't think that any of these assets will be in Simorgh... so not sure how to test?

**Comment by aeroplanejane** [comment]
I've started compiling a bunch of assets across the services published in CPS in 2016 here: https://paper.dropbox.com/doc/CPS-Test-Assets-OLDER-SITES--AuQEugWXaFm7Rc2aDYcC4p43AQ-00xOifrgbx7PJ3zjsFqtZ
We would test these by appending the renderer_env=live override in test or stage
