### ISSUE TITLE
ATI enhancement: Set or update atuserid cookie

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#4398]
**Is your feature request related to a problem? Please describe.**
We currently see double counting of users in ATI if they visit a Simorgh page then later visit an Orbit-using page.  This is because the way Orbit sets and stores the user ID is different from the default ATI approach which Simorgh uses.

**Describe the solution you'd like**
Make the following changes:

When a user arrives on a Simorgh page, *before sending anything to ATI*, check for the existance of an `atuserid` cookie on our domain.

If the cookie *does not* exist:

1. Generate a UUID, e.g. `00000000-1111-aaaa-bbbb-1234567890ab`
2. Generate a date 13 months in the future, e.g. `2020-11-24T08:28:00.888Z`
3. Create a JSON object in the following format: `{"name":"atuserid","val":"00000000-1111-aaaa-bbbb-1234567890ab","options":{"end":"2020-11-24T08:28:00.888Z","path":"/"}}` using the two values created
4. Stringify and URL Encode the JSON object, e.g. `%7B%22name%22%3A%22atuserid%22%2C%22val%22%3A%2200000000-1111-aaaa-bbbb-1234567890ab%22%2C%22options%22%3A%7B%22end%22%3A%222020-11-24T08%3A28%3A00.888Z%22%2C%22path%22%3A%22%2F%22%7D%7D`
5. Write the string as the value of a cookie named `atuserid` and save for the current domain (e.g. `.bbc.co.uk` or `.bbc.com`) with an expiry date matching the date generated in Step 2,  and path `/`
6. You can now allow the ATI code to construct it's hit, which will include the UUID from the cookie as the `idclient` parameter (this work done already)

If the cookie *does* exist

1. Generate a date 13 months in the future, e.g. `2020-11-24T08:28:00.888Z`
2. Update the date in the value of the cookie to match the new date
3. Update the expiry date of the cookie to match the new date

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by lintal** [comment]
One AC I have is that the format of the cookie value should satisfy the following Regex. This is something ATI have supplied:

`{\"name\":\"atuserid\",\"val\":\"([0-9a-zA-Z\\-]+)\".*`
