### ISSUE TITLE
Enable SPA CPS -> CPS navigation for inline links

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#4399]
### PLEASE GET SIGN OFF FROM @benjaminhobbs @jamesdonoh @hindsc52 BEFORE MERGING

**Is your feature request related to a problem? Please describe.**
At the moment we only use react router links for paths that match the articles regex, we should expand this to CPS Assets.

**Describe the solution you'd like**
Expand inline links to work for CPS assets

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by graeme-lindsay** [comment]
Blocked until we see the Mozart routing work completed

**Comment by aeroplanejane** [comment]
We are going to assume everthing is on the PAL and mozart will handle - am I right, @dr3 ?

**Comment by dr3** [comment]
@aeroplanejane Chatted with seniors, we think to be safe we wont enable Simorgh page -> Simorgh CPS page navigation untill all of a services CPS traffic is handled by simorgh.

This does mean we cant have `Simorgh MAP -> Simorgh MAP` or `Simorgh Frontpage -> Simorgh MAP` SPA navigation untill we migrate entire services onto simorgh for all CPS assets though :( They will need to do hard server page loads untill then.

This is due to not being able to known the type of asset, and thus if its for Simorgh or the PAL before a user clicks the link

**Comment by aeroplanejane** [comment]
Ok thanks @dr3 - that's a shame! Do we think we're going to get a bit of a lag / jarring experience when users navigate between page types until we resolve this issue?

**Comment by dr3** [comment]
@aeroplanejane it shouldn't be too bad, it will be better than the current `Simorgh frontpage -> Pal Story` we have atm :)
