### ISSUE TITLE
Heading added below media for MAP

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4403]
**Is your feature request related to a problem? Please describe.**
The headline transformer always adds the heading to the start of the blocks

![Screen Shot 2019-10-24 at 11 32 40](https://user-images.githubusercontent.com/8601460/67477571-42cd1b00-f652-11e9-950c-f5c3b506e1cd.png)

For MAPs, we want the media to be first

**Describe the solution you'd like**
Update the transformer to prevent it from adding a heading above the media player if the page is a MAP

It can add the heading below instead

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by pjlee11** [comment]
@ryanmccombe there are a11y requirements we should evaluate before just moving the headline below the AV player. I believe @greenc05 has been looking into this recently...

Update: #4150 has details on the investigation
