### ISSUE TITLE
AMP validation for a single scenario

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#441]
**Is your feature request related to a problem? Please describe.**
After an AMP route has been created (https://github.com/bbc/simorgh/issues/440) we want to be able to run a validation cli tool against a single page to see if it passes 

Here is a page that explains what the validation tool does: https://www.ampproject.org/docs/fundamentals/validate 

**Describe the solution you'd like**
To have an `npm` script in the `package.json` file that runs the `amphtml-validator` cli tool against *a single article*, e.g. `/article/amp/scenario-01`.  The output should be displayed in the console. This validation does not need to be run on CI at this point. This will be handled in a future issue. 

https://www.ampproject.org/docs/fundamentals/validate#command-line-tool

If there are any errors listed in the output, a separate issue should be opened to create an AMP-compliant component & container that addresses those points.

**Describe alternatives you've considered**
Since this is the recommended way to validate AMP pages, other options were not considered.

**Comment by chris-hinds** [comment]
Is the idea here to just make sure one does not break the AMP validation when making local changes? If so then this will be fine. We have been using the AMP validator for our current AMP setup since the initial launch and have not experienced any issues.

**Comment by sareh** [comment]
The aim in this specific Issue is to make the AMP validation output visible. 
If run against a scenario with an image it *will* show errors, since we aren't using `<amp-img>` yet. 
The aim is here to use the AMP validate in a way to have Test-Driven-Development of a sort - first there will be errors, then we will create Issues to address those errors (e.g. create an Image component that is AMP-compatible) then that'll make the amp-validate script no longer error. 
Once we have addressed all the errors, we can then put this `amp-validate` as part of the CI process so that any future changes will fail the build unless addressed.

**Comment by chris-hinds** [comment]
Ahhh I see, makes perfect sense to me in that case. :)

**Comment by sareh** [comment]
Resolved as fixed, in #492.
