### ISSUE TITLE
AMP validation for all scenarios

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#442]
**Is your feature request related to a problem? Please describe.**
After steps https://github.com/bbc/simorgh/issues/440 (creating amp routes) and https://github.com/bbc/simorgh/issues/441 (validating a single scenario) have been completed, we want to run the AMP validation script against all article scenarios. 

**Describe the solution you'd like**
Update the amp validation npm script to run against all of the article scenarios and output their results in the console. 

If there are any errors listed in the output, a separate issue should be opened to create an AMP-compliant component & container that addresses those points.

**Additional context**
See instructions here https://www.ampproject.org/docs/fundamentals/validate#command-line-tool and here https://www.npmjs.com/package/amphtml-validator

**Comment by chris-hinds** [comment]
Same question as #441 really, is to this run locally or on CI?

We have an AMP validator that runs on a Lambda and is validates every single published AMP article, posting to Slack with the error's (if there are any) if you are thinking of this as more of an end to end test maybe using the same validator setup we are now would be a good idea?

The current validator runs on both test and live.

**Comment by radiocontrolled** [comment]
Blocked pending https://github.com/BBC-News/simorgh/issues/873

@hindsc52 in the future when all the validation errors are sorted we will want to run this in CI but at present it would break CI.

**Comment by ChrisBAshton** [comment]
Related to #1122.

**Comment by jamesbhobbs** [comment]
I don't believe we need to validate every article, but this https://github.com/bbc/simorgh/issues/2220 is very valuable and quite similar.
