### ISSUE TITLE
Bump error on live radio AMP pages

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4457]
**Describe the bug**
```
SON Error: ECHO_DEBUG: AssertionFailed: appType should be one of Enums.ApplicationType, got "amp"
    at Object.error (echo-12.5.0.min.js:7)
    at u (echo-12.5.0.min.js:7)
    at Object.assertContainsValue (echo-12.5.0.min.js:7)
    at new v (echo-12.5.0.min.js:15)
    at t.initComplete (bump-4.js:6)
    at i (bump-4.js:6)
    at Object.execCb (amp:52)
    at e.check (amp:52)
    at e.<anonymous> (amp:52)
    at amp:52
```

**To Reproduce**

1. Go to `npm run build && npm run start`
2. Visit http://localhost:7080/korean/bbc_korean_radio/liveradio.amp
3. Open console
4. Play the audio
5. See error

**Expected behavior**
Should not produce errors in the console. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/67755659-6a482d00-fa30-11e9-8f3f-bca506eb3ca2.png)

**Testing notes**
Follow the above steps confirm no console errors are produced.

- [x] This bug fix is expected to need manual testing.

**Additional context**
This is likely due to us passing `appType` as `'amp'` and this not being a valid value in SMP for the field `appType`

**Comment by aeroplanejane** [comment]
This issue appears to be resolved. @LilyL0u @ryanmccombe can you confirm? 
<img width="522" alt="Screenshot 2019-12-03 at 12 08 39" src="https://user-images.githubusercontent.com/22519682/70049938-be14db80-15c5-11ea-9961-433d5e41f09e.png">

**Comment by LilyL0u** [comment]
I no longer get the appType/amp error, but I do get a different one shown in the screenshot below:

![Image 03-12-2019 at 14 15](https://user-images.githubusercontent.com/54575620/70058821-8747c100-15d7-11ea-82ef-18cb53b7a196.jpg)

**Comment by ryanmccombe** [comment]
Had seen that one previously too - seems to happen on all media players in simorgh, but doesn't have any impact - would be nice to investigate if we get the chance though
