### ISSUE TITLE
[Test] Check Japanese ATI variables are sent to NEWS_LANGUAGES_GNL

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#4458]
Currently we con't have access to NEWS_LANGUAGES_GNL so I could not check that Japanese test MAP is sending ATI values correctly.

1. Get access
2. Check custom variables are captured in ATI Explorer

The following variables are being captured in ATI for each site:

Content ID (e.g urn:bbc:ares::asset:korean/media-23248686)
App type (e.g responsive)
App name (e.g news-korean)
Language (e.g ko)
URL (e.g https://www.test.bbc.com/korean/media-23248686)
Content type (e.g article-media-asset)
Page title (e.g 협상이 진행 중"이라며 "이것이 입법 절차이고, 이것은 가는 바늘에 실을 꿰는 것"이라고 덧붙였다) BUG linked #4374
Publication date (e.g 2019-09-13T15:11:13.000Z)
Update Date (e.g 2019-09-13T15:11:14.000Z)
Campaign (e.g Amuse Me)
Category (e.g News)

**Comment by LilyL0u** [comment]
@aeroplanejane do you know who I can ask to get access to NEWS_LANGUAGES_GNL?

**Comment by aeroplanejane** [comment]
@LilyL0u would you like me to validate this?

**Comment by LilyL0u** [comment]
@aeroplanejane It all looks good for me except the duration being 6 seconds in ATI tag inspector when the video is 5 seconds. I'll ask an SMP person.

**Comment by aeroplanejane** [comment]
Hmm - I wonder is this happening specifically for Japanese? Or is it across the board? I just tried on this page: https://www.test.bbc.com/pidgin/23248703 and it looks like rich media is not capturing duration?

**Comment by LilyL0u** [comment]
@aeroplanejane I think it's not captured in ATI explorer, so maybe this doesn't matter. It is in the tag inspector though, and the only worry would be if we want to capture the duration in ATI explorer in the future, or if it effects the average playback time, which is a metric in the explorer.

**Comment by aeroplanejane** [comment]
Ok - think in the context of this task we're happy that the same values are being captured in NEWS_LANGUAGES_GNL are the same as what we're capturing in WS_NEWS_LANGUAGES - but I need to verify re duration - I believe it is something we should be capturing

**Comment by LilyL0u** [comment]
@aeroplanejane Gavin asked Jim about the duration issue:
We are passing the value and it used to calculated playback metrics.

From Jim:
'The duration of that is 5.8s - the UX always floors the seconds when displaying, I can't really remember the motivation, but it's common among media players.
ATI however just rounds to the nearest, however in general durations are pretty unreliable going into ATI, as we can't update the duration in it, and they do change - or at least they become more accurate, particularly with some of the mp3 and mp4 players on old progressive who don't get the metadata but guess the duration.'

So it's ok :)
