### ISSUE TITLE
Remove Simorgh Stories for Moment Locales

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#4463]
**Is your feature request related to a problem? Please describe.**
As a result of the Simorgh Seniors meeting, we discussed removing the Moment Locales stories from Simorgh's storybook, since there is visibility at the Psammead level. e.g. https://bbc.github.io/psammead/?path=/story/utilities-psammead-locales--moment-afaan-oromoo-om

**Describe the solution you'd like**
Remove the Simorgh stories `Moment Locales/ Editorial view & Developer view`

**Describe alternatives you've considered**
We could keep these in Simorgh and just remove the Chromatic QA snapshot testing, with this: ` chromatic: { disable: true },` as in https://github.com/bbc/psammead/issues/2526

We should check with UX/Product to ask whether they use these values:
Developer view example
<img width="723" alt="Screenshot " src="https://user-images.githubusercontent.com/3028997/67785708-929e4e80-fa65-11e9-85b1-9ad5074679d8.png">
Editorial view example
<img width="485" alt="Screenshot " src="https://user-images.githubusercontent.com/3028997/67785709-929e4e80-fa65-11e9-80ab-08378fd37bfc.png">

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
FYI product has recently asked to add all the services to those stories as they need to be able to view the output of all days, dates, months and formats from moment, so they can check the output with the editorial teams. The editorial view is so editorial only focus on what we are planning (currently) to show on the site.

I think we will have to remove the Chromatic QA snapshot testing instead.
