### ISSUE TITLE
Investigate Lazy Loading Images

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#448]
**Is your feature request related to a problem? Please describe.**
Investigate how we can effectively add lazy-loading functionality to our images.

**Describe the solution you'd like**
Come up with a list of 2 or more libraries/solutions to lazy loading, stating which one is the preferred solution and why.

Example libraries:
- https://github.com/jasonslyvia/react-lazyload

**Additional context**
Ensure this follows the same level of browser support as documented in https://jira.dev.bbc.co.uk/browse/NEWSART-557

**Comment by jp-bbc** [comment]
Introduction

Lazy loading is a method of executing a block of code based on a condition being met. It’s primary benefit is to optimise the performance of large web applications and to enhance the user experience (UX) through which it brings. In the context of lazy loading images, assets are dynamically loaded into the DOM, enhancing initial responses requested by the client. There are a few libraries supported by React that facilitates this functionality out of the box, that is both intuitive, requiring minimal maintenance overhead.

Option 1 (react-lazyload)

‘react-lazyload’ is a lightweight third party React library that dynamically loads image assets. It is available on npm or yarn. Technically, image assets are loaded through specifying the offset attribute, based on the position of the ‘x’ co-ordinate of the viewport. Loading images in this manner improves the user experience through loading and displaying images just before the user views it. However, if the offset value is too large, the benefits of the library are negated. Additionally, components can also be lazy loaded, which is defined by creating a rule inside the component file.

Sources:
- https://github.com/loktar00/react-lazy-load
- https://javascriptreport.com/four-libraries-to-improve-the-performance-of-your-react-app/

Option 2 (react-lazy-load-image-component)

‘react-lazy-load-image-component’ is another third party React library, that also dynamically loads images and other components/elements. It is available on npm and yarn. It includes a Higher-Order Components technique, to track window scroll position to improve performance.

The library includes two components (LazyLoadImage and LazyLoadComponent) and a HOC (trackWindowScroll) which adds scroll position tracking to any component. It handles scroll events, resize events and re-renders that might change the position of the components, and above-the-fold on initial render. Placeholder support is also provided, including custom placeholders.

There are several effects which are provided out-of-the-box. However they are optional and rely on CSS and the corresponding file being imported. Effects include blur, black-and-white and opacity.

Sources:
- https://www.npmjs.com/package/react-lazy-load-image-component
- https://medium.com/@aljullu/an-easy-to-use-performant-solution-to-lazy-load-images-in-react-e6752071020c

Pro’s (react-lazyload)

- It’s lightweight and fast - 6KB minified
- It’s easy to use
- It provides lazy loading out of the box
- It can also lazy load components

Cons (react-lazyload)

- It’s less flexible
- It has no effects
- It may handle groups of images less well without HOC technique

Pros (react-lazy-load-image-component)

- Very adaptable
- Very comprehensive - offers more than lazy loading image assets
- Has effects to enhance UX
- Can display images already lazy-loaded on the same page from the browser’s cache using visibleByDefault prop
- Can group elements when more than one is listening to scroll/resize events, which can reduce performance

Con’s (react-lazy-load-image-component)

- It’s larger (18KB)

Consensus

Through comparing both lazy loading libraries, it is clear that both offer different features. In the case of Simorgh, the web application is dependent upon libraries which are lean and offer performance at scale. While react-lazy-load-image-component provides caching capabilities through HOC technique and offers a range of customisable features, considering Simorgh’s performance needs, react-lazyload seems to be the most appropriate library of choice. While it has less customisable features as it’s counterpart offering, it provides the performance and UX requirements for this project, with the added flexibility of lazy loading components if needed. This recommendation however, is at the discretion of others in the team.

**Comment by BogdanDogaru** [comment]
@jp-bbc this is good work!

Following this, can you pick up #520 and build two PoCs, starting with option 1?

**Comment by PaulChinkwende** [comment]
*Lazy Loading Images [POCs]* 

Currently our unit test fail because they are looking for images which are not currently in the DOM.

Will we only be lazy loading images ? What about other components ?

Do we have any post-load requirements yet e.g timings, heights 

Will we have a placeholder image ?

*Current Results* 

React-lazyload has bee much quicker and simpler to implement into our current code.
Works well.
 Uses <LazyLoad > html tag which can encompass our image tag allowing us to use our current styled image component.
Can specify when to reload image.


(react-lazy-load-image-component) -

<LazyLoadImage replaces image constant. 
however, can not overwrite constant as it causes a duplication issue - how will be style it ? 
 currently returns an empty JSON object when we run our dev environment and try to access an article. We suspect this is because there is no image constant.
If you dont find image - return empty object ??

**Comment by BogdanDogaru** [comment]
We're using `react-lazy-load` in #673. This can be closed.
