### ISSUE TITLE
Documentation: Guidelines for automated testing

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#4487]
**Is your feature request related to a problem? Please describe.**

Simorgh's `CONTRIBUTING.md` file has the following section on writing tests:

> For new components, we write Jest Snapshot tests, with a deep render, using the `shouldMatchSnapshot` test utility function.
>
> For new containers, we write Jest Snapshot tests with a shallow render, using the `shouldShallowMatchSnapshot` test utility function. We also write assertion-based enzyme tests to capture variations in prop values. [See the Article `getInitialProps` tests here as an example.](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Article/index.test.jsx)

This is outdated. After discussions at the Simorgh seniors' conference, it was established that explicit assertion tests are now preferred for components, with a deep rendered snapshot to provide a cheap second level of test to check for accidental changes to component structure outside of these assertions.

From the notes of this discussion:

> **Snapshots**
> - snapshots for containers were changed to be deep rendered, instead of shallow rendered. This is since we are using Contexts (ServiceContext, etc.) and shallow rendering would just surface the context rather than the containers. Deep snapshots check the behaviour, rather than implementation. 
> - Shallow snapshots test implementation - so we don’t use them.
> 
> **Assertion testing**
> - These tests are self-documenting, which is a benefit to developers maintaining the component. 
> - This testing is more granular.

We need to update the guidelines for writing automated tests to:
- Justify why we favour assertion tests
- When to write unit/integration tests and when to e2e test - base this on the outcome of https://github.com/bbc/simorgh/issues/4486
- Add a dom structure component as an example, e.g. nav - explain what assertions we would make and what a snapshot would provide

**Comment by joshcoventry** [comment]
We now have a whole document which explains our testing strategy: https://github.com/bbc/simorgh/blob/latest/docs/Test-Strategy-Info.md
