### ISSUE TITLE
Remove use of Enzyme

### ISSUE THREAD

**Issue by mykeels** [bbc/simorgh#4491]
We currently have 3 test renderers in Simorgh - `react-test-renderer`, `@testing-library/react`, and `enzyme`.

Following https://github.com/bbc/psammead/issues/774, which aims at removing `react-test-renderer`, we should remove `enzyme` from our tests, and depend only on `@testing-library/react`.

## Solution
Remove `enzyme` and all use of it. Refactor shallow render tests because `@testing-library/react` does not have or encourage shallow rendering.

---

Some of the benefits of using `@testing-library/react` include:
 - encourages better testing practices and writing more maintainable tests 
 - is designed to enable and encourage writing tests that use components as the end users use them
 - it supports querying for elements in ways that encourage accessibility in components

Find out more about [@testing-library/react](https://testing-library.com/docs/react-testing-library/intro).

This article briefly describes and compares React test renders https://codeburst.io/revisiting-react-testing-in-2019-ee72bb5346f4

Here is more on why [`@testing-library/react` doesn't do shallow rendering](https://kentcdodds.com/blog/why-i-never-use-shallow-rendering).

**Comment by dr3** [comment]
We need Enzyme to render noscript tags :( AFAIK we dont have an alternative, other than maybe ReactDOM

**Comment by mykeels** [comment]
Perhaps an additional test helper function, that makes use of ReactDOM?
