### ISSUE TITLE
Integrate Top, Regular and Leading story promos in the new Frontpage layout

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#4500]
**Is your feature request related to a problem? Please describe.**
Once the new Grid is included in Simorgh, we should integrate the Top, Regular and Leading story promos to build the new Frontpages layout.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [X] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Closing this issue in favour of the main frontpage layout issue (https://github.com/bbc/simorgh/issues/4562) and PR (https://github.com/bbc/simorgh/pull/5139) in which it is covered.
