### ISSUE TITLE
Accessibility Swarm on the new Frontpage layout

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#4501]
**Is your feature request related to a problem? Please describe.**
We should a11y test the Leading and regular story promos once we integrate them in Simorgh to build the new Frontpages layout.

**Describe the solution you'd like**
 Go through the accessibility checklist and fix any issue we might face.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
Blocked on https://github.com/bbc/simorgh/issues/4500

**Comment by DenisHdz** [comment]
Unblocked on https://github.com/bbc/simorgh/pull/5139

**Comment by sareh** [comment]
Closed as complete!
