### ISSUE TITLE
Handle AV embed timeout on client

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#4517]
**Is your feature request related to a problem? Please describe.**
- Arises from https://github.com/bbc/simorgh-infrastructure/issues/597
- Relates to https://github.com/bbc/simorgh-infrastructure/issues/748

If an AV embed iframe fails to load at all (e.g. due to network timeout) the user may experience unpredictable results and not realise what has happened.

**Describe the solution you'd like**
We should handle timeouts and other client-side errors relating to AV embeds by showing a custom error message, ideally the same one used by https://github.com/bbc/simorgh-infrastructure/issues/748

Note that this issue does not cover timeouts that occur once the player has loaded, as these are handled by SMP.

Some options for how to do this are discussed on the investigation ticket linked above.

**Describe alternatives you've considered**

**Testing notes**
 - Test with cross-browser and cross-device by throttling the network connection.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
Check with AMP as well.

**Comment by 12** [comment]
I believe that with AMP, if an `iframe` fails to load, the end user will continue to just see the media player placeholder.

According to the [`amp-iframe` docs](https://amp.dev/documentation/components/amp-iframe/#iframe-with-placeholder):

> The amp-iframe must contain an element with the placeholder attribute, (for instance an amp-img element) which would be rendered as a placeholder until the iframe is ready to be displayed.
