### ISSUE TITLE
Text followed by another text block

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#452]
**Is your feature request related to a problem? Please describe.**
Text followed by another text block should have a certain treatment.

**Describe the solution you'd like**
We should insert a `hr` element in between text blocks. This `hr` element should have the following styles:
  - colour: #B80000
  - height: 4px;
  - width: 48px;
  - padding: 16px 0;

This is in addition to the 16px padding-bottom on the bottom of the text block.

These styles will apply across all breakpoints.
<img width="397" alt="screen shot of the red bar" src="https://user-images.githubusercontent.com/3028997/43957179-d02f1d54-9c9e-11e8-82ec-c5e588ed2d9b.png">

**Implementation notes**
Add a component for the HorizontalRule
Add a story to StoryBook which has a text block, a HorizontalRule and another text block.

**Comment by BogdanDogaru** [comment]
This is blocked by:
    - Fixing the bug where each we can override data sources (https://github.com/bbc/simorgh/issues/478)
    - Adding context so we know what other blocks have been rendered

**Comment by pjlee11** [comment]
Only blocked by "fixing the bug where each we can override data sources (#478)" if this requires cypress tests. Alternatively we could create a seperate issue for cypress tests and this is then only blocked by finding a way to have context of which blocks are rendered next to each other

**Comment by jtart** [comment]
We will integrate the HorizontalRule component to the Text component with #614, which unblocks this ticket as tests can be added there.
