### ISSUE TITLE
Text super/sub script support

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#454]
**Is your feature request related to a problem? Please describe.**
We should be able to render super/sub scripts in text.

**Describe the solution you'd like**
Use the same solution as in https://github.com/bbc/simorgh/issues/402.

**Additional Context**
Dependent on https://github.com/bbc/simorgh/issues/402.

The styles for `sub` and `sup` are already in the Normalize file, which we have imported globally. So the styling should 'just work'. 

```
sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}
sub {
  bottom: -0.25em;
}
```

**Comment by sareh** [comment]
Blocked until have clearer idea of what super/sub scripts will look like in passed data.

**Comment by jtart** [comment]
@BogdanDogaru @katikaa do we have an idea `what super/sub scripts will look like in passed data` yet?

**Comment by jtart** [comment]
Covered by https://github.com/BBC-News/simorgh/issues/402.
