### ISSUE TITLE
Desktop safari reader view is, ermm....... borked!

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4553]
**Describe the bug**
When viewing a Simorgh front page in Desktop safari and activating reader mode `cmd + shift + r` it looses all content on the page.

**To Reproduce**

1. Go to 'bbc.com/igbo'
2. turn on reader mode 'cmd + shift + r'
3. See error

**Expected behavior**
To see a cut down version of the front page

**Screenshots**
 
![image](https://user-images.githubusercontent.com/14273378/68138925-32a21f00-ff21-11e9-9917-c0b36a55d3ee.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Safari
- Version: 13.0.2

**Testing notes**

- [X] This bug fix is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
We may simply decide to not fix this, I am not sure on the stats for people using reader view on a desktop, however thought it worth reporting anyway.

**Comment by DenisHdz** [comment]
This works fine on articles, but we won't be looking at making it work on Front Pages as the content is not long enough.
