### ISSUE TITLE
Accessibility swarm on the Navigation component

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#4569]
**Is your feature request related to a problem? Please describe.**
Carry out a `team` accessibility swarm for the new version of the Navigation component once it is completed.

This could be done when integrating the alpha component locally in Simorgh.

**Describe the solution you'd like**
Go through the [accessibility checklist](https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers) and fix any issue we might face.

**Describe alternatives you've considered**

**Testing notes**
Ensure the visually hidden text is read out for translated text on the navigation dropdown menu, as specified in https://github.com/bbc/simorgh/issues/4890

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
This can be closed now as no P1 bugs have been found.
