### ISSUE TITLE
Change hardcoded chartbeat referrer value

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#4573]
**Is your feature request related to a problem? Please describe.**
We set the `virtualReferrer` to use a [hardcoded value](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js#L98) previously, this was done to isolate and highlight the issues with chartbeat's implementation of using `virtualReferrerr` in `virtualPage` calls.
Now that Chartbeat support has fixed that, we need to make use of our original value of the `virtualReferrer` in the canonical config.

**Describe the solution you'd like**
- Change the value [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js#L98) to use [`referrer`](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js#L80)
- Test how this works with clicking back and inline-links, note behavior and create issues to fix if any

**Describe alternatives you've considered**

**Testing notes**
- Refer to https://github.com/bbc/simorgh/issues/3368 for original bug issue and requirements that gave rise to these changes
- https://github.com/bbc/simorgh/issues/3977 should also be re-tested to see if the issue persists

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

- To work with chartbeat locally [the toggle](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/toggles/index.js#L4) needs to be enabled
- the `previousPath` value needs to be passed as an argument into this [hook](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/index.jsx#L30) as it's done [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/index.jsx#L57)

**Comment by jroebu14** [comment]
@jimjohnsonrollings what is the expected behaviour of the referrer value when we make this change?

**Comment by jimjohnsonrollings** [comment]
@jroebu14 

The expected behaviour is that the `v` field in the Chartbeat call contains the URL of the page which referred the user to the current page.

The specific case that wasn't working previously was if the user used the back button.

In the case that the user visits Page A, then Page B, then Page C, then clicks back to go to Page B again, we expect the final referrer value to be Page A (because it was Page A that referred the user to Page B), however we were previously seeing Page C in this field.

**Comment by jroebu14** [comment]
@jimjohnsonrollings thanks for the detailed explanation.

**Comment by andrewscfc** [comment]
@jimjohnsonrollings I have completed the below test on a fix on my local machine, could just confirm that it matches the scenario you described above. It seems to work as expected :) 

Testing Notes:
- Visit http://localhost:8080/chartbeat-test.html (Page A) a statically hosted file containing a link to http://localhost:7080/news/articles/c6v11qzyv8po (Page B)
- Click the link on the static page, navigating to http://localhost:7080/news/articles/c6v11qzyv8po (Page B)
  - v: http://localhost:8080/chartbeat-test.html, as expected
- Click link to http://localhost:7080/news/articles/c0g992jmmkko (Page C)
  - v: /news/articles/c6v11qzyv8po, as expected
- Press back returning to http://localhost:7080/news/articles/c6v11qzyv8po (Page B) 
  - v: http://localhost:8080/chartbeat-test.html, as expected
