### ISSUE TITLE
Add Fixture data for Most Read for all services. 

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#4574]
**Is your feature request related to a problem? Please describe.**
We should have local fixture data for Most Read, for each of the services. 

**Describe the solution you'd like**
We should have fixture data files with Most Read JSON data.  They should be in the files 
`/data/:service/mostRead/index.json`
or for services that have variants, like zhongwen, ukchina & serbian:
`/data/:service/mostRead/variantname.json`

Where to get the example data:
`https://ares-broker.api.bbci.co.uk/api/most/read/persian`
Note that the services with variants are at the endpoints of this format:
`https://ares-broker.api.bbci.co.uk/api/most/read/ukchina_trad`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: No tests are needed for this step. 

- [ ] This feature is expected to need manual testing.

**Additional context**
N/A

**Comment by thekp** [comment]
should i just skip over this service cymru, similarly with naidheachdan
?
no data for it
![image](https://user-images.githubusercontent.com/30599794/68319020-8cd3e900-00b5-11ea-84c2-3b5edb893baf.png)
![image](https://user-images.githubusercontent.com/30599794/68320077-3c5d8b00-00b7-11ea-9a16-b2515e0a112b.png)

**Comment by sareh** [comment]
@thekp Yes, skipping those services would be best.
