### ISSUE TITLE
Spike - Investigate how to build Frontpage desktop layout

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#4576]
**Is your feature request related to a problem? Please describe.**
We need one or two developers to investigate how to build the new desktop layout https://github.com/bbc/simorgh/issues/4562

**Describe the solution you'd like**
Build logic to display different layouts depending on the number of items in each section group. The layouts will use a different type of promos (Top, regular, regular without image and leading) and these will have to be wrapped within `Grid items` to indicate the number of columns they should take on the page.

**Describe alternatives you've considered**
N/A

**Testing notes**
Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Spike has been completed. Work has been carried out as part of these issues: https://github.com/bbc/simorgh/issues/4562 https://github.com/bbc/simorgh/issues/4500
