### ISSUE TITLE
Add cypress test to ensure component appears when guidance text is present

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#4580]
**Is your feature request related to a problem? Please describe.**
As a result of guidance text being added to media player in psammead in this issue https://github.com/bbc/simorgh/issues/3139 we need to add cypress tests to ensure the component renders when there is a guidance text.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by PriyaKR** [comment]
Blocked until the psammead media player in simorgh is bumped to version `2.2.0`

**Comment by rhenshaw56** [comment]
@PriyaKR this would be a duplicate of https://github.com/bbc/simorgh/issues/4253

**Comment by PriyaKR** [comment]
sorry my bad added in the corresponding PR.

**Comment by PriyaKR** [comment]
Closing as its a duplicate.
