### ISSUE TITLE
Puppeteer MAP page tests times out on CI regularly

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#4594]
**Describe the bug**
This puppeteer test fails on CI around 50% of the time:
```
puppeteer/rich-text-transforms.test.js (15.78s)

  ● rich-text-transforms JS bundle request › pidgin › only loads rich-text-transforms bundle after client navigation to MAP asset
```
It causes the Jenkins CI build to fail on almost half of all runs on PR commits. 

**To Reproduce**

1. Go to a PR with a Jenkins CI job that is failing (e.g. `/simorgh/detail/most-read-json/6/pipeline/27`)
2. Click on the job
3. See error

<img width="1308" alt="Screenshot error as puppeteer test fails" src="https://user-images.githubusercontent.com/3028997/68465843-22cd5800-020b-11ea-82b0-b622a6b70f8d.png">

**Expected behavior**
For this not to time out so frequently, we also need to re-enable the test once this has been fixed. (disabled in #4598 )

**Screenshots**
As above

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by jamesdonoh** [comment]
Test disabled in https://github.com/bbc/simorgh/pull/4598

**Comment by ryanmccombe** [comment]
Related: https://github.com/bbc/simorgh/issues/4758

**Comment by oluoluoxenfree** [comment]
Is this related? no suffix on the vendor bundles: 
<img width="914" alt="Screen Shot 2019-12-02 at 16 39 32" src="https://user-images.githubusercontent.com/3077443/69977406-a7697880-1522-11ea-98ee-7039d52b5285.png">
