### ISSUE TITLE
Only use client-side rendering if we are sure the device supports it

### ISSUE THREAD

**Issue by neildoughty** [bbc/simorgh#4634]
**Is your feature request related to a problem? Please describe.**
We should presume that user's device is low on memory and on a poor network. As such we should make server-side rendering the default option for all users, and kick in with SPA tech if we know the users' device can handle it. It's suggested we use Google's adaptive loading library to do the determination of a user's device.
https://github.com/GoogleChromeLabs/react-adaptive-hooks

**Describe the solution you'd like**
A simple experiment which can be tracked, to determine the impact of using server-side rendering by default, with client-side rendering kicking in for user's who can use it. Ideas for things to use - device memory, estimated network, etc
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory
https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/effectiveType
https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/saveData

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
>It's suggested we use Google's adaptive loading library to do the determination of a user's device.
https://github.com/GoogleChromeLabs/react-adaptive-hooks

Or use the principles from this library as this is effectively using standard browser API's.

**Comment by aeroplanejane** [comment]
Closing. Ref NEWSWORLDSERVICE-1419
