### ISSUE TITLE
Add Related Content to MAP

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4636]
**Is your feature request related to a problem? Please describe.**
Implement the "Related Content" list within the MAP / CPS Page

This corresponds with the PAL feature:

![image_preview](https://user-images.githubusercontent.com/8601460/68666370-b66c9480-053b-11ea-95b8-a9fdd0ac0886.png)

**Describe the solution you'd like**
Implement these designs: https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/dashboard?tag=Related%20Content

These designs can likely be achieved by existing components:

- https://bbc.github.io/psammead/?path=/story/components-sectionlabel--default
- https://bbc.github.io/psammead/?path=/story/components-storypromo-storypromolist--default
- https://bbc.github.io/psammead/?path=/story/components-storypromo-storypromo--default
- https://bbc.github.io/psammead/?path=/story/components-mediaindicator-video--video-with-duration

Data is available within the API response / `pageData` for each MAP - `relatedContent.groups[0].promos`

Translations for "related content" should be available within the service config - `default.translations.relatedContent`

Recommended steps for implementation:
- Create a new container within Simorgh that receives the CPS Promo data, and outputs the promo list using psammead components
- Update the CPS page to add an additional column to the grid, and insert this new container into it

**Describe alternatives you've considered**
Other designs considered, but went with this for initial iteration, as it does not require any new presentational components

**Testing notes**
[Tester to complete]

Dev insight: Full suite of automated tests for new features - Jest + Cypress.  Manual testing / UX review for a range of CPS assets.  Okay to merge this as page is not live yet, and being on test server makes review easier

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
Implemented this:

![Screen Shot 2019-11-14 at 15 56 44](https://user-images.githubusercontent.com/8601460/68874675-866af000-06f9-11ea-88c6-d1e608987f54.png)

Three known issues at this point:

- Translations for "related content" are only available for about half the services - created issue: https://github.com/bbc/simorgh/issues/4681
- We do not currently support related content without an image - for now, those assets just will not appear in the list.  I'm not too sure why there would be assets without images, but if that is a requirement, I suggest we do it in a later iteration, as it would need some changes to the existing psammead components
- The line between promos is much lighter in the component that in the design - this can be addressed by an update to the component if needed

**Comment by aeroplanejane** [comment]
This has been merged. UX have signed off and product have signed off. Closing this issue
