### ISSUE TITLE
Ditch HOCs for Hooks or render prop components

### ISSUE THREAD

**Issue by mykeels** [bbc/simorgh#4640]
**Is your feature request related to a problem? Please describe.**
Based on https://github.com/bbc/simorgh/pull/4567#discussion_r344096703, because of HOCs, we get snapshots like:

```
<div id="VariantContainer">
  <div id="PageWrapperContainer"
    ...
  </div>
</div>
```

**Describe the solution you'd like**
Ditching HOCs like WithVariant, for hooks like `useVariant`,  or render prop components.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
@mykeels could you provide a bit of an example on how we can replace these HOC's with hooks even in pseudo code will be useful.
