### ISSUE TITLE
Unable to run UK and non-UK tests against prod in UK

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#4651]
**Describe the bug**
Our [README says to use `CYPRESS_UK`](https://github.com/bbc/simorgh#running-e2e-in-the-uk-against-live) when running tests in the UK against test/live environments.

However this seems to not work correctly depending on the service being tested.

**To Reproduce**
Note: this affects many tests, the below is just given as one example.

Running the tests locally from inside the UK against test this passes:
```shell
$ CYPRESS_APP_ENV=test CYPRESS_SMOKE=false CYPRESS_ONLY_SERVICE=scotland CYPRESS_UK=true npx cypress run --spec cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
```
however without `CYPRESS_UK` set it fails.

Conversely, this passes:
```shell
$ CYPRESS_APP_ENV=test CYPRESS_SMOKE=false CYPRESS_ONLY_SERVICE=tamil npx cypress run --spec cypress/integration/specialFeatures/cookieBanner/testsForAMPOnly.js
```
however with `CYPRESS_UK` set it fails.

**Expected behavior**
It should be possible to get the entire (SMOKE=false) test suite to pass in the UK.

**Additional context**
The relevant README section should be reviewed/updated as part of this work.

**Comment by oluoluoxenfree** [comment]
@jamesdonoh Would it be okay to try this solution? https://docs.cypress.io/guides/guides/web-security.html#Disabling-Web-Security

currently researching if there are other implications of turning it off.

**Comment by oluoluoxenfree** [comment]
The above has already been implemented.

**Comment by PriyaKR** [comment]
@jamesdonoh By default cypress tests will run as if they were ran outside of the uk as the cypress variable `CYPRESS_UK` is set to default.If i remember correctly this variable `CYPRESS_UK` was added to fix the cypress failing locally because of cross domain issues.

Currently cypress doesnt support visiting multiple domains in one test https://github.com/cypress-io/cypress/issues/3985

Few tests are failing because in the same test we are trying to fetch another domain.

Also this issue was being avoided by using`cy.request` instead of `cy.visit` in most of the tests as cypress request command doesn't throw cross domain issues.But i see in case of amp tests apart from making a `cy.request`  before each test is run there is `cy.visit` being called within the test which causes the tests to fail.Might try replacing them with request instead of visit and see if the tests passes.

**Comment by PriyaKR** [comment]
I have tried running all the tests on my machine against test and live environments without passing  any value to `CYPRESS_UK` as default its set to false and all the tests passes no cross origin issues one or two issues failed which are not related to whether `CYPRESS_UK` is set or not.If you wanna run the tests as if they are run from uk then you need to set `CYPRESS_UK`=true but you will see cross domain issues.

Will there be any use cases where you have to run locally against test env setting `CYPRESS_UK=true`?

**Comment by PriyaKR** [comment]
The issues which i noticed irrespective of `CYPRESS_UK` set to true or false

- Cypress timeout issue on article amp page especially the metadata test refer screenshot issue1
- Cypress timeout issue on front page amp page especially the metadata test refer screenshot issue2
- Media asset test failing especially for amp page refer screenshot issue 3
- Timeout issue on canonical cookie banner test refer screenshot issue 4
- Cross domain issue with cookie banner tests for canonical and amp pages fails only for news and scotland articles page refer screenshot issue5.1 and issue 5.2
![issue 1](https://user-images.githubusercontent.com/9802855/71246340-5b824600-230e-11ea-8af7-791e73fbc911.png)
![issue2](https://user-images.githubusercontent.com/9802855/71246348-5f15cd00-230e-11ea-8caa-c4a7702c136f.png)
![issue 3](https://user-images.githubusercontent.com/9802855/71246356-62a95400-230e-11ea-89be-4941d27dba90.png)
![issue 4](https://user-images.githubusercontent.com/9802855/71246362-65a44480-230e-11ea-9c3e-c96f2adeddfb.png)
![issue5 1](https://user-images.githubusercontent.com/9802855/71246365-689f3500-230e-11ea-8647-3f9ed025b5b0.png)
![issue5 2](https://user-images.githubusercontent.com/9802855/71246372-6ccb5280-230e-11ea-81be-e9614ab6a3a2.png)

**Comment by PriyaKR** [comment]
The above issues needs to be fixed before we fix the env var `CYPRESS_ENV` issue.
