### ISSUE TITLE
Image caption indented at smaller screen sizes

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#4652]
**Describe the bug**
Image captions are appearing indented at screen sizes between 376px and 599px.

**To Reproduce**

1. Go to https://www.test.bbc.com/afaanoromoo/articles/cd8pz3kxwqgo
2. Toggle to a screen size between 376px and 599px 
3. Scroll down to image

**Expected behavior**
Image caption should be aligned with the edge of the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/52247014/68773257-23a72500-0623-11ea-95f6-3ed73de3284e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
This can be fixed by removing the padding left & right from the `psammead-caption` component and instead adding it on the Grid, being introduced in this PR: https://github.com/bbc/simorgh/pull/4493
