### ISSUE TITLE
Implement schema.org structured data for AV 

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#4664]
**Is your feature request related to a problem? Please describe.**
Following  the investigation on #4566 we would need to implement schema.org for video and audio-specific content in a attempt to make the metadata of these pages richer.

**Describe the solution you'd like**
Implement as per the findings [here](https://github.com/bbc/simorgh/issues/4566#issuecomment-553598074) using the updated table to plug in values for various properties.

Video/Audio object detail:

Name | Example value | Where does this come from?
-- | -- | --
@context | `http://schema.org`
type | VideoObject/AudioObject |  
name | "This is the title of the video" | model.versions[0].title
description | "This is the description of the video." | API?
thumbnailUrl | https://ichef.bbci.co.uk/images/ic/$recipe/p0715z8q.jpg |  
uploadDate | 2019-10-10T09:00:00+08:00 |  
duration | PT2M21S | model.versions[0].durationISO8601
contentURL |   | Player link/file location (based on player, we can only use the embed point)
embedURL | externalEmbedUrl":"https:\/\/www.bbc.co.uk\/news\/av\/embed\/p07t1hp1\/50299906 | 

**NOTICE**
Once a draft PR has been created, please make sure this has been shared with the Media pod as early as possible to get their feedback/code reviews.

**Testing notes**
- Test to work with Business Analyst using Google Analytics tool to make sure implementation is correct
- Google Analytics Tool: https://search.google.com/structured-data/testing-tool#

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
- [Google structured data testing tool](https://search.google.com/structured-data/testing-tool#url=) should be used to validate the  of schema.org metadata.

**Comment by aeroplanejane** [comment]
@aeroplanejane @ryanmccombe @pharingee we want to start work schema this so we're going to track this issue
