### ISSUE TITLE
Add / Validate Translations for MAP v1 Services

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4681]
**Is your feature request related to a problem? Please describe.**
Add required translations for our v1 services:

- pidgin 
- Igbo 
- Yoruba 

- Thai
- Punjabi 
- Afaan Oromoo
- Amharic
- Tigrinya
- Korean 
- Marathi
- Telugu
- Gujarati

**Describe the solution you'd like**
We need to ensure we have the correct translations for these services : 

- Cookie Banner 
- Privacy Banner 
- Footer 
- Timestamps 
- Related Content Header 

Please refer to the translations spreadsheet - pinned in the media pod channel 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Should we add cypress tests to all services for this?

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
@ryanmccombe if you can show me where these configs are stored in Simorgh then I can validate

**Comment by aeroplanejane** [comment]
Nm - there's another issue for related content! This has been done for our first 5 services but I won't be tracking this through github

**Comment by ryanmccombe** [comment]
Only assigned it to you because it was moved into in progress

If the translations are in the spreadsheet, we still need to move them into Simorgh - that's what this issue was for

**Comment by ryanmccombe** [comment]
These seem good to me as they are - ready for testing

https://docs.google.com/spreadsheets/d/1blHrKE_CGnEKuCqj7pqR-rylUIVbxgkl64f5LEHv6LE/edit#gid=0

**Comment by LilyL0u** [comment]
Pidgin link 'Why you fit trust BBC News' shoud go to https://www.bbc.com/pidgin/institutional-48528766 (in Pidgin language), but actually goes to https://www.bbc.co.uk/news/help-41670342 (in English Language).

This is also happening with Igbo and Yoruba.

**Comment by LilyL0u** [comment]
If the URL is bbc.com/pidgin/
Then if I add /media-511121201 to the end, which is a non-existent page (just changed the last number), should that have the Pidgin 404 error translations? Currently when I do that, it is in english as below:

![Image 17-01-2020 at 11 28](https://user-images.githubusercontent.com/54575620/72609501-fd507f00-391c-11ea-8662-3c6b0d21cb62.jpg)

This is also happening with igbo.

**Comment by ryanmccombe** [comment]
This seems to be an issue with the routing refactor - not with the translations.

Translations are there, but the request isn't reaching Simorgh - it's just hitting a Mozart error page that is using Simorgh's design

Conversation in Mozart's slack: https://bbcnews.slack.com/archives/C2BU2N4TH/p1579279652055500

**Comment by LilyL0u** [comment]
Yoruba - cookie banner and privacy banner in English

**Comment by LilyL0u** [comment]
Will test Thai, Punjabi, Afaan Oromoo, Amharic, Tigrinya, Marathi, Telugu, Gujarati when they are on test
