### ISSUE TITLE
[TEST ONLY] Title Tag and Essential Page Metadata to enable Search Discoverability 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4706]
**Is your feature request related to a problem? Please describe.**
Include SEO focused metadata such as:
- Title Tag
- H1/Heading
- Crosshead
- <body> (existing editorial paragraphs)
- Internal linking structures within <body>

**Describe the solution you'd like**
We need to ensure that the title tag is the full headline from CPS e.g the full headline on the MAP page 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Can be tested using - https://search.google.com/structured-data/testing-tool

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
We suspect this was done as part of the initial page scaffolding - just needs verification

**Comment by aeroplanejane** [comment]
Verified for our services using: https://chrome.google.com/webstore/detail/meta-seo-inspector/ibkclpciafdglkjkcibmohobjkcfkaef?hl=en
