### ISSUE TITLE
videoObject & audioObject - Search engine can distinguish video & audio on the page

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4707]
**Is your feature request related to a problem? Please describe.**
Implement the videoObject so search can identify the page has video content. 

See example of the  Schema > https://schema.org/VideoObject with implementation improving on competitor markup

Articles are working on the schema, but we need to ensure we pass the following props to the videoObject & audioObject: 
   
 type    
Name    
description    
duration    
thumbnailUrl    
uploadDate
embedURL

Requirements found on confluence here - WSMEDIA/MAP+%7C+SEO All values are provided through the ARES feed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
Can be tested through https://search.google.com/structured-data/testing-tool

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by gavinspence** [comment]
Blocked on https://github.com/bbc/simorgh/issues/4664

**Comment by pharingee** [comment]
I'm taking out contentURL from the issue description since SMP doesn't give access to an actual file.

**Comment by pharingee** [comment]
Work has been completed by the articles team
