### ISSUE TITLE
MAP - Use Video Poster Image in Metadata

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4708]
**Is your feature request related to a problem? Please describe.**
We swill use the video poster image in the MAP page metadata.

This will help give users more context / make the pages more appealing when linked in social media.

The pages currently use the default brand image:

![Screen Shot 2019-11-18 at 12 23 30](https://user-images.githubusercontent.com/8601460/69052169-3db77d80-09fe-11ea-9db9-fa0ba6467c9e.png)

This can be applied across all CPS pages. 

**Describe the solution you'd like**
Ensure the MAP poster image is used in the `og:image` metadata 

There are recommendations around the size of this image: https://developers.facebook.com/docs/sharing/webmasters/images/ 

Where a poster image doesn't exist use the default image / logo for the page. 

**Describe alternatives you've considered**

**Testing notes**
We can test opengraph data using this tool: https://developers.facebook.com/tools/debug/
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Duplicated
