### ISSUE TITLE
Footer - fallback to PNG if browser does not support SVG

### ISSUE THREAD

**Issue by katikaa** [bbc/simorgh#472]
**Is your feature request related to a problem? Please describe.**
From what we've seen here, there are browsers that do not support SVGs https://caniuse.com/#search=svg.

**Describe the solution you'd like**
Following the behaviour on the front page currently, we want to fallback to a png in those cases
![bbc news branding_4x](https://user-images.githubusercontent.com/25030311/43893672-b0f2d5ca-9bc7-11e8-9cc4-5b0365da499f.png)

**Comment by jtart** [comment]
This is not needed as the banner will be the same as in the Header.
