### ISSUE TITLE
AV captions are indented on mobile

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#4735]
**Describe the bug**
AV captions are indented on mobile. They should be aligned with the edge of the media player as per the designs.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo on mobile
2. Scroll down to any media asset with a caption
4. See that the caption is indented and not aligned with the media player, H1/H2, or body text

**Expected behaviour**
The caption should not be indented. It should be aligned with the media player and other content blocks, as per the design:
![image](https://user-images.githubusercontent.com/52247014/69239938-49887880-0b93-11ea-9100-727e9a48a903.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/52247014/69239870-1e9e2480-0b93-11ea-9033-de805d91d65b.png)

**Smartphone (please complete the following information):**

- Device: Pixel 2
- OS: Android 10
- Browsers: Facebook for Android, Chrome v.78, Opera Mini, Firefox for Android

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by RayNjeri** [comment]
Closing this in favor of work done in https://github.com/bbc/simorgh/issues/4311
