### ISSUE TITLE
AV on IE11 warns that player will stop working

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#4736]
**Describe the bug**
When playing audio/video on IE11 a warning message is displayed saying that the player will stop working.

**To Reproduce**

1. Run IE11
2. Open https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo
3. Play any audio/video object

**Screenshots**
<img width="751" alt="Screenshot 2019-11-19 at 14 07 55" src="https://user-images.githubusercontent.com/11161809/69242200-42179e00-0b98-11ea-9575-e52cd99f779b.png">

**Notes**
- Compare with other pages with video player on (News, iPlayer, WS, Live, etc.)
- Suggest a solution

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by 12** [comment]
Will SMP not just switch to the HTML5 player? I thought we forced the HTML player?

**Comment by neildoughty** [comment]
Some notes from SMP here: 
https://confluence.dev.bbc.co.uk/display/PLAYBACKSMP/Flash+deprecation
https://www.bbc.co.uk/iplayer/help/flash

**Comment by rhenshaw56** [comment]
closing as it's a flash deprecation warning
