### ISSUE TITLE
Update WS trust project links when destinations are ready

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#4743]
**Is your feature request related to a problem? Please describe.**
The WS Trust Project landing pages exist but are not yet complete.  Once they have been completed by the addition of the special schema.org includes for these pages, we should update the links in Simorgh to use them (until then, the WS links should remain pointing at the /news Trust Project Landing Page which contains the appropriate schema.org).  This is so that we do not fail Trust Project validation.

**Describe the solution you'd like**
Update the trust project links in each service's config file.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by AlistairGempf** [comment]
Site | Link | Link Currently Works
-- | -- | --
Afaan Oromoo | https://www.bbc.com/afaanoromoo/institutional-49281861 | Y
Amharic | https://www.bbc.com/amharic/institutional-49283133 | Y
Bengali | https://www.bbc.com/bengali/institutional-50409861 | N
Sinhala | https://www.bbc.com/sinhala/institutional-50288553 | N
Tigrinya | https://www.bbc.com/tigrinya/institutional-49283259 | Y
Nepali | https://www.bbc.com/nepali/institutional-50318130 | N

**Comment by AlistairGempf** [comment]
From ticket WSFRONTPGS-268

**Comment by OlgaLyubin** [comment]
All trust project links have been updated as all services are live.
