### ISSUE TITLE
Thai World Service Article Broken Locally Only

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#4751]
**Describe the bug**
NB: Live page looks fine: https://www.bbc.com/thai/international-49514085.amp

Issue identified debugging a cypress test, the following url http://localhost.bbc.com:7080/thai/international-49514085.amp shows following 'broken looking page':

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/9645462/69361300-196cd280-0c84-11ea-842e-9443540016ac.png">

The cypress test reports it cannot resolve this garbled image url: https://ichef.bbci.co.uk/news/800/undefined/ichef.bbci.co.uk/images/ic/$recipe/p07lyyc0.jpg 

If you look in the network tab you see the failed request:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/9645462/69361619-c5aeb900-0c84-11ea-8bce-3e7be79492bf.png">

A full local run of `npm run test:e2e` fails currently due this issue.

**To Reproduce**

In Browser: 
1. Go to http://localhost.bbc.com:7080/thai/international-49514085.amp 
1. See 'broken page' as above
1. Look in network tab to see various failed requests

Cypress Test
1. In terminal `export CYPRESS_ONLY_SERVICE=thai`, then `npm run test:e2e`
See failed cypress test:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/9645462/69361909-55546780-0c85-11ea-81a7-881834277b39.png">

**Expected behavior**
Not quite sure what is expected, sorry, someone please replace this with your expectation!

**Desktop (please complete the following information):**

- OS: iOS
- Browser: firefox
- Version 70

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by oluoluoxenfree** [comment]
@ryanmccombe This issue is still happening, and with multiple services:

![image (2)](https://user-images.githubusercontent.com/3077443/69656836-2cf7af00-1071-11ea-950f-7432bc26f50c.png)
![image (1)](https://user-images.githubusercontent.com/3077443/69656837-2d904580-1071-11ea-9fd0-61d4cb394f63.png)
![image](https://user-images.githubusercontent.com/3077443/69656838-2d904580-1071-11ea-9cd9-53524dd82dcf.png)

**Comment by oluoluoxenfree** [comment]
[output.txt](https://github.com/bbc/simorgh/files/3893189/output.txt)

**Comment by ryanmccombe** [comment]
Ah, good spot - this is happening for me too.  Weird that the simorgh-e2e-local build is passing, but not when run on dev machines.

Will investigate tomorrow!

**Comment by oluoluoxenfree** [comment]
Is this issue fixed?

**Comment by ryanmccombe** [comment]
> Is this issue fixed?

I believe so - I haven't done a full local run on dev machine yet, but live, test and local are all passing on the CI server

**Comment by oluoluoxenfree** [comment]
@ryanmccombe cool, I'll do a full run now
