### ISSUE TITLE
Pass correct props to article schema to enable SEO discoverability 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4752]
**Is your feature request related to a problem? Please describe.**
As an SEO expert I want to ensure the correct values are being passed to the Schema, so that my page is discoverable and ranked in search. 

**Describe the solution you'd like**
At the moment when you use the https://search.google.com/structured-data/testing-tool and test a test MAP page like: https://www.test.bbc.com/pidgin/23248703
  you will see that we're not setting values the following fields: 
![Screenshot 2019-11-20 at 11 26 32](https://user-images.githubusercontent.com/22519682/69365747-dc590e00-0c8c-11ea-9514-95816efb5775.png)

We need to set the correct props for the Article and Author objects and fields: 

| Object Name | Field Name | Value Example | Is Dynamic value? | Source |
| -- | -- | -- | -- |-- |
|Article|datePublished | 2019-11-21T19:35:04+01:00 | Yes | Ares - firstPublished | 
||dateModified | 2019-11-21T19:35:04+01:00 | Yes | Ares - timestamp |
|| headline | BBC Pidgin Minute | Yes | Ares - headline | 
| Author | @type | NewsMediaOrganisation or Organization (if trust project participant) | No | Simorgh | 
| | name | BBC News Pidgin | Yes (per service) | Simorgh (same as the schema publisher name) |
| | noBylinesPolicy | http://www.bbc.co.uk/news/help-41670342#authorexpertise | No | Simorgh (check with articles) |

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
Related Issue: https://github.com/bbc/simorgh/issues/4664

**Comment by karinathomasbbc** [comment]
noBylinesPolicy does come from Simorgh - in the config file for each service

**Comment by karinathomasbbc** [comment]
Please note:  https://www.test.bbc.com/pidgin/23248703 does not have an seoHeadline in promos -> headlines, therefore this will continue to flag up as an error.  However, this article - https://www.test.bbc.com/pidgin/articles/cwl08rd38l6o - works OK

**Comment by karinathomasbbc** [comment]
dateModified is blocked by #4092 - the timestamp field is not yet available on the AReS payload.
