### ISSUE TITLE
Tidy up MAP pages so they're in-line with the UX designs 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4758]
**Is your feature request related to a problem? Please describe.**
Currently the MAP page is not styled in-line with the designs: https://www.test.bbc.com/pidgin/23248703

Check design across mobile, desktop etc.

Known issues: video player on mobile not taking up the full width, timestamp & spacing around player.

Please note in particular the spacing between the headline and the player on the page. 
![Screenshot 2019-11-22 at 16 52 46](https://user-images.githubusercontent.com/22519682/69444579-8d70ae80-0d48-11ea-9674-e146db4dba65.png)

**Describe the solution you'd like**
We need to ensure that the styling of the pages matches the designs specified by UX
See: https://zpl.io/aMjlMnJ 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
- Increased space above player (now 40px on desktop; 32 on mobile)
- Reduced space below player (now 40px on desktop; 32 on mobile)
- Increased space below related content (now 56px on desktop; 48 on mobile)
- Timestamp no longer pops out to the side on desktop

Note
- the placeholder link is still there - issue to fix that: https://github.com/bbc/simorgh/issues/4761
- the player is still not full width on mobile - issue to fix that: https://github.com/bbc/simorgh/issues/4311
