### ISSUE TITLE
Validate Related Content Translations for Services 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4759]
**Is your feature request related to a problem? Please describe.**
We need to validate that we are using the correct translation values for the related content heading in MAPs. 

**Describe the solution you'd like**
We need to ensure the correct translations for related content have been implemented on the pages for the related content heading

![Screenshot 2019-11-22 at 17 03 19](https://user-images.githubusercontent.com/22519682/69445357-0d4b4880-0d4a-11ea-813d-78814773f1a9.png)

Each heading must match row 37 of the translations spreadsheet for each service.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
Russian & Uzbek had incorrect translations - other services OK
