### ISSUE TITLE
Display Error for non-JS scenario on MAP pages

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4760]
**Is your feature request related to a problem? Please describe.**
Currently when a user visits a MAP on Simorgh, when Javascript is disabled we don't display an error, we render a white space. This doesn't give any feedback to the user:
 
![Screenshot 2019-11-22 at 17 10 28](https://user-images.githubusercontent.com/22519682/69445917-3cae8500-0d4b-11ea-980f-2790b9eb3153.png)

Currently on Responsive news we give the user some feedback: 
![Screenshot 2019-11-22 at 17 10 57](https://user-images.githubusercontent.com/22519682/69445902-36200d80-0d4b-11ea-9e7d-9beb2997d5ec.png)

We need to ensure we give feedback to the user when the player is unable to load. 
We should use the error message in these designs: 
https://zpl.io/bLEP6xJ

Current the error message is displayed in English - we will need to translate it across languages but we will render English for now

**Describe the solution you'd like**

Given a user visits a MAP page
when javascript is disabled on their browser 
and there is a poster image available for the MAP
then we will display the poster image, a grey overlay and the text "To play this content, please enable JavaScript, or try a different browser"

Articles have implemented the same solution here: https://github.com/bbc/simorgh/issues/2368
**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Cypress tests for both Canonical and AMP
Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Similar issue: https://github.com/bbc/simorgh/issues/2368

**Comment by ryanmccombe** [comment]
See error component here: https://bbc.github.io/psammead/?path=/story/components-embederror--default

**Comment by LilyL0u** [comment]
Looks good but should it be 'JavaScript'. Pedantic, I know!

![Image 05-02-2020 at 11 36](https://user-images.githubusercontent.com/54575620/73838558-da263a80-480b-11ea-823e-b977478c3351.jpg)

@rebeccarfmcginnbbc

**Comment by LilyL0u** [comment]
Looks good in FF, Chrome and safari

**Comment by LilyL0u** [comment]
Will close when we have done the a11y review
