### ISSUE TITLE
Remove "test to MAP inline link on MAP" pages

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4761]
**Is your feature request related to a problem? Please describe.**
We are currently displaying this link at the top of MAP pages: 
![Screenshot 2019-11-22 at 17 17 50](https://user-images.githubusercontent.com/22519682/69446355-1b01cd80-0d4c-11ea-843c-a75d197a4858.png)

We need to remove it before we can go live. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
Waiting for core pod to complete

**Comment by ryanmccombe** [comment]
https://github.com/bbc/simorgh/issues/4594
