### ISSUE TITLE
Article data limited to specific environment

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#478]
**Is your feature request related to a problem? Please describe.**
- Test data should only be on the TEST endpoint. 
https://$TEST_SIMORGH_HOSTNAME/news/articles/c0000000001o This should work
https://$LIVE_SIMORGH_HOSTNAME/news/articles/c0000000001o This should not work

- Prod data should be on the LIVE and TEST endpoints. 
https://$TEST_SIMORGH_HOSTNAME/news/articles/c0000000027o
https://$LIVE_SIMORGH_HOSTNAME/news/articles/c0000000027o

**Describe the solution you'd like**
Currently, the prod articles are on the Live endpoint and Test endpoints.

**Describe alternatives you've considered**

**Additional context**

**Comment by dr3** [comment]
Do we need this @sareh? if not can you close please?
