### ISSUE TITLE
Improve Test Coverage of CPS Block Rendering

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4794]
**Is your feature request related to a problem? Please describe.**
CPS pages contain an array of different block types - video, paragraph, bulleted lists, headings etc

In our integration / end to end tests, we currently are only ensuring some block types are being rendered.  We should expand this

**Describe the solution you'd like**
Improve our integration tests to ensure the CPS page is rendering all the appropriate block types

Integration tests can be found here: https://github.com/bbc/simorgh/blob/latest/src/app/containers/CpsAssetPageMain/index.test.jsx

**Describe alternatives you've considered**
E2E tests? Might need to be added in the future after we consolidate E2Es

E2E tests for this page can be found here:
https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/mediaAssetPage/tests.js

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
@ryanmccombe is this required for go-live?

**Comment by ryanmccombe** [comment]
> @ryanmccombe is this required for go-live?

Nope - it's mostly to prevent future regressions
