### ISSUE TITLE
Feature Toggles

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#480]
**Is your feature request related to a problem? Please describe.**
Storybook is not sufficient for testing, particularly for accessibility testing, since components are rendered within an iframe. 

**Describe the solution you'd like**
To create a higher-order wrapper component that will render the component if a prop value is `on` or `off`. 

To set up query parameters that will toggle the component being used in the Article. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jamesbhobbs** [comment]
I think fullscreen mode (I think it's cmd+shift+f) and already working links like this are enough for testing... https://simorghstorybook.now.sh/iframe?selectedKind=Article&selectedStory=with%20just%20a%20headline

They are well buried in the documentation though.

**Comment by sareh** [comment]
@benjaminhobbs Thanks for this link, which has a view of the iframe contents.
Although this works to show the Footer in isolation: https://simorghstorybook.now.sh/iframe?selectedKind=Footer&selectedStory=default that `/iframe` endpoint is not available locally at http://localhost:9001/iframe?selectedKind=Footer&selectedStory=default . This makes it unsuitable for testing PRs. 

When trying the 'fullscreen mode' (CMD+Shift+F), all it does is hide the Storybook panels visually. The panels are still in the DOM and the component itself is within the iframe. (http://localhost:9001/?selectedKind=Footer&selectedStory=default&full=1&addons=1&stories=1&panelRight=0)

**Comment by ChrisBAshton** [comment]
Would [this issue](https://github.com/storybooks/storybook/issues/4667) mitigate this?

**Comment by sareh** [comment]
Closed since the core issue will be addressed here: https://github.com/bbc/simorgh/issues/1550
