### ISSUE TITLE
Enable embedding on live stream MAP pages 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4802]
**Describe the bug**
When a user enables embedding in CPS for MAP page with a live stream we should be allowing the user to embed the content. 

Currently this button is disabled even when the embeddable flag is true. 

**To Reproduce**

1. Go to https://www.test.bbc.com/pidgin/media-23256553
2. Note in the feed embeddable is flagged as true: https://www.test.bbc.com/pidgin/media-23256553.json
2. Click on play on the player
3. Note that the embed button is not visible 

**Expected behavior**
Expected behaviour is that this embed button is visible where embedding is enabled even on pages that have live streams enabled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22519682/69675249-1fa0eb80-1096-11ea-9443-8781853bbd54.png)

**Desktop (please complete the following information):**

All 

**Smartphone (please complete the following information):**
All 

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
A similar component has been recently implemented by the articles team: https://github.com/bbc/psammead/pull/2625

**Comment by karinathomasbbc** [comment]
Working live stream example: https://www.test.bbc.com/thai/thailand-23248713
Embeddable live stream example: https://www.test.bbc.com/pidgin/media-23262920

**Comment by ryanmccombe** [comment]
This should be fixed on the test env: https://www.test.bbc.com/pidgin/media-23256553

Can make it live after testing :)

**Comment by LilyL0u** [comment]
@karinathomasbbc https://www.test.bbc.com/thai/thailand-23248713 gets page unavailable. Problem? Or do we just need a different URL

**Comment by karinathomasbbc** [comment]
> @karinathomasbbc https://www.test.bbc.com/thai/thailand-23248713 gets page unavailable. Problem? Or do we just need a different URL

I think we just need a different one.  Not sure why that doesn't work anymore, but it would be good to have an example of audio, and one for video.

**Comment by LilyL0u** [comment]
> > @karinathomasbbc https://www.test.bbc.com/thai/thailand-23248713 gets page unavailable. Problem? Or do we just need a different URL
> 
> I think we just need a different one. Not sure why that doesn't work anymore, but it would be good to have an example of audio, and one for video.

This URL is used on the E2Es for thailand MAP so this will cause fails. 

![Image 03-02-2020 at 15 15](https://user-images.githubusercontent.com/54575620/73664850-05881880-4698-11ea-8deb-b06a4a78b8a5.jpg)

**Comment by ryanmccombe** [comment]
https://github.com/bbc/simorgh/pull/5299#discussion_r371958641

Only Igbo, Pidgin and Yoruba MAPs will route to Simorgh for now :)

**Comment by LilyL0u** [comment]
Embedding is false on this video stream: https://www.test.bbc.com/pidgin/media-23256547.json
And the embed option is not available on the player. (it can be embedded by adding the /embed to the end though, as as discussed in the Three Amigos, this needs to be investigated and worked on)

Embedding is true on this audio stream: https://www.test.bbc.com/pidgin/media-23256553
And the embed option is available on the player, and the /embed URL works (/embed?_x_candy_override=https%3A%2F%2Fapi.test.bbc.co.uk for test)

Embedding is false on this audio stream: https://www.test.bbc.com/pidgin/media-23256550 anf the embed option is not available on the player.

Embedding is true on this video stream: https://www.test.bbc.com/pidgin/media-23263912
the embed option is available on the player
