### ISSUE TITLE
Inline links - no bold or italics

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#481]
**Is your feature request related to a problem? Please describe.**
Prevent inline-links from having these styles:
- bold
- italic
- bold then italic
- italic then bold

**Describe the solution you'd like**
~We are unsure whether our current `markdown-to-jsx` library is sufficient for this purpose.~

**Comment by BogdanDogaru** [comment]
Blocked pending a discussion on whether we do this and if we do, how we solve the problem.

**Comment by ChrisBAshton** [comment]
Is this a business requirement? @jimjohnsonrollings ?

**Comment by jimjohnsonrollings** [comment]
No.  This is the opposite of the behaviour I would like.

**Comment by ChrisBAshton** [comment]
Closing!
