### ISSUE TITLE
Chartbeat pageview param not found for AMP

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4811]
**Describe the bug**
Cypress tests for chartbeat are failing with the following error

`[AmpAnalytics <unknown id>] Ignoring request for event. Request string not found:  pageview`

**To Reproduce**

1. Enable the chartbeat toggle for localhost
2. run the e2e's
3. See failing test

We should see if we can re-use this [file](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ATIAnalytics/amp/ampAnalyticsJson.js) (pre-defined structure for amp-anlytics) for chartbeat, we are already using it for ATIAnalytics.

This is the current chartbeat amp implementation.

**Comment by andrewscfc** [comment]
Can we bundle this linting fix into this issue? https://github.com/bbc/simorgh/pull/4812#discussion_r351705094 

Just so we test around this area when the change is made

**Comment by andrewscfc** [comment]
Progress update for anyone picking up this issue tomorrow:

I have looked at the documentation for how to implement chartbeat and found: http://support.chartbeat.com/docs/integrations.html#ampimpl 

It shows a configuration like this:
```
<amp-analytics type="chartbeat">
    <script type="application/json">
        {
            "vars": {
                "uid": "12345",
                "domain": "yoursite.com",
                "sections": "section 1, section 2"
                // Author, etc.
            }
        }
    </script>
</amp-analytics>
```

Our implementation has a `triggers` line that isn't mentioned: https://github.com/bbc/simorgh/compare/chartbeat-amp#diff-a6cb5242b50b07228921447ee534136aL6 

I have removed this on this branch: https://github.com/bbc/simorgh/compare/chartbeat-amp and the E2E test pass locally aside from those affected by https://github.com/bbc/simorgh/issues/4751 

I am unsure if removing the `triggers` config is advisable or if it has broken the analytics behaviour?

**Comment by andrewscfc** [comment]
Raised a PR with the `triggers` config above removed https://github.com/bbc/simorgh/pull/4861, the analytics 'seems to work' following some very simplistic testing from me: https://github.com/bbc/simorgh/pull/4861#issuecomment-560306383
