### ISSUE TITLE
Update Request Context to fallback to `default`

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#4818]
**Is your feature request related to a problem? Please describe.**
Our current implementation for `psammead-storybook-helper` returns variant value as`default` for non-variant services. https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-storybook-helpers/src/withServicesKnob.jsx#L41

 However our `RequestContext` (src/app/contexts/RequestContext/index.jsx) is defaulting variant value to `null`. We should have the default value of variant consistent throughout our repos.

**Describe the solution you'd like**
Update RequestContext to return `default` when the prop is not specified. https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/index.jsx#L85 

Tests may break, check that functionality is dependant on variant being `null`.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by g4rry420** [comment]
Hello, Can I work on this issue ?
