### ISSUE TITLE
[Test] Region restrictions on media and corresponding error messages on MAP player

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#4824]
This will be tested as part of the page swarm. Acceptance criteria below and link to MAP test scenario sheet here: https://docs.google.com/spreadsheets/d/16uD_5LkvJDbkbT5G0N3VoIThlecsjc-k81B_Hb9bSsU/edit#gid=0

Media content embedded from castaway in a CPS map may have certain region restrictions 

We require the clip metadata from MPV via AReS

"availableTerritories": { "uk": true, "nonUk": true },
We need to ensure that we respect these territories 

Media selector may take care of this but we need to be certain 

**Acceptance Criteria**

Given that a MAP has a clip on the page

And the content has been marked as <region restriction>
When I view this page from <region>
Then I am able to <outcome>

![Image 29-11-2019 at 12 32](https://user-images.githubusercontent.com/54575620/69869319-66fcc700-12a4-11ea-994f-a8cad53df6a1.jpg)

**Comment by gavinspence** [comment]
Closing as Done
