### ISSUE TITLE
[Test] Guidance warnings on MAP player

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#4825]
This will be tested as part of the page swarm. Acceptance criteria below and link to MAP test scenario sheet here: https://docs.google.com/spreadsheets/d/16uD_5LkvJDbkbT5G0N3VoIThlecsjc-k81B_Hb9bSsU/edit#gid=0

As a journalist

I want to ensure that any guidance on castaway is rendered in the player

so that users are warned when the content contains sensitive material

Within CPS editorial can select to add guidance within content options 

We would ideally want to support guidance added from castaway not through CPS

This may require work on the SMP side 

We will need to ensure we get warnings in the ARES response from MPV

**Comment by gavinspence** [comment]
Closing as marked as Done
