### ISSUE TITLE
Run AMP Validator against MAP pages

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4829]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
Currently fine - https://validator.ampproject.org/#url=https%3A%2F%2Fwww.test.bbc.com%2Fpidgin%2F23248703.amp

Should run again before going live

**Comment by pharingee** [comment]
I ran this today against the pages on our MAP asset list and it looks good

**Comment by karinathomasbbc** [comment]
Marking as Done - we have an item on the checklist to make sure this is OK once we go live, so no need to keep this open

**Comment by pharingee** [comment]
Tests passed once more
