### ISSUE TITLE
Image aspect ratios (9:16, 1:1, etc.)

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#484]
**Is your feature request related to a problem? Please describe.**
Ensure images of different aspect ratios are displayed correctly.

**Describe the solution you'd like**
Style the image block according to the UX&D designs, and test it with different aspect ratios (wide portrait - 9:16, square 1:1, etc.)

**Additional Context**
Designs TBC

**Testing**
- Cypress tests (at different breakpoints) - https://docs.cypress.io/api/commands/viewport.html#Width-Height

**Comment by BogdanDogaru** [comment]
Blocked:
- [x] until we update fixture data with the right image sizes #485
- [x] until we get designs for non-standard aspect ratios.

**Comment by katikaa** [comment]
Product have defined the outstanding requirements for custom images - let's talk about them in the next workshop/refinement meeting :)

**Comment by BogdanDogaru** [comment]
To do: Add UX designs to this issue.

**Comment by pjlee11** [comment]
Blocked awaiting UX designs

**Comment by sareh** [comment]
Closed as fixed.
