### ISSUE TITLE
Load low res images for no-script requests

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#486]
**Is your feature request related to a problem? Please describe.**
There is a requirement to have all images shown including on non-JS requests. 

**Describe the solution you'd like**
We can utilise the HTML `<noscript>` tag to load in low resolution images (width: 320px). This then stops the low resolution images from being downloaded on enhanced browser requests.

**Additional context**
Currently our live products only show the lead image on non-JS requests so this is a new treatment that we've not previously implemented.

**Comment by pjlee11** [comment]
This should ideally be done following the outcome and implementation of https://github.com/bbc/simorgh/issues/448

**Comment by pjlee11** [comment]
This is blocked until the lazyload library is implemented in #520

**Comment by pjlee11** [comment]
Closing the PR https://github.com/bbc/simorgh/pull/667 as it's going to be blocked for some time. The branch `noscript-low-res-image` should give a rough idea of what work needs to be done

**Comment by greenc05** [comment]
When implementing this, we should double check that this doesn't affect assistive technology e.g. that some AT doesn't see 2 image alt texts, particularly Read&Write

**Comment by pjlee11** [comment]
This should follow the implementation documented in https://github.com/BBC-News/simorgh/pull/899

**Comment by jamesbhobbs** [comment]
>There is a requirement to have all images shown including on non-JS requests.
No there isn't
