### ISSUE TITLE
Media Players do not show up on staging

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4864]
**Describe the bug**
AV players do not show up on staging for either MAPs or articles

**To Reproduce**
Go to one of these -
MAP: https://www.stage.bbc.com/pidgin/23248703
Articles: https://www.stage.bbc.co.uk/news/articles/c3wmq4d1y3wo

Note they **do** show up for live radio, so likely to be some issue with the AV player component (which is circumvented in live radio)

https://www.stage.bbc.com/indonesia/bbc_indonesian_radio/liveradio

**Expected behavior**
Video palyer available

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by HarveyPeachey** [comment]
Could the issue be caused by not having `stage` in our logic for figuring out the mediator environment in the `news-av-player` morph module?

**Comment by ryanmccombe** [comment]
I don't think it's getting as far as Morph - The iframe isn't emitted at all, so I suspect it's a problem in the simorgh or psammead component :(

![Screen Shot 2019-12-02 at 15 20 28](https://user-images.githubusercontent.com/8601460/69971165-6455d800-1517-11ea-8ada-58d3431967aa.png)

Most likely simorgh, as I believe the psammead root component has some styling (eg, a height)

**Comment by ryanmccombe** [comment]
This now works - https://www.stage.bbc.com/pidgin/23248703
