### ISSUE TITLE
Cypress test - Add test to check amp status is 200

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#4877]
In the liveRadio cypress tests there is a check for amp status returning a 200. This will be replicated in the mediaAssetPage tests.

(Trying to get similar coverage on MAPs as for live radio)

`describe(`Amp Tests for ${service} ${pageType}`, () => {
    describe('AMP Status', () => {
      it('should return a 200 response', () => {
        cy.testResponseCodeAndType(
          `${config[service].pageTypes.liveRadio.path}.amp`,
          200,
          'text/html',
        );
      });
    });`

**Comment by ryanmccombe** [comment]
Had a look at this following conversation at stand up - I can't see any way to make this test fail - if cypress goes to the page and it 404s (for example) cypress will fail, but not explicitely for this test

But, the test still created the scenario that detected the failure, even if it wasn't credited for it, so I think it still has value

If we had a bunch of other tests that visit the amp pages, that would be unnecessary as the page not existing would be detected as a side-effect of those tests.

But we only have a few other tests that hit .amp - if those few get deleted or modified, we'd still like a fallback test that at least makes cypress visit the page

So my opinion would be to keep the test around, at least for now

**Comment by LilyL0u** [comment]
Thanks, I'll keep it. I just hope it doesn't pass when it should fail! It's the same as the liveRadio test for this, so should be fine if that one was also acceptable.
