### ISSUE TITLE
Implement Media Player Tests for Live Radio

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#4885]
**Is your feature request related to a problem? Please describe.**
We recently established a technique to interact with the iframe during E2E testing

This was applied to the MAP pages, but not live radio

**Describe the solution you'd like**
 We should go back and apply the same technique to live radio, so we get some automated indication if code is breaking our embed endpoint

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
This is done!
