### ISSUE TITLE
AMP - T&Cs link in embed window does not work

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#4893]
**Describe the bug**
On amp pages, if you open the embed window on the player and click the terms and conditions link, nothing happens. This works on canonical pages.

**To Reproduce**

1. Go to https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo.amp
2. Play the media
3. Open the embed option
4. Click on terms and conditions link
5. See that the link does not open
6. Compare to canonical

**Expected behavior**
The user on amp should be able to open the terms and conditions

- [x] This bug fix is expected to need manual testing.

Tested and found on articles page but could affect the player on any page type

**Comment by LilyL0u** [comment]
![UNADJUSTEDNONRAW_mini_8d](https://user-images.githubusercontent.com/54575620/71265261-bed79c80-233d-11ea-93c7-83c9e7eabafa.jpg)

**Comment by gavinspence** [comment]
Closing as no longer needed
