### ISSUE TITLE
Resize bulleted-list bullet when page font is resized by user

### ISSUE THREAD

**Issue by pharingee** [bbc/simorgh#4943]
**Describe the bug**
When the user manually resizes a page with a bulleted-list, the bullet stays the same size.

**To Reproduce**

1. Go to https://www.test.bbc.com/pidgin/23248703
2. Resize for size in browser preferences
3. Reload page

**Expected behavior**
Bullet should resize with with the text.

**Testing notes**

- [x] This bug fix is expected to need manual testing.

<img width="796" alt="Screenshot 2019-12-11 at 11 24 14" src="https://user-images.githubusercontent.com/22519682/70988695-35646800-20ba-11ea-82f5-442dbb4aaa9c.png">

![Screenshot 2019-12-11 at 11 20 29](https://user-images.githubusercontent.com/22519682/70988696-35646800-20ba-11ea-9aa5-7b0da6032576.png)

![Screenshot 2019-12-11 at 11 20 14](https://user-images.githubusercontent.com/22519682/70988699-35646800-20ba-11ea-9e1d-05be367b30b8.png)

![Screenshot 2019-12-11 at 11 20 03](https://user-images.githubusercontent.com/22519682/70988700-35fcfe80-20ba-11ea-80a6-c7001ebf1074.png)

**Additional context**

**Comment by gavinspence** [comment]
This requires quick investigation. If it's related to the bullet being an SVG with significant work to address, we won't pick this up.

**Comment by aeroplanejane** [comment]
This will be fixed by https://github.com/bbc/psammead/issues/3607
