### ISSUE TITLE
Media Asset Pages can't be accessed from Opera Browser on MAC 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4954]
**Describe the bug**
We can't access Media pages from Opera on MAC 

**To Reproduce**
Steps to reproduce the behaviour:

1. Using Opera on your Mac Go to 'https://www.test.bbc.com/pidgin/media-23256553'
2. Note the error. 

**Expected behavior**
These pages should be available on opera. 
Note frontpage, radio and article pages have no issues. 

**Screenshots**
<img width="1035" alt="Screenshot 2019-12-11 at 16 35 45" src="https://user-images.githubusercontent.com/22519682/70729286-d211b900-1cfa-11ea-8c15-94217b02c45d.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [MAC]
- Browser [Opera]

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Can't reproduce on test or stage.

**Comment by ryanmccombe** [comment]
> Can't reproduce on test or stage.

Neither can I

@LilyL0u was able to reproduce this, but also had the same issue accessing any other internal BBC site on Opera, so likely to be a local issue

Worth investigating further in the new year though to be 100% certain

**Comment by aeroplanejane** [comment]
Going to close as per conversation with @ryanmccombe and @gavinspence
