### ISSUE TITLE
SMP iframe unavailable on stage with live data

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#4971]
**Describe the bug**
When showing live data on stage with `?renderer_env=live` the SMP player within the iframe shows a page unavailable error.

**To Reproduce**

1. Go to any MAP page on stage across Pidgin, Yoruba & Igbo
2. Apply the ?renderer_env=live to see live data
3. See error

https://www.stage.bbc.com/pidgin/media-50748913?renderer_env=live

**Expected behavior**
SMP should be available when viewing live data

**Desktop (please complete the following information):**

- OS: MacOS 10.14
- Browser: Chrome
- Version: 79

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
Initial PR was reverted - need to reopen

**Comment by karinathomasbbc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [a](https://trello.com/c/G7FcYWkZ/1-a)
