### ISSUE TITLE
Service variant not respected on initial render

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#4976]
**Describe the bug**
When a user has selected a service variant preference, and the cookie has been set accordingly, the default variant is still displayed initially, before re-rendering with the preferred variant. 

**To Reproduce**

1. Set the `skns_variant` cookie to have a value of `cyr`.
2. Navigate to http://localhost:7080/serbian/
3. You should see http://localhost:7080/serbian/lat load
4. The page content then disappears, and is replaced with http://localhost:7080/serbian/cyr (the URL also updates).

**Expected behavior**
The initial render to respect the preference cookie.

**Screenshots**
![variant-cookie](https://user-images.githubusercontent.com/6690955/70998239-b9284f80-20ce-11ea-9fd3-edd154ac2999.gif?s=200)

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
We cant have the initial render respect the users cookie preference as we can cannot decompose/check cookies on the server. So technically this is expected behaviour (not nice but expected).

the only way I think to get around this (without checking cookies on the server) would be to return a a loading/skeleton pages for the SSR (the initial render) and then wait for the hydration to kick in and check the users cookie for their preferred variant.

**Comment by tochwill** [comment]
Aha... so if we wanted to respect the cookie value we'd need to do it way higher up than Simorgh? How does routing work in this case in mozart (or whatever layer we're going to be using for cacheing going forward)? Do we just fall all the way through to `/serbian` for example and let Simorgh handle this, or do we route/cache anything based on cookie values?

**Comment by chris-hinds** [comment]
> Aha... so if we wanted to respect the cookie value we'd need to do it way higher up than Simorgh? How does routing work in this case in mozart (or whatever layer we're going to be using for cacheing going forward)? Do we just fall all the way through to `/serbian` for example and let Simorgh handle this, or do we route/cache anything based on cookie values?

All the business logic around service variants now happens client side (except for the server side defaults), so nothing in Mozart.
