### ISSUE TITLE
Navigation: AMP dropdown animation

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#4989]
**Is your feature request related to a problem? Please describe.**
@AlistairGempf undertook a spike into how we could animate the navigation dropdown in AMP. The result of that is here: https://github.com/bbc/simorgh/issues/4579#issuecomment-564951711. As there were some open questions, we decided to release the first iteration without the animation on the AMP site.

These animations should now be added with the following parameters:

<img width="565" alt="Screenshot 2019-11-06 at 14 39 03" src="https://user-images.githubusercontent.com/6690955/68311782-f77f2780-00a9-11ea-99fd-154d7d357bec.png">

<img width="571" alt="Screenshot 2019-11-06 at 14 39 12" src="https://user-images.githubusercontent.com/6690955/68311789-fa7a1800-00a9-11ea-8b42-c61fda08813b.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
Ensure when animations are turned off by the user using a system wide setting (e.g. reduce motion in system preferences), that these are adhered to.

Check animation speed works for shortest and longest navs - can decide is we need to parameterise this after this test.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by amywalkerdev** [comment]
Not going to be fixed by the Home team anymore
