### ISSUE TITLE
Investigate responsive image loading

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#500]
**Is your feature request related to a problem? Please describe.**
Investigate an effective way of replacing images with a suitable size, varying on browser dimensions.

**Describe the solution you'd like**
Present at least two solutions to achieve this, and their benefits. State which solution is preferred.

This can be either a library, or a standard, such as HTML's `<picture>` element, if browser support allows it.

Note: This must have support for HiDPI (Retina) displays.

**Additional context**
The images will be requested from the same ImageChef instance (image resizing system) as Responsive News.

Also consider how this will work on AMP pages and whether we can use a common solution.

**Outcome**
Document this in #501

**Comment by jtart** [comment]
~~There is a native lazyload spec coming to HTML. This should be investigated.~~ - not relevant to this issue

**Comment by ChrisBAshton** [comment]
Here is the responsive image component we use in visual journalism: https://github.com/bbc/news-vj-component-responsive-image

It's based on `<picture>` and has built-in lazy-loading. It would need some editing for our use case though, as it's not a React component.

**Comment by pjlee11** [comment]
Initial thoughts on this that an AMP-first approach would be to create a `srcset` value as this is how AMP implements a responsive image. This can then work out the box for non-AMP implementation. 

@ChrisBAshton had an idea around using JS on the client to get an image which exactly matches the device viewport size and we could debounce this in the scenario that a user drags the viewport wider/smaller. This feels like a future optimisation on the non-AMP components but would be good to research into

**Comment by pjlee11** [comment]
Picture is not a viable option as it has no support in IE and Opera mini. For context Opera mini is 90% of traffic for some world service sites 

https://caniuse.com/#search=picture

**Comment by ChrisBAshton** [comment]
Closed by #899.
