### ISSUE TITLE
Investigation: using padding to refine inline link styling

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#5011]
**Is your feature request related to a problem? Please describe.**
`border-bottom` is used to implement the preferred inline link style, and we'd like to keep all services using the same style if possible. However, the appearance is not acceptable for 5 services (Tamil, Telugu, Marathi , Bengali, Gujarati, Punjabi). One solution might be to use `padding-bottom` in combination with `line-height` for some services. We want to know if this is achievable.

**Describe the solution you'd like**
This is an investigation task that should be paired on between dev/test/UX. The goals are to look at:
- Whether we could use padding to achieve an acceptable appearance for these 5 services
- If we can achieve tolerably consistent results across the browsers and devices we support
- How the necessary padding could be efficiently specified and used in the codebase

Agreeing the final exact padding/line-height values is out of scope for this task. The objective is just to see if it is feasible.

**Testing notes**
TBD

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Note that the UX team have suggested these line height changes for services Gujarati, Marathi, Punjabi, Tamil, Telugu https://github.com/bbc/psammead/issues/2844 this leaves just Bengali potentially requiring this padding-bottom solution.
