### ISSUE TITLE
AMP - Error that asks you to download flash player - link to download does not work

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#5013]
**Describe the bug**
If you try to play some media on MAPs on IE11 you get the error message saying that you need to download the flash player. However, the link 'download flash player here' does not work when clicked. When I hover over the link, I see the URL is https://get.adobe.com/flashplayer.

**To Reproduce**
Go to an amp MAP URL for example:

www.test.bbc.com/pidgin/media-23256114.amp
www.test.bbc.com/pidgin/23248703.amp

Click play
See the flash player error
Try clicking the link to download flash player

**Expected behavior**
If this error should appear, the link to download flash player should be clickable if it is presented.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
When you go to the canonical version of the page, the player does not have an error, just a message saying that Flash will stop working in 2020 and will stop working on the device soon/

**Comment by aeroplanejane** [comment]
Won't fix as this is an SMP issue and flash will soon be deprecated.
