### ISSUE TITLE
On iOS, in production, the live radio SMP player controls are disabled apart from play and pause.

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#5021]
**Describe the bug**

On iOS devices, on the live radio page IN LIVE, the controls are disabled apart from play and pause.

When I first click play, the controls and seekbar are displayed but the controls under the player to go back and forward in the programme are disabled (greyed out) and the scrub bar cannot be moved. the play and pause button works fine.

If I then click pause, the controls fade out. When I click play again, the controls fade back in, apart from the red movable part of the scrub bar is not longer displayed, only the grey line.

Seen when a live programme is on on the devices iPhone SE iOS 12.4.1 and iPhone XS iOS 13.3.
Also seen when a live programme is not on (just place holder audio) on the iPhone 11 and iPhone 10. Experienced in Safari and Chrome.

**To Reproduce**

1. Go to www.bbc.com/korean/bbc_korean_radio/liveradio on an iOS device
2. Click play
3. Attempt to use controls
4. Pause and play again, see scrub bar not displaying properly.

**Expected behavior**
All controls should be able to be used and display properly.

**Screenshots**
When pressing play the first time:

![live radio disabled controls iphone se](https://user-images.githubusercontent.com/54575620/71592205-420ba600-2b27-11ea-98e0-f5839fa0c680.png)

Pressing play the second time after pausing:

![scrubbar not working ios](https://user-images.githubusercontent.com/54575620/71592530-821f5880-2b28-11ea-8065-2191f46456f5.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
This did not used to be a problem. Sounds player works on iPhone SE. On android this problem is not present.

**Comment by gavinspence** [comment]
Expected behaviour
