### ISSUE TITLE
Cookie redirects do not work on mobile and desktop

### ISSUE THREAD

**Issue by Bopchy** [bbc/simorgh#5038]
**Describe the bug**
Cookie redirects do not work on mobile devices and desktop browsers. This is likely because cookies that are not getting set on desktop and on mobile.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to http://localhost:7080/serbian on a mobile device/desktop browser. The page should navigate to http://localhost:7080/serbian/lat 
2. Click on the script link in the top right hand corner of the banner. This should cause the page to navigate to http://localhost:7080/serbian/cyr
3. Click on the Brand svg
4. See error (the page should load http://localhost:7080/serbian/cyr and not http://localhost:7080/serbian/lat)

**Expected behavior**
On Desktop browsers/mobile devices, clicking on the brand svg after clicking on the script link should load chosen variant page, not default.

**Screenshots**
![script_link_mobile](https://user-images.githubusercontent.com/12303856/71819786-1a27bf80-309e-11ea-93b6-23b061303bca.gif)

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
This issue is only on mobile devices. Desktop works as expected.

**Comment by Bopchy** [comment]
Needs https://github.com/bbc/simorgh/pull/4948 and https://github.com/bbc/simorgh/pull/4833 to be merged

**Comment by tochwill** [comment]
#4948 is merged into the feature branch now - I think we should look at this before we merge the feature branch to latest?

**Comment by tochwill** [comment]
Is this the same as Service variant not respected on initial render #4976 - or does the page not re-render at all? I've tried this locally and I see the behaviour described in that bug ticket.

**Comment by Bopchy** [comment]
On mobile, the page does not re-render

**Comment by Bopchy** [comment]
This issue is being caused by client-side javascript not loading when the hostname is not localhost on test devices. Because the redirect is happening on the client as mentioned [here](https://github.com/bbc/simorgh/issues/4976#issuecomment-566554172), if the client's javascript does not load, then the redirect will not work

**Comment by Bopchy** [comment]
Closing this as this is not really a bug, but an issue caused with how testing gets done.
