### ISSUE TITLE
Analyse the running order of script for `npm-p`

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#504]
**Is your feature request related to a problem? Please describe.**
We currently use `npm-p` to run multiple npm commands in parallel. This has been working successfully for many of our test scripts which require the application to be running locally such as cypress, lighthouse and bbc-a11y. 

**Describe the solution you'd like**
We should evaluate the execution order of `npm-p` as it's documentation does not clearly state whether the commands could cause race conditions. This could be achieved by create node scripts with various timeouts which console.log and execute them all using `npm-p`

**Additional context**
We should update the documentation for `npm-p` to be more explicit of our findings

**Comment by ChrisBAshton** [comment]
Do we? Or do we use `npm-run-all`?

Is there anything to do in this issue or can it be closed?

**Comment by ChrisBAshton** [comment]
Closing old issue
