### ISSUE TITLE
Split CPS Asset page type containers

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#5040]
A proposal to move to separate top level containers for each page type. Currently in Simorgh articles and front pages have their own page type container whereas all other assets (STY, FIX, PGL, MAPs) fall into the CpsAsset container. 

This is fine when those page types are all generally the same however with the addition of CPS STY's we will be adding a second column to the layout, we may have different meta data to apply for the different page types as well. Given this I'd like to switch to giving each page type its own top level container, this will add a small amount of duplication however will provide more flexibility and improve the readability of the code base.

**Current**

| PageType  | Container |
|-----------|-----------|
| Frontpage | Frontpage |
| Article   | Articles  |
| MAP       | CpsAsset  |
| STY       | CpsAsset  |
| PGL       | CpsAsset  |
| FIX       | Frontpage |

**Proposed**

| PageType  | Container |
|-----------|-----------|
| Frontpage | Frontpage |
| Article   | Articles  |
| MAP       | CpsMap       |
| STY       | CpsSty       |
| PGL       | CpsPgl       |
| FIX       | CpsFix       |

**Testing Notes**

This PR is primarily changing the file structure. it introduces a few new containers for our different CPS page types instead of having one large CpsAsset container for all CPS page types.

I would imagine just a simple regression of the different page types would be enough.

**Comment by sareh** [comment]
Since there's now going to be variation between the different CPS page types, it makes sense to separate out the containers.  Might be useful to namespace them for clarity. e.g. CpsFrontpage OptimoArticles CpsMap CpsSty CpsPgl CpsFix.
