### ISSUE TITLE
Create npm script to remove duplication of launching the application for testing purposes

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#505]
**Is your feature request related to a problem? Please describe.**
Currently the npm scripts for lighthouse, cypress and bbc-a11y testing all have "npm run killApp && npm run build && run-p --race start" prepended to them. 

**Describe the solution you'd like**
As we are in the process of adding the amp-validator which also requires this logic we should remove the duplication by creating an npm script which handles starting the application for the purpose of testing EG: 
```
"runApplicationInParallel": "npm run killApp && npm run build && run-p --race start"
```

**Additional context**
This solution would change the following:

```
"test:accessibility": "npm run killApp && npm run build && run-p --race start bbcA11y",
"test:e2e": "npm run killApp && npm run build && run-p --race start cypress",
"test:e2e:interactive": "npm run killApp && npm run build && run-p --race start cypress:interactive",
"test:lighthouse": "npm run killApp && npm run build && run-p --race start lighthouse",
```

to:

```
"runApplicationInParallel": "npm run killApp && npm run build && run-p --race start"
"test:accessibility": "npm run runApplicationInParallel bbcA11y",
"test:e2e": "npm run runApplicationInParallel cypress",
"test:e2e:interactive": "npm run runApplicationInParallel cypress:interactive",
"test:lighthouse": "npm run runApplicationInParallel lighthouse",
```

**Comment by sareh** [comment]
Closing as fixed.
