### ISSUE TITLE
Spacing Incorrect on Timestamps on MAPs 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5053]
**Describe the bug**
On a MAP page the spacing below the timestamp is incorrect. 

**To Reproduce**

1. Go to https://www.test.bbc.com/pidgin/media-23259752
2. Note the timestamp - and see that the updated time does not respect the spacing.
Spacing appears to fine on assets that have just the firstPublished date only (single timestamp) 

**Expected behavior**
The spacing of the timestamp should sit centrally between the headline and story body. 
See the design for reference: https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/dashboard?seid=5e14855290299456375c16ac

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by RichardPK** [comment]
PR: https://github.com/bbc/psammead/pull/2891

**Comment by RichardPK** [comment]
Simorgh PR: https://github.com/bbc/simorgh/pull/5072
