### ISSUE TITLE
Lighthouse Reports

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#5054]
**Is your feature request related to a problem? Please describe.**
Run Lighthouse reports against MAP pages

**Describe the solution you'd like**
Report how these compare to the existing MAP pages, and identify any opportunities for improvement

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by jroebu14** [comment]
## Test MAPs

https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://www.test.bbc.com/pidgin/23248703

![2020-01-10-11-06-lighthouse-dot-webdotdevsite appspot com](https://user-images.githubusercontent.com/4798332/72148655-404ca880-3399-11ea-8023-3e5714207d41.png)

---

https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://www.test.bbc.com/pidgin/media-23147054

![2020-01-10-11-27-lighthouse-dot-webdotdevsite appspot com](https://user-images.githubusercontent.com/4798332/72149953-409a7300-339c-11ea-9160-c23b2533eb52.png)

**Comment by jroebu14** [comment]
## Live MAP
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://www.bbc.com/pidgin/media-51053452

![2020-01-10-11-08-lighthouse-dot-webdotdevsite appspot com](https://user-images.githubusercontent.com/4798332/72149795-d7b2fb00-339b-11ea-9343-65479eabd837.png)

**Comment by jroebu14** [comment]
There seems to be an overall improvement with exception of Accessibility taking a hit for an incorrect aria-role value of text on span elements e.g. `<span role="text"`
