### ISSUE TITLE
Improve logging for data request failures

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#5059]
**Is your feature request related to a problem? Please describe.**
At the moment we log when we make a data request but not any information about the response, i.e.
```
info [getInitialData/index.js] DataRequest: [https://www.bbc.com/telugu.json]
```
This means we can't tell when a request failed and makes it harder to debug problems in production.

**Describe the solution you'd like**
Better logging for data requests and/or errors thrown as a result of problems arising from the data request.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
Looks like this has already been resolved, data fetch errors are now using the new logging standard, ensuring an event with useful information has been logged and making it easier to query for logs based on the event name.

https://github.com/bbc/simorgh/blob/c43bb7ac46c232b6a37e8550428e14a9deaab7d1/src/app/routes/utils/fetchPageData/index.js#L40
