### ISSUE TITLE
Move /src/app/Containers/PageHandlers to /src/app/Pages

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#5063]
Following the merge of https://github.com/bbc/simorgh/pull/5047, pages will be moved to `/src/app/Pages`, during the review we discussed also moving page handlers: https://github.com/bbc/simorgh/pull/5047#discussion_r363816774 . This issue is to discuss and potentially implement the move.

**Comment by andrewscfc** [comment]
To begin the discussion, I'd argue for the move because pages are being coupled to a dependency inside the `Containers` directory when `PageHandlers` are a composite part of `Pages` and not themselves used by containers. This search backs up this point showing all usages `PageHandlers` being `Pages` https://github.com/bbc/simorgh/search?q=PageHandlers&unscoped_q=PageHandlers  (at this point in the `Containers` directory as https://github.com/bbc/simorgh/pull/5047 has yet to be merged!) 

Getting a bit academic, the [Single Responsibility Principle](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch76.html) argues:
> Gather together those things that change for the same reason, and separate those things that change for different reasons.

In this case, when we change or add a `PageHandler` we are likely to modify a `Page` not a `Container`. This argues they should be maintained close together.

**Comment by chris-hinds** [comment]
This is going to open up much wider discussion point, however there has previously been mentions of swapping the HOC (Higher Order Components) out for custom hooks. I like this idea however I am a) not sure how much if any benefit this would bring and 2) not entirely sure custom hooks are the right approach.

I am happy to move these pageHandlers out of the containers dir, however am not 100% sure where exactly they belong. I do like the idea of keeping the `/pages` directory to just page type containers.

**Comment by simonsinclair** [comment]
From a dev-UX point of view, I like that I know what's in the `pages` directory before I open it. I will probably not expect to find anything else in there. And if I'm looking for something that relates to a page, I will probably start by locating the page and then inspect its dependencies.

That said, I see both points of view and am not precious on the outcome, as long as our structure makes things easy for fresh eyes. 👀

**Comment by chris-hinds** [comment]
This conversation has been left for a while now with no actions. I am closing the issue, we can re-open if we needed.
