### ISSUE TITLE
Investigate use of injectGlobal

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#509]
Currently, we are dogmatic about our [strict use of `injectGlobal`](https://github.com/bbc/simorgh/blob/latest/src/app/lib/globalStyles.js#L5-L73). While it is sensible that there is restrictions on this, which is recommended [by styled-components](https://www.styled-components.com/docs/api#injectglobal) we should investigate why these restrictions against, and evaluate our usage of it.

We should consider whether we can extract styles out of being locally set and to being globally set. An example of this might be our current application of the same font to multiple elements.

We should document the outcome of this investigation and have a determination about what styles can be added to `injectGlobal`, and why.

**Comment by ChrisBAshton** [comment]
Issue no longer valid.
