### ISSUE TITLE
Render summary on a PGL

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#5126]
**Is your feature request related to a problem? Please describe.**
Photo gallery asset summaries should render on the top of the page, they are currently not displayed.

[LIVE PGL](https://www.bbc.com/mundo/noticias-50565368)
[JSON Data](https://github.com/bbc/simorgh/blob/latest/data/pidgin/cpsAssets/sport-23252855.json#L141)

**Describe the solution you'd like**
Create a pre-processor rule for the text block. Apply the rule to only PGL assets.

https://github.com/bbc/simorgh/tree/latest/src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks

[Pre-processor rules](https://github.com/bbc/simorgh/blob/latest/src/app/routes/getInitialData/utils/getPreprocessorRules/index.js)

**Describe alternatives you've considered**

**Testing notes**

- [x] Extend unit tests to cover the new pre-processor rules.
- [x] Update [PGL snapshot](https://github.com/bbc/simorgh/tree/latest/src/app/pages/CpsPgl).
- [x] Manually check summary is being rendered.
- [x] ~Add e2e test for the photo gallery. Need to check if an asset is available on test.~ Decided to implement an E2E in a different issue, the E2E test is not related specifically to this issue
- [ ] UX check.
- [ ] A11y swarm.
- [ ] Check that [timestamps](https://github.com/bbc/simorgh/issues/5125) are positioned correctly on mobile, timestamps should appear between headline and text block (summary). This should work and be checked when #5125 is resolved.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by mykeels** [comment]
Local PGL URL: http://localhost:7080/pidgin/sport-23252855
