### ISSUE TITLE
Radio Schedules: Translations

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5132]
**Is your feature request related to a problem? Please describe.**
For the following languages:
```
Afrique
Arabic
Hausa
Korean
Pashto
Persian
Somali
Swahili
```

We need translations for:
- ~'Live'~ Done
- 'Next'
- 'Duration': `Duration, %localised_duration%`
- ~The header at the top of the section, for 'BBC News Radio'~ Done
- ~The link to radio frequencies for that service.~ Done

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by itimirichard** [comment]
The translations for `LIVE` are already present for all these services under the `default.translations.media` block. For the `NEXT` translations, Jonathan Booth wants us to keep it in english for now while he tries to get the translations.

**Comment by itimirichard** [comment]
Blocked until translations for `NEXT` are available

**Comment by jimjohnsonrollings** [comment]
These translations should be used for the strapline on the component.

Afrique: Journaux et Magazines
Arabic: أحدث نشرة أخبار
Hausa: Shirye-shiryenmu
Korean: BBC 코리아 라디오
Pashto: تازه خبرونه واورئ
Persian: برنامه‌های رادیو 
Somali: Barnaamijyada Idaacadda
Swahili: Vipindi vya Redio

**Comment by tochwill** [comment]
Note around 'Duration' - it won't work in all languages to just put the word Duration in front of a timestamp. We need to make sure this is accounted for and translated correctly.

**Comment by JonBeeb** [comment]
From the list above I've found the following (- line 50, 'Duration', line 82, 'Next')

Duration 
Arabic - المدة
Hausa - Tsawon lokaci 
Persian - زمان
Pashto - موده 
Afrique - Durée
Somali - Muddada
Swahili - Muda
Korean - 방송 길이

Next
Arabic - لاحق
Hausa - Na gaba
Persian - بعدی
Pashto - بل
Afrique-  SUIVANT
Somali - Xiga 
Swahili - MBELE
Korean - 다음

**Comment by tochwill** [comment]
@JonBeeb - just to follow up from our conversation last week, would it be possible for us to add the context of the translation to the spreadsheet (i.e., Duration [duration time]) or something similar, so we know where we should be interpolating the information around the translation string for each language?

**Comment by tochwill** [comment]
I'm closing this issue as we have translations for all of these services that are now live. I will continue to keep an eye on updates and raise new PRs accordingly when translations are updated.
