### ISSUE TITLE
Add local route for radio schedule json

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#5134]
**Is your feature request related to a problem? Please describe.**
Following this issue: https://github.com/bbc/simorgh/issues/5133 of adding fixture data for Radio schedules, we need to make it available via localhost so that we can fetch the data.

A result of this work would be to visit http://localhost:7080/korean/radio_schedules.json (for example - we can decide on the exact URL structure of this endpoint) and see the relevant JSON data being served.

FYI: we are currently not serving any radio schedules on services with variants.

**Describe the solution you'd like**
- In app/routes/regex create a radioSchedulesDataRegexPath which should match /:service/radio_schedules.json
- In server/index, for the local server, for this regex, we should fetch the radio schedules data.

**Describe alternatives you've considered**

**Testing notes**
Manual testing to ensure that the routes are working as expected.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
Example PR, for Most Read: https://github.com/bbc/simorgh/pull/4592

**Comment by tochwill** [comment]
Dependent on #5133
