### ISSUE TITLE
Create E2E's for PGL pages

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#5154]
**Is your feature request related to a problem? Please describe.**
Now that work has begun to get CPS PGL assets to render with Simorgh we need to create basic e2e tests which will check if a PGL asset exists.

**Describe the solution you'd like**
- [x] Create a new directory in our page e2e's for PGL pages, with test files that follow a similar structure to our MAP pages [tests](https://github.com/bbc/simorgh/tree/latest/cypress/integration/pages/mediaAssetPage). 
- [x] Also, ensure that the PGL page type is being tested for 404's and other relevant error codes. 
- [x] We'll need to check that are some content items on the PGL asset e.g headline, summary, images etc.

Here is a local asset page: http://localhost:7080/pidgin/sport-23252855.

~For now, this is the only local asset so the test should be omitted for other services that aren't Pidgin.~

Local PGL fixtures have now been added for all services through this PR: https://github.com/bbc/simorgh/pull/5168

**Describe alternatives you've considered**

**Testing notes**
Check with a tester to see if e2e's are written correctly.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by mykeels** [comment]
~How can we run cypress tests for only pgl?~

```
npm run test:e2e:interactive
```

then select the test you want to run
