### ISSUE TITLE
Add Schema.org metadata to PGLs

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#5159]
**Is your feature request related to a problem? Please describe.**
We would like to decorate our PGL pages with Schema.org metadata as we do in our Article pages.

**Describe the solution you'd like**
Add/amend the schema.org fields for PGLs to match what is in the tables.

Schema.org metadata is processed through the LinkedData container which can be found [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/LinkedData/index.jsx). Will need to check if there is any pieces of metadata that aren't needed for PGL pages.

Structure of the schema data can be found on the [schema.org](https://schema.org/docs/schemas.html) website.

Note: all remaining fields should be the same as for the article page. [See structured data tool](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.bbc.co.uk%2Fnews%2Farticles%2Fce9v85jlrzzo). With the code snippet section you just have to use the JSON that's generated on the page.

| Field        |  Value           |  Example  | Notes  |
| ------------- | ----------- | ---------- | ---------- |
| description |	Promo Summary | Australia atraviesa una ola de calor extremo que ha provocado miles de incendios. Hay más de una veintena de personas que murieron y unas 1.500 viviendas destruidas. La localidad costera de Mallacoota fue una de las más afectadas.  | This is a recommended field that we don't currently use on articles. Purpose is to provide a short description of the article. PGLs should populate this from the 'Promo Summary' field, i.e. same text as the summary. | 
| headline | Promo Headlines Headline | Las impactantes imágenes de los incendios que están arrasando parte de Australia.  | ~We should use ShortHeadline rather than Headline, as this is the equivalent of the SEO headline.~ | 

The following are sub-fields of **image**, which is an [ImageObject](https://schema.org/ImageObject).

| Field        |  Value           |  Example  | Notes  |
| ------------- | ----------- | ---------- | ---------- |
| `@type` |	`ImageObject` |    |  | 
| `url`	| Service Logo |  https://news.files.bbci.co.uk/ws/img/logos/og/pidgin.png |	  Required field: The URL to an image that is representative of the article or AMP story.    | 
| `width`	| Width of the logo |	 |
| `height`	| Height of the logo |	 |

**Describe alternatives you've considered**

**Testing notes**

Just update/check existing unit tests/snapshots we have for the LinkedData component. Ensure that other page types won't break with this implementation.

Use previously mentioned validation tools to test the implementation.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
n/a

**Comment by andrewscfc** [comment]
~Blocked until completion of https://github.com/bbc/simorgh/pull/5166~

**Comment by andrewscfc** [comment]
Question for refinement:

With the following requirement:
> Note: all remaining fields should be the same as for the article page. 

Should we be including `aboutTags` as in the Optimo article?
https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleMain/index.jsx#L74

Example from test:
https://github.com/bbc/simorgh/blob/latest/src/app/containers/LinkedData/index.test.jsx#L33..L40

**Comment by jimjohnsonrollings** [comment]
> We should use ShortHeadline rather than Headline, as this is the equivalent of the SEO headline.

That's not right.  The Long Headline is the SEO Headline.

**Comment by jimjohnsonrollings** [comment]
> Should we be including aboutTags as in the Optimo article?

I'd be happy if we can.

**Comment by andrewscfc** [comment]
> `We should use ShortHeadline rather than Headline, as this is the equivalent of the SEO headline.`
> 
> That's not right. The Long Headline is the SEO Headline.

I think that note in description is out of date, just to be clear @jimjohnsonrollings we want to use Promo Headlines Headline for headline?

**Comment by jimjohnsonrollings** [comment]
> I think that note in description is out of date, just to be clear @jimjohnsonrollings we want to use Promo Headlines Headline for headline?

TBH I'm not sure what Ares have renamed all the fields
