### ISSUE TITLE
MAPs reporting weird stats to SMP

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#5173]
**Describe the bug**
Jim Ley (SMP) has reported that some MAPs are reporting weird `location.pathname` values to SMP

**To Reproduce**
Have not been able to reproduce - see this slack thread for context (internal only): https://bbcnews.slack.com/archives/C8RGDMHN1/p1579182861096000

Telemetry seems to suggest AMP, iOS and/or Facebook are likely good places to start investigating

**Expected behavior**
Investigate and see if we can fix this

**Comment by jroebu14** [comment]
For a little more context - _I think_ that somehow these measurements are getting added to the end of the iframe src like so `15e14820safari_60412222acceptlanguage2222en-us2222platform2222iphone2222mobile22922hardwareconcurrency22822screenres22null`

making that a bit easier to read:
```
15e14820safari_6041
acceptlanguage: en-us
platform: iphone
mobile: 9
hardwareconcurrency: 8
screenres: null
```

I've had a quick look in the news av morph module, the bump-4 script, the amp-iframe script, psammead and simorgh and can't see anything suspicious in those areas.

**Comment by ryanmccombe** [comment]
Closing as won't fix - impact doesn't seem worth the effort
