### ISSUE TITLE
Navigation: Remove selected state from pages that are not the home page

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5216]
**Is your feature request related to a problem? Please describe.**
Currently, the first item in the navigation is highlighted as active no matter which page the user is on. This is incorrect for all pages other than the homepage. After discussions with the UX team and various stakeholders, it has been decided that we can't consistently determine which navigation item a particular page falls under. To remove the confusing scenario where the first item is selected when the user is not on that page, we will only highlight the homepage link in the nav if the user is on that page, otherwise we will not highlight anything.

This is a solution that we will be adopting temporarily until we are able to define a solution to know which navigation item should be highlighted as active.

**Describe the solution you'd like**
Check to see if the visited URL matches the URL for the homepage in config, and mark that nav item as active if the user is on that page. Otherwise, do not mark any items as active.

**Describe alternatives you've considered**

**Testing notes**
Test that the homepage link is marked as active when visiting the homepage, and nothing is marked as active for other pages.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Blocked on  #4833 (release of the new navigation)

**Comment by tochwill** [comment]
We had to revert the nav, will unblock when it's live!

**Comment by AlistairGempf** [comment]
> We had to revert the nav, will unblock when it's live!

We're live!

**Comment by AlistairGempf** [comment]
Following discussion on Slack, we've decided to select any page that is in the config and is the current page.
