### ISSUE TITLE
Navigation: Hide the burger menu if the user does not have JS enabled

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5218]
**Is your feature request related to a problem? Please describe.**
If the user does not have JS enabled, the burger menu will currently do nothing when tapped. The scrollable navigation currently contains all of the links that are present in the dropdown menu, so for now can be used for the navigation with JS disabled.
 
**Describe the solution you'd like**
This issue: https://github.com/bbc/simorgh/issues/2368 has added support to add css that is only applied when javascript is disabled. Use this approach to hide the menu button in this scenario.

**Describe alternatives you've considered**
We may replicate the dropdown menu for non-js users in the future when the lists in the scrollable nav and the dropdown nav diverge, but for now all links are present in both.

**Testing notes**
For non js browsers the burger menu should appear hidden.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Blocked on #4833 (release of the new navigation)

**Comment by tochwill** [comment]
Need to chat about this again as well as Opera Mini Extreme mode - the dropdown menu works on Opera Mini extreme mode, but horizontally scrollable areas do not, so let's decide a solution that works for both

**Comment by tochwill** [comment]
This bug covers the scrollable issue: we should not remove the burger menu here until we are sure it won't impact Opera Mini extreme users. https://github.com/bbc/psammead/issues/3099

**Comment by amywalkerdev** [comment]
Not going to be fixed by the Home team.
