### ISSUE TITLE
DRY up timestamp in CPS containers

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#5227]
**Is your feature request related to a problem? Please describe.**
> This timestamp (and its associated imports) seem like an obvious immediate candidate for DRYing up, if only to make these files shorter, especially as we now know the timestamp behaviour/appearance should be consistent across CPS page types. But could be done in a follow-up PR.

_Originally posted by @jamesdonoh in https://github.com/bbc/simorgh/pull/5166_

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**

**Comment by joshcoventry** [comment]
We may have to refactor/switch library from Moment.js so may revisit in future.
