### ISSUE TITLE
Footer link going to English page rather than corresponding language page

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#5232]
**Describe the bug**
To describe the bug I will be using the Pidgin page https://www.bbc.com/pidgin/media-51112120

In the footer, there is a link 'Why you fit trust BBC News', which goes to a page about 'Learn how the BBC is working to strengthen trust and transparency in online news'.
The link currently goes to the English language page https://www.bbc.co.uk/news/help-41670342
Whereas in the translations sheet, it gives a link to the Pidgin version of this page: https://www.bbc.com/pidgin/institutional-48528766.

This is also happening with the Igbo and Yoruba pages, and I have not checked yet but this may be a bug across all pages. The link just needs to be replaces with the correct language version of the page which is in the spreadsheet https://docs.google.com/spreadsheets/d/1IE6dvHfOJhYTIhC0kg8aRGnaj3fEg1NH9jQwo5NuUDQ/edit#gid=691318825.

Is this something we can work on?

**To Reproduce**

1. Go to https://www.bbc.com/pidgin/media-51112120 (or any MAP)
2. Click on the top link in the footer. In Pidgin this is called 'Why you fit trust BBC News'
3. Observe the URL and that the page is in English

**Expected behavior**
The link should go the version of the page in the language of the service, as present in the translations spreadsheet linked above

**Screenshots**

![Image 22-01-2020 at 14 21](https://user-images.githubusercontent.com/54575620/72901920-818e7200-3d22-11ea-88ec-870cb2bdbca8.jpg)

![Image 22-01-2020 at 14 19](https://user-images.githubusercontent.com/54575620/72901817-5572f100-3d22-11ea-92ce-37bebcff8ee2.jpg)

![Image 22-01-2020 at 14 19](https://user-images.githubusercontent.com/54575620/72901827-5a37a500-3d22-11ea-992c-657cc54c5813.jpg)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
The other footer links are correct

**Comment by staylos92** [comment]
This now looks to be fixed 👍
