### ISSUE TITLE
MAP timestamp "pops out" at largest breakpoint

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#5248]
**Describe the bug**
The MAP timestamp "pops out" at widescreen resolutions

The timestamp should stay in place at all breakpoints

This can be done by passing `popOut=false` to the timestamp component - see this PR where it was first implemented:

This was introduced in this PR: https://github.com/bbc/simorgh/pull/4939

It was likely broken following the work to split out the CPS page into MAPs, STYs and PGLs

**To Reproduce**
Steps to reproduce the behaviour:

View a MAP (eg, https://www.test.bbc.com/pidgin/23248703) at large resolutions

<img width="670" alt="Screen Shot 2020-01-24 at 10 50 38" src="https://user-images.githubusercontent.com/8601460/73063760-7872e180-3e97-11ea-8fbf-cd23436e719c.png">

**Expected behaviour**
The timestamp should stay in place at all resolutions

<img width="444" alt="Screen Shot 2020-01-24 at 10 51 43" src="https://user-images.githubusercontent.com/8601460/73063795-8c1e4800-3e97-11ea-887b-712a84c6b9dd.png">

Also consider adding a unit test to the page, to prevent this regression in the future

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Comment by rebeccamcginn** [comment]
The lost test can be found here:

https://github.com/bbc/simorgh/commit/e7c03e36cdecd4257f2f6446dd730f41736b7cc8#diff-97ffb7c6cce204795fdc6d6ad00acd16L228
