### ISSUE TITLE
Onward journeys schema definition

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#526]
**Is your feature request related to a problem? Please describe.**
Following the merging of https://github.com/bbc/simorgh/issues/524 we will have some scenario data for onward journeys. These scenarios should have a schema definition.

**Describe the solution you'd like**
We should update the `schema.yaml` to have an accurate definition of the onward journey data format using the OpenAPI 3.0 specification.

**Comment by jtart** [comment]
@pjlee11 did we decide that we want a schema definition for OJs?

**Comment by pjlee11** [comment]
@jtart assuming they will be in the Ares payload we should validate them

**Comment by pjlee11** [comment]
Should we do this? The payload for OJs does not come with the rest of the article data feed as previously expected. 

Closing as this does not feel valid any more
