### ISSUE TITLE
CSP errors with AMPAnalytics and chartbeat

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#5276]
**Describe the bug**
Seeing chartbeat errors via amp-analytics on all AMP pages on live (chartbeat has been disabled on our test environment to debug).

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'www.bbc.com/thai.amp'
2. Open the developer tools
3. See amp-analytics erros in the console

**Expected behaviour**
Chartbeat via amp-analytics should be working correctly and not surfacing any errors

**Screenshots**
www.bbc.com/thai
![image](https://user-images.githubusercontent.com/14273378/73162512-d98ff480-40e5-11ea-9461-0412b94547e6.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
`https://cdn.ampproject.org` is in the script-src directive for AMP pages, but not the connect-src directive. We are trying to hit a json endpoint here, not a script. I have a link to a PR that adds the source to the script-src directive in mozart, that I will post in slack as that is not open source. We need to do the same for content-src.

**Comment by tochwill** [comment]
Once this is fixed we should turn chartbeat back on in test.

**Comment by sareh** [comment]
Re-opening issue since we need the Mozart Routing PR change to fix this on Test/Live envs. https://github.com/bbc/mozart-routing/pull/1147
