### ISSUE TITLE
Use page type constants in e2e tests

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#5280]
**Is your feature request related to a problem? Please describe.**
We have a list of [page type constants](https://github.com/bbc/simorgh/blob/latest/src/app/routes/utils/pageTypes.js) which should be used when referring to different page types. We are beginning to make use of them within Simorgh and our e2e's should reflect that. For example in the [switch statement in testsForAllPages](https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllPages.js#L172).

We should also investigate if there are other places where this can be updated.

**Describe the solution you'd like**
- Refactor e2es to use `pageType`s that match our page type constants.

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
No longer required
