### ISSUE TITLE
Update config for new MAPs E2Es in test (Thai Punjabi Afaan Oromoo Amharic Tigrinya Marathi Telugu Gujarati)

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#5283]
**Is your feature request related to a problem? Please describe.**
Need to run E2Es in the test environment on the next services to go live

**Describe the solution you'd like**
Find URLs for 

- [x] Thai /thai/thailand-23248713 (live stream)

- [x] Punjabi /punjabi/media-23248705

- [x] Afaan Oromoo https://www.test.bbc.com/afaanoromoo/23149891

- [x] Amharic Amharic/news-23263266

- [x] Tigrinya Tigrinya/news-23263262

- [x] Marathi https://www.test.bbc.com/marathi/media-23127353

- [x] Telugu Telugu/international-23263261

- [x] Gujarati https://www.test.bbc.com/gujarati/other-news-23130286

- [x] Korean https://www.test.bbc.com/korean/media-23248686

and update the config to run the E2Es on test.
When these are run we can see if any of these services have issues on MAPs.

- [ ] This feature is expected to need manual testing.

**Comment by LilyL0u** [comment]
@ryanmccombe If a page is working on test but not locally, could it mean it just doesn't have the right fixture data for the video to work? Do we need to add fixture data for all the services so we can run the tests locally?

**Comment by ryanmccombe** [comment]
Hey - yep - when running Simorgh locally, it is getting the data from the /data folder within Simorgh: https://github.com/bbc/simorgh/tree/latest/data

Most of those fixtures are created by just copying and pasting live or test assets that exist in CPS into Simorgh's data directory.

However, there's no connection between local simorgh and the data in CPS.  Local is a totally different data source

Assets can exist in local but not test
Assets can exist in test but not local
Assets can exist in both test and local but have different data

**Comment by LilyL0u** [comment]
Fixed Thai asset
