### ISSUE TITLE
Only render related content of type `CPS` for all CPS asset PageTypes

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#5292]
**Is your feature request related to a problem? Please describe.**
For Related Contents onward journeys (`type: "see-alsos"` ), we want to be able to render only related content with the type `CPS`. Other types do not contain all of the required properties to render a story promo.

The reason for only rendering related items with a type of CPS is because other types do not always contain the required values to render a story promo. For example types of `link` on container a name and a uri. This means we currently render a blank promo item e.g.

![image](https://user-images.githubusercontent.com/14273378/73351615-4c84a100-4287-11ea-9730-fd8db9e35d79.png)

**Describe the solution you'd like**
Write a new preprocess rule to remove any item from the `see-also` section that does not have a type of `cps`.

The frontend component should only render promos with a type of `cps`. If no items are included the in see-also's array we should not render the related content component. 

**Describe alternatives you've considered**

**Testing notes**
Ensure we have snapshot test coverage and unit test coverage for the component.
Write unit tests for the new preprocess rule.

Example of a page containing related content, but no `type: "see-alsos"` related content: https://www.bbc.com/pashto/arts-and-literature-50230813

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
ProProcess rules for CPS Assets: https://github.com/bbc/simorgh/tree/latest/src/app/lib/utilities/preprocessor/rules/cpsAssetPage

**Comment by andrewscfc** [comment]
Some (hopefully) useful info for refinement from me @oluoluoxenfree and @HarveyPeachey:

- Asset with only TopCat2 onward journeys - **edge case we need to cover, do we delete the full onward journeys section?**: 
  - http://localhost:7080/arabic/art-and-culture-38260491
  - https://github.com/bbc/simorgh/blob/latest/data/arabic/cpsAssets/art-and-culture-38260491.json

- Asset with a mix of CPS and TopCat2 onward journeys
  - http://localhost:7080/azeri/azerbaijan-44208474
  - https://github.com/bbc/simorgh/blob/latest/data/azeri/cpsAssets/azerbaijan-44208474.json

## Implementation Considerations
### Filter in `CpsRelatedContent` Component
We could receive the data in the frontend component, but filter out 'at the last minute'
https://github.com/bbc/simorgh/blob/latest/src/app/containers/CpsRelatedContent/index.jsx 

*Question:* Is there any immediate prospect of us having to render TopCat2 onward journeys, if very soon maybe doing it here is the best place?

### Filter with pre-processor rule
We can remove the topcat2 onward journeys in a pre-processor rule, adding one here: https://github.com/bbc/simorgh/tree/latest/src/app/lib/utilities/preprocessor/rules/cpsAssetPage 

This removes the onward journeys at the earliest possible opportunity, seems the logical place to perform such filtering; this does add complexity in an area under debate https://github.com/bbc/simorgh/issues/5175
