### ISSUE TITLE
ATI analytics for PGLs

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#5293]
**Is your feature request related to a problem? Please describe.**
We want to add the ability to track ATI analytics for PGLs on page load.

**Describe the solution you'd like**
When I go to a photo gallery page, then a pageload event fires to ATI that includes the values below:

Based on example: https://www.bbc.com/mundo/noticias-50957121
AReS data: [https://ares-broker.api.bbci.co.uk/api/asset/mundo/noticias-50957121

ATI Label | ATI Code | Value | Source
-- | -- | -- | --
Countername/ Page | - | mundo.also_in_the_news.photo_gallery.50957121.page("counterName" in payload) | AReS
Destination | 598342 | WS_NEWS_LANGUAGES (on live) | Simorgh
  | 598343 | WS_NEWS_LANGUAGES_TEST (on test) | Simorgh
Producer  Level 2 | 62 | Mundo | Simorgh
Custom Site Variables |   |   |  
Content ID | - | [urn:bbc:cps:3979b8e0-9b81-9a4b-a863-5fd361cdc972] (urn:bbc:cps:curie - this is in AReS payload in "curie", which is the GUID for the content:"http://www.bbc.co.uk/asset/3979b8e0-9b81-9a4b-a863-5fd361cdc972" | AReS
App Type | - | responsive OR amp | Simorgh
App name | - | news-mundo | Simorgh
Language | - | es | AReS
URL | - | https://www.bbc.com/mundo/noticias-50957121 | Simorgh
Content Type | - | article-photo-gallery | This needs to be set
Page Title | - | Defined as {title} - BBC News Mundo where content title is Promo Headline from AReS payload | AReS for title / Simorgh for Brand
Referrer URL (x6) | - | The referrer URL, where available. Not set otherwise | Should be set by Library
Publication Date | - | [2020-01-23T15:49:31+00:00](firstPublished but needs to be converted from unix time) | AReS
Updated Date | - | [2020-01-23T15:51:48+00:00](lastUpdated but needs to be converted from unix time) | AReS
LDP Things (x13) | - | aresResponse.metadata.tags.about[i].thingLabel  separated by ~E.g. Life~Science | AReS
LDP Things IDs (x14) | - | aresResponse.metadata.tags.about[i].thingId    separated by ~E.g. 0239ab33-1cfc-4f5d-babb-a8159711af3e~0f469e6a-d4a6-46f2-b727-2bd039cb6b53 | AReS
Campaign | - | [WS - Update me] (Can be multiple values separated by ~  see: Campaigns / campaignName in payload) | AReS
Category | - | [News] (defined as categoryName in the payload) | AReS
Library Version | - | simorgh | TBC

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by lizcameron** [comment]
See https://github.com/bbc/simorgh/issues/5294 for work the media team have done to track LDP topic data in ATI

**Comment by amywalkerdev** [comment]
Should mostly be covered by #5233, will need to check the values are all correct once work is merged

**Comment by rhenshaw56** [comment]
tested mostly on http://localhost:7080/pidgin/sport-23252855
- [X] Countername / Page
- [X] Destination
- [X] Level 2 (70 for pidgin)
- [ ] Custom Site Variables
- [X] Content ID (urn:bbc:ares::asset:pidgin/sport-23252855)
- [X] App Type
- [X] App name
- [X] Language
- [X] URL
- [X] Content Type
- [X] Page Title
- [X] Referrer URL - present but empty on localhost as no inline links on PGLs to test
- [X] Publication Date
- [X] Updated Date
- [X] LDP Things - present on http://localhost:7080/afaanoromoo/oduu-41217768
- [X] LDP Things IDs
- [X] Campaign as x16 on http://localhost:7080/burmese/media-47680015
- [X] Category as x17
- [X] Library Version as x8

**Comment by amywalkerdev** [comment]
Closing this as we've tested locally and covered everything. Once we route something to test we can check again
