### ISSUE TITLE
Use ATI View Tracking Public API in `ATIAnalytics` Container

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#5304]
**Is your feature request related to a problem? Please describe.**
This issue intends to resolve a confusing and duplicated set of logic that made #5233 take longer to implement and opened us up to [a buggy implementation going live](https://github.com/bbc/simorgh/pull/5233#pullrequestreview-349587287).

1. As it stands in the `ATIAnalytics` container, we build the params to send to ATI using the respective 'param builder' for each asset type:
https://github.com/bbc/simorgh/blob/807a9816fdb8568ba28c29065ac9b7906b616967/src/app/containers/ATIAnalytics/index.jsx#L6..L10
1. We switch to each 'param builder' based on asset type:
https://github.com/bbc/simorgh/blob/807a9816fdb8568ba28c29065ac9b7906b616967/src/app/containers/ATIAnalytics/index.jsx#L17..L46
1. Then dispatch our page view to ATI:
https://github.com/bbc/simorgh/blob/807a9816fdb8568ba28c29065ac9b7906b616967/src/app/containers/ATIAnalytics/index.jsx#L48..L53

An API already exists that does much of 1 and 2 above but we have not used it in `ATIAnalytics`: https://github.com/bbc/simorgh/blob/807a9816fdb8568ba28c29065ac9b7906b616967/src/app/containers/ATIAnalytics/params/index.js#L79 

You can see the duplicated logic here https://github.com/bbc/simorgh/blob/807a9816fdb8568ba28c29065ac9b7906b616967/src/app/containers/ATIAnalytics/params/index.js#L38..L56 

**Describe the solution you'd like**
Ideally we would like to use [the API](https://github.com/bbc/simorgh/blob/807a9816fdb8568ba28c29065ac9b7906b616967/src/app/containers/ATIAnalytics/params/index.js#L79) rather than duplicate logic, we did quickly try this but got quite a few errors, there may be some work getting the API fit for use.

**Describe alternatives you've considered**
Potentially the  [the API](https://github.com/bbc/simorgh/blob/807a9816fdb8568ba28c29065ac9b7906b616967/src/app/containers/ATIAnalytics/params/index.js#L79) could be deleted instead, resolving the duplication. If we were to do this, we would have to consider where the currently unused 'click tracking' logic would go: https://github.com/bbc/simorgh/blob/807a9816fdb8568ba28c29065ac9b7906b616967/src/app/containers/ATIAnalytics/params/index.js#L70

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
Tackle as part of https://github.com/bbc/simorgh/issues/5743
