### ISSUE TITLE
Create OJ samples for prod scenarios

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#531]
**Is your feature request related to a problem? Please describe.**
Production scenarios don't currently have sample data for onward journeys

**Describe the solution you'd like**
Write some that are sufficiently generic.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ChrisBAshton** [comment]
Hi @jimjohnsonrollings - enlighten me - what do we do with these issues? :-) 

I wouldn't know where to start adding sample data for onward journeys, what should be in that test data, etc- is this something you'll be raising a PR for?

**Comment by jimjohnsonrollings** [comment]
@ChrisBAshton typically assign it to me, and badger me to raise a PR :)

**Comment by ChrisBAshton** [comment]
Not needed for now.
