### ISSUE TITLE
Topcat2 Route and Regex

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#5316]
**Is your feature request related to a problem? Please describe.**
The route structure for cps and topcat2 content differs from one another, the data structure should be equal which means we can utilise the same page containers across CPS and Topcat2 content.

| PageType         | URL Path                                                                                                                                                                                 |
|------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Media Asset Page | `/afrique/nos_emissions/2014/11/141111_porno_vengeur_ouganda`<br>`/arabic/multimedia/2014/05/140515_kenia_children_sex_trade`<br>`/azeri/multimedia/2012/09/120919_georgia_prison_video` |
| PGL              | `/afrique/monde/2014/05/140527_40_hip_hop`                                                                                                                                               |

**Describe the solution you'd like**
Add a new route to Simorgh to support the Topcat2 path structure and utilise the existing page type containers.

Add fixture data for Topcat2 assets

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Simorgh Routes: https://github.com/bbc/simorgh/blob/latest/src/app/routes/index.js
Simorgh Routes Regex Matchers: https://github.com/bbc/simorgh/blob/latest/src/app/routes/regex/index.js

**Comment by karinathomasbbc** [comment]
Hi @hindsc52 I have a draft PR for this if you wanted to have a look #5291

**Comment by chris-hinds** [comment]
👋 @karinathomas had a quick look, for this to support PGL assets I think we need to loosen the regex a little.

`/afrique/monde/2014/05/140527_40_hip_hop` didnt work locally unless I used this regex `[a-z-_]{1,}/[0-9]{4}/[0-9]{2}/[0-9]{6}[a-z0-9-_]{0,}`

note the extra `0-9` near the end of the matcher.

**Comment by karinathomasbbc** [comment]
Reopening to use for tracking addition of fixture data.

**Comment by joshcoventry** [comment]
@hindsc52 Is this still needed?

**Comment by karinathomasbbc** [comment]
I think we can close it!!
