### ISSUE TITLE
E2e cypress test for most read component

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#5319]
**Is your feature request related to a problem? Please describe.**
Cypress test to verify whether the component is rendered on article page for now on both canonical and amp should be added(may be under testForAllPages) depending on the service config for which the most read component is enabled.

**Describe the solution you'd like**
- check component is rendered on a page, depending on the toggle values

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
We need atleast locally a page which has most read component rendered to start writing the cypress test.

**Comment by PriyaKR** [comment]
@jimjohnsonrollings @laurapsn can we have the list of services which will have the most read component?

**Comment by PriyaKR** [comment]
Its blocked by the component not available on pages.

**Comment by jimjohnsonrollings** [comment]
@PriyaKR All services except Scotland, Archive, and Learning English (which isn't in Simorgh yet).
