### ISSUE TITLE
Update video blocks in scenario data

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#533]
**Is your feature request related to a problem? Please describe.**
The video blocks in the scenario data don't currently reflect the latest data design

**Describe the solution you'd like**
Update the scenarios

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sareh** [comment]
Closed as duplicate (https://github.com/BBC-News/simorgh/issues/204)
