### ISSUE TITLE
Reinstate archive e2es and smoke tests

### ISSUE THREAD

**Issue by amywalkerdev** [bbc/simorgh#5339]
**Is your feature request related to a problem? Please describe.**
In #5337 we disabled the archive e2e tests as due to a redirect loop caused by archive not being whitelisted for .com:

```
  > Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://www.bbc.com/archive/articles/manifest.json
```

We also disabled the Mozart smoke tests for archive in https://github.com/bbc/mozart-smoke-test/pull/178

One the redirect loop issue is resolved we need to reinstate these tests.

**Describe the solution you'd like**
- Re-enable e2e tests
- Re-enable smoke tests

**Comment by jamesdonoh** [comment]
Blocked till whitelisting for .com completed on live (due Thu 20 Feb)

**Comment by chris-hinds** [comment]
PR 178 in the smoke-tests repo is what was merged to remove the smoke tests for /archive

**Comment by 12** [comment]
This should've been closed with the above merged PR. My bad.
