### ISSUE TITLE
Update media indicator for Index Alsos

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#5340]
**Is your feature request related to a problem? Please describe.**
After https://github.com/bbc/psammead/pull/3029 is merged, we should update the version of Media Indicator to 3.0.0 and use the `isInline` prop.

**Describe the solution you'd like**
Update [psammead-story-promo/Index Alsos tests](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/src/IndexAlsos/index.test.jsx) and [test helpers](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/testHelpers/IndexAlsosContainer.jsx)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Original issue: https://github.com/bbc/psammead/issues/3019

**Comment by j-pendlebury** [comment]
Blocked on https://github.com/bbc/psammead/pull/3029 and https://github.com/bbc/psammead/issues/3039

**Comment by DenisHdz** [comment]
This is being done as a part of https://github.com/bbc/simorgh/issues/4562

**Comment by sareh** [comment]
Closing this issue in favour of the main frontpage layout issue (https://github.com/bbc/simorgh/issues/4562) and PR (https://github.com/bbc/simorgh/pull/5139) in which it is covered.
