### ISSUE TITLE
STY Byline PreProcess rule

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#5388]
**Is your feature request related to a problem? Please describe.**
CPS provides a name and a title that should be rendered as a a byline on an STY asset.

This data is available from the STY data feed under: `promo > byline`. We should render the `name` and `title` fields. if `byline.name` and `byline.title` is not available we should use the values from the persons array.

**Describe the solution you'd like**
The processor should produce a valid Optimo style block with a type of byline and be name spaced under `cps`.

Note: The Byline should be rendered directly beneath the title, above the timestamp.

**Describe alternatives you've considered**

**Testing notes**
Testing will be carried out in an issue where we integrate the Psammead Byline component with Simorgh.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by neildoughty** [comment]
I think this is what we want for WS - to use the localised byline information, which in terms of CPS content can sometimes be an overtype of an English journalist. 
To use the overtype where one is present, and if one isn’t use the original value.
Which I think means first look for this value:
byline.name - ਪ੍ਰਿਥਵੀ ਰਾਜ
byline.title - ਬੀਬੀਸੀ ਪੱਤਰਕਾਰ

And if it’s not there, use this one:
byline.person[0].name - Abdujalil Abdurasulov
byline.person[1].function - BBC News Almata

**Comment by neildoughty** [comment]
Lots more info here in a jira ticket: NEWSPALDECOM-524
