### ISSUE TITLE
STY: Incorrect positioning of Introduction

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#5402]
**Describe the bug**
According to NEWSART-905, with regards to a STY `introduction`:

> it appears after the H1 and timestamp but before the image and caption block(s)

Currently, it appears after the first image and caption. This violates the criteria listed above.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run Simorgh locally
2. Go to http://localhost:7080/mundo/23263889
3. See introduction snippet after the first image and caption

**Expected behaviour**
The introduction should be above the image and caption block.

**Screenshots**
![image](https://user-images.githubusercontent.com/7690572/73832960-156f3c00-4801-11ea-98a0-fef2260e3a8b.png)

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Comment by chris-hinds** [comment]
I think the requirements for this are incorrect. If we look at existing STY assets on PAL the introduction paragraph appears under the first image. https://www.bbc.com/nepali/news-51381554

![image](https://user-images.githubusercontent.com/14273378/73833338-bcec6e80-4801-11ea-8d49-9cd3ae45441b.png)

**Comment by 12** [comment]
Confirmed with Liz that this phrasing was not correct. This is a non-issue.
