### ISSUE TITLE
[Investigate] Samsung browser mini-player does not display the placeholder image for videos

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#5405]
Samsung browser mini-player does not display the placeholder image for videos, while the Chrome browser does

Using https://www.bbc.com/marathi/media-51349174

![screenshot_20200205-130233_samsung_internet](https://user-images.githubusercontent.com/58214768/73844703-fc728500-4818-11ea-8941-a3fdd26b7d7f.jpg)

Not sure if this is expected behaviour, or whether this is acceptable by editorial.

Please note, not all MAP pages are affected - there are examples of MAPs which display the images OK

**Comment by gavinspence** [comment]
Closing as the content is still accessible, and Samsung account for a low amount of traffic
