### ISSUE TITLE
Create E2E's for STY Pages

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#5407]
**Is your feature request related to a problem? Please describe.**
We need basic E2E tests for STY pages to check they work correctly.

**Describe the solution you'd like**
- [ ] Also, ensure that the STY page type is being tested for 404's and other relevant error codes. 
- [ ] Create a new directory in our page e2e's for STY pages, with test files that follow a similar structure to our PGL pages [tests](https://github.com/bbc/simorgh/tree/latest/cypress/integration/pages/photoGalleryPage). 
- [ ] We'll need to check that there are some content items on the STY asset e.g Headline, Byline, Timestamp, Introduction
- [ ] Enable this E2E test on our test environment by modifying: https://github.com/bbc/simorgh/blob/latest/cypress/support/config/services.js

Asset to use:
- http://localhost:7080/pidgin/tori-23169025
  - Add fixture data for this asset
- https://www.test.bbc.com/pidgin/tori-23169025

We want to match this structure used for the article tests: https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/articles/index.js 
  - Adapt page type here: https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/articles/index.js#L19
  - Add STY specific tests in `tests.js` e.g. for the byline: https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/articles/index.js#L3 
  - Add more general tests into `testForAllPages` e.g. timestamp tests: https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllPages.js#L432 

**Describe alternatives you've considered**
We can consider using our existing Article E2E test implementation for STYs too; we could either fork off the old implementation or use the same tests.

**Testing notes**
Pair with @paruchurisilpa to write these test for knowledge share.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Created #5480 to expand our available test assets.

**Comment by HarveyPeachey** [comment]
When this ticket has been completed, you will run into issues with the `amp-img` e2e test which is contained within `testsForALLPages.js` until https://github.com/bbc/simorgh/issues/5421 has been closed and merged. It may be best that if someone has started work on that issue, that you pair with them and then move onto this ticket.

**Comment by mykeels** [comment]
Blocked by #5421 till we have analytics for STY pages
