### ISSUE TITLE
Run CodeClimate checks on Jenkins

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#541]
**Is your feature request related to a problem? Please describe.**
Currently we are running CodeClimate code coverage checks on Travis https://github.com/bbc/simorgh/blob/latest/.travis.yml

**Describe the solution you'd like**
We should run CodeClimate in Jenkins.
There is a docker image provided for the CodeClimate CLI and we should aim to use this. https://github.com/codeclimate/codeclimate#installation

**Comment by jtart** [comment]
@sareh why do we want to move this away from Travis to Jenkins?

**Comment by ChrisBAshton** [comment]
After chatting to Sareh, seems like this isn't relevant anymore.

**Comment by dr3** [comment]
Howcome @ChrisBAshton?
