### ISSUE TITLE
Add page, OG and Twitter metadata to STYs

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#5423]
**Is your feature request related to a problem? Please describe.**
We want to make sure STY pages contain the correct page metadata, OG data and Twitter data.

**Describe the solution you'd like**
Ensure STYs contain the following metadata.

The metadata logic can be found in the metadata [container](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Metadata/index.jsx). And the container is used to produce the metadata for that asset.

Generic:
- [x] description = Promo summary

Open Graph (Facebook):
- [x] og:title =	promo -> headlines -> headline
- [x] og:type =	article	
- [x] og:description =	Promo summary 
- [x] og:site_name =	Service name	
- [x] og:locale =	Service locale	
- [x] og:url =	Canonical URL of article
- [x] og:image = Promo -> IndexImage (same as promo image used on FP ).  If it doesn't exist, use Service -> Logo
- [x] og:image:alt = Promo -> IndexImage -> AltText. If it doesn't exist, use the Service -> Logo -> AltText
- [x] article:author = should be article author [from service config]

Twitter:
- [x] twitter:creator = Service name e.g. `@BBCMundo` [from service config]
- [x] twitter:site = Service name e.g. `@BBCMundo` [from service config]
- [x] twitter:title =	promo -> headlines -> headline
- [x] twitter:description =	Promo Summary
- [x] twitter:img:src = promo -> IndexImage (same as promo image used on FP ).  If it doesn't exist, use Service -> Logo
- [x] twitter:image:alt = Promo -> IndexImage -> AltText. If it doesn't exist, use the Service -> Logo -> AltText

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]
https://developers.facebook.com/tools/debug/ -  Validator for Facebook metadata
https://cards-dev.twitter.com/validator - Validator for Twitter metadata
These tools might only work with live URLs and not with code snippets. So more investigation might need to be done to find other methods of validation of these two instances of metadata.
Use [HTML Pasta](https://htmlpasta.com/) to host the site or Github Pages.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
- A reference to similar work: https://github.com/bbc/simorgh/issues/5158

**Comment by FK78** [comment]
Index Image does not exist in the test data for STYs, but does for PGL and MAP pages. I've ticked them off as the Service Logo is used in it's place.

![Screenshot 2020-02-06 at 15 36 32](https://user-images.githubusercontent.com/34196381/73952209-a411b500-48f6-11ea-97ce-8b7210b18886.png)
