### ISSUE TITLE
Add schema.org metadata to STYs

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#5424]
**Is your feature request related to a problem? Please describe.**
We would like to decorate our STY pages with Schema.org metadata as we do in our Article pages.

**Describe the solution you'd like**
Add/amend the schema.org fields for STYs to match what is in the tables.

Schema.org metadata is processed through the LinkedData container which can be found [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/LinkedData/index.jsx). Will need to check if there are any pieces of metadata that aren't needed for STY pages.

Structure of the schema data can be found on the [schema.org](https://schema.org/docs/schemas.html) website.

**Note**: all remaining fields should be the same as for the article page, _including the presence of `videoObject `or `audioObject `markup where AV is present in an article_. Further issues/refinement may be needed if `videoObject `and `audioObject `are not present.

[See structured data tool](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.bbc.co.uk%2Fnews%2Farticles%2Fce9v85jlrzzo). With the code snippet section you just have to use the JSON that's generated on the page.

Based on example: https://www.bbc.com/mundo/noticias-internacional-51266689

| Field        |  Value           |  Example  | Notes  |
| ------------- | ----------- | ---------- | ---------- |
| description |	Content block Role: Introduction | El controvertido Brexit llega finalmente con la salida oficial de Reino Unido de la Unión Europea (UE) este 31 de enero, aunque la incertidumbre respecto a sus efectos prácticos todavía está lejos de ser despejada. |  | 
| headline | Promo Headlines Headline | Brexit: qué cambiará para visitar, trabajar y estudiar en Reino Unido tras la salida del país de la Unión Europea | | 
| type | categoryName | Use this mapping to transform category to the schema-appropriate value: <br>'News' = 'ReportageNewsArticle', <br>'Explainer' = 'BackgroundNewsArticle', <br>'Analysis' = 'AnalysisNewsArticle', <br>'Opinion' = 'OpinionNewsArticle', <br>'Feature' = 'ReportageNewsArticle',<br>'Infographic' = 'ReportageNewsArticle', <br>'Interactive' = 'ReportageNewsArticle', <br>'Newsbeat Investigates' = 'ReportageNewsArticle', <br>'Quiz' = 'ReportageNewsArticle', <br>'Summary' = 'ReportageNewsArticle', <br>'You what?' = 'ReportageNewsArticle', <br>'Advertiser Content' = 'AdvertiserContentArticle', <br>'Review' = 'ReviewNewsArticle', <br>'Ask the Audience' = 'AskPublicNewsArticle' | | 

The following are sub-fields of **image**, which is an [ImageObject](https://schema.org/ImageObject).

| Field        |  Value           |  Example  | Notes |
| ------------- | ----------- | ---------- |---------- | 
| @type |	ImageObject |    |  | 
| url | Promo Index Image | https://ichef.bbci.co.uk/news/208/cpsprodpb/17D42/production/_110620679_gettyimages-542984918.jpg  | Fallback to service logo if no image available   | 
| width	| Width of the image|	 | |
| height	| Height of the image |	 | |

**Describe alternatives you've considered**

**Testing notes**

Just update/check existing unit tests/snapshots we have for the LinkedData component. Ensure that other page types won't break with this implementation.

Use previously mentioned validation tools to test the implementation.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
See https://github.com/bbc/simorgh/issues/5159 for similar work on PGLs.

**Comment by FK78** [comment]
Do we need to check the contents of the `videoObject` and `audioObject`?

**Comment by FK78** [comment]
**Category**
| Field         | Value       | Example    | Notes      |
| ------------- | ----------- | ---------- | ---------- |
| description |  content -> blocks -> role | Introduction  |  Not present |
| headline | promo -> headlines -> headline | WS STY TEST - Full Headline | Present | 
| type | promo -> categoryName | N/A | Not present |

**ImageObject**
| Field         | Value       | Example    | Notes      |
| ------------- | ----------- | ---------- | ---------- |
| @type 	| ImageObject | N/A 	   | Present 	|
| url		| promo -> indexImage -> href | http://b.files.bbci.co.uk/113CB/test/_63730607_dogs2-kayleegarrick.jpg | Present, currently using service logo. | 
| width		| promo -> indexImage -> width | 976 | Present |
| height	| promo -> indexImage -> height | 549 | Present |
