### ISSUE TITLE
Update project trust links for Hindi, Indonesia, Gahuza, Tamil and Burmese

### ISSUE THREAD

**Issue by OlgaLyubin** [bbc/simorgh#5433]
**Is your feature request related to a problem? Please describe.**
Hindi, Indonesia, Gahuza, Tamil and Burmese have incorrect Project Trust Links.

**Describe the solution you'd like**
Replace project trust links in service configs with correct ones:

Indonesia | https://www.bbc.com/indonesia/institutional-49283175 
Gahuza | https://www.bbc.com/gahuza/institutional-49283343 
Burmese | https://www.bbc.com/burmese/institutional-51387206 
Hindi | https://www.bbc.com/hindi/institutional-50223932 
Tamil | https://www.bbc.com/tamil/institutional-50288575 

**Describe alternatives you've considered**
N/A

**Testing notes**
- [x] This feature is expected to need manual testing.

**Additional information**
Relevant JIRA tickets: WSFRONTPGS-279 and WSFRONTPGS-269

**Comment by JonBeeb** [comment]
Just a note that Tamil is an update to a current link
