### ISSUE TITLE
[Investigate] Implement chartbeat for MAP pages

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#5442]
See existing implementation for articles 

There should be a `<Chartbeat>` component which we can reuse

- [ ] Speak to Chris Hinds or Articles team for additional information

**Comment by pharingee** [comment]
Initial investigation shows that we can reuse the `<ChartbeatAnalytics>` component with some tweaks to it. The current [implementation](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js#L31) only supports front-pages and articles in the `getType` function. We can update this utility to get support for MAPs and live radio pages.

To get Chartbeat working for MAP pages, we need to update the current `ChartbeatAnalytics` component to accept MAP and Live radio as valid page types and use it in a new `MapChartbeat` component which will implement the `cbq` property.

| Property | MAP implementation | Live Radio Implementation |
|--------|-----------------------|-----------------------------|
| `uid` | Unchanged | Unchanged |
| `domain` | Unchanged | Unchanged |
| `useCanonical` | Unchanged | Unchanged |
| `sections` | Add MAP to `getType` in utils | Add Live Radio to `getType` in utils |
| `bbc_hid` | Unchanged | Unchanged |
| `title` | Add MAP to `getTitle` | Add LiveRadio to `getTitle` |
| `cbq` | Add to `MapChartbeat` component | Add to `MapChartbeat` component |
| `type` | Add MAP `getType` in utils | Add Live radio to `getType` in utils |

**Comment by aeroplanejane** [comment]
@pharingee Shall we close this seeing as we've raised: https://github.com/bbc/simorgh/issues/5521?

**Comment by LilyL0u** [comment]
URLs -

MAPS:
http://pal.test.bbc.com/pidgin/media-51466343
https://www.test.bbc.com/pidgin/media-51466343

Live radio:
http://pal.test.bbc.com/korean/bbc_korean_radio/liveradio
https://www.test.bbc.com/korean/bbc_korean_radio/liveradio

**Comment by pharingee** [comment]
> @pharingee Shall we close this seeing as we've raised: #5521?

I think so.
