### ISSUE TITLE
Add Legacy MAP example to storybook

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#5448]
We should ideally include a couple of examples:

- video
- audio
- images with copyright
- images without copyright
- links
- related content

**Comment by gavinspence** [comment]
Does this need to be part of this milestone? I thought we discussed only needing to put components available in storybook. As a TC2 MAP is equivalent to a CPS MAP I don't see the need.

**Comment by karinathomasbbc** [comment]
I think it should be included in this milestone due to the difference in media playback - playlist vs vpid?

**Comment by gavinspence** [comment]
Not required
