### ISSUE TITLE
Add additional unit testing for images with copyright holder

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#5449]
AReS Data for https://www.bbc.com/bengali/multimedia/2014/02/140206_fp_witness_mother_teresa (https://ares-broker.api.bbci.co.uk/api/asset/bengali/multimedia/2014/02/140206_fp_witness_mother_teresa) has an image which has a copyright

We need to add additional unit tests to the image renderer to ensure that copyright is included as expected in the image.

**Comment by aeroplanejane** [comment]
Do we have unit tests in place for this already? PGLs are currently being built out, think this might be something they are looking at?

**Comment by ryanmccombe** [comment]
@aeroplanejane

**Comment by aeroplanejane** [comment]
FYI An agreement has been reached with editorial that they will accept responsibility where copyright is missing from an image and we will render any images on TC2s regardless of whether copyright is present or not. Before CPS and current workflows, WS have added an overlay watermark to images or included copyright in the caption and copyright metadata has been absent. However, this shouldn't negate the need to write unit tests generally if you think they are required. cc @gavinspence

**Comment by ryanmccombe** [comment]
test

**Comment by gavinspence** [comment]
Closing as per comment above.
