### ISSUE TITLE
A11y Swarm on PGLs

### ISSUE THREAD

**Issue by amywalkerdev** [bbc/simorgh#5450]
**Is your feature request related to a problem? Please describe.**
We now have PGLs on test for Gujarati and would like to put them live soon. We should do an accessibility swarm on an example page.
(see https://bbc.github.io/accessibility-news-and-you/accessibility-swarms)

**Describe the solution you'd like**
- Arrange and carry out team swarm as described above
- Create and prioritise GitHub bug issue for any problems that are found, seeking guidance from a11y Champion as necessary

**Comment by amywalkerdev** [comment]
Use screenreader UX from MAPs and articles if needed

**Comment by andrewscfc** [comment]
Organised for 11/02 15.00 - 17.00 

~~We will use this URL for the swarm https://www.test.bbc.com/pidgin/media-43768328?renderer_env=live~~

We can use this url instead as it has copyright on the images: https://www.test.bbc.com/pidgin/media-43768328?renderer_env=live thanks @jimjohnsonrollings

**Comment by andrewscfc** [comment]
Created all our issues from the swarm:
#5514 #5515 #5516 #5507 

Closing as done

**Comment by jimjohnsonrollings** [comment]
Is there one for the background colour of the H2 in the onward journeys?

**Comment by andrewscfc** [comment]
> Is there one for the background colour of the H2 in the onward journeys?

I don't think so, can you create one @jimjohnsonrollings ?

**Comment by jimjohnsonrollings** [comment]
Yup - #5522
