### ISSUE TITLE
UX Review on PGL

### ISSUE THREAD

**Issue by amywalkerdev** [bbc/simorgh#5452]
**Is your feature request related to a problem? Please describe.**
We need to review the UX for an example PGL now that we have them on test for Gujarati.

**Describe the solution you'd like**
An engineer to sit down with UX and review the current page design for PGLs. Any issues from it to be prioritised and raised.

**Comment by andrewscfc** [comment]
Organised with UX to review: https://www.test.bbc.com/pidgin/50913502?renderer_env=live and send us feedback if necassary.

Natasha Hamilton will return us feedback from UX team.
