### ISSUE TITLE
Add Comprehensive STY & PGL Test Asset for a few different services

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#5480]
**Is your feature request related to a problem? Please describe.**
We need a test asset for STYs and PGLs that includes all supported page features (e.g. byline, includes, AV). These should be fixture files for each service and should be available via test ares; this is to support our E2E tests.

**Describe the solution you'd like**
A comprehensive test asset for a few different services e.g. Mundo, Arabic so we can the feature on both a RTL and LTR service as well a service with variants e.g. ukchina/(trad/simp)

Once these assets are added to simorgh ensure the e2e's run against them on localhost.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by lizcameron** [comment]
I've made the following test assets - all using exactly the same content as the Mundo article already in use (https://www.test.bbc.com/mundo/23263889?_x_candy_override=https://api.test.bbc.co.uk) for testing.

- Test asset for a RTL service: https://www.test.bbc.com/arabic/23298105?_x_candy_override=https://api.test.bbc.co.uk
- Test asset for a service with script switch: 
UK China/ Simp: https://www.test.bbc.com/ukchina/simp/23298231?_x_candy_override=https://api.test.bbc.co.uk
UK China/ Trad: https://www.test.bbc.com/ukchina/trad/23298231?_x_candy_override=https://api.test.bbc.co.uk
