### ISSUE TITLE
Add Byline to STY Page

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#5491]
**Is your feature request related to a problem? Please describe.**
Following the completion of https://github.com/bbc/simorgh/pull/5408 and https://github.com/bbc/psammead/pull/3061 we need to add support for the byline to the STY page.

**Describe the solution you'd like**
- Create `BylineContainer` to create a `@bbc/psammead-byline` using the block created by the [addBylineBlock rule](https://github.com/bbc/simorgh/blob/latest/src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addBylineBlock/index.js)
- Add the `BylineContainer` into the STY `componentsToRender`: https://github.com/bbc/simorgh/blob/latest/src/app/pages/CpsSty/index.jsx#L62

**Describe alternatives you've considered**

**Testing notes**
- [ ] Snapshot testing.
- [ ] Manually check position of the Byline.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by andrewscfc** [comment]
@amywalker1987 if we pick-up this work now, are we able to merge this before `@bbc/psammead-byline` comes out of alpha? Seems like we should be able to as STYs are not yet routed to the public?

**Comment by sareh** [comment]
@andrewscfc Do you have a ticket detailing adding of STY routes to live Mozart? Also a ticket for doing an accessibility swarm on psammead-byline? So long the first is blocked on the second, that should be fine.

**Comment by andrewscfc** [comment]
Cannot merge solution until #5496 completed

**Comment by simonsinclair** [comment]
> Cannot merge solution until #5496 completed

Just a heads up, this has been completed and the Byline's alpha tag has been removed.
