### ISSUE TITLE
Update the live radio text for persian 

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#5520]
Update the Live Radio title & description as per the following: https://jira.dev.bbc.co.uk/browse/NEWSPALDECOM-647

**Comment by ryanmccombe** [comment]
ARES need to change this - will log a request

**Comment by LilyL0u** [comment]
Looks good. Full stop in a different position in the JIRA issue, but Persian editor has seen a screen grab and says it is fine, so must be OK, and it does look like it is in the correct RTL position on the page.
