### ISSUE TITLE
Implement Chartbeat for MAP and Live Radio Pages

### ISSUE THREAD

**Issue by pharingee** [bbc/simorgh#5521]
**Is your feature request related to a problem? Please describe.**
Implement Chartbeat for MAP and Live Radio pages.

**Describe the solution you'd like**
MAPs -  https://jira.dev.bbc.co.uk/browse/WSMEDIA-92
Live Radio - https://jira.dev.bbc.co.uk/browse/WSMEDIA-147

The current [implementation](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js#L31) only supports front-pages and articles in the `getType` function. We can update this utility to get support for MAPs and live radio pages.

To get Chartbeat working for MAP pages, we need to update the current `ChartbeatAnalytics` component to accept MAP and Live radio as valid page types and use it in a new `MapChartbeat` component which will implement the `cbq` property.

| Property | MAP implementation | Live Radio Implementation |
|--------|-----------------------|-----------------------------|
| `uid` | Unchanged | Unchanged |
| `domain` | Unchanged | Unchanged |
| `useCanonical` | Unchanged | Unchanged |
| `sections` | Add MAP to `buildSections` in utils | Add Live Radio to `buildSections` in utils |
| `bbc_hid` | Unchanged | Unchanged |
| `title` | Add MAP to `getTitle` | Add LiveRadio to `getTitle` |
| `type` | Add MAP `getType` in utils | Add Live radio to `getType` in utils |

***Details on `sections`***
MAPs
We want to capture the service e.g "Afrique" and then the section name which we get from Ares e.g. "afrique" so this value would be "Afrique - afrique"
 
Then repeat the same entries again appended with "- MAP"
 
Then capture the category if there is one 
Service - <category name> - category e.g 
"Afrique - feature-category"
11:54
This would be
"< service> , <service> - <section name>, < Service> -MAP , <service> - <section name> -MAP, <service> - <category name>-category"
e.g. "Afrique, Afrique - afrique, Afrique - MAP, Afrique - afrique - MAP, Afrique - feature-category"

And in the case of live radio - because we don't have section or category for radio this would be something like:
"Arabic, Arabic - , Arabic - unknown, Arabic - unknown, Arabic - unknown";

So live radio will always be:
“[Service], [Service] - , [Service] - unknown, [Service] - unknown, [Service] - unknown”

**Testing notes**

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
URLs -

MAPS:
http://pal.test.bbc.com/pidgin/media-51466343
https://www.test.bbc.com/pidgin/media-51466343

Live radio:
http://pal.test.bbc.com/korean/bbc_korean_radio/liveradio
https://www.test.bbc.com/korean/bbc_korean_radio/liveradio
