### ISSUE TITLE
CPS PGL - All images should be full width in viewport below 375px

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#5525]
**Describe the bug**
When visiting a CPS PGL page such as https://www.test.bbc.com/gujarati/india-47512764?renderer_env=live and decreasing the viewport below 375px in width the images do not occupy the fill width of the screen when they should; see expected behaviour for full requirements. ~~Before this breakpoint, we do not have this requirement (Natasha is this correct?)~~

**To Reproduce**
Steps to reproduce the behaviour:

1. Resize your browser window to 375px in width
2. Go to https://www.test.bbc.com/gujarati/india-47512764?renderer_env=live
3. Scroll through the images
4. Observe how they don't take up the full width

**Expected behaviour**
- Below 375px images should occupy the full width of the viewport, this includes Square, Portrait, and 16:9 images
  - There is an exception for images with a width below 375px where they should retain their original width, this is not strictly required to be implemented for this issue though: https://github.com/bbc/simorgh/issues/5525#issuecomment-585863146
- Between 375px -768px -  16:9 images are full width
- At all other breakpoints the images are aligned to the grid:
![image](https://user-images.githubusercontent.com/9645462/74636264-8f87b500-515f-11ea-94f5-7f65793d9786.png)
_Revised following @stevencava 's clarifications: https://github.com/bbc/simorgh/issues/5525#issuecomment-585811458_

**Screenshots**
<img width="688" alt="image" src="https://user-images.githubusercontent.com/9645462/74346185-1971ff80-4da7-11ea-8420-1121fa207afd.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
Picked up in UX review #5452

**Comment by stevencava** [comment]
Expected behaviour

Below 375px images should occupy the full width of the viewport
Above 375px images do not have to occupy the full width of the viewport (is this correct Natasha, are there rules for other breakpoints?)

Just to pick up on "Above 375px" - There is this image size guide we use for Article 1.0. 

![image](https://user-images.githubusercontent.com/7226228/74428124-5514d400-4e50-11ea-990c-78fb7c94037d.png)

**Comment by andrewscfc** [comment]
@stevencava , thanks for the info

So from that image guide, are we saying we make images extend to full width between 375px-600px and then just stick to the image's 'normal' width. I'm not quite sure where that 'normal' width comes from.

**Comment by stevencava** [comment]
<img width="1279" alt="grid_image_sizes_article_1 0" src="https://user-images.githubusercontent.com/7226228/74449370-6374e700-4e74-11ea-95a0-7181937548a6.png">

**Comment by stevencava** [comment]
For 375px - Square, Portrait, and 16:9 images should be full width.
375-768 - 16:9 images are full width

For the rest of the breakpoints the images are aligned to the grid

**Comment by stevencava** [comment]
When visiting a CPS PGL page such as https://www.test.bbc.com/gujarati/india-47512764?renderer_env=live and decreasing the viewport below 375px in width the images do not occupy the fill width of the screen when they should. Before this breakpoint, we do not have this requirement (Natasha is this correct?)

----

This is correct, we just need full width below 375px.

**Comment by jimjohnsonrollings** [comment]
However, context of https://github.com/bbc/simorgh/issues/4341
Images which are *smaller* in their original form than the width specified above, should display at their original width instead (this is not necessary to implement in this issue, but it's possibly useful for you to be aware it is the intention later)

**Comment by PriyaKR** [comment]
Looks good the potrait and all images seem to occupy the entire viewport at widths < 375px.
<img width="331" alt="Screen Shot 2020-02-21 at 11 51 56" src="https://user-images.githubusercontent.com/9802855/75032552-be27c780-54a0-11ea-93c5-6dc347b91863.png">

Tested across browsers and devices only on Samsung galaxy s10(android 10) the images still dont occupy full width tested on BS but on other devices of same viewport as S10 it looks good.

**Comment by PriyaKR** [comment]
May be we should merge it and when on test should look on a real device.
