### ISSUE TITLE
Media Player reloads when using skip to content

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#5528]
**Describe the bug**
The Media Player will reload when clicking skip to content. This is most noticeable when you are in the middle of playing media because the media will go back to the beginning after clicking skip to content. This is a problem for any page type that uses the Media Player e.g. MAP, article pages, live radio pages.

**To Reproduce**

1. Go to https://www.stage.bbc.com/pidgin/23248703
2. Click on the video to play the content
3. Tab to the skip to content link
4. Observe the video reloads and shows the video placeholder

**Expected behaviour**
Video should resume playing after skipping to content.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
Tested on stage, test and also on live MAPs (video and audio clips)
