### ISSUE TITLE
Fix Jenkins CI false positives

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#553]
**Describe the bug**
Currently when unit tests fail on Jenkins, the build does not fail. 

An example here: https://github.com/bbc/simorgh/pull/546
https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh/detail/footer-links-columns/4/pipeline/51 The unit test failed, but Jenkins registered a pass.

**Comment by jtart** [comment]
Closed as won't fix as part of Simorgh.
