### ISSUE TITLE
Radio Schedules: Add radio schedules position to service config

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5536]
Blocked (see https://github.com/bbc/simorgh/issues/5536#issuecomment-610901542)

**Is your feature request related to a problem? Please describe.**
Add the position of the Radio Schedule into service config, and display it in the correct position based on this.

**Describe the solution you'd like**
This should probably be a relative position based on another group from the ares feed - we do not have requirements from each service for this yet. After https://github.com/bbc/simorgh/issues/4671 has been completed, we will get feedback from the editorial teams on where to display the component for each service.

**Describe alternatives you've considered**
N/A

**Testing notes**
An integration test should be sufficient.

Dev insight: We should write an integration test to test this. `/src/integration/..`

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
~Blocked on https://github.com/bbc/simorgh/issues/4671~

**Comment by EinsteinNjoroge** [comment]
We already have [the functionality](https://github.com/bbc/simorgh/pull/6104) to change the position of radio-schedules in place. The remaining work is to get feedback from the editorial teams on where to display the component for each service.
cc @tochwill

**Comment by tochwill** [comment]
We now have the positions in this ticket: https://github.com/bbc/simorgh/issues/6184
We can move the radio schedules to be rendered above the group that is defined in here, and update the values in config. I will close this issue, and add this to the details of that issue.
