### ISSUE TITLE
Set min-width on body content at wider breakpoints

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#555]
**Is your feature request related to a problem? Please describe.**
When a user increases the font-size above 100% the entire page (font-sizes, gutters, SVGs etc) increases for accessibility reasons. Because of this the body content shrinks responsively with the paddings/margins on the page. EG: The main content width on a 1280 screen, with font-size 100%, is 743px wide when compared to a font-size of 300% the main content width is 691px.

**Describe the solution you'd like**
Having shown this to UX they have requested that we should set a min-width to stop the body shrinking when the font-size is increased. 

**Additional context**
Font-size 300% example 

![691px width](https://user-images.githubusercontent.com/7791726/44534960-e1798700-a6f0-11e8-9f7f-5826945abe67.png)

_Testing Notes_

**Comment by jimjohnsonrollings** [comment]
I'm not sure I understand this

**Comment by pjlee11** [comment]
If you zoom the browser to  EG: `cmd + '+'` the width of the main article content shrinks because the font-size increases, this isn't good for accessibility and we can maintain a wider viewport for bigger font's using CSS

**Comment by jamesbhobbs** [comment]
Assigned to shared components as this is probably worth considering for the imminent grid work

**Comment by amywalkerdev** [comment]
This doesn't appear to be an issue anymore, increasing the text size uses up the whole of the browser width.
