### ISSUE TITLE
Make Front Pages Ghost-coloured

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#5553]
**Is your feature request related to a problem? Please describe.**
In order to allow us to share components, we've agreed to make the background colour of Front Pages GHOST (#FDFDFD).

**Describe the solution you'd like**
Make the background Ghost, and handle any repercussions of this change (e.g. background on specific components that need to change colour too).

We need this version of Section label to be merged into Simorgh at the same time: https://github.com/bbc/psammead/pull/3133

**Describe alternatives you've considered**
* Making other pages whiter (rejected)
* Making shared components more complicated (rejected)

**Testing notes**
Checking Storybook / Chromatic for regressions. 

Dev insight: Testing Simorgh front pages and any shared components like section labels on STY/PGL/MAPs

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Blocking this until we have the desktop layout work on the front pages are complete, to prevent conflicts.

**Comment by EinsteinNjoroge** [comment]
Closed in https://github.com/bbc/simorgh/pull/5727
