### ISSUE TITLE
UX review of Reith sans font weight

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#557]
**Is your feature request related to a problem? Please describe.**
During a UX review it was brought up that the Reith Sans Regular font seems to be weightier than in the design specs.

**Describe the solution you'd like**
Pair with UX to check if the embedded Reith Sans font is weightier than expected.

**Describe alternatives you've considered**
It may be that the designs differ to the actual font file we are embedding.

**Comment by bcmn** [comment]
Discussed & compared the design & implementation with Ngan Thi, together we couldn't find any issues.
