### ISSUE TITLE
[Investigation] Legacy MAP data failing validation on local 

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#5571]
This may not already be happening, or happening fully, as the legacy map page data is failing the validation here: https://github.com/bbc/simorgh/blob/70aec0c7a9c0d49591011a108230a17229737fb2/src/app/models/propTypes/data/index.js#L7

Here's a link to a conversation on Slack, where we have noticed this behaviour in the local environment (we suspect it is also happening in Test, but warning messages are suppressed): https://bbcnews.slack.com/archives/CJT0284G2/p1582559773023500

**Comment by karinathomasbbc** [comment]
This no longer appears to be happening, plus the E2E tests are running against TC2 assets in both local & test environments, so I suspect this has been resolved. Happy to close.
