### ISSUE TITLE
We need to support legacy MAPs that have modern media blocks

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#5572]
The embed endpoint is currently 404ing on this asset: https://www.test.bbc.com/gahuza/video/2016/01/160108_australia_fire_video?renderer_env=live

The asset ID within the embed URL has too many slashes: https://polling.bbc.co.uk/ws/av-embeds/cps/gahuza/video/2016/01/160108_australia_fire_video/p03dyj3j/rw

**Comment by aeroplanejane** [comment]
This only affects this asset. @pharingee has done an analysis on the TC2 assets - 1/5000 asset are affected
