### ISSUE TITLE
ATI analytics for MAP CPS and TC2 assets  

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5575]
**Is your feature request related to a problem? Please describe.**
We need to pass countername and content id to ATI so we can ensure data can be captured in ATI 

We do not get these values in the response from ares so we need to create these values ourselves using the data available to us in the feed 

**Describe the solution you'd like**

**countername**  
This needs to be updated for TC2 assets. 
This will take the same format currently in PAL which we can deduce from the URL 
See: https://www.bbc.com/uzbek/multimedia/2013/12/131221_sectarian_war_bowen

<img width="434" alt="Screenshot 2020-02-17 at 15 52 03" src="https://user-images.githubusercontent.com/22519682/74668648-90d7d280-519d-11ea-8907-c9fcc263033c.png">

**contentid:** 
Take the metadata id urn format, 
Replace ares with cps or topcat based on the url structure
Append the guid (end of the curie in the ares response) 
We will end up with the same format we currently have on pal e.g. [urn:bbc:cps:031c9e88-5827-f645-8ebd-88483f03cf12]

This fix can be applied to all CPS / TC2 asset types PGLs, STY and MAPs

**Describe alternatives you've considered**
We could ask AReS to make these changes but given their off-forge commitments this will not be a priority for them.  

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Example Map**
![Image from iOS (9)](https://user-images.githubusercontent.com/22519682/74831611-7d4b7980-530d-11ea-81fc-ccafa94ebc11.jpg)
![Image from iOS (10)](https://user-images.githubusercontent.com/22519682/74831627-82a8c400-530d-11ea-92d0-3505a07e1294.jpg)

**Comment by ryanmccombe** [comment]
We want Simorgh to return the same ATI tags as the corresponding assets do on PAL

Can use ATI tag inspector to verify

**Comment by aeroplanejane** [comment]
Tested these URLs and all looks good to me! 
Topcat: 
https://www.test.bbc.com/persian/world/2016/06/160613_om_naked_dining?renderer_env=live
https://www.test.bbc.com/azeri/multimedia/2012/09/120919_georgia_prison_video?renderer_env=live
https://www.test.bbc.com/kyrgyz/multimedia/2014/09/140903_iv_auturgan?renderer_env=live
https://www.test.bbc.com/gahuza/video/2016/01/160108_australia_fire_video?renderer_env=live 
https://www.test.bbc.com/sinhala/world/2015/09/150919_technology_at_schools?renderer_env=live
CPS: 
https://www.test.bbc.com/persian/world-51497110?renderer_env=live
https://www.test.bbc.com/azeri/international-51331762?renderer_env=live
https://www.test.bbc.com/kyrgyz/magazine-51509456?renderer_env=live
https://www.test.bbc.com/vietnamese/forum-51506476?renderer_env=live
https://www.test.bbc.com/gahuza/48549182?renderer_env=live
https://www.test.bbc.com/sinhala/sri-lanka-51375061?renderer_env=live
