### ISSUE TITLE
Exclude Byline Block from STY page with missing title or name

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#5582]
**Is your feature request related to a problem? Please describe.**
Currently our `BylineContainer` supports `name` and `title` optionally rendering nothing if either (or both) props are null: https://github.com/bbc/simorgh/pull/5512/files/9a024a41ad27dbf50cf8fab670a6514ea453c938#r380130101 

If we change the `addBylineBlock` pre-processor rule to not include a byline block if `name` or `title` are not in the ares data we can simplify the `BylineContainer` to require `name` and `title` and remove test cases/empty render logic.

**Describe the solution you'd like**
- Change logic in `addBylineBlock` pre-processor rule to return unmodified json if name or title are null: https://github.com/bbc/simorgh/blob/latest/src/app/lib/utilities/preprocessor/rules/cpsAssetPage/addBylineBlock/index.js#L32
- Make name and title required for `BylineContainer` https://github.com/bbc/simorgh/pull/5512/files/9a024a41ad27dbf50cf8fab670a6514ea453c938#diff-3ab527d29c79750a5cafd71378046787R6-R7 
- Remove empty render logic: https://github.com/bbc/simorgh/pull/5512/files/9a024a41ad27dbf50cf8fab670a6514ea453c938#diff-157097b54aac0bc0bee88b1c4218c69bR16
- Remove redundant test cases

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Had a quick wizz through the ticket and looks like it is a change if name or title are not available in the ares data then we make change to the BylineContainer, agreed this wouldn't need any manual testing.
