### ISSUE TITLE
Add CCPA link to all footers

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#5588]
**Is your feature request related to a problem? Please describe.**
As a part of our response to CCPA, we need to add a link to all our footers.

**Describe the solution you'd like**
The link text should be `AdChoices / Do Not Sell My Info`
The link destination should be `https://www.bbc.com/usingthebbc/cookies/how-can-i-change-my-bbc-cookie-settings/`
The link text should be in English on all services (with an English lang attribute)
1. Update [`psammead-sitewide-links`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-sitewide-links) to accept an optional lang attribute on its anchors )`<a>`.
2. Pull the updated `psammead-sitewide-links` into Simorgh and add an English lang attribute to relevant link - `AdChoices / Do Not Sell My Info`.

**Describe alternatives you've considered**
N/A

**Testing notes**
- These changes will require a dev a11y swarm.
- The snapshot could record the new lang= attribute.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
@jimjohnsonrollings what is the extra language code in the service config for?

**Comment by jimjohnsonrollings** [comment]
@hindsc52 So that we know what language the link text is in, and can apply the relevant markup for screenreaders

**Comment by simonsinclair** [comment]
@jimjohnsonrollings I'd also just like to clarify something: If "The link text should be in English on all services (with an English lang attribute)", do we need a config entry? Can we not wrap the link in lang="en-GB" by default?
