### ISSUE TITLE
Story promo no image - inline headline spacing

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#5595]
**Is your feature request related to a problem? Please describe.**
In sections with 13 promos, we display the headline of the promos without images inline with the media indicator.

In order to align it with the media indicator, we apply a `display: inline` to the `Headline` which unfortunately removes the padding that this has, making the `timestamp` to be attached to it.

<img width="1503" alt="inline-bug" src="https://user-images.githubusercontent.com/46446236/74755270-d31b1580-526a-11ea-837d-8ccc30f48a23.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a Front Page with a section which has 13 promos
2. See error

Can be seen here http://simorgh-infrastructure.api.bbci.co.uk/pidgin

**Expected behaviour**

**Screenshots**
Should have this amount of padding

![image](https://user-images.githubusercontent.com/1678786/75990934-91869d80-5eed-11ea-8575-f1cce1c4cd53.png)

Instead has this amount
![image](https://user-images.githubusercontent.com/1678786/75991031-b844d400-5eed-11ea-9a20-7a54af467764.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by mmcculloch** [comment]
I had a look at this but didn't have time to start it. The best solution I could fine would be to remove this logic https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/src/index.jsx#L137

Then place the `MediaIndicator` inside of the `Headline` component, next to the `Link` component. Since the text and mediaIndicator are both inline they will display correctly without the need to Headline inline.

https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx#L147
```jsx
      {headline && (
        <Headline
          script={script}
          service={service}
          promoType={promoType}
          promoHasImage={displayImage}
        >
          <MediaIndicatorContainer
            item={item}
            script={script}
            service={service}
            dir={dir}
            isInline={!displayImage}
          />
          <Link href={url}>
            {isLive ? (
              <LiveComponent
                service={service}
                headline={linkcontents}
                dir={dir}
              />
            ) : (
              linkcontents
            )}
          </Link>
        </Headline>
      )}
```
