### ISSUE TITLE
Make Live Radio pages ghost

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#5605]
**Is your feature request related to a problem? Please describe.**
In order to allow us to share components, we've agreed to make the background colour of all pages in Simorgh GHOST (#FDFDFD).

**Describe the solution you'd like**
Make the background Ghost, and handle any repercussions of this change (e.g. background on specific components that need to change colour too).

**Describe alternatives you've considered**
Making other pages white (rejected)
Making shared components more complicated (rejected)

**Dev notes**
Live radio page - http://localhost:7080/korean/bbc_korean_radio/liveradio

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by jroebu14** [comment]
Closed via https://github.com/bbc/simorgh/pull/5748
