### ISSUE TITLE
SPIKE: Using the toggles service for AMP ads

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5619]
**Is your feature request related to a problem? Please describe.**
We should have a dev swarm with members of each pod to understand the toggles service. We need to be able to do the following:

- Understand the toggles service and how it works with iSite.
- Make a client side call to the toggles service on page load, which will tell us if we need to show ads or not. Make sure you include geo-ip lookup in this request (this is a feature included with the toggles service). Then update the toggles context in Simorgh using the toggles reducer and action that already exist.
- The toggles service will also need to integrate with global flagpole. We will have to do this work in that service, so we need to be able to understand infrastructure and logging, and have access to the system.
- We should configure simorgh service config to whether or not a service has ads. Then we  won’t call the toggles service unless we need to.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Our approach for handling geoip has changed. We should only need to make a server-side call to the Toggles service for ads on AMP pages (to find out whether Ads have been turned off globally, or for a particular service). 
We can find out whether the particular user should have ads from the header: `X-Ip_is_advertise_combined`, which should be passed to Simorgh.

**Comment by tochwill** [comment]
@sareh - ~So we should now be able to make this decision using the same implementation for both canonical and AMP pages? We can read the header on the server, call the toggles service on the server, and then not render the ad component in the top level container _at all_ if we shouldn't be?~ Actually ignore this, sorry. We'll still need to use a GeoIP lookup from the client as we'll be serving AMP pages from the AMP cache.

**Comment by benjifellows** [comment]
Closing issue
