### ISSUE TITLE
Update READMEs to include link to article on BBC URL steer

### ISSUE THREAD

**Issue by mgurgel** [bbc/simorgh#562]
**Is your feature request related to a problem? Please describe.**
I linked to an article by a BBC TA regarding the rationale behind id-based URLs across the BBC. Phil suggested it gets added to the docs

**Describe the solution you'd like**
Add this link in the appropriate section in the README
https://www.smashingmagazine.com/2014/05/responsive-design-begins-with-the-url/

**Describe alternatives you've considered**
Add the link to the Wiki?

**Additional context**
N/A

**Comment by jamesbhobbs** [comment]
done not sure why merged Pr didn't close this
