### ISSUE TITLE
Replace content at /media/video with Most Watched

### ISSUE THREAD

**Issue by neildoughty** [bbc/simorgh#5631]
Currently all WS sites have an index of their most recently published video content on the url /<service>/media/video

We do not have a plan to replace this, since the recent assets endpoint will go away eventually and it will not include Optimo published content.

If we want to maintain this url, and I think at present we do, then we will need to have some video content present on this page, for all services, perhaps making use of a most watched component in a page is logical. This is likely a short-term fix to get things off Forge. It may be replaced in the medium-term.

Describe the solution you'd like
I would like a page in Simorgh to be available for each service of this format:
bbc.com/<service>/media/watched
If a user visits that page I would like them to be able to see a list of popular media asset pages from that service.

I would like the page to use exactly the same UX as Most Read in the first instance. Later, if Most Watched becomes richer, then that improved styling can be incorporated. In theory, if more than 10 items can be shown, or pagination included that might be nice, but not until v1 is released.

Describe alternatives you've considered
We could do nothing. We could just redirect the /media/video url to the service homepage. This is what we are planning to do for /audio and /photogalleries
I think i'd rather keep the URL alive and then at some stage have the media team do something more interesting with it.

Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

 This feature is expected to need manual testing.
Additional context
This piece of work is potentially a thing we could do, or not do. Before we get deep into it I'd be interested in an estimate of how much work is needed to make this happen for all sites.

**Comment by sareh** [comment]
Steps for this 

- enable `mostwatched` JSON route in Mozart, similar to `mostread` 
https://github.com/bbc/mozart-routing/blob/9cfab6c38a61de54808416448cf99358bdcc73fa/src/lib/mozart_routing/routes/live_routes.rb#L221-L249
& 
https://github.com/bbc/mozart-routing/blob/9cfab6c38a61de54808416448cf99358bdcc73fa/src/lib/mozart_routing/payloads/simorgh_ares_mostread.rb#L18

- update Simorgh MostRead container to fetch data for either `mostread` or `mostwatched`
- Ensure we have Simorgh Storybook stories for Most Watched as well as Most Read

(At this point, we can add Most Watched to any existing page)

- Add page route in Simorgh for the `mostwatched` (ensuring we consider those services with variants too) and create a new Simorgh Page that just has a H1 heading (offscreen?) with the MostWatched component on the page. UX might prefer to not have an offscreen h1 Most Read as well as an onscreen h2 Most Read. Will need to discuss requirements. 
- Add a Mozart Route for the page
- Make STM changes for the page routes to make them audience-facing.

**Comment by gavinspence** [comment]
Closing this as we have a Milestone capturing the work :)
