### ISSUE TITLE
Document ways to run Psammead locally with Simorgh

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#5635]
**Is your feature request related to a problem? Please describe.**
Often we're making changes in Psammead and we don't have a clear set of instructions of how to reliably use Psammead components within Simorgh. 

**Describe the solution you'd like**
- Adding information to a relevant readme. 
- Ensure instructions work for packages that are lower-down in the tree e.g. utilities (`@bbc/gel-foundations`) vs a top-level component e.g. `@bbc/psammead-most-read`

**Describe alternatives you've considered**
N/A - this was an outcome of a latest retrospective to improve the local development process when updating psammead packages.

**Testing notes**
[Tester to complete]

Dev insight: We should have multiple people trying these out. 

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
We will improve the developer experience by potentially using yarn in future.
