### ISSUE TITLE
Automate linting of CSS

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#564]
**Is your feature request related to a problem? Please describe.**
We do not currently implement any standards on our CSS.

**Describe the solution you'd like**
We should implement some linting using `stylelint` with integration with `styled-components`. See: https://www.styled-components.com/docs/tooling#stylelint.

We should add the library and then integrate in separate PRs to reduce complexity.

**Additional Context**
_Testing notes_

**Comment by ChrisBAshton** [comment]
Note: getting resolved in another repo by https://github.com/BBC-News/psammead/issues/30. We can use this as a basis for our own PR in this repo.

**Comment by ChrisBAshton** [comment]
Oh, it's already been done! Fixed in https://github.com/BBC-News/simorgh/commit/c89ce0fb74c1ed21e9fc90f6ffa3c11379543c4a.
