### ISSUE TITLE
Blocks of type 'generic' are being sent in ARES response for legacy MAPs but not rendered in Simorgh

### ISSUE THREAD

**Issue by RichardPK** [bbc/simorgh#5657]
**Describe the bug**

The ARES response for some Legacy MAPs contains content `blocks` in this format:

```
{
"type": "generic",
"xml": "<bold>Today's Headlines:</bold>"
}
```

Objects with type `generic` and a `xml` key do not match our components' propTypes validation, and so they are not rendered.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.test.bbc.com/persian/learningenglish/2016/09/160911_l93_lingohack.json?renderer_env=live'
2. Note the blocks with `type: generic` within the response.
3. Visit the Simorgh-rendered version of this page: 'https://www.test.bbc.com/persian/learningenglish/2016/09/160911_l93_lingohack?renderer_env=live'
4. Notice the text is not rendered.
5. Compare this with the PAL-rendered version of the page: 'https://www.bbc.com/persian/learningenglish/2016/09/160911_l93_lingohack'
6. Notice the text is rendered.

Pal:
<img width="674" alt="Screenshot 2020-02-24 at 12 50 41" src="https://user-images.githubusercontent.com/9042672/75153873-540f5c80-5704-11ea-89b0-d1588067d511.png">

Simorgh:
<img width="674" alt="Screenshot 2020-02-24 at 12 50 47" src="https://user-images.githubusercontent.com/9042672/75153901-68ebf000-5704-11ea-8dd2-1e1fb9adf32d.png">

**Other jsons for MAPs with type: generic**
- https://www.test.bbc.com/persian/learningenglish/2016/09/160902_l93_lingohack.json?renderer_env=live
- https://ares-broker.api.bbci.co.uk/api/asset/russian/multimedia/2016/02/160217_elt_lingohack

**Expected behaviour**
Simorgh would be expected to render these content blocks.

**Desktop (please complete the following information):**

- OS: OSX Mojave
- Browser: Chrome

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
Following an amigos and technical refinement, it was decided that we will transform blocks of type `generic` within `src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/index.js` by adding a new blockType transformer to `typesToConvert`.

In terms of object structure, `type` will be reassigned the value `paragraph`, `xml` will be changed to `text` (with the value remaining the same) and a key value pair `markupType`: `candy_xml` will be added. i.e.:

```
{
"markupType": "candy_xml",
"text": "<bold>Today's Headlines:</bold>",
"type": "paragraph"
}
```

**Example map**
![20200226_150203](https://user-images.githubusercontent.com/9042672/75459647-f5eaaf80-5977-11ea-8fa1-b2a5a55eb1aa.jpg)

**Comment by pharingee** [comment]
The AReS response for 1000 legacy media assets  was checked and we found only 22 occurrences of this bug. That's a 2% rate. 

Half of these URLs are going to be redirected.It was decided that we postpone this work until we're off-Forge. End user impact is tiny. It is a bug that is worth fixing but it's low in the priority list.

**Comment by gavinspence** [comment]
Impact too small to warrant work.
