### ISSUE TITLE
BUG - Missing text in a candy_xml paragraph block

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#5663]
Missing text in a candy_xml paragraph block

https://www.test.bbc.com/vietnamese/multimedia/2014/01/140117_hoangducnha_hoangsa_1974.json?renderer_env=live

In block 12 ,the second span text is being displayed, but the first span text is not displayed, leaving unattached text out of context.

![Image 24-02-2020 at 17 16](https://user-images.githubusercontent.com/54575620/75175125-a6af3f80-5729-11ea-9735-0b6957c70863.jpg)

![UNADJUSTEDNONRAW_mini_b0](https://user-images.githubusercontent.com/54575620/75175175-c47ca480-5729-11ea-97f6-b731e4a140d2.jpg)

Page link: www.test.bbc.com/vietnamese/multimedia/2014/01/140117_hoangducnha_hoangsa_1974?renderer_env=live

It is fine on PAL https://www.bbc.com/vietnamese/multimedia/2014/01/140117_hoangducnha_hoangsa_1974

This is also related: https://github.com/bbc/simorgh/issues/5860

**Comment by gavinspence** [comment]
@pharingee can you look at the incidence of this with your script? Not sure if it's worth the effort in picking this up.

**Comment by gavinspence** [comment]
Fixed now
