### ISSUE TITLE
Page link tests

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#5667]
**Is your feature request related to a problem? Please describe.**
[this](https://github.com/bbc/simorgh/pull/5666) pr removed a 404 link test we had in cypress. This test would traverse the links in the navigation and in the footer to ensure they all return a 200 response.

These tests often ran slow (upwards of 40s per page).

These also shouldn't really be a a part of the simorgh e2e suite and they are ensuring another third party page return a 200 response. 

**Describe the solution you'd like**
Create a new solution outside of simorgh that traverses the simorgh pages and checks the links on them.

This solution should probably not use cypress and should run separately from the existing simorgh pipelines.

**Describe alternatives you've considered**
N/A
**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by jblaut** [comment]
Currently working on something that can replace our link tests. All the code is currently here: https://github.com/jblaut/linkey-node, but hopefully once it's all done and approved, it should be moved to Simorgh.
