### ISSUE TITLE
Front Page: allow for sections with a full-width background colour

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5677]
**Is your feature request related to a problem? Please describe.**
Currently, the maximum width and margins are added to the front page container. For radio schedules we are adding a slice with a full width background colour. To achieve this, we should add the maximum width and margins to front page sections, to allow us to insert one of these slices with a different background colour into the page. Then we can alter the background colour of the slice containing radio schedules.

**Describe the solution you'd like**
Move margins from the front page container to front page sections.

**Describe alternatives you've considered**

**Testing notes**
The output should match the designs.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

Designs:
https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5dc0724906469a23537e6a04

**Comment by tochwill** [comment]
Before picking this work up, check with the UX team to ensure that this work is needed and the designs include the correct colour once we change the background of the page to ghost

**Comment by Bopchy** [comment]
It was confirmed with UX via Slack that this work is needed and the background of the radio schedules should be Lunar as indicated on the designs
