### ISSUE TITLE
Legacy MAPs with image as first block displays timestamp below image instead of above

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5683]
On legacy MAPs and CPS pages, an image block can be placed before the timestamp.

This means the timestamp is being displayed underneath the image, rather than below the headline as it should. In PAL the image shows below the timestamp when made small enough that it is not text wrapped to the side.

Simorgh: https://www.test.bbc.com/vietnamese/multimedia/2014/01/140117_hoangducnha_hoangsa_1974?renderer_env=live

PAL: https://www.bbc.com/vietnamese/multimedia/2014/01/140117_hoangducnha_hoangsa_1974.shtml

Potentially this could be any content type, not just images.

**Comment by RichardPK** [comment]
The solution of creating logic forcing the timestamp below the heading was discussed, but @gavinspence made the call this was an edge case and even when it happens, its impact is minimal. We are closing for now.
