### ISSUE TITLE
Discuss which routing e2e tests overlap with unit tests that we can remove

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#5694]
Since the routes tests refactor was merged https://github.com/bbc/simorgh/pull/5682 which gives more confidence about route matching and page rendering there is potential to remove some overlapping e2e tests.

We should discuss with a test engineer if there is any overlapping e2e tests and if we should remove them since we should try to rely on unit tests more as they run faster than e2e tests.

**Comment by graeme-lindsay** [comment]
@jroebu14 Are you happy this is being progressed and we can close this issue?
