### ISSUE TITLE
Display Error for Revoked Media 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5704]
**Story**
As Emily, a WS visitor to a media page 
I want to see a message when a piece of media is no longer available 
so that I can understand what the hell is going on. 

**Description**
Media can be revoked by editorial in Castaway.  
When it is revoked we get this response in the media block from ARES for CPS assets: 
See example: https://www.test.bbc.com/pidgin/media-23268723.json

```
  "media": {
      "caption": "Test Russian",
      "entityType": "Clip",
      "externalId": "p01pm45p",
      "format": "video",
      "id": "23257710",
      "statusCode": 404,
      "statusMessage": "Asset could not be found. Perhaps it was withdrawn.",
      "subType": "primary",
      "type": "external_vpid"
    },

```
At the moment we don't display anything to the user and the player isn't rendered. 
It makes pages like this look very strange: https://www.test.bbc.com/pidgin/media-23268723

**Proposed Solution**
When this happens we will display the generic error message saying "This content is no longer available" and NO IMAGE like we currently do on TC2 asset pages that don't support media e.g. https://www.bbc.com/vietnamese/multimedia/2015/04/150428_david_wheat_interview

![Screenshot 2020-02-27 at 17 52 50](https://user-images.githubusercontent.com/22519682/75471382-1b80b480-598a-11ea-84f4-3c94abd519b2.png)

This fix will apply to CPS asset types only. 

**Examples**
Given a CPS MAP page has media revoked 
When I visit a page for a service (https://www.test.bbc.com/pidgin/media-23268723)
then I will see a grey placeholder where the media would usually be
and I will see the message 'This content is no longer available' in the language of that service
and I will not see an image

**Comment by pharingee** [comment]
The example mapping session for this issue can be found here: https://miro.com/app/board/o9J_kvZ2wMk=/?moveToWidget=3074457347315171408

With a summary screengrab here:
<img width="729" alt="Screenshot 2020-03-05 at 13 54 24" src="https://user-images.githubusercontent.com/4933242/75988120-01def000-5ee9-11ea-8749-63a1a8ba2332.png">

**Comment by graeme-lindsay** [comment]
@pharingee  we discussed this today and we need to cycle back round the amigos of this next week. We want to cover the media block being missing as a rule.

**Comment by greenc05** [comment]
What accessibility acceptance criteria do we have for this @aeroplanejane? Is it the same as the no JS message?

**Comment by aeroplanejane** [comment]
Yep @greenc05, it's the same component
