### ISSUE TITLE
Error in Video Object Schema on Persian Live Stream 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5708]
**Describe the bug**
There are errors in the video object schema on the Live Stream Pages. 
This can affect google's ability to index these pages as video. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://search.google.com/structured-data/testing-tool/
2. Test this Persian Live TV URL: https://www.bbc.com/persian/media-49522521
3. Note the errors in the video object with the name, description thumbnail URL 

![Screenshot 2020-02-28 at 12 01 26](https://user-images.githubusercontent.com/22519682/75548424-250b2a80-5a25-11ea-80d7-41a5791bdb94.png)

This is where it's being rendered within the html:
<img width="760" alt="Screenshot 2020-03-03 at 15 52 47" src="https://user-images.githubusercontent.com/9042672/75795892-da621900-5d6a-11ea-86a2-3c8d14e275ab.png">

**Expected behaviour**
The video object should have no errors. 
See the PAL example of the live stream: http://pal.test.bbc.com/persian/media-49522521
See a clip example on Simorgh: https://www.bbc.com/pidgin/media-44221514

Live stream assets on Simorgh TEST:
https://www.test.bbc.com/pidgin/media-23256547
https://www.test.bbc.com/pidgin/media-23256548
https://www.test.bbc.com/pidgin/media-23256549
https://www.test.bbc.com/pidgin/media-23256550
https://www.test.bbc.com/pidgin/media-23256552
https://www.test.bbc.com/pidgin/media-23256553
https://www.test.bbc.com/pidgin/media-23256554

Live stream assets on LIVE: 
(PAL) https://www.bbc.com/arabic/media-49522519
(PAL) https://www.bbc.com/hindi/india-48336189 

**Additional context**
- `thumbnailUrl`, `description` & `name` are being handled within `/src/app/containers/MediaPlayer/helpers/metadata/index.js`

- The _transformer_ handling the video block metadata is `src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/version/index.js`

**Resources**
- Miro with example mapping https://miro.com/app/board/o9J_kvZ2wMk=/?moveToWidget=3074457347306292500
- A previous issue looking at SEO & distinguishing between videoObject & audioObject  https://github.com/bbc/simorgh/issues/4707
- SEO spec https://confluence.dev.bbc.co.uk/display/WSMEDIA/MAP+%7C+SEO

**Comment by karinathomasbbc** [comment]
There is a Chrome extension for structured data testing meaning you can test this locally - Structured Data Testing Tool - https://chrome.google.com/webstore/detail/structured-data-testing-t/kfdjeigpgagildmolfanniafmplnplpl

**Comment by aeroplanejane** [comment]
@RichardPK We need to change the name and description from ares.media.caption to ares.promos.headlines.headline for CPS MAPs with Live Streams. According to editorial this field is optional on CPS on live. In order to avoid issues with videoObject name and description in the future we should use headline field. This could also be used for TC2 MAP assets. cc @gavinspence @graemelindsayBBC
