### ISSUE TITLE
Add SW busting for React Router links

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#571]
**Is your feature request related to a problem? Please describe.**
#394 implements a service work, and we should be able to propagate updates to the service worker to the client-side application.

**Describe the solution you'd like**
We should follow the implementation described here: https://zach.codes/handling-client-side-app-updates-with-service-workers/, with #394 laying the ground-work for setting `swUpdate` on the window.

Also see the spectrum thread here: https://spectrum.chat/thread/1219ba5f-d395-4781-bce8-a57eb434eedf

**Describe alternatives you've considered**
None.

**Additional Context**
_Testing Notes_

**Comment by jamesbhobbs** [comment]
We disabled the caching
