### ISSUE TITLE
Move most read e2e test to testforAllPages

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#5715]
**Is your feature request related to a problem? Please describe.**
Currently we have the e2e tests for most read added for frontpage and not for articles.Move the test to `testForAllPages` and so that i runs across articles and frontpages(limited services).
https://github.com/bbc/simorgh/pull/5538

**Describe the solution you'd like**
Move the test to `testForAllPages` using a filter so that this test is run only for frontpage and article page for now.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Blocked until we have the existing most read test passing for front pages. https://github.com/bbc/simorgh/issues/5726

**Comment by DenisHdz** [comment]
Close as this e2e has been removed in https://github.com/bbc/simorgh/pull/5740
