### ISSUE TITLE
Investigate and add data for radio schedule programmes

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#5744]
**Is your feature request related to a problem? Please describe.**
When we pull in the radio schedule into simorgh we need data feed from ARes endpoint containing the programme schedules.Investigate from where the schedules are created whether in CPS or does come from anywhere else?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Closed as fixed by https://github.com/bbc/simorgh/pull/5907 & https://github.com/bbc/simorgh/pull/5855
