### ISSUE TITLE
Includes RequireJS stubbing for VJ/IDT1

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#5750]
#### Is your feature request related to a problem? Please describe.

We've identified that some includes depend on Require JS and _probably_ don't include it. We need to ensure that Require JS is in the page before rendering Includes of this type.

Note that while all IDT1 content needs RequireJS, only some VJ content does.

#### Describe the solution you'd "like"

- RequireJS added to document only for IDT1 and VJ includes
- We need to ensure that the script tag(s) are only added once
- We need try and avoid multiple versions of require being loaded onto the page as part of include polyfill implementations.

#### Describe alternatives you've considered
n/a

#### Testing notes
- Ensure requirejs not added to other page types 
- Ensure requirejs is not on STY pages without includes
- Check for console errors relating to 'require not being defined' for IDT1 and VJ includes
- Gather most used IDT1 and VJ includes: speak to @lizcameron and @eagerterrier about their availability on test
- Snapshot tests for various include configs: IDT2, VJ etc
- Follow instructions here to use test harness to test includes with requirejs https://github.com/bbc/simorgh-infrastructure/issues/897#issuecomment-607928529

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by andrewscfc** [comment]
Blocked until we can take forward one of our POCs for integrating includes into the page:
https://github.com/bbc/simorgh/issues/5822
https://github.com/bbc/simorgh/issues/5823
https://github.com/bbc/simorgh/issues/5824

**Comment by jamesdonoh** [comment]
Should no longer be blocked.

**Comment by andrewscfc** [comment]
@paruchurisilpa , please use this temporary branch to test this issue with IDT1 and VJ includes: https://github.com/bbc/simorgh/pull/6405

**Comment by paruchurisilpa** [comment]
Includes available on test:

* **** VJ *****:
* https://www.test.bbc.com/ws/includes/include/vjamericas/166-panama-elections-manifesto/mundo/app?responsive=true&newsapps=true&app-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-qwerty_panama/venta-app-panama_t29el.png&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-qwerty_panama/venta-app-panama_t29el.png

* https://www.test.bbc.com/ws/includes/include/vjamericas/304-countries-amazon-rainforest/portuguese/app?responsive=true&newsapps=true&app-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-werty/venta-app_portugues2_r224x.png&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-werty/venta-app_portugues2_r224x.png

* https://www.test.bbc.com/ws/includes/include/vjamericas/303-green-lie-amazon-rainforest/mundo/app?responsive=true&newsapps=true&app-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-werty/venta-app_o5yqs.png&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-werty/venta-app_o5yqs.png

* https://www.test.bbc.com/ws/includes/include/vjamericas/387/mundo/app?responsive=true&newsapps=true&app-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-asdf/venta-app_mapa_cuarentena_4kg4k.png&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-asdf/venta-app_mapa_cuarentena_4kg4k.png&app-image-alt-text=Clica%20para%20ver%20el%20contenido%20interactivo

*  https://www.test.bbc.com/ws/includes/include/vjamericas/408-brazil-coronavirus-lookup/portuguese/app?responsive=true&newsapps=true&app-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-werty/lookup_launcher_2_qdt5b.png&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-werty/lookup_launcher_2_qdt5b.png&app-image-alt-text=Clique%20aqui%20para%20ver%20o%20interativo

*  https://www.test.bbc.com/ws/includes/include/vjsthasia/833-delhi_election_results/gujarati/tally?responsive=true&newsapps=true&app-image=https://news.files.bbci.co.uk/include/vjsthasia/833-delhi_election_results/assets/app-project-assets/img/cover.png&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/include/vjsthasia/833-delhi_election_results/assets/app-project-assets/img/cover.png

*  https://www.test.bbc.com/ws/includes/include/vjsthasia/826-iswoty_medals_facewall/hindi/medalgrid?responsive=true&newsapps=true&app-image=https://news.files.bbci.co.uk/include/vjsthasia/826-iswoty_medals_facewall/assets/app-project-assets/img/banner.png&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/include/vjsthasia/826-iswoty_medals_facewall/assets/app-project-assets/img/banner.png

*  https://www.test.bbc.com/ws/includes/include/vjsthasia/849/english/app?responsive=true

*  https://www.test.bbc.com/ws/includes/include/vjsthasia/857-covid19_indian_states/hindi/header?responsive=true&newsapps=true&app-image=https://placehold.it/640x360&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://placehold.it/640x360

*  https://www.test.bbc.com/ws/includes/include/vjsthasia/856-covid19_bangladesh/bengali/app?responsive=true&newsapps=true&amp-clickable=true&amp-image-height=360&amp-image-width=640

* https://www.test.bbc.com/ws/includes/include/vjafwest/460-afcon-2019-dream-team/afaanoromoo/app?responsive=true&newsapps=true&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://placehold.it/640x360

*  https://www.test.bbc.com/ws/includes/include/vjafwest/409-afcon-2019-other-winners/afaanoromoo/app?responsive=true&newsapps=true&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://placehold.it/640x360

*  https://www.test.bbc.com/ws/includes/include/vjafwest/557-fire-stations-proximity/yoruba/app?responsive=true&newsapps=true&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-vjafwest/fire-stations-yoruba_m6dw5.png

* https://www.test.bbc.com/ws/includes/include/vjafwest/582-uk-africa-summit/pidgin/app?responsive=true&newsapps=true&app-clickable=true&amp-clickable=true&amp-image-height=576&amp-image-width=1000&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-vjafwest/uk-trade-amp-pidgin_2tmlt.png

* https://www.test.bbc.com/ws/includes/include/vjafeast/227-moi-timeline/swahili/app/full-width

* https://www.test.bbc.com/ws/includes/include/vjafeast/196-eliud-race-against-time/tigrinya/app?responsive=true&newsapps=true&app-image=https://placehold.it/640x360&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://placehold.it/640x360h

***** IDT *****
*  https://www.test.bbc.com/ws/includes/idt2/cb1a5166-cfbb-4520-bdac-6159299acff6/html

***** Story with IDT2 includes *****
*  https://www.test.bbc.com/pidgin/23298136

**Comment by paruchurisilpa** [comment]
Checked the includes mentioned above and the includes are rendered OK. Thanks Rowland for helping with some of the includes testing.LGTM..
