### ISSUE TITLE
Add Twitter metadata

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#576]
**Is your feature request related to a problem? Please describe.**
Our article page is currently missing metadata. This PR will add all the available Twitter meta.

**Describe the solution you'd like**
Add the following fields, including the logic necessary to render them correctly:
- `twitter:site` - '@BBCNews'
- `twitter:title` - `promo.headlines.seoHeadline`
- `twitter:card` - 'summary_large_image'
- `twitter:description` - `promo.summary`
- `twitter:creator` - `@BBCNews`
- `twitter:image:src` - static image (`"https://www.bbc.co.uk/news/special/2015/newsspec_10857/bbc_news_logo.png?cb=1"`)
- `twitter:image:alt` - 'BBC News'

**Additional context**
Some fields might require further discussion, and we will initially hard-code them.

**Testing notes**
- Unit tests are adequate

**Comment by BogdanDogaru** [comment]
Blocked waiting on #573

**Comment by sareh** [comment]
Closed as fixed.
