### ISSUE TITLE
Front page large images are better quality on IE11 than Chrome 80

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#5774]
**Describe the bug**
Images are displaying in higher quality in IE11 than Chrome.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to /thai on Live in IE11
2. Look at the top image
3. Go to /thai on Live in Chrome
4. Look at the top image
5. Compare the top images, observe that the one in IE11 is higher quality

**Expected behaviour**
Images should be the same quality.  Editorial ideal would be the higher quality in both browsers.

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/8124899/75991072-ca267700-5eed-11ea-90a5-19a926b0f55c.png)
![image (3)](https://user-images.githubusercontent.com/8124899/75991075-cbf03a80-5eed-11ea-9e1e-d8a7ee8cd900.png)
One of these looks better - the one that looks better is IE11

**Desktop (please complete the following information):**

- OS: Windows
- Browser BBC IE11, Chrome 80

**Testing notes**

- [/] This bug fix is expected to need manual testing.

**Additional context**

**Comment by amywalkerdev** [comment]
Srcset is not supported in IE11 (https://caniuse.com/#feat=srcset) so we use the largest image

**Comment by jimjohnsonrollings** [comment]
IE11 is defaulting to the 660px image.  Other browsers are using the 624px image.  We will make the other browsers use 660px as editorial seem to be happy with this.
