### ISSUE TITLE
Failing AMP Validation on TC2 Assets

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5782]
**Is your feature request related to a problem? Please describe.**
AMP validation is failing on TC2 asset pages. 
e.g. https://validator.ampproject.org/#url=https%3A%2F%2Fwww.bbc.com%2Findonesia%2Fbahasa_inggris%2F2016%2F08%2F160817_video_inggris.amp

This is also causing the E2E tests to fail, so we had to temporarily disable them

We need to ensure we provide an image placeholder. 

**Describe the solution you'd like**
The TC2 ARES response does provide an image, but it is too small.

- The amp placeholder that's used within live radio is the correct colour.
- The 'media asset revoked'/'cannot be played' placeholder is the correct size

Use the default grey image and bbc image block as our amp iframe image placeholder. 

The logic that handles this placeholder is within `getPlaceholderSrcSet` inside the `MediaPlayerContainer` component.

**Testing notes**
- [x] This feature is expected to need manual testing.

Test Environment: https://validator.amp.dev/#url=https%3A%2F%2Fwww.test.bbc.com%2Fpersian%2Firan%2F2016%2F09%2F160907_tc2_testmap1.amp 
Live Environment: https://validator.ampproject.org/#url=https%3A%2F%2Fwww.bbc.com%2Findonesia%2Fbahasa_inggris%2F2016%2F08%2F160817_video_inggris.amp

**Additional context**
- The AMP validator chrome plugin will help debug

- [x] Add MAPs & Legacy MAPs to the AMP Validation test
- [x] Re-enable TC2 E2Es in all environments

**Comment by LilyL0u** [comment]
Tested this on 10 legacy amp pages and amp validator passes for all :)
