### ISSUE TITLE
StatsObject Producer reporting incorrectly for Turkish and Indonesia

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5791]
**Describe the bug**
Rich Media data is not being tracked for Turkish and Indonesian in ATI 
We are reporting page load data correctly, this only affects rich media. 

**To Reproduce**

1. Go the the ATI explorer
2. Go to rich media within the content tab
3. Filter down to Turkish or Indonesian in the Level 2 sites 
4. Note that no richmedia is being reported for video or audio 

 
![Screenshot 2020-03-06 at 11 40 11](https://user-images.githubusercontent.com/22519682/76080671-47f68b00-5f9f-11ea-8aed-ecbb020813bb.png)

**Expected behaviour**
We should ensure that rich media is being captured for Turkish and Indonesian
We must pass "TURKISH" not "TURKCE" as the statsObject.producer for bbc.com/turkce
We must pass "INDONESIAN" not "INDONESIA" as the statsObject.producer for bbc.com/indonesia
see: http://bbc.github.io/echo-docs/documentation/reporting-ati/#producer

```
   require(['bump-4'], function (bump) {
        var settings = {"counterName":"turkce.world.media_asset.51710108.page","appType":"responsive","appName":"news-turkce","product":"news","insideIframe":true,"superResponsive":true,"externalEmbedUrl":"https://bbc.com/turkce/haberler-dunya-51710108/embed","playlistObject":{"holdingImageURL":"https://ichef.bbci.co.uk/images/ic/$recipe/p085dslz.jpg","items":[{"kind":"programme","live":false,"serviceID":null,"duration":245,"versionID":"p085ds7j"}],"summary":"Mülteci krizi: Sınırı geçebilenler, Yunanistan'da nasıl karşılanıyor?","title":"Mülteci krizi: Sınırı geçebilenler, Yunanistan'da nasıl karşılanıyor?","embedRights":"allowed"},"statsObject":{"destination":"WS_NEWS_LANGUAGES","clipPID":"p085ds7c","episodePID":null,"producer":"TURKCE"},"ui":{"locale":{"lang":"tr"},"subtitles":{"defaultOn":true},"cta":{"mode":"duration"},"embed":{}}};
        var player = bump.player(document.getElementById('mediaPlayer'), settings);
        player.load();
    });
```
```
require(['bump-4'], function (bump) {
        var settings = {"counterName":"indonesia.embedded_media.media_asset.51750632.page","appType":"responsive","appName":"news-indonesia","product":"news","insideIframe":true,"superResponsive":true,"externalEmbedUrl":"https://bbc.com/indonesia/media-51750632/embed","playlistObject":{"holdingImageURL":"https://ichef.bbci.co.uk/images/ic/$recipe/p085q5rz.jpg","items":[{"kind":"programme","live":false,"serviceID":null,"duration":90,"versionID":"p085q5kn"}],"summary":"Virus corona: Takut jabat tangan, 'Wuhan shake' jadi pilihan","title":"Virus corona: Takut jabat tangan, 'Wuhan shake' jadi pilihan","embedRights":"allowed"},"statsObject":{"destination":"WS_NEWS_LANGUAGES","clipPID":"p085q5kl","episodePID":null,"producer":"INDONESIA"},"ui":{"locale":{"lang":"id"},"subtitles":{"defaultOn":true},"cta":{"mode":"duration"},"embed":{}}};
        var player = bump.player(document.getElementById('mediaPlayer'), settings);
        player.load();
    });
```
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
I played media on an indonesian and a turkish page around 4pm on 9th March on the test environment. It was correctly sending 'media level 2' as 54 for Indonesian and 92 for Turkish, as seen in tag inspector.
In ATI Explorer, when I go to the Rich Media page and filter by Indonesian and Turkish, I can see that rich media was played around 4pm on the 9th March.

**Comment by ryanmccombe** [comment]
This is live now
 - https://www.bbc.com/indonesia/indonesia-51772194
-  https://www.bbc.com/turkce/haberler-dunya-51716134

**Comment by sareh** [comment]
@LilyL0u @karinathomasbbc I only just saw this ticket. You'll likely also need to update 'portuguese' to 'brasil'. https://github.com/bbc/simorgh/pull/5742

**Comment by aeroplanejane** [comment]
Thanks @sareh have raised a JIRA ticket to capture this when we turn our attention to the services with pre-roll - WSMEDIA-182. We'll raise another PR then.
