### ISSUE TITLE
Update trust links for Serbian, UK China and Ukrainian

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#5802]
**Is your feature request related to a problem? Please describe.**
Update trust links for Serbian, UK China and Ukrainian. See the table below for all the links. Serbian and UK China have a script switch so will need a link for each script

**Describe the solution you'd like**

Site | Link | Link works
-- | -- | --
Serbian (Lat) | https://www.bbc.com/serbian/lat/institutional-50173730 | Y
Serbian (Cyr) | https://www.bbc.com/serbian/cyr/institutional-50173730 | Y
UK China(Simp) | https://www.bbc.com/ukchina/simp/institutional-51359562 | Y
UK China(Trad) | https://www.bbc.com/ukchina/trad/institutional-51359562 | Y
Ukrainian | https://www.bbc.com/ukrainian/institutional-50170368 | Y

**Describe alternatives you've considered**
None

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Ticket will be updated to show when the pages have been published

**Comment by sareh** [comment]
PR should not be merged until these assets are published. Otherwise E2E tests will fail.
