### ISSUE TITLE
Remove npm audit whitelisted package - Acorn

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#5814]
**Is your feature request related to a problem? Please describe.**
In https://github.com/bbc/simorgh/pull/5811 we added acorn to the audit-ci whitelist, since other dependencies of ours need to include the updated `acorn` dependency.

We should remove the `--whitelist acorn` from the script. 

**Describe the solution you'd like**
After these PRs that should patch the vulnerabilities:
- jsdom: https://github.com/jsdom/jsdom/pull/2885 ✅ 
- webpack-bundle-analyzer: https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/339 ✅ 
- webpack: https://github.com/webpack/webpack/pull/10518 ✅

We should update our dependencies and remove the whitelist.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by mulholo** [comment]
Webpack bundle analyzer done for you! https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/339

**Comment by FK78** [comment]
Webpack has patched the vulnerability: https://github.com/webpack/webpack/releases/tag/v4.42.1
