### ISSUE TITLE
Testing Script Link behaviour on www.test environment

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#5837]
**Is your feature request related to a problem? Please describe.**

Acceptance criteria for the Script Link:

> When I visit /serbian
> I get redirected to /serbian/lat
> 
> When I visit /serbian/lat
> And have accepted preference cookies (cookie banner)
> And I click on the script link to /serbian/cyr
> I have the ckps_serbian cookie value set to cyr
> 
> When I visit /serbian/cyr
> And have accepted preference cookies (cookie banner)
> And I click on the script link to /serbian/lat
> I have the ckps_serbian cookie value set to lat
> 
> When I visit /serbian/lat
> And have NOT accepted preference cookies (cookie banner)
> And I click on the script link to /serbian/cyr
> No cookie is set
> 
> When I visit /serbian/cyr
> And have NOT accepted preference cookies (cookie banner)
> And I click on the script link to /serbian/lat
> No cookie is set
> 
> 
> 
> When I visit /ukchina
> I get redirected to /ukchina/simp
> 
> When I visit /ukchina/simp
> And have accepted preference cookies (cookie banner)
> And I click on the script link to /ukchina/trad
> I have the ckps_chinese cookie value set to trad
> 
> When I visit /ukchina/trad
> And have accepted preference cookies (cookie banner)
> And I click on the script link to /ukchina/simp
> I have the ckps_chinese cookie value set to simp
> 
> When I visit /ukchina/simp
> And have NOT accepted preference cookies (cookie banner)
> And I click on the script link to /ukchina/trad
> No cookie is set
> 
> When I visit /ukchina/trad
> And have NOT accepted preference cookies (cookie banner)
> And I click on the script link to /ukchina/simp
> No cookie is set

**Describe the solution you'd like**
Should be tested on front pages, e.g. 
`https://www.test.bbc.com/serbian/lat`

**Describe alternatives you've considered**
N/A

**Testing notes**
We already have automated tests, but this ticket is to check this manually.

- [x] This feature is expected to need manual testing.

**Additional context**
N/A

**Comment by jimjohnsonrollings** [comment]
When I visit /serbian/lat
And I already have the ckps_serbian cookie set to cyr
Then I am taken to /serbian/cyr

When I visit /serbian/cyr
And I already have the ckps_serbian cookie set to lat
Then I am taken to /serbian/lat

When I visit /ukchina/simp
And I already have the ckps_chinese cookie set to trad
Then I am taken to /ukchina/trad

When I visit /ukchina/trad
And I already have the ckps_chinese cookie set to simp
Then I am taken to /ukchina/simp

When my ckps_serbian cookie has been set by using the PAL script-switch
Then the Simorgh serbian page respects that cookie

When my ckps_serbian cookie has been set by using the Simorgh script-switch
Then PAL serbian pages respect that cookie

When my ckps_chinese cookie has been set by using the PAL script-switch
Then the Simorgh ukchina page respects that cookie

When my ckps_chinese cookie has been set by using the Simorgh script-switch
Then the PAL ukchina pages respect that cookie

**Comment by sareh** [comment]
Closed as completed.
