### ISSUE TITLE
Code split page components and dynamically their bundles when required

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#5846]
**Is your feature request related to a problem? Please describe.**
Our main bundle size gets larger every time we add a new page type.

**Describe the solution you'd like**
We should code split our pages so that we can dynamically load code for different pages as and when we need them.

Using loadable components we could perhaps do this easily.

We could also prefetch these page bundles i.e. load the other page bundles when the browser is idle so that when the user transitions to the another page type, the code would already be loaded.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
This has been superseded by a newer issue: https://github.com/bbc/simorgh/issues/6988

Newer PR opened: https://github.com/bbc/simorgh/pull/7229
