### ISSUE TITLE
Pass language metadata to ATI for variant MAPs

### ISSUE THREAD

**Issue by RichardPK** [bbc/simorgh#5856]
**Is your feature request related to a problem? Please describe.**
We should pass the language that an article has been viewed in to the ATI page load event:

- Uzbek - either Latin or Cyrillic script.
- Ukrainian - either Ukrainian or Russian language.
- UK china - MAP is published once but there are two variants of the MAP - Simple and Traditional. Which variant is rendered depends on the script switcher.
- Serbian -  MAP is published once but there are two variants of the MAP - Latin and Cyrillic. Which variant is rendered depends on the script switcher.

**Describe the solution you'd like**
Thos language is included in `metadata.language` in the ares response. 

`"language": "uz-Cyrl"`

**Comment by sareh** [comment]
Currently done like this for the front page: https://github.com/bbc/simorgh/blob/latest/src/app/lib/analyticsUtils/frontpage/index.js#L33-L35 It may be useful to reuse existing methods (move them to a shared file)

**Comment by ryanmccombe** [comment]
This should already work - https://github.com/bbc/simorgh/blob/d6a2bce6e20a16527b25b13924f26b866679d642/src/app/containers/ATIAnalytics/params/cpsAssetPage/buildParams.js#L42

**Comment by rebeccamcginn** [comment]
Already working
