### ISSUE TITLE
SMP Controls show in correct language for MAP variants

### ISSUE THREAD

**Issue by RichardPK** [bbc/simorgh#5858]
**Is your feature request related to a problem? Please describe.**
On the Ukranian service - CPS Maps can be published in both Ukranian and Russian. We need to pass the correct language to SMP so that the player controls are shown in that language.

**Describe the solution you'd like**

- If a MAP is published in Russian, we will show Russian translations in the player 
- If a MAP is published in Ukrainian, we will show Ukranian translations in the player 
- If a MAP is being viewed in UK China simplified script, we will show simplified script translations in the player.
etc.

The language is included in `metadata.language` in the ares response. 

Languages:
Ukranian: `"language": "uk"`
Russian:`"language": "ru"`

Scripts:
UK China simp: `"language": "zh-hans"`
UK China trad: `"language": "zh-hant"`

Serbian latin: `"language": "sr"` (note these may not show up on the player- pending SMP release)
Serbian cyrillic: `"language": "sr-cyrl"` (note these may not show up on the player- pending SMP release)

... + Uzbek

**Additional context**
JIRA: https://jira.dev.bbc.co.uk/browse/WSMEDIA-181
- Is this only for Ukranian, or does the same thing apply for different scripts?

**Comment by ryanmccombe** [comment]
This is already implemented - our Morph module passes the value in `metadata.language` from ARES to SMP

**Comment by ryanmccombe** [comment]
Confirmed this should already work - just requires Richard's work to get the embed endpoint working on variant MAPs before it can be manually tested

**Comment by aeroplanejane** [comment]
There is an issue here which wasn't captured in the github issue but specified in WSMEDIA-181. Uzbek only accepts one language code "uz" not "uz-Cyr" or "uz-Latn" so the player on those pages is defaulting to English as we are passing language codes that do not match the corresponding language in SMP. We need to fix so that we pass "uz" only for the Uzbek service, or create two forms in isite to match the language code and get them republish. Given they have only recently done this and they're under a lot of pressure I think we should do the former.

**Comment by aeroplanejane** [comment]
Media Playout changing the lang code to uz-Cyr (JIRA MP-3622) uz-Latn will default to English until we create a new translation file in isite, but editorial are happy to wait to do this.

**Comment by aeroplanejane** [comment]
Tested the following URLs and player controls showing in English. 
This is an SMP mapping issue that we have raised with media-playout to fix see JIRA MP-3625

Serbian: 
https://www.test.bbc.com/serbian/cyr/23279016
https://www.test.bbc.com/serbian/lat/23279016

UK China: 
https://www.test.bbc.com/ukchina/simp/media-23289085
https://www.test.bbc.com/ukchina/trad/media-23289090

Zhongwen: 
https://www.test.bbc.com/zhongwen/trad/23285038
https://www.test.bbc.com/zhongwen/trad/23285038
