### ISSUE TITLE
BUG - When an image is BBC copyright, the copyright should not show

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#5859]
On this page https://www.bbc.com/bengali/multimedia/2012/01/120104_asnasimaligangalpo

BBC is shown as the copyright in the bottom left of the image.

Jane spotted it could be because in copyrightHolder	"bbc" 
The bbc is lowercase

**Comment by aeroplanejane** [comment]
Because of the infrequency of this and the fact it only affects TC2 MAP pages - and the low traffic for TC2s we are not going to fix this.
