### ISSUE TITLE
BUG - 'topcat2' text shows in article, what looks like metadata is in the json paragraph candy xml block

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#5860]
https://www.bbc.com/turkce/multimedya/2014/02/140221_vid_almanya_genelev.json

Maybe a publishing error? Only seen it once

*Karina:*
This is an example where there are multiple tags within a single paragraph. If you compare this to https://pal.live.bbc.com/turkce/multimedya/2014/02/140221_vid_almanya_genelev, it is supposed to render a link to another asset page, but it is missing.

Archive this?

**Comment by gavinspence** [comment]
Won't fix - only seen once
