### ISSUE TITLE
documentLink link type rendered in plain text, not as a link

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#5861]
<documentLink href=\"\" document-type=\"\">\n\nfacebook.com/bbcpersian.dubbing</documentLink>

https://www.bbc.com/persian/tvandradio/2015/07/150721_doublage_truestories_se3

Similar to the link bug we had before which has now been fixed. But this is a link type we have not seen before.

**Comment by graeme-lindsay** [comment]
Can we get some data on occurrence and impact of this?

**Comment by gavinspence** [comment]
Won't fix - only on a small number of TC2 assets
