### ISSUE TITLE
Lots of error messages in Simorgh logs - 404s for AReS responses from the latest batch of MAPs - many legacy, many not.

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#5868]
Thread here: https://bbcnews.slack.com/archives/GHRMZSQ80/p1582823690043200

__Updates__
*28/02* Karina has followed up with AReS - https://bbcnews.slack.com/archives/C70C1RPGE/p1582713452032700
*03/03* Matt from AReS has been in touch - we're still trying to establish a pattern - could it be a crawler?

**Comment by graeme-lindsay** [comment]
This is an example of the wider observability concern - please discuss this with @graemelindsayBBC

**Comment by graeme-lindsay** [comment]
Maybe we should make Simorgh a bit more resilient to 4xx or 5xx errors - i.e. a retry policy?

**Comment by gavinspence** [comment]
Closing as old issue, hi @graemelindsayBBC
