### ISSUE TITLE
Includes script extraction/relocation

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#5878]
**Is your feature request related to a problem? Please describe.**
Following on from the creation of the Includes container and its toggle logic https://github.com/bbc/simorgh-infrastructure/issues/898, the transforming logic needs to be implemented to separate out the scripts from the markup.

This will be is required in order for includes to work correctly following a client-side render (e.g. in future when the user follows a `react-router` link) and preserve the isomorphic nature of the application.

Following this work, we expect:
- IDT2 content should work _for both server-side and client-side rendering_
- A proportion of VJ content will work _for both server-side and client-side rendering_ (we do not expect a change in the actual proportion of content that works)
- IDT1 content will not work

**Describe the solution you'd like**
- Consider using the Storybook approach described in *Testing notes* to see breakage first
- Utilize the [regex](https://github.com/bbc/simorgh/pull/5825) approach to transform the markup before rendering.
- We need to transform the markup to match and strip all occurrences of `<script>` elements from other include markup, as we have seen that script elements don't get executed because of the way they have been created by React (because of the 'parser-generated' flag).
  - Hence we need to match and isolate all `script` elements in the markup, re-create and append each with it's content in the original order into the html body like it's been done [here](https://github.com/bbc/simorgh/blob/e2be22ccec64493d808aa0211dc8fd7fc9ca53ac/src/app/containers/Include/index.jsx#L10..L14).
- Verify behaviour during client-side render (see *Testing notes* below)

**Describe alternatives you've considered**

**Testing notes**
- To be able to test client-side renderering, we could for example create a Storybook story that allows us to change the include URL and re-render the include client-side in Storybook
- We need to test this with a range of content (note that the test harness at the moment only supports server-side rendering of includes).

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by HarveyPeachey** [comment]
~**Blocked** until https://github.com/bbc/simorgh-infrastructure/issues/898 has been completed.~

**Comment by mykeels** [comment]
About relocating the includes script, we noticed that duplicate VJ includes do not initialise correctly. Only the first is successfully initialised by its scripts.

We’ve narrowed it down to the way the VJ scripts are written. 

(See `getCoreContentContainer` in https://news.files.bbci.co.uk/include/newsspec/19077-brexit-glossary/assets/embed/js/embed-init.js?v=1.2.16, which gets the include element by its id).

However, multiple unique VJs have no problem loading.

**Comment by andrewscfc** [comment]
Closing this issue as we no longer intend to implement script extraction and relocation, we have found too many issues with our approach. We will revisit client side rendering support for includes in a future issue.

We are moving on to https://github.com/bbc/simorgh/issues/5750 to complete our serverside rendered includes integration.
