### ISSUE TITLE
Respect Cookie Preferences on Serbian and UKChina 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5890]
**Is your feature request related to a problem? Please describe.**
If users accept personalisation cookies and hit their preference on the script switch, then we should ensure we serve the MAP asset that respects their preference. 

_Why?_ 
Users are more comfortable with one script than the other and in most cases will stick to using just one script. 
_What is the value?_ 
A better user experience, you always see the site in the script you're more comfortable with. Without having to locate and press the switch every time.

**Describe the solution you'd like**
Respect Cookie preferences where they are set and redirect the URLs based on the stored preference 

**Scenario 1: Cookies not Accepted**
Given a user has NOT accepted personalisation cookies 
and they have set their preference by hitting the script switch 
When a user hits bbc.com/ukchina/simp/MAP-12235
then they are served the same URL, bbc.com/ukchina/simp/MAP-12235

**Switch not Set**
Given a user has accepted personalisation cookies 
and they have NOT set their preference by hitting the script switch 
When a user hits bbc.com/ukchina/simp/MAP-12235
then they are served the same URL, bbc.com/ukchina/simp/MAP-12235

**Scenario 3: Cookies Accepted and Preferences Set**
Given a user has accepted personalisation cookies 
and they have set their preference to trad on UK china
When a user hits bbc.com/ukchina/simp/MAP-12235
then they are served bbc.com/ukchina/trad/MAP-12235

Full frontpage behaviour detailed here: https://github.com/bbc/simorgh/issues/5837

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by pharingee** [comment]
Assigning to myself to check to make sure that this works

**Comment by pharingee** [comment]
Checks are complete and the  cookie preferences are being respected on Serbian and UKChina. Closing this.
