### ISSUE TITLE
Script topic page redirect bug

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#5899]
**Describe the bug**
If I have already got the serbian cookie set to `lat`, then I visit this page:
https://www.bbc.com/serbian/cyr/topics/cvjp1d3k9dvt
I get redirected to this page: https://www.bbc.com/serbian/lat/topics/cvjp1d3k9dvt but it 404s since the latin topic for serbian is under a different id: https://www.bbc.com/serbian/lat/topics/cr50vdy9q6wt

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/serbian/cyr & click 'yes' to the cookie banner 
2. Click on script link `'lat'`
3. Then visit this topic page: https://www.bbc.com/serbian/cyr/topics/cvjp1d3k9dvt
4. See it redirect to https://www.bbc.com/serbian/lat/topics/cvjp1d3k9dvt and render a 404 error page.

**Expected behaviour**
To not redirect for topic pages in this way

**Screenshots**
<img width="1434" alt="Screenshot 2020-03-17 at 14 14 22" src="https://user-images.githubusercontent.com/3028997/76864907-cda8ef00-6859-11ea-9087-1a02b6cdf8ef.png">

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
This may be a bug in the Mozart Controller Context (middleware) for Script redirects.

**Comment by sareh** [comment]
@darrenlucas  Hi Darren, could you please look at this and comment on how we should ideally fix this issue for topic pages?

**Comment by sareh** [comment]
I have confirmed that the same bug is present when the script link is enabled on a PAL page, e.g. https://www.bbc.com/serbian/lat/srbija-51907918 instead of the Front page

**Comment by darrenlucas** [comment]
Good spot.

The language redirector middleware that performs the redirect won't have the information from tipo to know what the correct topic id is.

We might need to exclude topic pages from being redirected on the server side.  There should be a client side redirect in place on topic pages which will redirect to the correct topic id for the preferred language variant.

**Comment by sareh** [comment]
@darrenlucas  Thanks for confirming. So just to clarify, an update to [the Mozart Routing middleware that redirects](https://github.com/bbc/mozart-routing/blob/e50380d13e19d2aa6220f108a1f24031bfe7659b/src/lib/mozart_routing/middlewares/world_service_language_redirector.rb#L68-L70) to only server-redirect for pages that aren't topic pages?

**Comment by darrenlucas** [comment]
Yes, I've raised a PR in Mozart Routing and linked to this issue.

> There should be a client side redirect in place on topic pages which will redirect to the correct topic id for the preferred language variant.

I must have misremembered this because it hasn't been implemented, I think the redirector should still exclude topic pages so we don't redirect to a 404, but the user will manually need to switch to their preferred language variant.
