### ISSUE TITLE
Ads: Investigation: How can we support ads alongside our Content Security Policy?

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5922]
**Is your feature request related to a problem? Please describe.**
We currently have a leaderboard ad on the test environment, for the pidgin service's AMP front page: https://www.test.bbc.com/pidgin.amp

<img width="1304" alt="Screenshot 2020-03-19 at 08 27 58" src="https://user-images.githubusercontent.com/6690955/77046954-cc8fd300-69bb-11ea-98b2-7ce5560bc7e0.png">

As you can see, no ad is being loaded into the leaderboard.

This is because we encounter a number of content security policy violations, for the `connect-src` directive (which covers which sources we can make XHR requests to), the `img-src` directive (which covers which sources we can request images from), and the `frame-src` directive (which covers which sources can created nested browsing contexts):

<img width="732" alt="Screenshot 2020-03-19 at 08 29 30" src="https://user-images.githubusercontent.com/6690955/77047135-2bede300-69bc-11ea-991a-59e966e7c30a.png">

We only see these errors on an integrated environment, as when running locally, there is a more relaxed security policy.

**Note: The CSP headers are currently added in the mozart-routing codebase, not in Simorgh**
https://github.com/bbc/mozart-routing/blob/master/src/lib/mozart_routing/headers/simorgh_header.rb

**Describe the solution you'd like**
We need to understand how we can display ads from an ad service, and maintain a content security policy. Can we be provided with a full list of sources that we can add to our CSP, or is this is something that may not be known until the ad is ready to be displayed? 

Fatima from the GNL team has provided this list - we can check to see if this is enough for us to be able to render the ads that we need:

https://paper.dropbox.com/doc/NGAS-Third-party-calls--Aw5uHAzcB7eIGhQSplHpepZHAg-X2gs4ppxOJFbBiFME5f0n

After this, we could also investigate if the CSP meta tag created by https://blog.amp.dev/2020/03/11/easier-amp-development-with-the-new-amp-optimizer/ would cover this use case.
 
**Describe alternatives you've considered**

**Testing notes**
The CSP errors shouldn't be displayed on the console tab.Test with ads from different source list.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Heads up when someone is picking this up, Sareh has been working on a draft PR to include CSP meta tag, which we should be able to update without mozart changes.

**Comment by sareh** [comment]
This Simorgh PR is part 1: https://github.com/bbc/simorgh/pull/6053.
Will open a Mozart PR as part 2 and link that.

**Comment by tochwill** [comment]
After a conversation with Hong Cai, we may need to look into this again. WebCore have had a similar discussion around this that I will link to in a private channel.

**Comment by tochwill** [comment]
I believe we only need to consider top level sources that our page controls in our CSP. Anything requested from within the ad iframe should be covered by the fact we have added this iframe to our frame src. These are documented, and what we previously implemented. We should revisit this and have these requirements documented in our acceptance criteria. If this is not the case, we can revisit.

We also need to ensure that the inline script tags that we will add for the dotcom (GNL) code are covered.

- ‘unsafe-inline’ is already covered by our CSP - I’m hoping this will cover this use case? We will push this to test ASAP to see if this works, and continue conversations with the GNL team based on the outcome of this. This was the issue brought up by the GNL team that make me reopen this issue.
- Webcore instead uses ‘strict-dynamic’ with a [nonce](https://en.wikipedia.org/wiki/Cryptographic_nonce) based approach. This means scripts can be whitelisted using a base64 nonce that is generated by the server each time it transmits a policy.
