### ISSUE TITLE
Ads: GDPR - Ensure personalised ads are only served on AMP pages if user has consented to personalisation (via amp-consent)

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5925]
**Is your feature request related to a problem? Please describe.**
We can only show personalised ads if the user has consented to personalisation. On canonical pages, this is handled using the personalisation cookie. On AMP pages, this is handled using [amp-consent](https://amp.dev/documentation/components/amp-consent/).

We can use the `data-block-on-consent` and `data-npa-on-unknown-consent` attributes on the `amp-ad` component:

- If the user has responded affirmatively to the amp-consent component (user accepts the consent prompt), ads will be requested normally.

- If the user has responded negatively to the amp-consent component (user rejects the consent prompt), non-personalized ads will be requested.
    - If the user’s response to the amp-consent is unknown (user dismisses the consent prompt)
        - By default, no ad requests are sent at all
        - If `data-npa-on-unknown-consent` is set to true, non-personalized ads will be requested

This will need to be merged and tested on the test environment.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
- Unit tests to ensure that we are passing the correct attributes to amp ads
- The amp-ads component should also have its own testing around what is requested.
- Can we have any integration testing to ensure that the ads received are personalised or not?

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Blocked on https://github.com/bbc/simorgh/pull/6079

**Comment by Bopchy** [comment]
Integration tests will be added in https://github.com/bbc/simorgh/issues/6255
