### ISSUE TITLE
Page and Chapter name being incorrectly reported in ATI 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#5927]
**Describe the bug**
We are currently reporting the wrong chapter name for MAPs in Simorgh. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/pidgin/51875041
2. Open the ATI tag inspector 
3. Click on the page load event
4. Note the chapter name 
5. Note the page name 

**Expected behaviour**
The chapter name should correlate to the CPS home of the asset. 
We get the chapter name in the countername in the analytics part of the ares payload. 
If there is no chapter included in the countername, we will not record chapter in the ATI pageload.

The page name label should match the countername. 

We need to make an exception for TC2 assets because they don't return a countername but where a countername exists we should respect it.  
See: afrique/nos_emissions/2014/11/141111_porno_vengeur_ouganda

e.g. 

Page on PAL: http://pal.test.bbc.com/pidgin/media-44221514
Page with embedded_media chapter in Simorgh: https://www.bbc.com/pidgin/media-44221514
Countername: pidgin.**embedded_media**.media_asset.44221514.page

Page in PAL with Africa chapter:https://www.bbc.com/afrique/region-51804055
Countername: afrique.**africa**.media_asset.51804055.page

Page in PAL with no chapter: http://pal.test.bbc.com/pidgin/51875041
Page in Simorgh with no chapter: https://www.bbc.com/pidgin/51875041
Countername: pidgin.media_asset.51875041.page

**Screenshots**
![Screenshot 2020-03-19 at 09 44 16](https://user-images.githubusercontent.com/22519682/77054741-ffd85f00-69c7-11ea-9e42-7b03ccbf08a7.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
This JIRA has the full Media page requirements for pageload in ATI: https://jira.dev.bbc.co.uk/browse/WSMEDIA-59

**Comment by aeroplanejane** [comment]
![image (8)](https://user-images.githubusercontent.com/22519682/77891813-73e8f180-7269-11ea-9f70-6488cdb72d10.png)
![image (4)](https://user-images.githubusercontent.com/22519682/77891965-b6123300-7269-11ea-8b7e-3f6055a2f981.png)
![image (5)](https://user-images.githubusercontent.com/22519682/77891996-c62a1280-7269-11ea-941c-021e9222599c.png)
CPS assets all looking good 👌

**Comment by aeroplanejane** [comment]
In terms of TC2 assets, I messed up the description of this ticket so it's a little confusing... we seem not to record chapter at all on PAL see: 
http://pal.test.bbc.com/afrique/nos_emissions/2014/11/141111_porno_vengeur_ouganda 
http://pal.test.bbc.com/urdu/multimedia/2013/04/130426_sairbeen_april26_pt1

![image (6)](https://user-images.githubusercontent.com/22519682/77893516-ee1a7580-726b-11ea-81c9-61502a95c618.png)
![image (7)](https://user-images.githubusercontent.com/22519682/77893537-f5418380-726b-11ea-96fa-d7368fda118c.png)

Happy that we're now capturing this as chapter but we should also capture "multimedia as chapter and not make an exception. Thanks!

**Comment by LilyL0u** [comment]
looked at a variety of MAPs including cps and tc2, and MAPs without a countername. All were correct!
