### ISSUE TITLE
Refactor styled.extend due to its deprecation.

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#593]
**Is your feature request related to a problem? Please describe.**
According to https://github.com/styled-components/styled-components/issues/1546 the styled.extend will no longer be supported. Since we use it in some places we should refactor the code to use the new styled(component) syntax so that our code doesn't collapse when styled-components upgrades to version 4.

**Describe the solution you'd like**
Ctr+F the entire directory and change any
```JavaScript
component.extend`css`;
```
to

```JavaScript
styled(component)`css`;
```

***Example***
_This code is taken from bach component library_
From:
```JavaScript
const WhatsAppFlex = FlexContainer.extend`
  padding-top: 1em;
  padding-bottom: 1em;
`;
```
To:
```JavaScript
const WhatsAppFlex = styled(FlexContainer)`
  padding-top: 1em;
  padding-bottom: 1em;
`;
```

**Additional context**
https://github.com/styled-components/styled-components/issues/1546 for the full discussion. If you are running jest tests it should start flagging the use .extend as well.

**Comment by bcmn** [comment]
Uses of `styled.extend` have been removed, no need for further work here.
