### ISSUE TITLE
Radio Schedule: correct font for Radio Frequency Link

### ISSUE THREAD

**Issue by OlgaLyubin** [bbc/simorgh#5959]
**Describe the bug**
Radio Frequency Link is not using correct font as in Zeplin Designs:

<img width="262" alt="Screenshot 2020-03-24 at 10 45 30" src="https://user-images.githubusercontent.com/17802955/77417662-96888f80-6dbd-11ea-910d-9023f5a523c4.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a front page that has Radio Schedule
2. Scroll down to Radio Schedule section
3. See error

**Expected behaviour**
Use Reith Sans Regular for the Radio Frequency Link:

<img width="230" alt="Screenshot 2020-03-24 at 10 47 19" src="https://user-images.githubusercontent.com/17802955/77417500-6214d380-6dbd-11ea-8cf0-e673f3c21695.png">

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Looks good to me..
