### ISSUE TITLE
Zhongwen & Portuguese(Brasil) review

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#5961]
**Is your feature request related to a problem? Please describe.**
We want to release Zhongwen and Portuguese front pages. We should check all translations, configuration, and links. 

**Describe the solution you'd like**
- We should check requirements with Jon.
- We should check the service config as well as markup of the page to ensure we have translations for all offscreen text as well as on screen text.
- We should check Chartbeat config, ATI config, consent banners, metadata, navigation links, footer links, trust project links. Note that this should be done for these pages:

https://www.test.bbc.com/zhongwen/simp
https://www.test.bbc.com/zhongwen/trad
https://www.test.bbc.com/portuguese

- If there are any bugs, they should be fixed.
- Then we should review with UX designers (Laura and Ed).

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Unit tests should be sufficient, plus manual checks.

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by OlgaLyubin** [comment]
**Portuguese (Brazil):**
Navigation links ✅
Chartbeat config ✅ 
ATI config ✅
Cookies translations ✅
Skip to Content link ✅

**Trust Project Link** (needs updating but the link is currently not working):
https://www.bbc.com/portuguese/institutional-50054434

**Footer Links:**
- T̶r̶a̶n̶s̶l̶a̶t̶i̶o̶n̶ ̶s̶h̶e̶e̶t̶ ̶h̶a̶s̶ ̶“̶P̶r̶i̶v̶a̶c̶i̶d̶a̶d̶e̶”̶ ̶i̶n̶s̶t̶e̶a̶d̶ ̶o̶f̶ ̶“̶P̶o̶l̶í̶t̶i̶c̶a̶ ̶d̶e̶ ̶p̶r̶i̶v̶a̶c̶i̶d̶a̶d̶e̶”̶. 
- A̶l̶s̶o̶ ̶“̶C̶o̶n̶t̶a̶t̶e̶ ̶a̶ ̶B̶B̶C̶”̶ ̶i̶n̶s̶t̶e̶a̶d̶ ̶o̶f̶ ̶ ̶"̶F̶a̶l̶e̶ ̶c̶o̶m̶ ̶a̶ ̶B̶B̶C̶"̶
- There is an additional footer item that is not in the translation sheet ("AdChoices / Do Not Sell My Info")

**Consent Banner -> Privacy -> International** is in English:
"We've made some important changes to our Privacy and Cookies Policy and we want you to know what this means for you and your data."
It should be: "Nós fizemos importantes modificações nos termos de nossa Política de Privacidade e Cookies e gostaríamos que soubesse o que elas significam para você e para os dados pessoais que você nos forneceu."

**Translations:**
- T̶h̶e̶r̶e̶ ̶i̶s̶ ̶n̶o̶ ̶t̶r̶a̶n̶s̶l̶a̶t̶i̶o̶n̶ ̶f̶o̶r̶ ̶"̶L̶i̶s̶t̶e̶n̶"̶ f̶o̶r̶ ̶r̶a̶d̶i̶o̶ ̶b̶u̶l̶l̶e̶t̶i̶n̶ Edit: there is currently no radio for BBC Brasil (Portuguese)

**Comment by jimjohnsonrollings** [comment]
Chartbeat:
* Portuguese: brasil.bbc.co.uk
* Zhongwen: zhongwen.bbc.co.uk

ATI
* Portuguese app-name: news-portuguese
* Portuguese producer id: 33
* Zhongwen app-name: news-zhongwen
* Zhongwen producer id: 38

**Comment by hotinglok** [comment]
Zhongwen (both simp and trad):
Navigation links ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link ✅

Trust Project link updated from the news one to the new ones (to be filled out by editorial):
https://www.bbc.com/zhongwen/simp/institutional-51359584
https://www.bbc.com/zhongwen/trad/institutional-51359584

Footer Links:
All links updated since every link were just the news links. These can be found in the translations spreadsheet.

Translations:
Changed `Contact the BBC` translation from 联络BBC to 与BBC联络 in simp and 與BBC聯絡 in trad.
