### ISSUE TITLE
Radio Schedules: Durations of an hour or longer are being formatted incorrectly

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#5964]
**Describe the bug**
In the radio schedules component, durations of an hour or longer are being formatted incorrectly - the 'hour' is not being displayed.

<img width="1078" alt="Screenshot 2020-03-24 at 12 23 41" src="https://user-images.githubusercontent.com/6690955/77425268-60054180-6dca-11ea-8f28-a3452c843c86.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/swahili?renderer_env=live
2. View the radio schedules section
3. 'Dira Ya Dunia' should have a duration of 1:00:00. It is displaying as 00:00.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by EinsteinNjoroge** [comment]
FIxed in https://github.com/bbc/simorgh/pull/5978
