### ISSUE TITLE
Hindi, Mundo, Russian review

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#5969]
**Is your feature request related to a problem? Please describe.**
We want to release Hindi, Mundo and Russian front pages. We should check all translations, configuration, and links. Similar to the work in this issue: https://github.com/bbc/simorgh/issues/5961

**Describe the solution you'd like**
- We should check requirements with Jon.
- We should check the service config as well as markup of the page to ensure we have translations for all offscreen text as well as on screen text.
- We should check Chartbeat config, ATI config, consent banners, metadata, navigation links, footer links, trust project links. Note that this should be done for these pages:

https://www.test.bbc.com/hindi
https://www.test.bbc.com/mundo
https://www.test.bbc.com/russian

- If there are any bugs, they should be fixed.
- Then we should review with UX designers (Laura and Ed).

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Unit tests should be sufficient, plus manual checks.

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by OlgaLyubin** [comment]
**Russian:**
Navigation links ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link ✅
Trust Project Link ⛔️ (updated in https://github.com/bbc/simorgh/pull/6023)
Footer Links ✅
Translations ⛔️ (updated in https://github.com/bbc/simorgh/pull/6023)

**Comment by OlgaLyubin** [comment]
**Hindi:**
Navigation links ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link ✅
Trust Project Link ✅
Footer Links ⛔️ (updated in #6023)
Translations ⛔️ (updated in #6023)
