### ISSUE TITLE
Update trust links for Sites with Adverts

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#5975]
**Is your feature request related to a problem? Please describe.**
Update the trust project links to each site. Some links currently 404 and will be updated by the editorial team. Don't merge this ticket until all the links work

**Describe the solution you'd like**
Update the floowing sites. 

Site | Link | Link works
-- | -- | --
Zhongwen (Simp) | https://www.bbc.com/zhongwen/simp/institutional-51359584 | N
Zhongwen (Trad) | https://www.bbc.com/zhongwen/trad/institutional-51359584 | N
Hindi | https://www.bbc.com/hindi/institutional-50223932 | Y
Arabic | https://www.bbc.com/arabic/institutional-49283069 | Y
Mundo | https://www.bbc.com/mundo/institucional-51359666 | Y
Russian | https://www.bbc.com/russian/institutional-50098149 | N
Portuguese | https://www.bbc.com/portuguese/institutional-50054434 | N

The trust link is in each config file
https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/tamil.js

**Describe alternatives you've considered**
None

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Don't merge until all the above pages work..

**Comment by OlgaLyubin** [comment]
Trust links for all of the services above have already been updated.
