### ISSUE TITLE
Latin font on Tamil page not displaying as italic (could be on other pages)

### ISSUE THREAD

**Issue by graeme-lindsay** [bbc/simorgh#5977]
The page has a mixture of Tamil and Latin script.
On PAL, some of the latin script is in italics, but on Simorgh they are displaying as normal.
Simorgh: https://www.bbc.com/tamil/science/2015/02/150222_cannabis_reasearch

Ryan had a look and saw that the font, despite being in italics, was being set to normal, but when this is removed it displays in italics.

I first thought this is a small problem, but then I realised that in scientific writing it is common to use italics for things like species, and also when talking about viruses: https://wwwnc.cdc.gov/eid/page/scientific-nomenclature
Even if coronavirus is not one of these, there is likely to be more writing about diseases and animal species around this time.
I don’t know if this is the formal way of doing it in other languages though, so maybe it isn’t as much of a problem as it would be in English language websites??

https://bbcnews.slack.com/archives/CJT0284G2

**Comment by graeme-lindsay** [comment]
@eddemi85 - We believe there may be rules behind this lack of italicisation within Tamil and we were wondering if you had any insight form a UX perspective?

**Comment by graeme-lindsay** [comment]
Added this to the MAP Improvements milestone for future prioritisation cc @gavinspence @aeroplanejane

**Comment by aeroplanejane** [comment]
This is expected see: https://bbcnews.slack.com/archives/CHTF3GCTH/p1595943456378700 Closing
