### ISSUE TITLE
Update Marathi timestamps in Simorgh

### ISSUE THREAD

**Issue by OlgaLyubin** [bbc/simorgh#5980]
**Is your feature request related to a problem? Please describe.**
Marathi timestamps were updated in Psammead here https://github.com/bbc/psammead/pull/3250
We now need the same change to be displayed in Simorgh (https://bbc.github.io/simorgh/?path=/story/moment-locales-editorial-view--marathi-mr)

**Describe the solution you'd like**
Use Marathi timestamps that do not have "ago" split into a separate word (like it is currently done in Psammead https://bbc.github.io/psammead/?path=/story/utilities-psammead-locales--moment-marathi-mr).

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by JonBeeb** [comment]
It looks like this is now fine with the release today (26/3)

**Comment by EinsteinNjoroge** [comment]
Closed as done
