### ISSUE TITLE
IDT2 includes AMP support

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#5988]
**Is your feature request related to a problem? Please describe.**
In order to render IDT2 content on AMP pages we need to output a responsive flat image of the content with an alt attribute

The information required to create this image will be included in the Ares response based on data retrieved from the smallprox `/amp` 'mutator', following ARES-1007

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by lizcameron** [comment]
Replaced by https://github.com/bbc/simorgh/issues/6563
