### ISSUE TITLE
If VJ Include has an AMP alternative, ensure we fetch it and make it available

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#5989]
**Is your feature request related to a problem? Please describe.**
So far we do not render any VJ content on AMP pages. However more recent (c. 2018-) VJ includes have an AMP version available (the so-called 'AMP wrapper') on the `/amp` endpoint.

**Describe the solution you'd like**
Where a VJ include is known to have an AMP version, we should request it and add it to the Include block so that it's available to the page. Otherwise the block should be omitted.

**Possible routes**
1. See additional context below on `amp-image` query parameter.
2. Can Ares decorate existing Include data to tell us whether there is an AMP version available?
3. If we cannot determine the Include has an AMP version (i.e. confirm it was published after 2018) _before_ fetching it - we may have to fetch it from the `/amp` and determine its availability through HTTP status codes. 404/200.

Note: We should keep unnecessary network requests to a minimum.

**Describe alternatives you've considered**

**Testing notes**
- Need to test this with a mixture of VJ content old and new to ensure it is working as expected across canonical and AMP.

[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
- According to @eagerterrier the presence of the `amp-image` query parameter on the include path is expected to be a reliable way of determining if an AMP version is available.
- The pathname may be available to us, if we want to check which platform (AMP/Canonical) we are in, inside the pre-processor: https://github.com/bbc/simorgh/pull/6758.

**Comment by andrewscfc** [comment]
Just reviewing @Simon2828's draft PR, looks like we forgot a major implementation detail for amp includes that we need to implement, I've copied this from our 'WS Includes Approach' Paper:

> Most includes categorised as VJ based on their path can have `/amp` added, this rendering a full page that can be used as the `src` for an [amp-iframe](https://amp.dev/documentation/components/amp-iframe/). The full path is constructed with `https://news.files.bbci.co.uk/` followed by the vj include path with `/amp` at the end, so:
>
>`https://news.files.bbci.co.uk/` → `/include/vjamericas/176-eclipse-lookup/mundo/app` → `/amp`
> https://news.files.bbci.co.uk/include/vjamericas/176-eclipse-lookup/mundo/app/amp 

We can add url to our includes block to be used when implementing https://github.com/bbc/simorgh/issues/6841#issuecomment-641376986, rendering an amp iframe.
