### ISSUE TITLE
Run e2e tests against each build type

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#60]
**Is your feature request related to a problem? Please describe.**
We should be able to run our e2e tests easily against both dev and production builds.

**Describe the solution you'd like**
Add a variable to the `npm test:e2e` script so that it can be run against prod.
EG: `npm test:e2e --env=prod`

**Describe alternatives you've considered**
This could be separated out into a new script.
EG: `npm test:e2e:prod`

**Additional context**
This work is dependant on https://github.com/bbc/simorgh/pull/58 being finished as it requires the chaining of starting the server and running the tests.

**Comment by jamesbhobbs** [comment]
Implemented differently to the description, but still done.
