### ISSUE TITLE
BBC Russian - Add coronavirus to navigation bar

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#6026]
**Is your feature request related to a problem? Please describe.**
BBC Russian - Add coronavirus to navigation bar

**Describe the solution you'd like**
Add the following
title : 'Коронавирус '
url : '/russian/in-depth-51962199'

position: second item in the list

Thsi should reflect the navigation on this page: 
https://www.bbc.com/russian/features-52070859
 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Closed as fixed by #6028
