### ISSUE TITLE
Tidy up character escaping/unescaping

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#6035]
**Is your feature request related to a problem? Please describe.**
In a few places in the application we are escaping HTML characters, for example:

- Converting escaped characters in paragraph blocks back to the literal form: https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/paragraph/helpers.js#L8-L24
- Escape less than/greater than/ampersands in the text of internal links: https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/internalLinks/index.js#L53-L57

Some or all of these local solutions may be rendered obsolete by https://github.com/bbc/simorgh/pull/6019, we should therefore look at whether this code is still required and if not then remove it.

**Describe the solution you'd like**
- identify existing approaches for escaping/unescaping (consider HTML but also URL encoding or other special character escaping
- determine which (if any) of these are not needed and remove them
- for the remainder, look for opportunities to simplify these or make them more consistent

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
This seems like logic that would be moved to the BFF
