### ISSUE TITLE
BBC Indonesia - Add item to navigation bar

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#6039]
**Is your feature request related to a problem? Please describe.**
BBC Indonesia - Add item to navigation bar

**Describe the solution you'd like**
Add the following item in the navigation bar on BBC Indonesia

position: last item in list

link text: 'Majalah'
link : /indonesia/majalah-51456120

An example can be seen here: https://www.bbc.com/indonesia/majalah-51456120 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
Closed as fixed by #6042
