### ISSUE TITLE
Investigate suitable timestamp library

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#604]
**Is your feature request related to a problem? Please describe.**
We need to display the absolute and relative timestamp using different formats and in different languages. This will be extended in the future to include multiple timezones, different calendars, etc.

**Describe the solution you'd like**
Present two or more solutions to render a relative timestamps (i.e. x hours ago).
Considerations:
- Ability to internationalise the timestamp (post v1.0)
- Flexibility to allow for custom timestamp formats (both relative and absolute). We should discuss this with the wider engineering team, particularly L+R.
- Flexiblity for different plurality (and duality) wording for multiple languages

State which solution is preffered and why.

**Additional context**
Even thought we won't implement any i18n functionality yet, this has to be thought about early on.

**Comment by ChrisBAshton** [comment]
We tackled this recently in VJ: https://github.com/bbc/cmu-timeline/pull/21

TLDR; opted for `toLocaleString`, falling back to a simple dd/mm/YY format for browsers that don't support it. Wanted to avoid the bloat of a library.

**Comment by ChrisBAshton** [comment]
Replaced by #637
