### ISSUE TITLE
Investigate adding Recommendations to the correct position on a story page

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#6066]
**Is your feature request related to a problem? Please describe.**
We need to Investigate how to add recommendations content to the correct position on a story page.

**Describe the solution you'd like**
The recommendations block needs to be positioned after the 7th element on a story (an element is a paragraph, image, audio/video, etc.). This is to match the as-is position on live, which has been through thorough testing to confirm this is the optimum position.
We'll need to investigate how this works in relation to the Optimo blocks - i.e. does a CPS STY 'element' and a Simorgh STY page 'block' mean the same thing, so that placing Recommendations after 7 of these elements or blocks results in it appearing in the same place on the page? Double check this with @lizcameron during the investigation. 
Report back and recommend and approach to the team.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
- Element can mean paragraphs, images, or audio/video
- https://www.bbc.com/portuguese/brasil-52077132
- Mundo: https://www.bbc.com/mundo/noticias-41702909

**Comment by rhenshaw56** [comment]
Currently our blocks order determine how item/items are rendered on a story page. Block placement logic is handled in the pre-processors. So the only plausible way of having logic that adds a recommendation block would be having a pre-processor rule specifically for this.

Here's a [draft pr](https://github.com/bbc/simorgh/pull/6236) showing how this could be achieved.

**Comment by rhenshaw56** [comment]
closing as this will be addressed in https://github.com/bbc/simorgh/issues/6263
