### ISSUE TITLE
Fetch Recommendations OJ data from Ares endpoint

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#6067]
**Is your feature request related to a problem? Please describe.**
We want to fetch Recommendations data from Deimos which fetches from the Camino endpoint API. The recommendations onward journey is only being be used by five different services at the moment: This should be implemented in a way which will allow more services to use this.

- Arabic
- Hindi
- Mundo
- Portuguese (Brasil)
- Turkce (Turkish)

**Describe the solution you'd like**
Recommendations should be fetched from the Ares (Deimos) endpoint when their work has been completed which fetches data from the original Camino API. This endpoint will be hit via Mozart: (example URL will be added once Mozart work is completed). This is similar to to most read and the secondary column, so we might want a similar approach on how to fetch the data in Simorgh. Work for the Ares (Deimos) endpoint is encapsulated in Jira tickets `ARES-965` and `ARES-967`.

We will need to build the URL to hit the correct endpoint based on the article being rendered. We also need to think about what stage we want to prevent the Recommendations OJ rendering for services which don't currently use it. 

There is also a flag in the CPS Ares data under metadata called `allowAdvertising` which will be set to `true` if the service should render the component or `false` if it shouldn't.

The data fetch should only be made if the services should have the WSOJ component and if the `allowAdvertising` flag is called.

We should also ensure this work is behind a feature toggles for the different environments.

Create a log event in the container which logs that Simorgh should be rendering the recommendations component.

This will need a basic container creating to test the data fetching has been implemented correctly. The front-end component https://github.com/bbc/simorgh/issues/6266.

**Describe alternatives you've considered**

**Testing notes**
- Automated tests needed, Integration test
- Ensure the API call is only made when all success criteria are met e.g. is a valid service, allowAdvertising is `true` and feature toggle is enabled.

- [X] This feature is expected to need manual testing.

**Additional context**
~Need to confirm if Unirecs API can be publicly facing. Join dev-new_recs on slack to confirm this.~ - This work will now not use Unirecs API for the time being.

**Comment by FK78** [comment]
Recommendations data fetch work has been done in this [PR](https://github.com/bbc/simorgh/pull/6283).

**Comment by lizcameron** [comment]
~Blocked - awaiting confirmation of whether we can instead be calling the universal recommendations API, rather than directly calling Camino. This is because Camino is in the process of moving behind the unirecs API.~
