### ISSUE TITLE
Update the remaining trust project links

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#6070]
**Is your feature request related to a problem? Please describe.**
The remaining trust project links are all published!

**Describe the solution you'd like**
Update the final set of trust links.

Site | Link | Link works
-- | -- | --
Pashto | https://www.bbc.com/pashto/institutional-49283007 | Y
Hausa | https://www.bbc.com/hausa/game-da-mu-49283501 | Y
Persian | https://www.bbc.com/persian/institutional-49283091 | Y
Somali | https://www.bbc.com/somali/hayadeed-49283375 | Y
Swahili | https://www.bbc.com/swahili/taasisi-49283417 | Y
Korean | https://www.bbc.com/korean/institutional-49283197 | Y
Arabic | https://www.bbc.com/arabic/institutional-49283069 | Y
Afrique | https://www.bbc.com/afrique/institutionelles-49283281 | Y

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by OlgaLyubin** [comment]
All of these trust project links are already added to services config files.
