### ISSUE TITLE
Update Pashto Homepage to use dual calendars

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#6080]
**Is your feature request related to a problem? Please describe.**
The current PAL homepage for Pashto shows the date as using a dual calendar format. The date format on the new Pashto homepage is only showing 1 calendar. This should show a dual calendar (as seen in other Simorgh pages). 

The dual calendar format example can be seen here
https://www.bbc.com/pashto/afghanistan-52114144

**Describe the solution you'd like**
Any date on the Pashto homepage should use the dual calendar format

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Homepage
![image](https://user-images.githubusercontent.com/16046375/78268477-24702300-7500-11ea-9112-d4c134d3948d.png)

Simorgh page
https://www.bbc.com/pashto/afghanistan-52114144
![image](https://user-images.githubusercontent.com/16046375/78268664-6c8f4580-7500-11ea-8a7a-38954f5ac6ed.png)

**Comment by sareh** [comment]
Closed as fixed.
