### ISSUE TITLE
Constrain the Story Page's maximum width

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#6082]
### Is your feature request related to a problem? Please describe.
The Story Page's maximum width is not constrained. We need to be consistent with PAL and other pages (e.g. `pages/FrontPage`).

### Describe the solution you'd like

Talk to the Media Page team about this change; explain the changes and why we're doing it.

1. Complete https://github.com/bbc/simorgh/issues/4054 (from 1 Oct 2019).
2. Use this Component ☝️ to constrain the width of the Story Page. Assuming this component is a div, we need to nest the Story Page content within it.

_Note: Completing Step 1 will mean teams can fix diverging pages in a DRY and consistent way._

### Describe alternatives you've considered
n/a

### Testing notes

Snapshots will be updated.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

### Additional context
n/a

**Comment by oluoluoxenfree** [comment]
Blocked by #4054
