### ISSUE TITLE
Apply CSP headers on localhost development build

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6089]
**Is your feature request related to a problem? Please describe.**
As a result of this PR https://github.com/bbc/simorgh/pull/6053, we are applying Content Security Policy headers on the production build of Simorgh (`npm run build && npm run start`). 
This ticket is to extend that to the development build `npm run dev`

**Describe the solution you'd like**
- apply injectCspHeader directly and remove this conditional check: https://github.com/bbc/simorgh/pull/6053/files#diff-788dcef7a5e3a2740bf71979cca64a59R96
- Fix the eval errors that appear on Canonical pages. See Tom's comment here as to suggested approach: https://github.com/bbc/simorgh/pull/6053/files#r402942946
- Add any required directives to the nonLive list of directives in this file: `src/server/utilities/cspHeader/index.js`
- Test with all of these assets locally with the dev build:

http://localhost:7080/pidgin.amp - AMP front page with ad & toggle
http://localhost:7080/pidgin/media-44221514.amp - AMP MAP
http://localhost:7080/pidgin/tori-51745682.amp - AMP STY
http://localhost:7080/mundo/23263889.amp - AMP STY with includes
http://localhost:7080/pidgin/tori-49221071.amp - AMP PGL
http://localhost:7080/pidgin/articles/cwl08rd38l6o.amp - AMP Optimo Article
http://localhost:7080/persian/bbc_persian_radio/liveradio.amp - AMP Live Radio
http://localhost:7080/pidgin - canonical front page
http://localhost:7080/pidgin/media-44221514 - canonical MAP
http://localhost:7080/pidgin/tori-51745682 - canonical STY
http://localhost:7080/mundo/23263889 - canonical STY with includes
http://localhost:7080/pidgin/tori-49221071 - canonical PGL
http://localhost:7080/pidgin/articles/cwl08rd38l6o - canonical Optimo Article
http://localhost:7080/persian/bbc_persian_radio/liveradio - canonical Live Radio

**Describe alternatives you've considered**
We could choose to not make this change, but then we'll see issues with CSP headers after merging & it getting deployed up to the Test env / or remembering to manually check the `npm run build && npm run start` prod build locally. 

**Testing notes**
[Tester to complete]

Dev insight: Manually testing and checking the console.

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by jamesdonoh** [comment]
What is the use case for having a fully working CSP under `npm run dev`? Personally I would've thought just using `npm run build` when we need to maintain the CSP is sufficient. And things like port 1124 feel like implementation detail of the dev server that could change.
