### ISSUE TITLE
BUG - Portuguese error message is in English

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#6122]
Comment from Jonathan: I'm guessing that particular error message will be inside the embed i.e. in morph and not simorgh

Comment from Ryan: looks like a mismatch between what lang ARES returns, and what SMP expects
ARES has lang set to “pt-BR” - SMP expects “pt”

![Screenshot_20200407-143724](https://user-images.githubusercontent.com/54575620/78679231-df723500-78e1-11ea-8530-b1122780e0da.png)

**Comment by sareh** [comment]
This should be able to be fixed by adding a new field in the Service contexts `mediaPlayerLang` and passing that to the player. https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/portuguese.js#L22

**Comment by aeroplanejane** [comment]
We think SMP will resolve this on their side but we don't have an ETA on a fix yet see: https://jira.dev.bbc.co.uk/browse/MP-3625

**Comment by aeroplanejane** [comment]
Same fix for https://github.com/bbc/simorgh/issues/5858
