### ISSUE TITLE
Resolve Routing of Russian MAPs

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6129]
Russian MAPs not being routed in Test correctly due to page URL not matching the pattern for all other MAPs - e.g russian/__av__/media-12345

https://www.test.bbc.com/russian/av/media-52062077?renderer_env=live

AReS https://ares-broker.api.bbci.co.uk/api/asset/russian/media-52062077

Slack: https://bbcnews.slack.com/archives/CJT0284G2/p1585301213137000

Please ensure that Test & Live E2Es are included as part of this work

**Comment by ryanmccombe** [comment]
This is waiting a Mozart deployment to TEST.

Had to do a slightly weird implementation to get around the fact that TEST will go to Simorgh but LIVE will go to PAL.   In the interim, any request to `test.bbc.com/russian/av/:id` will be redirected to `test.bbc.com/russian/:id?renderer_env=live`

The `renderer_env` query string is included to eliminate a potential infinite redirect loop that would be caused were someone to request a live asset on the test environment.

Most Russian MAPs on the test environment legitimately have `/av` in the asset ID, so this implementation will make them unavailable for testing.  However, none of the Live assets do, so this will work fine in production and can be played around with on test using the `renderer_env` override

Note when putting Russian MAPs live, some cleanup work will need to be done to remove the querystring from the redirect - this is documented in the code next to the LIVE switch for Russian MAPs

**Comment by aeroplanejane** [comment]
@ryanmccombe and @RichardPK I think this can be closed now right? Seems like a duplicate..

**Comment by RichardPK** [comment]
Yup @aeroplanejane - will do now
