### ISSUE TITLE
Fonts refusing to load on localhost due to Content Security Policy

### ISSUE THREAD

**Issue by mykeels** [bbc/simorgh#6131]
**Describe the bug**
Following [this](https://github.com/bbc/simorgh/pull/6101#pullrequestreview-389840297) and [that](https://github.com/bbc/simorgh/pull/6101#pullrequestreview-389840297) comment.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to http://localhost:7080/mundo/23263889
2. Inspect the console
3. See font errors:

https://user-images.githubusercontent.com/3028997/78772873-5236eb00-798a-11ea-88b7-b50917cef115.png

https://user-images.githubusercontent.com/11996508/78773554-4e579880-798b-11ea-8507-40ddaba2cfc5.png

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
I believe the better way to address this error would be to serve fonts from here, instead of from localhost:

https://ws-downloads.files.bbci.co.uk/fonts/ReithSans/v2.511/medium.woff
https://ws-downloads.files.bbci.co.uk/fonts/ReithSans/v2.511/normal.woff

**Comment by sareh** [comment]
Looking at this page on the Test environment, I see that my previous comment was mistaken. These font files are being requested:

https://static.test.bbc.co.uk/news/1.312.03579/fonts/gel-news-icons-v3/gelnewsicons-regular-webfont.woff
https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff2
https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2

As part of this work, we can ensure these domains are on the relevant CSP headers for Test:
```
https://static.test.bbc.co.uk
https://gel.files.bbci.co.uk
https://fonts.gstatic.com
```
And these for Live:
```
https://static.bbc.co.uk
https://gel.files.bbci.co.uk
https://fonts.gstatic.com
```
