### ISSUE TITLE
On Demand Radio Page has correct page metadata 

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6133]
- [x] Ensure that standard metadata is present within the `<head>` of the page as per requirements [#WSMEDIA-186 - Page Data](https://jira.dev.bbc.co.uk/browse/WSMEDIA-186)
- [ ] Ensure OpenGraph (Facebook & Twitter metadata) is present as per requirements [#WSMEDIA-186 - OpenGraph](https://jira.dev.bbc.co.uk/browse/WSMEDIA-185)
- [ ] Automated tests to ensure metadata correct - unit & integration

**Additional Information:** 
https://paper.dropbox.com/doc/On-Demand-Audio-SEO-Metadata--AxvL5ADACVHXwYNBm7Ehjo~tAg-9ccFbhwazDB56TYzhSZVP#:uid=470258354415408089015900&h2=Page-Data

**Testing Checklist:** 
- [ ] OpenGraph - Use https://developers.facebook.com/tools/debug/
- [ ] https://opengraphcheck.com

**URLs:**
| Indonesia | Pashto |
| -- | -- |
| https://www.test.bbc.com/indonesia/bbc_indonesian_radio/w172x6r5000f38s?renderer_env=live | https://www.test.bbc.com/pashto/bbc_pashto_radio/w172x8nvf4bchz5?renderer_env=live | 
 
**Expected Results:**
| Metadata Tag | Indonesia | Pashto |
| ---  | ---------  | ------ |
| meta[http-equiv="X-UA-Compatible"] | IE=edge | IE=edge | 
| meta[name="robots"] |  noodp,noydir | noodp,noydir | 
| meta[name="theme-color"] |  #B80000 | #B80000 | 
| meta[name="viewport"] |  width=device-width, initial-scale=1, minimum-scale=1 | width=device-width, initial-scale=1, minimum-scale=1 | 
| meta[name="apple-mobile-web-app-title"] |   BBC News Indonesia | BBC News پښتو | 
| meta[name="application-name"] |   BBC News Indonesia | BBC News پښتو | 
| meta[name="description"] | Berita terbaru dari seluruh dunia dan ulasan peristiwa dari Indonesia. Juga berita olahraga terbaru dan berbeda setiap harinya. |د نړۍ وروستي خبرونه |
|  meta[property="fb:admins"] |  100004154058350 | 100004154058350 | 
| meta[property="fb:app_id"] | 1609039196070050 | 1609039196070050 |
| meta[name="mobile-web-app-capable"] |  yes | yes | 
| meta[name="msapplication-TileColor"] |  #B80000 | #B80000 | 
| meta[name="msapplication-TileImage"] |  https://news.files.bbci.co.uk/include/articles/public/indonesia/images/icons/icon-144x144.png | https://news.files.bbci.co.uk/include/articles/public/pashto/images/icons/icon-144x144.png | 

| OpenGraph Tag | Indonesia | Pashto |
| ---  | ---------  | ------ |
| meta[name="og:description"] | Berita terbaru dari seluruh dunia dan ulasan peristiwa dari Indonesia. Juga berita olahraga terbaru dan berbeda setiap harinya. |د نړۍ وروستي خبرونه |
| meta[property="og:image"] | https://news.files.bbci.co.uk/ws/img/logos/og/indonesia.png | https://news.files.bbci.co.uk/ws/img/logos/og/pashto.png |
| meta[property="og:image:alt"] | BBC News Indonesia | BBC News پښتو |
| meta[property="og:locale"]` | id-ID | ps |
| meta[property="og:site_name"] | BBC News Indonesia | BBC News پښتو |
| meta[name="og:title"] | Dunia Pagi Ini - BBC News Indonesia |وروستي خبرونه - BBC News پښتو |
| meta[property="og:type"] | website | website |
| meta[property="og:url"] | https://www.test.bbc.com/indonesia/bbc_indonesian_radio/w172x6r5000f38s | https://www.test.bbc.com/pashto/bbc_pashto_radio/w172x8nvf4bchz5 |

| Twitter Tag | Indonesia | Pashto |
| ---  | ---------  | ------ |
| meta[name="twitter:card"] | summary_large_image | summary_large_image |
| meta[name="twitter:creator"] | @bbcindonesia | @bbcpashto |
| meta[name="twitter:description"] | Berita terbaru dari seluruh dunia dan ulasan peristiwa dari Indonesia. Juga berita olahraga terbaru dan berbeda setiap harinya. |د نړۍ وروستي خبرونه |
| meta[name="twitter:image:alt"] | BBC News Indonesia | BBC News پښتو |
| meta[property="twitter:image:src"] | https://news.files.bbci.co.uk/ws/img/logos/og/indonesia.png | https://news.files.bbci.co.uk/ws/img/logos/og/pashto.png |
| meta[name="twitter:site"] | @bbcindonesia | @bbcpashto |
| meta[name="twitter:title"] | Dunia Pagi Ini - BBC News Indonesia |وروستي خبرونه - BBC News پښتو |

**Comment by LilyL0u** [comment]
@karinathomas do you have a list of what the standard metadata tags and open graph tags are meant to be? Need to check I am seeing all the expected tags

**Comment by karinathomasbbc** [comment]
@LilyL0u do you have access to https://developers.facebook.com/docs/sharing/webmasters/ - this lists the basic set of tags required (if you can't view this, I'll try and paste the info here).

We should have implemented all of these for the on demand radio page. 

You can also use the Structured Data Testing Tool to give you the information:

Open a terminal window
`npm i -g structured-data-testing-tool`

Once it has finished installing, you can run the following command to see which tags the page has + values

`sdtt -u https://www.stage.bbc.com/indonesia/bbc_indonesian_radio/w172x6r5000f38s?renderer_env=live -i`

Further instructions here: https://www.npmjs.com/package/structured-data-testing-tool#usage

**Comment by karinathomasbbc** [comment]
As for the standard ones, the Cypress tests contain a list of all the ones we expect for each page type - https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllPages.js - search for `meta[` and this will give you all of the tags.

**Comment by karinathomasbbc** [comment]
@LilyL0u I have updated the comment https://github.com/bbc/simorgh/issues/6133#issue-596627441 with the expected values for all metadata tags for the 2 services (Indonesia & Pashto) on test

**Comment by LilyL0u** [comment]
https://developers.facebook.com/tools/debug/ only works for pages that have been shared on facebook before

https://opengraphcheck.com does not show meta[property="og:image:alt"], but everything else looks good

**Comment by LilyL0u** [comment]
https://opengraphcheck.com does not show twitter tags, but I tested them by looking in the <head> and they are all correct

**Comment by karinathomasbbc** [comment]
@LilyL0u there should be an option to fetch new information for Facebook - there should be a button below where you enter the URL? 
![image](https://user-images.githubusercontent.com/58214768/79350768-c3007900-7f2f-11ea-9092-045755ccac1d.png)

Otherwise you can try these: 
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.test.bbc.com%2Findonesia%2Fbbc_indonesian_radio%2Fw172x6r5000f38s%3Frenderer_env%3Dlive

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.test.bbc.com%2Fpashto%2Fbbc_pashto_radio%2Fw172x8nvf4bchz5%3Frenderer_env%3Dlive

**Comment by karinathomasbbc** [comment]
> https://opengraphcheck.com does not show twitter tags, but I tested them by looking in the and they are all correct

Yeah open graph only works for metatags prefixed with `og:`

**Comment by LilyL0u** [comment]
Oh wow how did I not see that button

**Comment by LilyL0u** [comment]
On https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.test.bbc.com%2Fpashto%2Fbbc_pashto_radio%2Fw172x8nvf4bchz5%3Frenderer_env%3Dlive
some things are a bit strange:
og:title is undefined - BBC News پښتو
og:description is the copyright © 2020 بي بي سي. بي بي‌ سي‌ د نورو ویبپاڼو د محتوا مسوله نه ده. د نورو ویبپاڼو لینکولو په اړه زموږ تګلار
og:locale is empty

But these were fine on https://opengraphcheck.com

**Comment by karinathomasbbc** [comment]
Also seeing og:description = © 2020 بي بي سي. بي بي‌ سي‌ د نورو ویبپاڼو د محتوا مسوله نه ده. د نورو ویبپاڼو لینکولو په اړه زموږ تګلاره. - I am fairly sure that's the copyright / footer information, and definitely not what's in the HTML header. I think if we just inspect the HTML manually, we'll see the correct results.

**Comment by LilyL0u** [comment]
Yeah it's fine in the HTML. As long as this isn't a problem: that some places will take the wrong field for the desciption etc. then I am happy to move this issue to done.
