### ISSUE TITLE
On Demand Radio Page has correct ATI page metadata

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6134]
...so that we can generate reports and insights that help us improve our reach and engagement.

- [x] _ATI metadata for the media player has already been completed as part of #5984_ 
- [x] Ensure that the correct ATI metadata for the page is present as per requirements [#WSMEDIA-155 - ATI Page Load Tracking ](https://jira.dev.bbc.co.uk/browse/WSMEDIA-155)
 - [ ] Automated tests to ensure that ATI metadata is as expected. Determine whether this needs to be unit, integration or E2E test.

**Additional Information:**
https://paper.dropbox.com/doc/On-Demand-Audio-SEO-Metadata--AxvL5ADACVHXwYNBm7Ehjo~tAg-9ccFbhwazDB56TYzhSZVP#:uid=546747479559112509242594&h2=ATI-Analytics

**Comment by aeroplanejane** [comment]
Have requested that ARES change the contentType analytics label to player-episode. Raised as  ARES-1053. Expecting the change this week / next week.

**Comment by LilyL0u** [comment]
![Image 23-04-2020 at 16 37](https://user-images.githubusercontent.com/54575620/80119764-08e9bc80-8582-11ea-883e-5144ae1e17d5.jpg)
All variables present as outlined in the JIRA issue

**Comment by LilyL0u** [comment]
The final bullet point here is about automation testing, so shall I move it out of manual testing column if I have finished manually testing it @rebeccarfmcginnbbc ?

**Comment by karinathomasbbc** [comment]
> The final bullet point here is about automation testing, so shall I move it out of manual testing column if I have finished manually testing it @rebeccarfmcginnbbc ?

This will be handled by a PR which I have drafted - https://github.com/bbc/simorgh/pull/6006, which can't be merged until the SEO / Metadata work is complete (tests fail). So we could remove this from the list?

**Comment by LilyL0u** [comment]
> > The final bullet point here is about automation testing, so shall I move it out of manual testing column if I have finished manually testing it @rebeccarfmcginnbbc ?
> 
> This will be handled by a PR which I have drafted - #6006, which can't be merged until the SEO / Metadata work is complete (tests fail). So we could remove this from the list?

Cool I'll move it on
