### ISSUE TITLE
Simorgh will not render some valid VJ includes

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#6138]
**Describe the bug**
Some visual journalism includes do not start with `/include` as we previously believed, and can be any path e.g. `/news/special/2016/newsspec_14439/anchor.inc?anchor=Anchor3&responsive=true`

**To Reproduce**
Steps to reproduce the behaviour:

1. Checkout the include test harness branch: https://github.com/bbc/simorgh/tree/includes-test-harness
1. Run `npm run dev`
1. Vist http://localhost:7080/testInclude
1. Enter `/news/special/2016/newsspec_14439/anchor.inc?anchor=Anchor3&responsive=true` into the includes form and press submit
1. The include will not be rendered below the title of the test asset.

**Expected behaviour**
The include should be rendered below the title as a div with the id `Anchor`:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/9645462/78803477-f898e580-79b6-11ea-8e49-7e17d817a5a9.png">
(This probably has no practical use in Simorgh but apparently there are other includes that do not use the `/include` prefix that we will need)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**
- Update unit tests to match any logic added in.

- [x] This bug fix is expected to need manual testing.

**Additional context**
We can adjust the supported type logic here to treat all includes that do not start with `indepthtoolkit` or `idt2` as `vj` includes: https://github.com/bbc/simorgh/blob/7274f4f21f63e73e60ad1cc754c1d938c2026561/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js#L46..L65

Treat the following paths as VJ includes ('include', 'news/special', 'market-data', 'smallprox/include', 'edp').

**Comment by andrewscfc** [comment]
Blocked until https://github.com/bbc/simorgh-infrastructure/issues/949 is completed to allow includes with any path.

**Comment by FK78** [comment]
Can whoever picks this up add testing for multiple includes as well?

**Comment by FK78** [comment]
Can whoever picks this up add testing for multiple includes, possibly create a new issue for this to check what includes we expect to render more than once on a page.

**Comment by FK78** [comment]
| Include routes    | Rendering?         |
|-------------------|--------------------|
| news/special      | :white_check_mark: |
| market-data       | :white_check_mark: |
| smallprox/include | :x:                |
| edp               | :x:                |

**Comment by rhenshaw56** [comment]
> Include routes 	Rendering?
> news/special 	✅
> market-data 	✅
> smallprox/include 	❌
> edp 	❌

Thanks for testing these @FK78, for `edp` the response is an envelope format which we currently don't have support for extracting in simorgh and since we only have one of these I removed them from the supported types. for `smallprox/include` the url which we're testing with doesn't map to test.

**Comment by FK78** [comment]
> > Include routes 	Rendering?
> > news/special 	✅
> > market-data 	✅
> > smallprox/include 	❌
> > edp 	❌
> 
> Thanks for testing these @FK78, for `edp` the response is an envelope format which we currently don't have support for extracting in simorgh and since we only have one of these I removed them from the supported types. for `smallprox/include` the url which we're testing with doesn't map to test.

I believe @eagerterrier mentioned that we would not be supporting `edp` as its meant for elections, not world service.
