### ISSUE TITLE
Update MostRead component in StoryPage to use small font

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#6145]
**Is your feature request related to a problem? Please describe.**
Following implementation of https://github.com/bbc/psammead/issues/3320 we need to add props to opt into the smaller font for most read. This will decrease the font size to match our updated designs: see JIRA NEWSART-936.

**Describe the solution you'd like**
Add suitable props to MostRead in the StoryPage to use the smaller font.

**Describe alternatives you've considered**

**Testing notes**
- Update snapshots
- Visit a story page and check font matches zepellin designs
- UX check required

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by andrewscfc** [comment]
Blocked by https://github.com/bbc/psammead/issues/3320

**Comment by HarveyPeachey** [comment]
Closing as work was completed in https://github.com/bbc/simorgh/pull/6348
