### ISSUE TITLE
Japanese timestamps are in incorrect format on MAPs/Articles/PGLs/STYs

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6155]
**Describe the bug**
Japanese timestamps are in incorrect format on MAPs (Raised by editorial team)

This affects: 

- Japanese
- Korean
- UK China
- Zhongwen

This affects timestamps on these asset types: 

- CPS MAP: https://www.bbc.com/japanese/video-52227521
- Optimo Article: https://www.bbc.com/japanese/articles/cj4m7n5nrd8o
- CPS PGL: https://www.bbc.com/japanese/features-and-analysis-50914393
- CPS STY: (only on local, not yet audience-facing)
- This is *not* an issue for Story Promo timestamps on Front pages (www.bbc.com/japanese) or on related content on other pagetypes

Information on the source of this issue is in the `Additional context` section at the end of this description.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/japanese/video-52227521
2. Scroll down to timestamp
4. See timestamp as:
`9 四月 2020`

**Expected behaviour**
The correct time stamp should be 2020年4月9日 i.e. YYYY年MM月DD日

（年=year, 月=month, 日=day）

**Screenshots**
<img width="936" alt="Screenshot 2020-04-10 at 10 31 01" src="https://user-images.githubusercontent.com/3028997/78980731-6c053900-7b16-11ea-92c2-3f9b872bac1b.png">

Media Asset Page timestamp (using ArticleTimestamp component)
`3 十二月 2019`
<img width="130" alt="Screenshot Media Asset Page timestamp" src="https://user-images.githubusercontent.com/3028997/78981185-4d537200-7b17-11ea-9dba-6c5a54ebf017.png">

The same bug is found on Optimo articles (using ArticleTimestamp component)
`2 十二月 2019`
<img width="121" alt="Screenshot 2020-04-10 at 10 36 52" src="https://user-images.githubusercontent.com/3028997/78981183-4d537200-7b17-11ea-86bc-db42a199810c.png">

But not the front page (using StoryPromo)
https://www.bbc.com/japanese
<img width="130" alt="Screenshot front page" src="https://user-images.githubusercontent.com/3028997/78981186-4dec0880-7b17-11ea-8ec9-2b42ce163ce4.png">

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
We need to fix the format of the `ArticleTimestamp` component for Japanese, which is used for these pagetypes:

- Optimo Articles
- CPS Media Asset Pages
- CPS Photogalleries
- CPS Stories

Currently, we're using `D MMMM YYYY` for Article Timestamp for all services. See this file: https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleTimestamp/timeFormats.js#L5-L8

```
// 22 March 2019
export const formatDate = 'D MMMM YYYY';

// 22 March 2019, 17:05 BST
export const formatDateAndTime = 'D MMMM YYYY, HH:mm z';
````

For Japanese, we should be using:
`formatDate = 'LL';` , which maps to the correct `'YYYY年M月D日'`
`formatDateAndTime = 'LLL';`  which maps to `'YYYY年M月D日 HH:mm'`

Moment file for Japanese: https://github.com/moment/moment/blob/develop/src/locale/ja.js#L17

We should see if we can use LL/LLL for all other locales, too.

**Comment by sareh** [comment]
We should investigate whether we can change the locale for these to LL and LLL respectively, since that is correct for en-gb and ja. We should check this for all other locales. https://github.com/moment/moment/blob/develop/src/locale/en-gb.js#L17-L18
https://github.com/moment/moment/blob/develop/src/locale/ja.js#L17-L18

**Comment by LilyL0u** [comment]
@jroebu14 Japanese looks good. Will check the other exception services too.

**Comment by LilyL0u** [comment]
MAPs on the other exception services on test also look good
