### ISSUE TITLE
Inline links within a caption need UX evaluation 

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#616]
**Is your feature request related to a problem? Please describe.**
Currently the styles for the inline link render within a Caption have several bugs, please see screenshots.

**Screenshot 1**
![image](https://user-images.githubusercontent.com/7791726/45152041-d5e59000-b1c7-11e8-8558-1d32b7aa7926.png)
![image](https://user-images.githubusercontent.com/7791726/45151912-7dae8e00-b1c7-11e8-9fd9-9fef162aeef2.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/7791726/45151912-7dae8e00-b1c7-11e8-9fd9-9fef162aeef2.png)

**Describe the solution you'd like**
A developer should pair with UX to address the multiple issues eluded to below. 

Initial suggestions would be to remove the 2px padding top and bottom on the inline link. However if the padding is required by UX for touch areas we should change the line height of the Caption text to match the body copy. 

Screenshot 2 shows that descenders (letters that drop below the line, EG: g, y, p, j, etc) are also being cut off by the highlight background colour if the link spans multiple lines. It also shows that the border bottom is cut off if the link spans multiple lines

**Describe alternatives you've considered**
We could request UX to use text decoration underline instead of a border-bottom.

**Comment by erutht** [comment]
This is not relevant to inline linking in captions, but FYI, the [Jira issue about image captions](https://jira.dev.bbc.co.uk/browse/NEWSART-556) has been updated.

**Comment by greenc05** [comment]
We should ensure the inline links are still readable along with all content near the inline links when:
- The page is zoomed up to 200%
- When the browsers largest text size setting is used

**Comment by pjlee11** [comment]
Having paired with Natalie this not only an issue for the captions but an issue in the body copy also. Therefore I opened the issue ... to address this

**Comment by pjlee11** [comment]
All the issues/screenshots on https://github.com/BBC-News/simorgh/issues/828 are relevant to this issue also, however this is has additional complication that the line-height on the type specs for long primer to do clear the line above as they are too tight. The following screenshot shows this clearly:

![pasted_image_at_2018-10-19__5_03_pm](https://user-images.githubusercontent.com/7791726/47231741-b09e9100-d3c5-11e8-8724-38592849f0ef.png)

This said it if we are going to highlight a link in a caption using background-color we will need to increase the line-heights which would mean getting UX to confirm with GEL that they are happy with the change, which would likely require a review of the typography specs in regards to the new reith font.

**Comment by pjlee11** [comment]
Blocked awaiting UX decisions

**Comment by pjlee11** [comment]
Having spent time pairing with Natalie we've decided: 
- [padding top and bottom on the inline link should be removed](https://github.com/BBC-News/simorgh/issues/1055)
- UX need to talk to GEL about redefining the type specs as Reith and the current typography settings are not compatible
- The current border-bottom design may not be acceptable when it comes to multi-line links so we could:
    a) Use `text-decoration: underline` instead of `border-bottom` for inline link styling
    b) Experiment with `box-shadow` instead of `border-bottom` however we would also require a fallback, potentially text-decoration?
    c) Continue using `border-bottom` however we will need to change all the typography settings/groups  so that they render the border correctly for multi-line links

**Comment by sareh** [comment]
Closed since issue is now in Psammead: BBC-News/psammead#222
