### ISSUE TITLE
IE11 - AMP Img not working on Test & Live - AMP bug

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6183]
**Describe the bug**
AMP Img not working on Test & Live - AMP bug

e.g. https://www.bbc.com/hindi.amp
<img width="1240" alt="Screenshot 2020-04-15 at 10 57 11" src="https://user-images.githubusercontent.com/3028997/79324923-3a221700-7f08-11ea-9863-6b8592592440.png">

Issue to track: https://github.com/ampproject/amphtml/issues/27775

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any AMP page in IE11 https://www.bbc.com/hindi.amp
2. See images not loading

**Expected behaviour**
To have images working as expected

**Screenshots**
<img width="1240" alt="Screenshot 2020-04-15 at 10 57 11" src="https://user-images.githubusercontent.com/3028997/79325104-7c4b5880-7f08-11ea-988f-8b0425823cf3.png">

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser/version IE11

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
We will have to wait for the AMP team to fix the bug.

**Comment by sareh** [comment]
The AMP issue has been resolved: https://github.com/ampproject/amphtml/issues/27775

When visting https://www.bbc.com/mundo.amp using Browserstack with IE11, I can see the page working:

<img width="600" alt="Screenshot AMP page IE11 fixed" src="https://user-images.githubusercontent.com/3028997/80966790-18cc9080-8e0d-11ea-9a4e-e776ce6cf3b6.png">

**Comment by paruchurisilpa** [comment]
Looks good to me..
