### ISSUE TITLE
Logger warnings in console - Winston logger

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6195]
**Describe the bug**
When running `npm run dev` or `npm run build && npm run start` we have the following warning:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [File]. Use emitter.setMaxListeners() to increase limit
```

**To Reproduce**
Steps to reproduce the behaviour:

1. `npm run install && npm run dev`
2. In your terminal, see the error `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [File]. Use emitter.setMaxListeners() to increase limit`

**Expected behaviour**
No error

**Screenshots**
```
(node:21424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [File]. Use emitter.setMaxListeners() to increase limit
(node:21424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [File]. Use emitter.setMaxListeners() to increase limit
(node:21424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [File]. Use emitter.setMaxListeners() to increase limit
(node:21424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [File]. Use emitter.setMaxListeners() to increase limit
(node:21424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [File]. Use emitter.setMaxListeners() to increase limit
(node:21424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**Desktop (please complete the following information):**
- OS: Mac OS
- Browser - N/A
- Version - N/A

**Testing notes**
- [x] This bug fix is expected to need manual testing.
- run `npm run dev` and ensure that the warnings above are not displayed
- run `npm run build:local && npm run start` and ensure that the warnings above are not displayed

**Additional context**
This warning appears to be occurring due to Node streams having a default maximum number of 10 emitters on a single instance.  We currently have more than that in our application.

Looking at the Winston dependency, the class Stream sets the maximum value to `Infinity` here: https://github.com/winstonjs/winston/blob/aed30ab87437048c7fca43ff08055889fb92af6b/lib/winston/transports/stream.js#L36

However, in the Console and File class definitions (which we are directly using in our `logger.node` file), we can see that these are called [`this.setMaxListeners(30);`](https://github.com/winstonjs/winston/blob/ac502df17fb3fb598a8d24bedf7c7ec544b46c99/lib/winston/transports/console.js#L35) & [`this._stream.setMaxListeners(30);`](https://github.com/winstonjs/winston/blob/ac502df17fb3fb598a8d24bedf7c7ec544b46c99/lib/winston/transports/file.js#L51) respectively. 

The File class seems to be doing just fine, since `/log/app.log` does not have the warnings logged to it.

However, it is in the Console that we can see the errors. As we can see from the errors above, it is warning us about there being 11 listeners, implying that the maximum number is still set at 10.  
This may be due to the `setMaxListeners` not being called correctly in the Console class in the Winston dependency: 
I think this needs to be updated from [`this.setMaxListeners(30);`](https://github.com/winstonjs/winston/blob/ac502df17fb3fb598a8d24bedf7c7ec544b46c99/lib/winston/transports/console.js#L35).

It would be good to be able to set that Console max listeners value within [our application's `logger.node` file.](https://github.com/bbc/simorgh/blob/03a37a73ad7b3ae361ac183a50b3bcb04b3c39cb/src/app/lib/logger.node.js#L33-L38)

**Comment by itimirichard** [comment]
This appears to be an issue with the winston package as stated in the description. I have logged an issue on the winston repo [here](https://github.com/winstonjs/winston/issues/1791).

**Comment by joshcoventry** [comment]
We are using "winston": "^3.2.1" but the latest version is 3.3.3, so it may be worth seeing if bumping the version fixes this.

**Comment by joshcoventry** [comment]
We are now using 3.3.3 but the problem persists, I have added a comment to the issue relating to this bug in the winston repo.
