### ISSUE TITLE
Some legacy assets not matching against a route in Simorgh

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#6217]
**Describe the bug**
During our load test we noticed a number of urls were getting a 404 response from Simorgh. This is because of their format. The URLs that received a 404 response o not currently match the regex used for capturing legacy assets.

[Regex101 showing the current legacy asset regex does not match against 177 urls used in the loadtest](https://regex101.com/r/2vav2C/1)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'http://localhost:7080/ukchina/simp/elt/english_now/2015/09/150903_todays_phrase_as_quick_as_a_flash'
2. See the 404 error response
3. Observe the `route_info` log in the console (This shows that the request did not match a route and instead the error page was returned)

**Expected behaviour**
The url should return a 200 response from Simorgh (given valid fixture data)

**Screenshots**
![image](https://user-images.githubusercontent.com/14273378/79497377-798f5700-801f-11ea-9da8-586d83ed9067.png)

![image](https://user-images.githubusercontent.com/14273378/79497424-8f048100-801f-11ea-84b8-9a8b94563239.png)

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
Example URL that do not match the current legacy asset regex

```
/ukchina/simp/cool_britannia/life_in_uk/2016/08/160822_life_uk_oxford_gee_canteen
/ukchina/simp/elt/english_now/2014/06/140612_todays_phrase_turn_the_page
/ukchina/simp/sport/gossip/2015/05/150517_gossip
```

**Comment by paruchurisilpa** [comment]
This doesn't need manual testing and have automated tests covered. Spoke to Chris and he mentioned that this may be replaced by another one with a different approach this afternoon.So moving straight to Done.
