### ISSUE TITLE
Visually displayed copyright text requires lang attribute

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#623]
**Is your feature request related to a problem? Please describe.**
The visually displayed copyright text is always in English 

**Describe the solution you'd like**
* On non-English articles we should add a `lang` attribute to the visually displayed copyright text so this can be announced by screen readers with the correct accent. This should not be applied to the visually hidden text 'Image source, '.
* In Persian we expect the copyright span to be right aligned.

Arises from https://github.com/bbc/simorgh/pull/618

**Testing notes**
English News article example: http://localhost:7080/news/articles/cn7769kpk9mo
Persian article example: http://localhost:7080/persian/articles/cyddjz5058wo

* Screen reader - test both the visually hidden text such as: 'Image source, ' and the visually displayed copyright text such as 'Getty images' are read with the correct accents - Make sure to check that this works ok with `role="text"`
* Check to make sure that the visually hidden text 'Image source, ' (translated) is read with a Farsi accent on `Persian`
* Check to make sure that the visually displayed copyright text such as 'Getty images' is read with an English accent on `Persian`

Dev insight: We should have unit tests for the changes.

**Comment by dr3** [comment]
@sareh Is this ws-frontpage-stream? our images dont have copyright on them

**Comment by sareh** [comment]
@dr3 Thanks. Have re-assigned.

**Comment by pjlee11** [comment]
@sareh Currently all copyright is produced in English across all the services. @jimjohnsonrollings could confirm, my understanding is that in the short/medium term editorial will continue using only English content in the copyright field

**Comment by sareh** [comment]
@pjlee11 Drew meant that images on *front pages* don't have copyright on them, but that Articles for all services do.

**Comment by jimjohnsonrollings** [comment]
I agree with everyone

**Comment by pjlee11** [comment]
@greenc05 could you confirm the edits you've made to the test notes in the issue description? 
This issue is purely about adding a `lang` attribute to only the `copyright` because in the current state of Optimo the value will always be english due to Optimo not yet supporting non-latin copyrights in their image workflow. 

If there are other changes relating to the image needed on top of adding lang to the copyright they should be opened as a new issue as we are aiming for small, single change issues. Also with our development workflow and approach to refinement if new requirements are added to a ticket then the issue should be refined again. 

`Make sure to check that this works ok with role="text"` - my understanding is this testing was carried out as part of adding the `role="text"` functionality, is it necessary to be re-testing it?
`Check to make sure that nothing has changed on UK News.` - could you clarify what is meant by this?

**Comment by greenc05** [comment]
@pjlee11 we are only adding a lang attribute to the visually displayed copyright text here.

 'Check to make sure that nothing has changed on UK News.' - I've no idea what that means, it was already there... Just removed it.

'Make sure to check that this works ok with role="text" - my understanding is this testing was carried out as part of adding the role="text" functionality, is it necessary to be re-testing it?' Yes this is necessary as it will inherit - We should check that there is no adverse effects and that lang attributes work ok with role text.

**Comment by sareh** [comment]
For clarification, here are example outputs. 

A service that is not in British English, eg. Persian:

```
<html lang="fa">
........ 
     <Copyright lang="en-GB">
        <VisuallyHiddenText lang="fa">، منبع تصویر</VisuallyHiddenText>
     Getty Images
     </Copyright>
...... 
</html>

```

A service in British English, eg. News. 

```
<html lang="en-GB">
........ 
     <Copyright>
        <VisuallyHiddenText>Image source, </VisuallyHiddenText>
     Getty Images
     </Copyright>
...... 
</html>

```
