### ISSUE TITLE
On Demand Radio Brand AMP Validator tests

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6241]
Run automated AMP Validator tests for a sample on demand radio page:

https://github.com/bbc/simorgh/blob/74221208cd41fc4f6c63aa1ecbec0b75a2794f92/package.json#L7

_Note - The results of these tests will not completely validate the page until the OD-radio episode Image PR has been merged https://github.com/bbc/simorgh/pull/6471_

**Comment by pharingee** [comment]
The amp validator passes but we probably need to make the test more maintainable.

**Comment by karinathomasbbc** [comment]
Agreed - sounds like a discussion to have in an amigos session :)
