### ISSUE TITLE
Rendering empty paragraphs <p></p>

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6250]
**Describe the bug**
For Optimo articles, we currently render empty paragraphs - we should not be doing that. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/kyrgyz/articles/c9zgn5451jno
2. See paragraphs that are empty
<img width="940" alt="Screenshot paragraphs that are empty" src="https://user-images.githubusercontent.com/3028997/79766747-4cdd8700-8320-11ea-88b7-b12ace7447c2.png">

**Expected behaviour**
We should not render empty paragraphs

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 80.0

**Smartphone (please complete the following information):**

**Testing notes**
We can add unit tests to ensure this is fixed and remains fixed

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
This is not a Simorgh bug, this needs to be fixed from Optimo's side as they should not be sending us empty paragraphs.
