### ISSUE TITLE
Replace ramda path/pathOr with optional-chaining

### ISSUE THREAD

**Issue by mmcculloch** [bbc/simorgh#6258]
**Describe the solution you'd like**
The `ramda/src/path` &  `ramda/src/pathOr` functions are used to get data from nested objects without the chances of an error being thrown if a parent object is undefined/null. The functions are used extensively (around 47 places for path and 51 for pathOr) since we lacked a native solution to this problem.

New native syntax called `optional-chaining` has been added to the language and is now in final phase, with popular toolchains such as `create-react-app` now using it.

This task is to add https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining to our babel config and replace `rambda/src/path` & `ramda/src/pathOr` usage.

**Example**

_Ramda_
```js
const home = path(['home'], translations);
const groups = path(['content', 'groups'], frontPageData);

const headlineText = pathOr(null, ['promo', 'headlines', 'headline'], json);
```

_Optional Chaining_
```js
#path 
const home = translations?.home;
const groups = frontPageData?.content?.groups;
# pathOr
const headlineText = json?.promo?.headlines?.headline || null;
```

**Advantages**
- This is native syntax designed to solve this issue
- Bundle size will likely increase slightly until path & pathOr are removed and then return to normal
- Not all keys need to be optional `frontPageData?.content.groups;` <- In this case it is assumed if `content` exists then the `groups` key is not optional.

**Investigation**
PR that tests this package: https://github.com/bbc/simorgh/issues/6258

**Bundle Size**
Since the plugin [@babel/plugin-proposal-optional-chaining](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining) is a transform there is no immediate increase to bundle size, but instead the code written is transformed, for example:

Before
```js
const test = myObject.test?.test2
const tes2 = myObject?.test?.test3
const test3 = myObject.test?.test2
```

After
```js
const test = (_myObject$test = myObject.test) === null || _myObject$test === void 0 ? void 0 : _myObject$test.test2;
const tes2 = myObject === null || myObject === void 0 ? void 0 : (_myObject$test2 = myObject.test) === null || _myObject$test2 === void 0 ? void 0 : _myObject$test2.test3;
const test3 = (_myObject$test3 = myObject.test) === null || _myObject$test3 === void 0 ? void 0 : _myObject$test3.test2;
```

This is larger than the written code but should gzip quite well. Once path and pathOr are removed the bundle size should decrease by about 3KB. I recommend a slow transition away from path & pathOr rather than trying to do them in one go as mistakes could be made.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Comment by chris-hinds** [comment]
before we just dive into doing this work, can we check what the bundle size would be after adding the required babel plugin?

**Comment by mmcculloch** [comment]
> before we just dive into doing this work, can we check what the bundle size would be after adding the required babel plugin?

I can have a look during learning day on Friday, I'm not currently sure if the bundle will go up, down or stay the same.

**Comment by simonsinclair** [comment]
Thanks, @mmcculloch - feel free to assign yourself to this if you get around to looking at it and want to take it further.

**Comment by mmcculloch** [comment]
@hindsc52 @simonsinclair Added some notes from my investigation into bundle size. To sum up I believe because it's a transform it'll result in a slight increase that will be mitigated by gzip and then return to normal once the path & pathOr packages are removed.

**Comment by DarioR01** [comment]
After a short survey to all software engineers we decided that optional chaining is not beneficial enough to refactor the entire code. The main point being that Ramda paths can be used for majority of our use cases, whereas optional-chaning is not. Meaning that even implementing it would mean a mix use of Ramda path and optional chaining across our components. In conclusion we prefer to use a single uniform method instead of a mixture of methods.
