### ISSUE TITLE
Afrique, Arabic, Hausa, Korean, Pashto, Persian, Somali, Swahili review

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#6259]
**Is your feature request related to a problem? Please describe.**
Before we release the final 8 front pages on Thursday, we should check that all of the config values are correct.

**Describe the solution you'd like**
For the following services:

- afrique https://github.com/bbc/simorgh/issues/6259#issuecomment-617333475
- arabic https://github.com/bbc/simorgh/issues/6259#issuecomment-617341736
- hausa https://github.com/bbc/simorgh/issues/6259#issuecomment-617350486
- korean https://github.com/bbc/simorgh/issues/6259#issuecomment-617361997
- pashto https://github.com/bbc/simorgh/issues/6259#issuecomment-617215168
- persian https://github.com/bbc/simorgh/issues/6259#issuecomment-617113458
- somali https://github.com/bbc/simorgh/issues/6259#issuecomment-617179381
- swahili https://github.com/bbc/simorgh/issues/6259#issuecomment-617095518

We need to check the following values:

Navigation links - do they all go to the correct, valid URL?
Chartbeat config - does this match what is in PAL?
ATI config - does this match what is in PAL?

(To check Chartbeat and ATI config in PAL, you can look in the network tab on the currently live PAL page - filtering for a1.api should give you the ATI calls, and filtering for ping.chartbeat the Chartbeat ones. For ATI, you’re looking for the s2 value)

Cookies translations - do these match what is on the translation spreadsheet?
Skip to Content link - is this correctly translated and function as expected?
Trust Project Link - does this go to the correct, valid URL?
Footer Links - do these all go to the correct, valid URL?
Translations - do all translations for the service match what is written in the translations spreadsheet? We should check the service config as well as markup of the page to ensure we have translations for all offscreen text as well as on screen text.

Please leave a comment below if you are looking at a service so somebody else does not repeat the effort. Please paste the above list below with either a ✅ if this is correct for the service, or outline what needs to be updated, and raise a PR with the updates required - there is an example comment below.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Example for a reviewed service:

**Service Name**
Navigation links ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link✅
Trust Project Link ✅
Footer Links ✅
Translations ✅

**Comment by benjifellows** [comment]
**Swahili**
Navigation links ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link ✅
Trust Project Link ✅
Footer Links ✅
Translations ✅

**Comment by EinsteinNjoroge** [comment]
**Persian**
Navigation links ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link ✅
Trust Project Link ✅
Footer Links ✅
Translations ✅

**Comment by benjifellows** [comment]
**Somali**
Navigation links ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link ✅
Trust Project Link ✅
Footer Links ✅
Translations 
Translation Sheet: Sababta aad ku aamini kartid BBC News 
Site: Sababta aada ku aamini kartid BBC News - Fixed

**Comment by amywalkerdev** [comment]
> Translations: should we have translations for this link on the footer?

Nope the AdChoices / Do Not Sell My Info should always be in English :)

**Comment by benjifellows** [comment]
**Pashto** 
Navigation links  ✅
Chartbeat config  ✅
ATI config  ✅
Cookies translations  ✅
Skip to Content link  ✅
Trust Project Link  ✅
Footer Links  ✅
Translations https://github.com/bbc/simorgh/pull/6270/files

**Comment by tochwill** [comment]
**Afrique**
Navigation links ✅
Chartbeat config  ✅
ATI config ✅
Cookies translations  ✅
Skip to Content link  ✅
Trust Project Link  ✅
Footer Links  ✅- all links go to valid pages - where can I check these links are definitely the correct ones?
Translations ✅

There is an image missing at the bottom in the 'Ecoutez BBC Afrique' section. Does an image need adding here?

**Comment by tochwill** [comment]
**Arabic**
Navigation links  ✅
Chartbeat config ✅
ATI config ✅
Cookies translations - privacy banner translations appear to have changed (الكوكيز) to 'Cookies' in english. Cookie banner translations also need updating.
Skip to Content link  ✅
Trust Project Link ✅
Footer Links ✅- all links go to valid pages - where can I check these links are definitely the correct ones?

Translations:

- Cookie banner: Top two translations need updating. Weird brackets on linkText. Weird ordering on full stops etc. Will check this today
- Comma on ‘caption’ on the wrong side? externalLinkText too. The same for the following?
    - imageCaptionOffscreenText: 'التعليق على الصورة، ',
    -  videoCaptionOffscreenText: 'التعليق على الفيديو، ',
    - audioCaptionOffscreenText: 'التعليق على التسجيل الصوتي، ',
    - defaultCaptionOffscreenText: 'التعليق، ‘,
    - imageCopyrightOffscreenText: 'صدر الصورة، ',
    - 'ملفات الارتباط Cookies', - Cookies link, is cookies on the wrong end of the text?
I think my editor might be messing with these?

Jim has confirmed that these are correct.

**Comment by tochwill** [comment]
**Hausa**
Navigation links ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link ✅
Trust Project Link ✅
Footer Links ✅- all links go to valid pages - where can I check these links are definitely the correct ones?
Translations https://github.com/bbc/simorgh/pull/6270/files - fixed  ✅

**Comment by tochwill** [comment]
**Korean**
Navigation links  ✅
Chartbeat config ✅
ATI config ✅
Cookies translations ✅
Skip to Content link ✅
Trust Project Link ✅
Footer Links ✅- all links go to valid pages - where can I check these links are definitely the correct ones?
Translations ✅
