### ISSUE TITLE
Schema.org Thing types needs updating because of Ares changes and there's a teeny bug

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#6278]
**Describe the bug**
There's a bug in our handling of Thing types in schema.org, where if a Thing has multiple types we always call it a 'Thing', even if only one of the types is one we accept.

Ares (in v2) have also changed how they return the Thing Types, which means:
* We will receive the Thing types in the form of an ontology identifier, followed by a colon, followed by the type (e.g. `core:Person`) rather than just the type (e.g. `Person`).
* The acceptableTypes therefore become: `core:Person`, `core:Event`, `core:Place`, `core:Organisation`
* However we need to render them out without the `core:` prefix

**To Reproduce**
Steps to reproduce the behaviour of the bug (assumes the second part of the above already changed):

1. Go to /kyrgyz/articles/c2vxxr2zrrko
2. Look in the Ares data
3. See the code `thingType": ["core:Place","core:Thing"]`
4. Look at the schema.org markup in the rendered page
5. See the code `{"@type":"Thing","name":"Орусия"}`

**Expected behaviour**
The `@type` in the schema.org should in this case be `Place`.

Source of bug: https://github.com/bbc/simorgh/blob/latest/src/app/containers/LinkedData/getAboutTagsContent.js

```
const checkType = types => {
  const acceptableTypes = ['Person', 'Event', 'Organization', 'Place'];
  if (types.length === 0 || types.length > 1) {
    return 'Thing';
  }
  return acceptableTypes.includes(types[0]) ? types[0] : 'Thing';
};
```

The existing logic says that if there are no types in the data, then use `Thing` - this is correct.

However it also says if there are more than one type in the data, then to always use `Thing` - this is slightly wrong.  The logic should be that if there are more than one type _out of those which are in acceptable types_ then to use Thing.

This will almost always return `Thing` as written, as the acceptableTypes are all subtypes of Thing, so will always return in the data with both Thing and the other type (i.e. more than one type).

So the correct logic should be:
* If there are no types use `Thing`
* If any one of the types `['core:Person', 'core:Event', 'core:Organization', 'core:Place']` are present, then use that type, but without the `core:` prefix
* If more than one of the types `['core:Person', 'core:Event', 'core:Organization', 'core:Place']` are present, then use `Thing`

***Scenarios***
Given the types from Ares are `["core:Place","core:Thing","tagging:TagConcept"]`
Then I expect Simorgh to output `Place`

Given the types from Ares are `["core:Place","core:Thing","core:Person","tagging:TagConcept"]`
Then I expect Simorgh to output `Thing`

Given the types from Ares are `["core:Thing","tagging:TagConcept"]`
Then I expect Simorgh to output `Thing`

Given there are no types from Ares
Then I expect Simorgh to output `Thing`

**Testing notes**
- Page validated using [Google Structured Testing Tool](https://search.google.com/structured-data/testing-tool/u/0)
- Cover scenarios mentioned above in unit tests.
- Link up with Gerald about his testing tool.

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by jimjohnsonrollings** [comment]
I've applied the blocked label on the basis that there's an Ares bug which means we aren't getting the relevant fields from them in the right format anyway

**Comment by jimjohnsonrollings** [comment]
Unblocked as we've agreed that the format Ares now returns the values in is the one we will use going forward.

**Comment by ghost** [comment]
Hey @jimjohnsonrollings I couldn't find `{"@type":"Thing","name":"Russia"}` is there something am missing?

**Comment by jimjohnsonrollings** [comment]
@sadickisaac Aha - that's because the migration to Ares v2 has changed them into Kyrgyz instead of English so it now says `{"@type":"Thing","name":"Орусия"}`.  I'll update the description.
