### ISSUE TITLE
Display the category label

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#628]
**Is your feature request related to a problem? Please describe.**
As part of the [Trust Project](https://www.thetrustproject.org/) we need to show which category the article is part of.

**Describe the solution you'd like**
We need to add logic to transform the category label we get from the CMS (found in `metadata.passport.category`) into a user-facing label.

Note that this logic will vary in the future by home and language so this needs to be built with that in mind.

UX:
- font: Reith Sans Bold
- size (type): Minion
- colour: `#404040` (Storm)
- text transformation: all uppercase
- padding-top: 0
- padding-bottom: 16px
- a11y:
    - Mark up should have no semantic meaning (div/span)
    - landmark region is "main"
    - the category label is read out
    - Test when reading the content out all in one go with VoiceOver iPhone/Safari (2 finger swipe down), that there is a pause between this element and the next e.g. the time stamp

**Describe alternatives you've considered**
We've considered having this information come from an upstream service, where the mapping between the CMS category identifier and the user-facing label would be performed. For now we decided it's faster to do this in our application.

**Additional context**
Design: 
![image](https://user-images.githubusercontent.com/2587947/45223232-9a71c100-b2ae-11e8-993b-592cefa937ae.png)

**Testing notes**
TBD

**Comment by sareh** [comment]
Blocked until Optimo implement this feature.

**Comment by jamesbhobbs** [comment]
Closing as impossible to do, should be done in psammead first anyway
