### ISSUE TITLE
Address requestAnimationFrame Polyfill warning

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#63]
**Describe the bug**
When we run the Jest tests, `npm run test:unit` we get this warning
```
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills
```

**To Reproduce**
1. `npm run test:unit`
2. Type `a` and click enter to run all tests
3. See error

**Expected behavior**
No error

**Additional context**

**Comment by jamesbhobbs** [comment]
This is no longer true, could only be steps for reproduction of error are out of date, but closing as I can reproduce anyhow.
