### ISSUE TITLE
Live e2es regularly failing on SIGSEGV

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#6301]
**Describe the bug**
Since we upgraded to Cypress 4.4.0 in https://github.com/bbc/simorgh/pull/5976 anywhere between 70-80% of our live e2e tests are failing on CodeBuild with the error:
```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
```

**Testing notes**
- [ ] This bug fix is not expected to need manual testing.

**Additional context**
Cypress was subsequently updated to 4.4.1 in https://github.com/bbc/simorgh/pull/6251

This bug has been raised with the Cypress maintainers in https://github.com/cypress-io/cypress/issues/7048

**Comment by jamesdonoh** [comment]
A few people have added comments to the Cypress issue so we aren't entirely alone, still no response from the maintainers though.

There could be mileage in trying a different browser in a few experimental CodeBuild runs. Cypress uses [headless Electron by default](https://docs.cypress.io/guides/guides/launching-browsers.html#Electron-Browser) but can be made to use both Chrome or Chrome via command-line switches, though these would need to be installed separately. This might not be a sustainable solution but might at least allow us to feed back more info to the maintainers.

**Comment by mykeels** [comment]
CodeBuild Logs: https://bpaste.net/564Q

**Comment by mykeels** [comment]
This comment looks promising. https://github.com/cypress-io/cypress/issues/6184#issuecomment-576442882

**Comment by karinathomasbbc** [comment]
Given the recent improvements to the E2Es (reduced the runtime to under an hour), and Cypress upgrades, we are no longer seeing this issue, so I believe we can close this issue 🥳
