### ISSUE TITLE
Investigate adding a Circuit Breaker

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#632]
**Is your feature request related to a problem? Please describe.**
When our APIs (e.g. AReS) fail, we should avoid making repeated requests to those systems to allow them to recover. 

We can use the [Circuit Breaker pattern](https://www.martinfowler.com/bliki/CircuitBreaker.html), with a suitable implementation for us.

**Describe the solution you'd like**
Propose two or more solutions to implement a Circuit Breaker in Simorgh, state which solution is preffered and arguments for it.

**Describe alternatives you've considered**
We will complement the Circuit Breaker with a kill-switch in our application, pending investigation.

**Comment by bcmn** [comment]
Based on the talk of circuit breaking specifically, I initially focused on looking into [opossum](https://github.com/bucharest-gold/opossum) & [brakes](https://github.com/awolden/brakes/), as Opossum seemed to be the best of those I found for keeping their dependencies up to date & doing similar maintenance, & Brakes seemed the only one to be doing more ambitious things with replacing functions with a third-party promises library, [Bluebird](http://bluebirdjs.com). However, I'm not sure how much the project would benefit from Bluebird -- specifically, whether the team's usage would even trigger it, & whether it'd be simply premature/unnecessary optimisation in the first place. Opossum seems to have the most flexible hooks for triggering additional behaviour based on state change, which may prove useful, not least for simply understanding & communicating the behaviour.

It wasn't clear from the issue, but after conversations with Bogdan it sounds like he was keen on an exponential backoff solution. Neither of the above uses this pattern — Opossum instead [uses a "half-open" state in which only the first attempt once in the state is let through the circuit breaker](https://github.com/bucharest-gold/opossum/blob/master/README.md#fallback) (it appears Brakes is a lot more naive in this regard). 

Of libraries which use the exponential backoff model, [async-retry](https://github.com/zeit/async-retry) seems to have wide usage already, & was easy to use in the app.

I’m unclear as to whether there’s more nuanced preferences that should be taken into account — I did a quick implementation of all three of these libraries in the app, & would generally favour Opossum or async-retry. At that point, it depends on which model of retrying we want to go for. The half-open, circuit breaker model only really makes sense if we expect to have multiple sources within the app using a single point of access for the same/similar operations. As far as I'm aware right now, this doesn't seem like the way we'll be utilising it -- but I'm not clear whether we want to treat _any & all_ requests to the data API with the same circuit breaker?

**Comment by jackpopp** [comment]
Hey, I stumbled across this issue and wanted to point out there is a pan BBC node http client that already implements the circuit breaker pattern that can be found here: https://github.com/bbc/flashheart specifically https://github.com/bbc/flashheart#circuit-breaker

**Comment by craigkj** [comment]
Additionally to the above, there is https://github.com/bbc/id-http-client which is a wrapper around the utility lib https://github.com/bbc/bbc-http-client-node. This one also contains a metrics client and logging wrapper as well as a 'brakes' circuit breaker. 

I would suggest using https://github.com/bbc/bbc-http-client-node for http requests regardless, and then either flashheart or the id-http-client if you need the extras. Both are open to PRs and this is the kind of thing we should not be rebuilding multiple times.

**Comment by jamesdonoh** [comment]
Looking again at this, we need an implementation that would work for both server-side and client-side requests, unless I'm mistaken that rules out anything based on `bbc-http-client-node` and anything that couldn't/shouldn't be webpack'ed.

Going to close as the investigation was done and start a new ticket to implement this.
