### ISSUE TITLE
Investigate feasibility of enabling CSR for selected CPS types

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#6322]
**Is your feature request related to a problem? Please describe.**
We want to know whether it is feasible to enable client-side rendering (CSR) of only some CPS content using `react-router` links depending on the asset type. Specifically, can we enable react-router links for MAPs only?

The related content blocks in the CPS data includes the asset type. Also the front page groups used to populate the secondary column on STYs/PGLs should have the type present. It might also be possible simply by looking at the path structure.

https://github.com/bbc/simorgh/blob/latest/src/app/routes/index.js

Talk to ws-media when picking up this ticket.

**Describe the solution you'd like**
- Look into whether this can be done via either or both of the following (investigate both):
  - Using the asset type in the source data
  - Using any patterns in the URL/path structure
- Identify obstacles/limitations and describe what would need to be done to overcome them
  - e.g. will this work for Most Read links?
- Timebox investigation to 2 days

Expected Outcome:

Dropbox paper or a PR with explanatory comments.

**Comment by mykeels** [comment]
Inline links in the content blocks are in the following format:

```json
{
  "name": "",
  "uri": "",
  "type": "link"
}
```

**Comment by joshcoventry** [comment]
Won't do.
