### ISSUE TITLE
Batch 1 For Ares V2 Migration

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6324]
**Is your feature request related to a problem? Please describe.**
In this PR: https://github.com/bbc/simorgh/pull/6294/files?file-filters%5B%5D=.js#diff-3b008fba57fe9eb2546a7ae54d193807R22

**Live release of Batch 1**

This batch includes optimo articles, liveradio, on-demand radio, radio schedules.

There are two sets of updates needed for this batch - Mozart changes (for the Page data) and 
Morph changes (for the Embed endpoints for media on Optimo articles and Live Radio / On Demand Radio pages)

Test this page: https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo
Page & relevant AV embed endpoint examples:
Live radio
https://www.test.bbc.com/persian/bbc_persian_radio/liveradio
https://polling.test.bbc.co.uk/ws/av-embeds/media/bbc_persian_radio/liveradio/fa?morph_env=live
Optimo articles
https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo
https://polling.test.bbc.co.uk/ws/av-embeds/articles/c3wmq4d1y3wo/p01k6msp/en-GB
On demand radio (not yet audience facing)
https://www.test.bbc.com/pashto/bbc_pashto_radio/w3ct0n6m
https://polling.test.bbc.co.uk/ws/av-embeds/media/pashto/bbc_pashto_radio/w3ct0n6m/ps?morph_env=live
Radio schedules (on front pages)
https://www.test.bbc.com/afrique?renderer_env=live
Note that liveradio and on demand radio pages are always going to use the live av emdeds data
After we have completed the outstanding tasks listed above, we can:
Merge these two Mozart PRs (automatically goes to Test)
https://github.com/bbc/mozart-assembler/pull/331/files
https://github.com/bbc/mozart-routing/pull/1291

Note the date of the next Mozart Routing deployment (Tuesday or Thursday)
Live release for Morph endpoints via the Mozart Page Configs should be coordinated with the Mozart Routing Live release, which should happen on Tuesday or Thursday this week, depending on when the above changes are made.

Have comms with Ares about the go-live date/time for Ares V2 for these pages.

**Describe the solution you'd like**

**Describe alternatives you've considered**
N/A

**Testing notes**
A regression check for Optimo
 - specifically checking playback of media
- ATI reporting of statsObject and lang/locale values

Dev insight: 

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
**Testing notes**
Live radio Morph Module changes have been on Test for a week.

For radio schedules, Jane has checked the JSON payload between V1 & V2 for Radio schedules. There is no more page-level testing we can do on Test - since we only have data on live. We will go live and monitor there.

Only the Optimo pages need testing manually: 
- A/V on any Test Optimo articles we have, e.g. https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo.amp

A regression check for Optimo
 - specifically checking playback of media
 - ATI reporting of statsObject and lang/locale values

**Plan for tomorrow morning (Thursday 28th April)**
- Manual deployment of mozart page configs Optimo/LiveRadio/OnDemandRadio up to live, with the Ares V2 embed endpoint changes (https://github.com/bbc/mozart-page-configs/pull/1402)
- Live release of Mozart Assembler and Routing, with the Ares v2 changes for the page.

**Comment by paruchurisilpa** [comment]
Looks good to me...

**Comment by sareh** [comment]
Closed as completed.
