### ISSUE TITLE
Opera mini extreme mode text spacing issue

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#6325]
**Describe the bug**
In opera mini extreme mode when the thai frontpage is visited there seems to be irregular spacing between the text and the numerals.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'http://localhost:7080/thai'
2. See the error

**Expected behaviour**

**Screenshots**
![Opera_mini_issue](https://user-images.githubusercontent.com/9802855/80393786-e240c400-88a8-11ea-8907-153a5dd57b07.jpeg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Won't fix. Closing
