### ISSUE TITLE
[WS Stories] Add Mozart smoke tests for STY assets

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#6349]
**Is your feature request related to a problem? Please describe.**
To help with testing we should ensure we have Mozart smoke tests running against STY assets on test and live.

**Describe the solution you'd like**
- Select a live STY asset for each service that goes live and add a mozart smoke test for that asset.
- Extend the current smoke tests to include live assets
- This PR should be merged shortly after the live release.

**Describe alternatives you've considered**
We have no alternatives!

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ghost** [comment]
@hindsc52 where do I find the list of live STY pages for all services?
