### ISSUE TITLE
[WS Stories] Ensure VJ and IDT Includes do not render on AMP

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#6350]
**Is your feature request related to a problem? Please describe.**
As of right now includes do not yet work on AMP pages and we have decided that this is not required for the MVP launch of STY's on Simorgh.

**Describe the solution you'd like**
Using the Platform value from the request context ensure that nothing is rendered within the include container when on AMP.

If on AMP return `null` in the container.

**Describe alternatives you've considered**
Rendering of potentially broken includes on AMP

**Testing notes**
Add a unit test to cover when the container returns null.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [X] This feature is expected to need manual testing.

**Additional context**

**Comment by ghost** [comment]
@hindsc52 Do we have other types on includes that would render on amp?

**Comment by chris-hinds** [comment]
> @hindsc52 Do we have other types on includes that would render on amp?

@sadickisaac we just have the one include container, so as long as that container returns `null` that should cover all cases
