### ISSUE TITLE
Share tools - per service or per locale

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#638]
**Is your feature request related to a problem? Please describe.**
Consider the order of share tools for each article. We can implement them taking two different approaches:
1) A set order of social sharing services that are listed *per service*. e.g. for `/news`, `/persian`.
2) A set order of social sharing *per user locale*

**Describe the solution you'd like**
As a result of this investigation, we need to have an understanding of the pros and cons of these approaches. We should write issues for implementing the recommended implementation.

**Comment by ChrisBAshton** [comment]
We're no longer doing sharetools in the foreseeable future.
