### ISSUE TITLE
[Tech Debt] Replace waitFor(() => {}) with act()

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#6384]
**Is your feature request related to a problem? Please describe.**
Some tests in our code base are using `waitFor(() => {})` with an empty callback which is considered bad practice.

Removing the wait() from these tests reveals warnings/errors where we should be using `act()` to ensure updates to the toggles and MostRead containers are handled correctly, `waitFor()` was masking these warnings.

```
Warning: An update to CanonicalMostRead inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
```

**Describe the solution you'd like**
Replace any use of waitFor(() => {}) that has an empty callback with act() https://reactjs.org/docs/test-utils.html#act

And ensure the test continue to pass successfully, this time without any warnings.

**Describe alternatives you've considered**
N/A

**Testing notes**
Unit tests should all pass.

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by mykeels** [comment]
Should this be closed now that the PR is merged?

**Comment by chris-hinds** [comment]
@mykeels this is a new issue that arose from the previously merged PR.
