### ISSUE TITLE
Improve how we visualise pagemon dashboards

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6400]
Investigate stripping back the number of tests visualised on Pagemon dashboard to make debugging issues easier _"in the heat of battle"_ - one of each 'type' (i.e. one per endpoint, one per page type, canonical/amp - details TBD).

Consider:

- Can tests for every page still run, but can we only visualise one per-type?

- Or, are we able to 'roll up' tests for all pages - so visually only one is represented, but it can easily be expanded to become more granular. 

https://paper.dropbox.com/doc/Simorgh-Alerting-Monitoring--AyaAixGZZTqB6JLwz~xbBREJAg-9Gw0fPgUCYpqF2fv2IiUC#:uid=965078369373147428852147&h2=PageMon

**Comment by gavinspence** [comment]
Closing this as no longer needed
