### ISSUE TITLE
Mozart ARES v2 follow up tech debt

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6403]
Fixed by: https://github.com/bbc/mozart-routing/pull/1448
& https://github.com/bbc/mozart-routing/pull/1456

Pending script-switch endpoint Mozart changes being merged: Refactor OD & live radio payload & route to match Belfrage-friendly approach and inherit variables from ws_base.rb.

- [x] ~~Media payloads should be renamed to live radio~~ No longer relevant - these payloads are now renamed and shared between various pages
- [x] Payload spec and route spec should not test the same things twice. Move specs testing route params into the route spec.
- [x] ~~Create ws_endpoint_base that our endpoints inherit from, to decouple their inheritance chain from ws/front_page & ws/languages~~ Fixed by https://github.com/bbc/mozart-routing/pull/1448
- [x] ~~Implement 404/500 consts https://bbcnews.slack.com/archives/CHCGL8UP4/p1586338995424200?thread_ts=1586335924.417700&cid=CHCGL8UP4~~ Fixed by https://github.com/bbc/mozart-routing/pull/1448

**Comment by RichardPK** [comment]
A few of these are fixed by https://github.com/bbc/mozart-routing/pull/1448

**Comment by RichardPK** [comment]
Done
