### ISSUE TITLE
Update the x5 and x6 values for ATI _again_

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#6404]
**Is your feature request related to a problem? Please describe.**
Data used from the x5 and x6 fields in ATI is coming out malformed for end-users of the ATI data.  This appears to be due to a complexity in how ATI handles this data, which necessitates us sending the data in a particular way.

**Describe the solution you'd like**
Previously, ATI advised that we needed to URL encode the values of the x5 and x6 fields before wrapping them in square brackets.

The new advice is to URL encode the values of the x5 and x6 fields, then URL encode them _again_, before wrapping the result in square brackets.

NB. Other uses of these values need to remain as they are, e.g. Chartbeat = not encoded at all, and the ATI `ref` field (when implemented in #6351 ) = only encoded once.

**Describe alternatives you've considered**
N/A

**Testing notes**
Update unit tests to ensure that the correct levels of encoding are being used for each analytics implementation.

Ensure that the correct values are being sent with the request.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
confirmation with Jim: It should be okay to encode it once on AMP and double encode on canonical.

**Comment by thekp** [comment]
re-opening issue as I have reverted the PR that initially resolved it: https://github.com/bbc/simorgh/pull/6728
