### ISSUE TITLE
TC2 Map with Audio not playing

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6407]
- Bug: Issue with Legacy assets with audio - SMP on Chrome Version 81.0.4044.129 (latest) 
    - https://www.bbc.com/somali/war/2011/10/111005_business (note this works in Firefox)

        - Ares V1 and V2: 
            https://ares-admin-tool.api.bbci.co.uk/v2/content?path=urn%253Abbc%253Aares%253A%253Aasset%253Asomali%252Fwar%252F2011%252F10%252F111005_business
![](https://paper-attachments.dropbox.com/s_DB291BAEDD3798C18A7687787817DE7CD4365B51264571131C95C12B9A7912DA_1588680504303_Screenshot+2020-05-05+at+13.07.48.png)
![](https://paper-attachments.dropbox.com/s_DB291BAEDD3798C18A7687787817DE7CD4365B51264571131C95C12B9A7912DA_1588680504315_Screenshot+2020-05-05+at+13.07.41.png)

    - https://www.bbc.com/swahili/medianuai/2011/10/000002_dira_ya_dunia_fri
    - 5002        The format of the media resource was not suitable (audio). This indicates an HTML5 MEDIA_ERR_SRC_NOT_SUPPORTED error on the audio tag. This is our SMP error 5002: https://confluence.dev.bbc.co.uk/display/mp/Error+Model
    - This Audio legacy asset is working just fine: https://www.bbc.com/tamil/science/2015/02/150222_cannabis_reasearch
![](https://paper-attachments.dropbox.com/s_DB291BAEDD3798C18A7687787817DE7CD4365B51264571131C95C12B9A7912DA_1588680762768_Screenshot+2020-05-05+at+12.53.02.png)

    - Same issue or two different issues?
        Ares https://jira.dev.bbc.co.uk/browse/ARES-972

**Comment by gavinspence** [comment]
Works now
