### ISSUE TITLE
Add Dari Radio Schedule to /persian/afghanistan IDX page

### ISSUE THREAD

**Issue by benjifellows** [bbc/simorgh#6409]
**Is your feature request related to a problem? Please describe.**

As part of the creation of the /persian/afghanistan IDX page, the Dari Radio Schedule component needs to be added into the page. 

https://bbc.github.io/simorgh/?path=/story/containers-radioschedule--radio-schedules
https://github.com/bbc/psammead/tree/latest/packages/components/psammead-radio-schedule

**Describe the solution you'd like**
Things that need to be done:
- Add config to specify if the radio schedule should be rendered
- Add config to specify where the radio schedule should be rendered
- Render the component
- Use the withRadioSchedule function on the server to be able to server render Radio Schedules
- Update our usage of getRadioScheduleEndpoint to accommodate the Radio Station name not matching the Service name

**UX**
Check with UX the positioning of the component on the page is correct
Jim suggested: "Can we put it somewhere then editorial can feedback if we want to move it?", "after Features, which mirrors where it is on PAL (mobile)"

**Testing notes**
- [ ] Create tests => integration, snapshot, assertion
- [ ] Ran Radio Schedule tests on IDX pages

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
We discussed with product and agreed to initially render radio schedules under the "Features" sections, and if editorial give us feedback, we can update the position.

**Comment by Bopchy** [comment]
Possible approach: Add in new object for IDX page config for Persian and Ukranian services. This will contain `hasRadioSchedules` value
