### ISSUE TITLE
IDX - Fetch index data from ARES

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#6413]
**Is your feature request related to a problem? Please describe.**
This issue is dependent on https://github.com/bbc/simorgh/issues/6422, which renders an IDX skeleton page. In here, we will have created a new route for IDX pages.

We can do the following in parallel with this:
- Add fixture data and a local route for the IDX pages. https://github.com/bbc/simorgh/issues/6432
- Route the ARES index feeds via mozart: https://github.com/bbc/simorgh-infrastructure/issues/991

We then need to fetch the data for the IDX page, transform it, and provide the data to the page container.

**Describe the solution you'd like**
- Create a `getInitialData` function for IDX pages, that fetches data from that feed.
- Apply the data transformation rules from the `home` route to the payload we get back from the index feed.
- Validate:
  - The schema matches the schema we currently get back for home pages.
  - We use same keys for `squash-top-stories` - this should be correct.

We can then display the story promos in https://github.com/bbc/simorgh/issues/6420.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
This is blocked on making the data available, in https://github.com/bbc/simorgh/issues/6432 and https://github.com/bbc/simorgh-infrastructure/issues/991

**Comment by thekp** [comment]
A part of this issue, we should just render the pageData to ensure we are seeing the data.
