### ISSUE TITLE
Display H1 on IDX pages

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#6414]
**Is your feature request related to a problem? Please describe.**
The page should include a visible h1 title - `metadata.title` in the ARES feed.

Given: I am on the url /persian/afghanistan
When: I look at the page
Then: I see a h1 title component from Ares feed data

Given I use a screen reader
When I navigate to the main landmark
Then a heading level 1 must be the first content to be announced in the landmark
And this must uniquely identify the page: 
‘the title we get from ARes feed’

- Ensure that this H1 is the target of the skip to content link.

**Describe the solution you'd like**
We need to ensure that the title tag is the full headline from ARES feed e.g the full headline on the IDX page

**Describe alternatives you've considered**

**Testing notes**
Manual testing of H1 title including accessibility testing of it(also test for skip to content )
Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
- Double check with UX, is this exactly the same as the Most Read page title (the font is different in designs but it may have been updated in one place and not the other) - if so we can split this out into a reusable component in Psammead that can be used in both places.

**Comment by greenc05** [comment]
Should be be ensuring the skip to content funcationaliy is in the h1, as part of this issue?

**Comment by DenisHdz** [comment]
>     * Double check with UX, is this exactly the same as the Most Read page title (the font is different in designs but it may have been updated in one place and not the other) - if so we can split this out into a reusable component in Psammead that can be used in both places.

UX has confirmed they are they same title, so will be creating a new Psammead component that can be used by the two pages types.

**Comment by DenisHdz** [comment]
> Should be be ensuring the skip to content funcationaliy is in the h1, as part of this issue?

@greenc05 This was added already as a part of the [Skeleton work](https://github.com/bbc/simorgh/pull/6506/files#diff-346f8e3caa9c1d2bbbad14c28dc2fcaaR6) and will be replicated in the new Psammead component.
