### ISSUE TITLE
Add Metadata to IDX pagetype for persian/afghanistan

### ISSUE THREAD

**Issue by EinsteinNjoroge** [bbc/simorgh#6415]
**Is your feature request related to a problem? Please describe.**
IDX pages should contain the correct metadata

**Given**: I am on the url /persian/afghanistan
**When**: I share the Page on Twitter and Facebook
**Then**: I get the correct Title and Description

**Describe the solution you'd like**
Use `summary` tag from ares as the `description` meta tag
The `title` meta tag should be the same as the title displayed in the h1 in https://github.com/bbc/simorgh/issues/6414.
Otherwise display the same information as the homepage. We should then audit this.

**Describe alternatives you've considered**

**Testing notes**
This will need unit tests.
Create metadata tests following an example (these are covered by the core integration tests that will be run for this page type - these need to be added in another issue.)

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
This is blocked until we have data from the ARES feed: #6432 and bbc/simorgh-infrastructure#991
