### ISSUE TITLE
Collect ATI & Chartbeat analytics from IDX pagetype

### ISSUE THREAD

**Issue by EinsteinNjoroge** [bbc/simorgh#6416]
**Is your feature request related to a problem? Please describe.**
The BBC should be able to access analytics around IDX page

**Given**: I'm looking at Chartbeat
**When**: I look for the /persian/afghanistan page
**Then**: It should act like a Homepage

**Given**: I'm looking at ATI
**When**: I look for the page inspector
**Then**:
- _~The page includes the Chapter where it is homed~_ 
- _`AND` identifies itself with (x07) as : index-section_
- _AND has the same language as /persian_

**Question**
- How do homepage analytics behave?
~Use of Chapter? _(Chapter in CPS represents where story is in CPS, generally the section)_~

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
Blocked til this issue is complete: https://github.com/bbc/simorgh/issues/6413
