### ISSUE TITLE
Display Most Read on /persian/afghanistan IDX page

### ISSUE THREAD

**Issue by OlgaLyubin** [bbc/simorgh#6418]
**Is your feature request related to a problem? Please describe.**

As a part of an IDX /persian/afghanistan page, we need to render a Most Read section
https://github.com/bbc/psammead/tree/latest/packages/components/psammead-most-read
https://github.com/bbc/simorgh/tree/latest/src/app/containers/MostRead

**Given:** I am on the https://www.bbc.com/persian/afghanistan page
**When:** I look at the bottom of the page (below the story promos, above the footer)
**Then:** I see the most read section

<img width="930" alt="Screenshot 2020-05-06 at 08 48 17" src="https://user-images.githubusercontent.com/17802955/81149616-73353080-8f76-11ea-9aa8-f3016e85910c.png">

**Describe the solution you'd like**

- Confirm with Product that we **do** need to display Most Read section.
- Client render Persian Most Read section on the IDX page. (Confirm if this should be SSR - @thekp)

**Describe alternatives you've considered**
Do not display a Most Read section on IDX page if Product decides it is not needed.

**Testing notes**

- Add unit tests/snapshots/integration tests
Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Comment by thekp** [comment]
> Confirm with Product that we do need to display Most Read section.

I have confirmed with product and they said: "Afghanistan - whatever’s simplest.  Ukraine in Russian - no"

Therefore we have to think about conditionally rendering most-read on IDX pages

**Comment by Bopchy** [comment]
Possible approach: Similar to suggested approach mentioned [here](https://github.com/bbc/simorgh/issues/6409#issuecomment-633949490), Add in new object for IDX page config to Persian service config. This should contain `hasMostRead` value
