### ISSUE TITLE
Use home page presentation rules on persian/afghanistan IDX page

### ISSUE THREAD

**Issue by Bopchy** [bbc/simorgh#6420]
**Is your feature request related to a problem? Please describe.**
The IDX page layout should follow the same layout rules as those used on home page. The layout is described [here](https://paper.dropbox.com/doc/WS-Front-pages-layout-iteration-1--AzVhzr0FMGyPkREhjw_PxuWBAg-Q8UJIyuoq1tnTPID76waI)

**Describe the solution you'd like**
G: I am a visitor on the route /persian/afghanistan
W: I am viewing the list of promos on this page
T: They are presented according to the rules defined in this document

#6422 has created a new page container, and #6413 passes the processed data into our page container. We can render the data on this page using the FrontPageSection:

```
const groups = path(['content', 'groups'], pageData);

...

{groups.map((group, index) => (
  <Fragment key={group.title}>
    <FrontPageSection group={group} sectionNumber={index} />
  </Fragment>
))}
```

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Blocked on https://github.com/bbc/simorgh/issues/6413, which passes the processed data into our page container.
