### ISSUE TITLE
Create IDX Skeleton Pages for both Canonical and AMP

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#6422]
**Is your feature request related to a problem? Please describe.**
We want to render Index (IDX) pages in Simorgh which should replicate the current Front Page behaviour. 
Current examples in PAL: 
- https://www.bbc.com/ukrainian/ukraine_in_russian
- https://www.bbc.com/persian/afghanistan
This ticket is about starting off this work by just making a page container and making the routes.

**Describe the solution you'd like**
We should begin with the creation of a skeleton page with the routes set up at /persian/afghanistan, /persian/afghanistan.amp, /ukrainian/ukraine_in_russian and /ukrainian/ukraine_in_russian.amp and for Canonical and AMP respectively. 
- This will require an IDX page container which can just return a div for the time being.
- This will also require adding the routes to `mozart-routing`, covered by https://github.com/bbc/simorgh-infrastructure/issues/992

**Post-refinement comments**
1) Regarding routing:  Are there going to be more IDX assets in the future? @tochwill confirmed with @jimjohnsonrollings that no future IDX assets will be made so we only need to route these two pages.

2) The goal is just to get a page on test, the contents, layout, etc. does not need to be considered at the moment.

3) **Technical steps involved:**
 - Make a new route for both IDX pages in Simorgh
   - Create a route which doesn't fall under CPS assets due to having a unique regex for just these routes: 
**/persian/afghanistan
/persian/afghanistan.amp
/ukrainian/ukraine_in_russian
/ukrainian/ukraine_in_russian.amp**
   - Using mostRead as an example in routes, we need a similar export for IDX which specifies `pagetype` and returns a 200 response in the `getInitialData` function
   - ~~Check if IDX pages has a metadata object inside the response. We shouldn't need to do anything as long as Ares is giving us the data~~ @tochwill checked this and confirmed we do have metadata being returned

 - Make a page container using higher order components (eg. withPageWrapper, withContexts) alongside the other page types.
   - Create a snapshot test just to check that it is rendering an empty page. This can be updated later when content is added.

Mozart routing and STM changes will then need to be made in order to see this page on the test environment. This is covered by this issue: https://github.com/bbc/simorgh-infrastructure/issues/992

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
example PR of smoke test: https://github.com/bbc/mozart-smoke-test/pull/215/files
example of adding mozart routing for only TEST and LOCAL env: https://github.com/bbc/mozart-routing/pull/1301.

Notably, unit tests for PAL can be added here: src/spec/integration/routes/pal_routes_spec.rb

**Comment by tochwill** [comment]
Thanks @thekp - I've copied those examples over to the simorgh-infrastructure ticket.

**Comment by thekp** [comment]
> Thanks @thekp - I've copied those examples over to the simorgh-infrastructure ticket.

I was meant to comment it on the infra ticket 🤦 I've deleted it here now 👀

**Comment by thekp** [comment]
Since we are not fetching any data in this issue, but we still need a getInitialData function in our routes export. We can add: ` getInitialData: () => Promise.resolve({ status: 200, pageData: [] }),` and then page should render with no pageData
