### ISSUE TITLE
Test Includes for Batch 1 of Story Pages, Gahuza and Uk China

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#6437]
Before each CPS Story page batch goes live, we need to check includes frequently used on each service work correctly in Simorgh.

## Test Instructions
For each PAL url provided for an include:
- Change the domain to test.bbc.com from bbc.com/bbc.co.uk
- Add `?renderer_env=live` to it to render the page using Simorgh.
- Visit the page
  - It is likely to 404 on first visit, please allow a few seconds for ares to render the asset for the first time

e.g. http://www.bbc.com/gahuza/36575997 -> http://www.test.bbc.com/gahuza/36575997?renderer_env=live

## Acceptance Criteria
When testing we can use the live PAL page to compare against to see if our include render correctly. Acceptance Criteria could include:
- No console errors observed in dev tools
  - **Look out for CSP errors, they are very likely to appear for untested includes**
  - CSP errors will require a bug to be raised and the CSP to potentially be altered
- Looks and behaves as on the PAL page

**Comment by lizcameron** [comment]
Includes (all types) to test for batch 1 (Gahuza and UK China):


SERVICE | ASSET_URL | INCLUDE_TYPE | INCLUDE_URL
-- | -- | -- | --
Gahuza v6 | http://www.bbc.co.uk/gahuza/36575997 | 1 IDT1 | /indepthtoolkit/data-pics/UN_refugee_figures_2015_world_service_greatlakes?app-image=http://news.files.bbci.co.uk/vj/live/idt-images/datapic-UN_refugee_figures_2015/UN_refugee_figures_2015_j5pc6.jpeg
Gahuza v6 | http://www.bbc.co.uk/gahuza/36802263 | 3 VJ | /news/special/idt/clickable_guide.inc?id=nice_attacks_langs_gch_gahuza
Gahuza v6 | http://www.bbc.co.uk/gahuza/36942542 | 3 VJ | /news/special/2016/newsspec_13790/content/iframe/gahuza/index.inc?responsive=true&app-clickable=true&app-image=http%3A%2F%2Fa.files.bbci.co.uk%2Fworldservice%2Flive%2Fassets%2Fimages%2F2016%2F08%2F01%2F160801090104_olympic_mind_match.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/43035137 | 3 VJ | /include/vjafwest/8-africans-in-winter-olympics-2018/gahuza/main?responsive=true&newsapps=true&app-clickable=true
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-36544625 | 1 IDT1 | /indepthtoolkit/data-pics/disability_grace_africa_rm_greatlakes
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-36544625 | 1 IDT1 | /indepthtoolkit/data-pics/disability_retta_ethiopia_rm_greatlakes
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-36548822 | 1 IDT1 | /indepthtoolkit/data-pics/disability_retta_ethiopia_rm_greatlakes
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-36548822 | 1 IDT1 | /indepthtoolkit/data-pics/disability_grace_africa_rm_greatlakes
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-36724668 | 1 IDT1 | /indepthtoolkit/data-pics/chilcot_legal_basis_gch_greatlakes
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-36724668 | 1 IDT1 | /indepthtoolkit/data-pics/chilcot_last_resort_gch_gahuza
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-36843122 | 1 IDT1 | /indepthtoolkit/data-pics/Turkey_crackdown_DigiHub_WS_languages_gahuza
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-37035269 | 3 VJ | /news/special/2016/newsspec_13789/content/iframe/gahuza/index.inc?responsive=true&app-clickable=true&app-image=http%3A%2F%2Fa.files.bbci.co.uk%2Fworldservice%2Flive%2Fassets%2Fimages%2F2016%2F08%2F08%2F160808163046_body_match_ws_app_promo_624.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-37927751 | 3 VJ | /news/special/2016/newsspec_14813/content/iframe/gahuza/us-gop.inc?responsive=true&app-clickable=true&app-image=http://a.files.bbci.co.uk/worldservice/live/assets/images/2016/11/09/161109092836_us_election_2nddaymaps_winner_ws_62_v3.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-37927751 | 3 VJ | /news/special/2016/newsspec_14813/content/iframe/gahuza/us-winners.inc?responsive=true&app-clickable=true&app-image=http://a.files.bbci.co.uk/worldservice/live/assets/images/2016/11/09/161109092836_us_election_2nddaymaps_winner_ws_62_v3.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-37927751 | 3 VJ | /news/special/2016/newsspec_14813/content/iframe/gahuza/us-dem.inc?responsive=true&app-clickable=true&app-image=http://a.files.bbci.co.uk/worldservice/live/assets/images/2016/11/09/161109092836_us_election_2nddaymaps_winner_ws_62_v3.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-40985690 | 3 VJ | /news/special/2016/newsspec_14439/anchor.inc?anchor=anchor1&responsive=true
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-43115360 | 3 VJ | /include/vjafwest/11-black-panther-quiz/gahuza/main?responsive=true&newsapps=true&app-clickable=true
Gahuza v6 | http://www.bbc.co.uk/gahuza/48118437 | 2 IDT2 | /idt2/c463d4fd-23a8-4b7d-8265-225fb44a7e85
Gahuza v6 | http://www.bbc.co.uk/gahuza/48118437 | 2 IDT2 | /idt2/23bb773f-2408-4870-9f7a-0ba861f321ff
Gahuza v6 | http://www.bbc.co.uk/gahuza/49116789 | 2 IDT2 | /idt2/7dade4b3-4ff8-4882-b1de-c7212604da11
Gahuza v6 | http://www.bbc.co.uk/gahuza/50080046 | 2 IDT2 | /idt2/493618f3-907a-4542-8e90-49c9e83ff806
Gahuza v6 | http://www.bbc.co.uk/gahuza/50080046 | 2 IDT2 | /idt2/cb49f4da-7302-4065-8d05-10f3f43c473c
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-46907039 | 3 VJ | /include/newsspec/21841-green-diet/gahuza/app?responsive=true&newsapps=true&app-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-asdf/app_launcher_ws_640_7ania.png&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-asdf/app_launcher_ws_640_7ania.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-47133068 | 1 IDT1 | /indepthtoolkit/data-pics/komlaquote_gahuza?app-image=https://news.files.bbci.co.uk/vj/live/idt-images/datapic-komlaquote/komlaquote_7vo0o.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-48355081 | 2 IDT2 | /idt2/635bad10-a010-4bdb-95cc-5e6e149f72ab
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-48355081 | 2 IDT2 | /idt2/f97befec-a80d-4646-bcd6-b7a1ff35a285
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-48961151 | 2 IDT2 | /idt2/d4b9819b-cb3f-48d0-a0f8-29245a41e306
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-49829216 | 1 IDT1 | /indepthtoolkit/image-sliders/Greenland_sat_pics?app-clickable=true&app-image=https%3A%2F%2Fnews.files.bbci.co.uk%2Fvj%2Flive%2Fidt-images%2Fimage-slider-Greenland_sat_pics%2F1993_credit-nc_dl067.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-50330144 | 2 IDT2 | /idt2/1b8d3bd5-be6d-40ad-a4ab-e6a25a4f5f62
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-50332056 | 2 IDT2 | /idt2/1b8d3bd5-be6d-40ad-a4ab-e6a25a4f5f62
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-50423382 | 2 IDT2 | /idt2/3a260bae-96c1-4003-88f4-6db58a4df7b9
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-50603145 | 2 IDT2 | /idt2/5dfc2f6b-5e86-44f0-b292-62f041ca380f
Gahuza v6 | http://www.bbc.co.uk/gahuza/amakuru-50825332 | 3 VJ | /news/special/idt/syndicated/quiz.inc?id=Climate_Change_Africa_EnglishMaster_WS_Languages_gahuza&apps=false
Gahuza v6 | http://www.bbc.co.uk/gahuza/imikino-48638099 | 3 VJ | /include/vjafwest/439-afcon-2019-live-results-table/gahuza/app?responsive=true&newsapps=true&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://news.files.bbci.co.uk/vj/live/idt-images/image-slider-images%20amp/amp_image_ws_640_q2ch1.png
Gahuza v6 | http://www.bbc.co.uk/gahuza/imikino-50027584 | 3 VJ | /include/vjafeast/196-eliud-race-against-time/gahuza/app?responsive=true&newsapps=true&app-image=https://placehold.it/640x360&app-clickable=true&amp-clickable=true&amp-image-height=360&amp-image-width=640&amp-image=https://placehold.it/640x360
Gahuza v6 | http://www.bbc.co.uk/gahuza/institutional-49283343 | 3 VJ | /include/datapres/trust-project/landing-page/gahuza.inc?responsive=true
UKChina v6 | http://www.bbc.co.uk/ukchina/simp/48315606 | 2 IDT2 | /idt2/e2d8fef6-21d0-430c-8185-dc4f190d8040
UKChina v6 | http://www.bbc.co.uk/ukchina/simp/49550154 | 2 IDT2 | /idt2/d9479d73-42c6-4a7a-89fc-6c1e9e7ebe21
UKChina v6 | http://www.bbc.co.uk/ukchina/simp/49909211 | 2 IDT2 | /idt2/636e9854-b515-4157-acd3-e6b67d9c0dd9
UKChina v6 | http://www.bbc.co.uk/ukchina/simp/life-in-uk-47373385 | 1 IDT1 | /indepthtoolkit/image-sliders/AlloaModelRailway?app-clickable=true&app-image=https%3A%2F%2Fnews.files.bbci.co.uk%2Fvj%2Flive%2Fidt-images%2Fimage-slider-ALLOA%20TRAINS%2Freal2_qystx.jpg
UKChina v6 | http://www.bbc.co.uk/ukchina/simp/life-in-uk-47458656 | 1 IDT1 | /indepthtoolkit/quizzes/crossing_divides_wstest_ch/syndicated?app-clickable=true&app-image=http%3A%2F%2Fnews.files.bbci.co.uk%2Fvj%2Flive%2Fidt-images%2Fquizzes-quiz_cta%2Fstart_geh2q.png
UKChina v6 | http://www.bbc.co.uk/ukchina/simp/40826838 | 1 IDT1 | /indepthtoolkit/data-sets/world_record_fees_ws_chinese
UKChina v6 | http://www.bbc.co.uk/ukchina/simp/40826843 | 1 IDT1 | /indepthtoolkit/data-pics/philip_retire_chinese_tra?app-image=https://news.files.bbci.co.uk/vj/live/idt-images/datapic-philip_retire/philip_retire_dogas.png

**Comment by andrewscfc** [comment]
Blocked by https://github.com/bbc/simorgh-infrastructure/issues/994 

@lizcameron has found that a large portion of the includes we need to test are not available on the test environment and it is not realistic to make them available there. Given this is the case, this issue is blocked on making the smallprox endpoint available on live which we can then use for testing.

_The [test harness](https://github.com/bbc/simorgh/pull/6073) needs updating to point at the live environment when https://github.com/bbc/simorgh-infrastructure/issues/994 is completed. We also need to update the test harness instructions above to make it clear we are testing against the live environment._

**Comment by andrewscfc** [comment]
The issue description has been updated to reflect that we no longer intend to use the test harness.

**Comment by andrewscfc** [comment]
Blocked by https://github.com/bbc/simorgh/pull/6427

This PR will provide an initial CSP update to allow a large proportion of includes to work.

**Comment by lizcameron** [comment]
Would be good to check errors/fallbacks as part of this testing - i.e. if any are seen during testing, make a note of them/raise other issues to investigate as part of future batches.

Examples seen so far:

- Unknown cause for this default system styling seen on this page https://www.test.bbc.com/gahuza/23302543. This include (path `/news/special/idt/syndicated/quiz.inc?id=sport_weekly_quiz_week14&apps=false` is available on Test, so not sure why this is showing. Is it the default VisJo fallback?:


![image](https://user-images.githubusercontent.com/52247014/82356645-c50c9a80-99fb-11ea-8bb6-8fa17a4207ea.png)


- Also this error message for the same Include, seen when reloading the same page https://www.test.bbc.com/gahuza/23302543:


![image](https://user-images.githubusercontent.com/52247014/82356548-a1e1eb00-99fb-11ea-86c9-f2138c7384af.png)

- Again, on page reload, sometimes this include does show:


![image](https://user-images.githubusercontent.com/52247014/82356477-8840a380-99fb-11ea-859a-dbe389300fc4.png)

**Comment by andrewscfc** [comment]
Initial CSP update now merged: https://github.com/bbc/simorgh/pull/6427, unblocked

**Comment by staylos92** [comment]
Testing of this is documented here: https://paper.dropbox.com/doc/Test-Includes-for-Batch-1-of-Story-Pages-Gahuza-and-Uk-China--A0QbRepB_4L7RWCrILWUTFjpAg-UUEANEP8Sg37xCLU9FrUg 

See the final 2 columns for details of testing outcome

**Comment by paruchurisilpa** [comment]
Re-tested this and few includes do not load, few includes load without images and few includes load ok but with console errors. The re-test results can be seen here:

https://paper.dropbox.com/doc/Test-Includes-for-Batch-1-of-Story-Pages-Gahuza-and-Uk-China--A0ycw~T0lX0j~O5TD51seCYIAg-UUEANEP8Sg37xCLU9FrUg

**Comment by paruchurisilpa** [comment]
This has gone live, so closing ...
