### ISSUE TITLE
Add missing Features and Analysis titles translations 

### ISSUE THREAD

**Issue by lizcameron** [bbc/simorgh#6453]
**Is your feature request related to a problem? Please describe.**
Some of the translations for 'Features and Analysis' are missing, as editorial were still working on translations. This issue is to add the missing translations to the service configs.

**Describe the solution you'd like**
Add the missing translations to the `featuresAnalysisTitle` field within `translations` in the service configs for the following services (note that currently this field is populated with English placeholder text "Features"):
- Igbo
- Pidgin 
- Yoruba
- Punjabi
- Afaan Oromoo
- Amharic
- Indonesian
- Tigrinya
- Korean
- Gujarati
- Telugu
- UK China (trad and simp)
- Serbian (lat and cyr)

Translations can be found in the translations spreadsheet. Ask @lizcameron for a link.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
- JIRA NEWSART-945

**Comment by FK78** [comment]
The Korean translation is the same as the Tigrinya translation.
