### ISSUE TITLE
Implement Comscore tracking for AMP

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#6472]
**Is your feature request related to a problem? Please describe.**
Comscore is considered the market standard for tracking website popularity across most of the globe.  This is used heavily by advertisers when deciding where to sell advertisements.  While this is the primary use case for this data there are other internal uses.

We need to implement this tracking for AMP.

There is a separate issue for implementation on Canonical: #6754 

**Describe the solution you'd like**
Implement the Comscore tracking beacon in all AMP pages.

This is the code recommended by Comscore - the `c2` value inserted is specific to us as an organisation:
```
<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
<amp-analytics type="comscore">
  <script type="application/json">
    {
      "vars": {
        "c2": "17986528"
      },
      "extraUrlParams": {
        "comscorekw": "amp"
      }
    }
  </script>
</amp-analytics>
```
Consent for AMP is handled by the amp-consent library and we do not need to do anything specific.  My understanding is that if the user has either consented or explicitly not-consented, then the beacon will fire appropriately, however if the user has ignored the consent option, and there is no consent policy timeout (and I understand we don't set a timeout) then no beacon is sent.

- Create a ComscoreAnalytics container (similar to ChartbeatAnalytics container)
- Add to current amp-consent implementation

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: We can add unit tests for the content of the amp-analytics component. We can have integration tests to make sure the amp-analytics type="comscore" component is added to AMP pages. 

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
Q: Can we only add comescore tracking for the services we'll have ads for?

@jimjohnsonrollings (we do not want to add additional javascript to slow down the page)

**Comment by jimjohnsonrollings** [comment]
A: We want it for all services - it will be used to inform whether we turn on ads for more services in the future

**Comment by mmcculloch** [comment]
* Should this have a toggle similar to `chartbeatAnalytics` ?
* Do I have to do anything special to implement with amp-consent?
* How do I confirm that comscore is working?

**Comment by jimjohnsonrollings** [comment]
* Toggle: That I think is an engineering decision
* amp-consent: Nope, my understanding is that it just works
* good question...

**Comment by jimjohnsonrollings** [comment]
Re question 3 - I've asked on the Jira ticket.

**Comment by sareh** [comment]
On question 1 - yes, I think it'd be good to have a toggle for this in the same way as chartbeatAnalytics.
