### ISSUE TITLE
"Content not available" placeholder not displayed for live stream if no image exists

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6495]
The following test asset has a live stream, however, because there is no associated image, no media player or placeholder is displayed on the MAP page: https://www.test.bbc.com/somali/23055894

```
"content": {
    "blocks": [
      {
        "available": true,
        "caption": "Uganda oo sheegtay ka baxida Soomaaliya 30",
        "duration": "PT0S",
        "embedding": false,
        "externalId": "bbc_world_service_west_africa",
        "format": "audio",
        "id": "63485393",
        "live": true,
        "subType": "primary",
        "type": "version"
      }
    ]
```

Ideally, we would see the "Content not available" placeholder

**Comment by gavinspence** [comment]
I think this is fixed in production. Also this is a test asset using an old stream.

**Comment by gavinspence** [comment]
Not addressing
