### ISSUE TITLE
Media block without ID not displaying on MAP

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6497]
e.g. https://www.bbc.com/persian/afghanistan/2013/04/130429_l42_vid_afgh_corruption

We should probably add logging to determine the number of occurences - at the moment this would probably slip throught the cracks, and we would be unaware that there is no media block displaying. 

We could also consider being less "strict" and allow media player to be displayed without a block ID, however we would need to confirm that this behaviour is OK for STYs if there are multiple players on the page

**Comment by RichardPK** [comment]
@pharingee remember that good ol' script? Could we run it to see the number of occurrences of this?

Media block has prop `"id": "",` causing the media player not to render

**Comment by pharingee** [comment]
Run on 1000 urls we get 7 urls with no ids. It's not a common occurence, but we can do some logging to see if it occurs on popular urls.

**Comment by rebeccamcginn** [comment]
Tested and working as expected:

https://www.bbc.com/indonesia/multimedia/2013/04/130430_tokoh_pakraden_suyadi_edit
https://www.bbc.com/portuguese/videos_e_fotos/2013/05/130509_passinho_csf
https://www.bbc.com/portuguese/videos_e_fotos/2013/05/130502_insetos_gastronomia_pai
https://www.bbc.com/mundo/video_fotos/2013/04/130429_video_ferrari_policia_dubai_il

Logs are showing up in Sumo for the missing blockId
