### ISSUE TITLE
Update Kyrgyz most read Fixture data to include Optimo promo blocks

### ISSUE THREAD

**Issue by Bopchy** [bbc/simorgh#6500]
**Is your feature request related to a problem? Please describe.**
Most read component was updated to handle data from Optimo in https://github.com/bbc/simorgh/pull/6467. Kyrgyz fixture data was updated in the PR to include sample Optimo data provided in https://github.com/bbc/simorgh/issues/6392. This example data should be updated with real Optimo most read fixture data.
 
**Describe the solution you'd like**
Update Kyrgyz most read fixture data in `.storybook/static/data/kyrgyz` and `data/kyrgyz/mostRead` with data from ares. The new ares most read fixture data should be from Optimo.

**Describe alternatives you've considered**
Retain the example data - but this is not ideal.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
Reason for block: We need to wait for ARES to make the changes for the most read feed to include optimo blocks so that we can get examples

**Comment by jimjohnsonrollings** [comment]
Ares have released their change.
