### ISSUE TITLE
ATI values for most read page

### ISSUE THREAD

**Issue by PriyaKR** [bbc/simorgh#6503]
**Describe the bug**
ATI values `x6` and `ref` for most read canonical and amp pages are not similar to other simorgh pages.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'http://localhost:7080/pidgin/popular/read.amp' or 'http://localhost:7080/pidgin/popular/read'
2. Click on 'brand image'.
3. Then come back again to most read page.
4. Look at the ATI values in network tab.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Won't fix. Closing
