### ISSUE TITLE
Ads: Refactor AMP ads and add MPU support

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#6512]
**Is your feature request related to a problem? Please describe.**
We currently only support leaderboard ads with our AMP ads implementation. We should also support MPUs.

**Describe the solution you'd like**
- As well as leaderboards, we also need to support the `mpu` ad slot type.
- The size is always 300x250.
- The Ad container should accept a prop, which will determine the ad type to display. This can be passed to the AMP ad container in this PR, and will then also be able to be used by the canonical container. prop should be called `slotType` unless a better name makes sense.
- We currently have `ampAdPropsMobile` and `ampAdPropsDesktop`, and render two amp-ads with media queries in order to support desktop and mobile. MPUs are consistent across all breakpoints, so we can just render one amp-ad in this case.
- MPUs also require a grey background, as outlined in the zeplin design: https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5e8daefb3b7e1e22c7d313ed - this is not full width like the leaderboard ad.
- No need to implement yet this will be done in another issue

A quick change of these parameters in the leaderboard position shows the following:

![Screenshot 2020-05-13 at 17 19 36](https://user-images.githubusercontent.com/6690955/81838586-37820400-953e-11ea-8cdb-5c13729a8980.png)

**Describe alternatives you've considered**

**Testing notes**
Unit tests should be sufficient for now, there is a issue to add integration tests later #6255 

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
Refinement:

We were discussed what can be reusable for both AMP and Canonical, and decided to wait till the in-progress is merged in. Then it would be clearer to determine what is reusable.

On the front page main, add another AdContainer that accepts a prop of mpu/leaderboard.
