### ISSUE TITLE
On Demand Integration Test

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6526]
**Describe the bug**
A new integration test for On Demand pages was added.

The snapshot changed from 14th May 2020 to 15th May 2020 and when the pipeline ran at 2am on 15th May, the assertion failed and prevented a build to the Test environment.
If left as it is, this test is going to fail every day.

The asset needs to be updated from Ares V1 response to Ares V2 response to ensure it contains a value for releasedatetimestamp.

<img width="800" alt="Screenshot 2020-05-15 at 10 56 50" src="https://user-images.githubusercontent.com/3028997/82038158-066b1600-969b-11ea-824d-ab8db623acd5.png">

**To Reproduce**
Steps to reproduce the behaviour:

See error https://github.com/bbc/simorgh/pull/6522

**Expected behaviour**

**Screenshots**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
N/A

**Comment by sareh** [comment]
Re-opening this issue since we have failures of integration tests for multiple PRs:

https://github.com/bbc/simorgh/pull/6513
https://github.com/bbc/simorgh/pull/6502

Note that the date seen in the snapshot is 18th May 2020, so it is falling back to today's date still.

<img width="771" alt="Screenshot of errors" src="https://user-images.githubusercontent.com/3028997/82196053-1ed46e00-98f1-11ea-9a3f-4592f830a749.png">

**Comment by karinathomasbbc** [comment]
This has now been resolved
