### ISSUE TITLE
Command + Click into functions and components with from path aliases don't work

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#6528]
**Describe the bug**
Command + Click into functions and components with from path aliases don't work. The path autocomplete also does not work with aliases.

Not having the ability we're used to to click into functions and components is a hindrance especially when trying to track down bugs quickly.

**To Reproduce**
Steps to reproduce the behaviour:

1. Command + click a function or component in Simorgh that is imported from an aliased path
2. Observe you are not taken to the function or component definition

**Expected behaviour**
You should be taken to the function or component definition

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
The first part of this issue might just be an investigation into why the click through to functions is not working
