### ISSUE TITLE
Replace 'Copyright' with 'Image Source' in offscreen image reading experience

### ISSUE THREAD

**Issue by katikaa** [bbc/simorgh#655]
**Is your feature request related to a problem? Please describe.**
Copyright field is not exclusively used for copyright. Some times it is used to convey credit. Some times it's the owner of the photo or the person who took them photo etc. For this reason we need to change the word 'copyright' to something more generic that covers all the reasons.

**Describe the solution you'd like**
If an image has copyright
Then the screen reader reads out "Image Source <image copyright>."

**Comment by bcmn** [comment]
Done in  #652.
