### ISSUE TITLE
OD radio responsive image is choosing wrong sized image for viewport width 

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#6558]
**Describe the bug**
OD radio responsive image is choosing wrong sized image for viewport width resulting in a poor quality image.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/indonesia/bbc_indonesian_radio/w172xh27b7mzccz?renderer_env=live
2. Observe image quality is no good

**Expected behaviour**
Image size is appropriate for the viewport width

**Screenshots**
![Screenshot 2020-05-19 at 10 08 52](https://user-images.githubusercontent.com/4798332/82307808-c9fc2a80-99b8-11ea-8def-bbef03f63dd6.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: chrome, safari, firefox

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
For some reason it's even more noticeable on firefox: 
![Screenshot 2020-05-19 at 16 02 41](https://user-images.githubusercontent.com/22519682/82343089-4fe49980-99ea-11ea-832b-1fccb76b58fa.png)
