### ISSUE TITLE
Update SumoLogic queries for AReS to include radio pages

### ISSUE THREAD

**Issue by pharingee** [bbc/simorgh#6559]
SumoLogic queries containing
"ares-broker.api.bbci.co.uk/api/asset/*/" 

do not include our radio pages which have the following structure:

"ares-api.api.bbci.co.uk/api/ws-media"

Note we have /api/ws-media NOT /api/asset/

**Comment by karinathomasbbc** [comment]
Query updated in Sumologic

**Comment by pharingee** [comment]
The changes made add `ares-broker.api.bbci.co.uk/api/index/*/` logs to the query. Is this expected behaviour?

**Comment by karinathomasbbc** [comment]
I have only updated this query - https://service.eu.sumologic.com/ui/#/search/948061

**Comment by pharingee** [comment]
If you change the time to 7 days you's see `https://ares-api.api.bbci.co.uk/api/index/news/worlds/mobile/domestic` in the list of urls. Is that expected?

**Comment by karinathomasbbc** [comment]
> If you change the time to 7 days you's see `https://ares-api.api.bbci.co.uk/api/index/news/worlds/mobile/domestic` in the list of urls. Is that expected?

This is a tricky one because we probably want to include news articles (since they are provided by Simorgh) but not other news products e.g. index. It's better than it was i.e. now includes radio queries and if it causes issues we can always address in future

**Comment by pharingee** [comment]
Looks good to me then. Should we mark this as completed then?

**Comment by karinathomasbbc** [comment]
If you're happy, that's it manually tested! So we can move to Done. Thanks G.

**Comment by pharingee** [comment]
Sounds like a plan!

**Comment by gavinspence** [comment]
Closing as per the above comment
