### ISSUE TITLE
Compare Reith fonts with different formatting

### ISSUE THREAD

**Issue by katikaa** [bbc/simorgh#656]
**Is your feature request related to a problem? Please describe.**
We need to keep the number of Reith variations to a maximum of 4 (at the moment we have 6 variations in order to cover bold and italics in headlines and text). Because of that we have suggested that we only use Reith Serif Medium and Reith Sans Regular and we add weight to create Bold and we italicise to assimilate the italics family. UX would like to see the different variations on a page so that they can compare the visual output

**Describe the solution you'd like**
Please use this phrase (thanks @sareh!) and output it on a page with all below combinations:
"The quick brown fox jumps over the lazy dog"
- Compare Reith Sans Bold with Reith Sans Regular weighted
- Compare Reith Serif Medium Italics to Reith Serif Medium with italic formatting
- Compare Reith Sans Regular Italics to Reith Sans Regular with italic formatting
- Compare Reith Sans Bold Italics to Reith Sans Bold with italic formatting
- Show Reith Serif Medium, Reith Sans Regular and Reith Sans Bold next to each other
**Additional context**
Please work with UX (Natalie or Ngan Thi)

**Comment by bcmn** [comment]
I've created a story for this in the branch `font_comp`. Feel free to make changes or give me a shout if any adjustments are needed.

Screenshots
<img width="1458" alt="screen shot 2018-09-28 at 10 51 53" src="https://user-images.githubusercontent.com/11646957/46202095-c90f1480-c30d-11e8-86a2-e8ab0b44911f.png">

<img width="1457" alt="screen shot 2018-09-28 at 10 52 05" src="https://user-images.githubusercontent.com/11646957/46202096-cc0a0500-c30d-11e8-898a-b749993b437f.png">

<img width="1454" alt="screen shot 2018-09-28 at 10 52 14" src="https://user-images.githubusercontent.com/11646957/46202101-ce6c5f00-c30d-11e8-823f-dfeb70c1b510.png">

<img width="1461" alt="screen shot 2018-09-28 at 10 52 24" src="https://user-images.githubusercontent.com/11646957/46202116-d3c9a980-c30d-11e8-9610-f9c5a5cd8f8e.png">

<img width="1460" alt="screen shot 2018-09-28 at 10 52 37" src="https://user-images.githubusercontent.com/11646957/46202121-d6c49a00-c30d-11e8-9780-2538fbcc686b.png">

**Comment by bcmn** [comment]
As all the immediately actionable parts of this ticket are completed & it's just adding noise to the board, we have agreed to close this & open any further actions as tickets when necessary.
