### ISSUE TITLE
Episode pages will 404 for 5 - 10 seconds until ARES retrieves the data from Nitro

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6573]
Go to https://www.test.bbc.com/pashto?renderer_env=live
Click on an episode link in the schedule. 
Note the episode page shows a 404 - it takes about 5 - 10 seconds for the data to load in from nitro and you have to continuously refresh. 

More info in this doc: 
https://paper.dropbox.com/doc/Slow-Responses-on-Episode-Pages-Framing-the-problem--A0arXabwmIPu8LAhOS3Tawy0AQ-6JCoSuwvnuiHsIX32OBe5

A user is going to leave the site 

Spike - retry the ARES API if I get a 404 or 202 response for an episode page
https://jira.dev.bbc.co.uk/browse/WSMEDIA-184

Ryan's spike: https://github.com/bbc/simorgh/compare/fetch-data-retry

AReS slack convo:
https://bbcnews.slack.com/archives/C70C1RPGE/p1589388340025600

Let's get someone from AReS team to attend amigos

Profile the ARES responses for ondemand radio endpoints

**Comment by aeroplanejane** [comment]
We are profiling the response. 
ARES are also looking at a couple of fixes: 
Caching the episodes in advance: https://jira.dev.bbc.co.uk/browse/ARES-1185 
They've also added a fix to improve the speed: https://jira.dev.bbc.co.uk/browse/ARES-1152

**Comment by karinathomasbbc** [comment]
Closing - we are tracking https://github.com/bbc/simorgh/issues/7022 for pre-warming the cache instead
