### ISSUE TITLE
Resolve spacing between secondary column components

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#6584]
### Is your feature request related to a problem? Please describe.
There is too much space between the Onward Journey components (Top Stories, Features & Analysis, and Most Read) in the secondary column.

Have a look here - https://www.bbc.com/afrique/monde-58559264

![image](https://user-images.githubusercontent.com/59573468/133768332-293ffa66-a013-4b0f-8fe0-25ff37f772ab.png)

### Describe the solution you'd like
The space between these components should always be equal to 40px.

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.
- [x] This feature is expected to have a UX review.

### Additional context
![spacing](https://user-images.githubusercontent.com/1430787/82564770-3a4dac00-9b71-11ea-835f-78af74840c63.png)

**Comment by oluoluoxenfree** [comment]
The current implementation still uses the old grid; currently blocked by #3686
