### ISSUE TITLE
Update tags in scenarios to not list predicates with no tags

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#660]
**Is your feature request related to a problem? Please describe.**
The scenarios currently treat a lack of tags for a given predicate in different ways.

**Describe the solution you'd like**
When a predicate has no tags, that predicate won't be shown at all.

**Describe alternatives you've considered**
Considered an empty array or null, but decided that it's more future proof to show only the predicates which are relevant to the article rather than specify some predicates that will always appear, given that the available predicates will change in the future.

**Additional context**
N/A

**Comment by sareh** [comment]
Needs to be updated for articles in 
`data/test/news/articles/c0000000001o` & `c0000000015o` to `c0000000024o` inclusive
