### ISSUE TITLE
Remove top navigation bottom border

### ISSUE THREAD

**Issue by FK78** [bbc/simorgh#6602]
**NB - this issue exists within Psammead, not Simorgh**

Simorgh PR - https://github.com/bbc/simorgh/pull/7305
Psammead PR - https://github.com/bbc/psammead/pull/3628 ✅ 
Version bump PR - https://github.com/bbc/psammead/pull/3629 ✅ 

**Describe the bug**
There is a 1px [pink line](https://user-images.githubusercontent.com/34196381/82549219-1c218500-9b4c-11ea-9635-75fdd0c9dcde.png)  below the seconday nav bar that needs to be removed. It wasn’t intended design but a technical limitation - the way the component was built to allow the items in the nav wrapping over two lines meant that the line couldn’t stretch over 1280px.

We also have an [additonal px](https://user-images.githubusercontent.com/34196381/82549248-2cd1fb00-9b4c-11ea-872e-dff3960befb2.png) of padding below the hover state of the News nav bar.

This impacts all page types.

This issue might be related to this https://github.com/bbc/simorgh/issues/5864

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any Simorgh page
2. See issues mentioned above.

**Expected behaviour**
There should be no padding between the hover state on the News nav bar and the pink line below the secondary nav should be removed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
If picked up by ws-stories or ws-media speak to ws-home for more context as they built this component.
Denis Hernandez worked on the nav so may be good to consult with him when picking this up.

**Comment by DenisHdz** [comment]
For context, this is not a line, but a border-bottom we apply to each list item in the navigation, so when the navigation breaks into different lines, they have a separator in between:

<img width="860" alt="nav" src="https://user-images.githubusercontent.com/46446236/84037161-1a522100-a996-11ea-9716-4239fda904f8.png">

The colour used is `C_POSTBOX` with 30% of transparency https://github.com/bbc/psammead/blob/latest/packages/components/psammead-navigation/src/index.jsx#L30
