### ISSUE TITLE
Remove blockIds from scenario data

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#661]
**Is your feature request related to a problem? Please describe.**
Optimo propose not to surface blockIds in the data.

**Describe the solution you'd like**
Remove the blockIds from our scenario data

**Describe alternatives you've considered**
N/A

**Additional context**
@BogdanDogaru has an action to confirm this won't cause us any problems

**Comment by BogdanDogaru** [comment]
We are safe to remove the `blockId`s from our data source but we'll need to make some changes in our app first.

**Comment by sareh** [comment]
Blocked until these PRs are completed: https://github.com/BBC-News/simorgh/issues/661 & https://github.com/BBC-News/simorgh/issues/740

**Comment by pjlee11** [comment]
Closed in favour of https://github.com/BBC-News/simorgh/issues/794
