### ISSUE TITLE
Move article data handling from render to getInitialProps

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#662]
**Is your feature request related to a problem? Please describe.**
Currently there is data manipulation in the Article Container's `render` method. We should move that to the `getInitialProps` method.  

Prompted by this comment: https://github.com/bbc/simorgh/pull/647#discussion_r217465970

**Describe the solution you'd like**
Data fetching and manipulation should happen in `getInitialProps` and these props should be passed to the `render` function.

**Comment by jtart** [comment]
Closed as won't fix.
