### ISSUE TITLE
Add Linked data to IDX page

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#6621]
**Is your feature request related to a problem? Please describe.**
We currently have an IDX skeleton page and need to add Linked Data to this page.

**Describe the solution you'd like**
- Import the linked data container into the IDX page.

The linkedData currently has [props](https://github.com/bbc/simorgh/blob/b11344b1461700bdfd3734a7c1a5c2bee786f2b2/src/app/containers/LinkedData/index.jsx#L99-L115) of: 
```
LinkedData.propTypes = {
  showAuthor: bool,
  type: string.isRequired,
  seoTitle: string.isRequired,
  headline: string,
  description: string,
  datePublished: string,
  dateModified: string,
  aboutTags: arrayOf(
    shape({
      '@type': string,
      name: string,
      sameAs: arrayOf(string),
    }),
  ),
};
```

We should pass the same props as what the FrontPage does (`type` and `seoTitle`). The seoTitle should be the meta title.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by Bopchy** [comment]
Blocked on pageData being available - https://github.com/bbc/simorgh/issues/6413
