### ISSUE TITLE
Investigate Client Error Monitoring Solution for Simorgh

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#6641]
**Is your feature request related to a problem? Please describe.**
Currently, we have no visibility of errors on people's devices. We rely on individuals noticing and raising issues. We should investigate a solution for client monitoring.

**Describe the solution you'd like**
We currently log server errors into sumologic. There is a sumologic client monitoring solution, for which a library is provided [here](https://github.com/SumoLogic/js-sumo-logger). However, we are looking at migrating this logging away from sumo logic, so it is worth considering an alternative approach.

There are many teams at the BBC, some of whom may already have a client error monitoring solution in place. Check with the iPlayer, Sounds and media playback (Jim Ley) teams to see what they already have in place, and whether we are able to reuse this. @chris-hinds has mentioned a solution that is being worked on by these teams so may be able to direct us.

It is also worth considering this alongside this alongside the [investigation into client performance monitoring](https://github.com/bbc/simorgh-infrastructure/issues/1034). Should this data be collected in the same place?

- Once we know what a potential solution is, do we need to sample either performance monitoring, or errors reported (we want to collect all of these if possible), or both?

We should identify a possible solution and estimate how much work this would be as the output of this issue. We can then make a call if we should implement this before releasing display ads.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
I have written up some initial thoughts regarding the iPlayer/Sounds solution here: https://paper.dropbox.com/doc/Client-Error-Monitoring--A48UiUc57Topot0udESmua~0Ag-2cNeKl0WI89C2uCietEge

**Comment by itimirichard** [comment]
Thanks for the research on this and the detailed doc you've put together @tochwill . I think it's a good idea to follow this approach and if it doesn't suit our needs, then we can investigate other solutions such as Bugsnag, etc, as you suggested.
