### ISSUE TITLE
Migrate SEO / metadata tests from Cypress to integration

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6648]
**Is your feature request related to a problem? Please describe.**
We would like to start migrating tests from Cypress to integration, in small manageable chunks.
We have identified a number of "SEO / metadata" Cypress tests which already exist in integration tests, which can therefore be removed. 

**Describe the solution you'd like**
The following tests run for every configured URL in the Cypress config:
https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllPages.js#L21
https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllCanonicalPages.js#L19
https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllAMPPages.js#L14

Many of these assertions are already run as part of integration tests:
https://github.com/bbc/simorgh/blob/latest/src/integration/common/SEO.js#L5
https://github.com/bbc/simorgh/blob/latest/src/integration/common/core.amp.js#L2
https://github.com/bbc/simorgh/blob/latest/src/integration/common/core.canonical.js#L2

- If the test already exists in integration tests, it should be removed from the cypress suite
- If the test does not already exist in integration tests, it should be added to integration tests and removed from the cypress suite

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by oluoluoxenfree** [comment]
| test in cypress | exists in integration? | 
|-----------------|------------------------|
| should have correct title & description metadata (Twitter and OG) | y  |
| should have resource hints | y |
| should render a H1 which has attributes `id` and `tabindex` | y |
| should include the canonical URL | y |
| should have a correct robot meta tag | y |
| should have lang attribute matching payload data | y | 
| should have the correct shared metadata | ?? |
| should have dir matching service config | y |
