### ISSUE TITLE
Migrate header tests from Cypress to integration

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6649]
**Is your feature request related to a problem? Please describe.**
We would like to start migrating tests from Cypress to integration, in small manageable chunks.
We have identified a number of header Cypress tests which already exist in integration tests, which can therefore be removed. 

**Describe the solution you'd like**
The following header tests run for every configured URL in the Cypress config:
https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllPages.js#L317

Many of these assertions are already run as part of integration tests:
https://github.com/bbc/simorgh/blob/latest/src/integration/common/header.js

- If the test already exists in integration tests, it should be removed from the cypress suite
- If the test does not already exist in integration tests, it should be added to integration tests and removed from the cypress suite
- Tests which check the navigation "burger menu" in different viewports (e.g. https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllPages.js#L400) should remain in Cypress - that's exactly what it's built for!

**Notes**

- Investigation needed on why the [''should have one visible navigation''](https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllPages.js#L378-L400) tests are behind a toggle for articles pages 

**Current setup:**

Cypress
- `'should render the BBC News branding'` [**DELETE** _- already migrated_]
- `"should have offscreen text with product's language code set to English"` [**MIGRATE**]
- `'should not set the language code for localised name'` [**MIGRATE**]
- `'should not have a language attribute if no serviceLocalizedName set'` [**MIGRATE**]
- `'should have a visible banner, with a skip to content link'` [**DELETE** _- already migrated_]
- `'should have one visible navigation'` [**MIGRATE** - Starting point already in Integration]
- `'should show dropdown menu and hide scrollable menu when menu button is clicked'` [**KEEP IN CYPRESS**] ✅

Integration
- `'I can see the branding'`
- `'I can see the navigation'`
- `'I can see a skip to content link'`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by PriyaKR** [comment]
Comparing headers tests in cypress and the integration tests the tests for branding assertion, navigation test and skip to content link assertion are present in both the places additional one that cypress has is the check for scrollable nav at smaller viewports.

Also noticed in cypress the navigation tests for article pagetype are carried out based on the toggle `navOnArticles` value.Do we still need this toggle assertion in here this toggle seems to be enabled across all environments refer `simorgh/src/app/lib/config/toggles/index.js` or we add this toggle assertion in integration test before the nav tests are run.

**Comment by karinathomasbbc** [comment]
> Comparing headers tests in cypress and the integration tests the tests for branding assertion, navigation test and skip to content link assertion are present in both the places additional one that cypress has is the check for scrollable nav at smaller viewports.
> 
> Also noticed in cypress the navigation tests for article pagetype are carried out based on the toggle `navOnArticles` value.Do we still need this toggle assertion in here this toggle seems to be enabled across all environments refer `simorgh/src/app/lib/config/toggles/index.js` or we add this toggle assertion in integration test before the nav tests are run.

Thanks for this analysis, Priya, it is really helpful. I definitely think we need to keep the scrollable nav at smaller viewports, and the use of the toggle check. I believe the other tests can be removed from Cypress, since we do have them in integration.
