### ISSUE TITLE
Remove consent banner translation tests from Cypress

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6652]
**Is your feature request related to a problem? Please describe.**
We have identified a number of consent banner Cypress tests in `cypress/integration/pages/testsForAllPages` which could be removed, as these tests are already run as part of `cypress/integration/specialFeatures/cookieBanner`

**Describe the solution you'd like**
The following tests run for every configured URL in the Cypress config:
https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllPages.js#L288

- Are they a duplicate of the special feature tests?
- If so, delete them from cypress

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by PriyaKR** [comment]
@karinathomasbbc the tests in `cypress/integration/pages/testsForAllPages`  seems to verify the translations for the cookie and banner whereas the tests under `cypress/integration/specialFeatures/cookieBanner` verifies the different use case when different combinations of privacy and cookie banner are accepted or rejected.

So both are entirely different tests and can be left as it is.

**Comment by PriyaKR** [comment]
After discussing with @karinathomasbbc agreed upon removing the translations tests for cookie banners as there is a possibility for the tests to fail when the journalists update the config value and there is less point in testing the translation.

But thought assertion of the page being in localised language is required which seems to be captured in integration tests.So the translation tests in cypress for cookie banner can be removed.
