### ISSUE TITLE
Disable some of the article E2E tests to improve E2E test run time

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6657]
**Is your feature request related to a problem? Please describe.**
In analysing the metrics for Cypress tests in the Test & Live environments (https://paper.dropbox.com/doc/E2E-Test-Improvements--A0vzJEsibrpNfQAoG0O6NPY3Ag-hW9KxI5VIfsUPvBQbn5Yu#:uid=509547277800101499136606&h2=Metrics:-Before) we have discovered that the article E2E tests take **50% of the total test execution time** 😮

Currently, the Cypress config has 1 entry per service for articles, a total of 39.
These tests also run on canonical & AMP, therefore 78 in total.

I have carried out some additional analysis into each test article, and have found a vast number of similarities between them, meaning that there is a chance that we don't need to run the tests for every single article for each service - https://docs.google.com/spreadsheets/d/1R6Kbpjrz_SIrppvhLcvErEm-c-VY8pyhb-jav-N8mXM/edit?usp=sharing

**Describe the solution you'd like**
Could we experiment with reducing the number of article tests which run in Test / Live E2Es by disabling certain services?

Can we select a cross section of articles from the spreadsheet to cover the main variants?
- with and without last updated timestamp
- with and without media player
- media player with and without guidance
- with and without a link to another article
- with and without a BBC image (no copyright)

We should disable E2Es for services which are not listed below:

Test Environment
| Service | Reason |
| -- | -- |
| afrique | RTL, last updated timestamp, BBC owned image (no copyright), video with guidance |
| news | public service, link to another optimo article |
| persian | LTR, service numerals in timestamp, no last updated timestamp, video (no guidance) |
| scotland | public service, no navigation | 
| japanese | public service |
  
Live Environment
| Service | Reason |
| -- | -- |
| azeri | RTL, may be publishing live optimo articles soon, no last updated timestamp, video (no guidance |
| news | public service, last updated timestamp, video (no guidance), BBC owned image (no copyright) |
| kyrgyz | RTL, already publishing live optimo articles, video with guidance | 
| persian | LTR, no last updated timestamp, no media player, |
| scotland | public service, no navigation | 
| japanese | public service |

**Describe alternatives you've considered**

**Testing notes**

**Additional context**

**Comment by karinathomasbbc** [comment]
We have had a discussion and agreed on the following approach:
- we are going to experiment with reducing the number of article E2Es to a handful of services, to cover the "variants" mentioned in the description

>with and without last updated timestamp
with and without media player
media player with and without guidance
with and without a link to another article
with and without a BBC image (no copyright)

- we are not going to remove any of the individial article page tests right now - this is something which we may decide to revisit at a later date
- we will keep the news optimo article test URLs, although these may need to be removed later, when these articles are migrated to WebCore
- we will use kyrgyz test URLs because this service is currently publishing live optimo articles

Please note: issue description has been updated to include the list of articles a result of this discussion

**Comment by amywalkerdev** [comment]
We can definitely remove all cymrufyw and naidheachdan tests, as they do not have any live Optimo articles and will now be rendered by Web Core in the future.
