### ISSUE TITLE
Add Chartbeat analytics to Story pages

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#6689]
**Is your feature request related to a problem? Please describe.**
We need to enable chartbeat analytics for story pages to enable us see how users interact with the story page content in real-time.

**Describe the solution you'd like**
Add `ChartbeatAnalytics` to the `StoryPage` using the approach below:
```
import ChartbeatAnalytics from '#containers/ChartbeatAnalytics';
...
<ChartbeatAnalytics data={pageData} />
```
@sareh suggests this may be the only work required, we can test as per the testing notes below and look at the alternative below if that proves not to be the case.

**Describe alternatives you've considered**
Chartbeat has already been integrated in simorgh so most of the work that needs to be done here will just ensure that it's working on the story pages for both canonical and amp. See an [example pr](https://github.com/bbc/simorgh/pull/5540) of how it was added to the MAP and Radio pages.

To get Chartbeat working for story pages, we need to update the current `ChartbeatAnalytics` [utils](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js) to accept the following properties for story pages.

| Property (param) |  |
|--------|-----------------------|
| `uid` (g) | 50924 - Unchanged |
| `domain` (h) | Unchanged - should be the same as other page types in that service  |
| `useCanonical` | Unchanged |
| `sections` (g0) | CPS has sections and categories that need to be considered. E.g. "Mundo, Mundo - internacional, Mundo - STY, Mundo - internacional - STY, Mundo - feature-category" Add logic to `buildSections` in utils to fit this case |
| `bbc_hid` | Unchanged | Unchanged |
| `title` | Promo Headlines: Headline (from AReS). Refactor `getTitle` to use the Headline for STY pages |
| `window._cbq` | `lgdin anon` as value. Always anon until/unless we integrate with Sign-In  |
| `referrer` (v) | Unchanged |

**Testing notes**
- View the page source to see the chartbeat tags
- Use the live HUD to see that the links are working etc.
- Look at the network call for the old and current

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc
- [X] This feature is expected to need manual testing.

**Additional context**

_As a BBC editor/journalist
I want Chartbeat tags added to story pages
So that I can see page usage in real time._

**_Acceptance Criteria_**
_Given I am on a World Service STY page
When I look at the network requests in the console
Then I can see hits to ping.chartbeat.com
And those hits contain the correct information about the Story_

**Comment by lizcameron** [comment]
From @sareh  I believe it should be fixed by adding the following to the /pages/StoryPage:

```
import ChartbeatAnalytics from '#containers/ChartbeatAnalytics';
...
<ChartbeatAnalytics data={pageData} />
```
