### ISSUE TITLE
Story Include - only loads core content, test only

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#6698]
**Describe the bug**
Some includes only load their core content, looking broken:
> <img width="661" alt="image" src="https://user-images.githubusercontent.com/9645462/83158217-6aaac280-a0fc-11ea-8ff9-2ab4cf9be1ed.png">

We may want to prioritise this as although it only happens on test it will make it difficult to test includes before going live with future services.

The following error is displayed:
> <img width="795" alt="image" src="https://user-images.githubusercontent.com/9645462/83158301-89a95480-a0fc-11ea-812d-0ac17db10e1d.png">

**To Reproduce**
Steps to reproduce the behaviour:

Visit any of the following urls:
- https://www.test.bbc.com/gahuza/36942542?renderer_env=live
- https://www.test.bbc.com/gahuza/43035137?renderer_env=live
- https://www.test.bbc.com/gahuza/amakuru-37035269?renderer_env=live
- https://www.test.bbc.com/gahuza/amakuru-37927751?renderer_env=live
- https://www.test.bbc.com/gahuza/amakuru-50825332?renderer_env=live

**Expected behaviour**
Include loads and renders correctly with no errors.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Browser Firefox

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Testing:

Checked the following URL's  and the include loads and renders ok without errors.

   *  https://www.test.bbc.com/gahuza/36942542?renderer_env=live
   *   https://www.test.bbc.com/gahuza/43035137?renderer_env=live
   *  https://www.test.bbc.com/gahuza/amakuru-37035269?renderer_env=live
   *  https://www.test.bbc.com/gahuza/amakuru-37927751?renderer_env=live
   *  https://www.test.bbc.com/gahuza/amakuru-50825332?renderer_env=live

**Comment by andrewscfc** [comment]
Thanks @paruchurisilpa , looks like the merge of https://github.com/bbc/simorgh/pull/7249 fixed this, I'll close 🙂
