### ISSUE TITLE
Use fragmented data

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#672]
**Is your feature request related to a problem? Please describe.**
[New fragmented data](https://github.com/bbc/simorgh/tree/latest/data/fragmented) exists that is analogous to the new Optimo data structure.

**Describe the solution you'd like**
Refactor rendering logic to be able to render the fragmented data structure, and remove the rendering of markdown.

**Comment by sareh** [comment]
Further work on this is blocked, pending the final decision being made about the fragmented data feed.
