### ISSUE TITLE
Ads: e2e test for zhongwen simp/trad fail when Canonical ads enabled

### ISSUE THREAD

**Issue by mmcculloch** [bbc/simorgh#6734]
**Describe the bug**
Canonical ads are currently disabled on `/zhongwen/simp` & `/zhongwen/trad` because these were failing e2e tests for currently unknown reasons. The follow errors were produced.

```bash
frontPage - /zhongwen/simp - Canonical
       Running testsForAllPages for zhongwenSimp frontPage
         Metadata
           "before all" hook for "should have resource hints":
       Exception in queued GPT command
```

```bash
frontPage - /zhongwen/trad - Canonical
       Running testsForAllPages for zhongwenTrad frontPage
         Metadata
           "before all" hook for "should have resource hints":
       Exception in queued GPT command
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Set the following to true

https://github.com/bbc/simorgh/blob/991a49d0fa143de67d97032cf3e89ee65a21b038/src/app/lib/config/services/zhongwen.js#L49

https://github.com/bbc/simorgh/blob/991a49d0fa143de67d97032cf3e89ee65a21b038/src/app/lib/config/services/zhongwen.js#L271

2. The e2e will pass locally so you need to push it up in a branch.

**Expected behaviour**
Tests should pass

**Testing notes**
- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
This may be that there is a directive specified that is not yet supported by Safari. We should confirm where this is coming from, and whether we think it will cause an issue beyond these errors being logged. We have seen the same thing with our AMP CSP - we need to specify `worker-src` for other browsers, and `child-src` for safari, as there is no one directive covering this that is supported by both latest versions chrome and by safari.
