### ISSUE TITLE
Route Zhongwen variant URLs for Radio Episodes and Brands 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6744]
Fixed by: #6874 (Simorgh routing) ✅ 
[#1401 ](https://github.com/bbc/mozart-routing/pull/1401 )(Mozart routing) ➖ 

Route Zhongwen endpoints for radio brand and episode pages

ARES-1150 will resolve 404s

**episode** 
Given an episode endpoint in ARES https://ares-api.api.bbci.co.uk/api/ws-media/radio/zhongwen/bbc_cantonese_radio/w172xf3qgcmyky5
then it will be routed to a simp variant like this: 
https://www.bbc.com/zhongwen/simp/bbc_cantonese_radio/w172xf3q33b5fbb
and a trad variant like this: 
https://www.bbc.com/zhongwen/trad/bbc_cantonese_radio/w172xf3q33b5fbb

**Brand**
Given we have an ares brand endpoint like this: https://ares-api.api.bbci.co.uk/api/ws-media/radio/zhongwen/bbc_cantonese_radio/programmes/p0340tsy
then it will be routed to a simp variant like this: https://www.bbc.com/zhongwen/simp/bbc_cantonese_radio/programmes/p0340tsy
And a trad variant url like this: 
https://www.bbc.com/zhongwen/trad/bbc_cantonese_radio/programmes/p0340tsy

We don't expect the script to change. This is not supported in PIPs.

**Comment by karinathomasbbc** [comment]
~This may be resolved now:
https://www.test.bbc.com/zhongwen/simp/bbc_cantonese_radio/w172xf3qgcmyky5 - OK
https://www.test.bbc.com/zhongwen/trad/bbc_cantonese_radio/w172xf3qgcmyky5 - OK~
These are still routing to PAL oops.

**Comment by RichardPK** [comment]
Reopened - needs https://github.com/bbc/mozart-routing/pull/1401 merged to be resolved
