### ISSUE TITLE
Resolve promo summary appearing in promo list in the secondary column

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#6746]
### Is your feature request related to a problem? Please describe.
Promos in the promo list within the secondary column on STY pages currently render captions, which also erroneously display at the medium breakpoint. We do not need to display captions at any breakpoint for the following components:
- Cps Related content 
- Cps Top stories
- Features and Analysis 

### Describe the solution you'd like
- Allow promo list promos to render without a caption.
- Adjust space between headline and timestamp accordingly. This should be the equivalent of 8px.
- Prevent caption data from being passed to promo list promos in the secondary column.

This may require a child Psammead issue.

### Describe alternatives you've considered
Hide the caption via styles at medium breakpoint, however this would mean we'd be rendering text unnecessarily.

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.
- [x] This feature is expected to need a11y testing to check Summaries are no longer read out at any breakpoint.

### Additional context
n/a

**Comment by HarveyPeachey** [comment]
There was some discussion about this before, there might be backlog issue somewhere for this https://github.com/bbc/simorgh/issues/6088#issuecomment-630065525

**Comment by simonsinclair** [comment]
> There was some discussion about this before, there might be backlog issue somewhere for this [#6088 (comment)](https://github.com/bbc/simorgh/issues/6088#issuecomment-630065525)

Thanks, Harvey - "backlog" there meant Jira. This is the only GH issue tracking this bug.
