### ISSUE TITLE
Implement Comscore tracking for Canonical

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#6754]
**Is your feature request related to a problem? Please describe.**
Comscore is considered the market standard for tracking website popularity across most of the globe. This is used heavily by advertisers when deciding where to sell advertisements. While this is the primary use case for this data there are other internal uses.

We need to implement this tracking for Canonical, as it needs to be present regardless of whether the page currently carries ads.

There is a separate issue for AMP as the implementation details are different: #6472 

There is an enhancement for SPAs, however that is not considered part of the MVP.

**Describe the solution you'd like**
Implement the Comscore tracking tag.

There is a tag provided by comscore below - however we should look into the suggestions in @jamesdonoh's comment before adding this to our codebase. We want to ensure that this isn't going to be a large performance hit on pages that implement comscore tracking.

We are going to host the script in our static assets so that we can control the versioning.

Comscore recommend the below code:
```
<!-- Begin comScore Tag -->
<script>
  var _comscore = _comscore || [];
   _comscore.push({ c1: "2", c2: "17986528", cs_ucfr: "0" });
  (function() {
    var s = document.createElement("script"), el = document.getElementsByTagName("script")[0]; s.async = true;
    s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b") + ".scorecardresearch.com/beacon.js";
    el.parentNode.insertBefore(s, el);
  })();
</script>
<noscript>
  <img src="https://sb.scorecardresearch.com/p?c1=2&c2=17986528&cs_ucfr=0&cv=2.0&cj=1" />
</noscript>
<!-- End comScore Tag -->
```

As above we will be using our self-hosted version of code rather than pulling in the script provided above ^

NB. _I_ think we could simplify the above because we are only on https

### GDPR & CCPA

If the user hasn't consented to personalisation, then we shouldn't be sending any data to Comscore.

We should check the value of the user's `ckns_policy` cookie - specifically the value of the third character.

Context: The `ckns_policy` cookie stores the user's consent to cookies as three binary digits. The first digit indicates consent to strictly necessary cookies, the second to functional cookies, and the third to performance and advertising cookies.

We should examine the third digit, and based on this select the value of the `cs_ucfr` parameter in the code snippets above to match the value of that third digit (0 or 1).

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

- We need to test, however we implement this, that we don't collect user data unless they have accepted performance and advertising cookies.
- We should look into the points raised by @jamesdonoh in his comment below, as this could affect exactly how we implement automated tests for this.

**Additional context**

**Comment by jamesdonoh** [comment]
Rather than simply implementing the snippet shown above we should look at how we can reduce the risk of loading arbitrary JS from a 3rd-party domain we have no control over. If comScore can offer a versioned URL we could implement [subresource integrity](https://www.smashingmagazine.com/2019/04/understanding-subresource-integrity/), alternately we could explore self-hosting the script.

**Comment by thekp** [comment]
Follow the same implementation of how we upload our static assets in simorgh-infrastructure (i.e static images, js bundles etc).

We will also have to update the provided script so that it only returns the explicit script's functionality and not the functions for creating a script.
