### ISSUE TITLE
Article object on MAPs throwing errors

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6760]
Go to https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.bbc.com%2Fpidgin%2Fmedia-44221514

Notice a lot of strange fields that are throwing error
<img width="616" alt="Screenshot 2020-06-02 at 16 35 42" src="https://user-images.githubusercontent.com/22519682/83544220-7a0f7e80-a4f5-11ea-9d20-bf76354d831c.png">

Expected behaviour - no errors. It looks like these fields shouldn't be here.

**Comment by karinathomasbbc** [comment]
It looks like it is related to one of the tags which has been added to the Minute - Event Coronavirus. When you have an event, you need to specify a location & start date, along with other information (as highlighted above). Not sure whether this should be an editorial fix to change the tag from an event to a name?

Other MAPs are OK e.g. https://www.bbc.com/pidgin/tori-52894183

**Comment by aeroplanejane** [comment]
This is fine!
