### ISSUE TITLE
Ensure `amp` attribute is applied on server-side render

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#677]
**Is your feature request related to a problem? Please describe.**
Running `npm run test:ampValidate` gives this error: 
```
The mandatory attribute '⚡' is missing in tag 'html ⚡ for top-level html'. (see https://www.ampproject.org/docs/reference/spec#required-markup)
```

The page has an attribute `amp={true}` on the client-side render, but does not have it on the server-side render. 
With client-side: JavaScript: (lang and amp attributes on the html element)
<img width="418" alt="screen shot 2018-09-20 at 09 58 21" src="https://user-images.githubusercontent.com/3028997/45807605-c2542200-bcbb-11e8-808a-d3dc3288a24c.png">

Without client-side JavaScript: (only lang attribute on the html element)
<img width="157" alt="screen shot with only lang attribute on the html element" src="https://user-images.githubusercontent.com/3028997/45807520-83be6780-bcbb-11e8-8d11-be9473c3d243.png">

**Describe the solution you'd like**
Ensure the `amp` attribute renders on the server-side render.

**Additional Context**
- Dependent on being able to test with no client-side bundle.

**Comment by pjlee11** [comment]
We should attempt to solve this using `React Helmet` and if this is not possible we should try using `React Helmet Async`

**Comment by pjlee11** [comment]
Likely to be related to this is:
```
Warning: Received `true` for a non-boolean attribute `amp`.

If you want to write it to the DOM, pass a string instead: amp="true" or amp={value.toString()}.
    in html (at Document/index.jsx:18)
    in Document (at server/index.jsx:76)
```

When running locally and hitting an amp url

**Comment by pjlee11** [comment]
Unblocked now that https://github.com/bbc/simorgh/issues/678 is in flight
