### ISSUE TITLE
AMP JavaScript

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#678]
**Is your feature request related to a problem? Please describe.**
Should contain this script for the AMP version, but not for the canonical version.

```
<script async src="https://cdn.ampproject.org/v0.js"></script>
```

Example URLs:
http://localhost:7080/news/articles/amp/c0000000027o AMP
http://localhost:7080/news/articles/c0000000027o Canonical

**Describe the solution you'd like**
Should use the `amp` prop available in the Article Container to conditionally render this script tag.
Since the script tag should be in the head, it's recommended to use React Helmet. 
Reference: https://www.ampproject.org/docs/fundamentals/spec#scrpt

**Comment by pjlee11** [comment]
This should require both unit and cypress tests.
