### ISSUE TITLE
Most Read Page rendering empty page

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#6789]
**Describe the bug**
Most Read has a requirement to not render when the `lastRecordTimeStamp` from the data: https://www.bbc.com/pidgin/mostread.json is greater than 35min.

Since the component is used directly on the most read page, this requirement is tied to the most read page. 

From our server logs, we have over 600 cases of not rendering most read receiving stale data on the page

**To Reproduce**
This can be seen in our sumo logs

**Expected behaviour**
Most Read Page should consistently render the most read component as it is the only component that exists on that page.

- Should we consider increasing the 35min threshold?
- Should we consider removing the ">35min do not render" requirement for the page only?
- Maybe there is a problem upstream in our application? mozart caching? ares caching?
- Should we consider throwing and error?

**Screenshots**
![image (18)](https://user-images.githubusercontent.com/30599794/83751925-916a7b00-a65f-11ea-9df5-bd039564f7b1.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
Investigation findings/actions:

- added extra content to our most-read stale data log (including generated timestamp, and isAmp).
- found out the mozart caching for onward-journeys data is set to 30seconds, can be seen in the [routing payload](https://github.com/bbc/mozart-routing/blob/master/src/lib/mozart_routing/payloads/onward_journeys_mostread.rb#L22-L24)
- we suspect that ares popApi might not be updating sufficiently when a service has a low user visits.

What is going to happen now?
- We suggested Ares team to investigate how reliable the `lastRecordUpdated` value is?


Currently waiting for Ares investigation outcome.

**Comment by thekp** [comment]
Update:

- ARES team has updated the `lastRecordUpdated` to return a valid value rather than a value in the future. (before ARES was returning a value that was BST but given it a `Z` timezone which meant when compiled to BST it would have an extra hour to it.)

- ARES api is cached by user requests, so if a service was to receive low traffic then the first user to visit a page with most read component will receive a cached set of data and the next page visit should get a fresh set of data

**Comment by thekp** [comment]
I've noticed that we are getting lower frequency to no stale data occurrences for services with STY pages, I will continue to monitor the server logs whilst stories team release their pages

**Comment by joshcoventry** [comment]
@thekp Are you still monitoring this, has there been much change in the past 2 weeks?

**Comment by thekp** [comment]
@joshcoventry Nope, I have not been actively monitoring this issue.

I just had a look at the logs, I can see that there has been a significant decrease in the number of services getting stale stale data occurrences for most read page.

Logs from the past 24hours (from 10/07/20)
![image](https://user-images.githubusercontent.com/30599794/87148122-bc22a180-c2a5-11ea-9844-9fc6502f99af.png)

Logs from last Saturday.
![image](https://user-images.githubusercontent.com/30599794/87147969-75cd4280-c2a5-11ea-9b90-2d98c7c5da0d.png)

Logs from last month (06/06/20)
![image](https://user-images.githubusercontent.com/30599794/87148367-2d625480-c2a6-11ea-8ca0-d038bf02a036.png)

The release of STY pages are definitely having a positive impact on the most read data.

**Comment by joshcoventry** [comment]
Based on the last 7 days, there are still a considerable number of services getting stale data:

<img width="984" alt="Screenshot 2020-09-07 at 09 53 50" src="https://user-images.githubusercontent.com/64649560/92368795-15655080-f0f0-11ea-9359-d791d396312d.png">

**Comment by karinathomasbbc** [comment]
We believe that the stale data will be resolved by releasing STY Pages to live. We will revisit this after the Off-Forge work is complete, and decide how to proceed from there
