### ISSUE TITLE
Update AMP specs to enable `focusable` attribute on SVGs

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#679]
**Is your feature request related to a problem? Please describe.**
We use the attribute `focusable="false"` on `<svg>` elements.
This attribute is not in the allowed list for AMP HTML.
See: https://www.ampproject.org/docs/fundamentals/spec#svg  
When you run `npm run test:ampValidate` we get this error:
```
The attribute 'focusable' may not appear in tag 'svg'. (see https://www.ampproject.org/docs/reference/spec#svg)
```

We often need to use the `focusable` attribute set to `false`, for accessibility reasons. Some assistive technology will focus on an svg, whereas this is an extra step for users of this AT to skip past. 

**Describe the solution you'd like**
We should open an issue and also a PR to the core AMP project to add the `focusable` attribute. This issue should have details of the assistive technologies that need `<svg focusable="false">`.

**Comment by sareh** [comment]
@greenc05 I believe the assistive tech that needs `focusable="false"` IE11, with JAWS. However, I can't remember where the results of this investigation work was written up. If you could please point me to that, I'd be very grateful.

**Comment by sareh** [comment]
I added this issue to the Header milestone, since it's the first usage of an SVG on our Article page which uses the focusable attribute. Until this gets addressed, the Header (and also Footer) won't pass AMP HTML validation.

**Comment by greenc05** [comment]
@sareh it's an IE issue, in which SVG's are focusable by default. We add focusable false to take SVG's out the tab order for keyboard and assistive technology users who use IE, Jaws of which is an example as it's mainly used with IE.

**Comment by jtart** [comment]
Issue to add to AMP spec: https://github.com/ampproject/amphtml/issues/19107

**Comment by ChrisBAshton** [comment]
Fixed yesterday in https://github.com/ampproject/amphtml/pull/19128. 

Doesn't look like they've published it to NPM yet - latest version is still 1.0.23 (9 months old): https://www.npmjs.com/package/amphtml-validator

**Comment by ChrisBAshton** [comment]
Estimate publish date ~1-2 weeks: https://github.com/ampproject/amphtml/pull/19128#issuecomment-437426737

**Comment by jtart** [comment]
Fixed! `focusable` no longer errors.
