### ISSUE TITLE
Assets not being served as Brotli where possible

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#6799]
**Describe the bug**
JS assets are being served as `gzip` which while good, could be improved on

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.co.uk/igbo
2. See Gzip being used for assets

**Idea behaviour**
Brotli is served

**Implementation**
This will likely need a webpack plugin to generate, then Akamai/Fastly config to use the files 

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version Latest

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by dr3** [comment]
Good news, you already great brotli files https://github.com/bbc/simorgh/blob/bf4c9b713b8c4134cfec841aa6151977a6e6160e/webpack.config.client.js#L150

So the only changes need are in the Akaimai and Fastly config!

**Comment by chris-hinds** [comment]
Thanks for raising this @dr3 

Looks like we might get ~8% saving if we were serving brotli via Akamai compared to the GZip counter part 

![image](https://user-images.githubusercontent.com/14273378/83774182-4b241480-a67d-11ea-8503-b2c92ffc5f13.png)

**Comment by joshcoventry** [comment]
Replaced by https://github.com/bbc/simorgh/issues/9761
