### ISSUE TITLE
AMP Boilerplate Styles

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#680]
**Is your feature request related to a problem? Please describe.**
This is the amp boilerplate styling that is needed for our AMPHTML version. 

```
<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

```
Source: https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md

> AMP HTML documents must contain this boilerplate in their head tag. Validation is currently done with regular expressions, so it's important to keep mutations as minimal as possible. Currently, allowed mutations are: (1) inserting arbitrary whitespace immediately after the style tag opens, and immediately before it closes; (2) replacing any space in the snippet below with arbitrary whitespace.

**Describe the solution you'd like**
Using the `amp` prop, we should conditionally add style tag to the document head, using Helmet. This can be done in the Article container's `render` function. 

Later on, this and other attributes which are AMP-specific can be moved to an `AMP` component. This refactoring does not need to be carried out for this Issue. 

**Additional context**
Note: we should not use `helmet.style.toComponent();` for this, since it will make it into a react component. We should use `helmet.style.toString();`  This is because the application will not be able to parse the contents of the style tag if we use the `toComponent` method. 
https://github.com/bbc/simorgh/blob/latest/src/app/components/Document/index.jsx#L10-L12

**Additional Context**
- Dependant on move to `uni` and the migration to moving Document to a HTML file

**Testing**
- Can be ran through amp-validate

**Comment by pjlee11** [comment]
As part of this issue we should ensure the issue to refactor things into an `AMP` component is created.

**Comment by sareh** [comment]
Blocked pending refactor of Document, to render to HTML instead of to a React component.
