### ISSUE TITLE
Insufficient data to render Somali radio schedules between 1am and 5am BST

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#6807]
**Describe the bug**
We are seeing `radio_schedule_data_incomplete_error` events for the Somali service's radio schedule between 1am and 5am BST. I do not believe we are receiving enough data from the ares feed to show the 3 latest programmes, I have logged the responses overnight and will investigate.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by JonBeeb** [comment]
Ares team have pushed the fix to live. Need to confirm this provides enough data.
