### ISSUE TITLE
Link text overlaps with the image inside story body in IE11

### ISSUE THREAD

**Issue by paruchurisilpa** [bbc/simorgh#6812]
**Describe the bug**
Inside story body the class 'distinct-component-group container-parrot wsoj-component' the link text overlaps with the image.

**To Reproduce**
Steps to reproduce the behaviour:
1.Go to https://www.bbc.com/mundo/noticias-america-latina-51518716 in IE11
2.Scroll down to "Quizás también te interese"
3.You can see the error

**Expected behaviour**
Text should be visible in all browsers not overlapping with images next to it

**Screenshots**
Screenshot attached.

<img width="1189" alt="Screenshot 2020-06-05 at 11 51 13" src="https://user-images.githubusercontent.com/1379277/83873522-df4cb500-a72b-11ea-8fdf-7905884204f0.png">

**Desktop (please complete the following information):**

- OS: Windows
- Browser IE
- Version 11

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
IE11 cannot interpret 'width: auto' on images correctly. The image width should be explicitly set, in this case its 194px at this viewport. Example below

<img width="1092" alt="Screenshot 2020-06-08 at 10 41 00" src="https://user-images.githubusercontent.com/64649560/84016113-b834f400-a974-11ea-8d85-f79426ef291f.png">

We would need to check this does not have an adverse effect in other browsers.

**Comment by HarveyPeachey** [comment]
I'm a bit confused, isn't this an issue with PAL not Simorgh?

**Comment by paruchurisilpa** [comment]
This is on PAL, I got confused as it had a social embed which went LIVE but mundo is not moved to Simorgh yet.. Will change the label to PAL..

**Comment by paruchurisilpa** [comment]
Closing this
