### ISSUE TITLE
Handle fetch of data not returning an ok response

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#682]
**Is your feature request related to a problem? Please describe.**
If the [fetch of data](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Article/index.jsx#L83) does not return an `ok` response (a status code in the 2XX range), `getInitialData` will return an empty object.

**Describe the solution you'd like**
We should handle a non-`ok` response by returning a `null` object, we could also add some logging around this (our only logging right now is logging to the console).

**Describe alternatives you've considered**
No other clear alternatives.

**Additional Context**
_Testing notes to be added_

**Comment by sareh** [comment]
Closing as fixed.
