### ISSUE TITLE
Cookie banner covers player on amp on smaller phone screens

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#6835]
When on a phone screen below 400px, and on amp, and having not accepted the cookie banner, the cookie banner covers the player in a way that makes it not clear there is a player on the page. 
![Image 08-06-2020 at 15 18](https://user-images.githubusercontent.com/54575620/84042868-87b58000-a99d-11ea-8ca1-62b3aad0015c.jpg)
Screenshot is of iphone 8

This is not a problem on canonical where the cookie banner is at the top, and is fine on phone screens larger than 400px which have a different layout:
![Image 08-06-2020 at 15 29](https://user-images.githubusercontent.com/54575620/84042879-8a17da00-a99d-11ea-8ae8-dd32243b7737.jpg)
Screenshot is of OnePlus 8

Discussion with Tom Williams https://bbcnews.slack.com/archives/GHRMZSQ80/p1591627356043300

**Comment by aeroplanejane** [comment]
I would emphasise that it's not just our pages that are affected. Would we expect to see this behaviour on _any_ amp page in Simorgh at this breakpoint?
