### ISSUE TITLE
Use fallback image for IDT2 Maps and Charts on Canonical

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#6837]
**Is your feature request related to a problem? Please describe.**
Following an investigation (https://github.com/bbc/simorgh-infrastructure/issues/1041) into resolving an issue loading Charts and Map IDT2 includes, we concluded there was no viable way to do this: https://github.com/bbc/simorgh-infrastructure/issues/1041#issuecomment-638743698 . 

This issue is to selectively use a fallback image as on AMP https://github.com/bbc/simorgh/pull/6672 to display IDT2 includes. We will only use a fallback image on 'broken includes'; we need to identify the full range of 'broken' IDT2 includes as part of this issue. A broken IDT2 include gives an error similar to this:
![image](https://user-images.githubusercontent.com/9645462/84054898-f568a880-a9ab-11ea-8558-8488ad7a8b6f.png)

**Describe the solution you'd like**
Please reference this branch as a guide: https://github.com/bbc/simorgh/compare/unsafe-eval-fallback 

Initially please work with testers/product to identify the range of IDT2 includes affected, at the time of writing includes that fetched the following two assets were affected:
![image](https://user-images.githubusercontent.com/9645462/84055233-71fb8700-a9ac-11ea-9386-c3c897800239.png)

When a full list of affected assets is idenitifed please pass this onto @Tarqwyn (https://github.com/bbc/simorgh-infrastructure/issues/1041#issuecomment-638767830) so his team are aware which includes will be served on canonical as images.

When you look through source of an affected include you will find a script tag that fetches an affected asset: 
https://www.bbc.com/ws/includes/idt2/23bb773f-2408-4870-9f7a-0ba861f321ff/html
![image](https://user-images.githubusercontent.com/9645462/84055676-15e53280-a9ad-11ea-88d8-eaa48fc9a1fb.png)
The presence of these tags indicates the include will not load correctly in Simorgh due to restrictions in our CSP.

When script tags like this are identified, the app should render a fallback image matching the requirements for AMP: https://github.com/bbc/simorgh/issues/6563 

It is likely code can be shared with the Amp implementation in this PR: https://github.com/bbc/simorgh/pull/6672 

When an affected asset is not found in the include payload, render the full html as in the existing canonical implementation for IDT2.

**Describe alternatives you've considered**

**Testing notes**
Add integration test to check include has been added to the page.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by lizcameron** [comment]
Maps and all 9 types of Chart are the IDT2 include types that do not currently work. 
List of all possible IDT2 types and examples below for testing.

Displays: 
- Datapic http://www.bbc.co.uk/gahuza/50080046
Path `/idt2/493618f3-907a-4542-8e90-49c9e83ff806`
- Quotepic http://www.bbc.co.uk/kyrgyz/entertainment-50052895
Path `/idt2/90d42d84-1b69-4371-9e60-268ddc600334`

Does not display:
- Map https://www.bbc.com/igbo/afirika-50122504 
Path `/idt2/c54304f1-9afb-40cf-bee3-f42833642798`
- Chart: table http://www.bbc.co.uk/gahuza/50080046
Path `/idt2/cb49f4da-7302-4065-8d05-10f3f43c473c`
- Chart: line chart http://www.bbc.co.uk/igbo/afirika-49607557
Path `/idt2/53583162-eab4-4547-a790-61a7d0d15fdc`
- Chart: bar chart http://www.bbc.co.uk/gahuza/amakuru-48355081
Path `/idt2/f97befec-a80d-4646-bcd6-b7a1ff35a285`
- Chart: column chart http://www.bbc.co.uk/kyrgyz/world-50484410
Path `/idt2/d8f6a0ba-edc6-4511-9ff9-2d510b9c8ecb`
- Chart: stacked bar chart - https://www.test.bbc.com/gahuza/23313911
- Chart: stacked column chart - https://www.test.bbc.com/gahuza/23313911
- Chart: grouped bar chart - https://www.test.bbc.com/gahuza/23313911
- Chart: grouped column chart - https://www.test.bbc.com/gahuza/23313911
- Chart: pie chart http://www.bbc.co.uk/kyrgyz/entertainment-50052895
Path `/idt2/f613f93e-ffa4-4720-a47a-b952a3dc1bb8`

**Comment by andrewscfc** [comment]
Thanks for adding these @lizcameron , @jimjohnsonrollings, looking above it seems we can only display DataPics and QuotePics without using a fallback image, is it worth us investing in the hybrid approach in this issue or should we just use fallback images for IDT2 includes for now? Just decreases complexity and may get this issue completed a bit quicker, we are happy to go ahead with the plan as above though otherwise.

**Comment by jimjohnsonrollings** [comment]
@andrewscfc I am happy with whichever solution is quickest and easiest.

**Comment by simonsinclair** [comment]
This is blocked until https://github.com/bbc/simorgh/pull/6672 is merged.

**Comment by rhenshaw56** [comment]
This should be unblocked now as #6672 has been merged
