### ISSUE TITLE
Invalid linked data properties for live radio pages

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#6840]
**Describe the bug**
Invalid linked data properties for live radio pages - `thumbnailUrl` and `publisher`.

<img width="937" alt="Screenshot 2020-06-09 at 09 12 13" src="https://user-images.githubusercontent.com/4798332/84123278-89308800-aa31-11ea-95a1-e3fd75149b1d.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://search.google.com/structured-data/testing-tool
2. Enter `https://www.bbc.com/korean/bbc_korean_radio/liveradio`

Observe invalid property warning for `thumbnailUrl` and `publisher`.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
This was duplicated here and was closed: https://github.com/bbc/simorgh/issues/4719
