### ISSUE TITLE
Render a Show More button in VJ Includes on AMP

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#6841]
### Is your feature request related to a problem? Please describe.
Following the completion of https://github.com/bbc/simorgh/issues/6917, we will be able to render VJ Includes on AMP. We need to add a Show More button to these.

### Describe the solution you'd like

Using the `resizable` attribute on `amp-iframe` we should implement a Show More button - see example: https://amp.dev/documentation/components/amp-iframe/#iframe-resizing.

#### Translations
"Show More" will have translations. In this issue, we will implement the logic to retrieve this translation from the `showMore` property, but default to "Show More" if that's not available. (Translations will be added in a separate issue).

#### Designs
When integrated successfully with the include, the 'show more' button that appears on VJ includes looks like this:
![image](https://user-images.githubusercontent.com/52247014/85298515-1a751500-b49c-11ea-806d-c92955f9ce96.png)

#### Note

VJ Includes on AMP already include the postMessage code to support this behaviour.
```
// https://news.files.bbci.co.uk/include/vjamericas/176-eclipse-lookup/mundo/app/amp
resizeSetup: function () {
  setInterval(function() {
    window.parent.postMessage({
      sentinel: 'amp',
      type: 'embed-size',
      height: document.body.scrollHeight
    }, '*');
  }, 500);
},
```

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.
- [x] Cypress tests would need to be created to check the 'show more' button is rendering
- [x] Needs an a11y review with Catharine during development

### Additional context
n/a

**Comment by andrewscfc** [comment]
Following completion of this approach in https://github.com/bbc/simorgh/issues/5989#issuecomment-641355816 we need render an `amp-iframe` in this issue:

We probably want to create a specific amp includes container as in @rhenshaw56 's PR here: https://github.com/bbc/simorgh/pull/6672 

This can construct an amp iframe like this: `<amp-iframe src="https://news.files.bbci.co.uk/include/vjamericas/176-eclipse-lookup/mundo/app/amp"></amp-iframe>`

We’ll need to look at the configuration and styling and attributes for this iframe, once we have an initial implementation; below is an example from our legacy amp pages:

https://www.bbc.com/mundo/amp/noticias-51705060

![image](https://user-images.githubusercontent.com/9645462/84164575-95850700-aa6a-11ea-9654-75104c74173a.png)
```
<amp-iframe width="640" height="723" sandbox="allow-scripts allow-same-origin allow-top-navigation-by-user-activation allow-forms" layout="responsive" frameborder="0" resizable="" src="https://news.files.bbci.co.uk/include/newsspec/26866-coronavirus-mapped/mundo/app/amp" class="i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-layout" i-amphtml-layout="responsive" scrolling="no" style="--loader-delay-offset:235ms !important; height: 723px;"></amp-iframe>
```

**Comment by andrewscfc** [comment]
This issue has been broken down into: https://github.com/bbc/simorgh/issues/6917

There will be a subsequent session to break out the requirements for the AMP show more button mentioned above, we will then close this issue.

**Comment by Simon2828** [comment]
This issue requires an a11y developer swarm of the AMP iframe, which checks both when the show more button is displayed and when it is not. @greenc05
