### ISSUE TITLE
OD Radio Episodes - Amp pages have errors: 'Uncaught TypeError: Cannot read property ‘getPreviousItemIndex’ of null', 'e.playlist is null'

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#6842]
Amp pages get errors:

iframe.html:68 Uncaught TypeError: Cannot read property ‘getPreviousItemIndex’ of null
    at X.get (iframe.html:68)
    at n (iframe.html:62)
    at Object.uiConfigUpdated (iframe.html:62)
    at X.i (iframe.html:67)
    at a (iframe.html:67)
    at X.dispatch (iframe.html:69)
    at n.updateConfig (iframe.html:63)
    at e.uiConfigFromBump (iframe.html:65)
    at t.<anonymous> (iframe.html:67)
    at iframe.html:55
On Opera

and 

TypeError: e.playlist is null
on Firefox

Link https://www.bbc.com/indonesia/bbc_indonesian_radio/programmes/w13xtt0s.amp

These do not happen on Canonical.

The original error on this was the Content Security Policy error which does not happen now, and the player and brand image display.

**Comment by LilyL0u** [comment]
@karinathomasbbc updated issue

**Comment by RichardPK** [comment]
~@RichardPK confirming issue isn't within Psammead~

Yea @LilyL0u - we aren't trying to make use of `getPreviousItemIndex` in Psammead or Simorgh. Good to raise with SMP 👍

**Comment by gavinspence** [comment]
Closing as needs raised with SMP
