### ISSUE TITLE
Render "Guide" Story Promos as div instead of heading

### ISSUE THREAD

**Issue by OlgaLyubin** [bbc/simorgh#6845]
**Describe the bug**
We currently have Story Promos of type "Guide" which are not parts of Useful Links, displayed without a timestamp (done in https://github.com/bbc/simorgh/pull/6595).

<img width="1045" alt="Screenshot 2020-06-09 at 11 23 26" src="https://user-images.githubusercontent.com/17802955/84137184-3ad8b480-aa44-11ea-8dfe-3bb57afe5f89.png">

However, it is incorrect in terms of accessibility because it just contains `h3` elements as links without any other content.
For this to be fixed, an `h3` needs to be swapped with a `div`. This PR https://github.com/bbc/simorgh/pull/6342 has work for rendering Story Promo as a `div` completed.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/afrique
2. Click on developer tools
3. Scroll down to "Réseaux sociaux" section
4. See Story Promos rendered as `h3` elements

**Expected behaviour**
Story Promos of type "Guide" that are not Useful Links are rendered as `div`s instead of `h3`s

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

Accessibility Acceptance Criteria: 

Given I am using a screenreader
When I navigate to a 'guide' promo within a 'Useful links' section
And there is no content after the link
Then the promo should not contain heading semantics

**Additional context**

**Comment by PriyaKR** [comment]
LGTM.
