### ISSUE TITLE
Move fetch for config (toggles) to server

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6866]
**Is your feature request related to a problem? Please describe.**

**This ticket should be paired/swarmed on!**

We need to use the data returned from the toggle/config API to decide when to show ads and to enable Ops/Editorial to toggle ads off for a particular service via the iSite form.

We don't need a client-side call to the toggles/config endpoint for every single page, which is currently what is happening in TogglesContext.

For pages that require the toggle/config values, (e.g. initially for display ads), we should get these values before we render a page. 

**Describe the solution you'd like**

_Toggle Flow for Canonical Pages_
![image](https://user-images.githubusercontent.com/54984834/86130890-c5a94e00-badc-11ea-8a98-9ff33a43cc46.png)

**Canonical**

- we want to call config API before rendering the page. Will be slow.
  - fetch from config endpoint for every service (in future we're going to need to do this for translations and other app config)
  - Add a function to the that is called on both the server before fetching the page data, and on the client in `App.jsx` when there is a client navigation.
- We merge remote toggles with the Simorgh defaults, and pass these `toggles` to our data.`{"toggles":{"ads":{"enabled":true,"value":""},"preroll":{"enabled":true,"value":""},"mostRead":{"enabled":true,"value":""}}}`
- In App.jsx, we should get the value `const { toggles } = initialData;`
We need to ensure that we don't just fetch this data on the initial page load but also on a client route change
- Pass in `toggles` to withContexts
- We should update `contexts/ToggleContext`
	- remove the fetch
	- add `toggles` prop to ToggleContextProvider
- Ensure our usage for useToggles do not change!

 - Slowness/excess data requests could be mitigated by cacheing the response for each service.
  - We will add an in memory cache to Simorgh.
- We will cache the response from the config service based on the URL - so there should be one request per service for the length of time we set as the cache's max-age.
- This will be configurable as an environement variable - to begin with we will set this cache age as 60 seconds and monitor.

- Note that in a follow-on PR we want to remove ToggleContextProvider. We should discuss the implications of this on a follow-on issue. 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Engineers should ensure that we are not making any client-side network requests to the config service.
Ads should continue to be rendered on the services that currently render ads.
There should be no content shifting when the ad is loaded in.

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
After some conversations across teams, we're going to change the approach here slightly. The story pages and media pages at least are going to be using this config from iSite imminently, so it makes sense to have this available for all routes.

- Make the call to the toggles service in the main server file, in parallel with the data fetch. This means we will fetch config for every route, not just home.
- As this could result in a fetch to the toggles service for every page view, we should cache this response in memory and read data from this cache until a max-age (to be defined) has expired.
- We will have one response to cache from the toggles service per service.
- We also want to ensure that client navigation still uses up to date config values. We can pass the values from the server into the app as has been done in this PR. We also want to make another call on client navigation - this could be done in the ToggleContext as has been removed in this PR, with an extra check to make sure we don't have values from the server fetch before making this call.
- In future, we could keep the values from the server in a cache on the client, and only make another client side fetch if this data is stale. This could be a consideration after this initial PR when we introduce more client navigation to Simorgh.

Actions for today:
- Have another look at in memory cache libraries. I've used https://github.com/isaacs/node-lru-cache previously, but it's worth checking if there are any newer libraries that could be another option.
- Update this PR to move where we fetch the data, bring back the client fetch (maybe update the logging in there), and make sure we don't fetch on the client if we have data from the server.
- Update tests to match this approach
- Understand why our cypress tests fail when we render ads (this PR means we start to render ads in cypress tests) - the GNL code uses a module/nomodule approach, which targets different browsers based on their capabilities. It looks like the version of the GNL code that is included with our tests includes `.finally`, which isn't supported by the browser that our tests are running in. In our CI we use electron, in travis we use firefox... - let's find out which version is being used in CI (we're running an old version on cypress in CI).
