### ISSUE TITLE
Enable support of /bbc_[service]_radio/programmes file data structure in fixture data

### ISSUE THREAD

**Issue by RichardPK** [bbc/simorgh#6880]
The url path for OD-radio brands is: `/service/bbc_[service]_radio/programmes/[pid]`

Currently our fixture data path does not support this structure, so OD radio brands are accessed in the same way as episodes, i.e.:  `/service/bbc_[service]_radio/[pid].json`

Therefore we don't have a way of distinguishing between brand/episode fixtures with the current data structure.

The od-radio data path should handle /programmes/ folder nesting.

**Comment by rebeccamcginn** [comment]
Closed as pages will not diverge
