### ISSUE TITLE
Russian MAP player error - on first load, player is not there and error in console

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#6886]
On first loading the page https://www.test.bbc.com/russian/av/media-52355574 in firefox, the player does not display and there is an error in the console.

![Screenshot 2020-06-12 at 11 06 43](https://user-images.githubusercontent.com/54575620/84498317-5ba14400-aca8-11ea-8fd1-d7546ff26954.png)

TypeError: window.dotcom.ads is undefinedru:77:15
    <anonymous> https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:77
    execCb https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    check https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    enable https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    bind https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    emit https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    each https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    emit https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    check https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    enable https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    init https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    a https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    completeLoad https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61
    onScriptLoad https://polling.test.bbc.co.uk/ws/av-embeds/cps/russian/media-52355574/p089zrbh/ru?morph_env=live:61

When the page is refreshed, the player appears and the error is gone. It also does not happen every time, but the best way to replicate it to sometimes work is to go to the URL in an incognito browser window on firefox. 

It also happened in Opera:

![Image 12-06-2020 at 11 09](https://user-images.githubusercontent.com/54575620/84498513-b2a71900-aca8-11ea-951b-6a5c2b487b24.jpg)
With a different error in the console.

ru?morph_env=live:77 Uncaught TypeError: Cannot read property 'enabled' of undefined
    at ru?morph_env=live:77
    at Object.execCb (ru?morph_env=live:61)
    at e.check (ru?morph_env=live:61)
    at e.<anonymous> (ru?morph_env=live:61)
    at ru?morph_env=live:61
    at ru?morph_env=live:61
    at each (ru?morph_env=live:61)
    at emit (ru?morph_env=live:61)
    at e.check (ru?morph_env=live:61)
    at enable (ru?morph_env=live:61)

@jroebu14 @RichardPK

**Comment by LilyL0u** [comment]
I now cannot recreate this on firefox or opera

**Comment by rebeccamcginn** [comment]
Fixed by Jonathan
