### ISSUE TITLE
Add Contributors section to our main Readme

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6887]
**Is your feature request related to a problem? Please describe.**
We'd like to recognise the open source contributors in our repository readme.
There is already a standard way to include contributors to a repository, below: 

We should add a section specifically for open-source contributors. 

`## Open Source Contributors` 
`We welcome Open Source contributors. [[Contribute](CONTRIBUTING.md)].`
`<a href="https://github.com/bbc/simorgh/graphs/contributors"><img src="https://github.com/bbc/simorgh/blob/latest/docs/open-source-contributors.svg" /></a>`

Since the vast majority of current contributors on this project are currently employed by the BBC, I think instead of just listing all the contributors, we should have a list of those who have contributed as _open source_ contributors. 

**Describe the solution you'd like**

Add an image to `/docs/open-source-contributors.svg` using an SVG of the format of this one: https://opencollective.com/SelfDefined/contributors.svg?width=890&button=false The styles here can be reused. 

Update the main README.md file with a `## Open Source Contributors` section with contributors listed.

**Describe alternatives you've considered**
N/A

**Testing notes**
The changes should just be reviewed. No other testing is required.

- [ ] This feature is expected to need manual testing.

**Additional context**
N/A

**Comment by joshcoventry** [comment]
Instead of the svg could use this: https://github.com/all-contributors/all-contributors-bot which makes it easy to update the highlighted contributors in the Readme- we could then ask who would like to be highlighted on the readme.

@sareh What do you think?
