### ISSUE TITLE
OD Radio and TV - Additional whitespace below media player on iPhone & desktop Safari

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#6930]
**Describe the bug**

Desktop Safari and mobile Safari are showing a large white space below the player on OD Radio and OD TV. 

**To Reproduce**
Steps to reproduce the behaviour **on mobile:**

1. Go to https://www.test.bbc.com/pashto/bbc_pashto_radio/programmes/p0340yr4 on iPhone / **Safari**
2. Click on "burger" menu in top right hand corner
3. Additional whitespace displayed below player - see screenshot
4. Close the drop down menu
5. Additional whitespace still displayed

Steps to reproduce the behaviour **on desktop:**

1. Go to https://www.test.bbc.com/pashto/bbc_pashto_radio/programmes/p0340yr4 on **Safari**
2. Irregular whitespace should be shown (either below player, or below footer).

**Expected behaviour**
No additional whitespace below the player

**Screenshots**
**Mobile:**

![image](https://user-images.githubusercontent.com/58214768/84936595-64dc4780-b0d2-11ea-89d3-318226de5d0b.png)

**Desktop**

![Screenshot 2020-06-24 at 11 08 08](https://user-images.githubusercontent.com/9042672/85536565-1d424800-b60b-11ea-8b29-4a69f64223c0.png)

**404**

![image](https://user-images.githubusercontent.com/59573468/85542509-0f8fc100-b611-11ea-922a-07b073329d83.png)

**Smartphone (please complete the following information):**
- Device: iPhone
- OS: iOS?
- Browser: Safari
- Version: 

**Testing notes**
- [ ] This bug fix is expected to need manual testing.

**Additional context**
Full Slack conversation https://bbcnews.slack.com/archives/GM323TD51/p1591364362032700

**Comment by pharingee** [comment]
Learnings:
A combination of `min-height: 100vh` on the [Server Component](https://github.com/bbc/simorgh/blob/latest/src/server/Document/component.jsx#L34) and the `flex-grow: 1` on the [On Demand Radio](https://github.com/bbc/simorgh/blob/latest/src/app/pages/OnDemandRadioPage/index.jsx#L50) and [Live Radio](https://github.com/bbc/simorgh/blob/latest/src/app/pages/LiveRadioPage/index.jsx#L32) page components. 
This works well on Firefox, Chrome and Opera but fails unexpectedly on Safari. Removal of `flex-grow: 1` or `min-height: 100vh` removes the space below the player but the footer no longer sticks to the bottom. 

Also, removal of `<ConsentBanner/>` on the [Header Component](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Header/index.jsx#L54) reduces the space below the player although it doesn't take it off completely.

**Comment by rebeccamcginn** [comment]
Closing issue as the upcoming schedule will fix the issue
