### ISSUE TITLE
On Demand TV Pages Lighthouse Tests

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#6945]
**Is your feature request related to a problem? Please describe.**

Lighthouse is an automated tool for improving the quality of web pages. It has audits for performance, accessibility, PWA, SEO etc. We would like to add lighthouse tests for the new On Demand TV Pages.

The mean, standard and minimum values can be set to the same as On Demand Radio for the time being. 

You can choose the URLs to run the tests against but here are two Brand URLs, one RTL and one LTR:
https://www.test.bbc.com/somali/bbc_somali_tv/tv_programmes/w13xttqt
https://www.test.bbc.com/pashto/bbc_pashto_tv/tv_programmes/w13xttn4

**Describe the solution you'd like**

The Lighthouse tests to run against two On Demand TV Brand pages, if this is still the way forward according to bbc/simorgh-infrastructure#1052

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Here is the PR for the On Demand Radio Lighthouse tests: https://github.com/bbc/simorgh-infrastructure/pull/1023

**Comment by gavinspence** [comment]
It would be good to see the lighthouse scores of the TV pages vs OD radio pages before setting the values to ensure they match up. I'm assuming there is a difference in size for players, but don't know how it would impact the scoring.

**Comment by karinathomasbbc** [comment]
There is some Simorgh Tech work in progress regarding lighthouse tests - it might be worth checking to see if this is still required going forward - https://github.com/bbc/simorgh-infrastructure/issues/1052
