### ISSUE TITLE
Update Contributing.md's Getting Started section

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6949]
**Is your feature request related to a problem? Please describe.**
Currently our [Contributing.md file's Getting Started section](https://github.com/bbc/simorgh/blob/latest/CONTRIBUTING.md#getting-started) doesn't point to the 'Good first issue' label https://github.com/bbc/simorgh/labels/Good%20first%20issue 

We should update this section to give better guidance to people who come across Simorgh and want to contribute for the first time.

**Describe the solution you'd like**
We should look at other Open Source projects that do a good job of being inclusive to new contributors, learn of best practice, make the changes to the Contributing.md file. 

**Describe alternatives you've considered**
N/A

**Testing notes**
The content should be reviewed. No testing necessary.

- [ ] This feature is expected to need manual testing.

**Additional context**
N/A

**Comment by amywalkerdev** [comment]
More info in #7241
