### ISSUE TITLE
On Demand TV Media Summary to span 5 columns

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#6951]
**Describe the bug**

The current grid implementation has the summary spanning 6 columns for On Demand TV pages. It should span 5 columns.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/pashto/bbc_pashto_tv/tv_programmes/w13xttn4
2. Open dev tools
3. See that the summary spans 6 columns

**Expected behaviour**

The summary should span 5 columns.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
Sent Ed some links to validate

**Comment by rebeccamcginn** [comment]
Tested on Safari, Firefox and Opera

**Comment by gavinspence** [comment]
Tested on Chrome on iOS - looks good!
