### ISSUE TITLE
jest dom: toBeEmpty() is being deprecated

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#6959]
**Describe the bug**
https://github.com/testing-library/jest-dom#tobeempty
Testing-Library have noted that this function is being deprecated

**To Reproduce**
Steps to reproduce the behaviour:

1. Open terminal and `cd simorgh`, ensure you have latest `git pull`
2. Run `npx jest src/app/containers/RadioSchedule/Canonical/index.test.jsx`
3. See terminal console for warnings:
![image](https://user-images.githubusercontent.com/30599794/85047604-f8bd1a80-b189-11ea-8afe-d004dcf982ab.png)

**Expected behaviour**:
Testing-library/jest-dom suggests to use `toBeEmptyDOMElement` instead of `toBeEmpty` function.

- Update the occurrences of `toBeEmpty` to be `toBeEmptyDOMElement` and the console warning should not persist. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by minimalsm** [comment]
I could take this if no one is working on it? @thekp

**Comment by thekp** [comment]
@minimalsm Yeah, feel free to pick up any issue that has no one assigned to it 👍
