### ISSUE TITLE
Update resource hints to include domains that are not currently included

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6960]
**Is your feature request related to a problem? Please describe.**

Screenshot of the webpagetest filmstrip for the hindi front page https://www.bbc.com/hindi run on a Moto G (Gen 1).

![webpagetest-hindi-frontpage-filmstrip](https://user-images.githubusercontent.com/3028997/85046556-81d35200-b188-11ea-9ad2-8562075046e5.png)

Screenshot of the waterfall for the hindi front page https://www.bbc.com/hindi
<img width="800" alt="Screenshot hindi front page waterfall" src="https://user-images.githubusercontent.com/3028997/85046611-9283c800-b188-11ea-97d2-aa498f652618.png">

[Link to WebPageTest results](https://www.webpagetest.org/video/compare.php?tests=200618_N9_ddc714c2d304a0497b3ba160ecd9575b-r:1-c:0)

We should improve page performance. There are some quick wins. 

**Describe the solution you'd like**
- Update resource hints to include domains that are not currently included, like the cookie oven domain
- . 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Unit tests for changes in PR.
Run test on WebPageTest again after the change. 

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by gavinspence** [comment]
Check whether https://static.files.bbci.co.uk is included or not

**Comment by jroebu14** [comment]
I discovered that the cookie oven url needs updated in resource hints https://www.bbc.com/cookieoven and https://www.test.bbc.co.uk/cookieoven on test.

cc @aaronmoran

**Comment by amoore108** [comment]
> I discovered that the cookie oven url needs updated in resource hints https://www.bbc.com/cookieoven and https://www.test.bbc.co.uk/cookieoven on test.
> 
> cc @aaronmoran

Thanks @jroebu14 👍🏼 

https://static.files.bbci.co.uk appears to be being used in Test and Live. It is set via the `process.env.SIMORGH_PUBLIC_STATIC_ASSETS_ORIGIN` value

**Comment by amoore108** [comment]
Are there any other domains that we should add @gavinspence?

Our current list:
https://ichef.bbci.co.uk
https://gel.files.bbci.co.uk
https://ws-downloads.files.bbci.co.uk
https://www.bbc.com/cookieoven (also the Test version)
https://www.bbc.co.uk/cookieoven (also the Test version)
https://static.files.bbci.co.uk (also the Test version)
https://a1.api.bbc.co.uk/hit.xiti? (also the Test version)

Having a read at a previous conversation https://github.com/bbc/simorgh/pull/7469, there are a few that we **shouldn't** add.
