### ISSUE TITLE
Lighthouse Recommendation - Serve images in next-gen formats

### ISSUE THREAD

**Issue by FK78** [bbc/simorgh#6990]
**Is your feature request related to a problem? Please describe.**
Parent issue: https://github.com/bbc/simorgh-infrastructure/issues/1088

We serve images in JPG format, but formats like JPEG 200, JPEG XR and WebP often provide better compression, which means faster downloads and less data consumption.

A run against https://www.test.bbc.com/arabic/articles/c1er5mjnznzo:

<img width="630" alt="Screenshot 2020-06-24 at 16 45 34" src="https://user-images.githubusercontent.com/34196381/85587971-c7cd6180-b631-11ea-9552-4ebeec96b166.png">

Report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.test.bbc.com%2Farabic%2Farticles%2Fc1er5mjnznzo

**Describe the solution you'd like**
Serve images in next-gen formats.

More information: https://web.dev/uses-webp-images/

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by minimalsm** [comment]
One thing to consider is that WebP does not support progressive rendering of images.

[More info](https://blog.cloudflare.com/parallel-streaming-of-progressive-images/#:~:text=WebP%20doesn't%20even%20support,appears%20to%20load%2050%25%20faster.)

**Comment by chris-hinds** [comment]
Blocked until Image Chef supports WebP Images
