### ISSUE TITLE
Add Lighthouse as an npm script

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#70]
Lighthouse is a tool that can be run within Google Chrome's Dev Tools. The same tool can also be run via CI. This task is to add the Lighthouse Best Practice tool as a separate npm script task `lighthouse`. We can do this by installing lighthouse-cli as a dependency.

https://github.com/googlechrome/lighthouse

There is configuration information here: https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md
This task will not include running the task as part of the build pipeline, since our page does not meet our threshold (90%) and will fail until we add a manifest with a short_name.

Outcome
When we run `npm run lighthouse`, we see the results of the Lighthouse Best Practice tests in the cli.

**Comment by PaulChinkwende** [comment]
@benjaminhobbs @jtart @BogdanDogaru 
I have lighthouse running as a npm script task against 'best-practices' audits when we run npm run lighthouse however output to the command line gives us a load of either HTML or Json(whichever we choose) which is extremely long and not really readable.

**Comment by jtart** [comment]
If we are not doing anything with the results atm, and JSON on the command-line is not really readable until it is parsed, I would recommend outputting the results as HTML and passing `--view` to automatically open the audit.

Then just need to make sure the static HTML files are ignored from git.

**Comment by PaulChinkwende** [comment]
Okay. 
For the future it might be possible to run a check against the ```lh-gauge__percentage``` score from the generated html doc against the one we expect in our latest branch to ensure that it is either equal or greater before allowing a PR to be merged.
