### ISSUE TITLE
Canonical Ads bug on Firefox Nightly

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#7000]
**Describe the bug**
When visiting a page with ads on the test environment in a _**Firefox Nightly**_ browser, I see an error and the ad does not load.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/mundo?adUnit=/4817/bbccom.test.site.flash/news_homepage_int in a Firefox browser
2. Open console
4. See this error in the console `Uncaught (in promise) Error: Failed to load https://securepubads.g.doubleclick.net/tag/js/gpt.js`

We already have the domain https://securepubads.g.doubleclick.net is already in the CSP header. 

**Expected behaviour**
To not see a console error. 

**Screenshots**
<img width="1437" alt="Screenshot mundo canonical add firefox bug" src="https://user-images.githubusercontent.com/3028997/85426831-e4569480-b572-11ea-99b5-400d0a781b57.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser _**Firefox nightly**_
- Version _**79.0a1 (2020-06-23)**_

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
N/A

**Comment by minimalsm** [comment]
I was unable to replicate this. Seems to be showing it fine on my end.

OS: Mac OS Catalina
Browser Firefox
Version 77.0.1

<img width="1435" alt="Screenshot 2020-06-23 at 20 07 41" src="https://user-images.githubusercontent.com/62268199/85447399-79668700-b58d-11ea-9dc8-e85a073f19e1.png">

**Comment by sareh** [comment]
Thank you, @minimalsm. 

I was just going to reply that this is not a bug with Firefox 77.0, only Firefox Nightly 79.0a1.  

I will keep this issue open so we can see if the issue is fixed in a future build of Firefox Nightly.

**Comment by OlgaLyubin** [comment]
This problem seems to be resolved now in the new version of FireFox Nightly (80.0a1). Ad is showing and no more console error.

<img width="1224" alt="Снимок экрана 2020-07-02 в 17 05 58" src="https://user-images.githubusercontent.com/17802955/86384252-65561000-bc86-11ea-8c40-3002166abfcc.png">

**Comment by itimirichard** [comment]
I can also confirm that I cannot see that error in the console for on Firefox Nightly (80.0a1) and that the ad is visible as well.

<img width="1431" alt="Screenshot 2020-07-03 at 5 15 55 PM" src="https://user-images.githubusercontent.com/34133081/86485738-6738d580-bd51-11ea-935f-01d913b04f72.png">

**Comment by OlgaLyubin** [comment]
Thanks for checking @itimirichard . I will close the issue now then 👍
