### ISSUE TITLE
IDT2 Image Fallbacks do not respect renderer_env parameter

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#7006]
**Describe the bug**
_Please note this is not a user facing bug but an issue for testing_

When Story pages with IDT2 includes are viewed using the `renderer_env` query parameter, the images will often not load. On canonical you see the `alt` text rather than the image (please note the `alt` text also has escaping issues described here: https://github.com/bbc/simorgh/issues/6998):
https://www.test.bbc.com/gahuza/48118437?renderer_env=live
> <img width="657" alt="image" src="https://user-images.githubusercontent.com/9645462/85512928-5a4e1080-b5f2-11ea-9ef0-7624a2855be5.png">

On amp you see a blank space where the image should be:
https://www.test.bbc.com/gahuza/48118437.amp?renderer_env=live

On both platforms the images fail to load from a [test location](https://www.test.bbc.com/ws/includes/idt2/23bb773f-2408-4870-9f7a-0ba861f321ff/image/816) but are available from a [live url](https://www.bbc.com/ws/includes/idt2/23bb773f-2408-4870-9f7a-0ba861f321ff/image/816).

The images should be loaded from environment the `renderer_env` has been set to as applied in this issue: https://github.com/bbc/simorgh/issues/6501 

**To Reproduce**
Steps to reproduce the behaviour:

1. Visit https://www.test.bbc.com/gahuza/48118437?renderer_env=live or https://www.test.bbc.com/gahuza/48118437.amp?renderer_env=live
See issues described above for canonical and amp respectively

**Expected behaviour**
Image should load successfully on both platforms

**Testing notes**
Modify https://github.com/bbc/simorgh/blob/latest/envConfig/local.env#L2 to https://www.bbc.com to test the above urls locally.

- [x] This bug fix is expected to need manual testing.

**Additional context**
One suggested solution is to extract the `renderer_env` logic from [this function](https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js#L19..L45) and move it to its own utility in the `/include` directory.

That way the logic can be shared by [getImageBlock](https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/getImageBlock.js) and the [include converter](https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/index.js) itself.

**Comment by joshcoventry** [comment]
This feature is stable and we're unlikely to revisit this, so I am closing it.
