### ISSUE TITLE
Get renderer_env parameter to work locally

### ISSUE THREAD

**Issue by paruchurisilpa** [bbc/simorgh#7009]
**Is your feature request related to a problem? Please describe.**

Currently `renderer_env` doesn't work for localhost

**Describe the solution you'd like**

- Currently localhost points to local data
- If we want to point localhost to test or live , the only ways to do it as follows which can be a little tedious 👍 
    - Go to the page locally & copy the json into your local /data/nepali/<page>.json file and it should work.
    - Open `src/app/routes/utils/fetchPageData/index.js` and change line 22-24 to be: `const baseUrl = "https://www.bbc.com"` or  `"https://www.bbc.com"`;
- `renderer_env` currently works on test but doesn't seem to work on `localhost`.

**Testing notes**
Few example URL's:

- localhost:7080/arabic?renderer_env=test should work
- localhost:7080/arabic?renderer_env=live should work

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Comment by simonsinclair** [comment]
Hi Silpa, @hindsc52 and I have been investigating this:

`renderer_env` will not have any effect when used on the dev-server (`npm run dev`) – this is expected. To use `renderer_env` on your local machine, you will need to create a Production build by running either:

_Test_
```sh
npm run build:test:debug
npm start
```

_Live_
```sh
npm run build:live:debug
npm start
```

I have raised a PR (here: https://github.com/bbc/simorgh/pull/7038) to resolve the CSP errors you will see with the above examples and add the necessary documentation to guide people wanting to test the app locally with test or live data.

**Comment by paruchurisilpa** [comment]
Thanks @simonsinclair
