### ISSUE TITLE
Media player on TV pages show cut off play controls

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#7010]
After playing content on the ondemand TV page, the player control looks clipped. Tested on Chrome (iOS)

![IMG_6490](https://user-images.githubusercontent.com/52488258/85535295-f5061980-b609-11ea-8e0a-bf3c8c0cfc06.PNG)

**Comment by LilyL0u** [comment]
It also looks like this on Android Chrome, Firefox, Opera Mini and Opera, except the scrub bar is not cut off, just the play and full screen buttons.

**Comment by LilyL0u** [comment]
Is this fix expected to be on test now?

**Comment by LilyL0u** [comment]
www.test.bbc.com/somali/bbc_somali_tv/tv_programmes/w13xttqt
