### ISSUE TITLE
Improve Canonical IDT2 Include fallback rendering

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#7016]
**Is your feature request related to a problem? Please describe.**
Following the completion of https://github.com/bbc/simorgh/issues/6837, we need to make some small improvements to how the fallback image displays for Canonical IDT2 includes. Two improvements have been identified:
1. Add spacing beneath the image.
2. Ensure the image selected is the appropriate size for the breakpoint - currently the largest image size is selected regardless of the breakpoint.

**Describe the solution you'd like**
- Apply spacing equal to `GEL_SPACING_DBL` to the bottom of the Include.
- Use a mobile first approach for sizing the default image.

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Not going to do.

**Comment by simonsinclair** [comment]
![](https://media.giphy.com/media/9Y5BbDSkSTiY8/giphy.gif)

**Comment by aeroplanejane** [comment]
_We're_ not going to do, but please don't let me stop you guys!!

**Comment by rhenshaw56** [comment]
![Alt Text](https://media.giphy.com/media/aDcvK946SC3GwCqLk8/giphy.gif)
