### ISSUE TITLE
Accessibility stylesheet results in invisible news stories

### ISSUE THREAD

**Issue by ssb22** [bbc/simorgh#7018]
I am hoping to fix this on my side in my [stylesheets for low vision](http://ssb22.user.srcf.net/css/) project, but I may need a hand understanding why the BBC's website makes my CSS go wrong.

Some people have medical conditions which makes them require dark mode.  Others need giant print and/or simplified layouts.  I provide CSS to do both, and for this issue I am referring to my CSS that's meant to change a site's colours without changing size or layout.

Here is how BBC News looks in Firefox today, with my colour-change-only CSS installed as `userContent.css`:
![image](https://user-images.githubusercontent.com/2261921/85578589-17139200-b632-11ea-9b9a-fbf55afa19c9.png)

and then when I go into the browser developer tools, I can see there are some `div` elements that have been rendered as black on black:
![image](https://user-images.githubusercontent.com/2261921/85578768-3ca09b80-b632-11ea-9d81-ffebb2a3cf3d.png)

and this isn't making any sense, because under "computed" styles nothing seems out of the ordinary (no `position` sending it somewhere else, no `z-index` hiding it, no obvious extra element plonked over the top of it, no `display: none` or `visibility: hidden` taking effect, etc).

Normally when I'm up against stuff going invisible on websites it turns out to be because they're using the horribly inaccessible method of displaying essential content with `background-image` (now I'm not against using `background-image` for *decoration*, but it shouldn't be used for essential content for obvious reasons).  That would affect screenreader users and it also affects my CSS files because I have to disable *all* backgrounds everywhere for safety (since I cannot positively specify a selector for each and every large bright background on the Web, and CSS does not provide a way to say "disable all backgrounds *except* these ones I know are OK", therefore I have to disable all); in some cases I can manually reinstate a particular site's controls by adding special-case rules back into my CSS but obviously I'd need some way of knowing what to display there and I wouldn't be able to rewrite every individual story on a news site.  But in this case I don't see any use of `background-image`, and the `div` does contain meaningful markup which I can inspect but not display:
![image](https://user-images.githubusercontent.com/2261921/85581200-488d5d00-b634-11ea-884d-5a2944b69009.png)

So what I'm trying to figure out is **what extra code should I put into my CSS to mitigate this problem** (as I am very much in favour of fixing things on the side of our tools rather than expecting every Web developer on the planet to provide us with separately-developed dark modes, which in any event would not interact well with having one always switched on in the browser and unfortunately there's no way to tell my CSS "detect when the site's doing it by itself and back off").  But the reason why I'm raising it as an issue *here* is in the hope of one of the BBC developers perhaps being able to give me a hint that would help me better understand how it's *supposed* to work.  Thanks.

**Comment by ssb22** [comment]
A similar problem occurs on http://www.bbc.co.uk/opensource/ where the descriptions of the individual projects are not visible.  By using the browser's developer tools to add `border` styles to various elements, I was able to establish that the `<div class="gel-media gs-o-faux-block-link homepage-promo">` is displaying, but neither of its two child `div`s are displaying (although they *are* being allocated space in the layout).

**Comment by sareh** [comment]
@ssb22 Thank you for raising this issue.

The BBC has multiple different technical stacks and the News front page (https://www.bbc.co.uk/news) and the Open Source page (https://www.bbc.co.uk/opensource/) are not pages that are served by this Simorgh Repository. 

Nevertheless, before passing this issue onto the relevant team, a few of us have tried to replicate this behaviour.

In my latest version of Firefox (version 77.0.1), I set `about:config` value of `toolkit.legacyUserProfileCustomizations.stylesheets` to `true` and added the linked stylesheet as `userContent.css` to the relevant directory.

Although the layout does not appear the same as that of the live site, I can see the images and headlines displayed. There are screenshots below.

Screenshot showing https://www.bbc.co.uk/news - the top of the page, showing the cookie banner and navigation
<img width="1437" alt="Screenshot of the top of the news front page" src="https://user-images.githubusercontent.com/3028997/85587440-b0927200-b639-11ea-81bb-82fa6fd3fb2d.png">

Screenshot showing https://www.bbc.co.uk/news - lower down the page, with images and headlines
<img width="1440" alt="Screenshot of the news front page - lower down the page" src="https://user-images.githubusercontent.com/3028997/85587436-af614500-b639-11ea-9e12-975ed166e824.png">

I am not sure of the cause of the issue you have raised. Could you please share the version of the browser you're using as well as the operating system of your device?

**Comment by ssb22** [comment]
Thanks Sareh.  Sorry I should have been clearer in my second paragraph: I provide *two* types of CSS files, one to change the layout, the other to *not* change the layout, and it's the one that *doesn't* change the layout that I was having trouble with.  I.e. this one: http://ssb22.user.srcf.net/css/0.css
This is on Firefox 77.0.1 on Linux (Fedora 32).

**However** I have now figured out how to fix it on my side.

The problem was due to an interaction between the BBC's `enhanced.css` rule for `.gs-o-faux-block-link .gs-o-faux-block-link__overlay-link::before` (which includes `position: absolute` and `z-index: 1`), and my rule for `a:before` which set background to black.  The BBC's rule was effectively making the pseudo-element before the `overlay-link` into a separate item, positioned **over the top** of the link, and then when I came along and set background to black, this pseudo-element effectively became a black box hiding the whole thing.

So I should use `transparent` instead of `black` on my `:before` and `:after` overrides.

(The reason why I had that rule at all is because I didn't want web designers to override our dark background by placing some `content` into the `::before` pseudo-element of an `a` element and setting bright background on *that*.  But as I'm already setting the *page* background to `black`, there's no reason why I can't use `transparent` for the `:before` and `:after` elements, making them more compatible with designs that use `position: absolute` on them.  And the reason why you didn't see the same bug on my *other* stylesheets—the ones which *do* change the layout—is because the *layout-changing* stylesheets will *override* that `position: absolute`, thereby dodging the issue, whereas the stylesheets that change only the colours will leave the `position` as it was.)

OK that's enough being Inspector Morse for one day: I'll get a fix out in the morning and link it here for completeness.  (This heat wave is making me dizzy.  I'd normally find an air-conditioned computer lab to hide in under these circumstances, but what with the lockdown I've just had to keep going in the heat.)

**Comment by ssb22** [comment]
fixed in https://github.com/ssb22/css-generator/commit/e92d3ccbeca905aa17343c8c7a57663f3876ec64 (for which I meant to write a better commit summary than "update", but a typo in my command (introduced by MHonArc's rendition of the email to myself, of all things) resulted in the commit message not actually being passed to my update scripts, so it just put in its default one... oh well)
