### ISSUE TITLE
Avoid an excessive DOM size

### ISSUE THREAD

**Issue by FK78** [bbc/simorgh#7020]
**Is your feature request related to a problem? Please describe.**
A large DOM will increase memory usage, cause longer style calculations and produce costly layout reflows.

A run against https://www.test.bbc.com/arabic:

<img width="641" alt="Screenshot 2020-06-24 at 17 57 07" src="https://user-images.githubusercontent.com/34196381/85603487-f0f4ee80-b63f-11ea-8d9b-59b92c993cec.png">

Full report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.test.bbc.com%2Farabic

**Describe the solution you'd like**
Consider using a “windowing” library like `react-window` to minimize the number of DOM nodes created if you are rendering many repeated elements on the page. [Learn more](https://web.dev/virtualize-long-lists-react-window/?utm_source=lighthouse&utm_medium=lr). Also, minimize unecessary re-renders using shouldComponentUpdate, PureComponent, or React.memo and skip effects only until certain dependencies have changed if you are using the Effect hook to improve runtime performance.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
This is currently just a warning from LH, The DOM size is currently well below LH's avoidable limit of 1500 DOM nodes,
