### ISSUE TITLE
Issue with bumping eslint-plugin-jsx-a11y above 6.2.3

### ISSUE THREAD

**Issue by chewu** [bbc/simorgh#7036]
**Describe the bug**
Upgrading to anything above 6.2.3 for eslint-plugin-jsx-a11y to 6.3.1 causes an issue for the licence of language-subtag-registry

```Problems with the licenses for these dependencies:
  language-subtag-registry@0.3.20
    License:     ODC-By-1.0
    Repository:  https://github.com/mattcg/language-subtag-registry
    Publisher:   undefined
    Url:         undefined
```

#6953

> @chewu I'm not comfortable adding an exception for that package without us getting legal advice, if the older version doesn't have any licence issues then let's pin back. Please could you create an issue to capture the task that we need to go and get this licence reviewed/approved before we can upgrade eslint-plugin-jsx-a11y?

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
This has already been fixed
