### ISSUE TITLE
On Demand Radio - Burmese - no space between hero image and text on Firefox

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#7041]
**Describe the bug**
Spacing between image & text is incorrect on Burmese for On Demand Radio on Firefox (Mac)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/burmese/bbc_burmese_radio/programmes/p030z23n
2. Note the spacing between the hero image and text

**Expected behaviour**
Spacing to be correct as per Zeplin 

**Screenshots**
Desktop
![image](https://user-images.githubusercontent.com/58214768/85890216-d0b26480-b7e4-11ea-8de0-17d365610d8e.png)
Looks OK on mobile with no image
![image](https://user-images.githubusercontent.com/58214768/85890231-dc059000-b7e4-11ea-9b8a-74c85eb3abb9.png)

**Desktop (please complete the following information):**
- OS: Mac
- Browser: Firefox
- Version

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by minimalsm** [comment]
This seems to be specific to Firefox. Working as expected on Safari and Brave Browser.

**Comment by LilyL0u** [comment]
Confirmed fixed by Ed and me
