### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#705]
**Is your feature request related to a problem? Please describe.**
We should have favicons, or at least one BBC one. Ask UX, I found one here: http://newsvote.bbc.co.uk/favicon.ico

**Describe the solution you'd like**
Have a favicon

**Comment by jtart** [comment]
We should use this favicon https://www.bbc.com/favicon.ico

**Comment by bcmn** [comment]
As discussed on Slack we wish to be consistent with the rest of the website, & use https://www.bbc.com/favicon.ico.
