### ISSUE TITLE
Spacings + Padding OD TV

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#7060]
**Describe the bug**

Spacing above the player should be:
240 - 399px. 8px 
400 - 1007px. 16px. 
1008+ 40px

Spacing below the player at 1008+ should be 40px

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/somali/bbc_somali_tv/tv_programmes/w13xttqt
2. Inspect element
4. See padding/spacing errors

**Expected behaviour**

**Screenshots**
Implementation to match designs

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
Consult Ed if questions arise

**Comment by LilyL0u** [comment]
Confirmed fixed by Ed
