### ISSUE TITLE
Thurs 2nd July - On Demand Radio Services Batch #2 Live

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#7064]
Mozart PR: https://github.com/bbc/mozart-routing/pull/1428

**Is your feature request related to a problem? Please describe.**
Put the remaining On Demand Radio services live:
- afrique/bbc_afrique_radio
- amharic/bbc_amharic_radio
- bengali/bbc_bangla_radio
- burmese/bbc_burmese_radio
- gahuza/bbc_gahuza_radio
- korean/bbc_korean_radio
- kyrgyz/bbc_kyrgyz_radio
- nepali/bbc_nepali_radio
- persian/bbc_persian_radio
- persian/bbc_dari_radio
- sinhala/bbc_sinhala_radio
- swahili/bbc_swahili_radio
- tamil/bbc_tamil_radio
- tigrinya/bbc_tigrinya_radio
- urdu/bbc_urdu_radio
- uzbek/bbc_uzbek_radio

**Describe the solution you'd like**
- Mozart routing

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
This is done!
