### ISSUE TITLE
Determine location of user from headers in Simorgh

### ISSUE THREAD

**Issue by benjifellows** [bbc/simorgh#7066]
**Is your feature request related to a problem? Please describe.**

**This issue should be paired/swarmed on**

We need to know where the user is in order to determine whether or not we should show them ads.

We do not want to perform any unnecessary API calls in order to determine this.

We get information from where the user is from headers.

**Describe the solution you'd like**
- For our initial release, we will look at the headers `X-Ip_is_advertise_combined` and `X-Ip_is_uk_combined` (for when traffic does not come via Fastly), or `X-BBC-Edge-IsUK` (for when traffic does come via Fastly). This is because Fastly currently does not add the headers used to make decisions about advertising that come from the GTM's. There is work in progress for this to happen.
- We will use these headers to decide on the server whether or not we should be rendering ads for that user.
- We can read these headers using Express' `req.headers` method
- Based on the values of these headers, we can set a boolean that can be passed into the application to be used (in some way) to decide whether a user should see ads based on location.
- This value should persist across client-side renders

- Mozart will need to vary on these headers and pass them through to Simorgh: https://github.com/bbc/simorgh-infrastructure/issues/1118
- We will continue to allow the GNL code to perform a client side lookup, as a failsafe in the case that these headers have misidentified a user’s location before the GTMs become the origin for Fastly.

_Toggle Flow for Canonical Pages_
![image](https://user-images.githubusercontent.com/54984834/86130858-b5916e80-badc-11ea-8953-ebe43b0d2544.png)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

- An easy way to test locally during development is to manually set these headers ourselves to ensure we see the correct output. As these are added by either the GTMs or Fastly, you will not see these headers locally when running Simorgh.
- We will want to test this on the test environment, we can use a proxy to ensure the user is in a place that will have different combinations of headers. We will not be able to do this until https://github.com/bbc/simorgh-infrastructure/issues/1118 is complete.
- Is there an override or method we can use to test this without proxies? Update, the PR for this has added the query parameter `force-ads=true`.
- We can set these headers in unit and integration tests.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
For context on the decisions made around how we identify where the user is: https://paper.dropbox.com/doc/GeoIP-Lookups-and-World-Service-Sites--Azd1UCuXEFF~fOT4tr6wBxbDAg-VEm9qMgSG7OlNjM5rhvuT?_tk=slack_preview

**Comment by thekp** [comment]
The work for this is complete.

To view Ads on canonical.
TEST & LIVE, you have to be outside the UK

LOCAL, you can use modHeader to add BBC-Adverts with value of true. 

Additional docs here: https://github.com/bbc/simorgh/pull/7489
