### ISSUE TITLE
Update Live Radio Title for Arabic

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#7071]
**Is your feature request related to a problem? Please describe.**; 
The arabic service want to update the page title on their live radio page: https://www.bbc.com/arabic/bbc_arabic_radio/liveradio to `مباشر: إذاعة بي بي سي عربي` so that it performs better in Search 

**Describe the solution you'd like**
We will update our Ares live radio config script to update the changes, and then ask ARES to update the in the Live Radio S3
document. 
The title comes from the liveradio endpoint in ARES: https://ares-api.api.bbci.co.uk/api/ws-media/liveradio/bbc_arabic_radio
We should see the changes propagated to the Promo.name 
and the changes will be propagated to analyticsLabel.pagetitle 

When I visit https://www.bbc.com/arabic/bbc_arabic_radio/liveradio
the the h1 will be `مباشر: إذاعة بي بي سي عربي`
and the page title will be `مباشر: إذاعة بي بي سي عربي - BBC News Arabic`

**Describe alternatives you've considered**
This could be overwritten in our own service configs. 

**Testing notes**
What could go wrong? Please don't take that as a challenge.

**Additional context**

**Comment by gavinspence** [comment]
Raised with AReS - https://jira.dev.bbc.co.uk/browse/ARES-1316
It's a one liner from their side so they'll pick it up when they can.

**Comment by aeroplanejane** [comment]
@ryanmccombe can you update your jist file? 
I've updated the text here: https://confluence.dev.bbc.co.uk/display/WSMEDIA/Live+Radio+%7C+Services 
We'll track this in JIRA so you can close when the jist file is updated. Thanks!

**Comment by aeroplanejane** [comment]
Thanks @ryanmccombe  - I've checked this on LIVE and editorial have reviewed. All good. Closing. 
https://www.bbc.com/arabic/bbc_arabic_radio/liveradio
