### ISSUE TITLE
Amp player - Scrub bar current-position-indicator is cut off

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#7073]
On amp, on OD Radio and Live Radio pages, the scrub bar current position indicator/dogegg is cut off:

![Image 30-06-2020 at 11 52](https://user-images.githubusercontent.com/54575620/86119279-12cff480-baca-11ea-8ea9-a25bf555d731.jpg)

It is fine on canonical

On the galaxy s10+ you can also see the duration cut off
![Image 30-06-2020 at 14 08](https://user-images.githubusercontent.com/54575620/86129845-3b141f00-badb-11ea-826f-149b8681b25b.jpg)

**Comment by RichardPK** [comment]
Bloody misbehaving dogegg
