### ISSUE TITLE
Check the Global Ad Flagpole value in our AMP access check

### ISSUE THREAD

**Issue by benjifellows** [bbc/simorgh#7077]
**Is your feature request related to a problem? Please describe.**
When rendering an AMP advert, we need to perform a check on the Global Ad Flagpole to see whether we should be showing ads.

This is reliant upon the completion of https://github.com/bbc/simorgh-infrastructure/issues/1068

**Describe the solution you'd like**

https://github.com/bbc/simorgh/blob/62ff6d33c9e8a4c24d813f380716f9e57c4be9eb/src/app/containers/Ad/Amp/index.jsx#L83
should just change to
```jsx
<div amp-access="toggles.ngasFlagpoles.adverts && toggles.ads.enabled" amp-access-hide="true">
````
_**Confirm these are the correct values once https://github.com/bbc/simorgh-infrastructure/issues/1068 is complete**_

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

We're integrated with the test config service locally and on test, and with the live config service on live.
We can turn the test flagpole OFF and ensure that we don't see AMP ads.

**Additional context**

**Comment by tochwill** [comment]
Blocked on bbc/simorgh-infrastructure#1068

**Comment by tochwill** [comment]
No longer going to be integrating with the global flagpole, at least initially. See https://github.com/bbc/simorgh-infrastructure/issues/1068#issuecomment-657429335 for an explanation.
