### ISSUE TITLE
Investigation: Avoid content shifting for AMP Ads when Ads are not shown

### ISSUE THREAD

**Issue by benjifellows** [bbc/simorgh#7080]
**Is your feature request related to a problem? Please describe.**
When Ads are rendered, we render a blank space in the position on the page we want the Ad to appear. When we do not want to render an Ad - on Canonical the behaviour is that we can make all of the decisions we have to make in order to render an ad slot on the server - toggles, flagpole, and location. This means we know if we should be rendering an ad before we render the page, so can reserve the space is needed, but not if no advert should be rendered.

However, when we do NOT want to render an Ad on AMP we run into the issue that we cannot make these decisions until we are on the client - we have to check the toggles, flagpole, and geoIP of the user after the initial page has been rendered. We will know if the service should have ads, but not if the user should be seeing ads at that time.

The current options for this are:
- Reserve the space for an advert for that service, and not show anything in the blank space if either the config service or geo ip lookup says we shouldn't show an advert.
- Show nothing, and then render the advert in afterwards, causing content shifting

Neither of these are preferrable, so we need to investigate a potential cleverer solution for rendering an AMP page without Ads or blank space whilst avoiding content shifting.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by itimirichard** [comment]
From my research so far, I haven't found a cleverer way to do this without affecting the user's experience. Another alternative would be not to render any AMP ads above the fold on page load (this is a popular opinion and generally considered [a best practice](https://amp.dev/documentation/guides-and-tutorials/develop/monetization/#best-practices)). This helps the user to start consuming content while loading ads in parallel (outside the viewport) without causing visible content reflow above the fold.

**Comment by itimirichard** [comment]
I've created this [doc](https://paper.dropbox.com/doc/Investigation-Content-Shifting-for-Amp-Ads--A4RfxDzMNujUF8x76keYwpF~Ag-Rki4cZvd0cN56zFHuyB85) to document my findings as well as the current options we have along with their respective trade-offs.

**Comment by itimirichard** [comment]
From the paper doc shared above, we've chosen to go with solution 1; which is to reserve a space for Ads. I've created this issue https://github.com/bbc/simorgh/issues/7380 to implement this solution.
