### ISSUE TITLE
Investigation: Allow user to revoke consent for personalisation on AMP

### ISSUE THREAD

**Issue by benjifellows** [bbc/simorgh#7086]
**Is your feature request related to a problem? Please describe.**

[**OVERVIEW**](https://paper.dropbox.com/doc/Consent-in-Simorgh--A26Qt006AShY~27zZ96mcOLdAg-WB2lwaOirai1bEgkKSC36)

### Canonical
**Providing Consent**
On a user’s first visit to a BBC Canonical webpage (regardless of whether or not a Simorgh page), they will see the ‘Privacy Banner’ - this informs them that we have a privacy policy and that it has been updated, and offers the chance to click through to read the policy.

Once it has been displayed, a cookie called `ckns_privacy` is created, with the value indicative of the version of the Privacy Banner the user saw (e.g. `july2019`) with an expiry date one year in the future.  So long as this cookie remains, and the value matches the latest version of the privacy banner, the user will not see the privacy banner again.

The user does not need to click on this banner - it being displayed is sufficient to set the cookie.

**Revoking Consent**
The user can, at any time, visit the central BBC consent pages and change their settings, or they can delete their local cookies to trigger the banners to display again.

In addition, following CCPA, we have added a link to the footer of all Simorgh pages which goes to the central BBC consent pages, reading `AdChoices / Do Not Sell My Info` - this link text is always displayed in English regardless of the service language, as it is targeting users in California who are assumed to be able to read English.

### AMP

**Providing Consent**
Our AMP pages do not have access to the same cookies as above.  This is primarily because the pages are most often served from the Google AMP cache, and so served on a non-BBC domain - standard browser security patterns will not grant a webpage on a third-party domain access to bbc.com cookies.

When the Cookie Banner is accepted on AMP, AMP itself (the code provided for the platform by Google) records in Local Storage (a form of browser data storage similar to, but distinct from, cookies) that the user has consented.

**Revoking Consent**
We do not offer a mechanism for the user to withdraw consent on AMP.

**Describe the solution you'd like**
We need a way for users to easily revoke their consent for personalised ads on AMP.

- The outcome of this investigation ticket should be an agreed solution that we can build that allows users to revoke their consent on AMP pages rendered by Simorgh.

- If the user is outside of the EEA (+ UK), they can be opted in by default, but still need a way of revoking their permission, this is specifically for californian legislation.

- As an alternative if this isn't possible, could we add california to the list of locations that we show the cookie banner? I know that amp-geo provides california as a location (probably for this purpose).

- Or should we show the banner everywhere?

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
There is a ‘post prompt’ UI specified in the documentation: https://amp.dev/documentation/components/amp-consent/#post-prompt
​​
​​I haven’t tried it out yet, but this would need to take the form of something like a persistent button, that could be selected to show a UI that would allow the user to remove their consent.

**Comment by hotinglok** [comment]
Closing due to investigation being concluded with a method to revoke AMP consent. AMP stores consent preferences as a hash in local storage which can be written and overwritten to change the choice of the user. See #7316 for more details
