### ISSUE TITLE
Upgrade to Styled Components V4

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#709]
There doesn't seem to be a set release date being discussed for V4 yet, as far as I found with a quick look.

Initial work for switching is on the [`styled-components-v4` branch](https://github.com/bbc/simorgh/tree/styled_components_v4).

At the moment there seems to only be one blocker when attempting to switch to the current beta:

* Waiting on `[jest-styled-components](https://github.com/styled-components/jest-styled-components)` to support V4, see [this issue](https://github.com/styled-components/jest-styled-components/issues/191)

**Comment by dr3** [comment]
Done https://github.com/bbc/simorgh/blob/latest/package.json#L125
