### ISSUE TITLE
See Also Images look Blurry on MAPs and STYs on Desktop

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#7090]
**Describe the bug**
See also promos are displaying blurred images on desktop. 

We appear to be picking up the 320px iChef version and expanding it, rather than picking up the larger size and reducing it depending on screen. 

e.g. 
We are displaying https://ichef.bbci.co.uk/news/320/cpsprodpb/0B0A/production/_113162820_einiaixxyaalzlc.jpg
for this URL https://www.bbc.com/pidgin/media-53231363 
We should instead take the larger image and then reduce it depending on screen size: http://c.files.bbci.co.uk/0B0A/production/_113162820_einiaixxyaalzlc.jpg

The full sized image file is available within the see-also promos in the ares response
` "indexImage": {
              "altText": "Npower application form",
              "caption": "Npower registration portal 2020 batch C",
              "copyrightHolder": "Twitter/npower_ng",
              "height": 540,
              "href": "http://c.files.bbci.co.uk/0B0A/production/_113162820_einiaixxyaalzlc.jpg",
              "id": "113162820",
              "path": "/cpsprodpb/0B0A/production/_113162820_einiaixxyaalzlc.jpg",
              "subType": "index",
              "type": "image",
              "width": 960
            },`

**To Reproduce**
Steps to reproduce the behaviour:

1. Using desktop on a machine with full HD or lower resolution
Go to a STY page with Related Content (see alsos): https://www.bbc.com/pidgin/tori-53222151
Or go to a MAP with Related Content (see alsos): https://www.bbc.com/pidgin/media-53231363
2. View the related content 
3. Notice that the image thumbnails are fuzzy 

**Expected behaviour**
The images should appear clearly and in higher resolution on see alsos promos on CPS MAPs & STYs 

**Screenshots**
![Screenshot 2020-07-01 at 12 21 19](https://user-images.githubusercontent.com/22519682/86238498-825ee600-bb95-11ea-8a10-30682c1544fb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
I have checked out this branch locally, and checked what it looks like on my desktop - looking good!

Before: 
![image](https://user-images.githubusercontent.com/58214768/88417080-2d4f7200-cdd9-11ea-872f-836ec7012284.png)

After:
![image](https://user-images.githubusercontent.com/58214768/88417043-20cb1980-cdd9-11ea-9d93-dac27e619ec2.png)

**Comment by karinathomasbbc** [comment]
Changes are now live & looking good. Moving to Done
