### ISSUE TITLE
Use image-with-placeholder for hero image on OD radio

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#7097]
**Describe the bug**

The hero is missing on OD Radio AMP pages when JavaScript is disabled.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/indonesia/bbc_indonesian_radio/programmes/w13xtt0s.amp
2. Disable JavaScript
3. Note the missing hero image

**Expected behaviour**
The hero should show as it does on canonical pages

**Screenshots**

![image](https://user-images.githubusercontent.com/59573468/86251158-65cca900-bba9-11ea-9a76-e7a6071f1de8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
![Screen Shot 2020-08-13 at 11 08 36](https://user-images.githubusercontent.com/8601460/90122555-5b2f3300-dd55-11ea-8a0c-ae1a1d00ca50.png)

**Comment by RichardPK** [comment]
- The image being used in OD radio is `psammead-image`, which uses `<amp-img>` on AMP.
- `amp-img` relies on Javascript. https://amp.dev/documentation/guides-and-tutorials/develop/media_iframes_3p/
- AMP suggest using a regular `<img>` as a fallback, nested within a `<noscript>` tag
- In order to add the fallback and see if it works, you need to use Storybook, which just dies on its ass when you disable JS.

Open to suggestions on how to view the change without blindly publishing new versions of `psammead-image` and seeing if it works

**Comment by rebeccamcginn** [comment]
What other pages use psammead-image?

**Comment by RichardPK** [comment]
Like, everything.

Front page, articles, MAP, onward journeys:

 
![Screenshot 2020-08-26 at 10 09 41](https://user-images.githubusercontent.com/9042672/91284901-6be39e00-e784-11ea-87cb-e59f5e96f9e1.png)

![Screenshot 2020-08-26 at 10 09 19](https://user-images.githubusercontent.com/9042672/91284903-6be39e00-e784-11ea-8923-4e130379b9b8.png)

![Screenshot 2020-08-26 at 10 09 59](https://user-images.githubusercontent.com/9042672/91284899-6ab27100-e784-11ea-9d60-9b4a3bb7f735.png)

**Comment by RichardPK** [comment]
This fallback behaviour could be valuable everywhere - asking on Slack if it is intentionally not being used.

**Comment by RichardPK** [comment]
From Chris

> "The vast majority of readers on an AMP will be coming from google search. If a reader has js disabled then google does not load the amp page"

Elsewhere on the site, the images make use of the `ImageWithPlaceholder` comp, to at least not render white space. I'll implement that on OD radio

**Comment by rebeccamcginn** [comment]
![image](https://user-images.githubusercontent.com/59573468/92005539-85b05280-ed3b-11ea-8f23-6a7a07a2d4f4.png)

Image placeholder now shows on AMP when JavaScript is disabled
