### ISSUE TITLE
[WSS] Release batch 4a to live

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#7098]
On Tuesday 7th July we want to release batch 4a of STY services to live. 

**Task:**

Move the following services from the pre-launch list to the live list in Mozart.

```
Marathi
Thai
Serbian
```

**The Mozart PR should be merged by Monday 6th**

**Comment by wangs02** [comment]
Change Notification Ticket - CHANGE-25097

**Comment by chris-hinds** [comment]
batch 4a released.
