### ISSUE TITLE
Afaan Oromoo live radio page 404s on test

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#7109]
**Describe the bug**
Afaan Oromoo live radio page 404s on test - https://www.test.bbc.com/afaanoromoo/bbc_afaanoromoo_radio/liveradio

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/afaanoromoo/bbc_afaanoromoo_radio/liveradio
2. Observe English 404 message

**Expected behaviour**
Afaan Oromoo live radio page should be shown

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
This has been resolved with the following Mozart PR - https://github.com/bbc/mozart-routing/pull/1436
