### ISSUE TITLE
Align Canonical Ads with UX Specifications

### ISSUE THREAD

**Issue by benjifellows** [bbc/simorgh#7119]
**[UX Specification](https://paper.dropbox.com/doc/UX-Specifications--A3e2OTpucQPtVgNznlH0sagOAg-akOs0FCThHOEeE8hz4qEA)**

UX have requested to pair on this issue.

**Ad Slot Background Colour**
GNL use #f8f8f8 for `background-color` and we use #f6f6f6 on AMP. UX are happy for us to change to #f8f8f8.
https://github.com/bbc/simorgh/blob/62ff6d33c9e8a4c24d813f380716f9e57c4be9eb/src/app/containers/Ad/Amp/index.jsx#L20

**Min Screen Width**
If screen width is below minimum, Ad Slot should not be displayed
- Leaderboard: 320px
- MPU: 300px

**Content Shifting**
We are not allowing any content shifting for Leaderboard Ads. The Ad Slot will be rendered at a specific size for each breakpoint, which corresponds with the largest Ad Unit possible within that breakpoint. We will not be using the Group 4 breakpoint and have created our own _Custom Leaderboard Breakpoint_.

For MPU’s, we are willing to allow Content Shifting as they will be generally further down the page and likely below the viewport of most users. We should reserve the space for the smaller ad slot, and allow it to grow if needed. A further issue could introduce a more complex solution that avoids content shifting here.

In both cases we can set a min-height on the ad slot.

**Custom Leaderboard Breakpoint**
In order to minimise the amount of empty space we are rendering for Ads in GEL Group 3/4 - we have developed a Custom Leaderboard Breakpoint at `940px width`. This separates the breakpoints at the `940px x 230px` Ad Unit for larger screens. 

### **Ad Unit Size**
The Ad Unit is the Ad Component we receive from GNL. This is a list of expected Ad Units for each breakpoint.

Leaderboard | GROUP 1: [320 - 399px] | GROUP 2: [400 - 599px] | GROUP 3 - Custom Leaderboard Breakpoint: [600 - 939px] | Custom Leaderboard Breakpoint+: [940px - 10000px]
-- | -- | -- | -- | --
Ad Units Served | 320px x 50px \ 300px x 50px | 516px x 60px \ 320px x 50px \ 300px x 50px | 516px x 60px \ 728px x 90px | 728px x 90px \ 970px x 250px \ 940px x 230px

MPU | GROUP 1: [320 - 399px] | GROUP 2: [400 - 599px] | GROUP 3: [600 - 1007px] | GROUP 4: [1008 - 10000px]
-- | -- | -- | -- | --
Ad Units Served | 300px x 50px \ 300px x 250px \ 320px x 50px | 300px x 50px \ 300px x 250px \ 320px x 50px \ 516px x 60px | 300px x 250px \ 300px x 600px | 300px x 250px \ 300px x 600px

### **Rendering the Ad Slot**

We will always render a space the width of the screen. We will then vary the Ad Slot height depending on breakpoint.

**Padding**
The additional space we need to render for the grey border around the largest Ad Unit for each Breakpoint.

Leaderboard - Group 1, 2, and 3: `8px (0.5rem)` of padding
Leaderboard-  Custom Leaderboard Breakpoint: `16px (1rem)` of padding
MPU - All Breakpoints: `8px (0.5rem)` of padding

**‘ADVERTISEMENT’ Link**
Above each Ad Unit should be a link with the word ‘ADVERTISEMENT’, language varied on service. The size of the 'ADVERTISEMENT’ link above the Ad Unit is `25px`. 

These are our UX specs, none of which are currently matched by the GNL implementation.
- Font size 11 
- Font is currently not one of our font styles - confirming with GNL
- Colour should be `#3F3F42`
- Should be regular - not bold

If the Ad Unit is not the largest for its breakpoint, it should be rendered vertically in the centre of the Ad Slot with space to the edge of the Ad Slot (e.g. `728px x 90px` Ad Unit will be rendered within a `250px` high Ad Slot with `80px` space reserved above and `80px` space reserved below). 

### **Ad Slot Size**
The size of the space rendered by WS to be filled by a GNL Ad Unit, including the ‘ADVERTISEMENT’ label
Padding is not included in the Ad Slot Height, it is a separate property.
**_When aligning ad with these dimensions, UX have requested to pair_**

Leaderboard | GROUP 1: [320 - 399px] | GROUP 2: [400 - 599px] | GROUP 3 - Custom Leaderboard Breakpoint: [600 - 939px] | Custom Leaderboard Breakpoint+: [940px - 10000px]
-- | -- | -- | -- | --
Ad Unit Height | 50px | 60px | 90px | 250px
'ADVERTISEMENT' Label Height | 25px | 25px | 25px | 25px
Ad Slot Height | 75px | 85px | 115px | 275px

MPU | GROUP 1: [320 - 399px] | GROUP 2: [400 - 599px] | GROUP 3: [600 - 1007px] | GROUP 4: [1008 - 10000px]
-- | -- | -- | -- | --
Ad Unit Height | 50px | 50px | 250px | 250px
'ADVERTISEMENT' Label Height | 25px | 25px | 25px | 25px
Ad Slot Height | 75px | 75px | 275px | 275px

We could define the max heights of each ad slot, and the height of the label as constants in our code, and then add them together so it's clear where these values have come from. If the UX specs of the label change, we can then update this in one place.

**Describe the solution you'd like**
-  [ ] If Ads are enabled, a space should be rendered underneath the Header section which meets the dimensions of a Leaderboard Ad at it's breakpoint. The Leaderboard Ad should then be rendered into the slot.
- [ ] If Ads are not enabled, the space should not render and the Leaderboard Ad should not render.

- [ ] If Ads are enabled, a space should be rendered underneath the Top Stories section which meets the dimensions of an MPU Ad at it's breakpoint. The MPU Ad should then be rendered into the slot.
- [ ] If Ads are not enabled, the space should not render and the MPU Ad should not render.

- [ ] There should be no content shifting on Canonical for Leaderboard Ads. We are accepting content shifting for MPU Ads on Canonical.
- [ ] If screen width is below minimum, Ads should not be shown
    - [ ] Min Leaderboard: 320px
    - [ ] Min MPU: 300px

**Testing notes**

- Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc
- Something worth considering is what happens when a user changes their screen size - e.g. going from a landscape phone to a portrait phone screen. Expected behaviour is that this will be handled by GNL, similar to how it handles if the page is resized and the ad is too wide.
- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
We define all of our size values using `rem` in our codebase, but the ads specs use `px` - we should ensure we're consistent in Simorgh.

**Comment by tochwill** [comment]
When this is picked up, chat with @benjifellows to answer the couple of questions we have in the issue above before implenting.
