### ISSUE TITLE
Afaanoromoo missing translation for expired content

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#7132]
**Describe the bug**
The translation is missing for "This content is no longer available" on Afaanoromo pages

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/afaanoromoo/bbc_afaanoromoo_radio/w3ct0lby
2. Note the English error message

**Expected behaviour**
The error message to be translated

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Translation requested in #wstranslations on slack https://bbcnews.slack.com/archives/CM3QLV200/p1593791919005700
This is not a pre-requisite for going live

**Comment by ryanmccombe** [comment]
Translation in spreadsheet: Qabiyyee kun hinjiraatu
