### ISSUE TITLE
Resource hints for media pages to improve performance

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#7144]
_Taken from [PR 7469](https://github.com/bbc/simorgh/pull/7469)_

## tl;dr - CONCLUSION

Following initial investigation, and conversations with @billthornton around [his own investgiations](https://paper.dropbox.com/doc/INNOVATION-DAY-Impact-of-preloading-resources--A50fusMCJFjn9tnkblbRLjgiAg-hhP8oDbUytXI3CGfCF21h) & @JibberJim - the conclusions can be summarised as:

- There are many reasons NOT to attempt to preconnect or preload 'real' media urls as detailed [in Jim's comment below](https://github.com/bbc/simorgh/pull/7469#issuecomment-676055798)
- Actual benefits of preconnecting to the bump/players domain are negligible due to a range of optimisations already in place by SMP. As detailed [in Jim's comment below](https://github.com/bbc/simorgh/pull/7469#issuecomment-676055798)
- Preloading bump _would_ work... but the question is; what is loading slower, while we preload bump?
- Ultimately the goal here was to try and allow SMP to have less to do (i.e. load quicker) **once initialised**. But, the bulk of our performance improvements can be achieved by getting SMP to **initialise quicker**, these are (as already discussed)

1. Stop using `polling.bbc.co.uk` domain on Canonical
2. Remove outer iframe on Canonical.

Pt 2. is a much larger discussion as we begin to maintain two media players, but pt 1. is fairly straightforward and I have a PR in progress to capture the work https://github.com/bbc/simorgh/pull/7581

----------

**Is your feature request related to a problem? Please describe.**
We should investigate if using resource hints on media pages could improve the speed of viewing content.

See here for more detail:
https://web.dev/preconnect-and-dns-prefetch/#streaming-media

There's a component in Simorgh that can easily do this for us if we decide it's worth the small amount of effort to implement.

https://github.com/bbc/simorgh/blob/latest/src/app/components/ResourceHints/index.jsx

We would drop this in at the page level.

> Only preconnect to critical domains you will use soon because the browser closes any connection that isn't used within 10 seconds.

This would be perfect for MAP and radio pages because we would expect the user to start playing media within 10 seconds of page load.

We should make sure that this works for iframe content resource loading. If not then we would need to implement in the news-av-player morph module

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
Is the intent here to use the URL of the video files as the resource hint?

Not too sure we can do that - those are provided by media selector (handled by SMP) and exist in a bitrate ladder with 8-11 variations

The exact video stream used depends on stuff like the user's screen size and connection speed

**Comment by jroebu14** [comment]
I'm not 100% sure but I don't think it has be the exact url, just the origin

https://web.dev/uses-rel-preconnect/
https://www.w3.org/TR/resource-hints/#preconnect

**Comment by RichardPK** [comment]
Looks like it can be used for documents / iframes - https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

> Many different content types can be preloaded. The possible as attribute values are:
> 
> ...
> document: An HTML document intended to be embedded by a <frame> or <iframe>.

The iframe src - `embedSource` is currently constructed at the `MediaPlayer` component level. 

Could I use `<Helmet>` to get the `<link>` elements into the page `<head>`? Is there another approach to do this?

I'm playing around with ideas here https://github.com/bbc/simorgh/pull/7469

**Comment by jroebu14** [comment]
@RichardPK you can use this https://github.com/bbc/simorgh/blob/latest/src/app/components/ResourceHints/index.jsx

**Comment by RichardPK** [comment]
@jroebu14 aye have done here - https://github.com/bbc/simorgh/pull/7469/files#diff-3a458af3a03c69f75416a5c352175b83R173 

Question is just whether they are doing anything useful if the `<link>` elements exist within the `<body>`? 

This is the DOM tree:
<img width="514" alt="Screenshot 2020-08-11 at 13 50 43" src="https://user-images.githubusercontent.com/9042672/89899123-b76d4800-dbd9-11ea-840a-c9da96d684dd.png">

**Comment by jroebu14** [comment]
Oh I thought that component used Helmet. Yeh I'm sure if you use Helmet it's able to be rendered server-side in the head

**Comment by RichardPK** [comment]
Lots of exploration into this issue here -> https://github.com/bbc/simorgh/pull/7469

**Comment by RichardPK** [comment]
Closing.

tl;dr of conclusion at top off associated PR. https://github.com/bbc/simorgh/pull/7469
