### ISSUE TITLE
With CSS off, there is no space between the header logo text and skip-to-content text 

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#7151]
**Describe the bug**

When CSS is turned off, the visually hidden link text for the logo in the header merges into the skip to content link text:

Pidgin home page:
![image](https://user-images.githubusercontent.com/59573468/86594644-51185880-bf8f-11ea-98a6-5a13c017376c.png)

Korean live radio page:
![image](https://user-images.githubusercontent.com/59573468/86594556-24644100-bf8f-11ea-82e7-d0d429c95d98.png)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/pidgin
2. Disable CSS

**Expected behaviour**
Separate out the content, potentially pushing the skip to content link onto a new line (by wrapping a div around this element?)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by simonsinclair** [comment]
Re-opening. See https://github.com/bbc/psammead/pull/4110.

**Comment by g4rry420** [comment]
Hello, Can I work on this issue ?

**Comment by rebeccamcginn** [comment]
You sure can!

From: Gurkiran Singh ***@***.***>
Reply to: bbc/simorgh ***@***.***>
Date: Friday, 7 May 2021 at 04:56
To: bbc/simorgh ***@***.***>
Cc: Rebecca McGinn ***@***.***>, Author ***@***.***>
Subject: Re: [bbc/simorgh] With CSS off, there is no space between the header logo text and skip-to-content text (#7151)


Hello, Can I work on this issue ?
