### ISSUE TITLE
Zhongwen OD Radio has lang attribute as "am" for amharic

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#7159]
Zhongwen OD Radio has lang attribute as "am" for amharic

<img width="1440" alt="Screenshot 2020-07-06 at 15 19 46" src="https://user-images.githubusercontent.com/54575620/86612353-eaebff80-bfa7-11ea-9845-5cb522b59052.png">

'ARES is reporting lang as amharic for all zhongwen radio assets'
'looks like we have two variables on the page - lang  from Simorgh and language from ARES :cry:
our page is using the ARES language for the HTML headers: https://github.com/bbc/simorgh/blob/latest/src/app/pages/OnDemandRadioPage/index.jsx#L142
But the Simorgh lang for the media player: https://github.com/bbc/simorgh/blob/latest/src/app/pages/OnDemandRadioPage/index.jsx#L104
we just need to use the simorgh lang for both - it’s an easy change' - Ryan

**Comment by RichardPK** [comment]
AReS fix deployed changing language from "am" -> "zh" for Zhongwen. This is no longer an issue
