### ISSUE TITLE
Audio button not correctly aligned on live for media clip

### ISSUE THREAD

**Issue by paruchurisilpa** [bbc/simorgh#7166]
**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/gahuza/amakuru-52983356
2. Scroll to the bottom of the page where there is an audio clip
3. The audio button is not correctly aligned.
4. Attached is the screenshot

**Expected behaviour**
The button should be correctly aligned with the image

<img width="1440" alt="Screenshot 2020-07-07 at 11 43 50" src="https://user-images.githubusercontent.com/1379277/86770353-7b7a1c80-c048-11ea-9651-275260d356da.png">

**Desktop (please complete the following information):**
- OS: MAC
- Browser : all browsers

**Comment by simonsinclair** [comment]
This seems to be a case of bad placeholder image as opposed to a bug - clicking play confirms this. Are you happy to close this issue @paruchurisilpa?

<img width="610" alt="Screenshot 2020-07-08 at 11 03 55" src="https://user-images.githubusercontent.com/1430787/86905974-bd6b9700-c10a-11ea-86de-d6eacd3f00ab.png">

**Comment by paruchurisilpa** [comment]
Its wrong image size --> http://ichef.bbci.co.uk/images/ic/640xn/p08gj509.jpg.

Closing..
