### ISSUE TITLE
Cinema Mode - On Demand TV

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#7178]
[WSMEDIA-236](https://jira.dev.bbc.co.uk/browse/WSMEDIA-236)

**Comment by LilyL0u** [comment]
![Image 13-07-2020 at 13 14](https://user-images.githubusercontent.com/54575620/87651183-9d5f5780-c74a-11ea-9870-b9c662991c19.jpg)

High contrast mode on the 'High Contrast' accessibility tool actually decreases the contrast as it darkens the player image as if the page had a white background and needed darker to contrast against it.

However, I think this is a limitation of the tool, as looking at a similar cinema mode on another website, The Guardian Videos, it does the same thing with decreasing the contrast.
