### ISSUE TITLE
Unable to load assets in Safari when running a production build locally

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#7214]
**Describe the bug**
When visiting a Simorgh page locally in Safari with a production build, we get SSL errors because the browser is trying to access localhost over https - resulting in no client javascript loading.

**To Reproduce**

1 Run Simorgh locally using `npm run build && npm run start`
2. Go to http://localhost:7080/afrique
3. Look at console

**Expected behaviour**
Safari should not try to access assets over localhost using https.

**Screenshots**
<img width="1432" alt="error" src="https://user-images.githubusercontent.com/46446236/87408720-cc938e80-c5bb-11ea-86f2-1a9e4603bdd1.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Safari
- Version 13.1

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
We are using [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) when running the production build.

**Comment by hotinglok** [comment]
Did some digging with @tochwill and concluded that there isn't an easy permanent fix for this. According to https://bugs.webkit.org/show_bug.cgi?id=171934 this is an issue to do with Safari being non-compliant to [this section](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy) of the Content Security Policy Specification which states that:

> If origin’s host component is "localhost" or falls within ".localhost", and the user agent conforms to the name resolution rules in [let-localhost-be-localhost], return "Potentially Trustworthy".

This issue has existed for at least 2 years which suggests this may persist for the forseeable future. Neither Chrome nor Firefox Nightly have this issue as well.

For now, In `src/server/utilities/cspHeader` you can remove the line `'upgrade-insecure-requests': true`, then access the page in Safari in a private browsing window.

**Comment by DenisHdz** [comment]
Thanks for the feedback @lokh01. I've set the `upgrade-insecure-requests` header to false and now I'm able to see the ads in Safari as the client JS is loaded 👍
