### ISSUE TITLE
VJ include not loading

### ISSUE THREAD

**Issue by joshcoventry** [bbc/simorgh#7226]
**Describe the bug**
A VJ include is failing to load on the Thai service: https://www.bbc.com/thai/52852885

Another example from Serbian service: https://www.bbc.com/serbian/lat/svet-52850902

The style is in source but something is removing it.

It causes this error in the console:

![image](https://user-images.githubusercontent.com/64649560/87525134-febaf400-c680-11ea-8ad1-805b538263d9.png)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to an affected link
2. The include does not load
4. See console error

**Expected behaviour**
The VJ include should load, like it does on PAL: https://www.bbc.com/afrique/institutionelles-52890205

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by andrewscfc** [comment]
This issue was caused by an unclosed `div` in the VJ content used on the page, the corrupted the DOM on our page meaning scripts in the VJ content could not locate DOM elements they wanted to reference by id. The html error was fixed and this fixed the issue.
