### ISSUE TITLE
Add Radio Schedule Translations for New Services 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#7227]
**Is your feature request related to a problem? Please describe.**
There are 8 services that haven't had schedules on the front pages yet. 
We need to update the relevant translations in Simorgh. 
The current schedule translations are defined in the service configs. 

**Describe the solution you'd like**
Add the translations for schedules for the following services: 

**Afaan Oromoo** 
```
liveLabel: 'KALLATTIIN', 
nextLabel: 'KAN ITTAANU',
previousRadioShow: 'Sagantaa raadiyoo dabre'
nextRadioShow: 'Sagantaa raadiyoo itti aanu'
duration: 'Turtii',
header: 'Dhaggeeffadhaa',
durationLabel: 'Turtii %duration%'
```

**Amharic**
```
liveLabel: 'ቀጥታ', 
nextLabel: 'ቀጣይ', 
previousRadioShow: 'ያለፈ የሬዲዮ ስርጭት'
nextRadioShow: 'ቀጣይ የሬዲዮ ስርጭት'
duration: 'ርዝመት',
header: 'ያድምጡ',
durationLabel: 'ርዝመት %duration%'
```

**Bengali** 
```
liveLabel: 'লাইভ',
nextLabel: 'পরবর্তী',
previousRadioShow: 'পূর্ববর্তী রেডিও অনুষ্ঠান',
nextRadioShow: 'পরবর্তী রেডিও অনুষ্ঠান',
duration: 'স্থিতিকাল',
header: 'রেডিও অনুষ্ঠান',
durationLabel: 'স্থিতিকাল %duration%'
```

**Burmese**
```
liveLabel: 'တိုက်ရိုက်ထုတ်လွှင့်မှု',
nextLabel: 'နောက်တစ်ခုသို့', 
previousRadioShow: 'ယခင် ရေဒီယိုအစီအစဉ်', 
nextRadioShow: 'နောက် ရေဒီယိုအစီအစဉ်', 
duration: 'ကြာမြင့်ချိန်', 
header: 'နောက်ဆုံးလွှင့် အစီအစဉ်များ',
durationLabel: 'ကြာမြင့်ချိန် %duration%'
```

**Gahuza**
```
liveLabel: 'IKIBIRIRAHO',
nextLabel: 'IBIKURIKIRA', 
previousRadioShow: 'Ikiganiro ca radiyo giheruka', 
nextRadioShow: 'Ikiganiro ca radiyo gikurikira',
duration: 'Umwanya bimara',
header: 'Ibiganiro bishya',
durationLabel: 'Umwanya bimara %duration%'
```

**Indonesian**
```
liveLabel: 'LANGSUNG', line 47 "LIVE"
nextLabel: 'BERIKUTNYA', line 90 "NEXT"
previousRadioShow: 'Siaran radio sebelumnya',
nextRadioShow: 'Siaran radio berikutnya',
duration: 'Durasi',
header: 'Siaran radio',
durationLabel: 'Durasi %duration%'
```

**Tigrinya**
```
liveLabel: 'ቀጥታ', 
nextLabel: 'ዝቕጽል',
previousRadioShow: 'ኣቐዲሙ ዝነበረ ፈነወ ራድዮ', 
nextRadioShow: 'ዝቕጽል ፈነወ ራድዮ', 
duration: 'ዕምሪ ፈነወ',
header: 'ስምዑ',
durationLabel: 'ዕምሪ ፈነወ %duration%'
```

**Urdu** 
```
liveLabel: 'لائیو', 
nextLabel: 'آگے جائیں',
previousRadioShow: 'گذشتہ ریڈیو پروگرام',
nextRadioShow: 'اگلا ریڈیو پروگرام',
duration: 'دورانیہ', 
header: 'ایف ایم بلیٹن',
durationLabel: '%duration% دورانیہ'
```

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
Not tested

**Comment by LilyL0u** [comment]
Errors on the schedule on test, so cannot test translations yet.
Errors seen are like:
error - radio_schedule_data_incomplete_error
and
error - { “event”: “radio_schedule_fetch_error”, “message”: “Error: Unexpected response (HTTP status code 404) when requesting /bengali/bbc_bengali_radio/schedule.json?renderer_env=live” }

**Comment by rebeccamcginn** [comment]
@LilyL0u I'll ping you when I've fixed schedules :) For Bengali, the masterbrand is bbc_bangla_radio so bbc_bengali_radio will 404 - https://www.test.bbc.com/bengali/bbc_bangla_radio/liveradio?renderer_env=live

**Comment by LilyL0u** [comment]
Tested - duration, header, durationLabel, and nextLabel are present to test, but previousRadioShow and nextRadioShow are not present, and liveLabel might only be present sometimes? Also there are translations in the aria-labels which are not in this issue so I have not been able to compare these to the expected words yet, but I will see if there is a sheet with these on.

Bengali
Burmese
Indonesia

**Comment by LilyL0u** [comment]
Also tested 
Urdu

**Comment by LilyL0u** [comment]
Also tested
Afaan Oromoo
Amharic

(became available Tuesday evening)
