### ISSUE TITLE
Display Smart Banners on iOS for 3 services

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#7247]
**Is your feature request related to a problem? Please describe.**
For the three services with iOS apps, we should enable iOS to display a Smart Banner to promote use of our apps.

**Describe the solution you'd like**
In order to achieve this we need a meta tag in the head of the html document for each page on the relevant service, of the following form:

```
<meta name="apple-itunes-app" content="app-id=**********, app-argument=**********">
```

In the following table, canonicalUrl should be the canonicalUrl of the page the user is currently viewing. The values will most likely want to live in the service config.

Service | App-ID | App-Argument
------------ | ------------- | -------------
Russian | 504278066 | {canonicalUrl}?utm_medium=banner&amp;utm_content=apple-itunes-app
Mundo | 515255747 | {canonicalUrl}?utm_medium=banner&amp;utm_content=apple-itunes-app
Arabic | 558497376 | {canonicalUrl}?utm_medium=banner&amp;utm_content=apple-itunes-app

Note that the apps team have explicitly excepted front pages (and a number of other URLs) from showing the banner - these are listed in and controlled by https://www.bbc.com/.well-known/apple-app-site-association

**Acceptance criteria**

### Meta tag present
Given I am on a Simorgh page on Russian/Mundo/Arabic
Then the relevant meta tag is present

### Banner displayed with App not installed
Given I am using an iOS device
And I select a Simorgh page in safari on Russian, Mundo, or Arabic (live env only)
And the page URL is allowed in https://www.bbc.com/.well-known/apple-app-site-association
And I don't have the app installed
Then I can see a smart banner for the relevant App
And the CTA to install the app
And the correct Name and description for the app in my device locale

- Note the page url where we don't display it will be determined when a NOT is present e.g `"NOT /russian/in-depth-42173006",`

### Banner displayed with App installed
Given I am using an iOS device 
And I select a Simorgh page in safari on Russian, Mundo, or Arabic (live env only)
And the page URL is allowed in https://www.bbc.com/.well-known/apple-app-site-association
And I do have the app installed
Then I can see a smart banner for the relevant App
And the CTA to open the app
And the correct Name and description for the app in my device locale

### Banner not displayed on excluded pages (e.g. Front Pages)
Given I am using an iOS device
And I select a page in safari with the URL starting  https://www.bbc.com/russian
And the page URL is not allowed in https://www.bbc.com/.well-known/apple-app-site-association
And I don't have the app installed
Then I do not see the smart banner

### Select install
Given I can see the Smart Banner
And I do not have the app installed
When I select install
Then the app store opens
And I can see the relevant App store page

### Select open
Given I can see the Smart Banner
And I do have the app installed
When I select open
Then the correct app opens
And the page I was on opens

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
Once we're happy with this functionality on Test, we need a PR to put it live, by removing this toggle / adding the toggle to the live environment https://github.com/bbc/simorgh/blob/a1cce545de3a1d881d7979917ac919ed465755f7/src/app/containers/Metadata/index.jsx#L111

**Comment by jimjohnsonrollings** [comment]
On Test:

AC | Result
--- | ---
Banner displayed with App not installed | Yes
Banner displayed with App installed | Yes
Banner not displayed on excluded pages (e.g. Front Pages) | No - the banner is displayed on the Test Front Page - this may be because the explicit exception URL is the Live URL though
Select install | Yes
Select open | Opens the app, with the in-app browser showing the correct asset from PAL (Mundo & Arabic) or 404 (Russian)

**Comment by jimjohnsonrollings** [comment]
NB The banners currently display on AMP pages, which we may need to disable as it's likely the app won't be able to cope with those URLs

**Comment by karinathomasbbc** [comment]
> NB The banners currently display on AMP pages, which we may need to disable as it's likely the app won't be able to cope with those URLs

This will be resolved once https://github.com/bbc/simorgh/pull/7822 is merged

**Comment by paruchurisilpa** [comment]
This can be tested once Russian STY's are Live.So moving it to blocked until then..

**Comment by karinathomasbbc** [comment]
We tested this today, and we saw the app banner appear on Front Pages, which is not expected behaviour. We have decided to restrict the app banner to STY and MAP pages only.

**Comment by karinathomasbbc** [comment]
Works as expected on Arabic, Mundo & Russian!
