### ISSUE TITLE
Ensure Related Content's heading is using the correct translation when a language override is present

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#7261]
### Is your feature request related to a problem? Please describe.
Ensure Related Content's heading is using the correct translation when a language override is present.

### Describe the solution you'd like
For Ukraine in Russian, this should be in Russian. And for Ukrainian, it should be Ukrainian.
The Related Content heading translation can be found under the `relatedContent` translation key in the service context.

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

### Additional context
- https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/russian.js#L78

**Comment by simonsinclair** [comment]
Blocked pending: https://github.com/bbc/simorgh/issues/7258.

**Comment by simonsinclair** [comment]
Unblocked following the merge of: #7258.

**Comment by Simon2828** [comment]
Checked that the Related Content's heading is using the correct translation with google translate.

An STY on BBC Ukrainian written in Ukrainian:
https://www.test.bbc.com/ukrainian/features-53407150?renderer_env=live
![Screenshot 2020-07-28 at 14 05 53](https://user-images.githubusercontent.com/13512114/88669892-5e32ee00-d0dc-11ea-8041-9cd7ee3f8e58.png)


An STY on BBC Ukrainian written in Russian:
https://www.test.bbc.com/ukrainian/news-russian-53373654?renderer_env=live
![Screenshot 2020-07-28 at 14 09 26](https://user-images.githubusercontent.com/13512114/88669957-6e4acd80-d0dc-11ea-9445-0d78e9cfc0ba.png)

**Comment by paruchurisilpa** [comment]
Testing:

Lang override is here: https://github.com/bbc/simorgh/blob/6383e745986eba7575c51d1ca88f64e3e6aa4764/src/app/lib/config

The lang override is only for ukrainian in russian pages.

https://www.test.bbc.com/ukrainian/features-53407150?renderer_env=live
https://www.test.bbc.com/ukrainian/news-russian-53373654?renderer_env=live

LGTM..

**Comment by Simon2828** [comment]
The Related Content's heading is using the correct translation when a language override is present, so closing.
