### ISSUE TITLE
Ensure the HTML 'lang' attribute is updated when a language override is present

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#7262]
### Is your feature request related to a problem? Please describe.
When a language override is present, we must indicate that the language of the content has changed from the default.

### Describe the solution you'd like
- Ensure that when a language override is present the root element's (`<html>`) `lang` attribute indicates the language of the content being served. E.G. If BBC Ukrainian serves a Russian Story, the value should match that found in the `ru-UA` config property.

#### A11y acceptance criteria

```
Given I’m using a screen reader
When I navigate the header with Ukrainian language content
Then it is announced with a Ukrainian accent

Given I’m using a screen reader
When I navigate the main column with Russian language content
Then it is announced with a Russian accent
```

Note: @OlgaLyubin will be able to help us with the dev a11y swarm.

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

### Additional context
None.

**Comment by simonsinclair** [comment]
Blocked pending: https://github.com/bbc/simorgh/issues/7258.

**Comment by simonsinclair** [comment]
Unblocked following the merge of: #7258.

**Comment by paruchurisilpa** [comment]
Checked using the link : http://localhost:7080/ukrainian/news-russian-23333960 and the lang is ru-UA which is correct..

a11y --> checked screen reader on mac to see if its reading ukranian language (ru-UA) , compared the above link with whats on test - https://www.test.bbc.com/ukrainian/news-russian-23333960 which is using ru.

LGTM...
