### ISSUE TITLE
Move script creation to Express and disable for AMP

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#728]
**Is your feature request related to a problem? Please describe.**
Script URLs are currently passed to `Document` and then injected into a react component. Injection of the app data is also handled in `Document`. This is inflexible and has limitations if we do not want to send scripts. For example, if the route is AMP.

**Describe the solution you'd like**
Move creation of [bundle](https://github.com/bbc/simorgh/blob/latest/src/app/components/Document/index.jsx#L13-L15) and [data](https://github.com/bbc/simorgh/blob/latest/src/app/components/Document/index.jsx#L35-L39) scripts to the `/*` Express route.

Once these scripts have been moved, we can wrap the logic that creates them in an AMP boolean, which is returned in [data](https://github.com/bbc/simorgh/blob/latest/src/app/components/Document/index.jsx#L35-L39), and send an empty array if AMP.

**Describe alternatives you've considered**
[Rendering scripts inside the Document](https://github.com/bbc/simorgh/pull/718/files#r220607697). This was discounted as the logic is overly-complicated and relies on react-helmet `htmlAttributes`.

**Testing notes**
- Cypress test for no scripts if AMP route

**Comment by pjlee11** [comment]
In terms of the Cypress testing a very similar test was written before the PR #718 was split out - https://github.com/bbc/simorgh/pull/718/commits/4050a4257ca33ef254df98a1a0649917eca22953#diff-16261b391f99eb1c859f8347e92e60daR20

**Comment by ChrisBAshton** [comment]
Is this resolved by #907?

**Comment by jtart** [comment]
Yes @ChrisBAshton
