### ISSUE TITLE
Update footer urls for /japanese

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#7281]
**Is your feature request related to a problem? Please describe.**
The Japanese service are using `vanity` urls for their footer links. Simorgh does not yet support these url format (and it may not in the future)

**Describe the solution you'd like**
Update the footer urls for Japanese. Another piece of work will add redirects for the vanity urls via Mozart (this will be a separate issue)

```
/japanese/help/terms > /japanese/help-33991540
/japanese/help/privacy > /japanese/help-33991542
/help/web/links/ > /japanese/help-33991539
```

**Describe alternatives you've considered**
Adding support for vanity URL's in Simorgh. This could be a lot of work for very little gain.

**Testing notes**
- Manually check the footer links for gahuza and japanese load the correct pages

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chewu** [comment]
Checked updated footer links on: http://localhost:7080/japanese ✔️
