### ISSUE TITLE
Front Pages: Index Alsos of type PRO are displayed without a URL or a Headline

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#7298]
**Describe the bug**
If the editorial team add an Index Also to the Top Story on their Front Page which is a LINK/PRO asset type, then we render the link as an `<a>` tag without any content or an href.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `/persian?renderer_env=test` on Test
2. Observe that two index alsos are visible
3. Observe that three are present in the code, but the third shows as `<a class="StyledIndexAlsosLink-xsqyvb-5 bqlSOf"><span class="IndexAlsosText-xsqyvb-4 gvRfTv"></span></a>`

**Expected behaviour**
* The third index also should also render with headline and href

In the JSON response, the headline and url for a `link` type are in the `name` and `uri` fields.  These field names differ from those used in other types.

The code for extracting the url appears to be here: https://github.com/bbc/simorgh/blob/8b4f86d6091287caa13dc8bd91bda5496f19d72a/src/app/containers/StoryPromo/IndexAlsos/index.jsx#L88

And headlines: https://github.com/bbc/simorgh/blob/8b4f86d6091287caa13dc8bd91bda5496f19d72a/src/app/containers/StoryPromo/IndexAlsos/index.jsx#L86

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Looks good to me, tested using http://localhost:7080/persian
