### ISSUE TITLE
Client-side routing is failing against the TEST environment

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#730]
**Is your feature request related to a problem? Please describe.**
Client-side routing is failing in the Test environment.

Steps to replicate: 
Visit https://simorgh.test.api.bbci.co.uk/news/articles/c0000000025o
Click on an inline link in the article body.
See the page fail to load and this error in the console:
```
TypeError: "NetworkError when attempting to fetch resource."
TypeError: "p is undefined, can't access property "content" of it"
Source map error: request failed with status 502
Resource URL: https://simorgh.test.api.bbci.co.uk/static/js/vendor-fd731fb0.658e1e70.chunk.js
Source Map URL: vendor-fd731fb0.658e1e70.chunk.js.map
```

**Describe the solution you'd like**
To have client-side routing working against the Test environment.

**Comment by pjlee11** [comment]
This is a duplicate of https://github.com/BBC-News/simorgh/issues/743
