### ISSUE TITLE
Improve logging for radio schedules on Live Radio pages

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#7332]
**Is your feature request related to a problem? Please describe.**
We should add logging to the Live Radio pages to help us investigate why radio schedules are not being displayed as expected

**Describe the solution you'd like**
It would be good to specify the reason why the radio schedule is not appearing:
- service does not have schedule
- we have not enabled radio schedule for live radio for this service
- error fetching schedule data
- schedule contains less than 4 items

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
Closing as covered by https://github.com/bbc/simorgh/issues/7500
