### ISSUE TITLE
Non-.ico Favicons

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#734]
Low priority, but following on from #705, there are many non-.ico favicons & theme colour definitions now expected by various popular browsers & operating systems, many of which are supported by existing articles. 

I tried to summarise these for the large OSes & browsers below, just so this list is available when we finally get to this work -- though maybe it can be reviewed with an eye on metrics (a very cursory glance at the metrics today didn't suggest this list was too crazy). 

This may also present an interesting question for how we architect this if we want any of the themes or favicons to differ by service or brand? Currently we use GEL's Postbox colour for the theme colour we support, & in the issue referenced above we plan to just use the BBC blocks for favicons, regardless of service.

---

### .png
Several sizes with `link` tags: 16x16, 32x32, 96x96

Example:
```
link rel="icon" type="image/png" href="path/to/favicon-32x32.png" sizes="32x32">
```

### iOS Safari
Several sizes with `link` tags, application name meta tag: 57x57, 60x60, 72x72, 76x76, 114x114, 120x120, 144x144, 152x152, 180x180

Example:
```
<link rel="apple-touch-icon" sizes="57x57" href="path/to/apple-touch-icon-57x57.png">
<meta name="apple-mobile-web-app-title" content="Application Name">
```

#### ✅ Manifest
`manifest.json` file with `link` tag. We already have this.

#### Old Chrome versions
One size with `link` tag, application name meta tag: 192x192

Example:
```
<link rel="icon" type="image/png" href="path/to/android-chrome-192x192.png" sizes="192x192">
<meta name="application-name" content="Application Name">
```

#### ✅ Theme colour
Theme colour in `meta` tag. We already have this.

Example:
```
meta name="theme-color" content="#color">
```

### Windows 8
One size in `link` tag, theme colour in `meta` tag: 144x144

Example:
```
<meta name="msapplication-TileColor" content="#hexColour">
<meta name="msapplication-TileImage" content="path/to/mstile-144x144.png">
```

### Windows 8.1/10
Several sizes with `link` tags, theme colour: 70x70, 150x150, 310x310, 310x150

Example:
```
meta name="msapplication-config" content="path/to/browserconfig.xml" />
```

Example of `browserconfig.xml`:
```
<browserconfig>
    <msapplication>
        <tile>
            <square70x70logo src="path/to/mstile-70x70.png"/>
            <square150x150logo src="path/to/mstile-150x150.png"/>
            <square310x310logo src="path/to/mstile-310x310.png"/>
            <wide310x150logo src="path/to/mstile-310x150.png"/>
            <TileColor>#color</TileColor>
        </tile>
    </msapplication>
</browserconfig>
```

### macOS
SVG icon with `link` tag, theme colour.

Example:
```
link rel="mask-icon" href="path/to/safari-pinned-tab.svg" color="#color">
```

**Comment by sareh** [comment]
Before picking up this ticket, you should look at this issue - they can likely be fixed in one PR. https://github.com/bbc/simorgh/issues/734

**Comment by jimjohnsonrollings** [comment]
Does this duplicate https://github.com/bbc/simorgh/issues/1340 ?

**Comment by joshcoventry** [comment]
We have these favicon/touch icons in use in production:

**.ico**
`        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
`

**Windows 8**
`        <meta data-react-helmet="true" name="msapplication-TileColor" content="#B80000" />
        <meta data-react-helmet="true" name="msapplication-TileImage" content="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-144x144.png" />`

**Apple touch icons (iOS/Safari)**
`<link data-react-helmet="true" rel="apple-touch-icon" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-192x192.png" />`
       ` <link data-react-helmet="true" rel="apple-touch-icon" sizes="72x72" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-72x72.png" />`
        `<link data-react-helmet="true" rel="apple-touch-icon" sizes="96x96" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-96x96.png" />`
        <link data-react-helmet="true" rel="apple-touch-icon" sizes="128x128" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-128x128.png" />
        `<link data-react-helmet="true" rel="apple-touch-icon" sizes="144x144" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-144x144.png" />`
        `<link data-react-helmet="true" rel="apple-touch-icon" sizes="152x152" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-152x152.png" />`
        `<link data-react-helmet="true" rel="apple-touch-icon" sizes="180x180" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-180x180.png" />`
        `<link data-react-helmet="true" rel="apple-touch-icon" sizes="192x192" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-192x192.png" />`
        `<link data-react-helmet="true" rel="apple-touch-icon" sizes="384x384" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-384x384.png" />`
        `<link data-react-helmet="true" rel="apple-touch-icon" sizes="512x512" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-512x512.png" />`
        `<link data-react-helmet="true" rel="icon" type="image/png" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-72x72.png" sizes="72x72" />`
        `<link data-react-helmet="true" rel="icon" type="image/png" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-96x96.png" sizes="96x96" />`
        `<link data-react-helmet="true" rel="icon" type="image/png" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-192x192.png" sizes="192x192" />`
        <link data-react-helmet="true" rel="apple-touch-startup-image" href="https://news.files.bbci.co.uk/include/articles/public/gahuza/images/icons/icon-512x512.png" />`

This means it looks like we are missing:

**.png**

Several sizes with link tags: 16x16, 32x32, 96x96

**Example:**

`link rel="icon" type="image/png" href="path/to/favicon-32x32.png" sizes="32x32">`


**macOS**

SVG icon with link tag, theme colour.

**Example:**

`link rel="mask-icon" href="path/to/safari-pinned-tab.svg" color="#color">`

**Old Chrome versions**

One size with link tag, application name meta tag: 192x192

**Example:**

`<link rel="icon" type="image/png" href="path/to/android-chrome-192x192.png" sizes="192x192">
<meta name="application-name" content="Application Name">`

**Windows 8.1/10**

Several sizes with link tags, theme colour: 70x70, 150x150, 310x310, 310x150

**Example:**

`meta name="msapplication-config" content="path/to/browserconfig.xml" />`

Example of `browserconfig.xml`:

`<browserconfig>
    <msapplication>
        <tile>
            <square70x70logo src="path/to/mstile-70x70.png"/>
            <square150x150logo src="path/to/mstile-150x150.png"/>
            <square310x310logo src="path/to/mstile-310x310.png"/>
            <wide310x150logo src="path/to/mstile-310x150.png"/>
            <TileColor>#color</TileColor>
        </tile>
    </msapplication>
</browserconfig>`

We also don't have any Apple touch icons smaller than 72x72, we could add  57x57, 60x60, 76x76, 114x114 ?
