### ISSUE TITLE
Investigate how to pass ATI values correctly

### ISSUE THREAD

**Issue by Simon2828** [bbc/simorgh#7359]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have any functionality to handle marketing trackers in the URL and so don't pass these correctly to ATI. Before we implement this, we need to investigate whether we need to do something in Mozart to ensure these ATI values get passed to Simorgh.  Or should this be interpreted client-side instead?

**Describe the solution you'd like**
- Look through logs to see if urls with the ati query strings are already in an allowed list.
- Find out how are we generating the ati query - is it done server side? 
- Find out if an allowed list in Mozart with the ati query strings is needed?
- Discuss with Mozart team implications (eg. around caching) if opting for a server side implementation.

Depending on the outcome of the investigation, new issues might need to be raised for the implementation.

**Describe alternatives you've considered**
N/A

**Additional context**
[parent issue](https://github.com/bbc/simorgh/issues/6609)

**Comment by chris-hinds** [comment]
Current findings;

- ATI params are built on the server side render
- The ATI beacon is only sent on the client using an `useEffect()`
- Mozart does not yet allow any other query strings though
- Mozart allow more query strings would, increase the cache variants, the load on Simorgh and ultimately the costs to running the infra.

General consensus is that we should construct and send the ATI beacon on the client.
