### ISSUE TITLE
Optimo Test Article 

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#736]
**Is your feature request related to a problem? Please describe.**
Create an Article on TEST Optimo (our CMS) with the following:

- Headline
- Image
- Subheading
- Text 
- Text
- Video
Headline has to be first. All five block-types should be used.

**Describe the solution you'd like**
The article should be published on TEST Optimo and visible on the Optimo endpoint.

**Comment by jimjohnsonrollings** [comment]
clm0kzply9po

**Comment by sareh** [comment]
This is blocked pending the Optimo team fixing their image uploader.

**Comment by nathangochin** [comment]
According to Allan, the Image uploader issues have been fixed, and Optimo is now publishing images. That should unblock this?

**Comment by jimjohnsonrollings** [comment]
Done

**Comment by jimjohnsonrollings** [comment]
This asset was subsequently deleted.
