### ISSUE TITLE
Implement consent revocation on AMP pages

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#7367]
**Is your feature request related to a problem? Please describe.**
We finished an investigation into AMP consent, and allowing the user to change their consent values: 
https://github.com/bbc/simorgh/pull/7316

We have a proposed solution. This issue should be fleshed out with designs and an agreed approach, whose legal implications are understood.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
This was done
