### ISSUE TITLE
Add Translations for bbc_persian_radio and bbc_nepali_radio

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#7374]
**Is your feature request related to a problem? Please describe.**
Persian (not dari) and nepali both require schedules on the live radio pages. 
We need to update the relevant translations in Simorgh.
The current schedule translations are defined in the service configs.

**Describe the solution you'd like**
**Persian** 
```
liveLabel: 'زنده', 
nextLabel: 'بعدی',
previousRadioShow: 'برنامه رادیویی قبلی'
nextRadioShow: 'برنامه رادیویی بعدی'
duration: 'مدت',
header: 'برنامه‌های رادیو',
durationLabel: '%duration% المدة الزمنية'
```

**Nepali** 
```
liveLabel: 'प्रत्यक्ष प्रसारण', 
nextLabel: 'अर्को',
previousRadioShow: 'यसअघिको रेडिओ कार्यक्रम'
nextRadioShow: 'यसपछिको रेडिओ कार्यक्रम'
duration: 'अवधि',
header: 'पछिल्लो कार्यक्रम सुन्नुहोस्',
durationLabel: 'अवधि %duration%'
```

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
Looks good but one question:
I expect this is fine, but usually in these translations I have seen duration and durationLabel with (a) shared word(s), for example like in the Nepali translations:
duration: 'अवधि',
durationLabel: 'अवधि %duration%'
However in Persian, these translations the words are different. This might be expected for the language but I wanted to make a note of it just in case. The one I am able to find in the HTML is مدت with the number, and المدة الزمنية cannot be found when searching the HTML.

**Comment by rebeccamcginn** [comment]
No, you are correct - this is an oversight :) Adding it now

**Comment by rebeccamcginn** [comment]
Addresses the issue: https://github.com/bbc/simorgh/pull/7441
