### ISSUE TITLE
Improve Radio Schedule logging

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#7377]
**Needs refinement - old issue around specifically adding page type into radio schedule logging**

Current logging for Radio Schedules doesn't report which page the schedule is being loaded on. Schedule requests on a live radio page vs the front page will currently be logged identically.

We need some way to distinguish between page types in Sumo in order to help find the source of the problem if we see radio schedules erroring.

Currently:
```js
logger.info(RADIO_SCHEDULE_REQUEST_RECEIVED, { url: radioScheduleUrl });
```

Where `radioScheduleUrl` is the `/${service}/bbc_${radioService}_radio/schedule.json` endpoint.

**Proposed solution**
One option would be to pass in the page url `path` into the logger as a way of delineating which page the schedule is being loaded on.

This would work for liveradio, i.e. a sumo query could have a parameter like `| where url === "*/liveradio"`, but I'm not sure how you could query a front page like that.

Page type may need to be passed in, with logic to figure out its page type in Simorgh.

- [ ] Implement & test logging in Simorgh
- [ ] Update Sumo queries

**Existing queries**

- Radio Schedule Requests: https://service.eu.sumologic.com/ui/#/search/941948
- Radio Schedule Errors: https://service.eu.sumologic.com/ui/#/search/941829

**Notes**
Are we receiving incomplete radio schedules data?: https://service.eu.sumologic.com/ui/#/search/942796
(see also runbook https://confluence.dev.bbc.co.uk/display/NEWSART/Simorgh+Run+Book#SimorghRunBook-RadioScheduleismissingfromFrontPageorIDXPage)
It's expected that some services will not have enough data until ARES-1357 is resolved

**Comment by rebeccamcginn** [comment]
I can test this once it is live

**Comment by rebeccamcginn** [comment]
pageType is now showing up in "radio_schedule_request_received" logs. PageTypes are logged as the following:

Home
IDX
LiveRadio
OnDemandRadio
