### ISSUE TITLE
Validate Ares article output

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#738]
**Is your feature request related to a problem? Please describe.**
We should validate the Article JSON output by Ares.

**Describe the solution you'd like**
After the Optimo Article has been published on TEST: #736, we should hit the Ares Test endpoint. https://$ARES_BROKER/api/article/{{id}}
We should save this article within our data files, e.g. at: `/data/test/news/c0000000029.json`. 
We should then run the data validator against this file: `npm run dataValidate`. 

**Testing notes**
If `npm run dataValidate` passes, that will be sufficient.

**Comment by ChrisBAshton** [comment]
Related to #920.
