### ISSUE TITLE
[P2] Create util functions ATI marketing params

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#7385]
**Parent Issue** https://github.com/bbc/simorgh/issues/6609

This is a great candidate for TDD :)

**Is your feature request related to a problem? Please describe.**
Some page requests on assets rendered by Simorgh can be part of a campaign being run by the marketing team. We can tell if a page request originates from a marketing campaign when the url will contains some additional query string parameters.

Different campaign types will have contain different values. For a given campaign type we should match these values and return them, in the correct order.

**Example campaign url**
```
/persian?at_medium=affiliate&at_campaign=73&at_type=partner&at_identifier=whatsapp&at_format=Link&at_creation=wspersian&at_variant=Editorial
```

**Describe the solution you'd like**
Create a set of util functions for constructing ATI marketing campaign parameters based on a campaign type.

If a particular value is not present in the url the output for that value should be blank.

The output should follow this structure:

```
xto=A-B-C-D-E-F-G
```

_If a particular value is not present in the url the output for that value should be blank. e.g. if the value for `F` is missing the expected output would be:_

**Each individual value should be URL encoded, some of the values will be wrapped in square brackets after the URL encoding. Ensure we are not double encoding the url parameters**

```
xto=A-B-C-D-E--G
```

Expected outputs based on campaign types:

**Campaign type == `affiliate`**

```
A = the letters al
B = the value of the at_campaign field
C = the value of the at_type field, wrapped in square brackets
D = the value of the at_identifier field, wrapped in square brackets
E = the value of the at_format field, wrapped in square brackets
F = the value of the at_creation field, wrapped in square brackets
G = the value of the at_variant field, wrapped in square brackets
```

**Campaign type == `sl`**

```
A = the letters SEC
B = the value of the at_campaign field
C = the value of the at_platform field, wrapped in square brackets
D = the value of the at_creation field, wrapped in square brackets
E = the value of the at_variant field, wrapped in square brackets
F = if the value of the at_network field is search, then F = S, if the value of the at_network field is content then F = C
G = the value of the at_term field, wrapped in square brackets
```

**Campaign type == `email`**

```
A = based on the at_emailtype field... acquisition -> EREC, retention -> EPR, promotion -> ES
B = the value of the at_campaign field
C = the value of the at_creation field, wrapped in square brackets
D = the value of the at_send_date field
E = the value of the at_link field, wrapped in square brackets
F = the value of the at_recipient_id field followed by the @ symbol and the value of the at_recipient_list field
```

**Campaign type == `display`**

```
A = AD
B = the value of the at_campaign field
C = the value of the at_creation field, wrapped in square brackets
D = the value of the at_variant field, wrapped in square brackets
E = the value of the at_format field, wrapped in square brackets
F = no value
G = the value of the at_general_placement field, wrapped in square brackets
H = the value of the at_detail_placement field, wrapped in square brackets
```

**Campaign type starts with `custom` e.g. custom123**

```
A = CS followed by the part of the at_medium field following the word custom (e.g. for custom123, it becomes CS123)
B = the value of the at_campaign field
C = the value of the at_custom_1 field, wrapped in square brackets
D = the value of the at_custom_2 field, wrapped in square brackets
E = the value of the at_custom_3 field, wrapped in square brackets
F = the value of the at_custom_4 field, wrapped in square brackets
```

**Campaign type == `xtor`**

Take the value of the `xtor` QS e.g.`?xtor=12345678` and return the following

```
xto=12345678
```

Note the difference in the parameter name, the output should not include the `r`

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by JonBeeb** [comment]
[ATI market value.xlsx](https://github.com/bbc/simorgh/files/5029248/ATI.market.value.xlsx)
Spreadsheet for list of campaign types
