### ISSUE TITLE
Update runbook for schedules on Live Radio pages

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#7388]
Update the runbook to include schedules on live radio pages
https://confluence.dev.bbc.co.uk/display/NEWSART/Simorgh+Run+Book

**Comment by aeroplanejane** [comment]
- Logged missing schedule on Live radio (where not expected) as a P4 under incident prioritisation
https://confluence.dev.bbc.co.uk/display/NEWSART/Simorgh+Run+Book#SimorghRunBook-Prioritisationofissues,forpagesthatbeingservedfromSimorgh
- These are steps to investigation the incident: https://confluence.dev.bbc.co.uk/display/NEWSART/Simorgh+Run+Book#SimorghRunBook-RadioScheduleismissingfromLiveRadioPage

**Comment by gavinspence** [comment]
Closing as marked as Done
