### ISSUE TITLE
Refactor Footer Container to have separate Amp/Canonical versions

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#7401]
**Is your feature request related to a problem? Please describe.**
The final decisions as to where to put the amp-consent button are still being made, but regardless of the outcome we will most likely place the button in the footer. This means that we will need separate AMP/Canonical versions as we have done with other containers.

**Describe the solution you'd like**
Separate current Footer `index.jsx` into `index.amp.jsx` and `index.canonical.jsx`. They don't need to have any actual differences at the moment but showing that they are rendering different things depending on these files is a good idea.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
We need confirmation on if we can replace the AdChoices/Do not sell my info link with the button to bring up the consent banner again, or if we need to add another button to the end of the list of links. We should just be able to check `isAmp` within one footer component and pass the button in if needed without needing to split these into two components I think!

**Comment by tochwill** [comment]
Going to close this issue - making changes to the footer for AMP pages can be done as part of https://github.com/bbc/simorgh/issues/7367, and we probably don't need to create a separate AMP/Canonical footer for that work!
