### ISSUE TITLE
Make Post request to /data

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#742]
**Is your feature request related to a problem? Please describe.**
On the Server, we should add a separate /data endpoint for POST requests. 

**Describe the solution you'd like**
In `/server/index.js`, add a post request for the`/data`endpoint.
```
{
    "components": [{
        "id": "simorgh-article",
        "endpoint": "$ARES_BROKER/api/article/${id}",
        "must_succeed": true
    }]
}
```

We should stringify the JSON of the response into the `bodyInline` of the object below:
```
{
    "components": [{
        "Index": "<index>",
        "id": "simorgh-article",
        "Status": "<component_status>",
        "envelope": {
            "head": [],
            "bodyInline": "",
            "bodyLast": []
        }
    }]
}
```

Later on, we will send this to Mozart Requester.

**Describe alternatives you've considered**
N/A

**Testing notes**
All tests should pass. 

**Additional context**
N/A

**Comment by sareh** [comment]
Blocked pending discussions with the Mozart team about the approach.

**Comment by BogdanDogaru** [comment]
Closing as we chose a different approach to this.
