### ISSUE TITLE
QA & put remaining schedules in production for live & on demand radio pages

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#7444]
There are 6 services yet to go-live with schedules for live and ondemand radio. 

We have held them back as the schedule endpoints often return no data, so the component occasionally disappears. 
In order to avoid confusion we are going to await the necessary changes from ARES who will extend the schedules see: https://jira.dev.bbc.co.uk/browse/ARES-1357

| Service | test url | live url | 
| ------------ | -------------------------------------------------------------------------------------- | --------------------------------------------------------------- |
| Bengali      | https://www.test.bbc.com/bengali/bbc_bangla_radio/liveradio?renderer_env=live          | https://www.bbc.com/bengali/bbc_bangla_radio/liveradio          |
| Afaan Oromoo | https://www.test.bbc.com/afaanoromoo/bbc_afaanoromoo_radio/liveradio?renderer_env=live | https://www.bbc.com/afaanoromoo/bbc_afaanoromoo_radio/liveradio |
| Burmese      | https://www.test.bbc.com/burmese/bbc_burmese_radio/liveradio?renderer_env=live         | https://www.bbc.com/burmese/bbc_burmese_radio/liveradio         |
| Amharic      | https://www.test.bbc.com/amharic/bbc_amharic_radio/liveradio?renderer_env=live         | https://www.bbc.com/amharic/bbc_amharic_radio/liveradio         |
| Nepali       | https://www.test.bbc.com/nepali/bbc_nepali_radio/liveradio?renderer_env=live           | https://www.bbc.com/nepali/bbc_nepali_radio/liveradio           |
| Tigrinya     | https://www.test.bbc.com/tigrinya/bbc_tigrinya_radio/liveradio?renderer_env=live       | https://www.bbc.com/tigrinya/bbc_tigrinya_radio/liveradio       |

When ARES has released the changes we will release the services. 
Release checklist: https://paper.dropbox.com/doc/Live-Radio-Release-Checklist-5820--A5Lmp06_llKt~kP~YjQwZQ2zAQ-7Tw62uKEGRZq43lY0ocaP

**Comment by LilyL0u** [comment]
Tested using the above links, all pages display schedule as expected.
