### ISSUE TITLE
[Investigate] Cleanup of media specific service & application toggles

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#7503]
**Is your feature request related to a problem? Please describe.**
We have agreed to migrate all of the Simorgh application toggles to iSite. We should now check if we need to tidy up any of the Simorgh code as a result, particularly media specific toggles (see https://github.com/bbc/simorgh-infrastructure/issues/1159 for further information)

**Describe the solution you'd like**
Remove feature toggles which are no longer required
Move toggles out of service config files - iSite is now the source of truth for this information
Fix any broken tests / snapshots

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
Work undertaken for schedules, cinemaModeTV, logMediaPlayerStatus, mediaPlayer, mostWatched, radioSchedule
