### ISSUE TITLE
Enable client side routing for Collaboration Week

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#7531]
**Is your feature request related to a problem? Please describe.**
As part of the work for implementing a sticky player, we need to enable CSR when hopping around the Live Radio/OD Radio pages

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
Navigating between one pageType works, for example OD Radio to OD Radio or Live Radio to Live Radio. 
Navigation across ws-media pageTypes (OD Radio -> OD TV -> Live Radio) is partially working. There is a flash of a blank page between the render as the implementation wasn't written to handle cross page types.

**Comment by rebeccamcginn** [comment]
App.jsx needs to be refactored

**Comment by rebeccamcginn** [comment]
Live Radio -> different pageType does not work, results in a blank page. Needs further investigation to work out why

This also means that the back button does not work here

**Comment by rebeccarfmcginnbbc** [comment]
Back button not working across page type with the current App.jsx implementation

**Comment by rebeccamcginn** [comment]
OD Radio/OD TV/Live Radio -> MAP all show a 404 then render the MAP

**Comment by rebeccamcginn** [comment]
We have made the decision to go with an intermediary solution for Collab Week wherein a loading page will render between cross page type navigation
