### ISSUE TITLE
Add a static page for /[service]/articles

### ISSUE THREAD

**Issue by jamesbhobbs** [bbc/simorgh#755]
**Is your feature request related to a problem? Please describe.**
There is no fallback page for a PWA or as a base url for an app shell

**Describe the solution you'd like**
Add a very basic static page on this link and use it as PWA start_url, and revert #1240.

**Describe alternatives you've considered**
Start with less basic page and rewrite document.jsx as an .html appshell, but it's a lot more work.

**Testing notes**
TBC

**Additional context**

**Comment by chris-hinds** [comment]
Low priority, speak with Benjamin next time we look at this issue to get some more information and to help prioritise.
