### ISSUE TITLE
Test ATI marketing campaign on test

### ISSUE THREAD

**Issue by rhenshaw56** [bbc/simorgh#7580]
**Is your feature request related to a problem? Please describe.**
During development of #7484, we were unable to test the marketing campaign values passed unto ATI as it is usually initiated by an external link. Following the merge of #7484 we now need to verify if it adheres to constraints defined in the original issue (#6609).
Following the outcome of this, we would have to create further issues to address any pending concerns or enable it on the live environment to close the issue.
**This would need to be done by a tester.**

**Describe the solution you'd like**
- reach out to @JonBeeb or @jimjohnsonrollings on how to test this.

**Describe alternatives you've considered**

**Testing notes**

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [X] This feature is expected to need manual testing.

**Additional context**

**Comment by jimjohnsonrollings** [comment]
At present, my understanding is that only the example in the original issue will work all the way through on Test and be visible in the ATI interface:

/persian?at_medium=affiliate&at_campaign=73&at_type=partner&at_identifier=whatsapp&at_format=Link&at_creation=wspersian&at_variant=Editorial

If we make up field values, we will be able to see them passing through in the client, but ATI will reject (not record) values that it is not expecting.

**Comment by paruchurisilpa** [comment]
Waiting for @jimjohnsonrollings to add the URL's so that I can pick this up for testing..

**Comment by jimjohnsonrollings** [comment]
### Testing

Example link | Expected ATI call parameter | Notes
--- | --- | ---
/persian?at_medium=affiliate&at_campaign=73&at_type=partner&at_identifier=whatsapp&at_format=Link&at_creation=wspersian&at_variant=Editorial | `xto=al-73-[partner]-[whatsapp]-[Link]-[wspersian]-[Editorial]` | This is the only one that is expected to actually record in ATI on Test
/arabic?at_custom1=[post+type]&at_medium=custom7&at_custom3=BBC+Arabic&at_custom4=9A8ADB50-E32A-11EA-928F-A1C04744363C&at_custom2=facebook_page&at_campaign=64 | `xto=cs7-64-[[post+type]]-[facebook_page]-[BBC Arabic]-[9A8ADB50-E32A-11EA-928F-A1C04744363C]` | This was a real one lifted from Live
/hausa?at_medium=sl&at_campaign=103&at_platform=google&at_creation=cheese&at_variant=digestive&at_network=search&at_term=egg | `xto=sec-103-google-[cheese]-[digestive]-s-[egg]` | I'm not convinced I've understood the logic for `at_platform` correctly in the original ticket...
/mundo?at_medium=sl&at_campaign=103&at_platform=google&at_creation=cheese&at_variant=digestive&at_network=content&at_term=egg | `xto=sec-103-google-[cheese]-[digestive]-c-[egg]` | I'm not convinced I've understood the logic for `at_platform` correctly in the original ticket...
/ukchina?at_medium=email&at_emailtype=acquisition&at_campaign=12&at_creation=food&at_send_date=20080808&at_link=gingerbread&at_recipient_id=1701&at_recipient_list=halloumi | `xto=EREC-12-[food]-20080808-[gingerbread]-1701@halloumi` | I've noticed that PAL has `EREC` in lower case.  I don't think we need to worry though
/turkce?at_medium=email&at_emailtype=retention&at_campaign=12&at_creation=food&at_send_date=20080808&at_link=gingerbread&at_recipient_id=1701&at_recipient_list=halloumi | `xto=EPR-12-[food]-20080808-[gingerbread]-1701@halloumi` | 
/gahuza?at_medium=email&at_emailtype=promotion&at_campaign=12&at_creation=food&at_send_date=20080808&at_link=gingerbread&at_recipient_id=1701&at_recipient_list=halloumi | `xto=ES-12-[food]-20080808-[gingerbread]-1701@halloumi` | 
/gujarati?at_medium=display&at_campaign=47&at_creation=iceberg&at_variant=juice&at_format=kitchen&at_general_placement=legume&at_detail_placement=mushroom | xto=ad-47-[iceberg]-[juice]-[kitchen]--[legume]-[mushroom] | 
/japanese?xtor=ad-47-[iceberg]-[juice]-[kitchen]--[legume]-[mushroom] | xto=ad-47-[iceberg]-[juice]-[kitchen]--[legume]-[mushroom] |
/nepali?at_medium=sl&at_campaign=103&at_platform=google&at_variant=digestive&at_network=search&at_term=egg | `xto=sec-103-google--[digestive]-s-[egg]` | This scenario is where one field is absent

In any/all of the above, replacing the `?` with `#` in the URL is expected to also work

### at_platform
* I think we might need to remove the square brackets from this one
* I think there might be a fixed list of acceptable values, and we need to map them to different forms
* I think we should probably go ahead with this regardless and if it's a problem raise a new issue

### at_emailtype
* PAL seems to lowercase the outcomes here
* I don't think we should be concerned - let's go ahead and we can fix later if it is a problem

**Comment by paruchurisilpa** [comment]
Testing:

Checked ATI calls for the links above and below are the xto values

1) https://www.test.bbc.com//persian?at_medium=affiliate&at_campaign=73&at_type=partner&at_identifier=whatsapp&at_format=Link&at_creation=wspersian&at_variant=Editorial 
-----> Expected  : xto=al-73-[partner]-[whatsapp]-[Link]-[wspersian]-[Editorial]
           Actual       :  xto=al-73-[partner]-[whatsapp]-[Link]-[wspersian]-[Editorial]

2) https://www.test.bbc.com/arabic?at_custom1=[post+type]&at_medium=custom7&at_custom3=BBC+Arabic&at_custom4=9A8ADB50-E32A-11EA-928F-A1C04744363C&at_custom2=facebook_page&at_campaign=64 
-----> Expected  : xto=cs7-64-[[post+type]]-[facebook_page]-[BBC Arabic]-[9A8ADB50-E32A-11EA-928F-A1C04744363C]
           Actual       : xto=CS7-64-[[post%20type]]-[facebook_page]-[BBC%20Arabic]-[9A8ADB50-E32A-11EA-928F-A1C04744363C]

3) https://www.test.bbc.com/hausa?at_medium=sl&at_campaign=103&at_platform=google&at_creation=cheese&at_variant=digestive&at_network=search&at_term=egg
----->  Expected : xto=sec-103-google-[cheese]-[digestive]-s-[egg]
            Actual      : xto=SEC-103-[google]-[cheese]-[digestive]-F=S-[egg]

4) https://www.test.bbc.com/mundo?at_medium=sl&at_campaign=103&at_platform=google&at_creation=cheese&at_variant=digestive&at_network=content&at_term=egg
-----> Expected:  xto=sec-103-google-[cheese]-[digestive]-c-[egg]
           Actual     :  xto=SEC-103-[google]-[cheese]-[digestive]-F=C-[egg]

5) https://www.test.bbc.com//ukchina?at_medium=email&at_emailtype=acquisition&at_campaign=12&at_creation=food&at_send_date=20080808&at_link=gingerbread&at_recipient_id=1701&at_recipient_list=halloumi redirects to https://www.test.bbc.com/ukchina/simp
-----> ATI call - https://logws1363.ati-host.net/?s=598343&idclient=17b23018-649b-4f84-a491-4c88595bbe03&s2=93&p=ukchinasimp.page&r=1440x900x24x24&re=1443x246&hl=14x55x16&lng=en-GB&x1=[urn:bbc:cps:402b156e-75c0-9e09-e050-a00a7ec04cae]&x2=[responsive]&x3=[news-ukchina]&x4=[zh-Hans]&x5=[https%253A%252F%252Fwww.test.bbc.com%252Fukchina%252Fsimp]&x7=[index-home]&x8=[simorgh]&x9=[%E4%B8%BB%E9%A1%B5+-+BBC+%E8%8B%B1%E4%BC%A6%E7%BD%91]&x11=[2016-10-31T15:18:49.000Z]&x12=[2020-04-15T10:31:47.000Z]  (Does not have xto value)

6) https://www.test.bbc.com/turkce?at_medium=email&at_emailtype=retention&at_campaign=12&at_creation=food&at_send_date=20080808&at_link=gingerbread&at_recipient_id=1701&at_recipient_list=halloumi
-----> Expected:  xto=EPR-12-[food]-20080808-[gingerbread]-1701@halloumi
            Actual    :  xto=EPR-12-[food]-20080808-[gingerbread]-1701@halloumi 

7) https://www.test.bbc.com/gahuza?at_medium=email&at_emailtype=promotion&at_campaign=12&at_creation=food&at_send_date=20080808&at_link=gingerbread&at_recipient_id=1701&at_recipient_list=halloumi
-----> Expected:  xto=ES-12-[food]-20080808-[gingerbread]-1701@halloumi
            Actual     :  xto=ES-12-[food]-20080808-[gingerbread]-1701@halloumi

8) https://www.test.bbc.com/gujarati?at_medium=display&at_campaign=47&at_creation=iceberg&at_variant=juice&at_format=kitchen&at_general_placement=legume&at_detail_placement=mushroom
----->  Expected:  xto=ad-47-[iceberg]-[juice]-[kitchen]--[legume]-[mushroom]   
             Actua     :  xto=AD-47-[iceberg]-[juice]-[kitchen]--[legume]-[mushroom]

9) https://www.test.bbc.com/japanese?xtor=ad-47-[iceberg]-[juice]-[kitchen]--[legume]-[mushroom]
----->  Expected:  xto=ad-47-[iceberg]-[juice]-[kitchen]--[legume]-[mushroom]
            Actual     :  xto=ad-47-[iceberg]-[juice]-[kitchen]--[legume]-[mushroom]

10) https://www.test.bbc.com/nepali?at_medium=sl&at_campaign=103&at_platform=google&at_variant=digestive&at_network=search&at_term=egg
-----> Expected:  xto=sec-103-google--[digestive]-s-[egg] 
           Actual      :  xto=SEC-103-[google]--[digestive]-F=S-[egg]

**Comment by paruchurisilpa** [comment]
Spoke to @JonBeeb about number 5) and he says - jon  2:59 PM
Sorry, the ukchina link not a real life situation (or should not be). It should be ukchina/simp or ukchina/trad. Just ukchina will do some high level redirect.For /ukchina as I doubt the redirect will carry the rest of the url to the new page.

**Comment by paruchurisilpa** [comment]
@rhenshaw56 @JonBeeb @jimjohnsonrollings 
For some examplyes     : Expected: xto=sec-103-google-[cheese]-[digestive]-c-[egg]
                                         Actual     : xto=SEC-103-[google]-[cheese]-[digestive]-F=C-[egg]

instead of c-[egg], I see F=C-[egg], what is F?

Does it make a difference if ATI call has a value in upper case whilst it is expected in lower case?

**Comment by jimjohnsonrollings** [comment]
Re 5 - Yes, sorry @paruchurisilpa that's my mistake

In 4, `F` is the way the sixth item in the list is described in the ticket.  You're right it shouldn't be there in the actual output.

It is not clear whether the case matters.

**Comment by paruchurisilpa** [comment]
Based on discussion we had in standup, moving it to Ready to merge, we will enable on Live and see if we see any issues..
