### ISSUE TITLE
Get specific campaign Ads from GNL for STY Ads

### ISSUE THREAD

**Issue by joshcoventry** [bbc/simorgh#7613]
**Is your feature request related to a problem? Please describe.**
An editor can add a campaign code to the CPS story so the adverts are related to the content of the story
This code needs to be passed to GNL so that it will return the correct adverts
information to get the correct ad for the service in the correct slot

**Describe the solution you'd like**
Ares fields

https://ares-broker.test.api.bbci.co.uk/api/asset/mundo/23234031

The STY asset returned by Ares includes the campaign keyword which we can pass to GNL to request the correct Advert:

**"adCampaignKeyword": "adcampaign",**

```
{
  "metadata": {
    "id": "urn:bbc:ares::asset:mundo/23234031",
    "locators": {
      "assetUri": "/mundo/23234031",
      "cpsUrn": "urn:bbc:content:assetUri:mundo/23234031",
      "curie": "http://www.bbc.co.uk/asset/4563c763-2d30-a24f-b3a2-a3eab7f4f6da",
      "assetId": "23234031"
    },
    "type": "STY",
    "createdBy": "mundo-v6",
    "language": "es",
    "lastUpdated": 1597833881614,
    "firstPublished": 1553002928000,
    "lastPublished": 1553002928000,
    "timestamp": 1553002928000,
    "adCampaignKeyword": "adcampaign",
```

GNL are looking for this object to be declared, with the campaign value passed in as `adCampaign`

```
window.dotcomConfig = {
}
```

_More details pending from GNL regarding the above._

### Acceptance
**Canonical**
Leaderboard advert

GIVEN the service is set to show ads
WHEN calling GNL with the service name and the Leaderboard ad slot and the campaign code
THEN GNL returns a Leaderboard ad belonging to this campaign

**MPU advert**

GIVEN the service is set to show ads
WHEN calling GNL with the service name and the MPU ad slot and the campaign code
THEN GNL returns a MPU ad belonging to this campaign.

**What could go wrong?**

We need to ensure we bear in mind the behaviour of our SPA when we update the window object to ensure GNL can read the value back.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] Integration test
- [ ] This feature is expected to need manual testing.

**Additional context**

NEWSART-982

**Comment by paruchurisilpa** [comment]
Blocked until GNL implements their code..

**Comment by simonsinclair** [comment]
Re-opening, still waiting on GNL.

**Comment by joshcoventry** [comment]
This is now in production and has been confirmed as working by GNL.
