### ISSUE TITLE
Enable comscoreAnalytics toggle on live

### ISSUE THREAD

**Issue by DenisHdz** [bbc/simorgh#7628]
**Is your feature request related to a problem? Please describe.**
~Blocked on fixing this bug issue: https://github.com/bbc/simorgh/issues/7627~

`comscoreAnalytics` toggle has been added to the live iSite form with the all values set unchecked, so it’s disabled.

We need to enable it once the script is tested on the test environment and we get the confirmation from the Comscore team that it is working as expected.

**Describe the solution you'd like**
Enable `comscoreAnalytics` toggle on the live iSite form.

**Describe alternatives you've considered**
N/A

**Testing notes**
Check comscore is firing on live Simorgh pages. 
Inform Stephen when we're toggling this on, so he can check behaviour on Live.

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by jimjohnsonrollings** [comment]
Comscore have verified this is working as expected on Test

**Comment by jimjohnsonrollings** [comment]
Done, and confirmed by GNL
