### ISSUE TITLE
Make a GET request to our Data endpoint

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#763]
**Is your feature request related to a problem? Please describe.**
`DATA_ENDPOINT`/news/articles/:id.json

Blocked by this PR: https://github.com/bbc/simorgh-infrastructure/issues/112

**Describe the solution you'd like**
Update this file to hit the data endpoint. 
Update the data urls for both the client and server:
https://github.com/BBC-News/simorgh/blob/latest/src/app/routes/getInitialData/index.js#L34-L38 

We should have a try/catch to fall back to the local `/data/` url and current Razzle base path value if we can't make a request to Mozart. 

**Note:** We need to find the format returned from the DATA ENDPOINT and extract out the data. 

**Describe alternatives you've considered**

**Testing notes**

**Additional context**

**Comment by sareh** [comment]
This is blocked until we have an endpoint `/news/articles/id.json` available via Mozart.

**Comment by bcmn** [comment]
No longer blocked by Mozart.

**Comment by pjlee11** [comment]
Blocked until https://github.com/bbc/simorgh-infrastructure/issues/120 is finished

**Comment by pjlee11** [comment]
Blocked until our fixture data and the test data have a matching structure.
