### ISSUE TITLE
Setup most watched page with page furniture and translated h1 page title

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#7640]
Example map: [Miro](https://miro.com/app/board/o9J_kvZ2wMk=/?moveToWidget=3074457349544789098&cot=12)
Some analysis of existing routes: [Dropbox Paper](https://paper.dropbox.com/doc/Analysis-Most-Watched--A6ccw62pyGe4I0pgfBjDw8iDAg-TK3nz2VKkDvUNC8P1rnh7) 
Jira ticket: [Jira](https://jira.dev.bbc.co.uk/browse/WSMEDIA-234)
Design: [Zeplin](https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5f22de67d3d1fd1f74e4cda1)

**Is your feature request related to a problem? Please describe.**
Currently when you visit https://www.bbc.com/afaanoromoo/media/video this page is being served by PAL. This page is to be served by Simorgh and use the MostWatched component.

**Describe the solution you'd like**
When I visit https://www.bbc.com/afaanoromoo/media/video I should see a page with page furniture (header/nav etc) and the Most Watched title (translated for the service).

- set up a new route in https://github.com/bbc/simorgh/blob/latest/src/app/routes/index.js
- set up regex to match route here https://github.com/bbc/simorgh/blob/latest/src/app/routes/utils/regex/index.js
- set up a new page component with page furniture here https://github.com/bbc/simorgh/tree/latest/src/app/pages (must use loadable)
- Add new most watched page type to scripts/bundleSize/pages.js to report the bundle size after each build of simorgh
- h1 page title should be rendered on page, it comes from service config e.g. https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/afrique.js#L209

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Comment by rebeccamcginn** [comment]
These are beautiful works of art. Bravo bravo.

**Comment by rebeccamcginn** [comment]
![image](https://user-images.githubusercontent.com/59573468/91588281-d6950500-e94f-11ea-827d-04116b6e66ee.png)

**Comment by rebeccamcginn** [comment]
Some pages for easy viewing:
https://www.test.bbc.com/korean/media/video
https://www.test.bbc.com/afrique/media/video
https://www.test.bbc.com/afaanoromoo/media/video

**Comment by LilyL0u** [comment]
Heading is an H1 ✅ 
![Image 16-09-2020 at 11 09](https://user-images.githubusercontent.com/54575620/93324149-6a4e4880-f80d-11ea-94c3-16a3ac68f174.jpg)

**Comment by SetJackal** [comment]
Tested. Looks fine across all supported services.
