### ISSUE TITLE
Most watched page Analytics

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#7643]
Example map: [Miro](https://miro.com/app/board/o9J_kvZ2wMk=/?moveToWidget=3074457349544789098&cot=12)
Jira ticket: [Jira](https://jira.dev.bbc.co.uk/browse/WSMEDIA-234)

Blocked by the data fetching in https://github.com/bbc/simorgh/issues/7641

**Is your feature request related to a problem? Please describe.**
The most watched page Chartbeat and ATI analytics components should be included in the page component.

**Describe the solution you'd like**
### ATI 

Same setup as most read pages with the exception of url and page which is derived from url

L1 - WS_NEWS_LANGUAGES (598342)
L2 - Afrique (3)
Page  afrique.media.video.page
Set #content type (x7) to list-datadriven 

Ref to custom values here: https://confluence.dev.bbc.co.uk/pages/viewpage.action?pageId=175872867#ATIAnalytics-GlobalCustomVariables-ContentType

### Chartbeat

Send page link and correct site ID (same as Frontpage / most read pages) 

Seo Schema: 

Webpage object (same as most read / frontpage indexes)e.g. https://www.bbc.com/burmese/popular/read

 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

Jira https://jira.dev.bbc.co.uk/browse/WSMEDIA-234

**Comment by aeroplanejane** [comment]
Page load event not being picked up in the inspector so don't think it's firing. 
![Screenshot 2020-09-25 at 16 51 17](https://user-images.githubusercontent.com/22519682/94289262-624e8100-ff50-11ea-8aae-eb7ba2dd160f.png)
](url)

**Comment by jroebu14** [comment]
Example of ATI reporting for https://www.test.bbc.com/yoruba/media/video @aeroplanejane 

```
s = 598343
idclient = b5eb13c5-8fb8-41e6-aadf-21b336ea7d4f
s2 = 107
p = yoruba.media.video.page
r = 1920x1080x24x24
re = 1920x569
hl = 11x40x45
lng = en-US
x2 = [responsive]
x3 = [news-yoruba]
x4 = [yo]
x5 = [https%253A%252F%252Fwww.test.bbc.com%252Fyoruba%252Fmedia%252Fvideo]
x7 = [list-datadriven]
x8 = [simorgh]
x9 = [E%CC%80yi%CC%81%2Bti%CC%81%2Ba%2Bwo%CC%80%2Bju%CC%80l%E1%BB%8D%2B-%2BBBC%2BNews%2BYor%C3%B9b%C3%A1]
```

**Comment by aeroplanejane** [comment]
Tested in ATI Explorer - data being captured as expected. 
![Screenshot 2020-09-28 at 12 08 35](https://user-images.githubusercontent.com/22519682/94425301-9c539900-0183-11eb-8bc2-413760ba36df.png)

Chartbeat also working as expected. Closing as done. 👍
