### ISSUE TITLE
Change public path for static assets served from S3

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#765]
**Is your feature request related to a problem? Please describe.**
Once static assets are uploaded to S3 and they are ready for production with a CDN in front of them,  we need to point at them in our bundles.

**Describe the solution you'd like**
Razzle recommends adding `crossorigin` to our scripts. See information on   `PUBLIC_PATH` variable in the link above, and [here](https://reactjs.org/docs/cdn-links.html#why-the-crossorigin-attribute).

Furthermore this requires a change to simorgh-infrastructure: 
We should change the [build-time variable](https://github.com/jaredpalmer/razzle#build-time-variables) of `PUBLIC_PATH` to be the CDN that is in front of S3. This CDN is: `https://news.test.files.bbci.co.uk`. The path to articles is: `include/articles/`. That is captured by this issue: https://github.com/bbc/simorgh-infrastructure/issues/134

**Describe alternatives you've considered**
No other alternatives.

**Testing notes**
Use of Cypress tests and general regression will cover the testing on this.

**Comment by bcmn** [comment]
Speaking with @jamesbrumpton, we noticed that the Cypress tests do not currently test the URL of img tags, so won't test this change in behaviour. While it should be tested by unit tests, this should be discussed.
