### ISSUE TITLE
Converted image is not rendered in most watched (old bad test data)

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#7710]
These images have come from an unusual source. If you look at the https://www.test.bbc.com/gahuza/mostwatched.json you’ll see the image href should be http://wwwpreview.test.newsonline.tc.nca.bbc.co.uk/media/images/63302000/jpg/_63302851_63302850.jpg
but we take it can convert it to an ichef image URL - https://ichef.bbci.co.uk/news/660/tmcs/media/images/63302000/jpg/_63302853_63302850.jpg - which does not exist
Therefore we cannot render it, and you’ll see the greyed out image. This could happen on live too

Found on page https://www.test.bbc.com/gahuza/amakuru-23257470

![Image 02-09-2020 at 17 52](https://user-images.githubusercontent.com/54575620/92014566-5acbfb80-ed47-11ea-996a-b7d24f322d04.jpg)

**Comment by aeroplanejane** [comment]
Hey @LilyL0u the fix for this it to republish the asset within CPS with correct data. I'm going to close this as it doesn't require a fix on our side.
