### ISSUE TITLE
Most Watched component should use live data if the renderer override is live

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#7711]
**Is your feature request related to a problem? Please describe.**
When viewing the Most Watched component on a MAP page on the test environment, the most watched data comes from the test endpoint e.g. https://www.test.bbc.com/gahuza/mostwatched.json
However, if we are viewing a live asset on the test environment, and using the `renderer_env` override, the most watched data should come from the live endpoint instead e.g. https://www.bbc.com/gahuza/mostwatched.json

**Describe the solution you'd like**
If URL contains `renderer_env=live`, then either 
1. append the same override to the mostwatched endpoint on test only https://test.bbc.com/gahuza/mostwatched.json?renderer_env=live
or 
2. use the live mostwatched endpoint e.g. https://www.bbc.com/gahuza/mostwatched.json

**Describe alternatives you've considered**
N/A

**Testing notes**
Ensure that when the live override is set (in test environment only), that the mostwatched data is live data
- [x] This feature is expected to need manual testing.

**Additional context**
Changes may need to be made here: https://github.com/bbc/simorgh/blob/latest/src/app/lib/utilities/getMostWatchedUrl/index.js, and perhaps we always want to view live data (even on the test environment). We should have access to the `process.env.SIMORGH_APP_ENV` to check which environment we're on
It is worth checking what we do for radio schedules when the live override is present

**Comment by rebeccamcginn** [comment]
For MAPs:

http://localhost:7080/hausa/media/video?renderer_env=live should show live data in the Most Watched component
http://localhost:7080/hausa/media/video should show fixture data in the Most Watched component

For Most Watched pages:

http://localhost:7080/hausa/media/video?renderer_env=live should show live data
http://localhost:7080/hausa/media/video should show fixture data
