### ISSUE TITLE
React warnings on TopCat 2 assets

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#7756]
**Describe the bug**
When rendering the following TopCat 2 asset we see various React warnings in running in development mode (`npm run dev`):
![image](https://user-images.githubusercontent.com/9645462/92454714-b6b7d980-f1b8-11ea-84e2-69688d3aa725.png)

**To Reproduce**
Steps to reproduce the behaviour:

1. `npm run dev`
2. Visit http://localhost:7080/persian/iran/2009/09/090920_bd_pp_ir88_timeline_election
3. Observe errors in the console.

I am unsure if the errors mean anything is rendering incorrectly compared to the PAL?

**Expected behaviour**
No react warnings display.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Firefox

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Won't fix. Closing
