### ISSUE TITLE
Use serif font as fallback for serif Reith

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#776]
**Is your feature request related to a problem? Please describe.**
When the Reith font does not load, the fallbacks are Helvetica, Ariel, sans.  So we fallback from Serif to Sans.

**Describe the solution you'd like**
Where we're using Reith Serif, the fallback should also be a serif font.

**Describe alternatives you've considered**
N/A

**Testing notes**
Unknown

**Additional context**
N/A

**Comment by jtart** [comment]
This is closed because we will fallback to sans.
