### ISSUE TITLE
Unbolden links in footer

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#777]
**Is your feature request related to a problem? Please describe.**
The links in the footer are in ReithSansRegular with a weight of 700.  This is not currently considered an acceptable way to use the font.

**Describe the solution you'd like**
Reduce the weight of the links to 400.

**Describe alternatives you've considered**
Swap the font for ReithSansBold - not worth it for the limited promenance of these links.

**Testing notes**
Unknown

**Additional context**
N/A

**Comment by greenc05** [comment]
@jimjohnsonrollings @nataliesmart Will another solution be used so the user can distinguish linking text from non linking text in the footer? http://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/design/actionable-elements

**Comment by jimjohnsonrollings** [comment]
Let's not.
