### ISSUE TITLE
X-Frame-Options Header Not Set

### ISSUE THREAD

**Issue by DemonusPC** [bbc/simorgh#779]
**Describe the bug**
Upon testing the local dev Simorgh server, ZAP flagged a missing X-Frame-Options header. 
<img width="1403" alt="screen shot 2018-10-10 at 11 43 00" src="https://user-images.githubusercontent.com/5437869/46731136-745a8a80-cc79-11e8-82c3-4d20c36e5ede.png">

The [X-Frame-Options header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) is a response header that tells the browser if a specified document is able to be included in an iframe. Older browsers do not enforce this rule but many modern browsers will indeed block the rendering of the element if told not to. If not specified there is a chance for clickjack attacks to be issued against our users. 

Protection against this attack is outlined in the [express best practise](https://expressjs.com/en/advanced/best-practice-security.html) document. 

**Expected behavior**
Since we do not expect the articled to be embedded in an iframe the server should return X-Frame-Options: deny. 

Note: My testing was localised to the single express dev server. We might already be protected thanks to Mozart, so contacting them should come first. We should still ideally fix this due to the simplicity of protection and good practises.

**Comment by pjlee11** [comment]
Looking at other application running on Mozart it seems the header is set (`x-frame-options: SAMEORIGIN`

![image](https://user-images.githubusercontent.com/7791726/46732863-96a6d500-cc86-11e8-8454-31e626208a6b.png)

Asking the Mozart team if this is being set by them or upstream of them.

**Comment by DemonusPC** [comment]
Shouldn't we block it for simorgh though? I doubt we would ever want our articles to be embedded in an iframe

**Comment by DemonusPC** [comment]
Just for anyone coming accross this issue. The outcome is outlined in #781. Despite being protected from this attack from the range of internal tools we will still apply proper security practises and code to Simorgh in the case that anyone picks this code and runs it. As the BBC we will continue to patch and fix any problems that can arise in the standalone Simorgh server, regardless of the internal tools that we use.
