### ISSUE TITLE
Error Pages refactor (Parent Issue)

### ISSUE THREAD

**Issue by joshcoventry** [bbc/simorgh#7815]
**Is your feature request related to a problem? Please describe.**
We need to revisit our approach to Error Pages in Simorgh.

Currently, we serve a fallback error page served by Mozart.

Since the page is not served by Simorgh, the error page is not rendered with the correct translation.

There are other things we would like to address when we implement a Simorgh-driven error page:

- An accessibility compliant design ( We shouldn't be using CSS for the list bullets, as this will read out as 'bullet' on some screen readers. It’s recommended to use a list style of none in the CSS e.g. this means adding our own ‘bullet’, and in addition adding aria roles to the list and list items of ‘list’ and ‘listitem’ to ensure we have list semantics in when using VoiceOver.)
(originally covered by https://github.com/bbc/simorgh/issues/1348)

- Translations

- Tests: Ensure error pages are on the Test environment for a small number of services, ideally one RTL (arabic) one LTR (mundo) one with with variants (zhongwen). Then we should add Cypress tests to check that the 404 pages are working for these services. (originally covered by https://github.com/bbc/simorgh/issues/2862)

- Integrate Most Read component in Error Pages (originally covered by https://github.com/bbc/simorgh/issues/3687)

- The Mozart cached error pages do not display cookie/privacy banners. The Simorgh version should. We are required to display these banners to all users in the EEA, but choose to display them to all users. The Privacy banner is displayed once (on first page view), then not again. The Cookie banner is displayed on all page views until the user sets a cookie preference (either by clicking the 'accept' option, or visiting the cookie preferences page). The logic for the banners is documented on https://jira.dev.bbc.co.uk/browse/NEWSART-741

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by greenc05** [comment]
To address the accessibility list issue above, we can simply use the bulleted list component in psammead along with role list and role listitem applied to the corresponding elements https://bbc.github.io/psammead/?path=/story/components-bulletedlist--default
