### ISSUE TITLE
Scroll Y position is not retained when using browser back/forward buttons (client side routing only)

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#7835]
**Describe the bug**
Scroll Y position is not retained when using browser back/forward buttons. This would be a bad UX especially if the user on a front page and has scrolled down the page and navigates to an article then clicks back and they are back at the top of the page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to http://localhost:7080/news/articles/c6v11qzyv8po
2. Click on the inline link in the article
3. Scroll half way down the page
3. Click the browser back button
4. Observe the scroll Y position is not where it was previously
5. Click the browser forward button
6. Observe the scroll Y position is not where it was previously

**Expected behaviour**
Like the native experience (without client side routing) then the scroll Y position should be retained when navigating backwards and forwards.

A potential solution I was working on that keeps track of the scroll Y position before the user transitions to a new page can be seen here - https://github.com/bbc/simorgh/pull/7834/files - this still needs work but the code changes might suggest where I was going with it.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
To revisit when we look at client side routing again.
