### ISSUE TITLE
Update Thai font

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#7872]
**Is your feature request related to a problem? Please describe.**
Update the following font on Thai

**Describe the solution you'd like**
On the Thai service update Trafalgar Group D from 32 to 30px. The line height stays the same. 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by FK78** [comment]
After Talos bumps @bbc/gel-foundations in Psammead, a UX review needs to be done and once approved we can close this issue.
