### ISSUE TITLE
[Perf] Use effective-connection-type (ETC) to load a lighter weight page.

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#7898]
**Is your feature request related to a problem? Please describe.**
There are a number of headers available, know as device hints that can tell us information about a users device or connection like the amount of RAM a device has of the rough connection speed it is using e.g. 2g, 3g, 4g, cable.

Can we use this information to a send a lighter weight page to a user by ensuring 3rd party content is only loaded a users actions it. I.e. if the connection type making the request is 2g let's put social embeds and includes behind a user action, something that tells the user they will be downloading extra content if choose too.

Passing these headers to Simorgh would mean that we have to vary on them in Mozart, so we may not be able to use them all. My suggestion would be to use the ECT to load a full page r a lightweight page, this way we only need to vary the cache on one header.

Or if we can enable CSR on STY pages we could always ship the lighter page by default and then progressively enhance the page on the client.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by andrewscfc** [comment]
Closing in favour of other tickets around use of `save-data` header etc
