### ISSUE TITLE
[Perf] Use content-visibility to skip rendering of below the fold content

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#7899]
**Is your feature request related to a problem? Please describe.**
A new CSS property, content-visibility can be used to tell the browser to skip the render/painting of content that is below the fold/outside of the current view port. This can in some cases dramatically decrease the rending time in the browser.

Learn more https://web.dev/content-visibility/

**Describe the solution you'd like**
Make use of the the content-visibility CSS value to skip rendering of content below the fold.

**Describe alternatives you've considered**

**Testing notes**
Need to check scroll behaviour
Need to validate any accessibility issues with hidden components

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
Initial components: footer, most read, topic tags, related content

**Comment by chris-hinds** [comment]
Nice to see this one being worked on. Would be interesting to see if this did in fact make any difference. 👍
