### ISSUE TITLE
Define Chartbeat config values specific to the FIX page

### ISSUE THREAD

**Issue by chewu** [bbc/simorgh#7910]
I think we might need to confirm what the values for those would be in the FIX pages data and set them appropriately in [this file](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/utils/index.js#L104-L125) for `getType` and `getTitle`

_Originally posted by @rhenshaw56 in https://github.com/bbc/simorgh/pull/7856#discussion_r494270309_

**Comment by paruchurisilpa** [comment]
I can see chartbeat beacon is fired as suggested by John.Moving it to Ready to merge..
