### ISSUE TITLE
NAV: Afrique - Update nav to remove deprecated indexes

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#7912]
**Is your feature request related to a problem? Please describe.**
Change the navigation bar on BBC Afrique to remove recent-asset indexes that are being deprecated as a result of the off-Forge migration.

**Describe the solution you'd like**
Change the navigation on the BBC Afrique site as follows
https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/afrique.js

{
 title: 'Accueil',
 url: '/afrique',
},
{
 title: 'Afrique',
 url: '/afrique/topics/cvqxn2k7kv7t',
},
{
 title: 'Monde',
 url: '/afrique/topics/cvqxn21vx11t',
},
{
 title: 'Sports',
 url: '/afrique/topics/c404v54yrqyt',
},
{
 title: 'Economie',
 url: '/afrique/topics/cnq687nr9v1t',
},
{
 title: 'Culture',
 url: '/afrique/topics/cnq687nrrw8t',
},
{
 title: 'Au féminin',
 url: '/afrique/38058576',
},
{
 title: 'Technologie',
 url: '/afrique/topics/cnq687nn703t',
},
{
 title: 'Santé',
 url: '/afrique/topics/c06gq9jxz3rt',
},
{
 title: 'Vidéos',
 url: '/afrique/media/video',
},
{
 title: 'Nos émissions',
 url: '/afrique/media-54074891',
},

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
https://www.bbc.com/afrique/media/video will become the Most Watched page which is currently in progress. Are there plans to keep this?
