### ISSUE TITLE
Updated Storybook has added padding

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#7917]
Resolved by https://github.com/bbc/psammead/pull/3728

When comparing the updated storybook on branch dependabot-storybook to the current one on https://bbc.github.io/psammead/?path=/story I can see a few slight differences that seem to have been introduced. To check if it was a difference due to the environment, I also compared latest on localhost to storybook in github, and it did not have the spacing/padding changes.

Here are some examples of the small changes introduced:

Padding added
![Image 24-09-2020 at 16 13](https://user-images.githubusercontent.com/54575620/94411084-0f531480-0170-11eb-891c-62af5114a379.jpg)

Padding added and font slightly different
![Image 24-09-2020 at 16 18](https://user-images.githubusercontent.com/54575620/94411115-1a0da980-0170-11eb-9aa8-97db50fd5cae.jpg)

Image alignment with text is different
![Image 24-09-2020 at 16 24](https://user-images.githubusercontent.com/54575620/94411145-20038a80-0170-11eb-938a-a7a3feea03f8.jpg)

Very noticable difference
![Image 24-09-2020 at 16 27](https://user-images.githubusercontent.com/54575620/94412420-ae2c4080-0171-11eb-9960-8b8160035edb.jpg)

**Comment by LilyL0u** [comment]
Storybook V6 Upgrade issue: https://github.com/bbc/psammead/pull/3728

**Comment by RichardPK** [comment]
- The content in that `Content anchor` component is dynamically changing, which may account for the differences between versions. I've made some changes regardless - can you take another look @LilyL0u ? 
- Fixed the issues with padding at the story `<body>` level (as seen on the 'Byline > Without Avatar' story)
- Going back into the app highlighted that the `a11y` addon wasn't working, now fixed
- Also changed our core storybook config files to meet the new standard going forward

**Comment by LilyL0u** [comment]
Padding issues fixed. Still some font issues. See screenshots below:

<img width="1440" alt="Screenshot 2020-09-30 at 09 45 24" src="https://user-images.githubusercontent.com/54575620/94664987-810f9780-0303-11eb-8604-99964171dbbd.png">

<img width="1440" alt="Screenshot 2020-09-30 at 09 22 08" src="https://user-images.githubusercontent.com/54575620/94665035-94bafe00-0303-11eb-8da3-4d587316a770.png">

<img width="1440" alt="Screenshot 2020-09-30 at 09 44 10" src="https://user-images.githubusercontent.com/54575620/94664997-853bb500-0303-11eb-901b-133454b09653.png">

**Comment by RichardPK** [comment]
Awesome thanks Lily I'll get this sorted this AM

**Comment by RichardPK** [comment]
Should be sorted now @LilyL0u - can you take a final 👀

**Comment by RichardPK** [comment]
Fixed
