### ISSUE TITLE
Most Watched a11y - remove component region landmark 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#7939]
**Describe the bug**

There should be no region for the component
it should just sit within ‘main’

Remove component region landmark 
the ‘section’ needs changing to a ‘div’ html element, and the role region and the aria-labelledby attributes need removing
<img width="618" alt="Screenshot 2020-09-28 at 10 29 11" src="https://user-images.githubusercontent.com/22519682/94416890-50025c00-0177-11eb-807b-2b67f4eddff2.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Most Watched page
2. Inspect the page using lighthouse 
3. Note the errors 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
For context 
This causing our a11y score to drop in lighthouse https://bbcnews.slack.com/archives/CJT0284G2/p1601033543048100?thread_ts=1601032648.047200&cid=CJT0284G2

**Comment by RichardPK** [comment]
Nice one Jane, I'm on it 👍
