### ISSUE TITLE
Align fixture data with ares payload

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#795]
**Is your feature request related to a problem? Please describe.**
Following the [analysis](https://github.com/BBC-News/simorgh/issues/792) we should align the fixture data with the ares payload.

**Describe the solution you'd like**
Using the examples in https://www.diffchecker.com/3VLSTaBY Add the following values:
`language`, `options`, `relatedContent` block and `analyticsLabels`
Also remove:
`category`, `genre` and `created`

Align the application (propTypes and schema) with the Ares payload, this requires removing the incorrect "required" values in the payload. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Data validator passing is sufficient testing

- [x] Intially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by BogdanDogaru** [comment]
Blocked pending our CMS successfully returning image data for newly-created articles (including `altText`).
