### ISSUE TITLE
Add Ads to FIX Page

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#7968]
**Is your feature request related to a problem? Please describe.**
Put ads on FIX pages - similar to Front Pages

**Describe the solution you'd like**
- [x] Add leaderboard FIX pages, similar to functionality on Front Pages
e.g https://github.com/bbc/simorgh/blob/latest/src/app/pages/FrontPage/FrontPage.jsx#L138
- [x] Add MPU to top stories container
e.g. https://github.com/bbc/simorgh/blob/latest/src/app/pages/FrontPage/FrontPage.jsx#L154
Include styling: https://github.com/bbc/simorgh/blob/latest/src/app/pages/FrontPage/FrontPage.jsx#L64
- [x] Ad campaigns are currently out of scope

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
LGTM...As part of this PR only tested leaderboard..MPU will be tested seperately..
