### ISSUE TITLE
Use fragmented data to render rich text for headings

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#800]
**Is your feature request related to a problem? Please describe.**
With work being merged to render fragment data with #672, the [heading](https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/Headings/index.jsx) components will render plain text rather than rich text. This is because the [`model.text` property in Fragmented data]() is just plain text

**Describe the solution you'd like**
We should change the Heading component to use the [Fragment](https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/Fragment/index.jsx) component to render bold, italics, and all other rich text. There are 2 options for using the Fragment component, and there needs to be a consideration for what option to use. These options are:
- Use the Fragment component 'directly' with the [Blocks](https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/Blocks/index.jsx) component (`Headings -> Blocks -> Fragment`) --- This means would need to extract `Fragment` out of each `Text -> Paragraph` block, which might be complex to maintain
- Use the Text component. It currently renders `Text -> Blocks -> Paragraph -> Blocks -> Fragment`, and would need a refactor to change out `Paragraph` for the `Heading` component, i.e. `Text -> Blocks -> Heading -> Blocks -> Fragment`  --- This would add cognitive complexity to the rendering structure, which would include CPU overhead

**Describe alternatives you've considered**
See 2 potential solutions in descriptions.

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Comment by jtart** [comment]
Let's deprioritise this for alpha-1.0 and do it afterwards, we can live with it for the foreseeable future.

**Comment by ChrisBAshton** [comment]
Fixed by #1367.
