### ISSUE TITLE
Use fragmented data to render rich text for image captions

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#801]
**Is your feature request related to a problem? Please describe.**
With work being merged to render fragment data with #672, the [image](https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/Image/index.jsx) components will render plain text rather than rich text. This is because the [`model.text` property in Fragmented data]() is just plain text.

**Describe the solution you'd like**
We should change the Heading component to use the [Fragment](https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/Fragment/index.jsx) component to render bold, italics, and all other rich text. There are 2 options for using the Fragment component, and there needs to be a consideration for what option to use. These options are:
- Use the Fragment component 'directly' with the [Blocks](https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/Blocks/index.jsx) component (`Caption -> Blocks -> Fragment`) --- This means would need to extract `Fragment` out of each `Text -> Paragraph` block, which might be complex to maintain
- Use the Text component. It currently renders `Text -> Blocks -> Paragraph -> Blocks -> Fragment`, and would need a refactor to be able to just return the string of text that can be nested inside the Caption component, i.e. `Caption -> Text -> Blocks -> Raw Text String(?) -> Blocks -> Fragment` --- This would add cognitive complexity to the rendering structure, which would include CPU overhead

As part of this work, we should add a Figure Caption story which contains a link, defined in fragment style (Following on from #1017).

**Describe alternatives you've considered**
See 2 potential solutions in descriptions.

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

- [x] Intially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by BogdanDogaru** [comment]
Let's deprioritise this for alpha-1.0 and do it afterwards. I feel like we can live with it for the foreseeable future.

**Comment by BogdanDogaru** [comment]
For this issue we'll go with Option 1, but as part of this issue we should contact Optimo to check whether the Editor front-end allows for this level of flexibility in captions.

**Comment by BogdanDogaru** [comment]
Blocked until we answer the question above ^

**Comment by ChrisBAshton** [comment]
Had discussion with Jim & Ben on this one.

Apparently rich text / multiple paragraphs _are_ allowed in Optimo, and so we should accommodate these in our designs and render these.

Now blocked until we have an updated design.
