### ISSUE TITLE
Update BBC Logo src on media player embeds with footer to use secure requests

### ISSUE THREAD

**Issue by pharingee** [bbc/simorgh#8020]
**Describe the bug**
The news-av-player morph module uses insecure `http` src to the BBC logo when the player comes with a footer

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/yoruba/amp/54283413
2. Open the console
3. See error: Mixed Content: The page at 'https://www.bbc.com/yoruba/av-embeds/54283413/pid/p08tcwyp.amp#amp=1' was loaded over HTTPS, but requested an insecure element 'http://emp.bbc.co.uk/emp/embed/img/bbclogo.png'.

**Expected behaviour**
Use a secure https request to fetch the BBC logo
Replace logo file with a suitable asset

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by RichardPK** [comment]
Hey G I'm gonna close this while we track all av-embeds issues here https://github.com/bbc/simorgh-infrastructure/issues/1224

The way the av-embeds morph module releases have been designed (with config deploys per-service), we ought to pool the fixes into one, rather than doing them one-by-one
