### ISSUE TITLE
Routing regex too strict for some TC2 FIX assets

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#8049]
**Is your feature request related to a problem? Please describe.**
https://www.test.bbc.com/ukchina/trad/in_depth/cluster_brazil_worldcup?renderer_env=live is a valid FIX asset, however due to the way in which the regex is configured for legacy (TC2) assets, Simorgh does not recognise the route and returns a 404 page 
Similarly, https://test.bbc.com/vietnamese/indepth/richer_world?renderer_env=live returns a 404

**Describe the solution you'd like**
Ensure that the legacyAsset regex can cater for an asset ID like ukchina/trad/in_depth/cluster_brazil_worldcup -> service/{variant}/category/subcategory
Adjust this regex https://github.com/bbc/simorgh/blob/latest/src/app/routes/utils/regex/utils/index.js#L4 accordingly

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
This is Live now,closing the ticket..
