### ISSUE TITLE
Remove non-fragmented data

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#805]
**Is your feature request related to a problem? Please describe.**
Following the merge of https://github.com/BBC-News/simorgh/pull/783 we should remove the non-fragmented fixture data.

**Describe the solution you'd like**
Move onward journeys into `data/fragmented` then delete `data/test/` and `data/prod/` then rename `data/fragmented/` to `/data/`. There will be need to change the path the fixture data is loaded from https://github.com/BBC-News/simorgh/pull/783/files#diff-788dcef7a5e3a2740bf71979cca64a59R49. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Additional context**
N/A

- [x] Intially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
blocked awaiting the merge of https://github.com/BBC-News/simorgh/pull/783

**Comment by bcmn** [comment]
#783 now merged.
