### ISSUE TITLE
Optimo: Allow use of the inLine block inside the Headline / Subheadline block

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#8105]
**Is your feature request related to a problem? Please describe.**
The Headline and Subheadline blocks do not currently render the content or markup on an inLine block within them.

Examples: TEST: /news/articles/crkxdvxzwxko

**Describe the solution you'd like**
If there is an inLine block inside a Headline or Subheadline block, then render it.

Sareh says:
src/app/containers/Headings/index.jsx needs const componentsToRender = { fragment: Fragment }; updating to include inline: InlineContainer

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Checked using the link : https://www.test.bbc.co.uk/news/articles/crkxdvxzwxko

LGTM.
