### ISSUE TITLE
[Social Embeds] Reduce layout shift of lazy loaded social embeds

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#8114]
**Is your feature request related to a problem? Please describe.**
We recently enable lazyloading for social embeds, however this has introduced some layout shifting when scrolling through the page we should try to reduce this as much as possible.

**Describe the solution you'd like**
The oEmbed response from ares contains the width and height of the social embed fallback image, can we we use these values to set a minimum width and height on the social embed container to ensure we reserve the necessary space for the social embed on the server side render,

We do not want to actually load a placeholder image, we instead want to use the width and height attributes of this as part of a media query to experiment how we could reserve blank white space on the page to prevent layout shift.

The image dimensions from Ares are not dynamic - we won't get different dimensions for different viewports so this also needs to be considered.

Not loading a placeholder image may result in poorer Lighthouse scores, so this is worth an experimentation.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Testes using the links:

* https://www.test.bbc.com/kyrgyz/23292889 --> There is a shift on this link
* http://localhost:7080/arabic/23298105 --> Images are loading slowly on localhost but I dont see any shift.

Tested with normal and slow 3G connections..
