### ISSUE TITLE
Align local data path with environment data path

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#813]
**Is your feature request related to a problem? Please describe.**
Currently, local data served over Simorgh is served over [`/data/:service/articles/:id.json`](https://simorgh.api.bbci.co.uk/data/news/articles/c0000000027o.json), and data that is served over over environments, i.e. Test, is served over [`/:service/articles/:id.json`](https://www.test.bbc.com/news/articles/c9rpqy7pmypo.json).

This causes a problem as it is complex to serve data locally and test environments in a succinct way, and aligning the route will allow ease of integration with environments.

**Describe the solution you'd like**
We should align the endpoint that serves local fixture data. Currently the Express server [statically serves the data folder](https://github.com/BBC-News/simorgh/blob/latest/src/server/index.jsx#L57).

We should serve the data over `/:service/articles/:id.json`, and should use the regex that is used in the [application routes](https://github.com/BBC-News/simorgh/blob/latest/src/app/routes/index.js#L13), appended with `.json`.

**Describe alternatives you've considered**
There is limited other viable alternatives.

**Testing notes**
Cypress tests:
- fix Cypress [data test](https://github.com/BBC-News/simorgh/blob/latest/cypress/integration/dataSpec.js)
- add test that tests body

**Comment by pjlee11** [comment]
I think a nice solution to this would be to create a `RAZZLE_DATA_PREFIX` env var which we could set in a `.env.development` file meaning that `npm run dev` would set the prefix and production builds would not use this. This would satisfy all use cases where on local, travis and env tests pass for both production and development builds.

Then in `getInitialData/index` we can change [this line](https://github.com/BBC-News/simorgh/commit/21b4d823702107277b50c96280be428b9e11c0b8#diff-0679334769cd96b7ad47b858903e3849R8) to be 
```
let url = `${process.env.RAZZLE_DATA_PREFIX}/${service}/articles/${id}.json`;
```
Where `RAZZLE_DATA_PREFIX` = `/data` on dev builds and `null` on production builds

**Comment by BogdanDogaru** [comment]
@pjlee11 that's a good idea!

For posterity: we discussed this at the refinement session we agreed to go with the solution in the description of this issue, and we will fall back on @pjlee11's solution.
