### ISSUE TITLE
Stub data requests in Cypress

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#815]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Additional context**

**Comment by BogdanDogaru** [comment]
Deprioritised for alpha-1.0 until we have a better plan on a separate E2E suite.

**Comment by pjlee11** [comment]
As the alpha goal is to be integrated with other internal applications we should keep Cypress's current behaviour which in it's current form will act as an integration test suite within the application and also as E2E tests in the deployment pipeline. If we were to do the above work we would no longer have the E2E benefit, at a time we need it most, without requiring further work to setup a dedicated E2E suite. This said we have removed the alpha label

**Comment by ChrisBAshton** [comment]
Superseded by #935.
