### ISSUE TITLE
Topic to FIX Redirects 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#8166]
**Is your feature request related to a problem? Please describe.**
There are a number of URLs that need to continue to work after forge so need to be redirected to the new pages.

Editorial have compiled a number of replacement FIX pages for redirecting in this ticket https://jira.dev.bbc.co.uk/browse/NEWSWORLDSERVICE-1071
 
**Describe the solution you'd like**
These redirects will need to be implemented in Mozart 
It's expected that this file will need updating https://github.com/bbc/mozart-routing/blob/master/src/lib/mozart_routing/middlewares/world_service_redirector.rb

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by chewu** [comment]
https://github.com/bbc/mozart-routing/pull/1660/

**Comment by chewu** [comment]
https://github.com/bbc/mozart-routing/pull/1660
