### ISSUE TITLE
Fix vulnerabilities in ws-korean-downloads

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#8182]
**Is your feature request related to a problem? Please describe.**
https://jira.dev.bbc.co.uk/browse/NEWSPALDECOM-301

Snyk is reporting major vulnerabilities in the Korean Downloads code - the report from June 2019 is attached to the Jira ticket 

It is expected that the vulnerabilities still exist, but we may want to rerun a tool like synk to ensure that we're covered 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by pharingee** [comment]
Vulnerabilities fixed on https://github.com/bbc/ws-downloads/pull/27. Npm audit returns 0 vulnerabilities for both lambdas
