### ISSUE TITLE
Add a CSS grid fallback to the footer

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#821]
**Is your feature request related to a problem? Please describe.**
Currently we have implemented the body content layout using CSS grid without a fallback. That means currently on browser like IE 11,  IE 10 [etc](https://caniuse.com/#search=grid) the page appears full width. The page should not be full width on viewports greater than 600px. 

**Describe the solution you'd like**
As in the `Footer/List` component we can specify fallback CSS, which we could make this responsive using static max-width values and percentage width values.  During this work it would be useful to pair with UX.

Example fallback block in styled components:
```
@supports not (display: grid) {
  _fallback CSS here_
}
```

**Describe alternatives you've considered**
If UX require full bleed components to be supported in non-grid layouts we could look at setting the fallback CSS on each item rather than setting it on a wrapper

**Testing notes**
Manually test browsers/devices to make sure there's no regressing with the implementation of the fallback. It would be good to specifically check iOS7 & IE9 and above as these have also been an issue.

**Additional context**
The below screenshot should be centre aligned:

<img width="1440" alt="screen shot 2018-10-18 at 14 10 34" src="https://user-images.githubusercontent.com/7791726/47156719-9b4f3700-d2df-11e8-98f5-56a8d3edef99.png">

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Using our latest browser stats we should decide how to style a page that does not support grid. Both product and UX should be involved in the decision making process.
Current thinking is this could be similar to our non-js approach where we would restrict the page to roughly 600px in width and make all content 100% width.

**Comment by pjlee11** [comment]
## Screenshots of IE9 which doesn't support CSS grid. 

_Note this is not a full bleed image and shows the content spanning the entire width of the viewport at all widths_

![1300px](https://user-images.githubusercontent.com/7791726/48475311-6d80e380-e7f4-11e8-85dc-ec9a1b63a4d7.png)

![1020px](https://user-images.githubusercontent.com/7791726/48475270-58a45000-e7f4-11e8-87ad-4c4087667027.png)

![650px](https://user-images.githubusercontent.com/7791726/48475386-91dcc000-e7f4-11e8-9a25-4c54b086c500.png)

![400px](https://user-images.githubusercontent.com/7791726/48475415-a6b95380-e7f4-11e8-8c82-c20f72a7114f.png)

**Comment by bcmn** [comment]
@jamesbrumpton was enquiring about this work, as it results in a lot of warnings on IE. Just to capture the outcome of the above ticket here:

> Discussed the screenshots of the issue alongside the browser usage stats with Jim.
> 
> In summary:
> Some WS sites see a reasonable amount of usage coming from affected versions of browsers. Instead of attempting a more full-featured fallback, we would like to establish a minimum width for the article body content on browsers that don't support CSS Grid. It's likely we will need to pair with UX to agree the specific width values.
> 
> The initial suggestion would be to be the constrained width would be static above the 1008px breakpoint, changing again at the 1280px breakpoint. The constrained width for the 0-1007 breakpoints would likely be dynamic, established as a percentage width for each breakpoint.
> 
> This work will be done in #821.

This isn't a priority for alpha 2, but I've made sure it's on the board.

**Comment by dr3** [comment]
On top of https://github.com/bbc/simorgh/pull/1160 we need a further PR in psammead https://github.com/bbc/psammead/tree/latest/packages/components/psammead-sitewide-links to add fallback support to the footer

**Comment by bcmn** [comment]
We should update the partially implemented fallback to reflect the v1.0 designs (which become slightly left-aligned as the viewport width increases) or decide whether a center-aligned fallback would be preferred.

**Comment by ChrisBAshton** [comment]
What needs to happen with that? Chat with UX?

**Comment by dr3** [comment]
Blocked on https://github.com/bbc/simorgh/issues/1318

**Comment by pjlee11** [comment]
This issue may also involve handling the width of text in the article as per the designs. If it does not we should open an issue to address this based on the stats of the browsers which require a fallback and what device widths are used compared to the designs. 

EG: Opera mini requires a fallback but is mobile-only and the designs for article text on mobile are 100% width of the article and therefore wouldn't require any changes

**Comment by sareh** [comment]
This ticket description refers to the article width non-Grid fallback, which has been carried out as part of this issue: https://github.com/bbc/simorgh/issues/1318  & is merged and now on Test and Live.  
  
There is a bug ticket for the non-Grid fallback specifically on IE8 and older: https://github.com/bbc/simorgh/issues/1404

The Footer being restricted to 1280px is captured in this issue.  https://github.com/bbc/psammead/issues/346

Closing this ticket since the remaining work is captured elsewhere.
