### ISSUE TITLE
FOOTER: Fix Hindi 'Contact us' link

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#8258]
**Is your feature request related to a problem? Please describe.**
The current Hindi 'Contact us' link in wrong. It needs updating
**Describe the solution you'd like**
Update the 'contact us' link
https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/hindi.js

      {
          href: 'https://www.bbc.co.uk/send/u50853357',
          text: 'बीबीसी से संपर्क करें',
        },

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by karinathomasbbc** [comment]
Verified on https://www.bbc.com/hindi - contact us link now points to correct URL
