### ISSUE TITLE
Integrate the "basic" timestamp component

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#826]
**Is your feature request related to a problem? Please describe.**
Integrate the component created in https://github.com/BBC-News/simorgh/issues/825 into the article.

**Describe the solution you'd like**
In the Article container render the timestamp component between the Headline and rest of the article blocks. 
```
          <MainContent>
            <Blocks
              blocks={initialHeadlineBlock}
              componentsToRender={componentsToRenderHeadline}
            />
            <Timestamp/>
            <Blocks
              blocks={restOfArticleBlocks}
              componentsToRender={componentsToRenderMain}
            />
          </MainContent>
```

**Describe alternatives you've considered**
N/A

**Testing notes**
Cypress test should be added and deep snapshots updated to ensure the timestamp is rendered. We should also test this across different browsers and devices to ensure compatibility.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
This is blocked awaiting a workshop to discuss the integration of the timestamp component.

**Comment by sareh** [comment]
This is now unblocked, since the approach to be taken was discussed and added to the issue description.

**Comment by BogdanDogaru** [comment]
Blocked on #839 (we need to split the data to integrate the component in the correct position)
