### ISSUE TITLE
Inline links styling issues

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#828]
**Is your feature request related to a problem? Please describe.**
Currently the inline links have styling bugs in the hover and focus states. This is due to the old GEL type specs seeming to differ for the new Reith font along with the fact that we have implemented the underline as a border and also have a padding top and bottom. 

**Describe the solution you'd like**
- We should remove the padding top and bottom from the inline links.
- We could swap `border-bottom` for `text-decoration: underline` - pending UX review 

**Describe alternatives you've considered**
We could re-evaluate the type specs (and get GEL to confirm the changes) to allow for the use of border bottom on inline links. EG: increase line-heights across all type specs.

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Additional context**
UX will be researching this to defined the solution. The issue https://github.com/BBC-News/simorgh/issues/616 is closely related.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### With top/bottom padding clearly overlapping ###
![image](https://user-images.githubusercontent.com/7791726/47231452-d37c7580-d3c4-11e8-8c26-56c80c88c63c.png)

### Without top/bottom padding ###
![image](https://user-images.githubusercontent.com/7791726/47231481-e727dc00-d3c4-11e8-909b-e786516f6c01.png)

### Without top/bottom padding, showing the border bottom of the previously line being cut off ###
![image](https://user-images.githubusercontent.com/7791726/47231573-2a824a80-d3c5-11e8-923b-f9457671ca53.png)

### Without top/bottom padding and using underline instead of border-bottom ###
![image](https://user-images.githubusercontent.com/7791726/47231644-5d2c4300-d3c5-11e8-8a6a-47959b930c25.png)

**Comment by ChrisBAshton** [comment]
Hi @pjlee11 - _is_ this blocked? If so, on what?

**Comment by ChrisBAshton** [comment]
Just saw "pending UX review" - so added label.

**Comment by ChrisBAshton** [comment]
@pjlee11 do the UX recommendations in https://github.com/BBC-News/simorgh/issues/616#issuecomment-444551804 apply here too?

**Comment by pjlee11** [comment]
@ChrisBAshton it's related but it's much more noticeable as a problem with the Caption. So parts of #616 would do most of the work this issue describes

**Comment by sareh** [comment]
Closed since issue is now in Psammead: https://github.com/BBC-News/psammead/issues/222
