### ISSUE TITLE
Emotion: IE11 issues

### ISSUE THREAD

**Issue by RichardPK** [bbc/simorgh#8306]
UX issues found during Browser regression tests following the Emotion migration.

Note. We have already tested across current versions of:

- [x] Safari
- [x] Firefox
- [x] Chrome

**There are a range of issues with some of the b-tier browser + OS combos that already exist on live. It is completely up for discussion if any of this needs to be fixed at all, let alone before merging**

### Issues found in browser regression test
Found by Chromatic:

1. IE 11- STY page (example below is from Chromatic running against Storybook). RTL services - secondary column has moved from left side to right. Snapshot: https://www.chromatic.com/snapshot?appId=5d28eb3fe163f6002046d6fa&id=5fa9458077839a00218171a9

This Chromatic snapshot is taken from the Simorgh storybook. It can be found within Storybook in `PAGES > Story Page > persian`

**Note - this also happens on content which makes use of multiple columns (see issue 3 below).**

left _latest_, right _emotion-ssr-all_
![Screenshot 2020-11-09 at 14 39 37](https://user-images.githubusercontent.com/9042672/98555163-80223c00-2299-11eb-84c0-b847f0b4f98f.png)

2. IE 11- OnDemand TV pages. Chromatic is reporting the page content being off-centre (ignore the lack of dark mode, that's a Chromatic ting).
**Note: This is already happening on live. May already be don't-fix**

![Screenshot 2020-11-09 at 14 32 35](https://user-images.githubusercontent.com/9042672/98554275-73511880-2298-11eb-9e91-b224b26dffb3.png)

---

Found by @LilyL0u 
3. Side column layout on STYs in Windows 7 + IE11 is pushed below the content. 

Left - _latest_, Right - _Emotion_
![Screenshot 2020-11-04 at 13 26 54](https://user-images.githubusercontent.com/9042672/98117393-95662780-1ea1-11eb-80af-159d571610cb.png)

This also happens on RTL services
<img width="1440" alt="Screenshot 2020-11-09 at 18 29 21" src="https://user-images.githubusercontent.com/9042672/98654572-66830200-2336-11eb-9330-2a69c8ff5621.png">

4. L/R Padding now being added on first child of StoryPromoUL on IDX pages, Windows 10 Firefox 48 and IE11.
![ezgif-1-a866090b997b](https://user-images.githubusercontent.com/9042672/98542225-80660b80-2288-11eb-9a23-e00e95b3fce5.gif)

**Comment by aeroplanejane** [comment]
Content is legible and accessible.

**Comment by RichardPK** [comment]
@LilyL0u is there any chance you can validate the two things that the Chromatic snapshots found in IE11?

- OnDemand TV page content is off-centre ✅  _validated but this is also a problem on live_
- Single column story page is aligned to the wrong side on RTL. This one's a bit weird... I'm not sure exactly what asset is used. The snapshot in Chromatic is here https://www.chromatic.com/snapshot?appId=5d28eb3fe163f6002046d6fa&id=5fa9458077839a00218171a9

**Comment by joshcoventry** [comment]
@aeroplanejane says it's OK to close this.
