### ISSUE TITLE
Add script to Document for server-side render

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#833]
**Describe the bug**
The scripts that are added to the page via react-helmet, i.e. [the AMP script](https://github.com/BBC-News/simorgh/blob/latest/src/app/components/Metadata/index.jsx#L33), are not added server-side rendered as they are not added to the [HTML document](https://github.com/BBC-News/simorgh/blob/latest/src/app/components/Document/index.jsx#L18-L43).

It works on pages that have the client-side React app as react-helmet on the client will just inject it into the DOM. AMP will not have the client-side React application, so needs to rely on HTML sent over the wire in the server-side render.

**To Reproduce**
1. Remove the client-side bundles from being sent
2. Create a prod build
3. View the prod build source/DOM element _or_ run the AMP Cypress specs
4. Note the lack of AMP CDN script.

**Expected behavior**
The AMP CDN script should be in the DOM when there is no client-side React application. 

**Additional context**
There is no way to remove client-side JS bundle right now - apart from manually removing code. There is [a ticket to remove the client-side bundle for AMP](https://github.com/BBC-News/simorgh/issues/728), which will help highlight and test.

**Comment by ChrisBAshton** [comment]
Is this still the case @jtart ? Sounded like we've resolved it (when talking in the AMP component meeting on Monday)

**Comment by jtart** [comment]
Still the case that scripts aren't added, but it's not an issue atm.

**Comment by ChrisBAshton** [comment]
Hmmm think this issue can be closed. We will need to think about scripts for AMP at some point at the component level, but not relevant at the moment. And the inline JS issue for AMP went away in https://github.com/BBC-News/simorgh/pull/907
