### ISSUE TITLE
Upgrade @emotion/core and @emotion/styled to new major version 11 in Simorgh

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#8348]
**Is your feature request related to a problem? Please describe.**
Upgrade `@emotion/core` and `@emotion/styled` to new major version 11.

Psammead PR 1: https://github.com/bbc/psammead/pull/4193
Psammead PR 2 (psammead-styles): https://github.com/bbc/psammead/pull/4231

Details of any breaking changes can be found here https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Fstyled%4011.0.0

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Comment by karinathomasbbc** [comment]
These PRs may also be relevant
https://github.com/bbc/simorgh/pull/8370
https://github.com/bbc/simorgh/pull/8377
https://github.com/bbc/simorgh/pull/8379
https://github.com/bbc/simorgh/pull/8380

**Comment by karinathomasbbc** [comment]
I completely forgot that an emotion upgrade would need to happen in Psammead first. I have closed the dependabot PRs as both Psammead & Simorgh would need to be upgraded in tandem.
