### ISSUE TITLE
Show Podcast promo on Russian STY pages

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#8350]
**Is your feature request related to a problem? Please describe.**
We need to promote podcast content on the Russian service.

**Describe the solution you'd like**
We should use a podcast promo component in Russian story pages.

The building of the podcast promo component will be done in https://github.com/bbc/psammead/issues/3987

**Acceptance criteria**
- should show on Russian story pages
- should be positioned in main area as the 3rd section on mobile devices
- should be positioned in sidebar as the 2nd section on all other devices
- should not show on all other services
- should be able to quickly toggle component on or off (iSite toggles?)

**Data**
Initially the data will be fixed. Refer to https://paper.dropbox.com/doc/Podcast-Brand-Promos--A_RYwZYQvGvIhwoSFM3w09tqAg-5Es8CPWRz3ItTkHwRxgOC for all data.

**Designs**
https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/dashboard

**Jira**
https://jira.dev.bbc.co.uk/browse/WSMEDIA-295

**Questions**
- where should the fixed data live? service config or iSite?

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
Looks good! In the first instance we'll use hardcoded data in Simorgh. Ideally this should be easy for us to change in a pr if necessary. 
When we add the promo to the frontpage we may use the CPS podcast promo data that we get in the frontpage feed from ares / cps

**Comment by pharingee** [comment]
Blocked until completion of https://github.com/bbc/psammead/pull/4124

**Comment by greenc05** [comment]
Why is this in a different position depending on device? And how are we intending to do this?

> should be positioned in sidebar as the 3rd section on mobile devices
> should be positioned in sidebar as the 2nd section on all other devices

**Comment by pharingee** [comment]
@greenc05 That was a typo. On mobile devices it's going to be the 3rd section because mobile devices don't have a side column. However on bigger devices the first section is directly under the main area, and the second section on the page becomes the first section on the sidebar. Which will make the third section(podcast promo) the second section on the sidebar.

Essentially, it's always the third section
