### ISSUE TITLE
400 response code for articles without headlines

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#836]
**Is your feature request related to a problem? Please describe.**
As a result of this issue: #826, when there is no headline block in the article, we just render no article, but still give a 200 response. 

We should return a `400` HTTP response code instead. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
A 422 response code was considered, since it is more accurate, but fragmenting our response codes will likely not be helpful at this time. 

**Testing notes**
Unit test should be sufficient. 

**Additional context**
This ticket is blocked, pending #826 being completed. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
I'm not sure this is truly a 4XX/client error issue? 🤔 The issue we're describing is that we can't render the data we've been given from an upstream source. The client has no control over this.

> A 422 response code was considered, since it is more accurate, but fragmenting our response codes will likely not be helpful at this time.

[422 describes an issue with the body of the _request_, originating from the client](https://httpstatuses.com/422). However, in this scenario, we can parse & act on the request perfectly well. What we're describing is that there is nothing the client could do that would allow them to correctly display the data in question.

If the data doesn't match an implied contract with our data source (i.e. "every article must include a headline"), then that implies the response should be a [502](https://httpstatuses.com/502).

Given that as far as I know the above is not a contract with our data source, then it would suggest to me that it is an [ISE, as Simorgh is making an assertion that is not always true](https://httpstatuses.com/500).

**Comment by ChrisBAshton** [comment]
+1, sounds like a 500 error to me.

**Comment by ChrisBAshton** [comment]
Articles _can_ be published without Headline blocks.

**Comment by jamesbhobbs** [comment]
@sareh There is an outstanding comment referring to this here: https://github.com/bbc/simorgh/blob/c45c717e3883b0fb4e25dc4b60b4c64235c86b13/src/app/containers/ArticleMain/index.test.jsx#L6

**Comment by jamesbhobbs** [comment]
Use correct status code, fail render of ANY page if h1 is not present.

**Comment by chris-hinds** [comment]
If we fail the render and respond with a 500 error this will put mozart into its fallback mode.
The only way to do this would be ti render the 500 error page but with a 200 response code
