### ISSUE TITLE
Relative client-side routing requests for data can make a request to different endpoint

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#837]
**Describe the bug**
Fetching data on the server makes a request to an absolute URL, where that URL is `<RAZZLE_BASE_PATH>/<path>`. The `RAZZLE_BASE_PATH` at the moment is `http://localhost:7080` across all environments, including on [Test](https://www.test.bbc.com/news/articles/c9rpqy7pmypo). This means a request for data will make a request to an internal localhost endpoint on the server.

However, data-fetching on the client makes a request to a relative URL. This means that on Test it will make a relative request for data, i.e. https://www.test.bbc.com/news/articles/c9rpqy7pmypo.json.

This is problematic as if the `RAZZLE_BASE_PATH` and origin of the relative URL are different, then data will be requested from different endpoints on the server and client.

**To Reproduce**
It is fairly difficult to reproduce as all assets locally and in the CMS match. Could be reproduced by creating different assets.

View this code: https://github.com/BBC-News/simorgh/blob/latest/src/app/routes/getInitialData/index.js#L7-L12

**Expected behaviour**
Should make requests to the same endpoint on server and client. This can be rectified by always making a request to an absolute URL on the server and client.

**Testing notes**
- Add two new articles in the CMS, to ensure the bug is not reoccurring.

**Comment by jtart** [comment]
This is blocked until Test is fully integrated e2e.

**Comment by BogdanDogaru** [comment]
Blocked until we have working inline links in our CMS
