### ISSUE TITLE
Cypress tests fail on CMS integration

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#838]
**Describe the bug**
The Cypress tests for metadata regarding description and title are failing due to the CMS not providing the required failures. 

**To Reproduce**
See error: https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh-infrastructure/detail/build-using-test-base-path/5/pipeline/

**Expected behaviour**
We should be able to integrate with the CMS and the Cypress tests pass across all environments.

**Suggested solution**
In the short term, we should comment out the failing tests until the CMS can provide these values. 

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by BogdanDogaru** [comment]
We'll re-add them in #820 and #842

**Comment by pjlee11** [comment]
Clarifying the tests to be commented out are as follows for both news and Persian:
- "should render a title" / <title>
- <meta> description
- <meta> og:description
- <meta> twitter:description

**Comment by bcmn** [comment]
Just to clarify: in addition to "should render a title", `og:title` & `twitter:title` also need to be disabled, as they use the same data.
