### ISSUE TITLE
[Spike] AMP Bind to adjust banner content/layout

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#8383]
**Is your feature request related to a problem? Please describe.**
In upcoming changes to the cookie consent banner on AMP we need to be able to "reveal" more content on a button click, sounds simple right? not so with AMP 👎 

**Describe the solution you'd like**
Can we use [AMP Bind](https://amp.dev/documentation/components/amp-bind/) to reveal more content in the cookie consent banner when a butting is clicked/press i.e. can we "expand" the banner revealing more text. AMP Bind could simply be used to hind and unhide the text.

Also when clicking this button can we change the browser focus? Can we ensure that the top element in the banner is focussed when its revealed?

This should just be a quick spike, no production ready code, no tests purely some quick work to see if AMP-Bind is required to "reveal" more content and to see how we set programatically set focus.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment]
This might also be useful: https://amp.dev/documentation/examples/user-consent/advanced_user_consent_flow/
