### ISSUE TITLE
Eliminate oneOfType warning

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#8392]
### Is your feature request related to a problem? Please describe.

Simorgh emits a propType warning:
```
Warning: Invalid argument supplied to oneOfType, expected an instance of array.
```

### Describe the solution you'd like

Eliminate this warning.

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] ~~This feature is expected to need manual testing~~.

### Additional context
https://github.com/bbc/simorgh/search?q=oneOfType

**Comment by aeroplanejane** [comment]
Closing as won't fix. cc @gavinspence
