### ISSUE TITLE
Update package.lock automatically

### ISSUE THREAD

**Issue by BogdanDogaru** [bbc/simorgh#84]
**Is your feature request related to a problem? Please describe.**
Every time Greenkeeper update one of our dependencies, our `package.lock` file falls out of date. We need to automate this in order to save dev time.

**Describe the solution you'd like**
The ideal solution would make use of https://github.com/greenkeeperio/greenkeeper-lockfile

**Describe alternatives you've considered**
- Updating the `package.lock` file manually every time (time consuming)
- Adding another build step for updating this file (unnecessarily complex)

**Additional context**
N/A.

**Comment by jamesbhobbs** [comment]
Seems like the docs here: https://github.com/greenkeeperio/greenkeeper-lockfile say that you either use this or npm ci. I'd rather continue to use npm ci and have the manual step of creating the lockfile on greenkeeper PRs than use this.

I'd appreciate a second opinion though. @sareh @pjlee11 @jtart @jp-bbc

**Comment by pjlee11** [comment]
Agreed we should stay with npm ci and not use greenkeeper-lockfile. Personally I think we should automate a script which checks out any greenkeeper created branches and does an install and commits the new package-lock.json

**Comment by jamesbhobbs** [comment]
One day far away maybe, very low priority though
