### ISSUE TITLE
Add Off-Screen Text to the Timestamp

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#840]
**Is your feature request related to a problem? Please describe.**
We need to add the off-screen text for the timestamp. This will then need to be swarmed across multiple a11y devices once this has been implemented.

**Describe the solution you'd like**
Implement off-screen text for the timestamp so that a11y tools read the timestamp out in a more human readable manner.

**a11y**
An a11y swarm will need to take place once the off-screen text has been implemented.

**Describe alternatives you've considered**
N/A

**Testing notes**
This requires a swarm with a11y tools.

**Additional context**

**Comment by bcmn** [comment]
I spoke with Catharine about this today. She is happy with there being no VHT for the Timestamp components.
