### ISSUE TITLE
Update grid-layout logic to enable full-width items

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#841]
**Is your feature request related to a problem? Please describe.**
Following the documentation of how to create a CSS grid which meets our requirements we should implement the CSS grid to match the documentation. 

**Describe the solution you'd like**
Using the documentation updated in #864 implement a CSS grid which supports the full-width / "full bleed" items.

**Describe alternatives you've considered**
N/A

**Additional context**
A storybook example of a full bleed item should be produced.

**Testing notes**
- Snapshot tests will need to be updated. Regression testing is necessary.

**Comment by BogdanDogaru** [comment]
Pending discussion on #824

**Comment by pjlee11** [comment]
Using the [CSS grid solution](https://github.com/BBC-News/simorgh/pull/824) and further [documentation](https://github.com/BBC-News/simorgh/pull/864) implement a grid that allows for full width items.

**Comment by sareh** [comment]
Closed as fixed.
