### ISSUE TITLE
Use Promo.summary value as the metadata description

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#842]
**Is your feature request related to a problem? Please describe.**
Following #838 we should re-add the metadata description cypress tests when the promo.summary is available for the CMS.

**Describe the solution you'd like**
 Re-add the metadata description cypress tests

**Describe alternatives you've considered**
N/A

**Testing notes**
Re-enabling commented out Cypress tests

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by BogdanDogaru** [comment]
Blocked pending the summary value being available through our CMS, and returning an actual value.

**Comment by ChrisBAshton** [comment]
Is this still blocked?

**Comment by ChrisBAshton** [comment]
Assigning to Jim to find out.

**Comment by jimjohnsonrollings** [comment]
Not v1.0, but still blocked.  This feature doesn't exist yet in Optimo.

**Comment by ChrisBAshton** [comment]
Related to #1423?

**Comment by jimjohnsonrollings** [comment]
Yes.  Optimo don't yet provide a summary, so #1423 was an interim alternative.

**Comment by jamesbhobbs** [comment]
Closing as impossible to do. @jimjohnsonrollings please ensure there's a JIRA issue as this is a desired product feature.

**Comment by sareh** [comment]
@BenjaminHobbs there already is a JIRA ticket for this. This issue was created as a result of that in a Story refinement session. This should be re-opened and have the 'externally blocked' label on it.
