### ISSUE TITLE
Zhongwen Radio 500 error on test 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#8420]
**Describe the bug**
Radio pages for Zhongwen are giving 500 errors on test 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/zhongwen/simp/bbc_cantonese_radio/w172xn6jsl60g8z
2. Note the error 

**Expected behaviour**
Live zhongwen radio assets from ares should be routed to test like all other radio services. 
More context in this slack thread: https://bbcnews.slack.com/archives/CJT0284G2/p1605874092361000

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
When this is run in the pipeline, this URL does not get an error, so the E2Es are not failing there:
![Image 20-11-2020 at 16 44](https://user-images.githubusercontent.com/54575620/99826029-b7250700-2b4f-11eb-8c63-ffac8b1f3c68.jpg)


However, when I run the E2Es on my computer, this URL does get a 500 error:
![Image 20-11-2020 at 16 41](https://user-images.githubusercontent.com/54575620/99825770-60b7c880-2b4f-11eb-933f-168b7d42cd2f.jpg)


https://www.test.bbc.com/zhongwen/simp/bbc_cantonese_radio/w172xf3rxfx25cj?renderer_env=live
https://www.test.bbc.com/zhongwen/simp/bbc_cantonese_radio/w172xf3rxfx25cj

**Comment by rebeccamcginn** [comment]
@aeroplanejane This should be good to close now that we have checks for missing versions

**Comment by LilyL0u** [comment]
> @aeroplanejane This should be good to close now that we have checks for missing versions

Yep and the E2Es are now passing :)

**Comment by aeroplanejane** [comment]
Nice! Thanks for sorting @rebeccamcginn and @LilyL0u
