### ISSUE TITLE
Generalise access to toggles

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#8441]
_This was an agreed action following post-incident review: "2020-11-20: Internal Server Error for On Demand Radio and TV Pages"_

**Is your feature request related to a problem? Please describe.**
We do not have a standard, safe way of accessing toggle data outside of React components (where we have the `useToggles` hook

We should have a standardised implementation that we can use across as much of our code as possible including, at least, `getInitialData` functions

**Describe the solution you'd like**
Design and implement a mechanism that can be used for this purpose, and does not throw exceptions if the toggle data is unavailable.

Update as many places as possible to use this function (including, at least, `getInitialData` functions)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
Interim protection in case schedules is toggled off globally: https://github.com/bbc/simorgh/pull/8445
