### ISSUE TITLE
Incorrect padding on onwards journeys components

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#8504]
The padding on the onward journeys components has shifted it to the right (too much padding on the left)
e.g https://www.bbc.com/russian/media-53631991

**Comment by LilyL0u** [comment]
<img width="1440" alt="Screenshot 2020-11-26 at 15 44 39" src="https://user-images.githubusercontent.com/54575620/100619396-f8b66e80-3314-11eb-84d1-ba371fbf52c4.png">

**Comment by RichardPK** [comment]
Hey I think I fixed this @LilyL0u - sorry, didn't see this issue last week when I pushed the fix. Can you confirm it's aw good now?

**Comment by LilyL0u** [comment]
Fixed
<img width="1440" alt="Screenshot 2020-12-07 at 13 19 49" src="https://user-images.githubusercontent.com/54575620/101355742-ed23f400-388e-11eb-8645-ac89715950a8.png">
