### ISSUE TITLE
Horizontal overflow affecting various page types/services

### ISSUE THREAD

**Issue by joshcoventry** [bbc/simorgh#8511]
**Describe the bug**
Something is causing horizontal overflow on our pages.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://bbc.com/gahuza
2. At viewports lower than 1339px wide, a horizontal scrollbar appears in Chrome, Safari

**Expected behaviour**
We should not have a horizontal scrollbar.

Investigate the element causing the overflow.

**Screenshots**

![image](https://user-images.githubusercontent.com/64649560/100749266-595cae80-33dc-11eb-86ea-cc208748401e.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.7.
- Browser Chrome,Safari
- Version Latest chrome

Also confirmed as happening on mobile, not just desktop.

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by simonsinclair** [comment]
An initial investigation reveals this is likely caused by the `SkipLink` (when it's hidden).

<img width="1091" alt="Screenshot 2020-12-03 at 13 12 49" src="https://user-images.githubusercontent.com/1430787/101022406-462b1980-3569-11eb-8aa1-3b6ea19981c0.png">
