### ISSUE TITLE
The data validator is throwing UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#854]
**Describe the bug**
Currently when the validator errors it silently errors which will be fixed in #853. This issue is to:
- Update the fixture (`data/test/news/c0000000005o.json`) which contains a syntax error
- Ensure the test doesn't fail silently

**To Reproduce**

1. git checkout `latest` or `bbb342edd03bc09bbaf3c03e4671aeacfc38269b`
2. `npm run test`
3. See error

**Expected behavior**
There should be no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/47572265-7a679100-d932-11e8-90fa-decf6dd5e92d.png)

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by jamesbrumpton** [comment]
LGTM
