### ISSUE TITLE
Main content overflows into secondary column

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#8558]
**Describe the bug**
When visiting pages such as https://www.bbc.com/serbian/lat/svet-52291930, the main content overflows into the secondary column; _this has only been seen in Firefox_ so far.
![image](https://user-images.githubusercontent.com/9645462/101464107-25cad880-3936-11eb-8910-8d2d42e17a4e.png)

**To Reproduce**
1. Open firefox
2. Visit https://www.bbc.com/serbian/lat/svet-52291930

Observe overflowing content

**Expected behaviour**
Content stays in main column

**Desktop (please complete the following information):**

- OS: Mac
- Browser Firefox 
- Version 82.0.2

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by RichardPK** [comment]
Possible Simorgh fix https://github.com/bbc/simorgh/pull/8563

**Comment by paruchurisilpa** [comment]
1. Update local.env with these values
SIMORGH_BASE_URL = http://www.bbc.com
SIMORGH_INCLUDES_BASE_URL =https://www.bbc.com/ws/includes
2.Restarted Simorgh and then visited http://localhost:7080/serbian/lat/svet-52291930
3.LGTM
![FireShot Capture 012 - Kako se virus korona širi svetom_ Interaktivna mapa - BBC News na srp_ - localhost](https://user-images.githubusercontent.com/1379277/102080058-b48f9780-3e05-11eb-8328-5d9be14fba6d.png)

**Comment by RichardPK** [comment]
Awesome ty @paruchurisilpa - I'll merge https://github.com/bbc/simorgh/pull/8563
