### ISSUE TITLE
Analyse & update scenarios to ensure valid use cases remain testable

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#862]
**Is your feature request related to a problem? Please describe.**
Currently, we have a [range of test data scenarios](https://github.com/BBC-News/simorgh/blob/latest/data/README.md), the majority of which are expected to fail in version 1.0. In some cases, this will prevent us from accessing the test data which features certain components -- for example, the horizontal rule component currently only exists in scenarios 11 & 14, both of which should fail by 1.0.

**Describe the solution you'd like**
We want to be confident that all valid components & use cases are covered in scenarios which will not be expected to fail in 1.0.

This ticket will review the existing scenarios for cases similar to the horizontal rule example above, & create new, valid scenarios to exhibit components as needed.

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
@bcmn just one more of your issues closed :)
