### ISSUE TITLE
White loading flash - OD TV media player

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#8638]
**Is your feature request related to a problem? Please describe.**
OD TV is in cinema-mode. The white loading background of the media player needs to be changed to match the cinema mode colour for OD TV pages.

**Describe the solution you'd like**
To replace the white loading background with #121212

![image](https://user-images.githubusercontent.com/59573468/102981573-0f5d7900-4501-11eb-8bb3-21e95cc28bb0.png)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

Morph-module PRs for implementing a dark background in Live Radio:

https://github.com/bbc/morph-modules/pull/37678/files
https://github.com/bbc/morph-modules/pull/37683/files

**Comment by rebeccamcginn** [comment]
Morph-module PRs for implementing a dark background in Live Radio:

https://github.com/bbc/morph-modules/pull/37678/files
https://github.com/bbc/morph-modules/pull/37683/files

**Comment by rebeccamcginn** [comment]
https://github.com/bbc/morph-modules/pull/39506

**Comment by LilyL0u** [comment]
Just to check, the colour change we are talking about here is not the colour of the placeholder image, but of the colour that very briefly flashes between the presentation of the placeholder image and the video? When the placeholder image is present this shows as a dark grey, and then the flash after it is black.

As in this expertly timed screenshot: 
![Image 18-01-2021 at 16 11](https://user-images.githubusercontent.com/54575620/104939071-ddc4ba00-59a7-11eb-978f-c78a96fb1a48.jpg)

The colour is a bit different from the black surrounding it, is this expected?

The colour in the frame appears to be #000000 and the surrounding colour is #121212

**Comment by rebeccamcginn** [comment]
I see what you are saying. There appear to be 4 flashes on live:

Placeholder
White flash
Black flash
Image

On test, the white flash is replaced with #121212:

![image](https://user-images.githubusercontent.com/59573468/105011247-a3552e80-5a34-11eb-862a-3ab00c5f5e8c.png)

Not ideal to still have 4.

**Comment by rebeccamcginn** [comment]
We could use the SMP events to keep the placeholder visible under the video is playable or we could change the background-color from #121212 to #000000, which would cut it down to placeholder -> black -> image

We could also do both, with the background-color change as a short term measure and the SMP events as the end goal.

**Comment by LilyL0u** [comment]
The white flash has been changed to black (there is no white flash at any point.
Rebecca will implement the SMP events method as mentioned above, so that the sequence will be placeholder -> black -> image, and it will have a separate issue. Moving to Done.
