### ISSUE TITLE
Update cookie and privacy banners to use updated designs

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#8664]
Based off JIRA NEWSWORLDSERVICE-1049
We want to update our consent banners on both canonical and amp to use updated designs:
- [x] On Canonical this consists of moving the banner to the bottom of the viewport - https://github.com/bbc/simorgh/issues/8696
- [x] On Canonical we would update the designs and address accessibility issues - https://github.com/bbc/psammead/issues/4216

**Comment by simonsinclair** [comment]
Both issues referenced here have now been completed.
Remaining work has been consolidated into the following issue: https://github.com/bbc/simorgh/issues/8668.
