### ISSUE TITLE
Restricted Video - Create Test Assets 

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#867]
**Is your feature request related to a problem? Please describe.**
When video content is restricted to a particular region, we should display the correct error message. We should have test assets for each of these scenarios and have them documented in https://github.com/BBC-News/simorgh/blob/latest/data/README.md

region restriction | region | outcome
-- | -- | --
UK only | UK | play the video
UK only | outside the UK | see the poster image + caption but no video player, and the message "Sorry, we cannot show this [video/audio/media] in your part of the world."
Non UK | UK | see the poster image + caption but no video player, and the message "Sorry, we cannot show this [video/audio/media] in your part of the world."
Non UK | outside the UK | play the video
International | UK | play the video
International | outside the UK | play the video

**Describe the solution you'd like**
We should have test assets for each of these scenarios and have them documented in https://github.com/BBC-News/simorgh/blob/latest/data/README.md

**Describe alternatives you've considered**
N/A

**Testing notes**
No test needed for this. 

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by jimjohnsonrollings** [comment]
I'll add examples of each to cmejqde986vo

International: p01k6msm and p01kdbwr
UK: p01kdbns
Not-UK: p01kdbpz
