### ISSUE TITLE
Ensure Video Respects Regional Restrictions 

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#868]
**Is your feature request related to a problem? Please describe.**
After this issue has been completed: https://github.com/BBC-News/simorgh/issues/867, we will have test assets for videos in various regions. 

**Describe the solution you'd like**
The video player should respect these regional restrictions. All scenarios should also be tested for audio.

region restriction | region of user | outcome
-- | -- | --
UK only | UK | play the video
Global | UK | play the video
Non-UK only | UK | video player shows the poster image + caption, but doesn't play the video. Should have error message "Sorry, we cannot show this [video/audio/media] in your part of the world."
Non-UK only | outside the UK | play the video
Global | outside the UK | play the video
UK only | outside the UK | video player shows the poster image + caption, but doesn't play the video. Should have error message "Sorry, we cannot show this [video/audio/media] in your part of the world."

- It is unlikely that we can override the SMP error message. 

We should have Storybook stories that include these 6 different video restriction scenarios. This would then enable us to use it as a reference for what the Video block should do in various situations.

Use a VPN to test the restriction of the video. 

**Describe alternatives you've considered**
N/A

**Testing notes**
We should test manually via using a VPN. 
We would ideally wish to add automated Cypress tests for this. 

**Additional context**
- Talk to SMP about how this is currently done. What needs to be done to enable this to work. 

Blocked pending video being rendered correctly https://github.com/BBC-News/simorgh/issues/134 & test assets being added to Storybook https://github.com/bbc/simorgh/issues/1681

**Comment by 12** [comment]
@sareh Is this a test-only issue? AFAIK SMP handles this automatically as the video PID contains the regional data.

**Comment by 12** [comment]
As the media player implementation does not live in Simorgh, I am closing this issue.
