### ISSUE TITLE
Move canonical consent banner to the bottom of the view port

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#8696]
**Is your feature request related to a problem? Please describe.**
We want to move the consent banners to the bottom of the view port to improve our CLS score. Further designs updates be captured in another issue: 

**Describe the solution you'd like**
Consider google's styles to pin the consent banner to the bottom of the view port; you can do this by inspecting our amp pages and looking at the styles.

The change would focus around the canonical consent banner here: https://github.com/bbc/simorgh/blob/latest/src/app/containers/ConsentBanner/index.canonical.jsx#L6 

**Describe alternatives you've considered**

**Testing notes**
- Update chromatic snapshots to update the position of the banner
- Full browser regression test of consent banner to check position

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Checked various pages and the banner seems to be appearing correctly on browsers..Once its merged will perform further testing on all devices.

LGTM..
