### ISSUE TITLE
Correctly configure Chartbeat component in podcast page

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#8757]
**Is your feature request related to a problem? Please describe.**
We want the ability to track Podcast pages with Chartbeat Analytics Tracking

**Describe the solution you'd like**
The same implementation as On Demand Radio and TV with the exception of the "sections" value:

This is a comma separated list, where the first value should be the name of the service, e.g. "Afrique" or "Persian" and the second value should be the name of the service appended with " - Podcasts"

Example:

```
"Arabic, Arabic - Podcasts"
```

The remaining values are the same as OD Radio:
```
ContentType = player-episode
Page Title = title + "-" + service  Example: "BBC Info - BBC News Afrique"
uid = 50924

```

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by LilyL0u** [comment]
Arabic - https://www.test.bbc.com/arabic/podcasts/p08gp8wx?renderer_env=live
Arabic, Arabic - Podcast
Canonical - type: player-episode 
Amp - contentType = player-episode
title: BBC Xtra - BBC News Arabic
uid: 50924

Burmese - https://www.test.bbc.com/burmese/podcasts/p02pc9lh?renderer_env=live
Burmese, Burmese - Podcast
Canonical  - type: player-episode
Amp - contentType: player-episode
title: Burmese Evening Broadcast - BBC News မြန်မာ
uid: 50924

Gahuza - https://www.test.bbc.com/gahuza/podcasts/p07yh8hb?renderer_env=live
Gahuza, Gahuza - Podcast
Canonical - type: player-episode
Amp - contentType: player-episode
title: Baza Muganga - BBC News Gahuza
uid: 50924

Indonesian - https://www.test.bbc.com/indonesia/podcasts/p02pc9v6?renderer_env=live
Indonesia, Indonesia - Podcast
Canonical - type: player-episode
Amp - contentType: player-episode
title: BBC Indonesia - BBC News Indonesia
uid: 50924


Nepali - https://www.test.bbc.com/nepali/podcasts/p02pc9w3?renderer_env=live
Nepali, Nepali - Podcast
Canonical - type: player-episode
Amp - contentType: player-episode
title: बीबीसी नेपाली पडकास्ट - BBC News नेपाली
uid: 50924

Persian - https://www.test.bbc.com/persian/podcasts/p02pc9wf?renderer_env=live
Persian, Persian - Podcast
Canonical - type: player-episode
Amp - contentType: player-episode
title: Pargar - BBC News فارسی
uid: 50924

Russian - https://www.test.bbc.com/russian/podcasts/p05607v8?renderer_env=live
Russian, Russian - Podcast
Canonical - type: player-episode
Amp - contentType: player-episode
title: Радиоархив Русской службы Би-би-си - BBC News Русская служба
uid: 50924

Tamil - https://www.test.bbc.com/tamil/podcasts/p03412j3?renderer_env=live
Tamil, Tamil - Podcast
Canonical - type: player-episode
Amp - contentType: player-episode
title: பிபிசி தமிழோசை - BBC News தமிழ்
uid: 50924

Zhongwen (simp and trad checked) - https://www.test.bbc.com/zhongwen/simp/podcasts/p02pc9xp?renderer_env=live
Zhongwen, Zhongwen - Podcast
Canonical - type: player-episode
Amp - contentType: player-episode
title: BBC 時事一周 Newsweek (Cantonese) - BBC News 中文
uid: 50924

**Comment by LilyL0u** [comment]
Bug being fixed https://github.com/bbc/simorgh/pull/8854
'Podcast' instead of 'Podcasts' in 'sections'

Will mark this as Done and retest with the fix issue

**Comment by rebeccamcginn** [comment]
@LilyL0u Fix is merged :)
