### ISSUE TITLE
[Investigation] Correctly configure SMP rich media tracking for podcast pages

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#8758]
**Is your feature request related to a problem? Please describe.**
- This work may already be setup correctly.
- Confirm that the current fields being sent by our morph `on-demand-radio` strategy to SMP are correct for podcasts 
- Jira is here to validate against: https://jira.dev.bbc.co.uk/browse/WSMEDIA-304

**Notes**
- We currently have the value `radioProgramme` assigned to the `playlistObject.kind` object. Podcasts actually have an `smpKind` in the ares response, and it is `radioProgramme` rather than `audio`. So this may be correct.
- The only other thing we might need to worry about is the ATI settings, but even they seem to be the same - the on-demand radio settings in morph are just using the `metadata.pageIdentifier` from ares, which seems to be defined for podcasts too

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by RichardPK** [comment]
Re-added 'blocked' label - we expect nothing needs doing on this but we'll be able to validate that when testing ATI this week.
