### ISSUE TITLE
Client-side requests for data are forbidden on Test

### ISSUE THREAD

**Issue by jtart** [bbc/simorgh#877]
**Describe the bug**
When clicking an inline link that the client-side React Simorgh app will handle, a request for data for that article is made. That request for data is forbidden and returns a 403 on the Test environments. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Visit this article: https://www.test.bbc.com/news/articles/c9rpqy7pmypo
2. Open the Network tab
3. Click on the inline link that reads 'which were later donated to local hospices'
4. In the browser, note that a white page is displayed
5. In the network tab, note that the request for https://www.test.bbc.com/news/articles/c85pqyj5m2ko.json returned a `403`

![403](https://user-images.githubusercontent.com/16549467/47787102-b53c4100-dd05-11e8-9af8-84c09127f417.gif)

**Expected behaviour**
The request for data should not be forbidden and the page should load.

**Additional context**
We should investigate what the issue is.

**Outcome**
Create an issue containing more details on how to fix this. Also as part of the new issue, ensure all tests pass (there is a Cypress test for this).

**Comment by pjlee11** [comment]
### Cors error on `.co.uk`

![image](https://user-images.githubusercontent.com/7791726/47808035-6efed600-dd35-11e8-8fb9-ef4548d4fde0.png)

### 403 error on `.com`
![image](https://user-images.githubusercontent.com/7791726/47808141-a4a3bf00-dd35-11e8-95a7-2ebc9d86f381.png)

Seems to be erring on Chrome but not on Firefox

**Comment by jimjohnsonrollings** [comment]
Could we solve the CORS issue by... not making the article available on .co.uk at all?

**Comment by sareh** [comment]
Able to replicate locally by 
- running `RAZZLE_BASE_PATH=https://www.test.bbc.com npm run dev` locally
- visiting http://localhost:7080/news/articles/c85pqyj5m2ko in Chrome
- clicking on the inline link
- I get this list of errors 

<img width="1045" alt="screen shot 2018-11-01 at 09 14 25" src="https://user-images.githubusercontent.com/3028997/47843142-9a75d500-ddb6-11e8-9322-94866b05422c.png">

Get a similar stack trace in Firefox. 
<img width="995" alt="screen shot 2018-11-01 at 09 20 26" src="https://user-images.githubusercontent.com/3028997/47843396-64852080-ddb7-11e8-8be9-8a77e7cf56b0.png">

**Comment by jtart** [comment]
Speaking with the frameworks team and @BogdanDogaru yesterday, it seems that this issue is because Test is behind a certificate.

**Comment by pjlee11** [comment]
Also the payload is curl'able

```
➜  simorgh git:(latest) ✗ curl -I https://www.test.bbc.com/news/articles/c85pqyj5m2ko.json
HTTP/2 200
server: openresty
x-cache-action: HIT
x-cache-hits: 2
vary: Accept-Encoding,X-BBC-Edge-Cache
cache-control: public, stale-while-revalidate=10, max-age=30
x-cache-age: 10
content-type: application/json
x-mrid: n1
date: Thu, 01 Nov 2018 10:28:44 GMT
x-content-type-options: nosniff
x-lb-nocache: true
x-msig: 65258c7ca553902ec467a2fbb6335501
content-length: 11691
```

**Comment by pjlee11** [comment]
Further investigation shows this seems to stem from configuration in and upstream application that we integrate with and should be solved by a combination of changes their end and #895

**Comment by jtart** [comment]
This is now fixed.
