### ISSUE TITLE
Podcast Promo - On IE11 the podcast promo is visually incorrect

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#8783]
On the browser IE11 on the Windows 7 a11y laptop the podcast promo does not look right, both on the page and in Storybook. It is fine in Chrome and Firefox.

Photo of podcast promo on the page:
![PXL_20210121_163401752 MP](https://user-images.githubusercontent.com/54575620/105384360-03e99480-5c0a-11eb-84fb-03b6261a0087.jpg)

Photo of podcast promo within Storybook canvas:
The image is missing, but otherwise looks fine
![IMG_20210121_164740](https://user-images.githubusercontent.com/54575620/105384183-d3a1f600-5c09-11eb-8624-c9edd05a7c29.jpg)

Photo of podcast promo expanded into its own frame in Storybook:
the image is missing but also the sections are not correct visually (see the second white box, and the grey section in between the title and the description)
![IMG_20210121_164754](https://user-images.githubusercontent.com/54575620/105384265-e6b4c600-5c09-11eb-8df9-4738f674848b.jpg)

I also checked this on Windows 10 on IE11 on Browserstack to check it wasnt just a Windows 7 issue. The problem is also in Windows 10 in IE11 (the side bar is also at the bottom of the page instead of at the side, but we have seen this before)
<img width="474" alt="Screenshot 2021-01-21 at 17 05 30" src="https://user-images.githubusercontent.com/54575620/105385554-63946f80-5c0b-11eb-98bb-8a277889663c.png">

**Comment by jroebu14** [comment]
For reference, this is how the component looks in modern browsers:

<img width="696" alt="Screenshot 2021-01-25 at 10 33 49" src="https://user-images.githubusercontent.com/4798332/105694495-f168a700-5ef8-11eb-846b-a0622dca092e.png">
<img width="1006" alt="Screenshot 2021-01-25 at 10 33 05" src="https://user-images.githubusercontent.com/4798332/105694504-f594c480-5ef8-11eb-90da-3d9f749c2c2c.png">
