### ISSUE TITLE
Expand E2E coverage for new AMP Cookie Banner flows

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#8810]
Part of:  #https://github.com/bbc/simorgh/issues/8668.

PR:  amp-consent-int-test

### Is your feature request related to a problem? Please describe.

The new AMP Cookie Banner has an additional user flow (see Additional context), which must be included in our E2E test suite. The source code for the new AMP Cookie Banner can be found in `cookie.amp.jsx` in the following PR: https://github.com/bbc/simorgh/pull/8718/files.

### Describe the solution you'd like

Create a branch based off `amp-bind-consent`. Ensure E2E coverage for the following flows:

**Test 1**
- AMP Cookie -> Accept

**Test 2**
- AMP Cookie -> Manage settings
- AMP Cookie -> Manage settings -> Accept

**Test 3**
- AMP Cookie -> Manage settings
- AMP Cookie -> Manage settings -> Reject

### Describe alternatives you've considered
N/A.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

### Additional context
![104318508-6c809500-54d7-11eb-8232-efd75ccef5dc](https://user-images.githubusercontent.com/1430787/106036772-a653bd00-60cd-11eb-8e36-9f427fec479b.png)

**Comment by paruchurisilpa** [comment]
The PR is merged now into base branch (amp-base-consent). Closing the ticket..
