### ISSUE TITLE
[PS AMP] Related content section title shows where there is no related content

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#8812]
**Describe the bug**
The related content section title still renders even when there is no related content to render

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.co.uk/sport/football/55790817.amp
2. Scroll down to the bottom of the page
3. See the Related Content title with no related content items

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/14273378/106123824-523eec00-6152-11eb-8e60-e52ebbb48b07.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by andrewscfc** [comment]
It _looks_ like this may be caused by an unexpected data format in related content for this story page:
```
"groups": [
    {
      "type": "related-hypers",
      "promos": [
        {
          "locators": {
            "assetUri": "/sport/40584813",
            "cpsUrn": "urn:bbc:content:assetUri:/sport/40584813"
          },
          "title": "Featured hyper: min. 10 pieces inc. 2 videos",
          "language": "en-gb",
          "timestamp": 1610952610000,
          "id": "urn:bbc:ares::asset:sport/40584813",
          "type": "hyper"
        },
        {
          "locators": {
            "assetUri": "/sport/33151178",
            "cpsUrn": "urn:bbc:content:assetUri:/sport/33151178"
          },
          "title": "Explore the BBC",
          "language": "en-gb",
          "timestamp": 1610964780000,
          "id": "urn:bbc:ares::asset:sport/33151178",
          "type": "hyper"
        },
        {
          "locators": {
            "assetUri": "/sport/football/44057186",
            "cpsUrn": "urn:bbc:content:assetUri:/sport/football/44057186"
          },
          "title": "Information hyper for football stories",
          "language": "en-gb",
          "timestamp": 1531638378000,
          "id": "urn:bbc:ares::asset:sport/football/44057186",
          "type": "hyper"
        }
      ]
    }
  ],
  "section": {
    "subType": "index",
    "name": "Gossip",
    "uri": "/sport/football/gossip",
    "type": "simple"
  },
  "site": {
    "subType": "site",
    "name": "BBC Sport",
    "uri": "/sport",
    "type": "simple"
  }
}
```
I think this code may be causing no promo to be rendered: https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx#L166 
Do we want to support this format in Simorgh or hide the entire related content section @aeroplanejane ?

Additionally all of the urls in referenced seem to 404 and the titles look a lot like placeholders for journalists but I'm not sure? Maybe these were hidden on the PAL?

**Comment by aeroplanejane** [comment]
The promo type we support are called "see-alsos"
see "type": "see-alsos", on https://www.bbc.com/mundo/noticias-internacional-47339295.json 

We want to hide / suppress the related content section if see-alsos are not present. 
On the standard Webcore canonical page you can see they are not present: https://www.bbc.co.uk/sport/football/55790817
