### ISSUE TITLE
Emotion 11 - 'Recent Episodes' text on OD TV is now in grey on black background

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#8816]
When testing the new Emotion 11 changes I noticed the 'recent episodes' component text on OD TV has become grey in colour. As OD TV is in dark mode, the background is black and the text needs to be white to have a great enough contrast.

See where pink/purple arrow indicates

<img width="1220" alt="Screenshot 2021-01-27 at 17 21 01" src="https://user-images.githubusercontent.com/54575620/106132027-50c5f180-615b-11eb-8046-894ff446a649.png">

**Comment by ryanmccombe** [comment]
This should be fixed in latest / live 🥳

**Comment by LilyL0u** [comment]
Fixed
<img width="941" alt="Screenshot 2021-02-18 at 16 16 24" src="https://user-images.githubusercontent.com/54575620/108386672-c5dd9180-7204-11eb-9911-a419d8bc1f44.png">
