### ISSUE TITLE
Translations appearing in wrong places for AMP Consent banner

### ISSUE THREAD

**Issue by paruchurisilpa** [bbc/simorgh#8848]
While building e2e's we noticed that the translations for parts of the text appear to be in the wrong places (doesn't say reject and accept on the buttons in the 'manage settings' expanded banner for example).

Service: Persian

Worth checking if its the case for other services too.

Will make a list of the services on this ticket for which the translations might be in wrong place
<img width="1440" alt="screenshot_2021-02-04_at_12 38 17" src="https://user-images.githubusercontent.com/1379277/107020924-63fc4100-679b-11eb-80ff-a7c874dc4b71.png">
<img width="1440" alt="screenshot_2021-02-04_at_12 39 19" src="https://user-images.githubusercontent.com/1379277/107020948-6a8ab880-679b-11eb-9a84-62ddccd23255.png">

**Comment by andrewscfc** [comment]
Just a note to update Naidheachdan translations when this issue is picked up.

**Comment by andrewscfc** [comment]
Update ukranian translations from spreadsheet as part of this issue

**Comment by paruchurisilpa** [comment]
https://docs.google.com/spreadsheets/d/1foxSxvod_C9WR1YW7PsEehyU95RnrHaxS_pq435rOp0/edit#gid=0

All the fixes are working. The ones that still need fixing have to be raised as separate isses , this issue can be closed pending raising tickets..
