### ISSUE TITLE
Ensure SMP Rich Media Tracking is correct in ATI for PS 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#8858]
**Is your feature request related to a problem? Please describe.**
Ensure rich media tracking is enabled correctly in ATI for Public service 
This is to ensure that media tracking is being tracked in the right place. 

**Describe the solution you'd like**
Set up for each service (tbc)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
ATI destination is coming from here: https://github.com/bbc/morph-modules/blob/master/news-av-player/src/smp.js#L16-L39

`product` is also hardcoded to "news" here: https://github.com/bbc/morph-modules/blob/master/news-av-player/src/smp.js#L123 - this is responsible for the red branding

**Comment by ryanmccombe** [comment]
Should be sorted now - https://www.bbc.co.uk/sport/football/55790817.amp
