### ISSUE TITLE
Reconcile InlineLink container files

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#887]
**Is your feature request related to a problem? Please describe.**
Currently there are both `.index|.test|.jsx` and `index.new|.test|.jsx` files in `containers/InlineLink` these are artifacts from the [work to implement fragments/urlLinks](https://github.com/BBC-News/simorgh/pull/780).

![image](https://user-images.githubusercontent.com/7791726/47858624-6a452b00-dde4-11e8-8525-5d9977913235.png)

**Describe the solution you'd like**
- We should overwrite the files without `.new` from the `.new` files. 
- We should ensure all components using the non `.new` files suffer no regression, if so fix
- We should  ensure all components using the `.new` files are updated following the reconciliation.

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Additional context**
The [issue around caption rendering logic](https://github.com/BBC-News/simorgh/issues/801) has potential to affect this ticket 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
~Blocked on #1016: `index.jsx` is currently used by `containers/Text`, so we can't remove it yet.~

Also blocked on #1017: we'll scrap our current (unfinished) implementation of inline links inside Captions, deleting the related tests at the same time. That will make #887 a smaller PR.
