### ISSUE TITLE
Reorder schedule promo cards

### ISSUE THREAD

**Issue by pharingee** [bbc/simorgh#8897]
**Is your feature request related to a problem? Please describe.**
The order of the radio schedules is not easy to understand

**Describe the solution you'd like**
Change the order of the promos on the schedule component on the 400px, 600px and 1008px breakpoints. 

Order sequence: https://zpl.io/2GLQEXm

The order is reversed on the 600px and 1008px breakpoints for RTL languages. 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
Reopening for testing
