### ISSUE TITLE
Cannot scroll to/access top of manage settings page of cookie banner

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#8899]
**Describe the bug**
Bug affects a branch, not an issue on live: https://github.com/bbc/simorgh/pull/8718

On mobile devices, the top of the manage settings page is inaccessible:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/9645462/108393104-41424180-720b-11eb-820c-b678721c7f48.png">
When you click the 'Manage my settings' button you land on a page that appears to be scrolled 'part way' down - you cannot scroll to the top.

**To Reproduce**
Below are the _exact_ reproduction steps where the issue was discovered; visiting this storybook link from the PR also allows you to replicate the issue: https://5d28eb3fe163f6002046d6fa-lmnlzwmenv.chromatic.com/iframe.html?id=containers-consent-banner--amp&viewMode=story 
Please visit this url instead of steps 1-2 if you want a quick reproduction.

Steps to reproduce the behaviour:

1. Follow these instructions to setup Simorgh for cross device testing: https://github.com/bbc/simorgh/blob/latest/docs/A11y-Testing-Cross-Device.md
2. http://YOUR_IP:7080/news.amp on an incognito tab in Chrome
3. Click 'OK' on the privacy banner
4. Click 'Manage my settings' on the cookie banner
5. Observe the inaccesible content

**Expected behaviour**
All content including the heading visible and is scrolled to the top.

**Smartphone (please complete the following information):**
- Device: Honor BKL-L09
- OS: Android
- Browser: Chrome
- Version: 88

_This issue has also been reported on:_
- Firefox, Android
- Safari, iOS

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment]
I cannot reproduce this on desktop so I suspect its todo with the browser chrome/ui on mobile 
![image](https://user-images.githubusercontent.com/14273378/108483533-c15fba00-7292-11eb-86a3-f8663196d293.png)
