### ISSUE TITLE
Improve Screenreader UX for Radio Schedules Promos

### ISSUE THREAD

**Issue by pharingee** [bbc/simorgh#8904]
**Describe the solution you'd like**
Improve screenreader UX for radio schedules promo by announcing 'Listen' and the duration of the episode for standard, live and next promo cards.

JIRA: https://jira.dev.bbc.co.uk/browse/WSMEDIA-248

## Announcement
Standard promo (Not live or next) : Listen, [brand title], [start time], Episode [episode title], duration [duration]
Live: Listen Live, [brand title], [start time], Episode [episode title], duration [duration]
Next: Listen Next, [brand title], [start time], Episode [episode title], duration [duration]

### Promo - Type - Standard
Given I use a screen reader
When I navigate to a standard radio schedule promo e.g. not live or next
And I am navigating via headings and links
Then the following should be announced as part of the heading/link: Listen, [brand title], [start time], Episode [episode title], duration [duration]

### Promo - Type - Live
Given I use a screen reader
When I navigate to a LIVE radio schedule promo
And I am navigating via headings and links
Then the following should be announced as part of the heading/link: Listen Live, [brand title], [start time], Episode [episode title], duration [duration]

### Promo - Type - Next
Given I use a screen reader
When I navigate to a NEXT radio schedule promo
And I am navigating via headings
Then the following should be announced as part of the heading: Listen Next, [brand title], [start time], Episode [episode title], duration [duration]
 
Given I use a screen reader
When I navigate to a next promo
And I am navigating via links
Then the next promo should not be announced

### Duration
Given I view the html for the radio schedule
When the media duration is viewed
Then this must be written with a comma to separate hours, minutes and seconds e.g. [00,00] or [00,00,00]
And this must be prefixed with the word ‘Duration’ e.g. Duration 00,00
 
Given the duration has already been announced to screen readers in the promo 
when I navigate to duration 
it is hidden to screenreaders 
 
Given I am viewing the radio schedule
When I CSS is not available
Then I should be able to see the audio icon and the duration numbers

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by rebeccamcginn** [comment]
https://github.com/bbc/psammead/pull/4376

**Comment by rebeccamcginn** [comment]
Closed by automation - reopening

**Comment by rebeccamcginn** [comment]
Closed by automation - reopening

**Comment by LilyL0u** [comment]
Checked on Hausa
Talkback - reads Listen, Listen Next
NVDA - reads Listen, Listen Next
JAWS - reads Listen, Listen Next. Although it sounds like it says 'aa' before 'listen', not sure what that is but it says it on everything and does still say listen. Maybe it is saying 'ha' as the hausa language code.

Waiting for a live programme in the schedule

**Comment by LilyL0u** [comment]
Live tile on Swahili -
NVDA - reads out 'Listen live' in English. Is this an expected lack of translation @rebeccamcginn ?


Live tile disappeared while starting another screenreader aaargh

**Comment by rebeccamcginn** [comment]
@LilyL0u Yep, not been provided by editorial

**Comment by LilyL0u** [comment]
> @LilyL0u Yep, not been provided by editorial

OK, good. I'll wait until I find another live tile to test on the other screenreaders!
