### ISSUE TITLE
Photo Gallery Page - unexpected indentation on left of Related Content component

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#8911]
On photo gallery pages there is an unexpected space on the side of the related content component (on the left side on LTR and the right side on RTL)

LTR https://www.bbc.com/zhongwen/trad/chinese-news-49065935
<img width="1136" alt="Screenshot 2021-02-24 at 11 47 58" src="https://user-images.githubusercontent.com/54575620/108996829-ce1b4e00-7696-11eb-95fe-0e7ecea6cf1f.png">

RTL https://www.bbc.com/urdu/pakistan-48242478
<img width="1137" alt="Screenshot 2021-02-24 at 11 51 56" src="https://user-images.githubusercontent.com/54575620/108996874-db383d00-7696-11eb-8ca8-80f884727a2a.png">

This is not happening on related content on MAPs. The layout of related content on MAPs is also only one item in each row, whereas on photo galleries it appears to be two on each row (as in the Urdu screenshot).

<img width="896" alt="Screenshot 2021-02-24 at 11 48 23" src="https://user-images.githubusercontent.com/54575620/108997052-120e5300-7697-11eb-970f-a93bc22a0c5d.png">

Bizarrely, when you translate the page, the indentation disappears and is correct!

<img width="1147" alt="Screenshot 2021-02-24 at 11 48 11" src="https://user-images.githubusercontent.com/54575620/108997158-2fdbb800-7697-11eb-88d7-fcaa5c39b688.png">

Seen on firefox and chrome

**Comment by RichardPK** [comment]
I _ think_ the margin on this element might just need removing? 

<img width="1057" alt="Screenshot 2021-03-03 at 11 54 05" src="https://user-images.githubusercontent.com/9042672/109802062-3b8b2980-7c17-11eb-8d8f-11d340b261ea.png">

@mukama - this is an issue within PGL (Photo Gallery Pages) on Simorgh,  you can get local urls to view these pages here https://github.com/bbc/simorgh/blob/latest/docs/Simorgh-Release-Info.md (v useful doc - worth bookmarking). You can recreate the bug locally on the Zhongwen 'trad' local example in that doc - `zhongwen/trad/chinese-news-49065935`

I think this is the place where the component is used on this PGL page https://github.com/bbc/simorgh/blob/e470060cd6a1853cd58cb18435f02c653de097bc/src/app/pages/PhotoGalleryPage/PhotoGalleryPage.jsx#L134

**Comment by SetJackal** [comment]
Tested, works as expected. See screenshots showing correct alignment. 

![1](https://user-images.githubusercontent.com/52279739/110756810-91c52180-8242-11eb-8adb-a397086edd8a.jpg)
<img width="879" alt="2" src="https://user-images.githubusercontent.com/52279739/110756819-938ee500-8242-11eb-92eb-857ab4a4a84f.png">
