### ISSUE TITLE
Refactor includes data fetching to to use the existing fetchData method

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#8922]
**Is your feature request related to a problem? Please describe.**
We recently set a custom user-agent string on our data fetch to help the operations team identify request being made by Simorgh. 

See the PR here: https://github.com/bbc/simorgh/pull/8905

**Describe the solution you'd like**
The include [pre-processor](https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/include/fetchMarkup/index.js#L21) currently uses `isomorphic-fetch` directly instead of using the exiting [fetch data method](https://github.com/bbc/simorgh/blob/latest/src/app/routes/utils/fetchPageData/index.js)

We should refactor the includes work to use this method instead, that way we only use a single method for data fetching across the entire codebase and any logging, fetch options etc only need to be specified in one location.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
Revisit are part of BFF
