### ISSUE TITLE
Consider caching approach changes for static assets

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#8931]
**Is your feature request related to a problem? Please describe.**
Arising from feedback on https://github.com/bbc/simorgh/pull/8916

Specifically around:
* Setting a hash in the URL so that caches can be longer but updates can be released
* Consistently setting the `strict-transport-security` value to a longer value

**Describe the solution you'd like**
* Consider the above suggestions and decide whether to implement them, or other ideas

**Comment by eagerterrier** [comment]
akamai supports query strings, so adding version `?v=1` would work if we needed quick updates. Also, happy with `strict-transport-security` value for now.
