### ISSUE TITLE
Investigate better fallback UI for clientside render failure

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#8936]
**Is your feature request related to a problem? Please describe.**
During an incident where we were unable to render pages on Opera Mini Extreme Mode, we experienced an error state where the clientside render completely failed, showing a white screen with no content - we need a better fallback UI for this scenario.

**Describe the solution you'd like**
A user consumable error page of some kind:
- Maybe just show a 500 page?
- Maybe show a specific page for clientside failures encouraging the user to report the error?
- Maybe the error page calls back to some API to tell us a clientside render failure has occured?

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by HarveyPeachey** [comment]
Not sure if this helps, but Opera have a [blog post](https://dev.opera.com/articles/opera-mini-and-javascript/) with some useful information about Opera Mini in extreme mode, it might be a bit outdated as the last update was in 2015
