### ISSUE TITLE
Document how to test/debug Opera Mini Extreme Mode

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#8937]
**Is your feature request related to a problem? Please describe.**
During an incident where Opera Mini Extreme Mode no longer rendered our pages due an error in clientside rendering, we were not able to debug/test our pages using a local development build as we could not replicate the intermediate browser used to render pages in extreme mode.

**Info from Opera dev:**

* Extreme mode is a proxy with server-side full web browser engine.
* Regadring running Dragonfly, in addressbar go to opera:config#DeveloperTools|DeveloperToolsURL address and put there http://dragonfly.op-test.net 
* Regarding enabling extreme mode on desktop - it doesn't need to be enabled.  The desktop client uses the same web browser engine as the proxy servers so if your page renders correctly in the desktop client, there's high chance it will work in Opera Mini for Android Extreme mode as well.  There are some differences, most notably time limit for JavaScript execution, longer JavaScript event handling because of client-server roundtrip or severly limited webfonts support.

**Describe the solution you'd like**

-  We have downloaded the opera desktop browser from [this link](https://ftp.opera.com/ftp/pub/opera/mac/1216/) 
-  On Mahave and Catalina managed to get Opera and Dragonfly working, however pages do not seem fully functional on it.
- On Catalina  page loads, links are clickable but images are not loading.
- On Mahavepage loads like bbc.com/hausa (examples in screenshots), but the page appears to be always loading and clicking on links does not navigate me to another page. There are some errors in the console.

**Describe alternatives you've considered**
* Test Opera Mini in Extreme mode on the smartphone for testing purposes, and if and when we see issues we use this browser version as a debugging tool. 

**Testing notes**
* Use Opera Mini Extreme Mode on a device for exploratory and regression testing .
* We have also added Opera mini to our agreed browser list - https://confluence.dev.bbc.co.uk/display/news/January+2020+-+Agreed+browser+support+for+Simorgh , so will be covered in exploratory and regression testing.

![opera](https://user-images.githubusercontent.com/1379277/111351144-c68a0c00-867a-11eb-9347-feea4fb650b7.jpg)
![opera1](https://user-images.githubusercontent.com/1379277/111351171-cdb11a00-867a-11eb-8e36-c90461eeeb9b.jpg)

**Comment by paruchurisilpa** [comment]
We will solely use Opera Mini in Extreme mode on the smartphone app for testing purposes, and if  we see issues we use this browser version as a debugging tool. Rest of the details are mentioned above in the issue itself above. Closing this..
