### ISSUE TITLE
Investigate Automated Testing of Opera Mini Extreme Mode

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#8938]
**Is your feature request related to a problem? Please describe.**
We experienced an incident where Opera Mini Extreme Mode no longer rendered our pages due an error in clientside rendering, we would like to try and catch errors like this automatically in future in CI.

**Describe the solution you'd like**
- Investigate using 'web page test' in our CI to test a subset of our pages in Opera Mini Extreme mode.
- Produce a prototype script we could use in CI
- Add it to CI if it proves simple

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by HarveyPeachey** [comment]
# WebPageTest Opera Mini Extreme Mode
Having a look at [WebPageTest](https://webpagetest.org/), they provide a testing suite which gives the ability to test against 3 different android devices that run Opera Mini (Extreme Mode). This can be shown by installing their [NodeJS wrapper](https://github.com/marcelduran/webpagetest-api) and using the command `webpagetest locations`, which provides us the different server locations and devices that are available for testing. In the list we are given 3 devices which use Opera Mini (Extreme), they are the Moto G4, Moto G6 and Moto G, which are the same devices that are available through the website.

However looking at the [API product page](https://product.webpagetest.org/api) it looks like Opera Mini browser is not available to be used through the API. There is a command `webpagetest locations --key API_KEY` which can be found on the [NodeJS wrapper docs](https://github.com/marcelduran/webpagetest-api#2-get-api-available-locations), but you need a valid API key to do this, but to get an API  key you need have a paid subscription.

I have contacted Catchpoint who are the owners of WebPageTest to clarify if the Opera Mini devices are accessible through the API, an individual of the support team has contacted the WebPageTest team to get back to me through email. I've also posted on their [forum](https://forums.webpagetest.org/t/android-opera-mini-extreme-devices-api-support/11759) as well.

If we do get confirmation that this is available through the API we can use the [official GitHub action](https://github.com/WPO-Foundation/webpagetest-github-action) to integrate this with our current CI setup. I'm not sure how often we want to run this, in my mind doing this for every single PR might be costly based on the [subscription prices](https://app.webpagetest.org/ui/entry/wpt/signup?enableSub=true&utm_source=product&utm_medium=button&utm_campaign=apisub&utm_content=b). It would make sense to carry out the action on merging into latest, then we can catch it before it's pushed to code-build and deployed. Or we could make use of the [NodeJS wrapper](https://github.com/marcelduran/webpagetest-api) and have it run through code-build. Both should be pretty trivial to setup as they're both well documented. With GitHub actions we can specify a [test spec](https://github.com/marcelduran/webpagetest-api/wiki/Test-Specs) that we provide as budget parameter in our action configuration, so we can determine if the page has rendered, for example maybe using [firstContentfulPaint](https://github.com/WPO-Foundation/webpagetest-github-action#setting-performance-budgets).

We could also host a [private instance](https://docs.webpagetest.org/private-instances/) of WebPageTest. This would mean having to run a web server and VM to emulate Opera Mini Extreme on android as the testing device.

**Comment by HarveyPeachey** [comment]
A [reply](https://forums.webpagetest.org/t/android-opera-mini-extreme-devices-api-support/11759/2) from the WebPageTest team:

> No, the physical mobile devices (Android or iOS) are not available through the API currently. Mobile testing through the API uses Chrome’s mobile emulation from the cloud nodes.
> 
> Deploying and scaling the mobile devices so they can be used through the API is being looked at but odds are that if/when it gets deployed that tests on actual mobile devices will be significantly more expensive.

**Comment by HarveyPeachey** [comment]
As discussed in the post incident review, we're looking into other alternative methods of detecting rendering issues, hopefully using [client side error reporting](https://github.com/bbc/simorgh/issues/8936). As shown from this investigation WebPageTest's API doesn't currently support what we need, this may change and we may re-open this issue.
