### ISSUE TITLE
ServiceContext is providing the wrong value for `service` on AMP

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#8940]
### Describe the bug

ServiceContext is providing the wrong value for `service` on AMP.

### To Reproduce
Steps to reproduce the behaviour:

1. Log the value of `service` from a component consuming ServiceContext.
2. `yarn build:test:debug` (this can also be reproduced in development)
3. `yarn start`
4. Visit any AMP page.
5. See terminal output.

Note:
- You may see more than one log per request, which could suggest we are rendering pages more than once.
- Log output in development mode also suggests this bug could be affecting the endpoint toggles are fetched from.

### Expected behaviour
As with Canonical:
1. One log per request.
2. The correct service.

### Screenshots

A request to http://localhost:7080/mundo.amp:
![Screenshot 2021-03-04 at 10 53 16](https://user-images.githubusercontent.com/1430787/109954253-07783d00-7cd9-11eb-92e6-85e4ed8543fa.png)

### Testing notes

- [x] This bug fix is expected to need manual testing.

### Additional context

None.

**Comment by HarryVerhoef** [comment]
Which component did you put the log in to find this? I tried the ConsentBanner and Navigation components, both logged the correct service, and the ConsentBanner logged twice but the Navigation component logged just once.

EDIT: The reason the ConsentBanner was logging twice for me was that the privacy and cookie banners are rendered on top of each other in Amp, this works perfectly fine though:
https://github.com/bbc/simorgh/blob/f1bab164a091bda53193c96fa686c4321322de76/src/app/containers/ConsentBanner/index.amp.jsx#L49-L63

**Comment by simonsinclair** [comment]
> Which component did you put the log in to find this? I tried the ConsentBanner and Navigation components, both logged the correct service, and the ConsentBanner logged twice but the Navigation component logged just once.

- You should be able to log from any component that is a child of Service Context.
- The bug starts on the server, so I would recommend reading from the terminal.

@chris-hinds and I were going to catch up about this tomorrow morning. I'll check to see if you're around to join. 👍🏼

**Comment by HarryVerhoef** [comment]
> * You should be able to log from any component that is a child of Service Context.
> * The bug starts on the server, so I would recommend reading from the terminal.

These logs were in the terminal, the files I put the logger in were:
`src/app/containers/ConsentBanner/Banner/index.amp.jsx`
`src/app/containers/Navigation/index.amp.jsx`

**Comment by aeroplanejane** [comment]
Closing as won't fix. cc @gavinspence
