### ISSUE TITLE
[PS AMP] Revert temporary disabling of Newsround secondary data fetching.

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#8944]
**Is your feature request related to a problem? Please describe.**
Newsround fetches its secondary data from a slightly different api endpoint than the rest of news. We made an update to the Mozart payload to support this however it wasn't merged in time.

This [PR](https://github.com/bbc/mozart-routing/pull/1777) temporarily disables secondary data fetching for Newsround. This should be reverted once Mozart PR #1777 is live.

**Describe the solution you'd like**
Revert this PR or manually remove the changes it introduced.

**Comment by aeroplanejane** [comment]
Done. Secondary column supported here: https://www.bbc.co.uk/newsround/56827208.amp
Closing
