### ISSUE TITLE
Promote podcast content on home pages

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#8957]
**Is your feature request related to a problem? Please describe.**
We want to promote podcast content on home pages.

**Describe the solution you'd like**
We currently have the capability to promote podcast content on home pages. Editorial teams are able to do this using CPS. We currently render podcast promos using the StoryPromo component. We instead want to use the PodcastPromo component. We would like to support this on home pages & other IDX pages.

### Design

The only example of podcast content being promoted via a StoryPromo can be found here https://www.bbc.com/zhongwen/simp

It looks like this:

Zeplin - https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294?seid=5fad76c342e8332662e9448b

![Screenshot 2021-02-18 at 16 28 12](https://user-images.githubusercontent.com/4798332/110345576-a3ca7880-8026-11eb-8f4a-a882204fe783.png)

Using the PodcastPromo component (from [Psammead](https://bbc.github.io/psammead/?path=/story/components-podcastpromo--default)) it should look something like this:
<img width="599" alt="Screenshot 2021-03-08 at 15 56 03" src="https://user-images.githubusercontent.com/4798332/110345740-cf4d6300-8026-11eb-8aff-8df3d9c56c6f.png">

We will need to adapt the PodcastPromo UI so that the image and text content is not stacked on desktop view as it currently is by default because of its adaptability to the sidebar on story pages. Needs discussion on the best way to do this.

### Data

The data from Ares for this home page can be found here https://www.bbc.com/zhongwen/simp.json

The podcast promotional data part looks like this:

```json
 "type": "podcast-promotion",
        "title": "Podcasts",
        "items": [
          {
            "name": "《时事一周》（粤语）",
            "summary": "最新节目内容（13-02-2021）：拜登终于与习近平通话：缅甸示威有人中弹：中国敢言女企业家被判刑",
            "indexImage": {
              "id": "116945588",
              "subType": "index",
              "href": "http://c.files.bbci.co.uk/159EA/production/_116945588_bidenxireuters.jpg",
              "path": "/cpsprodpb/159EA/production/_116945588_bidenxireuters.jpg",
              "height": 1080,
              "width": 1920,
              "altText": "拜登与习近平",
              "copyrightHolder": "Reuters",
              "type": "image"
            },
            "uri": "http://www.bbc.com/zhongwen/simp/institutional-38228429",
            "aresUrl": "https://ares-api.api.bbci.co.uk/api/asset/zhongwen/simp/institutional-38228429",
            "contentType": "Podcast",
            "assetTypeCode": "PRO",
            "timestamp": 1481007686000,
            "type": "link"
          }
        ],
        "strapline": {
          "name": "播客精选"
        },
```

We need to extract the relevant parts and feed this into the PodcastPromo component.

The data we need is:
- promo title
- brand title
- brand description
- image src
- image alt
- link text
- link href

### Acceptance Criteria
```
Given I am on the homepage for these services:
- Arabic
- Burmese
- Gahuza
- Hausa
- Hindi
- Indonesian
- Nepali
- Persian
- Russian
- Zhongwen
- Brasil
- Marathi

When I scroll to the podcast promotional section

Then I see the new PodcastPromo component and not the StoryPromo component
```

TODO Add link here to PodcastPromo a11y criteria

### Translations
https://docs.google.com/spreadsheets/d/1f1x53UDjmzJCf0Pv94t1AOPceCapolFxeu77LMyA4IM/edit#gid=757630729
For "episodes" see "Label that is displayed on Podcast promo"

### Questions
- IDX pages included? YES

### Jira
https://jira.dev.bbc.co.uk/browse/WSMEDIA-320

**Testing notes**
- Setup podcast promo in test CPS and have conditional to not show on live (then remove conditional for going live)
- Unit tests
- Integration tests

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by gavinspence** [comment]
Given this is not straightforward, I'd rather we spend more time investigating other possible solutions which don't rely on CPS before picking this type of promo up again. 

Editorial teams will still be able to promote Podcasts for the time being.

**Comment by aeroplanejane** [comment]
Closing from github and moved to NEWSWORLDSERVICE-1422 - requires UX work and investigation of solution. cc @gavinspence @joshcoventry
