### ISSUE TITLE
[PS AMP] Enable News, Sport, Newsround e2e tests for AMP pages

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#8960]
**Is your feature request related to a problem? Please describe.**
We are now/soon to be rendering STY and CSP assets for News, Sport and Newsround we should ensure these are included in our end to end test suite.

**Describe the solution you'd like**
- Extend our e2e test to run run again News, Sport and Nesround STY and CSP assets 
- Simorgh only renders the .amp variants of these of these assets so we should not test the canonical

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Merged the PR and moved to Done..
