### ISSUE TITLE
Podcast promo image on IE11

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#8964]
**Describe the bug**
The podcast promo image is huge

![Image from iOS (7)](https://user-images.githubusercontent.com/4798332/110480585-8ce75d00-80de-11eb-8a7b-eb891b166a77.jpg)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/arabic/podcasts/p02pc9qc
2. Observe huge image

**Expected behaviour**
The image should not be huge as shown in designs or other browsers

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Internet Explorer
- Version: 11

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by mukama** [comment]
It looks like fallbacks for the grid component are not working site wide. Fixing the [Grid component ](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-grid) will automatically resolve this issue
