### ISSUE TITLE
Third party links title incorrect size

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#8967]
**Describe the bug**
The size of the title is slightly incorrect -
1008+px (Russian & Arabic) - title is 24px, design specifies 20px
240-600px (Russian & Arabic) - title is 20px, design specifies 18px

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/russian/podcasts/p05607v8 or https://www.bbc.com/arabic/podcasts/p08z9x26
2. Scroll down to Third Party Links
3. See error

**Expected behaviour**
Title should be to spec

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by mukama** [comment]
Hi @gavinspence

I noticed from the design in psammead that the `SectionLabel` component was defined globally with 24px at 1008+px. Could you please share a link to the design? Thank you.
