### ISSUE TITLE
BUG - Ads - Front page Arabic Ads have error outside the UK on amp

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#9023]
The E2Es kept failing on the Arabic front page on amp with an error coming from the application code, not Cypress.
Andrew helped me investigate: We couldn't see any console errors when replicating the test steps, so we then tried replicating it in Ireland where AWS runs the tests. In Ireland, where ads are shown, there is an error on the Ads on the Arabic front page on amp. As it doesn't happen with every test run, this could be due to the domain of some/one of the ads, but the others are fine. 

Screenshot of errors in console:

<img width="1037" alt="Screenshot 2021-04-01 at 14 47 55" src="https://user-images.githubusercontent.com/54575620/113303849-6392a900-92f9-11eb-99bc-52a77399f05e.png">

and of ad not showing visually:

<img width="1153" alt="Screenshot 2021-03-31 at 13 48 46" src="https://user-images.githubusercontent.com/54575620/113146725-ed724180-9227-11eb-98ca-ff188e7798fb.png">

**Comment by aeroplanejane** [comment]
Hey @LilyL0u do know what the test is checking? ie/ Is it checking that there is a full ad being displayed or just the presence of the placeholder exUK? We don't care _too_ much about ads being displayed on frontpages (STYs are most important) and sometimes not being displayed - that is often outside our control and depends on ad bidding, the GNL plugin etc. 
Sometimes if the campaign has not been sold then no ad will display, but we will see the placeholder if user is outside UK, ads have been enabled etc. 
I wonder if the test is necessary? And if it's not maybe we can disable it?

**Comment by LilyL0u** [comment]
> Hey @LilyL0u do know what the test is checking? ie/ Is it checking that there is a full ad being displayed or just the presence of the placeholder exUK? We don't care _too_ much about ads being displayed on frontpages (STYs are most important) and sometimes not being displayed - that is often outside our control and depends on ad bidding, the GNL plugin etc.
> Sometimes if the campaign has not been sold then no ad will display, but we will see the placeholder if user is outside UK, ads have been enabled etc.
> I wonder if the test is necessary? And if it's not maybe we can disable it?

The test doesn't check the ad - it is a test that visits one of the H3 links, checks it works, and returns to the front page with cy.go(back) and checks it has returned to the front page. So unrelated to the ads, but the error from the application causes the test to fail.

If we don't care about the application error we could try to catch the error so it doesn't fail tests. If we do want to prevent this application error (probably better than leaving it there?) this test is a good way of seeing if it has been fixed or if it comes back. If it is out of our control to fix, perhaps the error could be caught or dealt with in the application code rather than in the tests.

**Comment by LilyL0u** [comment]
Basically it is an error in the application, not in the tests. If we catch the error in the tests (for an unrelated error to the test), it is just hiding an error that is still there. It also might mean that if anyone adds any more front page tests, they have to add another catch for this unrelated error.

**Comment by aeroplanejane** [comment]
Thanks @LilyL0u 
in the screengrab I see a CSP error and an application error - so we need to fix the cause of the application error and possibly update our CSP 
Screenshot 2021-04-01 at 10.39.48.png 

The impact of NOT fixing this bug is:
- It causes our e2es to fail 50% of the time
- It might stop some users from seeing ads on amp frontpages

Solutions might be (from Lily)  

- Fix the source of the error which could be the CSP
- If we can’t fix the CSP, catch the error in the application as an expected issue sometimes
