### ISSUE TITLE
[Investigation] CMP Blocking Banner Performance 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#9028]
**Background:** 
JIRA: NEWSWORLDSERVICE-1251
GNL recently made a change to enable a CMP blocking banner to users within the EEA 
The banner renders on canonical pages in the EEA where users visit our pages for the first time 

**Expected behaviour:** 
 
- Given I am within the EEA or California
- When I visit bbc.com mundo on canonical for the first time
- Then I am shown a blocking banner

**To Do:** 

- Understand the impact to Simorgh in terms of performance 
- Look at speedcurve to understand the impact to our Core Web vital stats
- https://speedcurve.com/?cs=lg&d=7&dc=2&de=1&ds=1&m=speedindex&r=eu-west-1&s=330892&u=441868
- How might this impact core web vitals 

**Output of investigation:** 

- What is the impact to users within the EEA 
- What is the impact to users outside of the EEA 
- What impact might this have where Google crawls our sites for search indexing and core web vitals 
- What can we do to improve performance of the banner (low hanging fruit)
- Recommendations to GNL

**Comment by neildoughty** [comment]
One thing which appears to be true - that the CMP banner has improved performance, by deferring the ad code. So in the EEA, where the CMP pop-up appears, the ad code does not start running until consent has been given. Therefore, the pages are loading a fair bit quicker.
EG - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.bbc.com%2Frussian

One thing to test - what is happening in this respect outside the EEA? Is the AD code still causing us performance problems, which are potentially harder to spot?

**Comment by aeroplanejane** [comment]
SpeedCurve reports that Pashto article pages seem to show a sustained increase in Fully Loaded time and TTI since Fri 2 Apr due to google fonts download https://speedcurve.com/bbc/news-ws/site/?b=chrome&cs=lg&d=90&dc=2&de=1&ds=1&r=ap-south-1&s=317507&u=394955
See also slack [thread](https://bbcnews.slack.com/archives/CK85Q5SL9/p1618222105022900)

**Comment by andrewscfc** [comment]
Outputs of investigation can be found here
https://paper.dropbox.com/doc/CMP-Performance-Investigation--BJQ5bASvUDGsp3KYdxGlKHWBAg-aR4ZxK3s24xhqVIEZAM0j

Additional to this we have seen the following effects on our Web Vital scores:
Performace dropped from 90 -> 89
Best practicrs dropped from 75 -> 69
These will adversely affect our SEO if not addressed.
