### ISSUE TITLE
Overlap in Most Read component

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#9051]
**Describe the bug**

Overlap in the Most Read component on Arabic site:

![image](https://user-images.githubusercontent.com/59573468/114726521-60ee7580-9d35-11eb-94cb-92c75fc26d92.png)

https://www.bbc.com/arabic/middleeast-56548177

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by mukama** [comment]
We'll close the issues because we could not replicate this issue any more. Let's reopen this ticket if the issue reoccurs. 
![image](https://user-images.githubusercontent.com/2413911/116066372-ac3b4900-a690-11eb-86a4-8dde8b7d1bde.png)

**Comment by rebeccamcginn** [comment]
I can see it today on Chrome - https://www.bbc.com/arabic/middleeast-56548177

![image](https://user-images.githubusercontent.com/59573468/116204288-8b2c3400-a734-11eb-99b1-127c18c3f281.png)

**Comment by paruchurisilpa** [comment]
Checked in psammead with the overlapping text which Caesar provided for testing and LGTM.

بريطانيا ترسل سفينتين حربيتين إلى ميناء جيرسي وسط خلاف مع فرنسا على الصيد
or
الهند تقرّ بوجود علاقة بين سلالة كورونا المتفشية لديها وارتفاع عدد الإصابات

**Comment by paruchurisilpa** [comment]
I will retest again now that its merged..
