### ISSUE TITLE
Add JSON schema for scenario data and validate them

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#91]
We have various article scenarios as JSON in/data/, but no schema.

A schema should be added. @PaulChinkwende defined a drafted schema for the Article in https://swagger.io/tools/swaggerhub/ some time ago, we should set this up to match the examples in /data and then validate our data against it with automated tests.

We must use the OpenAPI 3.0 Schema and I strongly advise using YAML to allow comments.

I suggest using something like: https://www.npmjs.com/package/swagger-cli and https://www.npmjs.com/package/swaggest-test 

NB we should validate all our test articles in the repo. In the future, this test can be run on real article payloads on load of the article page so errors can be caught pre-parsing. For now though we only need to test our data endpoints.

**Comment by jamesbhobbs** [comment]
@PaulChinkwende this could be a good issue for you as you're aware of swagger already and the testing could be a nice challenge to setup for you. Whoever does it pairing would probably be best.

**Comment by PaulChinkwende** [comment]
Sounds like a good idea.
