### ISSUE TITLE
Kyrgyz Podcast Routing

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#9107]
**Is your feature request related to a problem? Please describe.**
A new podcast has been commissioned under the bbc_kyrgyz_radio masterbrand. We currently do not support this masterbrand in Mozart routing

**Describe the solution you'd like**
Set up routing in Mozart for bbc_kyrgyz_radio

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by gavinspence** [comment]
Closing this one as the page has been released 😃
