### ISSUE TITLE
Investigate how to get Storybook rendering AMP components

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#911]
**Is your feature request related to a problem? Please describe.**
When we have an AMP component, e.g. an AMP Image component that renders`<amp-img>`, we want to make it visible in Storybook https://simorghstorybook.now.sh.  
However, because our standard Storybook setup does not include the AMP required markup and JS, (https://www.ampproject.org/docs/fundamentals/spec#required-markup) the component won't render accurately. 

**This is a prerequisite to adding AMP components to our application and also to our future component library.**

**Describe the solution you'd like**
- A storybook setup that displays AMP components
- What do we do if storybook just cannot render AMP components?

**Describe alternatives you've considered**
N/A

**Testing notes**
Add an AMP component, e.g. an AMP Image component that renders`<amp-img>`, and see it displayed correctly in Storybook https://simorghstorybook.now.sh.  

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
The outcome of the investigation is to use a Storybook generator to add the required AMP markdown to the story iframe. This will be implemented in https://github.com/BBC-News/simorgh/issues/943
