### ISSUE TITLE
Use view and click tracking hooks on the most read component

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9129]
**Is your feature request related to a problem? Please describe.**
As a ws product manager I want to know how many users who see the features & analysis promos on our pages click on the links so that I have a baseline to measure improvements to the component.

![most_read](https://user-images.githubusercontent.com/4798332/119505812-3e547100-bd65-11eb-9e30-1ea2f8cc0766.png)

**Describe the solution you'd like**
Enable tracking to the features & analysis block that will send a single view event when the block is in view and a single click event if any link within the block is clicked. The content of the view and click event must be the same for the block so ATI can calculate the click/view value.  The tracking must contain details of what service is being tracked.

Configure the features & analysis block on cps articles and media asset pages to enable block level tracking. This will give a view in ATI where we can track the views/clicks of the block.

### The click event
Send a block level click event if any link/promo within the block is clicked. (we are only tracking the interaction and not tracking the link location)

Don't send a click event if any other part of the block is clicked.

`atc=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General Placement]-[Detailed Placement]-[Advertiser ID]-[Url]&type=AT`

```
(atc)

Article Page
atc=PUB-[article-sty]-[most-read]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT

MAP Page
atc=PUB-[article-media-asset]-[most-read]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT

Front Page
atc=PUB-[index-home]-[most-read]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT

Most Read Page
atc=PUB-[list-datadriven-read]-[most-read]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT
```

### The view/impression event

`ati=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General]-[Detailed]-[Advertiser]-[Url]&type=AT`

```
(ati)

Article Page
ati=PUB-[article-sty]-[most-read]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT

MAP Page
ati=PUB-[article-media-asset]-[most-read]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT

Front Page
ati=PUB-[index-home]-[most-read]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT

Most Read Page
ati=PUB-[list-datadriven-read]-[most-read]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT
```

### Example values from click/impression events

|                    |                                                                  |
| ------------------ | ---------------------------------------------------------------- |
| Campaign           | 'article-sty' (this is dynamic and relates to the page type)                                                        |
| Creation           | 'most-read'                                                    |
| Variant            | empty                                                            |
| Format             | empty                                                            |
| General Placement  | _page_ eg pidgin.world.story.56829018.page (same as the p value) |
| Detailed Placement | empty                                                            |
| Advertiser ID      | empty                                                            |
| Url                | empty                                                            |

### ATI Tag Inspector
In the Tag Inspector these values should be present:
- Site - 598342
- Level2 - 70
- (Under -Ad)
- Campaign ID - article-sty
- Creation ID - most-read
- General placement - pidgin.world.story.56829018.page

### Accessibility
The solution should have no adverse affects with any of our support assistive technology. This will require a developer accessiblity swarm to check that nothing unexpected is read out, such as 'clickable'. e.g. Only the content and HTML semantics should be announced for elements, nothing extra to the defined screen reader UX for components.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
The WS event tracking matrix contains all tracking campaigns and which components are appear on which page types NEWSWORLDSERVICE/WS+event+matrix.

**Comment by JonBeeb** [comment]
Updated ATI examples with most-read (was features)

**Comment by LilyL0u** [comment]
Test URLs:
Pidgin
Articles - http://localhost:7080/pidgin/articles/cwl08rd38l6o
Article-STY - http://localhost:7080/pidgin/tori-51745682
MAPs - ?
Front Page - http://localhost:7080/pidgin
Most Read - http://localhost:7080/pidgin/popular/read

**Comment by LilyL0u** [comment]
Articles view event = PUB-[article]-[most-read]-[]-[]-[pidgin.articles.cwl08rd38l6o.page]-[]-[]-[]
Article sty view event = PUB-[article-sty]-[most-read]-[]-[]-[news::pidgin.news.story.51745682.page]-[]-[]-[]
Front page view event = PUB-[index-home]-[most-read]-[]-[]-[pidgin.page]-[]-[]-[]
Most read view event = PUB-[list-datadriven-read]-[most-read]-[]-[]-[pidgin.popular.read.page]-[]-[]-[]

**Comment by LilyL0u** [comment]
Articles click event = PUB-[article]-[most-read]-[]-[]-[pidgin.articles.cwl08rd38l6o.page]-[]-[]-[]
Article sty click event = PUB-[article-sty]-[most-read]-[]-[]-[news::pidgin.news.story.51745682.page]-[]-[]-[]
Front page click event = PUB-[index-home]-[most-read]-[]-[]-[pidgin.page]-[]-[]-[]
Most read click event = PUB-[list-datadriven-read]-[most-read]-[]-[]-[pidgin.popular.read.page]-[]-[]-[]

**Comment by LilyL0u** [comment]
The above match the expected information.

One thing that is different is the 'news::' part of the General Placement in the Article STY view and click events. What is this?

**Comment by JonBeeb** [comment]
The value is obtained from the ares feed and (I think) are assigned by cps.
