### ISSUE TITLE
Prioritising Simorgh JS Bundles

### ISSUE THREAD

**Issue by joshcoventry** [bbc/simorgh#9135]
**Is your feature request related to a problem? Please describe.**

Prioritising Simorgh JS Bundles
•	Should we ensure our JS bundles are prioritised?
•	Perhaps we don’t need too because we SSR
•	Improving our JS download time could improve TTI which could impact our web-vitals score
•	Are fonts actually a higher priority for us?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by andrewscfc** [comment]
Close as this has been resolved by: https://github.com/bbc/simorgh/pull/9640
