### ISSUE TITLE
Application error causing scheduled live E2E failure on Arabic AMP front page with ads

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#9138]
**This issue is blocked while we wait for resolution of an escalation to google about their ads solution potentially causing this problem. In the meantime I have caught the exception to stop the application error failing the scheduled live E2Es, but I am leaving this issue here to remind us this is not yet resolved and will require coming back to.**

PR with the exception catching **https://github.com/bbc/simorgh/pull/9157
**

We regularly get the following application error on amp Arabic front page which causes the scheduled live E2Es to fail:

<img width="810" alt="Screenshot 2021-05-26 at 16 30 07" src="https://user-images.githubusercontent.com/54575620/119688288-c444ea80-be3f-11eb-9bd6-b7836ba966d8.png">

It does not happen every live scheduled run, but it is quite frequent.

The reason I think this could be related to ads is that the error only happens in the AWS E2E run in Ireland which gets ads, and never seen when running on my computer in the UK. Sometimes when I look at the page in Browserstack, the ad section is blank (apart from the title 'advertisements'). Could be related to CSP with a problem with eval as seen in the AWS error message and the console message in the below screenshot. Although that was seen on canonical and not amp!

<img width="1369" alt="Screenshot 2021-05-17 at 12 28 03" src="https://user-images.githubusercontent.com/54575620/119689520-d410fe80-be40-11eb-8d50-2e311f8a64b0.png">

**Comment by aeroplanejane** [comment]
Hey @LilyL0u is this still an issue?
