### ISSUE TITLE
AMP Pages in the Google News App - Menu is not opening

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#9154]
**Describe the bug**
The Google News app on both Android and IOS will render the AMP variant of a story if one is available. Today I noticed that with News AMP pages in the IOS Google News App the navigation menu does not open. The click/tap is registered, the icon switches to the close icon however the menu never opens.

It is worth noting that I am running the IOS 14.7 beta, so this may be causing an issue but I suspect not. I also do not have an Android device to test this on.

**To Reproduce**

1. Open the Google News App on IOS
2. Search for BBC (To find an actual BBC article I open the BBC Urdu topic) _Search in this app isn't great!_
3. Find a BBC News story and tap to open it.
4. Tap on the menu icon to open the menu.

**Expected behavior**
The mobile navigation menu should open.

**Screenshots**

https://user-images.githubusercontent.com/14273378/120502986-f2907000-c3d3-11eb-8ebe-fe6d4249979b.mp4

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max
- OS: IOS 14.7 Beta
- Google News App

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context** Add any other context about the problem here.

**Comment by pvaliani** [comment]
A similar issue happens on Android OS 11 with a Galaxy S10 mobile device within the Google News App.

https://user-images.githubusercontent.com/72317734/124627210-44b32e00-de77-11eb-9267-54fe91fa41a3.mp4

**Comment by rebeccamcginn** [comment]
Linking second Google News app defect - https://github.com/bbc/simorgh/issues/9218

**Comment by gavinspence** [comment]
Will raise this (& #9218) with Google as we're not able to debug in the Google News App, and navigation works fine when accessed on AMP across different browsers

**Comment by aeroplanejane** [comment]
Google team are unable to recreate this issue. 

> In regards to the menu issue, you should be able to debug the issue a little further by enabling designer mode in your Google News app and then enabling the setting to make webviews debuggable with Chrome Remote Debugging Webviews.

**Comment by aeroplanejane** [comment]
Closing as won't fix. cc @gavinspence
