### ISSUE TITLE
Fix the ATI campaign tracking where the XTOR url value is not passed to ATI in some situations

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9182]
**Describe the bug**
A campaign is tracked via values passed on the url which are then sent to ATI through a beacon. One of the values used is XTOR where the values of the XTOR parameter is passed by Simorgh to an ATI beacon. When the url contains an anchor,the XTOR value is not passed to ATI.

 

Example URLS:

All links below should pass the contents of the xtor parameter
When the #!psicash=eyJt... value is included in the url, the parameters are not passed

**To Reproduce**
Example URLS:

All links below should pass the contents of the xtor parameter
When the #!psicash=eyJt... value is included in the url, the parameters are not passed

```
Fails
https://www.bbc.com/burmese?landed=996410751846761766&xtor=CS1-13-%5Bwsburmese~C~A40B39C45D39E38F39G41wsmktgburmese_reactive%5D-%5BPSIPHON%5D-%5B%7Bcampaign.id%7D%5D-%5B%7Bad.id%7D%5D#!psicash=eyJtZXRhZGF0YSI6eyJjbGllbnRfcmVnaW9uIjoiTU0iLCJjbGllbnRfdmVyc2
 
(url decoded)
https://www.bbc.com/burmese?landed=996410751846761766&xtor=CS1-13-[wsburmese~C~A40B39C45D39E38F39G41wsmktgburmese_reactive]-[PSIPHON]-[{campaign.id}]-[{ad.id}]#!psicash=eyJtZXRhZGF0YSI6eyJjbGllbnRfcmVnaW9uIjoiTU0iLCJjbGllbnRfdmVyc2
 
if you remove the #!psicash=eyJt….. it works as expected. 
https://www.bbc.com/burmese?landed=996410751846761766&xtor=CS1-13-%5Bwsburmese~C~A40B39C45D39E38F39G41wsmktgburmese_reactive%5D-%5BPSIPHON%5D-%5B%7Bcampaign.id%7D%5D-%5B%7Bad.id%7D%5D
```

**Expected behaviour**
As an owner of a campaign
I want to track the campaign through ATI
So that I can see how successful that campaign has been

Update the logic extracting the XTOR value from the URL to work when an anchor value is also included. This should mean all the links above will pass the xtor string

**Testing notes**
All the above links pass the xtor value as xto in the ATI beacon.
An Example can be seen below.
The xto can be seen in the network tab and checking values sent using hit.xiti

<img width="973" alt="image-2021-05-04-16-28-28-999" src="https://user-images.githubusercontent.com/4798332/122056565-9b31cd00-cde1-11eb-8467-e78acba196b0.png">

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by rebeccamcginn** [comment]
Closed by automation; reopening for testing
