### ISSUE TITLE
Nav update - add Olympics index to Japanese nav

### ISSUE THREAD

**Issue by jordit** [bbc/simorgh#9186]
**Is your feature request related to a problem? Please describe.**
Update the navigation of BBC News Japanese to add a link to their Tokyo Olympics index

**Describe the solution you'd like**
Add this link after the Corona virus index (/japanese/52137815) 

title: '東京五輪・パラ'
url: '/japanese/57464837'
position: third item in the list
 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by aeroplanejane** [comment]
@jordit do you want to link your original PR? (or where you were planning to make the change?)
