### ISSUE TITLE
Media player loads video instead of placeholder image on AMP before user interaction

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9201]
**Describe the bug**
The media player component in Simorgh does not load the placeholder image in AMP and instead loads the player on page load and will autoplay if the browser supports autoplay.

This is not as performant as the media player for canonical which loads a placeholder image and loads the player when the user clicks the placeholder image.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/mundo/articles/cdwrpl7qwqqo.amp 
2. Observe the video player loads the video content and autoplays (if on IE) or displays video placeholder instead of static image placeholder (as is the behaviour on canonical)

**Expected behaviour**
Video should not load video content on page load and should not autoplay. An image should be loaded in place of the video player. When the user click on the placeholder image, then the video player should load.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
``

**Comment by aeroplanejane** [comment]
Hey @jroebu14 looked at our stats for IE over the last 30 days on AMP (we had 5 visits) Don't think we need to spend time on this and will close. Glad the tests are passing now. 
Might be time to update the browser support list.

**Comment by jroebu14** [comment]
@aeroplanejane so this bug affects all browsers because the video content is downloaded on page load for AMP and not deferred like it is on canonical. So we may be unnecessarily loading video files for our AMP users because some users may never intend to play video content.

**Comment by jroebu14** [comment]
@aeroplanejane not sure if that information changes your decision to close this or not

**Comment by aeroplanejane** [comment]
Ah, sorry @jroebu14 misinterpreted the problem. 
We're not autoplaying video on amp are we? ie. I visit an article AMP page with embedded video, player loads _and_ video autoplays? It's just we're loading the media player by default rather than the placeholder?

**Comment by mukama** [comment]
That's correct @aeroplanejane. While we don't autoplay on AMP, we're still loading the video instead of showing a placeholder. I'll re-open this issue and investigate a suitable approach with @jroebu14

**Comment by aeroplanejane** [comment]
Copied to NEWSWORLDSERVICE-1299

**Comment by aeroplanejane** [comment]
Closing for now, can reopen when we pick this up again when we have the opportunity.
