### ISSUE TITLE
Reserve top ad slot for WS language AMP sites

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#9204]
**Is your feature request related to a problem? Please describe.**

Initial investigation: https://github.com/bbc/simorgh/issues/9161

Our AMP pages currently have a poor CLS score due to the page shift that occurs when the top advert loads in. 

**Example top slot:**

![image](https://user-images.githubusercontent.com/59573468/123557180-587bd780-d787-11eb-804a-b23f405ba8e2.png)

In order to improve this score, we are going to render a placeholder on AMP pages for WS languages that have ads enabled. This is the same placeholder that is rendered for canonical pages.

**Canonical placeholder:**

![image](https://user-images.githubusercontent.com/59573468/123557704-4f403a00-d78a-11eb-89bd-b77477e62e20.png)

**Describe the solution you'd like**

- Add an ad placeholder to the top of the WS pages that support ads
- The placeholder will match the design of the existing canonical placeholder
- The addition of the placeholder can be determined by a toggle - enabled for WS languages that have ads enabled
- The ad slot **should not** be reserved on the AMP News or Sport pages
- In this first iteration, we will leave the placeholder on the page if the user is in the UK (the ad should not load in), rather than remove the placeholder once the user's location is known

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by rebeccamcginn** [comment]
Reserved space is a little short on vertical height so fixing while I'm here - https://github.com/bbc/simorgh/pull/9215

**Comment by aeroplanejane** [comment]
@rebeccamcginn FYI the AMP folks have linked a potential workaround that would allow us to hide the amp slot for UK users see https://github.com/ampproject/amphtml/issues/35060#issuecomment-873268399
This could potentially work for all services. Let me know what you think
