### ISSUE TITLE
Share article URL is not the currently viewed page in Google News App when navigating article pages

### ISSUE THREAD

**Issue by pvaliani** [bbc/simorgh#9218]
**Describe the bug**
When searching for a BBC News (AMP generated) page via Google News, if a user navigates to another article from within a related content link in a searched article, then the URL in the "share link" option is not the currently viewed page. I.e The Google News app stores the URL of the previously viewed page for sharing. This issue also occurs with other news search results which are not BBC articles. 

Note: potentially being raised with Google at fortnightly meeting. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any BBC World News/Public Service page that is an AMP generated page via Google News
2. Click on the article to view it and then click on another article within related content i.e related stories
3. Scroll up to the "ellipses" menu on the top right of the Google News app and click "share"
4. Click "copy" and paste the URL in to your browser OR click "open in browser"
5. You should see that the URL in the browser is for the original article page found in the Google News search

**Expected behaviour**
Given a search for a BBC AMP generated page within the Google News App
When you click on an article from the search results 
And you then click on a related article within the original article
And you click "share" in the top right "ellipses" menu of the Google News App
And you should open the link in the browser or copy it to the browser
Then the article displayed with that URL should be the page you are currently viewing

**Screenshots**

https://user-images.githubusercontent.com/72317734/124626303-737cd480-de76-11eb-8706-cc95d40cb677.MP4

**Desktop (please complete the following information):**

- OS: N/A
- Browser: N/A
- Version: N/A

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max and Samsung Galaxy S10 
- OS: iOS 14.6 Big Sur and Android 11 
- Browser N/A - Google News App
- Version 5.32

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by aeroplanejane** [comment]
Raised with google team who are working to resolve it. Closing from our board.
