### ISSUE TITLE
Add support for RSS Marketing String type

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#9231]
**Is your feature request related to a problem? Please describe.**
We don't know how much usage there is of our RSS feeds.  I am looking at adding a marketing tracking string to the URLs in our RSS feeds so that we can track. ATI's marketing string spec has advanced since we implemented them originally, and the recommended approach uses the new way of doing custom marketing types.

**Describe the solution you'd like**
Add the additional approach to marketing tracking to Simorgh, reporting:

input field | condition | output field
------ | ------ | ------
at_medium | Any value other than those already defined, or beginning with the characters `custom` | at_medium
at_* | Report exactly as input | e.g. at_somekey=somevalue

**Describe alternatives you've considered**
Use a different marketing type - needs to be consistent across PS and WS though

**Testing notes**
Example URL: /mundo?at_medium=RSS&at_campaign=TEST

When working, should see the fields sent in the ATI data call

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
ATI Docs: https://developers.atinternet-solutions.com/javascript-en/campaigns-javascript-en/marketing-campaigns-v2/#smarttag-version-5-29-0_12

**Comment by gavinspence** [comment]
Can you share some examples of the RSS feeds we want to track, and how these are sent to ATI @jimjohnsonrollings ? Not sure of any examples in WS.

**Comment by jimjohnsonrollings** [comment]
There's an example feed here: https://feeds.bbci.co.uk/mundo/front_page/rss.xml (substitute for any service)

Content links appear as, for example: https://www.bbc.com/mundo/noticias-america-latina-58312598?at_medium=RSS&at_campaign=KARANGA

When the user follows the link to the Simorgh page, Simorgh should read the query parameters, as it does for other forms of marketing tracking, and pass through to ATI as specified above, by copying the `at_medium` and any other `at_*` parameters into the ATI call.

**Comment by aeroplanejane** [comment]
@JonBeeb to update

**Comment by JonBeeb** [comment]
@jimjohnsonrollings  so this would be a similar way to how we pass xtor to ATI in Simorgh but using the example above we pass
at_medium: RSS
at_campaign:KARANGA
or any other at_* value 
<img width="537" alt="image" src="https://user-images.githubusercontent.com/16046375/135633668-03ee3d97-377e-4ead-8ba9-d789ab8b4def.png">

**Comment by jimjohnsonrollings** [comment]
I think there are more similar approaches currently in Simorgh.  I think the `xtor` to `xto` mapping is an older version of this, which is still in use.

**Comment by JonBeeb** [comment]
So according to this: https://developers.atinternet-solutions.com/as2-tagging-en/javascript-en/campaigns-javascript-en/marketing-campaigns-v2/#smarttag-version-5-29-0_12

Hitting the url:  https://www.bbc.com/mundo/noticias-america-latina-58312598?at_medium=RSS&at_campaign=KARANGA

Would pass the additional parameters to ati via the page beacon:
`
src_medium:RSS
`
`
src_campaign:KARANGA
`

**Comment by jimjohnsonrollings** [comment]
Yes... which is subtly different from what I wrote isn't it.  So go with `src_` then rather than `at_`...

Checking what PS does...

https://www.bbc.co.uk/news/uk-58790028?at_medium=RSS&at_campaign=KARANGA

Looks like this sends `xto=cs-[KARANGA]` which is different again...

**Comment by MuhammadAHussain** [comment]
Is the below xto value correct, using the `src_property: value` like Jon described?
```
xto=src_medium:RSS-[src_campaign:KARANGA]-[src_type:testing]-[src_test:testing]
```

**Comment by jimjohnsonrollings** [comment]
It's not how I would have interpreted the docs, but that doesn't mean it's wrong.

I would have interpreted it to mean the key value pairs would exist outside of the `xto` parameter as URL query params in their own right, without an `xto`.

Best way is probably to try it locally and see if the data turns up as expected in the Test bucket in ATI

**Comment by JonBeeb** [comment]
Will do. Do you have a query where I can see it in ATI?

**Comment by jimjohnsonrollings** [comment]
I think so, but I can't post the link on a public issue, so will send it to you on Slack

**Comment by JonBeeb** [comment]
I've checked this is working as expected on (test) ATI.
