### ISSUE TITLE
Social embeds should not include index in skip link if there is only 1 embed by provider in an article

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9232]
**Describe the bug**
Currently social embeds contain the index of the embed by the provider e.g. 'Saltar contenido de Twitter, 1' and 'Fin del contenido de Twitter, 1' for the Mundo service.

This is incorrect when there is only 1 embed by the provider in an article. It should only include the index of the first embed when there are more than 1 embed by the provider in an article e.g. when there are multiple Twitter embeds.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/mundo/articles/c20myn5q195o
2. Tab to the article's only Twitter embed skip link
3. Observe the index in the skip link and end text

**Expected behaviour**
The skip link should not contain the index when there is only 1 embed by the provider in an article.

**Screenshots**
_Screenshot of bug_
<img width="669" alt="Screenshot 2021-07-13 at 11 15 17" src="https://user-images.githubusercontent.com/4798332/125434986-25eccaef-5ced-4243-a344-626c8793dd03.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by jroebu14** [comment]
We need to cover youtube embeds

**Comment by nicola-d-bbc** [comment]
> We need to cover youtube embeds

Will be covered in the future once more embed types are supported in Optimo.
