### ISSUE TITLE
Mock Cypress API requests

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#926]
**Is your feature request related to a problem? Please describe.**
For our Cypress integration tests, we currently make requests to the Ares API. We do not stub our requests.  This means that right now, when the TEST Ares API is returning non-200 responses, our build pipeline is failing on our integration tests.

This is not ideal and is blocking our work.  For this reason, we should stub our API requests in our Cypress tests. 

**Describe the solution you'd like**
We should stub responses to these paths, in our Cypress Integration tests.

```
/news/articles/c85pqyj5m2ko.amp
/news/articles/c85pqyj5m2ko
/news/articles/c9rpqy7pmypo
/persian/articles/cwv2xv848j5o
```
The Cypress tests should pass. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Our Cypress tests should pass, even when the Ares API is unavailable.  

**Additional notes**
Cypress docs: https://docs.cypress.io/guides/guides/network-requests.html#Stub-Responses

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
We could either 1) stub the Cypress calls, or 2) run Cypress against localhost

Any reason why we wouldn’t want to go for option 2? 🤔Feels like our tests are misleading if we're running against "test" and "live" but are in fact using local fixture data...

**Comment by pjlee11** [comment]
I’m convinced Cypress can’t mock the data for our server side render, I think we should look into proxying libraries - Jordan suggested [talkback](https://www.npmjs.com/package/talkback)

It's worth noting there also seems to be bugs when stubbing Cypress fixtures on client side requests such as this [race condition](https://github.com/cypress-io/cypress/issues/1956#issuecomment-437442617)

**Comment by ChrisBAshton** [comment]
After discussion at standup, agreed to close this (no longer high-priority now the build is passing) and can look at it again after alpha-2.

**Comment by pjlee11** [comment]
Echoing what Chris said, closing this in favour of https://github.com/BBC-News/simorgh/issues/935 which can be evaluated in the future
