### ISSUE TITLE
Update Optimo Article background colour

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#9278]
**Is your feature request related to a problem? Please describe.**

Change the Optimo Article background colour.

**Describe the solution you'd like**

Change the Optimo Article background colour to #f2f2f2. 

This will for the whole of the article section of the page except selected Onward journey blocks:

- Gist
- Twitter blocks
- Topic Tags
- Most read section

These should remain white.

![image](https://user-images.githubusercontent.com/59573468/127303216-dce36406-8e35-44cc-aefe-5afa3473a195.png)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by ryanmccombe** [comment]
This is on both test and live now - needs QA (can probably be done alongside the gist testing)

**Comment by paruchurisilpa** [comment]
The background color is now  #f2f2f2.

https://www.test.bbc.com/pidgin/articles/cvrvly5wkyqo
