### ISSUE TITLE
Add Translations for Gist component strong element

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#9280]
**Is your feature request related to a problem? Please describe.**
We need to support all our services with localisation for the gist component.

**Describe the solution you'd like**
Add translations for each service to the service config for the gist component integrated in a previous issue.
Sport, Cymru Fyw, Naidheachdan and Newsround will not support the Gist so can we default to the English "At a glance" 

Service | Text
-- | --
News | At a glance
Sport | At a glance
Naidheachdan | At a glance
Newsround | At a glance
Cymru Fyw | At a glance
Persian | خلاصه
Igbo | Nchịkọta
Pidgin | Summary
Yoruba | Ìsọníṣókí
Urdu | خلاصہ
Pashto | لنډیز
Arabic | ملخص
Thai | สรุป
Punjabi | ਸਾਰ
Afaan Oromoo | Guduunfaa
Amharic | ጭምቅ ሃሳብ
Indonesian | Rangkuman
Tigrinya |  
Korean | 요약
Afrique | Points clés
Gahuza | Incamake
Somali | Kooban
Swahili | Muhtasari
Azeri | Xülasə
Hausa | Takaitacce
Vietnamese | Tóm tắt
Kyrgyz | Корутунду
Japanese | 要点
Nepali | सारांश
Uzbek (Cyrillic) | Хулоса
Sinhala | සාරාංශය
Bengali | সার সংক্ষেপ
UK China (Simp) | 概要
UK China (Trad) | 概要
Turkce | Özet
Burmese (Unicode) | အနှစ်ချုပ်
Gujarati | સારાંશ
Marathi | थोडक्यात
BBC News Mundo | Sumario
Portuguese | Pontos-chave
Russian | Коротко
Serbian(Cyr) | Сажетак
Serbian (Lat) | Sažetak
Tamil | முக்கிய சாராம்சம்
Telugu | సారాంశం
Ukrainian | Стисло
Hindi | सारांश
Zhongwen (Simp) | 概要
Zhongwen (Trad) | 概要

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by andrewscfc** [comment]
Awaiting translations before we can proceed

**Comment by pvaliani** [comment]
Is Tigrinya supposed to be empty? Could someone kindly provide the translation for this in an update if not? Thanks.

**Comment by aeroplanejane** [comment]
Tigrinya to default to English for now. Removed Uzbek latin translation for now too.

**Comment by aeroplanejane** [comment]
Updated Burmese to `အနှစ်ချုပ်`
