### ISSUE TITLE
Redirect Russian Story Page for Partners

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#9285]
**Is your feature request related to a problem? Please describe.**
The Russian Service are asking for a redirect from an old TC2 asset that gives information on their partners to a new updated CPS asset. 

**Describe the solution you'd like**
301 Redirect
From
https://www.bbc.com/russian/international/2011/02/000000_g_partners
To
https://www.bbc.com/russian/institutional-43463215

Similar recent issue: https://github.com/bbc/simorgh-infrastructure/issues/1432
**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by rebeccamcginn** [comment]
Deployed + live
