### ISSUE TITLE
Create AmpImg component

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#929]
**Is your feature request related to a problem? Please describe.**
Arising from the meeting in #884: we agreed on an approach to implement AMP components.

Since #927, we have a PlatformContext in which we can derive `platform` information. When `platform` is `amp`, we want to render [amp-img](https://www.ampproject.org/docs/reference/components/amp-img).

## Describe the solution you'd like
We want to be able to programmatically determine whether or not a component has an AMP variant (to enable more possibilities in terms of reducing hard-coding in Storybook, tests, etc), so the only real solution is to keep the two variants in _separate files_. (It is difficult to programmatically determine if a given file exports a given constant).

We should be able to:

```js
import { Img } from '@bbc/psammead-image'; // explicitly get canonical version
```

And:

```js
import { AmpImg } from '@bbc/psammead-image'; // explicitly get AMP version
```

And we should be able to import the default export (which would be the canonical version)

```js
import Img from '@bbc/psammead-image'; // get canonical version via default export
```

We should also be able to get the non-transpiled version (e.g. if we only care about modern browsers):

```js
import { Img, AmpImg } from '@bbc/psammead-image/src';
```

And tests/storybooks can be auto-generated through some sort of:
In future, we may want to programmatically set up Storybook to have AMP-specific JavaScript, so this is why we keep the AMP definition in its own separate file. It would allow us to do something like:

```js
// pesudocode
if (exists('index.amp.jsx')) {
  const ampVersion = import('@bbc/psammead-image/src/index.amp');
  storybook.add(ampVersion);
}
```

We _did_ consider having a container that handles the platform switching for you:

```js
import DynamicImage from '@bbc/psammead-image';
<DynamicImage alt="" src="" platform="amp" />
```

...but this is a helper that is best suited to living in Simorgh, not Psammead (otherwise the logic would need repeating for every AMP component). Let's keep Psammead simple.

With all that in mind, proposed structure would be this:

Non-AMP component - unchanged:
```
component-name/
  index.jsx
```

AMP component - additional file:
```
different-component-name/
  index.jsx
  index.amp.jsx
```

In this example AMP component, `index.jsx` can define a canonical version (`export default`) and pull in the AMP version from `index.amp.jsx` to export that too.

**Describe alternatives you've considered**
There are a few ways we could approach this:

1) `export const AmpImg; export const Img` in the same file
2) `export default { canonical: Img, amp: AmpImg }` in one file (more programmatically 'hookable')
3) Separate `index.jsx` and `index.amp.jsx` files
4) Separate `index.jsx` and `amp/index.jsx` file/directory combos
5) ??? (probably plenty more)

**Testing notes**
~Our implementation of AMP vs non-AMP is likely to require more than just unit tests. Eg we want to ensure the AMP version is rendered on AMP pages, and the canonical version is rendered on canonical pages; something better suited to Cypress tests.~
For creating the component we will check it in Storybook. On a future ticket, when we integrate this, we will add a Cypress test.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by BogdanDogaru** [comment]
Blocked on #943

**Comment by ChrisBAshton** [comment]
Blocked pending decision on the 'Describe the solution you'd like' section of this issue.

**Comment by sareh** [comment]
I agree with you that it would be good to have separation into two different files within the same component. 

I think it would be better to have a file structure that has minimal changes when moving from just having a canonical version to having other variants. For this reason, I prefer this structure:

```
component-name/index.jsx
component-name/amp.jsx
```

**Single variant**

`Image/index.jsx`
```
export default const Img = (props) => {...};
```
Usage: `import Img from 'Image';`

**Two variants**
`Image/amp.jsx`
```
export const AmpImg = () => {...};
```

`Image/index.jsx`
```
import AmpImg from './amp';

const Img = () => {...};

export AmpImg;
export default Img; 
```

~Usage: `import { Img, AmpImg } from 'Image';`~ [1]Edit: updated as of @ChrisBAshton 's comment below.


Usage: `import Img, { AmpImg } from 'Image';`

**Comment by ChrisBAshton** [comment]
**EDIT: Sareh has updated her comment above, so this is no longer applicable**.

-----

I'm agnostic either way, until that last bit:

`import { Img, AmpImg } from 'Image';`

Should still be possible to `import OneImgToRuleThemAll from 'Image';`

Which requires:

```jsx
export default Img;
```

...at the end of the `Image/index.jsx` file.

**Comment by dr3** [comment]
Im not 100% sold on 
```
import Img, { AmpImg } from 'Image';
```
IMO
```
import Img from 'Image';
AND/OR
import { Img, AmpImg } from 'Image';
```
Is nicer, But thats a minor detail, everything else LGTM

**Comment by ChrisBAshton** [comment]
The downside to that, Drew, is if a component starts off canonical-only and _later_ offers an AMP variant.

You'd have to go from `import Foo from 'foo'` to `import { Foo } from 'foo'`, and would be a major version change.

As opposed to continuing to offer an `import Foo from 'foo'` alongside a `import { AmpFoo } from 'foo'`... 😄

**Comment by dr3** [comment]
If we offer a default export all the time then it wouldn't be an issue surely? Realistically were the only ones who are going to use the amp version, everyone else will use the normal one, which IMO makes having it always the default makes sence

**Comment by ChrisBAshton** [comment]
...but you're saying we should choose `import { Img, AmpImg } from 'Image';`, so no default export?

**Comment by dr3** [comment]
Oh no soz I mean we can do 
```
import Img, { Img, AmpImg } from 'Image';
```

**Comment by ChrisBAshton** [comment]
Yes, this is what I have in the description ^

**Comment by pjlee11** [comment]
>if a component starts off canonical-only and later offers an AMP variant.

If we are taking the "AMP-first" approach seriously in should be highly unlikely we start off components as canonical-only. Unless we are now agreeing that psammead won't be AMP-first which feels like a team discussion.

**Comment by ChrisBAshton** [comment]
True, I'd only expect a component to have an AMP variant added later if the AMP version isn't currently possible (e.g. amp-video). So "later offers an AMP variant" is a bit of an edge case.

You raise a good point; having a default export pointing to the canonical version doesn't sound very "AMP-first". But my understanding of AMP-first with respect to this team is that we know we'll need to support AMP, so we consider it from the beginning for every new feature, rather than as an afterthought. But we shouldn't expose the AMP component as the default one, to the detriment of other teams.

(I know that's not what you were suggesting, just pre-empting before anyone suggests that!)

**Comment by ChrisBAshton** [comment]
Discussed in meeting today. Agreed this structure:

```
foo/
  index.jsx
  index.amp.jsx
```

*All* components will export as follows:

index.jsx
```jsx
export const Foo = {};
export default Foo;
```

...ie exported as both default and named const.

When an AMP variant is needed:

index.amp.jsx
```jsx
export const AmpImg;
export default AmpImg;
```

index.jsx
```jsx
import AmpImg from './index.amp';
export AmpImg;
export const Foo = {};
export default Foo;
```

**Comment by sareh** [comment]
Closed this issue in Simorgh since the work is done in Psammead: https://github.com/bbc/psammead/pull/241
