### ISSUE TITLE
AMP: Nav menu and cookie banner do not work in Opera Mini extreme data saving mode

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9298]
**Describe the bug**
On this page Clicking on the nav menu or cookie banner causes the page appears to reload. The nav menu does not open and the cookie banner is not accepted.

Happens on a service with a variant e.g. https://www.bbc.com/zhongwen/simp.amp however on Pidgin, these clicks appeared to reload the page but the menu DID show, and the cookie banner was accepted.

This only occurs on AMP and in Opera Mini browser on Android with extreme data saving mode.

https://user-images.githubusercontent.com/4798332/128338176-7a044696-d373-4bdb-ba01-87e7b2b04cfa.mp4

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/zhongwen/simp.amp
2. Click on the nav menu or cookie banner
3. Observe the page reloading, the menu not opening or the cookie banner not disappearing.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by gavinspence** [comment]
Closing as variant services do not have meaningful Opera Mini traffic
