### ISSUE TITLE
Inline link E2E fails when integrated with dependencies

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#930]
**Describe the bug**
Currently we build our application with the `RAZZLE_BASE_PATH=https://www.test.bbc.com` and then run our Cypress tests pointing at the actual application endpoint. This means the server render works hitting Simorgh directly and the E2Es pass, however when clicking an inline link the application on the client tries to render data from a different domain and gets a CORS error. 

**To Reproduce**
Steps to reproduce the behaviour:
https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh-infrastructure/detail/latest/33/pipeline

**Expected behaviour**
We would ideally not get the CORS error but that requires work in one of our dependencies codebase and should happen without our build remaining broken. Therefore we should comment out the failing test as inline links are not a current priority and are blocking our deployment. 

**Additional context**
```
  Running: newsBodySpec.js...                                                             (7 of 10) 
  Article Body Tests

    ✓ should render a headline (974ms)
    ✓ should render a timestamp (67ms)
    ✓ should render a subheading (51ms)
    ✓ should render a paragraph (91ms)
    ✓ should have a placeholder image (54ms)
    ✓ should have a visible image without a caption (75ms)
    ✓ should have a visible image with a caption (68ms)
    ✓ should have an image copyright label with styling (55ms)
    ✓ should have an inline link with focus styling (49ms)

    1) should have a working first inline link

  9 passing (6s)

  1 failing

  1) Article Body Tests should have a working first inline link:

     CypressError: Timed out retrying: Expected to find element: 'header a', but never found it.
```

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by ChrisBAshton** [comment]
Resolved by #931.
