### ISSUE TITLE
Optimo - Empty Blocks Messing with Design

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#9313]
**Describe the bug**
We've seen several examples now where editorial (or Optimo) insert additional empty blocks into their content.  Rendering these empty blocks can subvert our design, eg, the misaligned timestamp here: 

![Screen Shot 2021-08-11 at 05 28 14](https://user-images.githubusercontent.com/8601460/128970100-bbc6c09f-6c4c-4154-86ee-51a6c3f1ec5b.png)

This is caused by the first text section starting with a paragraph which has no content:
![Screen Shot 2021-08-11 at 05 30 18](https://user-images.githubusercontent.com/8601460/128970137-f5077418-407c-48ba-a70e-e45dfe5c49c9.png)

Which we render without checking:
![Screen Shot 2021-08-11 at 05 28 58](https://user-images.githubusercontent.com/8601460/128970156-f014e3b5-9a6e-4978-a60e-5d244d1b530d.png)

**To Reproduce**
Example asset: https://www.test.bbc.com/arabic/articles/cl5m3453w36o

**Expected behaviour**
TBC - requires product input

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by aeroplanejane** [comment]
@ryanmccombe Wondering how much effort it would be to ignore empty blocks?
