### ISSUE TITLE
Investigate cause of intermittent onDemandTVPage integration test failure

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#9322]
**Describe the bug**
An integration test for onDemandTvPage seems to flake every so often when integration tests are ran.

**To Reproduce**
Steps to reproduce the behaviour (Intermittent so it will not happen every-time):

1. Run integration tests
2. See this test fail https://github.com/bbc/simorgh/runs/3323765805?check_suite_focus=true#step:6:7

**Expected behaviour**
The test to pass, and not fail causing the test suite to exit and error.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by rebeccamcginn** [comment]
Reopening. Occurrences yesterday and today, eg https://github.com/bbc/simorgh/pull/9505/checks?check_run_id=3805791104

**Comment by jroebu14** [comment]
I don't think it's the test that is flakey but perhaps the actual component or page data.

For example, sometimes when I load the page the component that is being checked for, recent episodes, is not present.

I've not got to the bottom of it yet but it could be to do with the toggle as it seems to be the only mechanism that shows/hides the component.

**Comment by jroebu14** [comment]
Here is a JSON diff of the SIMORGH_DATA object when, on the left, the recent episodes do not render, and on the right, when they do render.

`recentEpisodes` is empty and the toggles have a few diffs. Looks like a problem with the default toggle values.

![www jsondiff com_](https://user-images.githubusercontent.com/4798332/136748663-5032d446-4139-430a-9b9f-603d625c9e82.png)

**Comment by jroebu14** [comment]
Looking at the server logs it looks like it's a timeout issue.

```
"event":"config_error","error":"FetchError: network timeout at: https://config.test.api.bbci.co.uk/?application=simorgh&service=pashto&__amp_source_origin=http://localhost:7080"
```

The timeout for toggles fetches is set here https://github.com/bbc/simorgh/blob/latest/envConfig/local.env#L16.

I think for local we can just raise this to 5 seconds or something like that without that causing any issues.
