### ISSUE TITLE
Use view and click tracking hooks on the podcast promo component

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9329]
**Is your feature request related to a problem? Please describe.**
As a ws product manager I want to know how many users who see the podcast promos on our pages and click on the links so that I have a baseline to measure improvements to the component.
![image](https://user-images.githubusercontent.com/16046375/129713207-c9f62f54-d400-4565-8e81-8402d5042196.png)

**Describe the solution you'd like**
Enable tracking on the podcast promo block that will send a single view event when the block is in view and a single click event if any link within the block is clicked. The content of the view and click event must be the same for the block so ATI can calculate the click/view value.  The tracking must contain details of what service is being tracked.

Configure the podcast block on cps articles enable block level tracking. This will give a view in ATI where we can track the views/clicks of the block.

### The click event
Send a block level click event if any link/promo within the block is clicked. (we are only tracking the interaction and not tracking the link location)

Don't send a click event if any other part of the block is clicked.

`atc=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General Placement]-[Detailed Placement]-[Advertiser ID]-[Url]&type=AT`

```
(atc)
atc=PUB-[article-sty]-[promo-podcast]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT
```

### The view/impression event

`ati=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General]-[Detailed]-[Advertiser]-[Url]&type=AT`

```
(ati)
ati=PUB-[article-sty]-[promo-podcast]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT
```

### Example values from click/impression events

|                    |                                                                  |
| ------------------ | ---------------------------------------------------------------- |
| Campaign           | 'article-sty' (this is dynamic and relates to the page type)                                                        |
| Creation           | 'promo-podcast'                                                    |
| Variant            | empty                                                            |
| Format             | empty                                                            |
| General Placement  | _page_ eg pidgin.world.story.56829018.page (same as the p value) |
| Detailed Placement | empty                                                            |
| Advertiser ID      | empty                                                            |
| Url                | empty                                                            |

### ATI Tag Inspector
In the Tag Inspector these values should be present:
- Site - 598342
- Level2 - 70
- (Under -Ad)
- Campaign ID - article-sty
- Creation ID - promo-podcast
- General placement - pidgin.world.story.56829018.page

### Accessibility
The solution should have no adverse affects with any of our support assistive technology. This will require a developer accessiblity swarm to check that nothing unexpected is read out, such as 'clickable'. e.g. Only the content and HTML semantics should be announced for elements, nothing extra to the defined screen reader UX for components.

### The tracker hooks documentation with examples
- [useClickTrackerHandler](https://github.com/bbc/simorgh/blob/latest/src/app/hooks/useClickTrackerHandler/README.md)
- [useViewTracker](https://github.com/bbc/simorgh/blob/latest/src/app/hooks/useViewTracker/README.md)

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
The WS event tracking matrix contains all tracking campaigns and which components are appear on which page types NEWSWORLDSERVICE/WS+event+matrix.

**Comment by ryanmccombe** [comment]
Podcast promos now enabled on test environment, including event tracking

Example URLs: https://github.com/bbc/simorgh/issues/9325#issuecomment-901816894

**Comment by JonBeeb** [comment]
Hello, lookking at the network I can see:
ati: PUB-[article-sty]-[podcast-promo]-[]-[]-[business::zhongwensimp.business.story.58267694.page]-[]-[]-[]
type: AT

I called in promo-podcast just in case we need to track other promo types.

**Comment by ryanmccombe** [comment]
Oh, oops 😭 

Should we change this?  This is live for Russian at the minute so events are being tracked under `podcast-promo`

**Comment by JonBeeb** [comment]
Yes. We will always get new data!

**Comment by ryanmccombe** [comment]
Fix here: https://github.com/bbc/simorgh/pull/9346

**Comment by LilyL0u** [comment]
I see in the description it says
' This will require a developer accessiblity swarm to check that nothing unexpected is read out, such as 'clickable'. '

Has this been done?

**Comment by LilyL0u** [comment]
View event looks good:
2 examples-
ati: PUB-[article-sty]-[promo-podcast]-[]-[]-[brasil::portuguese.brasil.story.58264547.page]-[]-[]-[]
ati: PUB-[article-sty]-[promo-podcast]-[]-[]-[science_and_technology::arabic.science_and_technology.story.57696380.page]-[]-[]-[]

Click event looks good:
atc: PUB-[article-sty]-[promo-podcast]-[]-[]-[brasil::portuguese.brasil.story.58264547.page]-[]-[]-[]
atc: PUB-[article-sty]-[promo-podcast]-[]-[]-[science_and_technology::arabic.science_and_technology.story.57696380.page]-[]-[]-[]

**Comment by LilyL0u** [comment]
When looking in the ATI inspector
Nothing appears on view
On click 5 rows appear in tag inspector 


<img width="787" alt="Screenshot 2021-08-23 at 16 59 10" src="https://user-images.githubusercontent.com/54575620/130479371-de511f13-d769-4282-84d0-489b54044669.png">

The 3rd row is the information for the click event for the podcast promo

The values in tag inspector are all there (as long as the portuguese Level 2 and Site numbers are correct?)
Here is one of Portuguese

<img width="329" alt="Screenshot 2021-08-23 at 17 00 49" src="https://user-images.githubusercontent.com/54575620/130479768-efee342e-55be-4796-8013-197b8a244efb.png">

and one of Arabic
<img width="353" alt="Screenshot 2021-08-23 at 17 07 38" src="https://user-images.githubusercontent.com/54575620/130480601-bd6386f4-9d7e-434b-9b8c-a7b6ffd3f317.png">

**Comment by LilyL0u** [comment]
Question: are the names of the variables in tag inspector chosen by us or are they written by ATI and we can select them? I am wondering because the spelling of '**detailled** placement id' could be a tripping point at some point.

**Comment by LilyL0u** [comment]
Another question
The Site number as an example value is suggested to be 'Site - 598342' 
However both Portuguese and Arabic have Site numbers 598343. Is this OK?

**Comment by gavinspence** [comment]
I believe the names of the variables are defined by ATI, however @JonBeeb should be able to confirm. 

The 'site ID' is where we report values to ATI. The site IDs are as follows: 

WS_NEWS_LANGUAGES | 598342 
-- | -- 
WS_NEWS_LANGUAGES_TEST | 598343

So, 598343 is actually correct as it's reporting values to test. 598342 is what we should expect on live.

**Comment by JonBeeb** [comment]
The 'detailled placement id' is an ATI thing.

**Comment by JonBeeb** [comment]
I can see data appearing in ATI (on Test) for most services. 
![image](https://user-images.githubusercontent.com/16046375/130603215-cd483990-4a19-4f8a-8b7d-68af0a81990f.png)
