### ISSUE TITLE
Stub Ares data for integration tests

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#935]
**Is your feature request related to a problem? Please describe.**
For our Cypress integration tests, we currently make requests to the Ares API. We do not stub our requests. This means that right now, when the TEST Ares API is returning non-200 responses, our build pipeline is failing on our integration tests.

Therefore this issue is to investigate into mocking server responses using libraries such as [talkback](https://www.npmjs.com/package/talkback).

**Describe the solution you'd like**
Using a HTTP proxy stub the responses during our integration tests.

**Describe alternatives you've considered**
Originally we [investigated using Cypress to stub the data for our integration tests](https://github.com/BBC-News/simorgh/issues/926), however it does not seem possible to stub the data for our server side render using Cypress internal logic. 

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Additional context**
Polly.js was also suggest but seemed overly complex for our task.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
James & I were talking about how it would be good to prioritise this as we begin working on error pages, & need to identify how we might achieve 502 responses from Simorgh.

**Comment by dr3** [comment]
Closing as not needed, if ares goes down, mozart fallback cache will catch it. if its down for more than 6 hours, Ahhh panic
