### ISSUE TITLE
Incorrect line height on synopsis on On Demand Audio pages

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#9352]
The line height on the synopsis is incorrect. The specs on the original design are: font size 24px and line height 28px.

<img width="908" alt="Screenshot 2021-08-23 at 11 11 29" src="https://user-images.githubusercontent.com/54575620/130435079-2158bf07-fa8c-4385-83de-43c06d262181.png">

**Comment by greenc05** [comment]
Please carry out a developer (2 person) a11y swarm as part of this work, the only required testing in this case is with our supported screen readers https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing.html
