### ISSUE TITLE
AMP page links stop working after visiting a google.com/amp/* page and navigating to a BBC domain and back to the Google domain

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#9375]
**Describe the bug**
When visiting an AMP page from a Google search that opens a URL to a google.com/amp/*, and then clicking a link on the page that leads to a non-AMP page and then returning to the previous AMP page, links on the page stop functioning.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Google and find a BBC news article served by the Google search carousel component on mobile
2. See the URL starts with google.com/amp/*
3. Click on any link on the page
4. Click back to return to the google.com/amp/* page
5. See that no links work when clicked on

**Expected behaviour**
Links should behave correctly when returning back to the google.com/amp/* page.

**Video**

https://user-images.githubusercontent.com/4706195/131487083-bae3e43c-72ca-4d7f-b9a4-96acd4a3b607.MP4

**Smartphone (please complete the following information):**

- Device: iPhone 7
- OS: iOS - 14.8
- Browser: Safari, Chrome

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
This could be caused by the page being served from the google.com URL, and it causing an issue with the routing functionality. There is another issue that encapsulates changing this URL served here https://github.com/bbc/simorgh/issues/2560. This could potentially solve the issue. Could be related to https://github.com/bbc/simorgh/issues/9154 and https://github.com/bbc/simorgh/issues/9218

**Comment by nicola-d-bbc** [comment]
Can't seem to replicate the issue on Android - may just be an iOS issue.

**Comment by nicola-d-bbc** [comment]
We've decided to park this for now as the work to fix this doesn't seem worth it for how edge-casey it is.

**Comment by aeroplanejane** [comment]
Closing as we're not going to fix. cc @gavinspence
