### ISSUE TITLE
Move GitHub templates into .github folder

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#940]
**Is your feature request related to a problem? Please describe.**
We currently have a mixture of `.github/` folder containing pull request template & issue templates, and various files in the root (CODE_OF_CONDUCT.md). Leave CONTRIBUTING.md so it's as obvious as possible for people new to the repo. Follow @sareh 's suggestion and is common practice, e.g. required by Google on their OSS repos.

GitHub supports serving the [code of conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) file from the `.github/` directory, so we should tidy up our repo by serving these 'meta' files from one place.

**Describe the solution you'd like**
Move the `CODE_OF_CONDUCT.md` file to the `.github/` folder. If there are any other moveable files, they should be moved too.

**Testing notes**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Since this is an open source project, I think it is important to keep the Contributing.md and Code_of_conduct.md files at the top level. This will ensure these files are visible to those visiting the repository for the first time. 
For this reason, I suggest closing this issue.

**Comment by dr3** [comment]
> Since this is an open source project, I think it is important to keep the Contributing.md and Code_of_conduct.md files at the top level. This will ensure these files are visible to those visiting the repository for the first time.
> For this reason, I suggest closing this issue.

+1 :)

**Comment by jamesbhobbs** [comment]
For future clarity the description was updated following the comments above
