### ISSUE TITLE
Upgrade to Node v10

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#941]
**Is your feature request related to a problem? Please describe.**
Now that [Node v10 is in long term support](https://nodejs.org/en/blog/release/v10.13.0/), let's update our [.nvmrc](https://github.com/BBC-News/simorgh/blob/latest/.nvmrc) and [.npmrc](https://github.com/BBC-News/simorgh/blob/latest/.npmrc) files and package-lock.json so that we're all running the latest stable version.

**Describe the solution you'd like**
Update Node version references everywhere where appropriate, and update the README.

Ensure that Node v10 runs locally with no issues, and ensure that CI continues to pass.

**Testing notes**
Ensure the build still passes.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Blocked on equivalent issue in Simorgh Infrastructure.

**Comment by sareh** [comment]
Also blocked on https://github.com/bbc/psammead/issues/427
