### ISSUE TITLE
Gist spacing tweaks

### ISSUE THREAD

**Issue by gailetaplin** [bbc/simorgh#9421]
**Describe the bug**
Extra spacing needed to match designs and give breathing space. 

**To Reproduce**
See gist component here: https://5d28eb3fe163f6002046d6fa-smzcatprda.chromatic.com/?path=/story/containers-gist--at-a-glance
and live here under the main image: https://www.bbc.com/kyrgyz/articles/cg7dnx6yxrno

**Expected behaviour**

- Increase space below 'At a glance' heading to 24px
- Increase spacing between bullets to 16px (may need to pair on this if it is already 16px to tweak it) 
- Increase spacing between bullet and text to 24px
 

**Screenshots**

![image](https://user-images.githubusercontent.com/74012325/133220254-ea69c0e9-6bef-40fd-97d0-b7ffb018273f.png)

**Testing notes**

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Comment by paruchurisilpa** [comment]
Testing:

* https://www.test.bbc.com/afrique/articles/c7yn6nznljdo

   --- Increase space below 'At a glance' heading to 24px --> Verified and looks good
   --- Increase spacing between bullets to 16px (may need to pair on this if it is already 16px to tweak it) --> Verified and looks good
   --- Increase spacing between bullet and text to 24px -->The bullet point is an image and not an actual standard bullet point, so it was difficult to verify this as we don't know where the image starts. This has been confirmed with Gail and approved.

LGTM..
