### ISSUE TITLE
Brasil (and others) Podcast episodes ATI view event not working

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9426]
**Is your feature request related to a problem? Please describe.**
Looking in ATI the podcast episodes, the 'view' tracking number is lower than the click rate. 
Tracking for podcast episodes for all other sites look correct (more views than clicks)
Checking this podcast page, the ATI beacon for the episodes does not seem to fire. 
https://www.bbc.com/portuguese/podcasts/p07r3r3t

**Describe the solution you'd like**
Check that we are sending a view (interaction) beacon on the brasil podcast page 
https://www.bbc.com/portuguese/podcasts/p07r3r3t

**Describe alternatives you've considered**

**Testing notes**
Navigate to a podcast page https://www.bbc.com/portuguese/podcasts/p07r3r3t
Check ATI for the episodes-audio interaction event when the episode list is in view
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by jroebu14** [comment]
@JonBeeb this isn't the issue but I've noticed that the view event doesn't fire until you view 50% of the whole episode list component. This means a view event may not fire if there are a lot of episodes.

**Comment by rebeccamcginn** [comment]
@jroebu14 I think you're right that this is the issue. On desktop, the viewport is tall enough to fire the observer:

![image](https://user-images.githubusercontent.com/59573468/134694069-d15decd3-9fd2-46bf-942d-a68614199656.png)

Component height is 1935 and viewport is 969, ie we can see 10 of the 20 episodes.

On mobile, we can't view 50% of the component due to the amount of episodes and so the observer never fires. Most we can view on an iPhone X is 7 out of 20

We could add some logic to adjust the threshold based on the number of episodes.

**Comment by jroebu14** [comment]
@rebeccamcginn @ryanmccombe we don't need to adjust the threshold. I think we can use the implementation from example 2 [here](https://github.com/bbc/simorgh/blob/latest/src/app/hooks/useViewTracker/README.md) to fix the issue.

```
   * Example 2 - Log 1 view event when any of the the component's containing items are viewed.
   * In this example, by initialising the hook OUTSIDE of the `topStories` map
   * callback function and assigning the single `ref` to multiple DOM elements, only
   * one view event is logged even if all 3 story items are viewed.
```

**Comment by ryanmccombe** [comment]
> @rebeccamcginn @ryanmccombe we don't need to adjust the threshold. I think we can use the implementation from example 2 [here](https://github.com/bbc/simorgh/blob/latest/src/app/hooks/useViewTracker/README.md) to fix the issue.
> 
> ```
>    * Example 2 - Log 1 view event when any of the the component's containing items are viewed.
>    * In this example, by initialising the hook OUTSIDE of the `topStories` map
>    * callback function and assigning the single `ref` to multiple DOM elements, only
>    * one view event is logged even if all 3 story items are viewed.
> ```

Oops - didn't see this comment before I made the PR.  Got two options for this now.  Guessing the second is preferred?

Changing the intersection threshold: https://github.com/bbc/simorgh/pull/9458
Forwarding the reference: https://github.com/bbc/simorgh/pull/9460

**Comment by jroebu14** [comment]
Yeh maybe the 2nd to keep consistency with the other view tracker implementations 👍
