### ISSUE TITLE
Replace fonts for Tamil, Bengali and Sinhala on Live Topic pages

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#9435]
**Is your feature request related to a problem? Please describe.**
To mirror the font replacement that's being carried for Simorgh, we need need to the same for the WS Live and Topic Pages. These pages are served by Morph within a combination of different Morph modules. 

**Describe the solution you'd like**
Following the steps from a previous font replacement [issue](https://github.com/bbc/simorgh/issues/8754) we need to carry out the same process to replace the following service fonts

[Tamil](https://github.com/bbc/morph-modules/blob/master/morph-grandstand/sass/tamil/_config.scss):  Latha replaced by [NotoSansTamil](https://ws-downloads.files.bbci.co.uk/fonts/index.html#NotoSansTamil)
[Bengali](https://github.com/bbc/morph-modules/blob/master/morph-grandstand/sass/bengali/_config.scss):  ShonarBangla replaced by [NotoSerifBengali](https://ws-downloads.files.bbci.co.uk/fonts/index.html#NotoSerifBengali)
[Sinhala](https://github.com/bbc/morph-modules/blob/master/morph-grandstand/sass/sinhala/_config.scss): IskoolaPota replaced by [NotoSerifSinhala](https://ws-downloads.files.bbci.co.uk/fonts/index.html#NotoSerifSinhala) 

 1. Clone the morph-modules [repo](https://github.com/bbc/morph-modules)
 2. Navigate to the morph-grandstand [module](https://github.com/bbc/morph-modules/tree/master/morph-grandstand)
 3. Go to the `morph-grandstand/sass` directory
 4. In the `_config.scss` for Tamil, Bengali and Sinhala replace the fonts see [here](https://github.com/bbc/morph-modules/pull/39714/files) for examples - Don't change script name
 5. 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by pvaliani** [comment]
Order of merges:

1. Update grandstand scripts _config.scss for the language service required (if font sizes/line height need changing)
2. Create morph grandstand pr with font changes - We can also bump bbc grandstand in here
3. Then bump morph-grandstand in share-tools
4. Then bump morph grandstand in lx-stream v4
5. Then bump morph grandstand in lx-page
6. Then bump lx-stream v4 in news-lx-wrapper
7. Then bump lx-stream-v4 in lx-commentary

We need to bump the internal packages as well as the root packages i.e as we currently do for Psammead
