### ISSUE TITLE
Populate Lighthouse test URLs dynamically from scenario data

### ISSUE THREAD

**Issue by radiocontrolled** [bbc/simorgh#944]
**Is your feature request related to a problem? Please describe.**
Currently URLs to test in Lighthouse are manually added in` simorgh/lighthouse.js` (see https://github.com/BBC-News/simorgh/pull/876/files). 

They should be populated by our scenario data instead. We may want to run lighthouse tests against all our scenarios (including Persian).

**Describe the solution you'd like**
Adapt the Lighthouse script to make use of `fs.readdir('data/prod/news/')` to pull in some or all of our scenarios. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by radiocontrolled** [comment]
See https://github.com/BBC-News/simorgh/issues/331 for main Lighthouse issue

**Comment by chris-hinds** [comment]
This is no longer required as as apart of [this pr](https://github.com/bbc/simorgh-infrastructure/pull/429) Lighthouse no longer runs against fixture data or Loacalhost. It is now running in our CD pipeline against the test environment on a live asset.
