### ISSUE TITLE
Replace fonts for Tamil, Bengali and Sinhala on access to news pages

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9459]
**Is your feature request related to a problem? Please describe.**
To mirror the font replacement that's being carried for Simorgh, we need to do the same for the WS Morph pages (specifically tamil access-to-news) These pages are served by Morph within a combination of different Morph modules.

**Describe the solution you'd like**
Following the steps from a previous font replacement issue we need to carry out the same process to replace the following service fonts
Details for previous changes can be found here:
https://github.com/bbc/morph-modules/pull/39891/files
 bump grandstand https://www.evernote.com/shard/s663/sh/38dd49b9-469a-3fc7-a15a-4492dd77a225/de014a52ca443cdde35867849c48abd2 

Tamil: Latha replaced by NotoSansTamil
Bengali: ShonarBangla replaced by NotoSerifBengali
Sinhala: IskoolaPota replaced by NotoSerifSinhala
**Describe alternatives you've considered**

**Testing notes**
Check the following page uses the NotoSansTamil font
https://www.test.bbc.com/tamil/access-to-news?_x_candy_override=https%3A%2F%2Fapi.test.bbc.co.uk&morph_env=test
https://www.bbc.com/tamil/access-to-news
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by JonBeeb** [comment]
Before image
![image](https://user-images.githubusercontent.com/16046375/135430020-02d0d1f0-4b83-49b5-8c0e-72d617007dd4.png)

**Comment by paruchurisilpa** [comment]
Looks good to me..
TEST:
* https://www.test.bbc.com/tamil/access-to-news?morph_env=live

<img width="1431" alt="Screenshot 2021-09-30 at 13 01 35" src="https://user-images.githubusercontent.com/1379277/135451462-e2ffaf0f-0aa6-46b2-b5a6-bd291e69e98b.png">

LIVE:
* https://www.bbc.com/tamil/access-to-news

<img width="1431" alt="Screenshot 2021-09-30 at 12 58 16" src="https://user-images.githubusercontent.com/1379277/135451057-b20433f4-0e09-4985-8eec-9c34b55dfae1.png">
