### ISSUE TITLE
`uncaught:exception` event causing E2E failures on STY and MAPs

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#9465]
The E2Es are now failing due to uncaught exceptions, since 14:55 on Tuesday 28th September. The error is 

'TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.'

I cannot replicate this running the tests on my computer. I cannot see any console errors. 

It is likely to be related to the PR removing the code in this change https://github.com/bbc/simorgh/pull/9457/files

Do we want to put the code back to handle the exception, or fix the source of the exception?

Here are some screenshots of the slightly different error messages on different pages:

simorgh-cd, TestEnvironment, MAP
<img width="910" alt="Screenshot 2021-09-29 at 14 33 48" src="https://user-images.githubusercontent.com/54575620/135279369-516e2035-d34c-441e-85de-7211aa7e907d.png">

live-simorgh-e2e-scheduled, Story Page, AMP
<img width="895" alt="Screenshot 2021-09-29 at 14 38 34" src="https://user-images.githubusercontent.com/54575620/135279786-8e2ab244-073e-4c6a-b9c3-79ec967ae714.png">

live-simorgh-e2e-scheduled, MAP

<img width="986" alt="Screenshot 2021-09-29 at 14 41 36" src="https://user-images.githubusercontent.com/54575620/135280363-8f38efb8-dc3c-4a31-b5f2-d76b45dad755.png">

test-simorgh-e2e-scheduled, MAP

<img width="993" alt="Screenshot 2021-09-29 at 14 45 00" src="https://user-images.githubusercontent.com/54575620/135280922-96075a41-7d29-49ea-8c1a-202ede3f7732.png">

I have included some of the test failures after the exception test failure as it shows that whatever is happening is also affecting the check for iframes etc

**Comment by amoore108** [comment]
Could be related to changes here https://github.com/bbc/simorgh/pull/9457 that removed code to ignore promise based exceptions. Re-adding this will probably fix the issue, although its worth exploring why those errors are being thrown in the first place.
