### ISSUE TITLE
Implement Cypress dashboard

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#948]
**Is your feature request related to a problem? Please describe.**
Currently when our E2Es fail on CI we have to replicate the failure on our local device this can cause inconsistency and takes up time. Ideally we should see the actual failure that occurred on CI.

**Describe the solution you'd like**
Cypress Dashboard - a GUI to step through all tests that run, including those on CI https://docs.cypress.io/guides/core-concepts/dashboard-service.html#Overview. ~As part of this we should evaluate whether to turn back on `screenshotOnRunFailure` in the Cypress config.~ (Edit: this has already been turned on)  

**Describe alternatives you've considered**
N/A

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Additional context**
We initially turned `screenshotOnRunFailure` off in the Cypress settings as it creates local screenshots on failures and these can easily be committed by mistake. Ideally the Cypress tests should not be embedded in the application but act as a standalone test suite. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Now we have turned on Screenshots in Cypress, whenever there is a failing Cypress integration test on Jenkins, there is a file output in `/cypress/screehsots/*`.

We should ensure there is a simple way to view these files that are on the Jenkins box. We should update the Simorgh Infrastructure Readme to have the relevant notes.

**Comment by jamesbhobbs** [comment]
There's no point doing this, we'll exceed the free allowance in no time. We'd need purchasing and I don't think it's worth it.
