### ISSUE TITLE
Change SEO medata Description for BBC Azeri 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#9514]
**Is your feature request related to a problem? Please describe.**
The Azeri Service want to update the SEO meta description for the service to improve their SEO

They want to change it from 

"BBC News Azərbaycanca öz səhifələrində Azərbaycan və dünyadan bu günün xəbərləri və şərhlərini təqdim edir. Visit BBC News Azeri for the latest from Azerbaijan, Armenia, Georgia."

![image](https://user-images.githubusercontent.com/22519682/136348662-0844cd24-2cf0-40a1-b473-982a2a26dab4.png)

To

"BBC News Azərbaycanca öz səhifələrində Azərbaycan və dünyadan bu günün xəbərləri və şərhlərini təqdim edir. Visit BBC News Azerbaijan for the latest from Azerbaijan, Armenia, Georgia."

Users are more likely to search for BBC Azerbaijan rather than BBC Azeri. 

**Describe the solution you'd like**
Update the config to reflect the change requested above. 

https://github.com/bbc/simorgh/blob/be9497217bb82e2b1c80e7b7f7d962f5ba901a0a/data/azeri/frontpage/index.json

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by aeroplanejane** [comment]
Amending my typo. Sorry @DarioR01 !

**Comment by DarioR01** [comment]
No worries @aeroplanejane 😄

**Comment by aeroplanejane** [comment]
Will be fully resolved by JIRA CPSSITE-2267
