### ISSUE TITLE
Update the Font stack for the Orbit so we use the correct fonts in Orbit on the Topics/Live pages

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9516]
**Is your feature request related to a problem? Please describe.**
There are more fonts need to be set for more platforms
Update the fonts for Orbit (based on the Live page updates) 

**Describe the solution you'd like**
Update the following files with the updated Live pages font stacks (with Noto fonts)
https://github.com/bbc/nav-orbit/tree/master/app/locales

https://github.com/bbc/nav-orbit/blob/master/app/locales/ta-IN.json
https://github.com/bbc/nav-orbit/blob/master/app/locales/si-LK.json

(This looks up to date?)
https://github.com/bbc/nav-orbit/blob/master/app/locales/bn-BD.json

**Describe alternatives you've considered**

**Testing notes**
Test the correct fonts are used in the 'ORBIT' bar on test/live pages

[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by JonBeeb** [comment]
I think we just need to update the font stack config for each service

**Comment by pvaliani** [comment]
> I think we just need to update the font stack config for each service

moving this to done as this was merged last week!
