### ISSUE TITLE
Document the merging process for Simorgh

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#952]
**Background**
Currently, we have not documented clear instructions on the process of merging PRs in both simorgh and simorgh-infrastructure. We should clearly define and document when a PR is allowed to be merged.

**Suggested approach**
We should document that merging PR's to either repo's should only be performed when the latest of both simorgh and simorgh-infrastructure is a successful job.

Therefore before merging a PR I should check that the jenkins jobs for latest in each repo is not currently running and the previous build is green.

**Additional Content**
Defining this process then helps shape automating the process rules such as #143

**Comment by radiocontrolled** [comment]
It could be helpful to have a high level flow chart of how our pipelines work.
