### ISSUE TITLE
Hover state underline on Firefox 

### ISSUE THREAD

**Issue by skwong25** [bbc/simorgh#9535]
**Describe the bug**
Hover state underline is visually unclear. Noticed across a few services with non-Roman scripts: 
- Noticable: Hindi, Urdu, Persian 
- Doesn't affect: Bengali, Chinese, Tigrinya, Korean, Gujarati, Sinhala, Arabic

For the affected services, even if there are no downward protrusions (like a 'p' or 'y') in the scripts, sections of underline are still missing. The result is a visually-unclear hover state underline.

This occurs on Desktop Firefox only.
Does not occur on Desktop Opera, Chrome or Safari. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.bbc.com/hindi'
2. Hover over article links to trigger hover state.

**Expected behaviour**
The text should have a clear underline. 
Expect to see breaks in the underline where the script has downward protrusions, but should be mostly continuous otherwise.  

**Screenshots**
<img width="1792" alt="LIVE HINDI" src="https://user-images.githubusercontent.com/59804681/136927068-88c0578b-f5f8-464a-8583-6b47ecc9ac78.png">
<img width="1792" alt="LOCAL URDU" src="https://user-images.githubusercontent.com/59804681/136927071-dd667305-85eb-435d-8040-5a37b219b346.png">

**Desktop (please complete the following information):**

- Browser: Firefox 
- Version: 92.0.1

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Comment by amoore108** [comment]
@skwong25 If you want to test this locally you can use the branch here https://github.com/bbc/simorgh/pull/9558. Cheers!

**Comment by skwong25** [comment]
Thanks @amoore108 for the fix and the link to branch.

Tested locally on below services below for fix and regression. 
Promo links look & working as expected now. I will move this ticket to Ready To Merge column. 

-    Hindi, Urdu, Persian 
-    Bengali, Chinese, Tigrinya, Korean, Gujarati, Sinhala, Arabic
