### ISSUE TITLE
Investigation into possible CSS loading optimisations e.g. inlining above the fold/critical rendering path CSS

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9546]
**Is your feature request related to a problem? Please describe.**
Currently we inline all of a page's CSS in the head of the document.

CSS is a render-blocking resource. By eliminating render-blocking resources we can improve First Contentful Paint (FCP).

As an example, for this [Story page](https://www.bbc.com/mundo/noticias-america-latina-58794275) the total weight of inline CSS is 58k. Inlining all of a page's CSS may not be the best strategy as mentioned [in this article](https://web.dev/extract-critical-css/):

> if you inline a large amount of CSS, it delays the transmission of the rest of the HTML document

Another downside is that it prevents the browser from caching any CSS for reuse on subsequent page loads.

A better strategy might be inlining above the fold/critical rendering path CSS and async loading an external stylesheet that can be cached and used across all pages.

To retrieve above the fold CSS there are tools that use headless browsers to render pages and extract the CSS e.g. [Critical](https://github.com/addyosmani/critical) or [Penthouse](https://github.com/pocketjoso/penthouse).

**Describe the solution you'd like**
Prototype/hack loading a Story page with critical CSS in the head of the document and async loading the rest of the CSS then measure FCP and compare it against current FCP for the same Story page.

If we think there are clear benefits to changing the CSS loading strategy then investigate which tools we can use in our build tooling to help us inline above the fold CSS for all pages and estimate the effort involved and any potential downsides/gotchas in this approach.

An example of before & after reports can be seen here https://github.com/addyosmani/critical-path-css-demo

**Describe alternatives you've considered**
- Our current CSS loading strategy might be the best option. The complexity of inlining above the fold CSS might not be worth the small performance gain.
- There might be other CSS loading strategies better suited to rendering our pages.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by andrewscfc** [comment]
Closing in favour of other css in js investigations
