### ISSUE TITLE
Update Persian Podcast Description

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#9554]
**Is your feature request related to a problem? Please describe.**
The Persian service have updated the podcast description. 

**Describe the solution you'd like**
Update the podcast podcastPromo.brandDescription in the config for Persian with the text below

```
brandDescription:
       'گفتگو با چهره‌های سیاسی، هنری و ادبی از تلویزیون فارسی بی بی سی.',
```

Update the Persian config found here - https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/persian.js

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by paruchurisilpa** [comment]
The brandDescription is updated in config to the below:

brandDescription:
       'گفتگو با چهره‌های سیاسی، هنری و ادبی از تلویزیون فارسی بی بی سی.',
