### ISSUE TITLE
Setup speedtracker

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#962]
**Is your feature request related to a problem? Please describe.**
Discovery got infosec and legal approval for News to use speedtracker which runs webpagetest and lighthouse, logging the results here https://bbc-news.github.io/news-speedtracker/

https://github.com/BBC-News/news-speedtracker

**Describe the solution you'd like**
Set up a speedtracker repo for articles have it run on many pages and devices

**Additional context**
Setup guide written by @jamesdonoh https://confluence.dev.bbc.co.uk/display/news/SpeedTracker+setup

- [ ] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by jamesdonoh** [comment]
We are not going to set this up, as SpeedTracker's maintainer says in its current form it is not sustainable. Have separately been talking to Monitoring about a better-supported synthetic monitoring solution.
