### ISSUE TITLE
Refactor Story Promo Component

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#9624]
**Is your feature request related to a problem? Please describe.**

Refactor Story Promo component to simplify future iterations of onward journeys.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by jroebu14** [comment]
One way to refactor this component is to use the compound component pattern to compose UI variants in separate files and use react context to pass data to child components. I've not used this pattern much but I think it would be used similar to this example https://github.com/jroebu14/promo-proto/tree/main/src

The `Promo` component deals with the context and imports child components to make them into sub-components of `Promo`  e.g. `Promo.Image`. The other components e.g. `StandardPromo` are created from the `Promo` component and its sub-components. All data related props are passed to the `Promo` component which the sub-components will automatically receive from context.

The sub-components can be included/excluded at will and composed in any order to achieve the desired UI. This is better than providing boolean props e.g. `showImage` or conditionally rendering structural elements within one component which leads to complexity.

One thing I'm actually not sure about with this pattern is if I'm misusing context by passing all data related props to it. Examples I've seen online only use the context for shared state. I think the benefit of using if for data props too is that it will remove the need to props-drill. A downside to this though is that sub-components will always have to get data from the context and there might be cases you want to pass the data as props.

I think there are only 3 StoryPromo variations - top, regular and leading. Splitting the StoryPromo up into 3 variant components made of sub-components should reduce a lot of the complexity and make it easier to build new variants.
