### ISSUE TITLE
Make use of WebP images via ImageChef

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#9628]
**Is your feature request related to a problem? Please describe.**
WebP is a modern image format which should reduce the weight of images in use across supported pages in Simorgh by approximately 25% compared with PNGs & JPEGs on similar sizes. 

As per OSPREY-3783, WebP support is being added to ImageChef so we can make use of this. 

**Describe the solution you'd like**
- [x] https://github.com/bbc/simorgh-infrastructure/issues/1492
- [x] Add HTML picture element with different picture sources
- [x] Make available on Test to begin with
- [x] Determine phasing for roll out
- [ ] Understand likely performance improvements
- [ ] [Stretch] Determine how we might be able to replace other images by a WebP format

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by jroebu14** [comment]
Questions for refinement:

- will the webp image src be available in the Ares data or do we need to write code to replace .jpg with .webp?
- we currently preload .jpg images. do we also preload .webp images or just preload .webp and assume most browsers support .webp and browsers that don't will preload an image format it doesn't support?
- where should we add the picture element? should it wrap each use of the psammead-image in simorgh or should we add it to psammead-image?
