### ISSUE TITLE
Make use of the data-hero attribute to improve AMP LCP scores

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#9630]
**Is your feature request related to a problem? Please describe.**
As per - https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/explainer/

An AMP Optimizer can significantly improve the time it takes to render images in the first viewport. This is critical when optimizing the LCP times to meet the Core Web Vitals.

In AMP, hero images can be explicitly declared by annotating an amp-img with the data-hero attribute:

`<amp-img data-hero src="/hero.jpg" layout="responsive" width="640" height="480" alt="..."></amp-img>`

AMP Optimizers support a maximum of two hero images on a page to avoid blocking bandwidth for other critical resources. 

**Describe the solution you'd like**
Apply data-hero attribute to relevant content to improve LCP in AMP

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by rebeccamcginn** [comment]
Blocked by the AMP Optimizer PR revert: https://github.com/bbc/simorgh/pull/9542 + https://github.com/bbc/simorgh/pull/9626

**Comment by andrewscfc** [comment]
Closing following these PRs:
Adds data-hero to STY AMP pages: https://github.com/bbc/simorgh/pull/9847
Adds data-hero to Article AMP pages: https://github.com/bbc/simorgh/pull/9919
