### ISSUE TITLE
JSON stringify/parse page data

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9636]
**Is your feature request related to a problem? Please describe.**
There can be a small performance win by stringifying page data on the server and parsing on the client. More details found here https://v8.dev/blog/cost-of-javascript-2019#json

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by amoore108** [comment]
I've had a brief look at this using the Mundo FrontPage as the test set. I ran the pageData JSON for that page through the [json-parse-benchmark](https://github.com/GoogleChromeLabs/json-parse-benchmark), but the results range from very small gain to very small loss.

I applied JSON.stringify() in `src/server/index.jsx` = `data.pageData = JSON.stringify(data.pageData);`

And then JSON.parse() in `src/app/containers/PageHandlers/withData/index.jsx` = `<Component pageData={JSON.parse(pageData)} {...props} />`.

Not sure if our JSON objects are large enough to benefit from this, although the article linked does say that its a good rule of thumb to apply this technique to objects 10kB or larger, which the Mundo FrontPage JSON object is.

Results:
```
Benchmarking JS literal on v8-7.5.288… 0m2.130s
Benchmarking JSON.parse on v8-7.5.288… 0m2.279s

Benchmarking JS literal with cold loads on v8-7.5.288… 0m0.212s
Benchmarking JSON.parse with cold loads on v8-7.5.288… 0m0.207s

Benchmarking JS literal with warm loads on v8-7.5.288… 0m0.122s
Benchmarking JSON.parse with warm loads on v8-7.5.288… 0m0.180s

Benchmarking JS literal on v8-7.6.303… 0m2.106s
Benchmarking JSON.parse on v8-7.6.303… 0m2.177s

Benchmarking JS literal with cold loads on v8-7.6.303… 0m0.216s
Benchmarking JSON.parse with cold loads on v8-7.6.303… 0m0.201s

Benchmarking JS literal with warm loads on v8-7.6.303… 0m0.135s
Benchmarking JSON.parse with warm loads on v8-7.6.303… 0m0.138s

Benchmarking JS literal on v8-7.7.299… 0m2.297s
Benchmarking JSON.parse on v8-7.7.299… 0m2.255s

Benchmarking JS literal with cold loads on v8-7.7.299… 0m0.213s
Benchmarking JSON.parse with cold loads on v8-7.7.299… 0m0.176s

Benchmarking JS literal with warm loads on v8-7.7.299… 0m0.124s
Benchmarking JSON.parse with warm loads on v8-7.7.299… 0m0.132s

Benchmarking JS literal on v8-7.8.279… 0m2.105s
Benchmarking JSON.parse on v8-7.8.279… 0m2.232s

Benchmarking JS literal with cold loads on v8-7.8.279… 0m0.228s
Benchmarking JSON.parse with cold loads on v8-7.8.279… 0m0.183s

Benchmarking JS literal with warm loads on v8-7.8.279… 0m0.117s
Benchmarking JSON.parse with warm loads on v8-7.8.279… 0m0.140s

Benchmarking JS literal on v8… 0m2.465s
Benchmarking JSON.parse on v8… 0m2.466s

Benchmarking JS literal with cold loads on v8… 0m0.225s
Benchmarking JSON.parse with cold loads on v8… 0m0.186s

Benchmarking JS literal with warm loads on v8… 0m0.141s
Benchmarking JSON.parse with warm loads on v8… 0m0.143s

Benchmarking JS literal on chakra… 0m2.510s
Benchmarking JSON.parse on chakra… 0m2.582s
```

**Comment by jroebu14** [comment]
Thanks for this @amoore108 Happy to close this issue based on your investigation.
