### ISSUE TITLE
Mac VoiceOver reading space in figure captions

### ISSUE THREAD

**Issue by DarioR01** [bbc/simorgh#9641]
**Describe the bug**
VoiceOver on Mac is reading space in figure captions.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/mundo/noticias-internacional-58389811
2. Navigate to the first figure
3. Navigate each element by pressing VO+RightArrow button
4. VoiceOver will read as follows:
-  fuente de la imagen, EPA, clikable
- Pie
- Space
- Uno de los ultimos vuelos en..... Afganistan., clikable

**Expected behaviour**
It should not read out Space
It should not read Pie only. It should read the entire phrase Pie de Foto

**Screenshots**

<img width="1792" alt="Screenshot 2021-11-04 at 16 12 22" src="https://user-images.githubusercontent.com/90621252/140378749-a2c4de3c-b180-450f-8a2a-f3f9c6796e1b.png">

<img width="1792" alt="Screenshot 2021-11-04 at 16 22 06" src="https://user-images.githubusercontent.com/90621252/140378781-a00b0543-5d90-472f-90c1-9e7c3d33b9e7.png">

<img width="1792" alt="Screenshot 2021-11-04 at 16 15 37" src="https://user-images.githubusercontent.com/90621252/140378802-b51863c0-4fcb-4d35-afba-a897857d86bd.png">

<img width="1792" alt="Screenshot 2021-11-04 at 16 15 41" src="https://user-images.githubusercontent.com/90621252/140378833-beb6168f-1814-4361-b6ef-4bba94a6ea0b.png">

**Desktop (please complete the following information):**

- OS: MacOs Big Sur 11.6
- Browser Firefox 
- Version 93.0

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
Might be very similar to issue [#9559](https://github.com/bbc/simorgh/issues/9559) experienced on TalkBack with comma being read out as comma instead of a pause.

**Comment by greenc05** [comment]
@DarioR01 please could we re-test this using the Safari browser? This is the default VoiceOver browser on Mac.

**Comment by DarioR01** [comment]
@pvaliani Already tested and he had no issue. We will simply report the bug to Mozilla Firefox and close the issue.

**Comment by greenc05** [comment]
Great, yes please close.

**Comment by pvaliani** [comment]
Bug report to Mozilla is here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1740025

Issue closed :)
