### ISSUE TITLE
Do we need to add alarms for APIs that render content on the page when they return empty arrays? 

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9649]
**Is your feature request related to a problem? Please describe.**
The WSOJ sections of the articles stopped appearing on the latest articles on Friday 5th Nov and this issue was raised by editorial.
 
The WSOJ section depends on this (example) endpoint which started to return an empty array. 
https://onward-journeys.api.bbci.co.uk/api/recommendations/mundo/noticias-internacional-59172725

Ideally we should know before editorial if there is a problem getting content for a page.    

**Describe the solution you'd like**
Should we set up alarms when we get an empty array for any APIs that provide data for the page?  

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by joshcoventry** [comment]
@JonBeeb Do we know how often this happens? 

Assuming we do not display the OJ component if the array is empty, is that not enough so editorial know it's not showing because there wasn't any data? 

cc @aeroplanejane
