### ISSUE TITLE
Reduce spacing on WSOJ 

### ISSUE THREAD

**Issue by gailetaplin** [bbc/simorgh#9657]
**Describe the bug**
WSOJ block has too much space to the right of the text at the smallest break points, causing it to wrap sooner than necessary + extending the block.

**To Reproduce**
Any service with the component at sizes below 400px. (Hindi, Mundo, Turkish)

Go to an article page, (https://www.bbc.com/turkce/haberler-dunya-59220895) and see WSOJ after 5th Paragraph. 

**Expected behaviour**
Reduced margin to 8px on the right hand side. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74012325/140958549-aeba4996-ff7e-4740-be49-bec9c4e9dbfa.png)
![image](https://user-images.githubusercontent.com/74012325/140958581-dc240d1e-0e8d-44f4-a2ef-abe7702cc9dd.png)
![image](https://user-images.githubusercontent.com/74012325/140958624-b66f25a2-8d9d-4c20-bcd5-5b79a2b597ec.png)
![image](https://user-images.githubusercontent.com/74012325/140958655-e3d3c2e6-eba1-499a-b5ea-2e99dda60df5.png)
![image](https://user-images.githubusercontent.com/74012325/140958680-7b1ad8a1-ab86-42a7-a753-99121ade5b49.png)
![image](https://user-images.githubusercontent.com/74012325/140958709-bac864b0-8969-415f-8562-e66f3e7e4cc9.png)

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by Reedham20** [comment]
Hey is anyone working on it
If not I would love to give it a try
