### ISSUE TITLE
TalkBack reading comma in RecentVideoEpisodes

### ISSUE THREAD

**Issue by DarioR01** [bbc/simorgh#9664]
**Describe the bug**
TalkBack is reading commas in RecentVideoEpisodes instead of taking a brief pause.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://5d28eb3fe163f6002046d6fa-txxqywudqk.chromatic.com/?path=/story/containers-episode-list-video--multiple-items
2. Use Talkback to navigate each element
3. Notice that Talkback reads out the comma's instead of making a short pause

**Expected behaviour**
Talkback should not read commas.

**Screenshots**

<img width="1792" alt="Screenshot 2021-11-11 at 11 56 21" src="https://user-images.githubusercontent.com/90621252/141294053-bf8d1cf4-eaa1-4fc2-a6a4-9374bb81fb0d.png">
**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A5 2017
- OS: Android: 8.0.0 Samsung Experience: 9.0
- Browser: Chrome
- Version: 95.0.4638.74

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
Here are some previous PR about the same bug. This bug is usually resolved by concatenating the comma to the rest of the text:
https://github.com/bbc/simorgh/pull/9594
https://github.com/bbc/simorgh/pull/9566

**Comment by DarioR01** [comment]
this will require testing on supported screen readers:

- [ ] NVDA
- [ ] JAWS
- [ ] TalkBack
- [ ] VoiceOver for Mac
- [ ] VoiceOver for iOS

**Comment by greenc05** [comment]
As discusssed with @DarioR01 we will just fix the comma that can be concatenated
