### ISSUE TITLE
FrostedGlass promo Experiment

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#9681]
**Is your feature request related to a problem? Please describe.**

REF: https://jira.dev.bbc.co.uk/browse/NEWSWORLDSERVICE-1376

Launch an experiment to test the performance of multiple variations of the high impact promo within the features and analysis onward journeys module on CPS and Optimo articles. 

Optimizley needs to be configured for the following
All WS STY (and Optimo) pages across all services
- Mundo
- Brasil
- Turkish
- Hindi
- Arabic
- Russian
- Ukrainian
- Persian
- Kyrgyz (Optimo)

It also needs to be set up show on mobile only.

The following events need to be configured:
Component clicks
Component views
Page views
Visitors 

Variations are

Control: 

No impact promos - existing features promos on STYs 

Variant A: 
High impact promo on first item in features on mobile only
- Minimum contrast 10
- Palette 10

Single Impact Promos

Variant B:
- High impact promo on all items in features on mobile
- Minimum contrast 10
- Palette 10

Variant C: 

- 1 impact promo
- minimumContrast 7
- paletteSize 20

Variant D: 

- All impact promo
- minimumContrast 7
- paletteSize 20
  

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by amoore108** [comment]
Current code that determines the display of the FrostedGlassPromo:
https://github.com/bbc/simorgh/blob/latest/src/app/containers/CpsFeaturesAnalysis/index.jsx#L50-L60

and
https://github.com/bbc/simorgh/blob/latest/src/app/containers/CpsFeaturesAnalysis/index.jsx#L115-L123

**Comment by JonBeeb** [comment]
Experiment is set up in Optimizley.
All IDs can be found here: https://app.optimizely.com/v2/projects/20897131008/experiments/21129541057/api_names

**Comment by HarveyPeachey** [comment]
Couple of questions as I missed refinement on this. Are we getting rid of the frosted glass promo iSite configuration? And are we skipping the scroll depth event for this as well?

**Comment by amoore108** [comment]
> Couple of questions as I missed refinement on this. Are we getting rid of the frosted glass promo iSite configuration? And are we skipping the scroll depth event for this as well?

Yes I believe will be removing the iSite configuration for this, cc @JonBeeb @aeroplanejane.

The scroll depth event is now in a separate ticket https://github.com/bbc/simorgh/issues/9789
