### ISSUE TITLE
a11y Issue - `aria-labelledby` referencing elements that do not exist

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#9696]
**Describe the bug**
This code is attempting to assign URLs to IDs: https://github.com/bbc/psammead/blob/72b856d268b362833038a4be102634a493593d38/packages/components/psammead-story-promo/src/IndexAlsos/index.jsx#L63

URLs can contain characters that are not valid ID characters

> ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens (“-”), underscores (“_”), colons (“:”), and periods (“.”)

https://www.w3.org/TR/html4/types.html#type-id

This is causing an issue where we have `aria-labelledby` attributes referring to IDs that do not exist

![Screen Shot 2021-11-24 at 12 39 23 copy](https://user-images.githubusercontent.com/8601460/143241348-3b083df3-f95f-4297-9ab0-6a809b8e4bb9.png)

https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1637756847173-65786.report.html

This is currently only on the test environment - https://www.test.bbc.com/persian/afghanistan

**Comment by amoore108** [comment]
Couple of other merged PRs that may also be affecting this:

https://github.com/bbc/psammead/pull/4600/files#diff-0d6098383c76ce9d8f2a56372f1db8727d5fd5d39bf7394825ba72a6dd74f485

https://github.com/bbc/psammead/pull/4587/files#diff-97e58d99c28dbaf83be5f6d4cf90896871b5f07813ea8a277f6225a7c6b4c41a
