### ISSUE TITLE
Pair with UX to define <img> srcset values

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#971]
**Is your feature request related to a problem? Please describe.**
Following the [responsive image investigation](https://github.com/BBC-News/simorgh/pull/899) outcome being that we should use `srcset` we need sit with UX to define the `srcset` values. This should be evaluated AMP-first. 

**Describe the solution you'd like**
Pair with UX and across different devices and browsers trying different `srcset` values. Ensure image quality is optimised across the different variations. 

**Testing notes**
None needed, since this is an investigation.

**Additional context**
For the investigation I used the following values `240, 320, 480, 624, 800`. As pixel density affects the browsers calculation of which image to select we should not supply an image greater than 800px. This is because an iPhone, which has a width of 500px and a pixel density of 3, would attempt to select an image of 1500px or more and the image quality difference is not worth the additional page weight. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by oluoluoxenfree** [comment]
My findings with the inital investigation's values (240, 320, 480, 624, 800, and a  640 default as was already in the page) were as follows:

## Emulated devices in Google Chrome

| Device | Pixel density ratio | Device width | Chosen image width (px) |
|:------:|:------------:|:-------------------:|:-----------------------:|
| Jiophone 2 | 1 | 240px  | 240 |
| Nokia N9  | 1 | 480px | 480 |
| Nokia Lumia 520 | 1.5 | 320px | 480 |
| Blackberry Playbook | 1 | 600px | 624 |

## Actual Devices

| Device | Pixel density ratio | Device width | Chosen image width (px) |
|:------:|:------------:|:-------------------:|:-----------------------:|
| iPhone 5s | 2 | 320px | 640 |
| Nexus 5x | 2.6 | 412px | 800 |
| Oneplus 5 | 2.375 | 455px | 800 |
| iPhone 4 | 2 | 320px | 640 |
| Galaxy Note 2 | 2 | 360px | 800 | 


## Things to consider

- Is it desirable to have the 800px image downloaded on (almost) all of the high resolution devices?
- Including more images in the 700 - 800 range causes some devices to pick a smaller image, but is this worth the increased length of srcset?
