### ISSUE TITLE
Create a Utility/Hook To Detect a User's Viewport Size

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#9716]
**Is your feature request related to a problem? Please describe.**
As part of the Optimizely work, it has been decided that the experiment on the Features and Analysis component with a high impact promo should only be ran if a user is using a mobile device. This is to mitigate the side effect of Optimizely switching variants causing a jarring user experience, so it should only be ran if the features and analysis promo is below the fold.

**Describe the solution you'd like**
As our application is agnostic, both with server side rendering and client side rendering, this utility should probably be implemented as a custom react hook, that makes use of the `useEffect()` to only run on the client. What the custom hook should produce is a string that can be used by Optimizely's decision logic, to decide wether to run an experiment for the user. 

As the current scope is just for mobile the the hook would return a `mobile` string when the viewport is a mobile size (as described below). If not, then the return value would be null. 

The default value should be null (i.e, initially), until the `useEffect()` is invoked on render, and when it does Optimizely will then use that to update its decision.

Integrating this utility with Optimizely can be done separately to decouple the work.

Mobile view size: Support <= 1008px i.e `GEL_GROUP_4_SCREEN_WIDTH_MIN = `63rem`; // 1008px`

**Describe alternatives you've considered**
Not using a custom react hook, and implementing this as a standard JS function.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by ryanmccombe** [comment]
This might already be done - the `useMediaQuery` hook probably covers the requirements here?

https://github.com/bbc/simorgh/blob/be9497217bb82e2b1c80e7b7f7d962f5ba901a0a/src/app/containers/Navigation/index.canonical.jsx#L32-L36

**Comment by HarveyPeachey** [comment]
> This might already be done - the `useMediaQuery` hook probably covers the requirements here?
> 
> https://github.com/bbc/simorgh/blob/be9497217bb82e2b1c80e7b7f7d962f5ba901a0a/src/app/containers/Navigation/index.canonical.jsx#L32-L36

Good spot, this looks like it's gonna cover our requirements. Wooop!

**Comment by aeroplanejane** [comment]
This will be covered in another PR @ryanmccombe @HarveyPeachey @pvaliani can you link for reference?
