### ISSUE TITLE
Investigate component libraries

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#972]
**Is your feature request related to a problem? Please describe.**
We will be sharing our components with the Reach & Languages team, putting them into [Psammead](https://github.com/BBC-News/psammead).

The team is open to choosing a component structure, so let's do some research. We want to investigate popular component libraries & tools, to avoid wasting effort on solved problems, and/or investing in deprecated dependencies.

**Desired outcome**
Investigate the most popular component libraries and:

1. Decide what a component implementation should look like (RE file structure, tests, markup), according to current best practices.
2. Decide what we want from our component library in terms of a) how components are viewed, and b) how components are consumed into applications.
3. Review our choice of Pattern Library (currently [Storybook](https://github.com/storybooks/storybook)), given the decisions made in 1 and 2.

**Component libraries to investigate**
[This list](https://hackernoon.com/23-best-react-ui-component-libraries-and-frameworks-250a81b2ac42) highlights a number of popular repositories: [Material-UI](https://v0.material-ui.com/#/) ("the most popular React component library"), [React-Bootstrap](https://react-bootstrap.github.io/), [grommet](https://v2.grommet.io/), [Ant](https://ant.design/docs/react/introduce), [blueprintjs](https://blueprintjs.com/), [React Toolbox](http://react-toolbox.io/#/), [Atlaskit](https://atlaskit.atlassian.com/).

Also a number of corporate ones:

* Gov.UK: https://design-system.service.gov.uk/components
  * Has links to [prototype kit](https://govuk-prototype-kit.herokuapp.com/docs) and [gov.uk front-end](https://github.com/alphagov/govuk-frontend), which don't appear to be reusable externally.
* BuzzFeed: https://solid.buzzfeed.com/
  * Links to [buzzfeed/solid](https://github.com/buzzfeed/solid), which contains styles for components, but doesn't appear to contain HTML markup or JS.

Research and document each component library here, as a separate comment for each one (so that we can edit each in isolation). Highlight the good and bad aspects, and describe how the components (and tests) themselves are structured.

**Pattern libraries to investigate**
[Storybook](https://github.com/storybooks/storybook), [Fractal](https://fractal.build/guide/web/), [Patternlab](https://patternlab.io/), [Astrum](http://astrum.nodividestudio.com/). Let's [read](https://blog.hichroma.com/storybook-vs-styleguidist-2bd93d6dcc06) around the [subject](https://chromatichq.com/blog/evaluating-tools-building-component-library).

NB: BBC VJ started using Fractal but ended up making a bespoke (closed-source) generator: https://bbc.github.io/news-vj-patterns/ (The Fractal build was not extensible enough).

**Other things to investigate**
Dev/design workflow tools (e.g. AirBnb use [React-sketchapp](https://airbnb.design/painting-with-code/), “bridging the gap between dev & design”. 

**Additional context**
We should evaluate potential component libraries with respect to:

1. AMP support
2. how they manage utilities & styles
3. how they might integrate with Storybook (or if it is bundled with an alternative viewer)
4. publishing pipeline (e.g. NPM)
5. anything else of note

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
# Material-UI
Reviewed by Chris and Jordan.

[material-ui](https://github.com/mui-org/material-ui) is the most popular React component library in use.

## Structure
```
packages/
  material-ui/         #  (or any of the many other projects!)
    src/
      Modal/
        index.js       # pulls in Modal.js
        Modal.js
        Modal.test.js
        Modal.d.ts     # TypeScript equivalent
```

Has a `material-ui-lab` package that includes `incubator components that are not yet ready to move to core`.

## Tests
Uses [Enzyme](https://github.com/mui-org/material-ui/tree/master/test#writing-tests).

## Pattern library
Custom [script generates docs](https://github.com/mui-org/material-ui/blob/master/docs/scripts/buildApi.js) from source.

## AMP or variants?
No AMP support. Each component exports just a canonical version.

## Styles and utils?
Exports [material-ui-styles](https://github.com/mui-org/material-ui/tree/master/packages/material-ui-styles) and [material-ui-utils](https://github.com/mui-org/material-ui/tree/master/packages/material-ui-utils) packages which are consumed by the components.

## Publish mechanism
Components are [published with Lerna](https://github.com/mui-org/material-ui/blob/master/lerna.json). Components are published in a single package, with other packages exported separately too, i.e. `styles` and `utils` - as mentioned above. 

## Overall

Neat file structure, with use of vanilla JS + TypeScript definitions. The `lab` package is interesting - components that are not ready for production and more experimental.

**Comment by ChrisBAshton** [comment]
# Atlaskit
Reviewed by Chris and Jordan.

[Atlaskit](https://atlaskit.atlassian.com/) is "Atlassian's official UI library, built according to the Atlassian Design Guidelines".

## Structure
Example: https://bitbucket.org/atlassian/atlaskit-mk-2/src/1c1c92f841ae70bb75ac905701b106e95667e2e1/packages/search/quick-search/?at=master
```
packages/
  search/         #  (or any of the many other projects!)
    quick-search/
     index.ts    # exports from src/.
     src/
        index.ts       # pulls in various typescripts from components
        components/
        __tests__
```

_Many_ packages inside a single mono repo - no distinct component library. 

## Tests
Uses react-test-renderer and Jest (i.e. snapshots, like we do).

## Pattern library
Hard to say - _think_ it's using [CodeSandbox](https://codesandbox.io/).

Example output: https://atlaskit.atlassian.com/packages/core/button

## AMP or variants?
No AMP support. Each component exports just a canonical TypeScript version.

## Styles and utils?
Requires all consuming applications to pull in `import '@atlaskit/css-reset';`, which [contains reset styles and other defaults](https://bitbucket.org/atlassian/atlaskit-mk-2/src/1c1c92f841ae/packages/css-packs/css-reset/src/?at=master).

## Publish mechanism
This is a monorepo that uses [Bolt](https://github.com/boltpkg/bolt) for managing releases.

## Overall

An expansive mono-repo that includes more than just a component library, which makes it difficult to traverse. Doesn't seem to conform to definitive design patterns.

**Comment by bcmn** [comment]
# React-Bootstrap
Reviewed by Ben & Jordan

## Structure
```
/
  src/
    component.js
  test/
    component.test.js
```

Very flat structure -- tests are separated from the components. Related components seem to only be implied by naming convention, e.g.:

```
Nav.js
NavContext.js
NavDropdown.js
NavItem.js
NavLink.js
Navbar.js
NavbarBrand.js
NavbarCollapse.js
NavbarContext.js
NavbarToggle.js
```

## Tests
Using Enzyme.

## Pattern library
Using Storybook, with [documentation website utilising inline examples](https://github.com/react-bootstrap/react-bootstrap/blob/master/www/src/pages/components/breadcrumb.mdx).

## AMP or variants?
No AMP.

## Styles & utils
No CSS shipped in library, expect you to pull in Bootstrap CSS, & components have classNames to match.

## Publish mechanism
Custom script that publishes to both NPM & Bower, including showcase docs. Single (but private) script to examine & publish their repo, packaged and versioned together as a single entity. Not using anything like Lerna.

# Overall

Well-documented, & we like the inline showcase of components alongside documentation. Definitely not a fan of flat structure.

**Comment by radiocontrolled** [comment]
# Grommet
https://github.com/grommet

"a react-based framework that provides accessibility, modularity, responsiveness, and theming in a tidy package"

## Structure
In the `src/js` directory, there are directories for the following: 
```
components
contexts
themes
utils
```
`components` - React components
`contexts` - React Contexts
`themes` - Several themes, e.g. base & dark theme (https://github.com/grommet/grommet/blob/master/src/js/themes/dark.js)
`utils` - includes functions for proptypes and other utilities that are used in the components. We could move our helpers and models  (https://github.com/BBC-News/simorgh/tree/latest/src/app/helpers and https://github.com/BBC-News/simorgh/tree/latest/src/app/models) into such a directory.

## Tests

Jest snapshot tests with `jest-styled-components`

## Pattern library

Storybook: https://storybook.grommet.io/
CodeSandbox for each component, as well: https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=button&module=%2Fsrc%2FButton.js  
Great for lowering the barrier for contributing back to the component library. 

## AMP or variants?

No

## Styles & utils

Within `grommet`, there is a utils directory, with JavaScript files exporting utilities.  The component files use `styled-components`.

There is a separate `'grommet-icons'` npm module (https://github.com/grommet/grommet-icons) which is independent of the standard `grommet` component library.
```
import { Alarm } from ‘grommet-icons’;
<Alarm color=‘plain’ size=‘xlarge’ />
```

## Publish mechanism

Publishes grommet to npm
There are separate grommet repos (e.g. grommet-icons)

# Overall

* Nice approach to a11y (consistent way of passing a11y props down to components, e.g https://v2.grommet.io/button, https://v2.grommet.io/anchor)
* The grommet directory structure makes sense. However, if we were to replicate it, we'd need to ensure we'd package up individual components.

**Comment by bcmn** [comment]
# BlueprintJS
Reviewed by Ben

## Structure
```
/
  packages/
    core/
      src/
        common/
          typography
          colors
        component/
          component.scss
          component.md
          component.tsx
      test/
        component/
          component.test.js
    additional-packages...
```

Separated tests, not clear what criteria are for a component to be included in `core/`. The "additional packages" above includes everything from "table" or "list selection" components, to a package dedicated to generating their documentation website & their staging package for components under development.

## Tests
Uses Lerna to run the tests for each package in parallel. Tests use Enzyme.

## Pattern library
Doesn't really seem to use a third-party one as defined in this issue. 

Docs are generated from the other packages in `packages/`. Components are [showcased inline on the docs site](https://blueprintjs.com/docs/#core/components/breadcrumbs). Examples are specified in the `docs-app` package, with a really good interface for trying out different prop values & other variables that will change behaviour. I _think_ the examples are just pulled in at the top of the relevant page.

## AMP or variants?
No AMP.

## Styles & utils
Included in a "core" package with a shared "common" folder. Other packages bundle additional CSS as needed.

## Publish mechanism
Uses lerna to publish individual sub-packages within the repo. NPM scripts to aggregate those into types -- e.g. "dist:libs" for all components, app & data changes separate.

# Overall

**Comment by bcmn** [comment]
# Reach-UI
Reviewed by Ben & Jordan

## Structure
```
packages/
  component/
    src/
    examples/
      basic.example.js
```

`.example.js` files are programmatically fetched into Storybook.

## Tests
Jest _supposedly_ used for tests, very few to no tests written at time of writing.

## Pattern library
Storybook, programmatically fetching `.example.js` files from each package. Also has website to showcase components alongside both technical & non-technical documentation.

## AMP or variants?
No AMP.

## Styles & utils
Utils is it's own package. Each package has it's own base styles. Currently have to import both component & it's styling separately -- overriding styles is done using styled components.

## Publish mechanism
Lerna is used to publish individual components.

# Overall
Structure & storybook examples very nice, & design showcase/docs website nice.

**Comment by jtart** [comment]
## Outcomes/Potential implementations

- An experimental components package for components that are more experimental/not ready for production - material-ui-lab
- Export an individual AMP component - as materual-ui exports TS definitions
- Keep principle of single responsibility of library - !atlassian
- Have a (consistent) nested folder structure - !react-bootstrap
- A show-case/documentation website - material-ui/react-bootstrap
- Splitting of components/contexts/themes/utils - grommet
- `examples/` folder to programmatically generate stories

**Comment by ChrisBAshton** [comment]
# Ant
Reviewed by Chris and TBC.

[Ant](https://ant.design/docs/react/introduce) follows "the Ant Design specification, we developed a React UI library `antd` that contains a set of high quality components and demos for building rich, interactive user interfaces".

## Structure
Example: https://github.com/ant-design/ant-design/tree/master/components/avatar

```
components/
  avatar/         #  (or any of the many other projects!)
    index.tsx    # incorporates Interface, Props, and Class
    index.en-US.md
    index.zh-CN.md
    __tests__/  # uses Enzyme & Jest snapshots
    style/         # contains .less css (not styled-components)
    demo/
      basic.md
      dynamic.md
```

## Tests
Uses Enzyme and Jest.

## Pattern library
Uses [bisheng](https://github.com/benjycui/bisheng) to make their [site](https://github.com/ant-design/ant-design/tree/master/site).

The `demo/` folder for each component contains [markdown](https://github.com/ant-design/ant-design/tree/master/components/anchor/demo) which can be rendered as examples.

## AMP or variants?
No AMP consideration.

## Styles and utils?
Didn't have time to check this

## Publish mechanism
Publishes one module; `antd`, which can be tree-shaken when importing (e.g. `import { DatePicker } from 'antd';`). Also requires manually pulling in the styles (`import 'antd/dist/antd.css';`).

Uses [bespoke publish script](https://github.com/ant-design/ant-design/blob/master/scripts/prepub.js).

# Overall
Not keen on publishing one module - you lose the versioning of components. And not keen on the two points of import - we want styled components.

**Comment by ChrisBAshton** [comment]
Awesome, thanks everyone 🎉
