### ISSUE TITLE
Integrate Optimizely Events With Click and View Tracking

### ISSUE THREAD

**Issue by HarveyPeachey** [bbc/simorgh#9722]
**Is your feature request related to a problem? Please describe.**
As part of the Optimizely work, we need to track clicks and scroll into view for experiment variations to be able to analyse and determine what actions need to be taken, once an experiment has been completed.

**Describe the solution you'd like**
As we are using Optimizely's React SDK, which interfaces with their full stack implementation, it provides an API to be able to send events easily to Optimizely, and automatically work out which experiments are associated with those events, which is outlined in their [Easy Event Tracking](https://www.optimizely.com/insights/blog/introducing-easy-event-tracking-the-easier-way-to-understand-and-optimize-the-customer-journey/#:~:text=Easy%20event%20tracking%20eliminates%20cumbersome,from%20external%20sources%20into%20Optimizely.&text=Easy%20event%20tracking%20opens%20up,providers%20to%20integrate%20with%20Optimizely.) blog post.

We currently have two hooks setup within Simorgh that already carry out [click](https://github.com/bbc/simorgh/tree/latest/src/app/hooks/useClickTrackerHandler) and [view](https://github.com/bbc/simorgh/tree/latest/src/app/hooks/useViewTracker) tracking. One solution would be to integrate an optional parameter within these hooks, which would be used to send the events to Optimizely if the parameter were to be passed in. This is because our first experiment on the Features and Analysis component, is already using these hooks to send events to ATI.

This optional parameter would probably be the `optimizely` object which would give access to the tracking API within Optimizely's React SDK library. The SDK provides a HOC called [`withOptimizely`](https://github.com/optimizely/react-sdk#tracking), which gives a component access to the Optimizely API, then within that component you would pass the Optimizely object into the View and Click tracking hooks.

There might be another way to implement tracking, and that's consuming the `OptimizelyContext` pointed out by another user https://github.com/optimizely/react-sdk/issues/78#issuecomment-716439981

Events are setup within the Optimizely Experiment UI, send a message in the #group-news-ws-ab-testing channel on slack to gain access to the Full Stack project. The events will also need to be added to the Metrics section of an experiment to see them working.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by pvaliani** [comment]
For testing purposes it would be good to have a page to test which has only one promo in Features & Analysis to check if Optimizely will still run as intended. It's possibly an unlikely scenario but would be worth checking. 

 @JonBeeb
