### ISSUE TITLE
AMP media player placeholder srcset is 1 image source repeated multiple times

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#9762]
**Describe the bug**
The media player placeholder image srcset for AMP is 1 image repeated multiple times.

<img width="503" alt="Screenshot 2021-12-30 at 12 38 18" src="https://user-images.githubusercontent.com/4798332/147761584-c252988d-e378-45f0-bae6-854c3677ee85.png">

This happens because in [this file](https://github.com/bbc/simorgh/blob/latest/src/app/lib/utilities/ichefURL/index.js#L22-L24) we are returning `locator` (the image url e.g. `'https://ichef.bbci.co.uk/images/ic/1024x576/p0bdk3xv.jpg'`) when `originCode` equals `'pips'` and this function is called in a map callback of multiple image size resolutions so just returns the same image url each time.

This is not a problem on canonical because we rely on SMP built-in image placeholder which uses the correct srcset. On canonical, only use our own placeholder in a noscript tag which is displayed when js is disabled. However, like with amp, the no js placeholder srcset is incorrect so this should be fixed too.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/hausa/media-59822286.amp
2. Inspect the media player placeholder image
3. See the repeated same sized image in the srcset attribute

**Expected behaviour**
The srcset uses different sized images so that the browser can choose the most appropriate image to download and render.

We need to either fix the srcset creation for the amp placeholder or, like canonical, we use SMPs built-in placeholder. The thinking with the amp placeholder must have been that we need to use `amp-img` so we need to create our own placeholder. It's worth investigating if we can use the built-in SMP placeholder since it is in an iframe meaning we don't need to use amp elements.

As mentioned above we still need to fix the placeholder srcset creation so that is correct on canonical when js is disabled.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by paruchurisilpa** [comment]
Testing:

* Checked using the URL : http://localhost:7080/bengali/media-23269006.amp

I see the following: ( No 1024*576)

<img width="1048" alt="Screenshot 2022-01-27 at 09 20 43" src="https://user-images.githubusercontent.com/1379277/151329832-5bb3f393-9c39-4af7-ba0f-c311d7b4fc4e.png">

This is what's on live:

<img width="987" alt="Screenshot 2022-01-27 at 09 53 18" src="https://user-images.githubusercontent.com/1379277/151335859-03507315-1264-40c8-8357-ab4d85e665a8.png">

LGTM...
