### ISSUE TITLE
Track page views in Optimizley for Sty/Article pages

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9788]
**Is your feature request related to a problem? Please describe.**
Track page views for each variation in optimzley
The page already fires of an ATI event when the page loads  

**Describe the solution you'd like**
Create a new event in Optimizley to capture page views
Fire the event when the page loads. 

We can use the Optimizely object which has a track function, we can access this object with UseContext, issue explaining [this](https://github.com/optimizely/react-sdk/issues/78).

Here is an example for where the track function is used in our click tracker https://github.com/bbc/simorgh/blob/71ecd0c7f15eb1dafa496aba463b3fdf029b4b2f/src/app/hooks/useClickTrackerHandler/index.jsx#L61-L63

Try and follow what we've done for ATI analytics [here](https://github.com/bbc/simorgh/blob/latest/src/app/containers/ATIAnalytics/index.jsx), where we use this component on each page we want to track a page view, see the [Article page](https://github.com/bbc/simorgh/blob/71ecd0c7f15eb1dafa496aba463b3fdf029b4b2f/src/app/pages/ArticlePage/ArticlePage.jsx#L170) as an example.

We don't need any separation for STY and Article page reports, so page views can be combined.

**Describe alternatives you've considered**

**Testing notes**
View a page running an experiment
View each variation on the page 
Check the page views in Optimizley matches the expected value for each variation
We can disable it on the test environment, and a specific service can be chosen to test the page views are working correctly locally.
Look at disabling a specific E2E which may affect the page view event being sent.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by amoore108** [comment]
@JonBeeb What type of data are we looking to track for each of the Sty/Article pages? Taking the ATI page view tracking as an example, we send up something like the following for an Article page:
```
https://logws1363.ati-host.net/?s=598343&idclient=ed397db8-23b0-40e7-9223-0a4573e16713&s2=62&p=mundo.articles.c20myn5q195o.page&r=3008x1692x24x24&re=2350x497&hl=15x29x45&lng=en-US&x2=[responsive]&x3=[news-mundo]&x4=[es]&x5=[http%253A%252F%252Flocalhost%253A7080%252Fmundo%252Farticles%252Fc20myn5q195o]&x7=[article]&x8=[simorgh]&x9=[Mundo%2BTwitter%2BTest]&x11=[2021-06-29T11%3A07%3A41.434Z]&x12=[2021-06-29T11%3A07%3A41.434Z
```
Do we want something similar for Optimizely, without the more native ATI elements?

Do we only want to send a 'page view' if any Optimizely variation is being used?

**Comment by JonBeeb** [comment]
Just count the page view if any variation is used (so it is fired off if we hit the page event if we don't see the component).   I think we just need to send the page_view ID when we load the page https://app.optimizely.com/v2/projects/20897131008/experiments/20933791389/api_names (I think the ID will be different for different experiments. )
