### ISSUE TITLE
Add Custom Attribute to Optimizely Click Tracking for Features

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9790]
**Is your feature request related to a problem? Please describe.**
Track the component click event so it can be filtered in Optimizley.

**Describe the solution you'd like**
Set up Optimizley to use a custom attribute to segment/filter by users who have clicked the component
Pass the custom attribute with the click event sent with `optimizely.track(component_clicks)`

API for track:
`track(eventKey: string, overrideUserId?: string | EventTags, overrideAttributes?: UserAttributes, eventTags?: EventTags): void Track an event to the Optimizely results backend`

**Describe alternatives you've considered**

**Testing notes**
View a page running an experiment
View each variation on the page
Click for component on each variation
Check the results can be filtered by the clicked attribute
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by paruchurisilpa** [comment]
Testing:

Scenario 1 -- 

* Goto http://localhost:7080/mundo/articles/c45965g63xno
* On Pageload shows experiment Variation_2
* Get 1 pageview
* Scroll to the promo
* Get 1 componentview
* Refresh the page 3 times
* Get 3 pageviews
* Viewed component 2 times 
* Got 2 component views

In Optimo Viewed Features = True && Service = Mundo

Expected = 4 Pageviews 3 ComponentViews
Result = 4 Pageviews 3 ComponentViews --> Works as expected

Scenario  2 --

* Goto http://localhost:7080/mundo/articles/c45965g63xno
* On Pageload it shows experiment Variation_2
* See 1 pageview in console
* Scroll the page to see the promo
* Get 1 component view
* Click on one of the item in Promo
* Get a click event + 1 Pageview
* Refresh the page 2 times 
* Get 2 Pageviews
* Refresh the page again 
* Scroll to the promo
* Get 1 Pageview and 1 ComponentView
* Click on Promo
* Get 1 Pageview + 1 Component View + 1 Click

Expected = 6 Pageviews + 3 Component Views + 2 Clicks
Result = 6 Pageviews + 1 Component View + 1 Clicks --> Not working as expected

In Optimo Clicked Features = True && Service = Mundo
