### ISSUE TITLE
Horizontal scroll promos - layout & text clipping issues on Firefox 48 + Edge 18

### ISSUE THREAD

**Issue by skwong25** [bbc/simorgh#9797]
**Describe the bug**
* **Firefox 48 on Desktop**
     * Content is right-aligned/left-aligned on the page and third card is hidden.
     * The scroll bar is present but is not obviously a navigation scroll bar.
     * Card text overflows incorrectly (see screenshot 1 below)

* **Edge 18.x on Desktop** 
    * Card text is clipped without the ‘…’ that usually denotes ellipsis. (see screenshot 2 below)

<img width="1791" alt="Desktop Firefox 48 RTL " src="https://user-images.githubusercontent.com/59804681/149376604-03fb5ca7-de45-46e9-a3d1-c56415c5704d.png">

<img width="1787" alt="Desktop Windows 10 Edge 18 x - ellipsis " src="https://user-images.githubusercontent.com/59804681/149376885-3ffe730b-32a5-4a62-9a55-2004dfb8be63.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to links on test:
* https://www.test.bbc.com/arabic/articles/cjn2e0jek55o (RTL script) 
* https://www.test.bbc.com/pidgin/articles/crrrkxz2k0ko
2. Scroll down to view multi-card promos

**Expected behaviour**
Page content should be centred in the column. 
A third card in a multi-card promo on Desktop is usually visible without scrolling. 
Text should wrap up to a three lines and then be clipped with an ellipsis. 

**Smartphone (please complete the following information):**

- Device: Desktop 
- OS: Windows 10
- Browser/Versions: Firefox 48 & Edge 18.x

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
See original issue/ feature request ticket #9697 
Fixed by Pull Request #9729

**Comment by skwong25** [comment]
Firefox 48 & Edge 18 are currently Level B supported browsers as per February 2021 list. This may change in the next update. Awaiting confirmation of updated Browser Support list before we know if this bug needs fixing.

**Comment by aeroplanejane** [comment]
Hey @skwong25 @JonBeeb has done an analysis and it looks like Firefox 48 accounted for 0.21% of all traffic and Edge 18 accounted for 0.01% of traffic in the last quarter. We are going to close this issue and update the browser support list early next week. Thanks for raising and testing so thoroughly.

**Comment by aeroplanejane** [comment]
This is actually in the process of being fixed! Will leave open.
