### ISSUE TITLE
Run End to End tests on CI

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#98]
**Is your feature request related to a problem? Please describe.**
Currently, end to end tests are not run on CI - only linting and unit tests are.
This can cause problems, such as this one, where Cypress end to end tests that were merged into `latest` failed. 

**Describe the solution you'd like**
To add end to end tests on Travis CI

**Comment by jamesbhobbs** [comment]
@sareh from the perspective of this repo this task is done, fixing it on jenkins is in our private repo only.
