### ISSUE TITLE
Podcast Promo displaying in the wrong position 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#9820]
**Describe the bug**
The podcast promo occasionally renders in the wrong position on STY pages. 
I've seen a couple of examples but have only been able to reproduce on Hindi

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.bbc.com/hindi/india-60128834 '
2. Scroll down to the end of the article
3. Note the position of the podcast promo

**Expected behaviour**
The podcast promo should appear inline in the body of the article and not below the onward journeys at the end of the article

**Screenshots**
![Screenshot 2022-01-25 at 16 59 49](https://user-images.githubusercontent.com/22519682/151025579-b4ef81fa-e0fe-43f5-8f31-4abe4d6247a0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by paruchurisilpa** [comment]
Testing:

URL's:
* http://localhost:7080/hindi/india-60167798
* http://localhost:7080/russian/news-60171262
* http://localhost:7080/russian/news-60167667
* http://localhost:7080/persian/iran-60165609

LGTM...

**Comment by DarioRusso1** [comment]
Account test: please ignore :D
