### ISSUE TITLE
Hindi experiment: - Var B - Related content

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9870]
**Is your feature request related to a problem? Please describe.**
Overview

This will show 4 promos in the ‘Related content’ component replacing the editorially chosen content

The title will stay the same as the title on the Recommendations component

Up to 4 promos will be shown in order based on the recommendations endpoint

Dates will not be shown in the promos

Optimizley view and click events will need to be added to the whole block (this is currently implemented in ATI)

UX
Experiment Designs: https://zpl.io/aXyyrE8

Live CPS Related Content designs: https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/613a13351714592686b37888

A11y
This should be the same as what’s live for current related content:
Live CPS Related content (labelled as 'More on this story' on the design): https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/6125660245e314a3399ef4d3

Test
Use the whitelist in Optimizley to show variation on Test

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by amoore108** [comment]
Title to be used:
```
  const title = pathOr(
    'You may also be interested in',
    ['recommendationTitle'],
    translations,
  );
```

**Comment by JonBeeb** [comment]
The (final) text will be
Recommended Stories and More Recommended Stories 
(waiting for translations)

**Comment by JonBeeb** [comment]
Recommended stories — ये भी पढ़ें
More recommended stories — कुछ और जानिए
