### ISSUE TITLE
Hindi experiment - Var C - EdOJ

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9871]
**Is your feature request related to a problem? Please describe.**
Overview

This will show a max of 3  promos in the component

This will be shown after the 5th paragraph

Component should render the same as the Optimo version, the main difference being that this component will have a title

The designs show the icons and duration, however these are **not required** for this implementation

Up to 3 promos will be shown in order based on the recommendations endpoint

Optimizley view and click events will need to be added to the whole block (this is currently implemented in ATI)

Q: This block does not currently exist on CPS pages, so can we easily reuse the Optimo version?

Examples:
https://www.bbc.com/kyrgyz/articles/c4nl7rq7yjlo

UX
Designs: https://zpl.io/aXyyrE8

A11y
Design: https://app.zeplin.io/project/6216b3ee60424c97dc083cc0/screen/6216b77d88b7b7880b765350

Test
Use the whitelist in Optimizley to show variation on Test

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by amoore108** [comment]
Title to be used:
```
  const title = pathOr(
    'You may also be interested in',
    ['recommendationTitle'],
    translations,
  );
```

**Comment by JonBeeb** [comment]
The (final) text will be
Recommended Stories and More Recommended Stories 
(waiting for translations)

**Comment by JonBeeb** [comment]
Recommended stories — ये भी पढ़ें
More recommended stories — कुछ और जानिए
