### ISSUE TITLE
Topic Tracking - Chartbeat Integration

### ISSUE THREAD

**Issue by rebeccamcginn** [bbc/simorgh#9885]
**Is your feature request related to a problem? Please describe.**
Add Chartbeat integration to Topics.

Related to issue #https://github.com/bbc/simorgh/issues/9892

**Describe the solution you'd like**
- Add Chartbeat tracking to Topic pages (Chartbeat is already integrated on Simorgh). The page will be index in chartbeat with the following tags '{service},  {service} - Topics' For example the page https://www.bbc.com/mundo/topics/c95y3rn3gkjt will have tags 'mundo, mundo - topics'

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by paruchurisilpa** [comment]
Testing:

https://test.bbc.com/mundo/topics/c28j4ek229kt?morph_env=test

Can see both 'mundo' and 'mundo-topics'

<img width="1366" alt="Screenshot 2022-03-11 at 17 05 00" src="https://user-images.githubusercontent.com/1379277/157913812-92af5b21-7c3a-4652-8308-bee03bb869f0.png">
