### ISSUE TITLE
Redirect `.co.uk` traffic to `.com` in Mozart

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#989]
**Is your feature request related to a problem? Please describe.**
Currently both `www.(test.)bbc.co.uk/news/articles*` and `www.(test.)bbc.co.uk/news/articles/*` have a successful server render via Mozart. However, inline links to articles do not work on `.co.uk` due to CORs errors when requesting the JSON payload from Mozart. We will look into fixing the CORs error in [this issue](https://github.com/BBC-News/simorgh/issues/1012) but in the meantime we should serve articles only on `.com`. 

**Describe the solution you'd like**
We should add a redirect in [mozart-routing]() for articles traffic on `.co.uk` to route to `.com`.

**Describe alternatives you've considered**
We could change the configuration in the traffic managers to only open a route for `.com` to Mozart. However, this would mean that `.co.uk` requests will fall through to the top level PAL route per service which creates inconsistency between `bbc.com/$SERVICE/articles/*` and `bbc..co.uk/$SERVICE/articles/*`. 

**Testing notes**
[Tester to complete]

Dev insight: As this is dependant on mozart changes it will need regression testing once the code is promoted onto  TEST/LIVE. We could also add E2E tests to ensure that `.co.uk` traffic is redirected to `.com` for TEST and LIVE. 

**Additional context**
Pasted from Slack #mozart-devs on 26/11/18
>Phil Lee [12:05 PM]
Hey Mozart people, does mozart redirect traffic at all? Maybe somewhere in the routing?

>Ryan Wood [12:08 PM]
We redirect http traffic to https, we also redirect market data urls, and redirect old topic ids to the new topic ids
oh and recently we also added redirect support for local news pages that have moved
HTTP redirects logic: https://github.com/bbc/mozart-routing/blob/master/src/lib/mozart_routing/middlewares/https_redirector.rb
Market data redirects: https://github.com/bbc/mozart-routing/blob/master/src/lib/mozart_routing/middlewares/redirector.rb
The local news/topic page redirects are based on the responses of contexts. If the contexts asks to redirect like this:
https://github.com/bbc/mozart-controller/blob/master/src/contexts/news/tipo/tipo_redirector.rb or https://github.com/bbc/mozart-controller/blob/master/src/contexts/news/local_news_locator/local_news_redirector.rb
then this is passed back to routing and routing serves the user a 301/302 (edited)

>Phil Lee [12:14 PM]
So in the use case that articles want to redirect all `.co.uk` traffic to `.com` I’d probably want to create a new middleware, correct?

>Ryan Wood [12:16 PM]
Yep, if you want those redirects in Mozart that’d be where to do it. `.co.uk` -> `.com` sounds like something that would better be achieved at the traffic manager level, although arguably that’s the case with the http/https redirects too now

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
No longer doing the redirect.
