### ISSUE TITLE
Add ATI tracking to Topic page

### ISSUE THREAD

**Issue by nicola-d-bbc** [bbc/simorgh#9892]
The current Topic pages have ATI page tracking, which is the minimum for the new pages.
Ideally, we can add chartbeat to the pages and any other ATI tracking.

**Describe the solution you'd like**
- Click and view level tracking for mobile and desktop for new Topics page via ATI
This is currently done in Morph via reverb, so these values will need to be replicated in Simorgh
- This can use the same code as the homepage but change x7 value to reflect the page type ( x7=[index-category] )

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
- Current Topic page with tracking: https://www.bbc.com/pidgin/topics/c95y35941vrt

*Current Reverb tags:*
```
https://a1.api.bbc.co.uk/hit.xiti
?s=598342
&idclient=2704e4bc-fa8e-457c-b8c9-50652587fd5c
&ts=1643898538691
&vtag=5.29.1
&ptag=js
&r=1920x1080x24x24
&re=1920x541
&hl=14x28x58
&lng=en-GB
&idp=1428583918370
&jv=0
&p=pidgin.topics.c95y35941vrt.page
&s2=70&x2=[responsive]
&x3=[news-pidgin]
&x4=[pcm-NG]
&x5=[https%3A%2F%2Fwww.bbc.com%2Fpidgin%2Ftopics%2Fc95y35941vrt]
&x7=[index-category]
&x8=[reverb-3.3.0]
&x9=[Donald%20Trump%20-%20BBC%20News%20Pidgin]
&content_type=index-category
&language=pcm-NG
&library_version=reverb-3.3.0
&app_name=news-pidgin
&app_type=responsive&ref= 
```

*Current output from Simorgh index:*
```
https://a1.api.bbc.co.uk/hit.xiti
?s=598342
&idclient=2704e4bc-fa8e-457c-b8c9-50652587fd5c
&s2=70
&p=pidgin.page
&r=1920x1080x24x24
&re=1920x541
&hl=14x33x27
&lng=en-GB
&x1=[urn%3Abbc%3Acps%3A52f3c7b1-83ed-2338-e050-17ac8045cd94]
&x2=[responsive]
&x3=[news-pidgin]
&x4=[pcm]
&x5=[https%253A%252F%252Fwww.bbc.com%252Fpidgin]
&x7=[index-home]
&x8=[simorgh]
&x9=[Domot%2B-%2BBBC%2BNews%2BPidgin]
&x11=[2017-07-07T15%3A16%3A48.000Z]
&x12=[2022-02-03T14%3A17%3A51.000Z]
```

**Comment by ryanmccombe** [comment]
**Step 1: Import and add ATIAnalytics to the TopicPage component:**

```javascript
import ATIAnalytics from '#containers/ATIAnalytics';
<ATIAnalytics data={pageData} />
```

**Step 2. Create a new function that converts page data to the ATI values we want.**  See this for an example:
https://github.com/bbc/simorgh/blob/99845a11cadcf4c908059c4b966f09a057fdd480/src/app/containers/ATIAnalytics/params/media/index.jsx

These functions set the values to meaningful names, but in ATI they have names like `x7`
This mapping happens here:  https://github.com/bbc/simorgh/blob/latest/src/app/containers/ATIAnalytics/atiUrl/index.js

Eg, the `contentType` becomes `x7`: https://github.com/bbc/simorgh/blob/latest/src/app/containers/ATIAnalytics/atiUrl/index.js#L145

**Step 3: Once our new function is created, update `pageTypeHandlers` to map the page type to our function:**

https://github.com/bbc/simorgh/blob/latest/src/app/containers/ATIAnalytics/index.jsx#L19

Eg:

```javascript
{
  // ...
  TOPIC: myNewFunction,
  // ...
}
```
note: `TOPIC` comes from here: https://github.com/bbc/simorgh/blob/66149d2e571ec810b2f2492cc9b4106bfd7c1a17/src/app/routes/utils/pageTypes.js#L13

Consider refactoring that object so we're not using magic strings, eg:

```javascript
import * as pageTypes from '#app/routes/utils/pageTypes'

{
  // ...
  [pageTypes.TOPIC_PAGE]: myNewFunction,
  // ...
}
```

Complete example of adding ATI is here:
https://github.com/bbc/simorgh/pull/2971
