### ISSUE TITLE
Topic Page - Web Vitals

### ISSUE THREAD

**Issue by RetiredBlob** [bbc/simorgh#9900]
**Is your feature request related to a problem? Please describe.**
Our topic page implementation is not compatible with web vitals reporting.

Web Vitals expected the page type to be available on `pageData.metadata.type` - this is not the case for the data being returned from the BFF.

We should update the BFF to support this, or update the Web Vitals code to support the topic implementation:

https://github.com/bbc/simorgh/blob/cdf5c11f3087f87a57f95afc8fefeb3e53c4e3ff/src/app/Layouts/defaultPageWrapper.jsx#L34

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by rebeccamcginn** [comment]
Page type is set in getInitialData. Added for Topic pages as 'Topic'
