### ISSUE TITLE
Remove ServiceContext dependency from Brand

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#994]
**Is your feature request related to a problem? Please describe.**
ServiceContext usage should be in containers/, not components/.

Ideally we would initialise Brand with a `service` _prop_, rather than rely on context.

https://github.com/BBC-News/simorgh/blob/latest/src/app/components/Brand/index.jsx#L74-L78

**Describe the solution you'd like**
Create a BrandContainer, which uses ServiceContext logic, and passes a prop to the Brand component, thereby removing the ServiceContext from the presentational component.

Also remove the Header component, replace with `<header>` html directly in the containers/Article.jsx, and pull in the new BrandContainer inside this HTML.

**Describe alternatives you've considered**
N/A

**Testing notes**
Regression testing for the branding on both the header and footer. This would be looking at the responsive style, current/future/older versions of web browsers and non-JS behaviour.

Dev insight: Just regression tests needed. Everything should look identical.

**Additional context**
This is a prerequisite for moving to the Psammead component library - we want the Brand component to be as reusable as possible.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
I disagree with removing the Header because we tie ourselves to the articles always having a `<header>` we also lose the reuse-ability of the component and the detailing of the `role` attrb acting as an Accessibility landmark

**Comment by radiocontrolled** [comment]
@pjlee11 @ChrisBAshton 
I'm not sure about getting rid of Header either. It's possibly very useful as a reusable, accessible component (in Simorgh, and elsewhere).

Although if we do get rid of Header, we could always add documentation to the Article container explaining that a11y reasoning behind `<header role="banner">` (we might also explain why we have a ` <main role="main">`, another landmark). So if we lose the Header as a component we should consider creating a documentation issue for this.

**Comment by ChrisBAshton** [comment]
Happy to keep the header. Just to document - the thinking around removing it was to try to avoid passing a prop down two layers of components, and given we have an inline `<main>` already I didn't see much value in a separate `<header>`.

**Comment by sareh** [comment]
@pjlee11 @radiocontrolled @ChrisBAshton @bcmn 

If we keep the Header component, it would be only:
```
<header role="banner">{children}</header>
```
It is just the semantic element without any styles at all associated with it, so it won't be visible in Storybook. 

Instead of creating a BannerContainer, we should make it a HeaderContainer:

Option 1) https://github.com/BBC-News/simorgh/pull/1023#discussion_r237571744
```
const HeaderContainer = () => (
  <header role="banner">
    <ServiceContextConsumer>
      {({ brandName }) => <Brand brandName={brandName} />}
    </ServiceContextConsumer>
  </header>
 );
```

Option 2) `<header role="banner">{children}</header>`
```
const HeaderContainer = () => (
  <Header>
    <ServiceContextConsumer>
      {({ brandName }) => <Brand brandName={brandName} />}
    </ServiceContextConsumer>
  </Header>
 );
```
We should choose between these options. I'd be interested in hearing your views on this.

**Comment by radiocontrolled** [comment]
@pjlee11 @radiocontrolled @ChrisBAshton @bcmn
On preview I would say Option 1) #https://github.com/BBC-News/simorgh/pull/1023#discussion_r237571744, on the basis that the Header component is too simple to be a component. The styling and accessibility for the logo coming from Brand, with header just providing a landmark (which we do need and should document) but doesn't necessarily mean we need a Header component on its own.

**Comment by pjlee11** [comment]
I'd say option 1 because in the current context option 2 feels like overkill and would be trivial to split out in the future

**Comment by dr3** [comment]
We had a whiteboard session earlier today
![whiteboard with a diagram of the header and footer components](https://user-images.githubusercontent.com/11341355/49383596-05496180-f711-11e8-9830-0bd01cdf8289.png)

`Red = Components`

The outcome was that header and footer wouldn't be components as they are simply a single set of html tags. Instead `Brand` and `SiteWideLinks` would be components that are extracted. These make up the "Header" and "Footer" sections of the page and the readme would give context on how they are used and what HTML tags they should be inside.

**Comment by radiocontrolled** [comment]
The Header component is being removed in https://github.com/BBC-News/simorgh/issues/994 (this issue). A HeaderContainer replaces it: 

```
const HeaderContainer = () => (
  <header role="banner">
    <BrandContainer />
  </header>
);
```

The HeaderContainer is pulled into the Article container in 994.

The Footer component is being removed in https://github.com/BBC-News/simorgh/issues/1034
