### ISSUE TITLE
[Topic Pagination] Front End

### ISSUE THREAD

**Issue by ryanmccombe** [bbc/simorgh#9943]
Following on from the prototype here: https://github.com/bbc/simorgh/pull/9937

We need to make the pager component production ready

- Implement correct design and media queries
- Implement the correct screen reader UX (To be documented on 28/3/22)
- Update the canonical tag to reflect the page number
- Implement the "page x of y" version for very small devices
   - **Question**: do we have translations for this?
   - https://docs.google.com/spreadsheets/d/1AoNAmrhCCh9Pt9BbvGCVVSESHAcNtOn8MjRJRbCjpyw/edit#gid=35115428
   - If translation is not available, use English until we can get the translation 
- Implement a11y acceptance criteria
   https://paper.dropbox.com/doc/Pagination-AAC-TBC--BcyvOnpV5Gz1GnhwYYW6MEO5AQ-nSpURxA1JM10XCYBYsWYr
- Code cleanup and refactor
- Unit tests

**Comment by JonBeeb** [comment]
Translations will be captured here. 
We are currently asking for the following

"previous page/back", "next page/forward", 
"Page","of" (To construct the Page text ('Page' _n_ 'of' _n_)  

https://docs.google.com/spreadsheets/d/1AoNAmrhCCh9Pt9BbvGCVVSESHAcNtOn8MjRJRbCjpyw/edit#gid=35115428

**Comment by ryanmccombe** [comment]
👍 Cheers Jon - moving to blocked for now

Aside from translations, I also have these 4 questions:

1 - AC asks we not use colour alone to denote states.  Design, PS implementation and GEL guidelines are doing this

![Screen Shot 2022-03-16 at 08 48 00](https://user-images.githubusercontent.com/8601460/158551670-919401a3-343d-4558-9fef-cd0501c066ba.png)

Should I follow design or a11y a/c?

2 - A11y AC says the "disabled" arrows should have a contrast ratio of at least 4.5.  Design, PS implementation and GEL guidelines have contrast ratio of around 2.9

Should I follow design or a11y a/c?

3 - Unclear if "disabled" arrows should be interactive / focusable - eg, the previous arrow when user is already on the first page.  One AC says they should, another says they should not

What should happen here?

4 - JIRA ticket says we should not be collapsing unnecessarily - eg we should not replace a single page with an ellipsis.  This seems to be from GEL:

![Screen Shot 2022-03-16 at 08 45 42](https://user-images.githubusercontent.com/8601460/158551888-6e498928-0f30-4dea-92c1-9cc099b48e0d.png)

Miro board asks us to do the thing JIRA/GEL tells us not to do:

![Screen Shot 2022-03-16 at 08 58 29](https://user-images.githubusercontent.com/8601460/158553637-ba5ca8e2-ce32-4025-b672-cafd79a419e9.png)

I think the Miro board is based on the PS implementation, which is not following the GEL guidelines in this regard.

I'm pretty sure this is simply a PS bug rather than intentional?  Not sure we should be replicating bugs for the sake of consistancy?

**Comment by RetiredBlob** [comment]
The topic pagination front end is still waiting on code reviews here: https://github.com/bbc/simorgh/pull/9937 that should be in a relatively good place

Can do the rest when I’m back, but if anyone wants to do part 2 before then, it would be:

- Update to follow the tweaked design here: https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/623476535f2504b2ccb8e8a9
- Implementing the “page x of y” design (translations: https://docs.google.com/spreadsheets/d/1AoNAmrhCCh9Pt9BbvGCVVSESHAcNtOn8MjRJRbCjpyw/edit#gid=35115428 - use English for any missing translations)
- Implementing a11y AAC and screen reader UX

**Comment by greenc05** [comment]
All these questions, except for question 4, are now resolved now that we have confirmed designs and AAC

> 👍 Cheers Jon - moving to blocked for now
> 
> Aside from translations, I also have these 4 questions:
> 
> 1 - AC asks we not use colour alone to denote states. Design, PS implementation and GEL guidelines are doing this
> 
> ![Screen Shot 2022-03-16 at 08 48 00](https://user-images.githubusercontent.com/8601460/158551670-919401a3-343d-4558-9fef-cd0501c066ba.png)
> 
> Should I follow design or a11y a/c?
> 
> 2 - A11y AC says the "disabled" arrows should have a contrast ratio of at least 4.5. Design, PS implementation and GEL guidelines have contrast ratio of around 2.9
> 
> Should I follow design or a11y a/c?
> 
> 3 - Unclear if "disabled" arrows should be interactive / focusable - eg, the previous arrow when user is already on the first page. One AC says they should, another says they should not
> 
> What should happen here?
> 
> 4 - JIRA ticket says we should not be collapsing unnecessarily - eg we should not replace a single page with an ellipsis. This seems to be from GEL:
> 
> ![Screen Shot 2022-03-16 at 08 45 42](https://user-images.githubusercontent.com/8601460/158551888-6e498928-0f30-4dea-92c1-9cc099b48e0d.png)
> 
> Miro board asks us to do the thing JIRA/GEL tells us not to do:
> 
> ![Screen Shot 2022-03-16 at 08 58 29](https://user-images.githubusercontent.com/8601460/158553637-ba5ca8e2-ce32-4025-b672-cafd79a419e9.png)
> 
> I think the Miro board is based on the PS implementation, which is not following the GEL guidelines in this regard.
> 
> I'm pretty sure this is simply a PS bug rather than intentional? Not sure we should be replicating bugs for the sake of consistancy?

**Comment by JonBeeb** [comment]
Updated a11y / Ux  captured in this ticket : https://github.com/bbc/simorgh/issues/9984
