### ISSUE TITLE
Update Topics page visual design

### ISSUE THREAD

**Issue by gavinspence** [bbc/simorgh#9961]
**Describe the bug**
Reviewing a range of Topics pages on test has shown a number of issues we'd like to address. Updated UX designs can be found here - https://zpl.io/bLXeOjJ 

Summary of changes - 

1. Update spacing to be in line with design
2. Update grey colour of dividing lines (old spec was too dark)
3. Update grid to be consistent with other index pages
4. Update promo images to use lazy loading (See our use of `react-lazyload` for examples) (done here: https://github.com/bbc/simorgh/pull/9999)

**To Reproduce**
Steps to reproduce the behaviour: Go to any Topics page on Test and see spacing discrepancy

**Expected behaviour**
Update spacing, divider line & grid in line with design.

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by paruchurisilpa** [comment]
As disvussed with @ryanmccombe 

hi Silpa - not yet :slightly_smiling_face: can just move it to done though I think - think we are going to have a full review once the page is ready to go live

Moving this to done..

**Comment by gavinspence** [comment]
Closing as done
