### ISSUE TITLE
High Impact Promo  - Desktop & Mobile Design Updates

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#9971]
**Is your feature request related to a problem? Please describe.**
We want to ensure the high impact promos are to design spec before we put them live across desktop and mobile breakpoints. 

**Describe the solution you'd like**

Update the promos in features and analysis section on CPS and Optimo articles to meet the design specifications. 

**Out of scope**
The widths on the columns on desktop vary between CPS and Optimo articles, this will not be changed in these designs.
Mid / Tablet breakpoints will be tackled in this [issue](https://github.com/bbc/simorgh/issues/10014) 

**Acceptance Criteria:** 

Given I am viewing a CPS or Optimo article on desktop
When I view the features and analysis section
then the high impact promo designs meet the specifications [here](https://zpl.io/RMBW8pn) 

Given I am viewing a CPS or Optimo article on mobile
When I view the features and analysis section
then the high impact promo designs meet the specifications [here](https://zpl.io/3XZgoBW) 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by HarveyPeachey** [comment]
More styling changes needed
