### ISSUE TITLE
Pagination UX update and page limit.

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#9984]
**Is your feature request related to a problem? Please describe.**
Update pagination to match the updated UX / a11y

* Don't render 'previous page' arrow on page 1
* Don't render 'next page' arrow on last page
* Show a MAX page limit of 40 (even if there are more pages) - this may be done at the routing level.

Updated UX:
Zeplin link for latest pagination designs- https://zpl.io/EmknYqe

Screen reader UX:
- (2 arrows and numbers) https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/62347658126ad3130d85270e
- (1 arrow) https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/6220a6d1bd5af458b5c9b70f
- (Mobile) https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/6220a6d2d29bf357863f85b3

Accessibility Acceptance Criteria:
https://paper.dropbox.com/doc/Pagination-AAC--BeiYCh6ZjxAEfMq7lMLA7OQvAg-nSpURxA1JM10XCYBYsWYr

Translations:
https://docs.google.com/spreadsheets/d/1AoNAmrhCCh9Pt9BbvGCVVSESHAcNtOn8MjRJRbCjpyw/edit#gid=35115428
 

**Describe the solution you'd like**
Code comments: 

- Nav element: Use aria-label to label this
- Mobile text: use role text on span ‘page _ of _’ to ensure it is read out in one swipe
- Current page link: use ‘aria-current’ attribute with value of ‘page’ (translated)
- Ellipsis: Use role separator on the list item
- Arrow links: use aria-labelledby to negate the talkback bug for the nested spans

Code example:
```
<nav role=“navigation” aria-label=“Page”>
      <a href=“https://www.myurl.com” aria-labelledby=“previous-page”>
        <span id=“previous-page”>
          <span class=“vh”>Previous page</span>
          <svg class=“svg” aria-hidden=“true” focusable=“false”>Arrow</svg>
        </span>
      </a>
      <div class=“mobile-breakpoint-only”>
        <span role=“text”>Page <b>1</b> of <b>999</b></span>
      </div>
      <ul role=“list”>
        <li><a href=“?page=1”>1</a></li>
        <li><a href=“?page=2" aria-current=“page”>2</a></li>
        <li><a href=“?page=3">3</a></li>
        <li><a href=“?page=4”>4</a></li>
        <li><a href=“?page=5">5</a></li>
        <li><a href=“?page=6”>6</a></li>
        <li><a href=“?page=7">7</a></li>
        <li role=“separator”>
            <svg class=“svg” aria-hidden=“true” focusable=“false”>…</span>
        </li>
        <li><a href=“?page=999”>999</a></li>
      </ul>
      <a href=“https://www.myurl.com” aria-labelledby=“next-page”>
        <span id=“next-page”>
          <span class=“vh”>Next page</span>
          <svg class=“svg” aria-hidden=“true” focusable=“false”>Arrow</svg>
        </span>
      </a>
    </nav>
```

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Comment by YanLS01** [comment]
Adding Zeplin link for latest pagination designs- https://zpl.io/EmknYqe
